### ISSUE TITLE
can.map instance / property batching

### ISSUE THREAD

**Issue by shcarrico** [canjs/canjs#1002]
I would like to discuss an interface for property batches for a specific bit of a map.

##### problem
changes to child properties bubble out of parent properties. Handlers bound to parent properties are called multiple times, requiring debouncing or similar to avoid repeated triggering of bound handler functions. There are strange behaviors introduced by many debounces, as well as performance implications of clearing the stack between multiple property handlers bound via debounce.

##### proposed solution
some sort of property specific batch that would trigger a single change event on the higher level property, ie

```javascript
var map = new can.Map({ foo : { bar : [], baz : {} }});

map.attr('foo').startBatch( /*optional argument of batch id as string*/ );
map.attr('foo').attr('bar').push('bat') //no change event for foo
map.attr('baz').attr('biz','bit') //no change event for foo

map.attr('foo').stopBatch( /*optional argument of batch id as string, 
or stop all batches on this property */ ); //change event triggered
//change event data should include a list of all changes applied in batch 
```
This way, we get an atomic change from the parent property. This would also allow async updates to a child property in combination with sync updates w/o causing multiple change events from the parent. One could facilitate legit use cases for multiple changes via batches by using the optional batch ID param.

**Comment by justinbmeyer** [comment]
Binding to "change" is deprecated and will not be possible in `DefineMap` in 3.0.  Also, the use of the define plugin should remove the need to solve this problem in most apps and code.

However, a solution to do this might look like:

```js
var handler = function(){
  // stuff to do on one batch
};

var batcher = makeBatchBinder(handler);

map1.bind("prop1", batcher);
map2.bind("prop2", batcher);

makeBatchBinder = function(handler){
  var lastBatch;
  return function(ev){
    if(!ev.batchNum || ev.batchNum !== lastBatch) {
      lastBatch = ev.batchNum;
      return handler.apply(this, arguments);
    }
  }
};
```

If this is something someone would like to see in 3.0, please create an issue in /canjs/can-event .
