### ISSUE TITLE
Pass the element in options to stache helper 

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#1008]
Opened following https://github.com/bitovi/canjs/issues/893

Is it possible to pass a reference to the element for stache view helpers?

```HTML
<li class="{{myClassHelper}}">some text</li>
```

**Comment by justinbmeyer** [comment]
I'd be happy to get this into CanJS, but I'm closing this do to lack of interest.  It's pretty easy to do if anyone wants to pick it up.  Please create an issue in [can-stache](/canjs/can-stache).
