### ISSUE TITLE
Include can/construct/super in the core build

### ISSUE THREAD

**Issue by andykant** [canjs/canjs#1020]
We should add `can/construct/super` to the core CanJS build. We talked about it a long time ago, and I thought we were even planning on doing so, but it hasn't happened yet.

It doesn't have a huge footprint and is more or less invaluable when dealing with derived classes. I use it pretty extensively in the majority of the projects I've been working on.

Specifically, I think we should bake it directly into `can/construct` and leave `can/construct/super` as an empty alias plugin until we can deprecate it in a later version (3.0?).

**Comment by justinbmeyer** [comment]
Closing for https://github.com/canjs/can-construct/issues/4
