### ISSUE TITLE
can.route needs clear specificity rules

### ISSUE THREAD

**Issue by daffl** [canjs/canjs#1023]
One of the biggest confusions for beginners using can.route seems to be that there are no clear rules in what order routes are being matched. Most routing libraries have fairly clear specificity rules but with `can.route` matched routes seem to be entirely dependent on when they are set up. Considering the following two controls using can.Control.route the result when setting the hash to `#!todos/6` is different:

```js
// This will match :type/:id route
var Routing = can.Control({
    ':type/:id route': function(data) {
        console.log('Routing1 :type/:id route', data);
    },
    
    'todos/6 route': function(data) {
        console.log('Routing1 todos/6 route', data);
    }
});

// This will match todos/6 route
var Routing = can.Control({
    'todos/6 route': function(data) {
        console.log('Routing1 todos/6 route', data);
    },

    ':type/:id route': function(data) {
        console.log('Routing1 :type/:id route', data);
    }
});
```

**Comment by justinbmeyer** [comment]
Closing for the above issue in `can-route`
