### ISSUE TITLE
can.route url slashes are encoded to 2%F

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#1027]
@whitecolor 's original post:

> Due to use of ```encodeURIComponent``` in route.js param function url slahes (```/```) are converted to > ```2%F```. This is actual for pushstate urls.

> Think this is not a correct behaviour.

My interpretation:

Slashes (`/`) in `can.route.attr` values like "foo/bar" are converted to `"foo2%Fbar"`.  He doesn't think this is the correct behavior.

**Comment by justinbmeyer** [comment]
@moschel Can you clarify what you mean here:

> For example, if you have a rule like can.route(":page\.html") and a url like foo/bar.html, can.route.attr('page') will be "foo/bar" and that value will get escaped.

Specifically "that value will get escaped" ... what value?  Escaped how?
