### ISSUE TITLE
can.Model's events should be postponed with can.batch.start/stop

### ISSUE THREAD

**Issue by kir** [canjs/canjs#1056]
Hello,

  I'm writing an app where can.Model is extended to store data in IndexedDB database.
  In some operations, I have to update a bunch of records at a time, ~100. 

  I wrote a custom change handler, which updates UI on change. To consolidate multiple updates into one, I use can.start/stop + delayed UI update with setTimeout. 

  But, on record updating in IndexedDB I still get "updated" events even after can.start. I can workaround it by setting larger timeout in setTimeout in UI handler, but this is non-deterministic, so I think it is better to block can.Model events temporarily with can.batch as well.

   http://jsfiddle.net/maxkir/BYCLR/

  Thanks for considering this.

**Comment by justinbmeyer** [comment]
This should absolutely happen.  I'm not sure how I missed this.  Adding to can-connect's issues.  Thanks for reporting.
