### ISSUE TITLE
route is called twice when routing from within a route

### ISSUE THREAD

**Issue by sociocast-leroy** [canjs/canjs#1062]
Confusing title, I know... not sure how else to title this, though.
as per http://jsfiddle.net/weCsR/8/ , you see that the 'projects' route handler is called twice.

matt444 on irc found a workaround, http://jsfiddle.net/weCsR/9/ , by delaying the call that changes the route, but that doesn't explain why it happens?

**Comment by justinbmeyer** [comment]
This is indeed a bug.  However, as can/control/route is deprecated, it's unlike we're going to prioritize fixing this.  Moving it to an issue `can-control-route`.
