### ISSUE TITLE
Bug in view.mustache Passing Partials in Options

### ISSUE THREAD

**Issue by znajem** [canjs/canjs#1068]
The following code works:

    can.mustache('outer','<h1>Hello, {{name}}!</h1>{{>partial}}') ; 
    can.mustache('inner','<h2>it works!</h2>') ; 
    $('body').empty().append(can.view('outer',{
        name: 'World',
        partial: 'inner',
    })) ; 

If however, you rename the 'parital' key to anything else, as in the following example, it doesn't work...

    can.mustache('outer','<h1>Hello, {{name}}!</h1>{{>part}}') ; 
    can.mustache('inner','<h2>it works!</h2>') ; 
    $('body').empty().append(can.view('outer',{
        name: 'World',
        part: 'inner',
    })) ; 

To fix, I removed the single quotes around the literal string 'partial' in the 'if' statement on lines 1697--1699 in /view/mustache.js

    if (scope.attr('partial')) {
        partial = scope.attr('partial');
    }

**Comment by justinbmeyer** [comment]
This was fixed some time ago: https://github.com/canjs/can-mustache/blob/master/src/can-mustache.js#L1734
