### ISSUE TITLE
Dependencies on can/view/mustache should be eliminated

### ISSUE THREAD

**Issue by daffl** [canjs/canjs#1077]
Since there is now a replacement engine with can.stache, dependencies to `can/view/mustache` in e.g. `can/component` (https://github.com/bitovi/canjs/blob/master/component/component.js#L12) or `can/view/bindings` (https://github.com/bitovi/canjs/blob/master/view/bindings/bindings.js#L6) should be removed otherwise a production build will always contain the Mustache engine.

**Comment by justinbmeyer** [comment]
Closing as this is fixed in 3.0, but done in all of those individual repos.
