### ISSUE TITLE
can.Model resource not handling custom id property

### ISSUE THREAD

**Issue by alexisabril** [canjs/canjs#1084]
When using "resource" as a shortcut in can.Model, the api signatures generated are incorrect when using the custom id property.

```
var Foo = can.Model.extend({
    resource: '/foos'
}, {});

var Bar = can.Model.extend({
    id: 'Id',
    resource: '/bars'
}, {});

Foo.findOne({ id: 0 });
//Bar.findOne won't invoke an ajax request
Bar.findOne({ id: 0 });
```

This is due to https://github.com/bitovi/canjs/blob/master/model/model.js#L1077

I believe that line should be:

```
return resource + "/{id}"; //"id" will be looked up as model.id when we parse this string
```

**Comment by justinbmeyer** [comment]
In `can-connect`, the rules are as follows:

1. Identify your __id__ property with your set algebra:

  ```
  new set.Algebra(set.comparators.id("_Id"))
  ```

2.  Use the actual property when writing out your urls:

  ```
  url: {
    getData: "/things/{_Id}"
  }
  ```

3.  Use the actual property when making requests:

  ```
  Task.get({_Id: 5});
  ```
