### ISSUE TITLE
Enable can-value for input element update on "input" event 

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#1088]
Now with can-value for input element attribute's value is updated on "change" event. It would be nice to have out of the box capability to have the value updated on instant user text change (```input``` event). Not sure what API shouldbe used maybe some additional attribute on the element to indicate that ```input``` not ```change``` event should be handled.

**Comment by imjoshdean** [comment]
Gonna bump this but put a spin on it.

I don't necessarily think that can-value should update on `input`, but I do think we should update our stuff to support `can-input` and `($input)`

**Comment by justinbmeyer** [comment]
@imjoshdean does that not work?  `($input)` should work in every browser that supports it.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/canjs/issues/1088
