### ISSUE TITLE
JSON POST sends url_encoded_form content type instead of application/json

### ISSUE THREAD

**Issue by beno** [canjs/canjs#111]
Unlike any of the other jsMVC  frameworks that I am aware of CanJS submits its POST requests as url_encoded_form data instead of application/json. Is there a specific reason for this?

I would like to be able to send ajax requests with something like:

      contentType: 'application/json',
      dataType: 'json',
      headers: {
        'X-Requested-With': 'XMLHttpRequest'
      }

Can I do this? If so, how?

Thanks,
Michel

VOTE FOR THIS HERE: http://bithub.com/event/25916

**Comment by justinbmeyer** [comment]
Closing for the issue in can-connect.

**Comment by beno** [comment]
Just got bit by this again: I can't believe I am googling my own post here. Am I really the only one bothered by this?

Anyway, the problem is submitting an object with a nested array of objects:

    {foo: "foo", bars: [{bar: "bar"}]}

Submitting a JSON here would be trivial, but posting a encoded form turns this into

    q = jQuery.param({foo: "foo", bars: [{bar: "bar"}]})
        #=> "foo=foo&bars%5B0%5D%5Bbar%5D=bar"
    
which on a server turns into

    {"foo"=>"foo", "bars"=>{"0"=>{"bar"=>"bar"}}}

So now I am forced to create different code paths for submitting a urlencoded form or a JSON, which is not an acceptable option. Any help here?

**Comment by justinbmeyer** [comment]
Use a jquery Ajax prefilter to convert post/put into JSON across your app. 

Example: https://github.com/donejs/bitballs/blob/master/public/util/prefilter.js

can-connect now sends JSON by default.
