### ISSUE TITLE
Define plugin supporting can.List 

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#1127]
http://jsfiddle.net/xKc3H/399/

```javascript
var List = can.List.extend({

    define: {
        user: {
            get: function(){
                return 'xxx'
            }
        }            
    
    }
    
})

var list = new List()
```

throws
```Uncaught TypeError: Cannot read property 'user' of undefined ```

I think it is the same issue that can.List never supported can.compute on prototype.

**Comment by imjoshdean** [comment]
Happened to just run into a need for this. Giving it a :+1:

**Comment by justinbmeyer** [comment]
@imjoshdean what would this look like?

**Comment by imjoshdean** [comment]
The situation I needed it for was a virtual getter property to check the validity of all the items in a list:

```javascript
var Items = can.List.extend({
	Map: SomeItem
}, {
	define: {
		areValid: {
			type: 'boolean',
			get: function() {
				var areValid = true;

				this.each(function(item) {
					areValid = item.attr('someCondition');

					return areValid;
				});

				return areValid;
			}
		}
	}	
});

new Items().attr('areValid'); // -> true | false
```

I can't imagine this would look any different on a `can.List` than it would on a `can.Map` honestly.

**Comment by justinbmeyer** [comment]
@imjoshdean why couldn't that just be a simple function?

**Comment by imjoshdean** [comment]
That particular one might be able to be a simple function, though I happen to want to value to be live bound, but couldn't that argument be made for any virtual getter property?

```javascript
var Person = can.Model.extend({
    define: {
        fullName: {
            get: function () {
                return this.attr("first") + " " + this.attr("last");
            }
        }
    }
});```

`fullName` could be a simple function as well.

**Comment by justinbmeyer** [comment]
@imjoshdean somewhat yes, but there's also a need for setters, type conversion, async getters.  It would be weird to call `this.attr("fullName", "Something new")` to write, but `this.fullName()`to read.  

I think it's likely those things could be used on a list too.

**Comment by imjoshdean** [comment]
So, I think we are both agreed - this is something that would be beneficial to add, yes?

**Comment by justinbmeyer** [comment]
yeah, probably.  I am actually thinking more about how define should be used for the items within the list, not the expandos.

**Comment by imjoshdean** [comment]
Do you mean something such as this?

```javascript
var List = can.List.extend({ }, {
	define: {
		'0': {
			// By default, the first item in every list should be the beginning
			// of 2016 (for whatever reason).
			value: function() {
				retur new Date('1/1/2016');
			}
		}
	}
});```

**Comment by justinbmeyer** [comment]
or `*` to apply to any item in the list.

**Comment by imjoshdean** [comment]
That one is definitely trickier, unless we assume that everyone will only get items from an array with an iterator such as `can.each` or `can.List.prototype.each` or with `.attr()` e.g. `list.attr(0)`. Because it breaks down otherwise.

At minimum, it would be nice if `can/map/define` worked on the expando properties and maybe afterwards we went back and looked at how it should work for list items.

**Comment by dylanrtt** [comment]
I have already been using `*` with define in lists.

Example:
```js
var List = can.List.extend({
  define: {
    '*': {
      type: 'number'
    }
  }
});

var list = new List(['5', '3', '7']);

console.log(list.attr());
// [5, 3, 7]
```
http://jsbin.com/cepejemoci/edit?html,js,console

Was this not supposed to work?

**Comment by justinbmeyer** [comment]
```js
var MyList = can.List.extend({
  define: {
    idMap: {
      get: function(){
        var map = {};
        return this.each(function(item){
          map[item.attr("id")] =  item;
        });
        return map;
      }
    }
  }
});

var list = new MyList([
  {id: 1, name: "1"},
  {id: 2, name: "2"},
  {id: 3, name: "3"}
]);

console.log(list.attr("idMap"));

list.bind("idMap", function(){
  console.log("changed");
});

list.pop();
```

this should certainly work.
