### ISSUE TITLE
{{>}} doesn't render using passed-in renderers

### ISSUE THREAD

**Issue by zkat** [canjs/canjs#1145]
According to the docs on `{{>key}}`, `key` is looked up in the surrounding context, and if it's a function, will be called with the current context. Instead, it seems like the helper might be using the same lookup mechanism as `can.view()` when it looks at the literal text of `key` (without looking up `key`'s value).

Here's a fiddle:
http://jsfiddle.net/47Fw7/

Even if this isn't really what the feature was intended to do, it would be really nice to be able to do this, since in many of our projects, we always reference precompiled templates, and it would be nice to just pass those in and have them work.

**Comment by justinbmeyer** [comment]
Fixed at some point in 2.3: http://justinbmeyer.jsbin.com/zepoye/2/edit?html,js,output
