### ISSUE TITLE
Dynamic property access with mustache and stache

### ISSUE THREAD

**Issue by zkat** [canjs/canjs#1157]
[VOTE HERE](http://bithub.com/event/41611)

I've been working on converting a lot of `EJS` templates to `mustache` recently, and have found one particular pattern that I think might be worth addressing with a built-in solution.

Right now, without writing your own helper, you can't access a data property in mustache based on another property in the scope. Something like `<%= car.attr(part); %>` in `EJS` has no direct equivalent in `mustache`. To pull off the same task, you would need to write a helper, but that is only of limited utility.

This, for example, would still be fairly hard to translate:
```
<% things.attr(key).each(function(keyedThing) { %>
...
<% } %>
```

My first instinct is to propose a syntax extension that follows JavaScript conventions for dynamic field access: `obj[key]`, so you would be able to write the following to translate the above without losing the utility of `#each`:

```mustache
{{#each things[key]}}
...
{{/each}}
```

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-stache/issues/7
