### ISSUE TITLE
Partials not working with new Steal

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#1159]
Problem is due to [this code](
https://github.com/bitovi/canjs/blob/system-steal-domless/view/view.js#L101):

```js
if (url.match(/^\/\//)) {
	url = url.substr(2);
	url = ( typeof window === "undefined" || ! window.steal ) ?
		url :
		steal.config()
			.root.mapJoin("" + steal.id(url));
}
```

What is the equivalent of `steal.id` in the new Steal @justinbmeyer ?

**Comment by matthewp** [comment]
I don't think this is worth trying to fix.  Instead we should add the ~ extension to Steal. I have it mostly working here: https://github.com/bitovi/steal/tree/tilde

In 3.0 we can deprecate this.

**Comment by matthewp** [comment]
I take it back, this shouldn't be hard to fix, `getRenderer` already returns a deferred.

**Comment by justinbmeyer** [comment]
> What is the equivalent of steal.id in the new Steal

`system.normalize` - https://github.com/bitovi/legacy-steal/blob/master/steal.js#L2326

This will probably be hard to fix in "synchronous" `can.view` calls.

I think for now, we can just normalize relative to the current file (using joinURL (or whatever its called) ) and to the baseUrl.

**Comment by justinbmeyer** [comment]
(basically, no map or paths config will work)

**Comment by marshallswain** [comment]
Is this what's keeping my can.view.attrs from working in partials?  They work in the built production site, but not in development mode.

**Comment by justinbmeyer** [comment]
Make sure you import your modules that define your custom attrs.

**Comment by marshallswain** [comment]
I am importing them with <can-import> and they work in the main template
but not in the partials.

**Comment by justinbmeyer** [comment]
Your partials are importing them?

**Comment by marshallswain** [comment]
Can-import is in the main template. I haven't tried re-importing in the
partial, yet.

**Comment by marshallswain** [comment]
That worked.  Funny how I didn't try the simplest fix.

**Comment by justinbmeyer** [comment]
@matthewp I assume this is working now with `<can-import>`?
