### ISSUE TITLE
Defining attribute's merge strategy via map.define plugin

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#1170]
this
```javascript
var map = new MyMap()

map.attr({attr1: mapValue1, attr2: mapValue2})
```
would perform deep merge of attributes for attr1, attr2
`
for granular control over such merge it would be good to allow defining that particular attribute should not be merged but just set (replaced) instead for example via such api:

```javascript
var MyMap = can.Map.extend({
   define: {
       attr1: {
           merge: false
       }
   }
})

```

This issue relates to this forum post
https://forum.javascriptmvc.com/#Topic/32525000001683017
and this https://github.com/bitovi/canjs/issues/829

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-define/issues/17
