### ISSUE TITLE
Passing a boolean to can.Component

### ISSUE THREAD

**Issue by sporto** [canjs/canjs#1176]
I would like to pass a boolean to an attribute on a component. e.g.

	<client-list clients="{clients}" selectable="{true}">
	
This doesn't work. I understand that can will do a look up for a variable called 'true' in the parent scope e.g. parentScope['true'], resulting in undefined.

Fiddle here: http://jsbin.com/gibih/1/edit

This can be fixed by adding the define plug-in to the component: http://jsbin.com/hoxilelu/2/edit

But this feel awkward and it shouldn't be needed.

So please consider making it so if a {true} or {false} is passed, it is automatically converted to true/false booleans. So

	<client-list clients="{clients}" selectable="{true}">
	
would work straight out of the box.

**Comment by justinbmeyer** [comment]
The define plugin has `htmlbool`.  And it works with the new binding syntaxes: http://justinbmeyer.jsbin.com/netutu/2/edit?html,js,console,output
