### ISSUE TITLE
can-value timeout for setting

### ISSUE THREAD

**Issue by alexisabril** [canjs/canjs#1188]
Currently we have the following in bindings.js:

	"{value} change": "set",
	set: function () {
		if (!this.element) {
			return;
		}
		var val = this.options.value();

		this.element[0].value = (val == null ? '' : val);
	},

	"change": function () {
		if (!this.element) {
			return;
		}

		this.options.value(this.element[0].value);
	}

Specifically this line:

    this.element[0].value = (val == null ? '' : val);

In the scenario where a user changes an input, we have the following flow:

"change" handler invoked
options.value set
"set" function invoked

Although `this.element[0].value = (val == null ? '' : val);` is executed, the value is not actually set in the input. In most cases this goes unnoticed as the value the user typed is typically identical to the one returned from "{value}", however in cases where we are using a custom getter in a compute or attempt to format the value in any way, this becomes apparent.

Rudimentary solution would be to wrap `this.element[0].value = (val == null ? '' : val);` in a setTimeout, however maybe we should add a new set of APIs to allow filtering both on getting/setting of values.

For reference, Angular provides a "parsers" and "formatters" array to filter values, setting/getting respectively.

https://docs.angularjs.org/api/ng/type/ngModel.NgModelController
http://jsfiddle.net/SAWsA/811/

**Comment by justinbmeyer** [comment]
@alexisabril 

> Although this.element[0].value = (val == null ? '' : val); is executed, the value is not actually set in the input.

Why?  If you synchronously set `.value` after it has been changed, the user doesn't see the change?  If that's true, that's crazy.

**Comment by justinbmeyer** [comment]
I'm closing b/c I think this is fixed: http://justinbmeyer.jsbin.com/netutu/3/edit?html,js,console,output

Please re-open if I'm missing something.
