### ISSUE TITLE
stache reordering elements

### ISSUE THREAD

**Issue by savinger** [canjs/canjs#1189]
It seems as though stache is taking some liberties with my markup, whereas the can.mustache template engine displays it properly.

This...

    <span class="input-group-btn">
      <button class="btn btn-default" type="button">Go!</button>
    </span>

...renders as this...

    <span class="input-group-btn"> </span>
    <button class="btn btn-default" type="button">Go!</button>

http://jsfiddle.net/xLH4K/

**Comment by akagomez** [comment]
@daffl Can we fix this in 2.3? It's a very common "gotcha" for new CanJS devs. Related: https://github.com/bitovi/canjs/issues/1775

**Comment by justinbmeyer** [comment]
Not without breaking people's apps who rely on the behavior or adding more complex parsing rules.

**Comment by savinger** [comment]
Why would they rely on canjs to output markup different than what they declared?

**Comment by daffl** [comment]
This is similar to #1161 and #1134. The parser won't let you put block level elements within inline elements. We already changed this for links, I'm wondering if we should just turn that off completely since HTML5 seems to allow it in any case I tested.

**Comment by justinbmeyer** [comment]
Because people write markup like <li> without a closing tag pretty commonly.

**Comment by akagomez** [comment]
Can we limit that behavior to the few tags that might take advantage of it? Or possibly make that feature configurable? 

The way I see it, if we're going to aggravate one of the two types of users, I'd rather it be the experienced CanJS developer that decided to update and read the release notes.

**Comment by justinbmeyer** [comment]
> The way I see it, if we're going to aggravate one of the two types of users, I'd rather it be the experienced CanJS developer that decided to update and read the release notes.

I'd rather not break promises (SEMVER).  That aggravates everyone. So we can't change this until 3.0.  But yes, we can make it opt-in configurable before then.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-view-parser/issues/3

**Comment by akagomez** [comment]
Oh happy day!
