### ISSUE TITLE
can/map/list overrides can.List.prototype.filter and changes the API

### ISSUE THREAD

**Issue by andykant** [canjs/canjs#1192]
I included this detail in the documentation for `can/map/list` #1186, but the `can/map/list` plugin overwrites `can.List.prototype.filter` and changes the function signature for the API.

Without plugin:
```javascript
filteredList = list.filter(function(element,list){});
```

With plugin:
```javascript
filteredList = list.filter(function(element,index,list){});
```

**Comment by justinbmeyer** [comment]
It looks like this was fixed along the way: https://github.com/canjs/can-define/blob/master/list/list.js#L805 https://github.com/canjs/can-list/blob/master/can-list.js#L887 closing
