### ISSUE TITLE
Pseudo pre-compiling

### ISSUE THREAD

**Issue by stevenvachon** [canjs/canjs#1193]
Instead of building templates at runtime, what about parsing a JSON object that looks something like what @justinbmeyer [mentioned](https://github.com/bitovi/steal-tools/issues/51#issuecomment-51272429):
```js
can.stache([["start","h1"],["attrStart","class"],["attrValue","bar"],["attrEnd"],["close"]])
```

**Comment by gsmeets** [comment]
You're stating that can now parses the templates correctly in the related stealjs issue. 
I'd love include those parsed templates in my amd build layers, as opposed to simply wrapping them in can.stache() calls. Is this now possible? I've been toying around with it a bit, but I haven't got it working yet. The rendering parts of can are fairly complex to get a full understanding of how they work.

**Comment by justinbmeyer** [comment]
This is implemented now.

**Comment by gsmeets** [comment]
Any news on the slower performance that this gives? We've discussed this once on gitter...

**Comment by justinbmeyer** [comment]
Can you remind me what you mean by  "slower performance"?

**Comment by gsmeets** [comment]
I ran some tests in the past, and intermediate compiled templates actually performed worse at runtime than on the fly compiliation of stache templates.
