### ISSUE TITLE
Allow passing a function (callback) to a component

### ISSUE THREAD

**Issue by sporto** [canjs/canjs#1196]
Let's say that I have a component for choosing an element from the list, the parent scope wants to know when an element is selected. You can do this by:

- Passing a shared object (which is ok sometime, but sometime there is nothing to pass)
- Triggering a DOM event from the subcomponent, this works well but it could be simpler
- Calling a function in the parent scope directly from the sub component, this is a bad idea because of the tight coupling this creates.

But there is a simplest option that doesn't seem to be supported. This is simply passing a callback function to the subcomponent. Please see this fiddle:

http://jsbin.com/koxobamo/14/edit

I would like to simply do:

	<x-list selected="{onSelected}"></x-list>
	
`onSelected` is a function on the parent scope.

Please consider this.

**Comment by justinbmeyer** [comment]
This is working as part of 2.3.  

`value` will be a function in `some-component`'s viewModel:

```
<some-component {value}="@functionName"/>
```
