### ISSUE TITLE
Add @index to {{#key}}

### ISSUE THREAD

**Issue by stevenvachon** [canjs/canjs#1236]
I realize that it is not part of the Mustache spec, but `{{#each key}}` does not work inside attribute values (#1235) and therefore `{{#key}}` must be used. It'd be great if we could retain the functionality of `@index`.

Example:
```html
{{#key}}
    {{#if @index}},{{/if}}
    {{.}}
{{/key}}
```

The purpose of this is only technical and serves to accomplish #1237. We would never need to document that `@index` is indeed available within `{{#key}}`.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-stache/issues/8
