### ISSUE TITLE
Map {{#each key}} to {{#key}} inside attribute values

### ISSUE THREAD

**Issue by stevenvachon** [canjs/canjs#1237]
This results in a printed function object (#1235):
```html
<tag attribute="{{#each key}}asdf{{/each}}"/>
```
So, instead of forcing everyone to manually switch to `{{#key}}`, we should map `{{#each key}}` to it in this special case.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-stache/issues/8
