### ISSUE TITLE
Change to map not rendered in nested {{#if}}

### ISSUE THREAD

**Issue by stevenvachon** [canjs/canjs#1241]
```handlebars
<th class="{{#if sorting}}sort-{{#if ascending}}ascend{{else}}descend{{/if}}{{/if}}">
    asdf
</th>
```
When the value of `ascending` changes, the result is not rendered until the value of `sorting` is also changed.

http://jsfiddle.net/prometh/vwocku09/

**Comment by akagomez** [comment]
This is still a problem in latest. Possibly related to: https://github.com/canjs/canjs/issues/2229

**Comment by justinbmeyer** [comment]
Closing for the issue in can-stache
