### ISSUE TITLE
Changes to event-listening API

### ISSUE THREAD

**Issue by zkat** [canjs/canjs#1243]
CanJS currently has two API mechanisms for listening to events: `can.bind/can.unbind` and `can.on/can.off`. The first two map pretty directly to Backbone and jQuery's `.on/.off` methods, but the latter is kind of an incomplete version of Backbone's `.listenTo/stopListening` API on observable objects (and views), and works only on `can.Control` (and `can.Component`, by extension).

In the interest of having something like Backbone's ability to register listeners from a target object (I don't know how to best describe what `.listenTo` does), Justin and I talked about taking the following actions:

0. Keep `can.bind/can.unbind` in their current role as the low-level event binding API.
0. Implement `can.listenTo/can.stopListening`, and create methods on all observables that use these functions, much like things like `can.Map#bind` are implemented.
0. Deprecate `can.Control#on` and `can.Control#off` and alias them to `listenTo` and `stopListening`, which should be API-compatible (with extended features).
0. Once 3.0 comes along, remove `on/off` altogether in favor of `listenTo/stopListening`.

### notes
* Using `on/off` the way we currently do might cause confusion with how everyone else (specially jQuery) uses those terms, and it doesn't seem reasonable to change the `bind/unbind` API just for a change like this, so better to remove the `on/off` pair altogether.

**Comment by justinbmeyer** [comment]
In 3.0 here's the binding setup on our observables:

- `addEventListener` and `removeEventListener` - methods that any observable must implement to work with computes.
- `on` and `off` - short hand for `addEventListener` and `removeEventListener`.  
- `listenTo` and `stopListening` - registered event listeners.
- dispatch - dispatch an event on the listener.
- batch.dispatch - dispatch a batched event.
