### ISSUE TITLE
A function occurring prior to can.Construct.prototype.setup for can.Component

### ISSUE THREAD

**Issue by stevenvachon** [canjs/canjs#1249]
Consider this situation:
```js
can.Component.extend({
    init: function() {
        var newList = [];
        someGlobalMeta.forEach( function(foo) {
            if (this.scope.attr("something")) newList.push(foo);
        });
        this.scope.attr("list", newList);
    },
    scope: { something:true, list:[] }
});
```
[`can.Construct.prototype.init()`](http://canjs.com/docs/can.Construct.prototype.init.html) takes place after the component has hit the DOM, which results in an update *after* that, which is slower.

## Problematic solutions
* [`can.Construct.prototype.setup()`](http://canjs.com/docs/can.Construct.prototype.setup.html) takes place prior to `init()`, but doesn't appear to be available to `can.Component` (?) and still takes place after it's reached the DOM.
* [`can.Construct.setup()`](http://canjs.com/docs/can.Construct.setup.html) is *too* soon as it occurs before instantiation.
* A `can.compute()` is overkill since future "computing" is not needed.
* A closure has no scope, nor access to the not-yet-interpreted map:
```js
can.Component.extend({
    scope: {
        something: true,
        list: (function() {
            var newList = [];
            someGlobalMeta.forEach( function(foo) {
                if (this.attr("something")) newList.push(foo);
            });
            return newList;
        }).bind(this)()
    }
});
```

## Better solution
If we had something like a `can.Component.prototype.pre()` for making such preliminary changes, performance would be better in these situations.

**Comment by justinbmeyer** [comment]
Couldn't this be done in the Component's viewModel's `init`?  There it would be called prior to the rendering:

```
var VM = can.Map.extend({
  init: function() {
     // code
  }
})

can.Component.extend({
  viewModel: VM
})
```

Closing b/c I think this will work.  Re-open if there's still an issue.
