### ISSUE TITLE
Bug : can-value helper [2.1.3]

### ISSUE THREAD

**Issue by reno1979** [canjs/canjs#1263]
I had some trouble using the can-value helper with multiselect. 

The Model retrieved the data, and the values for each retrieved attribute for a multiselect are in an array. 

I found : 

bindings.js  333
```
if (option.value) {
	option.selected = !! isSelected[option.value];
}
```

Very odd to check like this, what if the value is an empty string or 0 ?!?!

Suggestion 
``` 
if (typeof option.value != 'undefined') {
						option.selected = !! isSelected[option.value];
					}
```

Then the second weard thing...

The template uses the each helper to render the options of the select box, it turns out that these options are not rendered in the dom yet when the above code is trying to set the selected values. 

See the Fiddle: 

updated 22-10-2014 (stache.can.js added and simplified code ) 

http://jsfiddle.net/reno1979/02aq58nh/

**Comment by neildcruz19** [comment]
>The template uses the each helper to render the options of the select box, it turns out that these options are not rendered in the dom yet when the above code is trying to set the selected values. 

Is there a workaround to this? I'm having the same issue with the can-value not working for multi-selects the same way as it does for other input types.

**Comment by justinbmeyer** [comment]
I'm being lazy, but what is the specific problem in the fiddle?  How can I see it breaking?  Thanks!

**Comment by justinbmeyer** [comment]
I don't think an option's value can be undefined, but it could be "".

**Comment by justinbmeyer** [comment]
Closing for issue in `can-stache`

**Comment by reno1979** [comment]
Hello Justin, 

I posted this a while back, to be honest I'm a bit unsure. 

Too long ago :/

**Comment by justinbmeyer** [comment]
no worries.  I think it might be working now except for the empty problem.
