### ISSUE TITLE
{{#switch}} helper

### ISSUE THREAD

**Issue by stevenvachon** [canjs/canjs#1264]
```handlebars
{{#switch attr}}
    {{#case "value1"}}asdf{{/case}}
    {{#case "value2" "value3"}}asdf{{/case}}
    {{#default}}asdf{{/default}}
{{/switch}}
```

This goes along with https://github.com/bitovi/canjs/issues/1216

I've already written http://jsfiddle.net/prometh/c71L3hzn/ but it'd need some work and would need to be rewritten for core.

While Justin's example didn't use a `{{/case}}` closer, mine does as I think it maintains template clarity. In case you're thinking that this doesn't relate to JavaScript, it may surprise you that it does:
```js
switch (attr) {
    case "something": {
        asdf();
        break;
    }
}
```

**Comment by matthewp** [comment]
So I think we're finally going to do this.
