### ISSUE TITLE
{{#each}} renders random numbers, after a helper throws an error

### ISSUE THREAD

**Issue by asavoy** [canjs/canjs#1271]
When using `{{#each}}` in a Mustache template, it will sometimes render `Math.random()` from [this code](https://github.com/bitovi/canjs/blob/c28001fd251df0ce0f86dcf1c290ffbef819796c/view/render.js#L81) instead of the correct content. With a Stache template, the content won't render at all.

Test case for CanJS 2.1.3: http://jsbin.com/bezolotagini/1/edit?html,js,console,output

This is a test case whittled down from an issue in an SPA project using CanJS. One template accidentally causes an error, and breaks other, unrelated templates if they use #each, until the user reloads the page. I'm not sure if there are other ways to trigger this issue, and if not, I'm not sure how much effort CanJS should put towards nicely handling error cases, but it would be helpful for it to be more compartmentalised.

**Comment by justinbmeyer** [comment]
It might be difficult to solve this without using `try/catch`.

**Comment by justinbmeyer** [comment]
Seems like stache handles this fine: http://jsbin.com/pofefu/edit?html,js,console,output
