### ISSUE TITLE
Question/Recipe: make widget/component with existing model

### ISSUE THREAD

**Issue by reno1979** [canjs/canjs#1276]
Also posted here: 
https://github.com/bitovi/canjs.com/issues/225

I didn't know where to post..... 

In the example  http://jsfiddle.net/reno1979/02aq58nh/

Is it possible to change it into a reusable component, on for example custom tags like 
```
<product-attributes attr-productid={productid}  ></product-attributes>
```

And can I use the model inside the component or the controller.? 
And is it possible to set a default template and to offer an alternative.

My goal is to be able to add the custom tag with attribute values that results in building the complete form.

**Comment by justinbmeyer** [comment]
I'm not sure exactly what example you are looking for.  But generally speaking, you can make anything into a reusable component.  If you still have this question, please ask on the forums: http://forums.donejs.com/c/canjs
