### ISSUE TITLE
$.fn.scope undefined when using CommonJS

### ISSUE THREAD

**Issue by ccummings** [canjs/canjs#1288]
I'm using CanJS in a Browserify application and noticed the scope jQuery plugin is not defined.

This happens because can.Component checks if `window.$` is defined before adding the plugin but in a CommonJS environment, jQuery does not add `$` to `window`.

> Source: https://github.com/bitovi/canjs/blob/master/component/component.js#L423

I think a much safer check would be `window.jQuery` since that always seems to be exposed.

**Comment by justinbmeyer** [comment]
I am using browserify too and just noticed this problem.  I think the correct solution would be to check for `can.$.fn`

**Comment by Guamaso** [comment]
I thought the solution was to not do this at all and, instead, have the check for jQuery abstracted from can.component. Or are you saying to use can.$.fn in the mean time?

**Comment by justinbmeyer** [comment]
I mean `if(can.$.fn) { can.$.fn = function{ ... } }`

But people can use `$().scope()`

**Comment by justinbmeyer** [comment]
Basically, we shouldn't be checking for jQuery.  If can.$ is an interface to the underlying library's nodeList.  Perhaps can.$.fn should be its interface to adding additional methods to it.
