### ISSUE TITLE
Extending Components doesn't work as expected.

### ISSUE THREAD

**Issue by dispatchrabbi** [canjs/canjs#1295]
Given this setup:

```js
var Parent = can.Component.extend({
  /* skip other stuff */
  helpers: {
    foo: () => { doParentFoo(); },
    bar: () => { doBar(); }
  }
});

var Child = Parent.extend({
  helpers: {
    foo: () => { doChildFoo(); },
    baz: () => { doBaz(); }
  }
});
```

I'd expect the Child component to have a `bar` helper, a `baz` helper, and a `foo` helper that calls `doChildFoo`. Instead, the Child component gets the right `foo` helper, a `baz` helper, and no `bar` helper.

Similar things happen with `events` and `scope`.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-component/issues/7
