### ISSUE TITLE
can.stache sectionHelper example contains typo

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#1299]
```js
can.stache.registerHelper('isJustRight',
  function(number, options){
    if(number > 50){
      return options.fn(this)
    } else {
      return options.inverse(this)
    }
    return out.join(" ")
});
```

It seems like the `return out.join(" ")` part is copy/paste cruft from the previous example.

**Comment by justinbmeyer** [comment]
Looks like this got fixed.

https://github.com/canjs/canjs/blob/a3b566ceb93dc60e4f1e909f9a27123b4ff55771/view/stache/doc/helpers/sectionHelper.md thanks @James0x57
