### ISSUE TITLE
performance documentation with benchmark.js

### ISSUE THREAD

**Issue by stevenvachon** [canjs/canjs#1315]
It'd be great if [Benchmark.js](http://benchmarkjs.com) were used in CanJS' build/release Grunt task to produce results of performance tests for inclusion in the DocumentJS-generated documentation.

Things like `map[0]` vs `map.attr(0)` or an official plugin vs the non-plugin approach or `can.mustache` vs `can.stache`, etc. Each newly released version would have updated benchmarks requiring no additional effort.

**Comment by justinbmeyer** [comment]
@stevenvachon We've talked about this for a while.  It's a great idea.  The main issue with this is that we need a server that's going to run at the same speed on every run.  That takes a bit to setup.  I'm going to close this issue and label it as "needs a hero".  If anyone wants to help, I'd love to make this part of the release cycle.
