### ISSUE TITLE
various can.List search and sort algorithm plugins

### ISSUE THREAD

**Issue by stevenvachon** [canjs/canjs#1316]
This is not a feature request, but more a poll for interest to see if I should implement them. I'm currently studying some computer science concepts and am discovering some useful options. Quicksort, shellsort, mergesort, heapsort, etc supporting live-binding; each a separate plugin to avoid bloat.

Performance benchmarks via #1315 could also be made available for those that, while experienced, have not yet studied any computer science; thereby aiding selection and opening the door to improved skills. I think that an awesome framework that makes you a better programmer is even more awesome.

**Comment by akagomez** [comment]
If you're into computer science data structures, you may be interested in the work going on here: https://github.com/canjs/can-binarytree

As far as sorting goes, the sort plugin pretty specifically uses selection sort to avoid unnecessary swaps in the DOM.
