### ISSUE TITLE
Invalid routes redirecting to empty URL #! which is the route for my dashboard

### ISSUE THREAD

**Issue by jondubois** [canjs/canjs#1341]
I have a default dashboard route defined to catch URLs which either do not have a hashbang part or finish with an empty #!:

```js
can.route('', {page: 'dashboard'});
```

When a user enters an invalid URL, I want to redirect them to a special 'Not found' page. I am able to handle invalid routes by adding a handler to capture when the 'route' attribute is removed from can.route.

The problem is that when the route is invalid, after a small timeout, the location.hash (containing the invalid URL) is changed to '#!' which also happens to be my dashboard route...

So basically the error page blinks on the screen for a few milliseconds and then it redirects me to the dashboard.

I really need it to stay on the error page with the bad route still displayed in the URL. It would be nice if can.route didn't clear the location.hash when it encounters an invalid URL.

To reproduce:

```js
can.route('', {page: 'dashboard'});
can.route('pagea/', {page: 'a'});
can.route('pageb/', {page: 'b'});

can.route.ready();
```

In the browser, change the URL hash to #!pagea/ (should work fine)
Then change to an invalid route like #!pagec/
Now can.route should clear the hash and send us to dashboard.

**Comment by justinbmeyer** [comment]
Closing for this issue on can-route: https://github.com/canjs/can-route/issues/4
