### ISSUE TITLE
Helpers not automatically unbound

### ISSUE THREAD

**Issue by moschel** [canjs/canjs#1342]
When you remove a component's element (or any template's container for that matter), the helpers associated with it are not automatically unbound.

For example, if you have a helper that checks a property on can.route, and renders a section if it matches, like:

````html
<div class='container'>
{{#isSection 'category'}}<x-category></x-category>{{/isSection}}
</div>
````

implemented like:

````js
      isSection: function(name, options){
        if(can.route.attr('section') === name){
          return options.fn(this);
        }
      }
````

If that associated component (or the HTML associated with that helper) is removed from the page - if ".container" is cleared out - this helper remains in memory. If you render this component (or template) again, and change the can.route 'section' property, this code will run twice.

In this example, since the DOM is gone, it won't actually run "inserted" on the x-category component, but it will initialize it and its scope.

Ideally, this would be fixed in the template layer. Whenever an element containing helpers is removed, any event handlers associated with that helper would be automatically unbound.

@daffl @justinbmeyer do you agree this is a bug? If so, I can create a breaking test.

**Comment by justinbmeyer** [comment]
This is fixed when we made components be able to be torn down when their nodeList is destroyed.
