### ISSUE TITLE
Bubbled event bindings work inconsistently when a can.Map is referenced multiple times

### ISSUE THREAD

**Issue by Bajix** [canjs/canjs#1343]
In the following snippet, each Classroom can.Map.extend instance has a Valedictorian can.Map.extend instance, with bindings for that valedictorian's GPA property. Additionally, in two of the instances, there is another reference, or nested reference to that same Valedictorian instance. When those are present, if they are defined before valedictorian, the binding to valedictorian.GPA will not be called, and instead there will be a change event for the first declared reference's event selector.

http://jsfiddle.net/ej10m0sn/1/

**Comment by Bajix** [comment]
Bump. The issue isn't resolved by using can/map/delegate either

**Comment by justinbmeyer** [comment]
Use this in a Component's event object and it should work.  It doesn't work anywhere else. The best way around it would be to listen to change and check if either valedictorian or valedictorian.GPA changed.

**Comment by justinbmeyer** [comment]
```js
"{scope} valedictorian.GPA": function(){ ... }

```

**Comment by Bajix** [comment]
Updated test with other binding signatures
http://jsfiddle.net/ej10m0sn/3/

**Comment by Bajix** [comment]
Well, so why should this be limited to only components? Bubbling is definitely good functionality for can.Control, can.Map.delegate, and can.Map.bind.

While I didn't create tests for it at this juncture, I've ran into this issue while using components as well.

**Comment by justinbmeyer** [comment]
> Well, so why should this be limited to only components?

Performance is the big reason we don't do it.  Consider what happens if you do:

```js
var map = new can.Map({a: {}});
map.attr("a", { .... });
```

By setting "a", you might have to trigger off every combination of properties that someone might listen to:

- "a"
- "a.b"
- "a.b.c"
- "a.x"
- "a.**"

Instead, we only fire off "a".  Any listeners like "a.b" are not triggered.  "a.b" is only triggered when "b" is changed on "a".

I understand how this can be confusing.  

I think the right thing to do is make the delegate plugin work this way and advise that listening to nested properties with bind is possibly not what someone wants to do.

**Comment by Bajix** [comment]
Yea, I could see how this could create performance issues.

This might be an area in which propagation or delegate are the only viable options.

**Comment by Bajix** [comment]
Can we do anything to make shallow events work? Really the use case that I'm looking for here is to be able to bubble events emitted by immediate children of a map.

**Comment by Bajix** [comment]
Quick follow up

So part of the reason why I see this type of functionality being immensely powerful is to be able to make shallow event bindings on a specific subject. This has the advantage of not requiring a lot of lifecycle logic, to teardown and rebind, or needing computes in luei of vanilla get/set functionality simply to coerce event handlers.

This use case doesn't really fit very well with propagate, as propagate is bottom up whereas the bindings in this case would need to be top down. Of course, you could make what you're intended to observe extend can/event with propagate, and use change events to change the parent, however that's a considerable amount of glue and requires extended somewhat violates separation of concerns, as it would require changes to the bindee that should otherwise exist on the binder.

A simple win here might simply be to exclusively use the shortest pathway when bubbling events, such that in a case where you could emit 'cats.0.cat.meow' or 'cat.meow', 'cat.meow' would always win out.

It would be pretty sweet to be able to dispatch custom events from a can.Map in the same manor.

```
var Map = can.Map.extend({}, {
  define: {
    cats: {
      value: Array,
      Type: Cat.List
    },
    cat: {
      value: Object,
      Type: Cat
    }
  }
}), map = new Map();

var Ctrl = new can.Control.extend({
  defaults: {
    map: map
  }
}, {
  '{map} cat.meow': function() {
    console.log('YAY!');
  }
});
```

**Comment by justinbmeyer** [comment]
What do you mean by "shallow event bindings on a specific subject"? I would call bind("foo.bar")  deep event bindings. 


I'm not really sure what you are saying about custom events. I don't see that code doing it. 

You can get the behavior you want by listening to change and using a regexp to check the attr arg like

/cats\.\d+\.cat\.meow/

**Comment by Bajix** [comment]
By shallow event binding, I mean that the event would bubble specifically to the immediate parent.

So if I had a map foo with property bar that is a can.Map instance, and if bar dispatched an event, that event could be bound to like `foo.bind('bar.{event}')`, where {event} could be a property name, or the name of a dispatched event. In the previous example, cat could have a property meow that could trigger a change event or alternatively use can.batch.trigger/can.event.dispatch to dispatch a meow event with the same effect.

I see what you mean about the regex approach and testing change - maybe simplified to `/cat\.meow$/`?. Anyway, the problem with that approach though is that it would still pick up events emitted from objects that aren't your subject (in this case `cat`), and require instance checking. Even then though, that feels awfully spammy and doesn't let you split up bindings if you wanted to do this with multiple properties and have inheritance etc.

From a performance perspective, I'm kind of curios how emitting something like `cats.*.cat.meow` compares to only emitting `cat.meow`. Is the latter not more performant?

**Comment by justinbmeyer** [comment]
> By shallow event binding, I mean that the event would bubble specifically to the immediate parent.
> 
It currently does do this and continues to bubble up. I suppose you are wondering what would happen if you didn't keep bubbling up when you say:

> From a performance perspective, I'm kind of curios how emitting something like cats.*.cat.meow compares to only emitting cat.meow. Is the latter not more performant?
> 
But this makes think I'm still not communicating how bubbling works. Bubbling up to all parents is not the problem. The problem that if someone changes the "cat" property, you want a "cat.meow" event.

**Comment by Bajix** [comment]
> It currently does do this and continues to bubble up.

It does do this, and I am using this in the example I originally posted

```
var b = new Classroom({
    valedictorian: valedictorian
});
can.bind.call(b, 'valedictorian.GPA', increment);
valedictorian.attr('GPA', 3.95);
```

That absolutely works! My callback gets called just fine there. The problem is that if that same map I'm binding to has another property, say a can.List that has that same object, suddenly my binding that was working will no longer work.

```
var b = new Classroom({
    students: students,
    valedictorian: valedictorian
});
can.bind.call(b, 'valedictorian.GPA', increment);
valedictorian.attr('GPA', 3.95);
```

This example is where the problem is. That binding that was working in the previous example no longer works. That is the issue I'm trying to address.

> But this makes think I'm still not communicating how bubbling works. Bubbling up to all parents is not the problem. The problem that if someone changes the "cat" property, you want a "cat.meow" event.

Let's say the `cat` property of `map` becomes a new instance of Cat, `map` would have a change event, and a `cat` event. This is a change event exclusively on `map`. It shouldn't have a `cat.meow` event. The properties of `cat` are irrelevant to this change event. If however the new `cat` has a meow event, because `meow` was changed, or dispatched, now that should bubble up to `map` and be observable while binding as `map.bind('cat.meow')`.

**Comment by justinbmeyer** [comment]
> suddenly my binding that was working will no longer work.

Ah, I get it.  This is because the same event can only fire once on an object.  This is to prevent cycles.

I will have to think on a better (and still fast) way of solving this.

**Comment by Bajix** [comment]
@justinbmeyer Thoughts on getting this into the eventual roadmap? This is a very scary issue as it creates a scenario in which your bindings can break unexpectedly, for non-intuitive reasons.

**Comment by justinbmeyer** [comment]
Anything that isn't closed is still potentially on the roadmap. I'd like to solve it, but I have no immediate plans to fix it. 

To be clear, the bindings "work" ... your page will result in the right thing, but there maybe undesirable side effects. 

If you'd like to help, that can move it along almost immediately. 

Another solution might be to apply all DOM changes at the end of a batch, in order. Every can.view.live would be applied in order.

**Comment by Bajix** [comment]
It appears this is slightly less broken on latest than 2.1.4. 

2.1.4
http://jsfiddle.net/vt4L4ydu/

Latest:
http://jsfiddle.net/r0nmmfh8/

The 2.1.4 example wasn't actually resulting in the right thing, and was breaking computes, which had much wider ramifications. The latest branch doesn't seem to have this issue with computes, which is awesome.

I think you mixed up issues, and were thinking of #1483 

I can tackle this issue. Assign it my way

**Comment by justinbmeyer** [comment]
Ah, I was thinking of #1866 .

**Comment by justinbmeyer** [comment]
@Bajix what's your email?  I'm sending you something to the email I have on file, but it bounced.  Can you email me at justin AT bitovi?  Thanks!

**Comment by Bajix** [comment]
It's Thomas@bajix.com

**Comment by justinbmeyer** [comment]
Closing for an issue in can-map. https://github.com/canjs/can-map/issues/2 I added a likely solution.
