### ISSUE TITLE
Proposal: scope events propagate through DOM automatically.

### ISSUE THREAD

**Issue by zkat** [canjs/canjs#1366]
## Proposal

Events coming out of `can.Component` should propagate through the DOM without the need for somehow passing things to the events object, or creating a reference to `this.element` in the insert event or similar and triggering on that.

## Justification and Notes

There are 4 APIs for configuring and interacting with `can.Component` from the outside:
* Attributes
* DOM children (`<content>`)
* Scope methods (by finding a reference to the component scope and calling them, see also #1362)
* DOM events

It's this last item that this helps facilitate. We often want to communicate that something has happened, to the outside world, through our component element, but the only way to expose events fired from `scope`-specific code to the DOM is to listen to them individually through the `events` object, and re-trigger them on `this.element`, which means duplicated effort that might neglect to implement functionality like `preventDefault`/`isDefaultPrevented`, instead of having it there by default.

It's worth noting that the most straightforward implementation of this would necessarily make `change` (and family) events automatically propagate and bubble throughout the DOM, which might become a performance issue -- but at least a `triggerExternal` or similar method could be available if this is the case. We should look into how much of a performance hit this kind of event storm could cause.

## Examples

```js
scope: {
  callMeMaybe: function() {
    this.trigger("ayy-lmao");
  }
}
```

```html
<call-something-maybe can-ayy-lmao="{attr 'greeting' 'haaaaayyyyy'}"></call-something-maybe>
```

**Comment by whitecolor** [comment]
This will be actually quite useful especially when https://github.com/bitovi/canjs/issues/1361 is in place.

**Comment by justinbmeyer** [comment]
This is closed with the introduction of the new event bindings:

```
<my-comp (view-model-event)="methodName()">
```
