### ISSUE TITLE
Allow can.view.attr to take an object as the second argument

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#1376]
I would like to be able to pass an object as the second argument to can.view.attr. This object would be used to extend can.Control and new instances would be created for each element. `attrData` would be set on `this.options`. It would work like so:

```js
can.view.attr('attr-name', {
  init: function() {
   // this.options.attrData
  },

  "button click": function() {

  }
});
```

Could do the same for `can.view.tag` but that might overlap too much with Components.

**Comment by dylanrtt** [comment]
I have been thinking a lot lately about how a higher level API for attributes might work and what I have ultimately come up with is practically a copy of can.Component with a few tweaks:

https://gist.github.com/dylanrtt/42f56d374080cad61c16#file-demo-html

I basically copied a bunch of code from can.Component, removed the parts about attaching a child scope/template and added a little bit of configuration to determine which attributes get mapped in.

I had several design goals in mind:

* Easily map attributes to a fully featured can.Map (prototype, define, etc.)
* Fully featured can.Control (templated event handlers)
* Listen to attribute changes without having to monkey with a single 'attributes' event where you check which attribute changed
* Easily listen to and change scope properties without worrying about memory leaks or passing computes to a separate can.Control definition
* Define which attributes are mapped to avoid standard standard HTML attributes like 'type' and 'class'

Many attributes will not need all that functionality, but for the ones that do, it's nice to have a better API. There is currently a lot of copy pasta going on in my example so if you guys agree with this type of design, some substantial refactoring may have to take place to make the can.Component code more reusable.

**Comment by justinbmeyer** [comment]
I support this idea. I'm going to add "needs a hero" and close it.  If someone wants to pick it up, I'll re-open it.
