### ISSUE TITLE
Events within nested computes

### ISSUE THREAD

**Issue by alexisabril** [canjs/canjs#1394]
Inner computes changing should trigger a change on a compute wrapping it. This is a potential bug or a potential no-fix depending on implementation details/perf considerations.

Real world scenario: 

Allowing for helpers that can return a value based on a deferred's state.

**Comment by justinbmeyer** [comment]
Seems valid.

**Comment by justinbmeyer** [comment]
@alexisabril maybe we can fix this in can.Compute

**Comment by daffl** [comment]
Is this fixed via #1486?

**Comment by alexisabril** [comment]
Just noting this was not fixed via #1486

**Comment by justinbmeyer** [comment]
Still breaking: http://justinbmeyer.jsbin.com/tinece/5/edit?html,js,output.  I think this only happens with computes that are defined and called within a compute: http://jsbin.com/qovipi/edit?html,js,console,output Closing for: https://github.com/canjs/can-compute/issues/7
