### ISSUE TITLE
Allow {{#if}} helper to handle multiple arguments

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#1411]
What do you think about allowing ```{{#if}}``` helper to handle multiple arguments?

```{{#if attr1 att2}}``` - would check if attr1 and attr2 are truthy 

or it is more reasonable to create separate helper fo this?

**Comment by justinbmeyer** [comment]
Not sure. Alternatives might be:

```
{{#and key1 key2}}
```

```
{{#or key1 key2}}
```

Or, we could possibly support  `&& and ||` in expressions.

**Comment by whitecolor** [comment]
> Or, we could possibly support && and || in expressions.

Then, negation ```!``` (for particular argument) as well would be useful.

```{{#if someParam && !anotherParam}}```

Will you think about it, let know that you decide.

**Comment by justinbmeyer** [comment]
I think making `if` handle multiple arguments is great for now.  We'd have to see what it takes to include more logic in stache.

Can you submit a pull request / test / docs?

**Comment by whitecolor** [comment]
maybe `{{#if fn attr}}` shoud be interpried as `if (fn(attr)){...`?

**Comment by justinbmeyer** [comment]
If this is still desired, please open here an issue here https://github.com/canjs/can-stache
