### ISSUE TITLE
Define get: async arguments are sometimes undefined

### ISSUE THREAD

**Issue by asavoy** [canjs/canjs#1416]
I'm using the `can/map/define` plugin, specifically the async form of `get:`. There's not any docs on this, despite  there being examples for it, such as [canjsmeetup/1_intro](https://github.com/bitovi/canjsmeetup/blob/dba08dd71603dd0b13a1a65e6fb3e7322a44d15a/1_intro/two_one_example.html) and [canjsmeetup/7_route](https://github.com/bitovi/canjsmeetup/blob/dba08dd71603dd0b13a1a65e6fb3e7322a44d15a/7_route/components/contact.js), so I'm not sure what is exactly supported.

The issue is that the callback argument is undefined, *unless* something has bound to the property first.

Please see this [JSBin](http://jsbin.com/wotititozo/1/edit?js,console), it errors at (1), but it works at (2) after doing `person.bind('fullName', function() {})`.

**Comment by justinbmeyer** [comment]
@asavoy I'm not sure what the correct behavior is.  You are resolving synchronously, which defeats the purpose of the async get.

Without binding, there can be no value.  Or, perhaps, the value should be `undefined`.

We can prevent the error from happening, by providing a callback, but (1) is not an appropriate use case.

Proposals:

A. Document how to use async getters.  
B. Provide a callback when unbound. So no errors happen, but discard the `resolved` value.  
C. Add a dev warning when .attr() is called on an async getter.  

@asavoy any interest in helping?

**Comment by asavoy** [comment]
@justinbmeyer While I reported the error here, I should have described the use case along with it.

I've written a view model for a can.Component's scope, with an async getter and a getter dependent on it. I'm using `this.attr('myAsyncProperty');` to not just get the value, but also to setup the binding. Everything works when the component is rendered to the DOM, but I'd like to also write DOM-less unit tests for the view model and that is where this error comes up.

Here's a similar example http://jsbin.com/cunane/8/edit?js,console where the async getter is resolved asynchronously (I agree resolving synchronously isn't useful, so disregard that).

I agree that the async getter should return `undefined`, at least until it gets resolved.

In response to your proposals:

A. Since discovering async getters, my team and I have agreed that it's really useful for simplifying code where AJAX requests are involved. Docs for it would have helped us find this earlier.

B. I've had a crack at fixing this already, by eagerly binding an empty handler for any async getters, which I think is what you're describing here. I don't have a lot of confidence with Map/define/compute under the hood, so I'll need someone to review it. I'll push it up soon.

C. I don't think there should be a warning because I feel that one should be able to have getters dependent on async getters as done in http://jsbin.com/cunane/8/edit?js,console

**Comment by justinbmeyer** [comment]
> B. I've had a crack at fixing this already, by eagerly binding an empty handler for any async getters, which I think is what you're describing here. I don't have a lot of confidence with Map/define/compute under the hood, so I'll need someone to review it. I'll push it up soon.

I'm not describing eagerly binding an empty handler (at least I doubt it for memory-leak concerns).

> C. I don't think there should be a warning because I feel that one should be able to have getters dependent on async getters as done in http://jsbin.com/cunane/8/edit?js,console

I didn't describe C fully.  I mean't that if `.attr()` is called on an async setter that is not bound, then produce a warning b/c the value returned is meaningless.

**Comment by justinbmeyer** [comment]
@asavoy If you're interested in working on this, lets talk tomorrow?

**Comment by justinbmeyer** [comment]
As I don't think the eager binding can work in all cases, 3.0 will still not pass the resolve when unbound as this is useful information and gives someone the ability to handle that situation.

Here's the issue to document it: https://github.com/canjs/can-define/issues/59
