### ISSUE TITLE
Make can.Observe.delegate have better & more consistent API

### ISSUE THREAD

**Issue by imjoshdean** [canjs/canjs#144]
Handle these specific issues:

https://github.com/jupiterjs/canjs/issues/119
https://github.com/jupiterjs/canjs/issues/121
https://github.com/jupiterjs/canjs/issues/122 - Need a way to allow people match delegates across events vs state
https://github.com/jupiterjs/canjs/issues/123
https://github.com/jupiterjs/canjs/pull/125

**Comment by justinbmeyer** [comment]
With async getters, much of this is unnecessary.  Closing.
