### ISSUE TITLE
Expose can.route.unbind

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#1459]
It's need to expose `can.route._teardown` to dismount routes when need (to be able later to mount via `ready` again).

for example `can.route.unbind`?

**Comment by matthewp** [comment]
Just curious, why are you wanting to dismount a route?

**Comment by whitecolor** [comment]
If I want to reinitialize the whole application. For example after for hot js modules reload.

**Comment by matthewp** [comment]
Ah, cool then.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-route/issues/7

it can't be .unbind because that actually binds things on the `can.route.data`.
