### ISSUE TITLE
Overriding the basicProcessor in can.Control

### ISSUE THREAD

**Issue by jeffrose** [canjs/canjs#146]
There is currently no way to access the `basicProcessor` for `can.Control`, which means the only way to override it is to loop through `can.Control.processors` after the fact and set your own. It would be more efficient if you could just override it. Possibly make it part of `defaults` or just an attribute on `Control`?

jQueryMX has the same problem.

**Comment by justinbmeyer** [comment]
I don't think we are ever going to get to this.  I'm going to close and add a "needs a champion" to get it in.  It's just not priority for the core team.
