### ISSUE TITLE
Models should be removed from store when id changes.

### ISSUE THREAD

**Issue by cklanac** [canjs/canjs#1463]
In the rare circumstance that a model ID shouldn't change, the store should be removed from store. 

Under normal conditions, id don't change, but under some circumstances such as creating/saving - the ID might not be known as it is being created or "drafted" and an ID is only created when saved. 

I've included a test in a PR which should ensure that the old model is removed when the ID is updated/changed.
https://github.com/bitovi/canjs/pull/1462

**Comment by justinbmeyer** [comment]
To be clear ... the model should still be in the store, only referenced by a new id.

**Comment by cklanac** [comment]
Gotcha'... Currently the model is stored twice, once with the old ID and again with the new ID. I'll make sure the test properly tests for either an update or a delete of the old model. 




    _____________________________

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-connect/issues/103
