### ISSUE TITLE
Value, Checked, Multiselect, Content controls in bindings.js are not exposed to the public API

### ISSUE THREAD

**Issue by abalmush** [canjs/canjs#1465]
I think I could have reused the code from the "/view/bindings/bindings.js" but many things are in the private scope there. Value, Checked, Multiselect, Content controls are not exposed to the public API.  As far as I can see those could be simply defined in separate modules and thus available for code reuse (custom binding solutions).

**Comment by justinbmeyer** [comment]
These controls have been replaced by the bindings methods which are exposed as a module.  However, we will document these methods as part of 3.0. Closing for: https://github.com/canjs/can-stache-bindings/issues/7
