### ISSUE TITLE
can.mustache & can.stache overly lenient in parsing

### ISSUE THREAD

**Issue by imjoshdean** [canjs/canjs#1476]
I was reviewing some code today with my client and I noticed a line of code that looked like the following:

```html
{{#if someCondition}}
   ...
{{/someCondition}}
```

And found that it worked. What's weirder is I can do the following like the following

```html
{{^someCondition}}
    ...
{{/each}}
```

and this would properly parse.

My question is - are we intentionally this lenient with our template parsing? I know if I attempt to parse with Mustache outright I get an error returned for my view. E.g.

```js
// template.mustache
{{#items}}
    {{name}}
{{/if}}

// template.json
{
  "items": [
      {"name": "red"}
  ]
}

// results
Error: Unclosed section "items" at 24
```

Thoughts? Further example with latest here - http://jsfiddle.net/co48cda2/3/

**Comment by justinbmeyer** [comment]
So, I believe mustache and handlebars support ending with just `{{/}}`; however, I think they also throw warnings if the ending exists and does not match.  We should probably give a warning.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-stache/issues/13
