### ISSUE TITLE
Remove `_computedBindings` from can.Map

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#1479]
Per @justinbmeyer, `_computedBindings` was added to support `can.compute`'s being defined on a `can.Map`'s prototype. Like this... 

```
var SpecialMap = can.Map.extend({
  firstName: 'Chris', 
  lastName: 'Gomez'
  fullName: can.compute(function () {
    return this.attr('firstName') + ' ' + this.attr('lastName'); 
  })
}); 
```

Now that we have the [Define](http://canjs.com/docs/can.Map.prototype.define.html) plugin, and especially the `type: 'compute'` (added in #1470), there's no/less(?) of need for `_computedBindings` anymore. 

From what I can tell we should be able to use `.isComputed` to detect computes and track the number of bindings on a `can.Map`'s property in `bind` and `unbind` alone without having to do things like [this](https://github.com/bitovi/canjs/blob/ac8ac533ebab36969c083e865b32d9ea2972c97c/map/define/define.js#L182) and [this](https://github.com/bitovi/canjs/blob/ac8ac533ebab36969c083e865b32d9ea2972c97c/map/map.js#L308).

Here are the instances I found post #1470.

```
totes:canjs akagomez$ grep -rn "_computedBindings" --exclude=./build\* --exclude=./dist\* --exclude=./test\* .
./list/list.js:91:				this._computedBindings = {};
./map/define/define.js:309:				this._computedBindings[attr] = {
./map/lazy/lazy.js:17:			this._computedBindings = {};
./map/map.js:277:				this._computedBindings = {};
./map/map.js:314:				this._computedBindings[prop] = {
./map/map.js:454:					if (this._computedBindings[attr]) {
./map/map.js:534:				if ( this._computedBindings[prop] ) {
./map/map.js:541:				if ( typeof this.constructor.prototype[prop] !== 'function' && !this._computedBindings[prop] ) {
./map/map.js:547:				var computedBinding = this._computedBindings && this._computedBindings[eventName];
./map/map.js:576:				var computedBinding = this._computedBindings && this._computedBindings[eventName];
./map/map_test.js:223:		equal(map._computedBindings.name.count, 2, '2 handlers listening to computed property');
./map/map_test.js:226:		equal(map._computedBindings.name.count, 0, '0 handlers listening to computed property');
./map/map_test.js:227:		ok(!map._computedBindings.name.handler, 'computed property handler removed');
```

**Comment by justinbmeyer** [comment]
I'm not so sure about this.  I think this is a useful flag to tell if a value is not directly on the map.

**Comment by justinbmeyer** [comment]
computedBindings is still useful, but we've removed trackCompute. Closing.
