### ISSUE TITLE
Inconsistent merging of List with models

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#1505]
This issue was fixed by https://github.com/bitovi/canjs/pull/91 long time ago but it seems that you removed `model/list` from `canjs` at all.

I'll just copy the explanation for mentioned PR:

```javascript
//Let's say we have a list of tasks that are bound to views with the following _cids:
var modelList = [
{ _cid : 1, id : 'f', name : 'foo'},
{ _cid : 2, id : 'b', name : 'bar'},
{ _cid : 3, id : 'c', name : 'cat'}
]

// If the server comes back with this order : 
var serverData = [
{id : 'f', name : 'foo'},
{id : 'c', name : 'cat'},
{id : 'b', name : 'bar'},
]

//The current code leaves you with this:
[
{ _cid : 1, id : 'f', name : 'foo'},
{ _cid : 2, id : 'c', name : 'cat'},
{ _cid : 3, id : 'b', name : 'bar'}
]
````
> Basically, the object with _cid 2 has now become the "cat" task.

> This is a problem for us because if the user is looking at a view of a task (bound to the model with _cid 2), suddenly they are looking at a completely different object.

This is really incosistent scenario for real world examples.

I would make maybe define plugin param to override default behavour with consistent for this general scenario.

**Comment by daffl** [comment]
This can be solved by setting the [removeAttr](http://canjs.com/docs/can.Model.removeAttr.html) static property to `true` which causes model merges to remove existing attributes.

I agree this should be the default behaviour but unfortunately we can't change this until the next major release.

**Comment by whitecolor** [comment]
@daffl 
Are you sure that `removeAttr` will not solve this problem? 

I think that in the example even with `removeAttr` map with `_cid` equal `2` still be a `cat` after update.

What I would do is to allow custom merge scenarios for a particular attribute. Using `define` pluign
```javascript
define: {
   myList: {
      merge: function(){
         //this function would be used to set attribute value while merge
      }
   }
}
```

**Comment by justinbmeyer** [comment]
@whitecolor I agree.  The define plugin should solve this.  And can.Model.List should do it by default.  I'm not sure what it will look like, but we will want to be able to set it on lists themselves:

```
can.List.extend({
  define: { 
   "*": {merge: function(){ ...} }
  }
})
```

This is clearly needed as @akagomez 's sort plugin does this (I think with some n^2 sort).

**Comment by whitecolor** [comment]
Not sure about such API. `'*': {merge: ..}` mean that merge option is applied to all attributes (i.e list items in case of `can.List`), but we are talking about operation with the whole List (correct merge with new set data), not operation each of its particular items.

**Comment by whitecolor** [comment]
Any Ideas about API for this?

**Comment by justinbmeyer** [comment]
```js
can.List.extend({
  define: { 
   merge: function(){ ...}
  }
})
```

?

**Comment by whitecolor** [comment]
I think this is not only problem with list
There is aslo a problem with such case (will explain again)
```
var Person = can.Map({
    
    age: 0,
    
    define: {
        name: {
            type: function(val){
                console.log('name type', val)
                return val ? new can.Map({first: val.first.toUpperCase(), last: val.last.toUpperCase()}) : val
            }
        },
        
    }

})

var person = new Person({name: {first: 'disney', last: 'walt'}, names:['disney']})

console.log('name', person.serialize().name) // -> `{first: 'DISNEY', last: 'WALT'}`

// while attr update, say I want `name` allways to be passed though type converter, not just merge
person.attr({
    
    age: 0,
    name: {
        first: 'john',
        last: 'galt'
    }    
})
//var ser = person.serialize()
console.log('name , person.serialize().name) // -> {first: 'jonh', last: 'galt'} and `{first: 'JOHN', last: 'GALT'}` needed
```
http://jsfiddle.net/xKc3H/367/

This is just simple example. So if we could avoid merging while such `attr` updates, for example using such API:
```
define: {
        name: {
            type: function(val){
                console.log('name type', val)
                return val ? new can.Map({first: val.first.toUpperCase(), last: val.last.toUpperCase()}) : val
            },
            merge: 'type' // or custom function
        }
```

This would allow to solve the issue with lists as well as any can.Map.
I hope I was clear.

**Comment by akagomez** [comment]
From what I can tell, the "JOHN GALT" example demonstrates that a define type converter is not called when setting multiple properties with `.attr(object)`: 

http://jsbin.com/jetibe/edit?html,js,console

How this relates to the original example I haven't been able to determine yet.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-define/issues/17
