### ISSUE TITLE
Keep can-value in sync with compute for input type="radio/checkbox/select"

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#1518]
We did this for `<input type="text">` here: #1443 

I'd hate for the one to be fixed in 2.2, and the others not. 

Just this morning @imjoshdean tried to rely on this and got burned: http://jsfiddle.net/imjoshdean/npwpa6v9/

I think  that as the Define plugin gets more popular this will become a greater issue. 

@daffl @justinbmeyer, Do you think this is important enough to hold up the 2.2 release?

**Comment by justinbmeyer** [comment]
I don't think it's important because this is a bug that we can fix in 2.2.1 very quickly. But if it gets done before David gets the builder working, then it can be in.

**Comment by akagomez** [comment]
Here's a Fiddle I put together a little while back demonstrating the issue: http://jsfiddle.net/akagomez/tksdbxvp/

**Comment by akagomez** [comment]
I suppose this issue is irrelevant now due to the new binding syntaxes @daffl?

**Comment by justinbmeyer** [comment]
fiddle seems to work now.  Closing.
