### ISSUE TITLE
Quoted arguments in stache helpers can cause parse errors within attributes

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#1536]
The following code throws a parse error:

    can.stache('<span title="{{#if "test"}}abc{{/if}}"></span>')()

The problem seems to occur when the attribute value is surrounded by the same type of quotes that are used in the helper arguments. This does not occur if you, for example, surround the attribute in double quotes and use single quotes for the helper arguments.

It happens with all helpers; I just used #if as an example even though you probably would never use it with a string like that.

It works fine in mustache.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-view-parser/issues/4
