### ISSUE TITLE
can.Component should show a warning if tag name is missing a hyphen

### ISSUE THREAD

**Issue by kylegifford** [canjs/canjs#1541]
Currently stache fails silently and does not render the template if a component's tag is missing a hyphen. The user should be notified with a warning if the tag is missing the hyphen.

**Comment by justinbmeyer** [comment]
Just an FYI, it will render the component if the component is loaded prior to the template being processed.  `can-import` would allow this.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-component/issues/11
