### ISSUE TITLE
can.fixture.rand should be inclusive

### ISSUE THREAD

**Issue by BigAB** [canjs/canjs#1562]
I think the numbers and arrays produced from [can.fixture.rand](http://canjs.com/docs/can.fixture.rand.html) should be inclusive of the MAX argument instead of exclusive. I think it would  be a more intuitive API.

The best example of this I can give is this:

```javascript
can.fixture.rand( [ "j", "m", "v", "c"] , 2, 3);
```
I think most people would assume this would give you either 2 **or 3** items from the array, but in actuality is only ever going to give you **2** random items, because the MAX is exclusive.

In my opinion, It also leads to a more intuitive API for the numbers too:

```javascript
// get a random integer between 0 and 10 (inclusive)
rand(10);

// get a random number between -5 and 5 (inclusive)
rand(-5, 5);
```

**Comment by justinbmeyer** [comment]
Math.random() gives you between 0 and 1 exclusive of 1 I believe.

**Comment by BigAB** [comment]
It does. But I don't think that invalidates the argument, specifically the `can.fixture.rand( [ "j", "m", "v", "c"] , 2, 3);` example

**Comment by justinbmeyer** [comment]
Yeah, this would be a `3.X` change.  I'm not sure about changing rand(-5,5) though.

**Comment by justinbmeyer** [comment]
Closing for the same issue in can-fixture
