### ISSUE TITLE
Improvement for can.component guide

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#1565]
First of all, the new guide is great!

But one thing I miss, the communication between the components.

There is one issue still open:
#1209 Improving communication and message passing between components
Maybe these docs have to adapt for the new version 2.2

Unfortunately my English is not so good, otherwise I would create a pull request. :)

**Comment by justinbmeyer** [comment]
I'll write up a guide about this for 2.3.

**Comment by pYr0x** [comment]
i think we can close this since the new binding syntax solve all the problems ;)
