### ISSUE TITLE
Live-bound dynamic attributes don't get updated properly if they don't exist on initial execution

### ISSUE THREAD

**Issue by ghost** [canjs/canjs#157]
This was discussed and fixed for EJS templates:

https://forum.javascriptmvc.com/topic/live-binding-an-image

But it doesn't work with Mustache templates. Check the following fiddle:

http://jsfiddle.net/donejs/4SmxJ/2/

It gives the **!!** error

**Comment by sarathgalimelu** [comment]
Hello @andykant  I was trying to use the img src as you mentioned in the workaround 
``` 
<img {{#image}}src="{{.}}"{{/image}} alt="An image" />
```
This is my code what I have been trying to set the image src to the template. But the src tag itself is not appended to the code after rendering the template. Can you help in this. Tried different combinations but didn't help.
Here is my code below and the version that I am using is 2.0

```
<a href="https://www.google.com/" style="font-family: 'Helvetica Neue', sans-serif; color: rgb(58, 139, 187); font-weight: normal; text-decoration: underline;" class="" target="_blank">
<img class="photo" width="200" src="{{ logoImage }}" id="headerImage" alt="Test Google" style="border: 0px; height: auto; line-height: 34px; outline: none; max-width: 600px !important;" />
</a>
```
