### ISSUE TITLE
Define default component display/CSS properties

### ISSUE THREAD

**Issue by tomgreever** [canjs/canjs#1581]
Problem: 
Browsers see custom components as `display: inline;` by default. Every new component I create has to have `display: block` applied. Sometimes that's the only CSS the component needs, so I have a bunch of less files for components with that one line.

Solution:
- Would be great to define a default display style for all components, like `display: block;`
- Or be able to define an entire set of default CSS properties for every component. Maybe all my components need a standard border.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-component/issues/12
