### ISSUE TITLE
Allow a data-can-autorender attribute to trigger autorender

### ISSUE THREAD

**Issue by ccummings** [canjs/canjs#1611]
Allow autorender functionality for a script tag with a `data-can-autorender` attribute.

**Comment by matthewp** [comment]
Here's where to do it: https://github.com/bitovi/canjs/blob/master/view/autorender/autorender.js#L58

**Comment by daffl** [comment]
Would just become `can.$("[can-autorender], [data-can-autorender]")` right?

**Comment by justinbmeyer** [comment]
@mjstahl did your commit land?  Can you submit a pull request?

**Comment by mjstahl** [comment]
@justinbmeyer Pull request has been committed - https://github.com/bitovi/canjs/compare/1611-data-can-autorender

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-view-autorender/issues/4
