### ISSUE TITLE
Component cross bindings not working when child component mutates bound properties.

### ISSUE THREAD

**Issue by m-mujica** [canjs/canjs#1612]
I've created a jsbin with a small example of this issue.

http://jsbin.com/hekege/1/edit?js,console,output

There I create two components `app-parent` and `app-child`; using the define plugin, `app-parent`'s viewmodel define `foo` and `bar` both with default values (`false`).

`app-child` receives both properties from `app-parent` (cross bound, `foo={foo}`) and it 'mutates' those properties by: 

1) defining a `foo` property in its viewmodel that returns true. (wondering if getters are only 'local', in which case it makes sense why parent's foo does not get updated).

2) *calling `this.attr('bar', true)` in the `init` method of its viewmodel. 

* it worked for me when I did a `this.scope.attr('foo', true)` in the `inserted` event so, cross-binding are indeed being set up after init.

**Comment by justinbmeyer** [comment]
Updated to minor: http://jsbin.com/ziwuhe/edit?html,js,output

I think there's several things going on here.

With regards to `foo`, the most important thing to understand is that can.Component prevents cycles.  If a child changes a parent, the child can't change immediately. If a parent changes a child, the parent can't change immediately.

So, what I believe is happening is that `foo` is being set to `false` on the child, but as there is no change (as get returns true), the parent is never updated.

With regards to `bar`, the child's viewModel is being created with `bar=false`, however, it changes it to true before we've had the chance to setup any listeners on the child to reverse-propagate to the parent.  In fact, `can.Map` doesn't even produce events during `init`.

The only solution to this would be to check what the viewModel's look like after being created, and try to update the parent view model if anything is different.

Somewhere around here: https://github.com/bitovi/canjs/blob/minor/component/component.js#L219

We could loop through `viewModel.attr()` and see if anything was different from `initialScopeData`.  If it was, we could try to set the value back to `twoWayBindings[prop].compute(update)`, but not before temporarily incrementing `viewModelPropertyUpdates[prop]` to prevent that change from updating the client viewModel.

**Comment by justinbmeyer** [comment]
Shows the new child-2-parent bindings can set this right: http://jsbin.com/vorote/edit?js,console,output

**Comment by justinbmeyer** [comment]
Closing because I'm betting this isn't a big problem with the new binding syntaxes.
