### ISSUE TITLE
Getting Started Guide Revisions

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#1615]
## Technical Requirements

- "nested" routing + linking
- basics Model / Component / Stache / Map / can.compute
- CRUD Modeling / fixtures
- the define plugin
- cross component communication
- error handling / loading states

- "pure dom" widgets?
- validation?

## UX Requirements

- Homepage / Order History / Restaurants (show which one is active)
- Loading state
- Error state
- Show lunch or dinner depending on time?
- Open and closed?

Stretch
- Login
- Show side items

**Comment by pYr0x** [comment]
+1

**Comment by tomgreever** [comment]
Ok, I've got the HTML / CSS designs ready and will add to the repo soon. Some notes...

## Common Header
Contains a nav with hover and `active` states:
![screen shot 2015-04-16 at 10 05 38 am](https://cloud.githubusercontent.com/assets/326843/7183958/291da272-e420-11e4-8adf-fd2a225e8aa5.png)

## Common Breadcrumb
To show the nested routing:
![screen shot 2015-04-16 at 10 06 40 am](https://cloud.githubusercontent.com/assets/326843/7183981/4d677680-e420-11e4-8ff5-218f779bc530.png)

## Homepage Hero
Just the content for a static homepage. 
![screen shot 2015-04-16 at 10 07 12 am](https://cloud.githubusercontent.com/assets/326843/7183996/6130c9c8-e420-11e4-8465-8857aef6f726.png)

## Restaurant List
With possibility of showing "Open" or "Closed" depending on the time of day. 
![screen shot 2015-04-16 at 10 07 33 am](https://cloud.githubusercontent.com/assets/326843/7184005/75218d6e-e420-11e4-854d-44c18624197c.png)

## Restaurant Header
Both the restaurant page and the order form should share this header: 
![screen shot 2015-04-16 at 10 08 45 am](https://cloud.githubusercontent.com/assets/326843/7184029/976dac4a-e420-11e4-829d-01ed9835a5fb.png)

## Restaurant Page
Just a static page. We don't really need this page (as far as UX goes), but it helps to have the form one level deeper for the routing part of the demo. Get more ipsum dummy copy here [http://www.lipsum.com/feed/html](http://www.lipsum.com/feed/html)
![screen shot 2015-04-16 at 10 09 48 am](https://cloud.githubusercontent.com/assets/326843/7184056/bf3ef602-e420-11e4-8fe1-b21a9a0be7ad.png)

## Restaurant Order Form
With tabs for lunch and dinner. Select the correct tab depending on time of day. Dynamically update the total $$ as the user checks the boxes. Error states require a `class="has-error"` on the parent element.
![screen shot 2015-04-16 at 10 12 09 am](https://cloud.githubusercontent.com/assets/326843/7184122/1e83e906-e421-11e4-94ac-c7f8a8a2c919.png)

## Order History
Just a simple table with Delete
![screen shot 2015-04-16 at 10 12 47 am](https://cloud.githubusercontent.com/assets/326843/7184134/326ca4d0-e421-11e4-9acd-b0d8a6c38a3c.png)

## Loading State
This is just `<div class="loading"></div>`
![screen shot 2015-04-16 at 10 13 20 am](https://cloud.githubusercontent.com/assets/326843/7184157/485dfc26-e421-11e4-8df1-d99e5c1a9ab2.png)

**Comment by tomgreever** [comment]
To add to the design: 
* Status / notification indicator to the main menu for Orders
* 3 states for order: Delivered, New, In Progress plus a control for changing the state
  - Filter / sort based on the columns?

**Comment by tomgreever** [comment]
Ok, I've updated the header and the order history table. 

@justinbmeyer please take a look and let me know if this is what you had in mind. 

### Header
Has notification for new orders
![screen shot 2015-04-29 at 2 58 47 pm](https://cloud.githubusercontent.com/assets/326843/7400134/4d06bc0e-ee80-11e4-8bbd-ba67c42f899d.png)

### Order History
Rows have states for New, Preparing, Out for Delivery, and Delivered. 
![screen shot 2015-04-29 at 2 58 39 pm](https://cloud.githubusercontent.com/assets/326843/7400152/68c790d0-ee80-11e4-9693-442ff2dc2633.png)

**Comment by tomgreever** [comment]
I updated my pull request with these changes https://github.com/bitovi/canjs/pull/1624

**Comment by daffl** [comment]
Can we move the styling updates to https://github.com/bitovi/place-my-order for now? That's where we're building the app for the talk and it would be nice for me to not have it to move back and forth from this branch.

**Comment by pYr0x** [comment]
@chasenlehara: i like the new guide very much! good work ! i would like to have more info about can.Construct. difference about construct.init and construct.setup and the static can.Construct.setup. this is still  confusing me..
