### ISSUE TITLE
can List concat serializes the objects in the list before adding it to the resulting list

### ISSUE THREAD

**Issue by James0x57** [canjs/canjs#1616]
Fiddle:
http://jsfiddle.net/qYdwR/2468/

when you click on a source item (either), it adds it to a bucket
I concat both buckets and check if the item is in either before adding it
the concat clones the items into a new array/list rather than just putting the item itself in the new array/list

the item should still be the same item after a concat
just also be in the new list/array

https://github.com/bitovi/canjs/blob/master/list/list.js#L998

Thoughts?

**Comment by James0x57** [comment]
Sooo we need some discussion on this, via #1758 

**_Points of argument:_**
**1)** The problem in #1758 says that if your can.List has a custom Map Type, pushing a new item which is already a map of some other type onto that list, you would expect the pushed item to be converted to the custom Map Type because the List's Map Type is set.

**2)** The problem in this issue ( #1616 ) is that concat was serializing the items from each input list before creating the concatenated output List, which means:
sourceList[ 0 ] !== ( sourceList.concat( [] ) )[ 0 ];
which is wrong by typical definition of concatenation.
-- The list created by concat uses the same constructor as the list on the left side of the argument

**_Goals/Discussion:_**
**1)** Be consistent. Which should we favor?:
-- Any item in the List should be the same type as it's Map Type, so all List methods should type cast.
OR
-- List methods should behave like array methods ( without type casting the args ) so any type casting needs to be done manually.

**2)** Should we give the option for either?
someList.push( /* can push fn, type enforced */ );
someList.push.raw( /* vanilla push fn, no type casting */ );

**3)** Document this behavior for each method. ( even if we don't resolve the inconsistency? )

**Comment by justinbmeyer** [comment]
Can't we check the type?

**Comment by justinbmeyer** [comment]
To further clarify, should it be more like:

```
concat: function () {
			var args = [];
                        var MapType = this.constructor.Map;
			can.each(can.makeArray(arguments), function (arg, i) {
				args[i] = (arg instanceof can.Map) && !(arg instanceof MapType) ? arg.serialize() : arg;
			});
			return new this.constructor(Array.prototype.concat.apply(can.makeArray(this), args));
		},
```

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-list/issues/3
