### ISSUE TITLE
Resources ending with trailing slash

### ISSUE THREAD

**Issue by rkojedzinszky** [canjs/canjs#1630]
That would be nice if the resource option to can.Model.extend would behave as that it would leave the trailing slash to the generated urls. As in the model.js sources in createURLFromResource comment a
```javascript
resource: "/todos"
```
will end in
```javascript
findAll: "GET /todos",
findOne: "GET /todos/{id}"
```
with a trailing slash added it should be
```javascript
findAll: "GET /todos/",
findOne: "GET /todos/{id}/"
```
Namely, I would like to use canjs models with django-tastypie, which expects a slash after all resource URIs.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-connect/issues/105
