### ISSUE TITLE
Mark `can.mustache` as deprecated & add note to `can.Component`

### ISSUE THREAD

**Issue by imjoshdean** [canjs/canjs#1638]
With the memory leak fixes that were made to `can.Component` as they relate to `can.stache` exclusively - we have officially turned out backs on `can.mustache`. We should put a deprecated tag on it in the API and perhaps a note on `can.Component` urging people that if they intend to use components then they should use `can.stache` instead, otherwise there is the potential for bad memory leaks.

**Comment by pYr0x** [comment]
I agree, but if you marked mustache as deprecated you have to remove mustache as a hard coded dependency for can.component

**Comment by matthewp** [comment]
@pYr0x we can't remove it as the default until 3.0.  This notice is just a warning that mustache won't have priority on bug fixes and eventually will be removed.
