### ISSUE TITLE
can.Model.model updates nested properties incorrectly

### ISSUE THREAD

**Issue by Bajix** [canjs/canjs#1647]
Whenever a request occurs, behind the scenes this uses can.Model.models, which in turn use a model store. The intent here is that if there is already a model instance for a given ID, instead of creating a new instance, this should instead merge properties and use a single object reference to represent each resource.

It is also a common case to create data structures that have nested data, and to utilize the define "Type" property to automatically construct can.Model.extend instances.

The problem arises now that simply making a request can result in updating the wrong models in unintended ways. When setting nested properties given plain data, this will check if the property being set is already observable, and if so update properties on the current value. For example, if you had nested items A, B, and loaded in B, A, C, in an ideal scenario B, A, and C would all be turned into model instances using can.Model.model, A and B would both (maybe) have changes, and the new A and B would be the same object references as the old A and B. Instead, what happens is that this will check to see if member 0 (A) is an observable, and update it with the new member 0 (B)'s data. Whoops. My A reference everywhere else now has B data.

Here's an example to illustrate:
http://jsfiddle.net/3pze32qh/2/

**Comment by Bajix** [comment]
This might also just be an issue with .attr

Modifying can.Model.model like below to loop through the passed attributes and use the key value syntax instead of the object syntax allows the more fine grain capabilities of the define plugin to take over

```
model: function( attributes, oldModel, xhr ) {
  if (!attributes) {
      return;
  }
  if (typeof attributes.serialize === 'function') {
      attributes = attributes.serialize();
  } else {
      attributes = this.parseModel(attributes, xhr);
  }
  var id = attributes[this.id];
  if ((id || id === 0) && this.store[id]) {
      oldModel = this.store[id];
  }

  if (oldModel && can.isFunction(oldModel.attr)) {
    for (var key in attributes) {
      oldModel.attr(key, attributes[key]);
    }
    return oldModel;
  }
  return new this(attributes);
}
```

**Comment by justinbmeyer** [comment]
I think the define plugin can make this a bit better.  It can control how items are merged or overwritten.  You could look up the item in the store.

**Comment by justinbmeyer** [comment]
closing: https://github.com/canjs/can-define/issues/17
