### ISSUE TITLE
Possible memory leak with observable in template

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#1666]
In the process of trying to narrow down the cause of an apparent memory leak in my app, I came across something strange as a result of rendering a stache template with an observable (can.Map).

Simplified version (just a can.Map):
http://jsbin.com/vavecuyaxi/1/edit?js,console,output

Original version (using can.Model with model store):
http://jsbin.com/rewiwiritu/1/edit?js,console,output

Click the create button then the destroy button, then repeat a couple times. You can see the _bindings count (and the __bindEvents.name array) on the person keeps increasing. If it were to go back to 0 in the second example, the model would be removed from the store at some point, but that never happens.

If you use a ```new can.Map``` each time instead of the existing one, there does not appear to be a leak, probably because the object is being garbage collected along with its events. However, that does leak in mustache. To see that in action, just run the following code in your debugger while recording memory usage.

```
setInterval(function () {
    can.mustache('{{ name }}')(new can.Map({name: 'Bob'}));
}, 100);
```

**Comment by moschel** [comment]
added breaking test: https://github.com/bitovi/canjs/commit/1895ae047984c31ad93b6bf93cf1e8366b92d749

**Comment by moschel** [comment]
@dylanrtt if your template is '<span>{{ name }}</span>' the _bindings count does go back down to zero - its async so your jsbin would not have seen it.

But if there is no wrapping element in the template, like '{{ name }}' it doesn't go back down to zero, so that suggests a leak

**Comment by moschel** [comment]
I think I remember coming across this once before and there's no good way to solve it, because the hook that triggers "removed" - https://github.com/bitovi/canjs/blob/master/util/jquery/jquery.js#L134 - doesn't get called in the case of a textNode removal, which is the case if your template is simply "{{name}}". The easy workaround is to always wrap your templates with a DOM node.

Maybe we should be throwing a warning in the case where a template isn't wrapped with an HTMLElement.

@daffl @justinbmeyer, any thoughts? Is this fixable?

**Comment by justinbmeyer** [comment]
@brianmoschel Yes, your test is "unfixable". However, you can have a template with no parent, only you need to remove the parent.  If you changed your test to remove the parent of the template, all bindings should be removed.

We could also allow people to pass their own nodeList and tear it down manually if they are in this situation.

A warning should only be thrown if a nodeList isn't provided to the template.  There are many situations internally where they are.

**Comment by dylanrtt** [comment]
@justinbmeyer I am not sure that removing the parent takes care of the bindings. For example, in the following jsbin, the template is rendered into a div, which is then added to the container. If I understand you correctly, emptying the container (which removes the div) should remove the bindings, but that doesn't appear to be happening.

http://jsbin.com/liwezuwoke/1/edit?js,console,output

**Comment by gsmeets** [comment]
This seems to leak even if I use a wrapping element:

    <script src="/Scripts/1.0.0.0/lib/jquery/jquery-1.11.2.js"></script>
    <script src="/Scripts/1.0.0.0/lib/can.debug.min.js"></script>
    
    
    <script>
        
        var template = can.stache( "<p>{{test}}</p>" );
        var foo = false;

        $( document ).click( function() {
            if ( foo ) {
                $( "div" ).remove();
            } else {
                var fragment = template({ test: "test2" });
                $( "div" ).append( fragment );
                foo = true;
            }
        });
        
    </script>

Using the 3 snapshot technique:
* First snapshot after load. 
* Click the screen,
* Snapshot
* Click the screen

![image](https://cloud.githubusercontent.com/assets/2570742/8570398/3a50ee5e-2580-11e5-8a57-63e114c35890.png)

If I change can.stache into can.mustache and repeat the procedure I don't get those dom nodes floating about.

**Comment by justinbmeyer** [comment]
This doesn't look like it is ever appending the   Fragment after the first time. This is because there are no divs to append it to. 

If that is the case, Stache will leak, but this isn't a valid use case.

**Comment by gsmeets** [comment]
There's one div in the page. After the first click it appends the template to the div, the next click the div is removed.  It's definitely appended to the page.

**Comment by justinbmeyer** [comment]
> the next click the div is removed. It's definitely appended to the page.

But on all future clicks, there is no div right?

**Comment by gsmeets** [comment]
Yes, but I only click twice you know ;) I think I can probably dumb the example down more, hang on.

**Comment by gsmeets** [comment]
Yes, even this poses a problem:

	var template = can.mustache( "<p>{{test}}</p>" );
		
	var fragment = template({ test: "test2" });
	$( "div" )
		.append( fragment )
		.remove();

![image](https://cloud.githubusercontent.com/assets/2570742/8580173/5dd4f1c0-25b9-11e5-96dc-13bf13f83301.png)

**Comment by gsmeets** [comment]
On second viewing, scratch that though, that's actually jQuery causing it. So I do need the 3 snapshot method to be sure it's the executed code that causes the leak.

**Comment by dylanrtt** [comment]
Looks like this is unfixable. In summary, the problem is the lack of a wrapping element around the bindings. The fix is to add a wrapping element when using `can.stache()`.

**Comment by justinbmeyer** [comment]
You could also pass your own nodeList and make sure you tear it down:

```
var template = can.stache("{{something}}");

var nodeList = [];
can.view.nodeLists.register(nodeList);
$(document.body).append(template({},{}, nodeList));

// sometime later ...
$(document.body).empty();
can.view.nodeLists.unregister(nodeList);
```
