### ISSUE TITLE
RFC: Allow a can.Component to use a different tag

### ISSUE THREAD

**Issue by marshallswain** [canjs/canjs#1680]
In today's Open Source Standup, @justinbmeyer mentioned that it would be nice to be able to tell a component to render with a different tag.  The specific example was for using an existing component inside a table but having it render as a `<tr>` or `<td>` in place of the original `<my-component>`, in the template.

@justinbmeyer, How would you want it implemented?
```
<my-component can-tag="tr">
```

**Comment by matthewp** [comment]
This would be on the Component prototype. The idea is to have a component be represented as a different tag in scenarios where a custom tag isn't possible (like in place of a <tr>).  There's another issue for allowing attrs to be Components: https://github.com/bitovi/canjs/issues/648#issuecomment-73942483  that I personally really like as well.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-stache/issues/15
