### ISSUE TITLE
Add helpers to can/view/autorender/system plugin

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#1682]
Currently you can do:

```html
<can-import from="my/state" as="viewModel"/>
```

And the state will be used as the viewModel for the template.  It would be useful to also have helpers for your main template so I'd like to support:

```html
<can-import from="my/helpers" as="helpers"/>
```

And this object will be passed as the second argument to the renderer.

**Comment by justinbmeyer** [comment]
@matthewp this is for can-ssr right?  `<can-import>` can export any import now, it's on can-srr to respect it?
