### ISSUE TITLE
Can Component fires event before template rendering in CanJS 2.2

### ISSUE THREAD

**Issue by lihan** [canjs/canjs#1685]
Live code here: http://jsfiddle.net/grany8aa/

```
var Component = can.Component.extend({
    tag: 'content-renderer',
    template: '{{{content}}}',
    viewModel: {
        define: {
            content: {
                type: 'string',
                value: 'loading...',
                set: function(newVal){
                    return newVal;
                }
            }
        }
    },
    events: {
        '{scope} content change': function() {
            var self = this;
            console.log('log from event ' +this.element.html());
            setTimeout(function(){
               console.log('log from timeout ' + self.element.html());
            });
        }
    }
});
```
In CanJS 2.1, when ``content`` attribute changes, the content will be reflected on DOM before the ``change`` event fires. But this is not the case in CanJS 2.2

In CanJS 2.2, when ``content `` attribute changes, the ```this.element.html()``` will not contain the updated ``content``. 

Is this a regression in CanJS 2.2? Otherwise, please suggest a fix for this without having to use ``setTimeout``.

**Comment by justinbmeyer** [comment]
I don't think this is a regression.  The event dispatching order of `events` handlers compared to the DOM is not documented or tested.  

However, it might be possible to control for this deterministically.

I think the internal control needs to be created after the rendering: https://github.com/bitovi/canjs/blob/master/component/component.js#L282

If you can submit a test (and maybe a fix if it's as easy as moving the control initialization under the template rendering), we can get it in a release.

**Comment by lihan** [comment]
@justinbmeyer I created a failing test for this issue. But the issue will not be resolved by simply change the order of internal control initialization code. I think this would only affect ``insert`` event. In my test case, it tested against the ``change`` event from ``viewModel``.

Another finding is, if I remove the ``set`` function from the ``content`` property, this issue will go away.

**Comment by justinbmeyer** [comment]
I'm closing this and marking it as "needs a hero".  @lihan or anyone else who runs into this problem, I'm happy to pair on making the change.  Just ping me when you have an hour to work on it on gitter: https://gitter.im/canjs/canjs
