### ISSUE TITLE
Promote render-to-vdom's can.inserted function to Master

### ISSUE THREAD

**Issue by imjoshdean** [canjs/canjs#1686]
The can.inserted function in render-to-vdom is a lot more powerful and works fine on 2.2.5. We should get it into Master as soon as possible as opposed to waiting until 3.0 when vdom is supposed to come to fruition.

https://github.com/bitovi/canjs/blob/render-to-vdom/util/inserted/inserted.js#L6

**Comment by matthewp** [comment]
Why is it more powerful?

**Comment by imjoshdean** [comment]
It works in windows besides the primary window, meaning it'll allow inserted events to fire if you insert DOM into a different window.

**Comment by daffl** [comment]
I don't think we introduced any breaking changes with VDom and it would be still good for 2.3 which we could do fairly soon.

**Comment by imjoshdean** [comment]
@daffl wouldn't switching Stache to use VDom be a substantial change? I remember VDom being a 3.0 feature because of this.

**Comment by matthewp** [comment]
We're not going to switch Stache to use vdom.  We could possibly have a feature to do rendering in a web worker and that would use vdom, but in a normal browser window it will remain as it is.

**Comment by justinbmeyer** [comment]
I think this is working right?

https://github.com/canjs/canjs/blob/master/util/inserted/inserted.js#L12

Should be getting the owner document of the element being inserted (assuming `document` wasn't passed correctly).  

@imjoshdean anyway you can create a test for this (or check that it's still not working)?  Presumably you could create an iframe and insert a template into it and see if stuff works.

**Comment by justinbmeyer** [comment]
this is resolved in 3.0.
