### ISSUE TITLE
Add support for "can-text" event

### ISSUE THREAD

**Issue by isadovskiy** [canjs/canjs#1698]
Right now there is a way to listen for attribute changes via can-attributes event. But there is no way to listen for changes in node's text. So would be great to have can-text event, which can be used to listed text changes on the specific node.

$(el).bind("text", function(ev){ .... });
$(el).text("some new text");

And add support for can.Control and can.Component event binding syntax

**Comment by justinbmeyer** [comment]
@isadovskiy I don't think we are going to add this.  In 3.0, my plan is to switch to Mutation observers.  Hopefully you support only browsers that have this.

If not, I can probably show you how to hack this in.

**Comment by isadovskiy** [comment]
Thanks for this update, @justinbmeyer. No immediate need to hack it.
