### ISSUE TITLE
Modify key -> argument behavior in can.stache

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#1699]
## Orignal Post

> As far as I can tell, I cannot pass a function directly to a component because it sees it as a compute and tries to run it. I have to pass an object or wrap the function in a function instead which isn't always convenient.

> http://jsbin.com/domutinoze/1/edit?html,js,console

## Summary

We are proposing a COMPUTE `~` and AT `@` operator.  `~` would try to provide a "compute", while `@` would give directly whats AT the specified property.  The following table describes its behavior.

#### Uses of Keys:

 - __helper expression__ - The arguments passed to stache helpers like `{{myHelper key1 key2}}`.
 - __call expression__ - The arguments passed to subexpressions like `{{myHelper(key1,key2)}}`.
 - __components__ - The `.attr` value that will be set in the component's viewModel for bindings like `[attr]="key"`.
 - __method helper expression__ - The arguments passed to an `(event)` binding like `($click)="method key"`.

##### Computes

An observable chain that ends in a compute.  Examples for `foo.bar`:

```js
// a compute as a property
{foo: {bar: can.compute(1)}}

// a compute as a map attr
new can.Map({ foo: {bar: can.compute(1)} })

// a compute returned by a function
{foo: function(){  return {bar: can.compute(1)} }} 
```

##### Functions

An observable chain that ends in a function or method.  Examples for `foo.bar`:

```js
// A method that reads an observable
{foo: {bar: function(){ return map.attr("value") }}}

// A method of an observable
var MyMap = Map.extend({bar: function(){  return this.attr("value") }})
{foo: new MyMap()}

// A property of an observable
new can.Map({ foo: {bar: function(){...} } })
```

##### Properties

An observable chain that ends in a property on an attr that is not a function or compute.  Examples for `foo.bar`:

```js
// an observable property
new can.Map({foo: {bar: "value"}})

// An observable returned by a function
{foo: function(){  return new can.Map({bar: "value"}) }}
```

#### Resulting behaviors:

* R - Reference
* R() - Executes the reference to get the value
* (R) - Wraps the observable chain in a compute
* (!R) - Wraps the observable chain in a compute only if an observable was read
* {} - Listen to changes and re-execute.

#### Behavior table

| `key`  | computes | functions | properties | general behavior
| --- | --- | --- | --- | ---
| helpers | (R()) | *1* | (R) | pass a compute if possible
| subexpression | {R()} | {R()} | {R} | pass the return value of a compute or function, re-call if something observable changes.
| components | {R()} | {R()} | {R} | two way bind to a compute or `map.attr`, 1-way bind to a function
| methods | R() | R() | R | pass the return value of a compute or function

 - 1 - If the `key` is a function on a normal object, the function is passed, even if the function calls a compute.  If the key is a function on a Map prototype, a `compute()` is passed regardless if the method is compute-able or `undefined` is returned and not compute-able.  If `key` is a function on a Map attribute, a compute is passed whose value is the function.

| `~key` | computes | functions | properties | general behavior
| --- | --- | --- | --- | ---
| helpers | (R()) | (!R()) | (R) | pass a compute if possible
| subexpression | (R()) | (!R()) | (R) | pass a compute if possible
| components | (R()) | (!R()) | (R) | 1-way bind a compute as a value if possible
| methods | (R()) | (!R()) | (R) | pass a compute if possible

| `@key` | computes | functions | properties | general behavior
| --- | --- | --- | --- | ---
| helpers | {(R)} | {(R)} | {(R)} | pass a compute that returns a a function or compute at the _end_ of the path.
| subexpression | {R} | {R} | {R} | pass a reference, but re-call if reference changes
| components | {R} | {R} | {R} | two-way bind to the reference
| methods | R | R | R | pass the reference

### key / helpers / computes

```js
// Context
context = new can.Map({foo: {bar: can.compute(1) }}

// compute passed for `foo.bar` argument:
compute(function(set){
  return context.attr("foo").attr("bar")(set)
})
```

### key / components / properties

```js
// Context
context = new can.Map({foo: {bar: "value" }}

// viewModel set for `prop="{foo.bar}"`:
viewModel.attr("prop", "value" )
```

### ~key / components / properties

```js
// Context
context = new can.Map({foo: {bar: "value" }}

// viewModel set for `prop="{~foo.bar}"`:
viewModel.attr("prop", compute(function(set){
  return map.attr("foo").attr("bar",set)
}) )
```

## @ key / components / functions

```js
// Context
function bar(){ ... }
var MyMap = Map.extend({bar: bar})
context = new Map({foo: new MyMap()}

// viewModel set for `[(prop)]="foo@bar"`:
viewModel.attr("prop", bar ) // if context.attr("foo") changes, a different function can be set here.

```

**Comment by daffl** [comment]
Function are always implicitly called in Mustache (and Stache). As you have shown in your Fiddle this can be solved by wrapping it into another function. Since this is expected behaviour and part of the Mustache specification with a workaround available I don't think there is anything we can do to change this.

**Comment by dylanrtt** [comment]
I can't accept "won't fix" as an answer for this anymore. This keeps coming up as a problem I need to workaround whereas angular 1.x provides this by simply throwing `&` on the directive definition (which is gross I know). We could probably do something like this:

```html
// passing function to component
<my-dialog callback="{ &myMethod }"></my-dialog>

// passing function to can-EVENT
<input type="button" can-click="{ doStuff &myMethod }">
```

Here's a simplification of a recent use case I encountered where I could not find a suitable workaround.

**my-component.js:**
```js
can.Component.extend({
  tag: 'my-component',
  template: // my-component.stache
  viewModel: {
    myMethod() {}
  }
});
```

**my-component.stache:**
```html
<!-- stuff -->

<!-- component somewhere in the middle -->
<my-dialog></my-dialog>

<!-- more stuff -->
```

**my-dialog.js:**
```js
can.Component.extend({
  tag: 'my-dialog',
  template: // my-dialog.stache
  viewModel: {
    // close dialog only if form validates
    closeDialog(validator, myMethod) {
      if (validator.validate()) {
        myMethod();
      }
    }
  }
```

**my-dialog.stache**
```html
<my-validator-group #group-validator>
  <div class="form-group {{^if nameValidator.isValid}}has-error{{/if}}">
    <input type="text" class="form-control" can-value="{person.name}">
    <my-validator #name-validator map="{person}" field="name"></my-validator>
  </div>

  <input type="button" class="btn btn-primary" can-click="{closeDialog groupValidator &myMethod}">
</my-validator-group>
```

There is no way for me to pass `myMethod` to that function. If `my-component`'s view model was exposed as a `#reference` then I could pass that in but that can't be done when all of this resides within `my-component.stache`.

Angular 1.x lets you use the `controllerAs` property of a directive which namespaces the controller. This affects the component's template so I could probably pass `myComponent` to the click handler if I wanted to, but we don't have a way to reference the current template's context like that except for in `can-EVENT` which doesn't work here since the click event is too deep.

Here are some alternatives I did not want to do.

**Bad Alternative 1:** I could pass `@element` to closeDialog and have it trigger an event which is hooked up to `myMethod` on the element via `can-EVENT`. I don't like the idea of triggering DOM events in the view model.

**Bad Alternative 2:** Adapting option 1 to not trigger in the view model, create a new view model property and change it just for this purpose. Add an event handler in the component that triggers the event... more convoluted.

**Bad Alternative 3:** Create another object on the `my-component` view model that exposes the method... it shouldn't come to this.

```js
define: {
  api: {
    get() {
      return { myMethod: this.proxy(this.myMethod) }
    }
```

Similar to method 3, the more traditional way would be to have `my-dialog` expect an object on which would be the method it should call. If it were just a dialog, that would make sense but my example above is a simplification; the actual scenario I have makes that seem inappropriate... perhaps because it needs to be partially redesigned but this all would have been so much easier if I could just pass a function reference in stache.

**Comment by justinbmeyer** [comment]
We've talked about a & operator for a long time. Not sure why it was marked as won't fix. Easier to add now that expression logic has been improved.

**Comment by patrickclancy** [comment]
+1 would love this feature

**Comment by matthewp** [comment]
Let's open this back up to discussion.

**Comment by justinbmeyer** [comment]
Should we use `*` or `&`? In C, * dereferences, `&` gives you the pointer address.  I suppose `&` makes sense. `*` would mean get the value ... `&` will mean give me the thing that can get me the value.

I'd like to take this into account with calling helpers.  Would the following call `myHelper` with 5 if `value=can.compute(5)`?

```
{{myHelper *value}}
```

What would:

```
{{myHelper &value}}
```

do?  Probably still just pass the compute?

**Comment by justinbmeyer** [comment]
Here's how to add this to minor.  A few things to prepare yourself with:

- Expressions like `{{foo (bar &zed) 5 tex="mex"}}` are tokenized, parsed and converted into "expression data".
- They are tokenized here: https://github.com/bitovi/canjs/blob/minor/view/stache/mustache_core.js#L334
- And parsed here: https://github.com/bitovi/canjs/blob/minor/view/stache/mustache_core.js#L291
- Expression data ends up looking like:  https://github.com/bitovi/canjs/blob/minor/view/stache/mustache_core_test.js#L8
- Component's don't use expression data.  They should!  
- [can.compute.read](https://github.com/bitovi/canjs/blob/master/compute/read.js#L10) can take options that control how something like "foo.bar" is read.  

Basically, expression data is a bunch of expression objects.  You can get the value of an expression object like:

```
exprData.value(scope, options) //-> * | compute
```

## 1. Token *

Ok, so with that in mind, the first thing is to make sure `*` turns into a token.  That can be done by changing `argumentsRegExp` here: https://github.com/bitovi/canjs/blob/minor/view/stache/mustache_core.js#L34.

## 2. Make `ScopeExpression` handle `&` and other options.

ScopeExpression is defined here: https://github.com/bitovi/canjs/blob/minor/view/stache/mustache_core.js#L107 as just taking a key to look up in the scope.  This probably needs to take an optional `readOptions` so I can do something like:

```
var funcRef = new ScopeExpression("func",{
  returnObserveMethods: true,
  proxyMethods: true,
  isArgument: true
});

var func = function(){}

funcRef.value(new can.view.Scope({
  func: func
})) //-> func
```

The `readOptions` passed to `ScopeExpression.prototype.value` should be merged with the one passed in when the `ScopeExpression` is being created.

## 3.  Make `_expressionData` create the right `ScopeExpression`s when it sees a `&`.

Basically, we need something like:

```js
if(token === "&"){
  cursor.index++;
  args.push( new ScopeExpression(nextToken, {
    returnObserveMethods: true,
    proxyMethods: true,
    isArgument: true
  } ));
}
```

## 4.  Test

At this point, there should be a test in https://github.com/bitovi/canjs/blob/minor/view/stache/mustache_core_test.js making sure that the new ScopeExpression functionality works and that `.expressionData` parses `&`s right.

At this point, you should be able to pass functions as `can-EVENT` arguments and to helpers.  YAY!  We should add some tests in `stache/stache_test.js` and `bindings/bindings_test.js` to make sure.

## 5. Components

Once the basics of this works, we need to make components work.  The best way to do this would be to use `.expressionData` to parse each attribute value.  And use the resulting expression data to get the value / compute instead of doing it manually as is done here: https://github.com/bitovi/canjs/blob/minor/component/component.js#L161

**Comment by dylanrtt** [comment]
> Someone needs to fill out the following matrix:

I believe it's currently like this:

|  | helpers | components | methods
| --- | --- | --- | ---
| computes | R | V | V
| functions | R | V | V
| properties | R * | V | V

_*_ Scope properties/objects are wrapped in computes when passed to helpers which seems like a special case because the function did not originally exist.

I think primitive values are always passed as values so I did not include them.

`*` should always pass values and `&` should always pass references so I'm not sure these tables are necessary. `*` would allow passing values directly to helpers and `&` would allow passing functions/computes to components/methods; any other variation would give the current behavior.

| `*` | helpers | components | methods
| --- | --- | --- | ---
| computes | V | V | V
| functions | V | V | V
| properties | V | V | V

| `&` | helpers | components | methods
| --- | --- | --- | ---
| computes | R | R | R
| functions | R | R | R
| properties | R | R | R

**Comment by justinbmeyer** [comment]
If I understand you correctly, I think the default behavior is:

|  | computes | functions | properties
| --- | --- | --- | ---
| helpers | R | (R) | (R)
| components | R() | R() | R
| methods | R() | R() | R

If a helper is passed a function, I think that function is converted to a compute.  I might be wrong though.  This matrix would make good docs :-)

**Comment by dylanrtt** [comment]
It turns out we're both wrong. It runs it.

http://jsbin.com/teyukumozo/edit?html,js,console

So this is how it currently works as far as we know:

|  | computes | functions | properties
| --- | --- | --- | ---
| helpers | R | R() | (R)
| components | R() | R() | R
| methods | R() | R() | R

**Comment by justinbmeyer** [comment]
http://jsbin.com/pedavaqofo/edit?html,js,console

It's converted to a compute if the function reads an observable.

**Comment by dylanrtt** [comment]
Interesting. I was originally thinking of `(R)` as adding an additional layer of a function where executing it would return the original reference. In this case, you just get a different function like `(R())` which returns the value of executing the original reference.

I would say that is fine for `&` to pass along except that in order to know the function is observable, it has to be executed which I don't think is acceptable.

**Comment by justinbmeyer** [comment]
> I would say that is fine for & to pass along except that in order to know the function is observable, it has to be executed which I don't think is acceptable.

I think it makes a lot of sense for a helper.  A helper really only gets "values" as arguments and needs to produce some sort of content.  It would be a very rare helper you needed to configure with a function.

**Comment by justinbmeyer** [comment]
@dylanrtt I'm going to try to make a document outlining the default behavior in almost any circumstance.  With that done, i'll revisit these `*` and `&`.  I've started the document here:

https://docs.google.com/spreadsheets/d/1KytpEzS6dJX5Hd44otuFyWQunnKy9pNHHVz7GW73Ox4/edit#gid=0

It's a work in progress, but please feel to comment.  I might have a hangout Friday to go over it w/ some bitovi folks.  Let me know if you want to join us.  Thanks.

**Comment by justinbmeyer** [comment]
>  I found a case where this would actually be pretty useful.

What use case?

Here's what I think everything should look like:

|  | computes | functions | properties
| --- | --- | --- | ---
| helpers | R | (!R) | (R)
| components | R() | R() | R
| methods | R() | R() | R

| `*` | computes | functions | properties
| --- | --- | --- | ---
| helpers | R() | R() | R
| components | R() | R() | R
| methods | R() | R() | R

| `&` | computes | functions | properties
| --- | --- | --- | ---
| helpers | R | (!R) | (R)
| components | R | (!R) | (R)
| methods | R | (!R) | (R)

**Comment by dylanrtt** [comment]
> What use case?

I was thinking it would be nice to pass a compute to a function so it could and then write back to the property without the function knowing anything about it.

If I understand your chart correctly and the `(!R)` means it runs the function and then creates a compute for it, as I described earlier, that means the function is run initially. For my use cases, that completely defeats the purpose of passing a function to a method or component (not sure I have use case for a helper) because I want the execution to be on my terms.

I was thinking of something like this:

```html
<input type="button" value="Submit" can-click="{doSubmit &validator.validate &dialog.closeDialog">
```

In that example, `validator` and `dialog` are in the references scope and can't be directly accessed by the view model. The idea is to close the dialog only if the validation returns true. Running `closeDialog` initially would obviously be undesirable.

I can currently achieve the functionality I just described by passing the validator and dialog instead of their functions, but that requires the `doSubmit` function to have knowledge of their APIs which is more complicated than it has to be; it might be an unreasonable expectation if `doSubmit` is part of another module entirely.

I would like to apply basically the same concept with components where I could pass a callback that the component will execute whenever it does some specific thing. You can currently do this by passing an object to the component with a method that it will know to call, but I find that to be cumbersome for simple components that have few options.

Using `can-EVENT` doesn't always make sense because you don't typically trigger events from the view model (creating an extra property for triggering an event is dumb), so being able to listen to view model events in stache (#1841) might alleviate the problem.

My goal with passing functions to a components/functions is to simplify the interaction between modules. I'm not sure what value computifying them provides.

**Comment by justinbmeyer** [comment]
I switched * and & in my head .. I'll update the matrix.  Posted it in a rush.

**Comment by dylanrtt** [comment]
If that's the case, then there would still be an inconsistency between passing a computable function and a non-computable one with `*`; sometimes you would have the function and other times you would have return value, which is currently the case for passing functions to helpers.

I was thinking that using `*` with a helper would pass the value like a simple helper so you don't have to deal with the compute, and the binding would be hooked up behind the scenes.

**Comment by justinbmeyer** [comment]
> I was thinking that using * with a helper would pass the value like a simple helper so you don't have to deal with the compute, and the binding would be hooked up behind the scenes.

Yeah, instead, I think I'm going to make subexpressions work this way by default.  That way we can be consistent and flexible in most situations ... even __methods__ could be passed computes.  I was just about to add them to the table.

**Comment by justinbmeyer** [comment]
@dylanrtt I updated the first comment with a summary.  Easier to track there.  Please let me know what you think.  Thanks for your help on this!

**Comment by justinbmeyer** [comment]
Not to self, crazy stuff like this should work:

`{{ foo( &bar().listIt ) }}`

**Comment by justinbmeyer** [comment]
@dylanrtt After a long talk with @mjstahl, we think that `&` and `*` is confusing.  We're thinking of changing it to `~` to make things give you a compute, and `@` to give you what's directly `AT` a certain property value.

`{{helper @my.method}}` will pass whatever it finds at my.method, be it a function, property value, or a compute.

`{{helper ~my.method}}` will pass a compute similar to what is passed now.

I'm going to update the summary with these changes.

**Comment by justinbmeyer** [comment]
btw, we could make these fill in for (.) like:

```
{{helper models@Todo~findAll}}
```

`models@Todo` would mean ... don't try to call the Todo constructor.  `Todo~findAll` would mean to convert the result of findAll to a compute.

**Comment by pYr0x** [comment]
I don't like the @ sign. It's confusing with the @index and @key and http://canjs.com/docs/can.Component.html#sig__TAG_ATTR_NAME_KEY_ATTR_VALUE__

In php a reference is created with &

**Comment by dylanrtt** [comment]
I agree with @pYr0x here. The `&` seems totally reasonable and even angular uses it.

**Comment by justinbmeyer** [comment]
Talking with a few old `C` folks at bitovi, they expected `&` to give them the compute.  As `&` gives you a pointer address, not the actual value, they expected it to make some value more "abstract".

@pYr0x I think @index and @key would actually make more sense now.  

Yes, it might be confusing with the old "@" behavior in viewModels in can.Mustache.  But that's long forgotten.

`@` even sounds better.  It's giving you the value __AT__ some property.  Everything is a reference in JavaScript.  Plus, `@` is still going to give you a compute if the compute is at the end of your lookup path.

**Comment by justinbmeyer** [comment]
@dylanrtt @pYr0x we've been on gitter talking about this all day.  Please join us if you have time: https://gitter.im/bitovi/canjs

**Comment by justinbmeyer** [comment]
Oh, and the fact we can substitute `.` for `@` and `~` really wins me over.  What does: 

```
{{helper models&Todo*findAll}}
```

Do?  It looks like it does a bitwise operation and some multiplication.

The following might not be immediately obvious, but at least doesn't look like something it isn't.

```
{{helper models@Todo~findAll}}
```


This might not seem that useful, but it's common for functions to have other properties on them.  `can.Model`s are great examples that we currently special case.  But those functions might have properties that should be treated as a compute.

**Comment by justinbmeyer** [comment]
A reminder to myself, with expressions like:

`selectedPlate(value)`

The default behavior if `selectedPlate` is an attribute, should be to call `context.attr("selectedPlate", value)`

**Comment by justinbmeyer** [comment]
There's a problem with the proposal.  Should `@foo` in:

`{helper @foo}`


with a context like:

```js
var bar = function(){};
var context = new can.Map({
  foo: bar
});
```

be passed as a `compute` that returns `bar`, or the `bar` function itself?

**Comment by pYr0x** [comment]
i think you are right. it should return a compute.

But can you explain whats the difference between {{helper....}} and CallExpressions?
