### ISSUE TITLE
Proposal: can.batch.debounce

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#1708]
Sometimes you want to handle events, except for when they've been batched with `can.batch.start()` and `can.batch.stop()`. 

In order to do that currently, you'd need to implement some logic like this... 

```
var list = new can.List(); 

// Run once despite many `length` events being dispatched
list.bind('length', function (ev, newVal) {
  if (ev.batchNum) {
    if (ev.batchNum === this._lastProcessedBatchNum) {
      return; 
    } else {
      this._lastProcessedBatchNum = ev.batchNum;
    }
  }
  
  console.log('The new length is... ' + this.attr('length')); //-> 3
}); 

can.batch.start();
list.push('a');
list.push('b'); 
list.push('c');
can.batch.stop()
```
http://jsbin.com/hanate/1/edit?js,console

Aside: Maybe there's a more clever way to write that logic, but this is what I've used and seen bouncing around.

It's not too difficult to implement, but it often gets repeated multiple time within an application (and even within the CanJS repo). It'd be nice if we could abstract this "don't continue unless batchNum is undefined or has changed" logic into a small utility. 

Here's my idea:

```
var list = new can.List(); 

// Run once despite many `length` events being dispatched
list.bind('length', can.batch.debounce(function () {  
  console.log('The new length is... ' + this.attr('length')); //-> 3
})); 

can.batch.start();
list.push('a');
list.push('b'); 
list.push('c');
can.batch.stop()
```
http://jsbin.com/jegiwo/1/edit?js,console (includes a naive implementation)

I'd love some feedback!

**Comment by akagomez** [comment]
Questioning whether "debounce" was a good name for a utility like this I decided to look up the definition.

> Glossary Term: Debounce 

> Electrical contacts in mechanical pushbutton switches often make and break contact several times when the button is first pushed. A debouncing circuit removes the resulting ripple signal, and provides a clean transition at its output.

> http://www.maximintegrated.com/en/glossary/definitions.mvp/term/Debounce/gpk/82

Sounds pretty suitable.

**Comment by matthewp** [comment]
:+1: sounds very useful.  Here you're always catching the event on the end but I wonder if some times you'd rather know at the beginning...

**Comment by imjoshdean** [comment]
While I like the concept, I'm not so sure it's the right solution to the problem you are expressing, which is unnecessarily repetitive events firing on batching. Let's use your example:

```js
var list = new can.List(); 

can.batch.start();
list.push('a');
list.push('b'); 
list.push('c');
can.batch.stop()
```

A `length` event will fire three times with the value being three. Do we REALLY want three events firing...or do we want one? I can't think of a case where I would want three events firing, especially if it is the same event (though I challenge someone to coming up with one, I'm sure it exists). 

I think coming up with a debounce/throttle addition to the batch API, while nice, fixes the symptom, not the problem.

**Comment by akagomez** [comment]
@matthewp In my implementation we're not catching the event on the end. We're calling the function on the first of the batched events. But knowing that this is a batched event, we can read directly from `this` instead of relying on `newVal`.

**Comment by akagomez** [comment]
@imjoshdean 

> A length event will fire three times with the value being three. 

That's not true. We'll get three events. Their `newVal` will be 1, 2, and then 3.

**Comment by imjoshdean** [comment]
@akagomez Sorry, what I meant was that the list's length property would be 3. Not what newVal would be equal to.

**Comment by imjoshdean** [comment]
I guess the big thing for me is I have a certain expectation of `can.batch` that's not being met. Not to detract from your suggestion or implementation because I think it's definitely worthwhile for what we currently have, say with the following example:

```js
var map = new can.Map({
    list: [1]
});

can.batch.start();

map.attr('foo', 'bar');
map.attr('foo', 'baz');
map.attr('list').push(2);
map.removeAttr('list');

can.batch.end();
```

What I would personally expect to get fired are the following events in map:

- change (attr: 'foo', how: 'set')
- change (attr 'list', how: 'remove')
- foo (newVal: 'foo', oldVal: 'bar')
- list (newVal: undefined, oldVal: [1,2])

Because going from the start of batching to the stop of batching, that's really all that's (seemingly) important.

What we currently get is the following:

- change (attr: 'foo', how: 'add')
- change (attr: 'foo', how: 'set')
- change (attr: 'list.1' how: 'add')
- change (attr: 'list', how: 'remove')
- foo (newVal: 'bar' oldVal: undefined)
- foo (newVal: 'baz' oldVal: 'bar')
- list (newVal: undefined, oldVal [1,2])
- I think I might've missed one or two

The answer might be "yes, of course" but - do we really need to fire all of those events when we are batching? Seems like many of them just aren't necessary.

**Comment by justinbmeyer** [comment]
@imjoshdean In general, it's rare that something like:

```
map.attr('foo', 'bar');
map.attr('foo', 'baz');
```

Happens within a batch.  If this is the case, then the logic to reduce the number of "replaced" events isn't worth it.

Also, while something like debounce would be useful for a single event handler, this pattern breaks down if you need to respond when `length` changes or some other event.  In this case you need to check the batch number.  Reducing the number of events would not help.

In general, using events to listen to view model changes should be avoided.  


@akagomez If there are multiple calls to debounce on the same events object, you'd need to make sure each one has its own place to store it's batch num.

Something like this would have been useful for a long time.  But now with diffing, and the upcoming can-derive, it slowly has less utility.

However, there are a few parts of CanJS's core that could use this ... not so much on a prototype, but using closures.

**Comment by akagomez** [comment]
@justinbmeyer Just to be clear, are you suggesting that we implement ONLY the closure variety as a part of 2.4.0. Or BOTH, despite the fact that the prototype variety is less useful than it would had been in the past?

**Comment by justinbmeyer** [comment]
I'd implement the versions that are already sudo-implemented in CanJS's core.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-event/issues/3
