### ISSUE TITLE
Allow specifying a viewModel for autorender

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#1721]
can/view/autorender creates a viewModel for rendering.  We need to be able to specify a module to use as the viewModel.  

```html
<script type="text/stache" can-autorender view-model="my/custom/map">
</script>
```

**Comment by nlundquist** [comment]
this isn't needed considering can-import can be used to amend a viewModel during rendering. In this example we import the module 'src/demo-data' as 'data'.
```
<can-import from="src/demo-data" {^value}='data'/>
{{#each data.default}}
     {{message}
{{/each}}
```
