### ISSUE TITLE
computeData.root is undefined (2.3.0-pre.1)

### ISSUE THREAD

**Issue by ccummings** [canjs/canjs#1728]
Discovered a case where the new scopeReader in compute_data throws an error because computeData.root and computeData.setRoot are undefined.

To reproduce you need to pass a property to a component (twoway bound) whose value is undefined. Then update that property in the component.

JSBin: http://jsbin.com/molatudupu/1/edit?html,js,output 
_click the rendered text to trigger the error_

This [commit](https://github.com/bitovi/canjs/commit/23de6705dd7c97c5608ddb8904541e601a62dd9d) added the breaking change.

And the error is thrown [here](https://github.com/bitovi/canjs/blob/master/view/scope/compute_data.js#L43)

I tried this on the latest from minor and the same issue happens. In 2.2.6 this worked.

**Comment by justinbmeyer** [comment]
Fixed now: http://jsbin.com/hebewe/edit?html,js,output
