### ISSUE TITLE
Wildcard serialize doesn't apply to getter properties

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#1730]
http://jsbin.com/cefaza/3/edit?js,console

Getter properties don't get serialized when `serialize` is set ike this:

```
'*': {
  serialize: true
}
```

**Comment by daffl** [comment]
Does it work if you serialize it explicitly?

**Comment by akagomez** [comment]
Yup. That's shown in the demo too.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-map-define/issues/4
