### ISSUE TITLE
removeAttr doesn't trigger "remove" event on can.Map

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#1731]
No `remove` event is fired when calling `removeAttr`.

```
var m = new can.Map({
  foo: 'bar'
});

m.bind('remove', function () {
  console.log('remove');
});

m.removeAttr('foo');
```

Demo: http://jsbin.com/zevopa/1/edit?js,console

I think the problem is here in `map.js`:

```
// Trigger a change event.
_triggerChange: function (attr, how, newVal, oldVal) {
    // so this change can bubble ... a bubbling change triggers the
    // _changes trigger
    if(bubble.isBubbling(this, "change")) {
        can.batch.trigger(this, {
            type: "change",
            target: this
        }, [attr, how, newVal, oldVal]);
    } else {
        can.batch.trigger(this, attr, [newVal, oldVal]); // <-- The event is assumed to be a set
    }

    if(how === "remove" || how === "add") {
        can.batch.trigger(this, {
            type: "__keys", // <-- Not really helpful since it doesn't include "how"
            target: this
        });
    }
},
```
https://github.com/bitovi/canjs/blob/3cd143018d5592a2550e435f5a33f2b2ab6a7b09/map/map.js#L341

**Comment by akagomez** [comment]
I asked in the "How can.Map works" Hangout why a `remove` event isn't triggered. Here's a link: https://youtu.be/MPZeaDY5mTk?t=33m11s

@justinbmeyer mentioned that we intentionally don't fire `add` or `remove` events on `can.Map`'s because there hasn't been a reason to. He also mentioned that you can bind to `__keys`, but you won't get the key that was removed.

**Comment by akagomez** [comment]
Interesting. `map.attr('key', undefined) === map.removeAttr('key')`. Check out this demo: http://jsbin.com/pabeco/2/edit?js,console

**Comment by akagomez** [comment]
So here's what I've learned...

1) A `can.Map`'s will exclude a key if the value is `undefined`. That wasn't expected. Compare:

```
var m = new can.Map({ a: 1, b: undefined });
console.log(m.attr()); //-> Object {a: 1}

var o = { a: 1, b: 2 }
console.log(o); //-> Object {a: 1, b: 2}
```

2) Binding to `change` is the only way to know if a "key" is added or removed from a map. No matter if it was removed for it's "value" being set to `undefined` or  `removeAttr` being called.

**Comment by pYr0x** [comment]
@akagomez i think events like remove and add have to trigger. there is no reasen why not. maybe you can make a pull request?

**Comment by justinbmeyer** [comment]
@akagomez `add`, `remove` and `set` events are not triggered on a `can.Map`.  This is because they are rarely needed and would add performance overhead.  

Is there a reason they are needed?  Closing for now.
