### ISSUE TITLE
Map define does not work if pushing a existing Map into it

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#1732]
i simplify the problem 
here is the JSBin demo:

http://jsbin.com/xopequfexa/9/

the problem also comes up when i tried to use the async call with can.Model

```
var list = can.Day.List();
Days.findAll({tour: 1}).then(function(days){
    can.each(days, function(day, index){
        var day = new Day(day.serialize());
        list.push(day);
    });
    setAttrValue(list);
});

```

**Comment by daffl** [comment]
That is true. Existing maps should be serialized and converted into a new one (if they are of different type) but they are currently not (much like `new Map(othermap)`). Unfortunately we can't add this until 3.0 since it would break the current API there is however a simple workaround of monkey patching `can.List.prototype.push` if that is that is the behaviour your applications expects:

```js
var old = can.List.prototype.push;
can.List.prototype.push = function() {
  var args = can.toArray(arguments);
  var item = args[0];
  
  if(item instanceof can.Map && !(item.instanceof this.constructor.Map)) {
    args[0] = item.serialize();
  }
  
  return old.apply(this, args);
}
```

**Comment by pYr0x** [comment]
why would this break the current API? 
if we serialize the map and push them into the list, a new map will be created. i think thats not good.

example:
* we define a Model 
* we make a aync call with findAll(). 
* we receipt a can.Model.List from parseModels http://canjs.com/docs/can.Model.parseModels.html
* and now we have to serialize this created List.Map and create a new one... there are too many creations of Maps

here an example that doesnt work ..  can.Model.List.Map has no effect
http://jsbin.com/soyorayiku/2/edit

**Comment by daffl** [comment]
Am I understanding it right that what you want to do is use a `Model.findAll` but receive an instance of a different list?

**Comment by pYr0x** [comment]
the main problem was, that in canjs 2.2.6 the define plugin was not working with can.Model.
In canjs 2.3 pre the define plugin is working also in can.Model as you can see here
https://github.com/canjs/place-my-order/blob/master/app/models/order.js

with not working define plugin in can.Model i thought i can put a custom can.Map into can.Model.List.Map #1745 describt at http://canjs.com/docs/can.List.Map.html but this was not working too.

the third way was to create a new list and add the custom Map into it. after using findAll(), i wanted to push the received a map into this new list. But here the next problem comes up (this issue #1732). Map define does not work if pushing a existing Map into it (see the example below)

after the define plugin is working on can.Model (canjs 2.3 pre) this whole problem collapse.

it would be nice if this issue will be solved. so we havent to serialize a map and then create a new one. i can also write a breaking test.

i would be also nice if that issue #1745 will be solved, so we have the ability to use a different List.Map for findAll() but findOne() refrence to can.Model itself.

**Comment by daffl** [comment]
I will look into the issue but do you have an example for the define plugin not working on can.Model in 2.2.6? can.Model just extends can.Map and I remember using the define plugin with can.Model in that version.

**Comment by pYr0x** [comment]
this test is breaking https://github.com/pYr0x/canjs/commit/33cb6f0412eaa5abc275ba2ae53e6c6a48c8a9d5 on my local machine at http://localhost:8000/model/test.html

**Comment by daffl** [comment]
Are you running the `model/test.html` or `test/jquery.html` test page? `model/model_test.js` does not include the define plugin so the tests would probably break when running `model/test.html`.

**Comment by pYr0x** [comment]
@daffl @justinbmeyer  any news about this issue? 
milestone was 2.3.0 ?

**Comment by justinbmeyer** [comment]
Closing for https://github.com/canjs/can-list/issues/4.  @pYr0x please confirm it's the same issue.  Thanks!
