### ISSUE TITLE
Memory leak in aync compute

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#1743]
using isResolved() in a define getter-function cause a memory leak.
example:
http://jsbin.com/remenaqise/6/edit?js,console,output

**Comment by justinbmeyer** [comment]
Anyway you can simplify this example?  I can take a look tomorrow.

**Comment by justinbmeyer** [comment]
Also, why do you say a memory leak?  I'm not easily able to profile that code b/c it's in an iframe, but it seems more like a problem with a compute binding to "itself", not a memory leak.

**Comment by pYr0x** [comment]
hi justin,

whats happening in my code example:
1. disable auto-run js
2. clear console output
3. run js
4. now the alert('memory leak'); will pop up and never end. and the counter "j" will increase.

maybe the title "memory leak" is not correct, there is an infinity loop witch raise an error
i hope

**Comment by justinbmeyer** [comment]
Thanks. Can you reduce what it takes to see the problem? Models are probably not necessary.

**Comment by justinbmeyer** [comment]
@pYr0x anyway you can check this and see if it's still a problem?
