### ISSUE TITLE
Better promise detection

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#1747]
A browser's Promise will fail can.isPromise.  I think we should change the test to something like:

```
can.isPromise = function(obj){
  return obj && (
     ( window.Promise && (obj instanceof Promise) ) ||
    ( can.isFunction(obj.then) && can.isFunction( obj["catch"] || obj.fail )
  )
}
```

**Comment by alexisabril** [comment]
Should can.isDeferred and can.isPromise be the same function in this case? Currently can.isDeferred looks for jQuery-esque deferred methods, which we use in a couple places: https://github.com/bitovi/canjs/blob/master/list/promise/promise.js#L15

**Comment by alexisabril** [comment]
Note, I retracted my prior PR when I realized the above. The current state of that branch has two separate functions: can.isDeferred and can.isPromise.

**Comment by justinbmeyer** [comment]
@alexisabril we should deprecate can.isDeferred and use can.isPromise everywhere.  They should be the same function.

**Comment by justinbmeyer** [comment]
@daffl we should release this in 2.3.  I didn't  notice that it was pushed to 2.4.  Why is that?  The old version remains so we aren't breaking any APIs.
