### ISSUE TITLE
Passing can.Map to can.List with a static Map property does not convert properly

### ISSUE THREAD

**Issue by ccummings** [canjs/canjs#1758]
If I define a List with a custom Map type and add a plain can.Map  instance to it, the resulting Obervable in the List remains a can.Map (not an instance of the the custom Map Type). 

Here's an example:
```js
var MyMap = can.Map.extend({});

var MyList = can.List.extend({
  Map: MyMap
}, {});

var map = new MyList([new can.Map({})]);
map.push(new can.Map({}));
map.push({});

console.log(map[0] instanceof MyMap);
console.log(map[1] instanceof MyMap);
console.log(map[2] instanceof MyMap);
```

Working fiddle of the same: http://jsbin.com/wukuduruho/edit?html,js,output

The problem is this [condition](https://github.com/bitovi/canjs/blob/master/map/map.js#L463) in can.Map

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-list/issues/4
