### ISSUE TITLE
Cannot use custom event params in can-EVENT callbacks with explicit arguments

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#1760]
The [trigger](http://api.jquery.com/trigger/#trigger-event-extraParameters) method in jQuery allows passing an additional argument when triggering events, which is particularly useful when firing custom events. These are passed to [can-EVENT](http://canjs.com/docs/can.view.bindings.can-EVENT.html) handlers in simple examples like this:

```html
<input type="text" id="test" can-foobar="{doStuff}">
```

```js
$('#test').trigger('foobar', data);

// view model
doStuff: function(context, element, event, data) {}
```

This works because the whole argument list is passed to the handler:
https://github.com/bitovi/canjs/blob/master/view/bindings/bindings.js#L257

However, if you use the newer syntax to specify what you want to send to your handler...

```html
<input type="text" id="test" can-foobar="{doStuff @event arg2}">
```

Only the specified arguments are passed and the additional param is dropped. One solution would be to add a new ```@``` key (e.g., ```@data```) to the context like ```@element``` and ```@event```, which looks like it would be pretty easy to add [here](https://github.com/bitovi/canjs/blob/master/view/bindings/bindings.js#L213).

**Comment by justinbmeyer** [comment]
@dylanrtt how would multiple args be passed?  I agree that we should fix this.  Thanks for pointing it out.

**Comment by dylanrtt** [comment]
You can only pass one extra argument to `trigger()` and the rest are dropped. The jQuery docs recommend passing an array.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-stache-bindings/issues/9
