### ISSUE TITLE
How create gmail like common control bar in Canjs?

### ISSUE THREAD

**Issue by wishabhilash** [canjs/canjs#1764]
For example we make a Gmail clone in canjs. Consider each item in the sidebar being rendered with a component of its own. Now I want a single control bar just like gmail to control the activities inside the components.

How should I approach it???

At present am looking at the change event of localStorage, is there a better solution to this???

There is also a stackoverflow question by me on this:
http://stackoverflow.com/questions/31136080/how-create-gmail-like-common-control-bar-in-canjs

**Comment by justinbmeyer** [comment]
@wishabhilash This type of question is best on the forums: http://forums.donejs.com/c/canjs 

I'm not sure what you are planning on doing with `localStorage`, but it doesn't sound like the right solution to me.
