### ISSUE TITLE
boolean property in model not respected by selects

### ISSUE THREAD

**Issue by rmannibucau** [canjs/canjs#1765]
Hi

is there a built it way to support a property of type boolean with canjs? 

My issue is the select i use force it to be a string and converter/define/serialize definition to convert it back to a boolean are ignored.

**Comment by marshallswain** [comment]
Can you post a jsbin or fiddle that demonstrates what's going on?

**Comment by rmannibucau** [comment]
Well I'm not yet familiar enough to be able to import a http js in these tools but here a starting point:

    <html>
    <head>
    <script src="https://code.jquery.com/jquery-2.1.4.js"></script>
    <script src="http://canjs.com/release/2.2.6/can.jquery.js"></script>
    </head>
    <body>
    <div id="out"></div>

    <script type="text/mustache" id="flag-view">
        <select can-value="model.flag">
            <option>Select something...</option>
            <option value='true'>True</option>
            <option value='false'>False</option>
        </select>
        <button can-click="{ doLog model }">Log</button>
    </script>
    <script>
    var Model = can.Map.extend({
        define : {
            flag : { type: 'boolean', set: function (val) {
                return val === true || val === 'true';
            }}
        }
    }, {});
    var model = new Model({ flag: true });
    $("#out").html(can.view("flag-view", new can.Map({model:model, doLog: function (m) {
    console.log(m.serialize());
    }})));
    </script>
    </body>
    </html>

So you have a basic select with a simple model having a single field "flag" which should stay a boolean. In this snippet I used define (which is ignored so maybe I did something wrong) but using old syntax (convert/attributes) leads to the same.

My goal is to keep flag type to boolean (this way the sent json is always valid for the server).

To test it click on "Log" before changing any value, you get a correct json then change it to false or true and you'll get a string instead of a boolean.

Hope it helps

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-stache/issues/17

This would be solved like:


```
<select {($value)}="booleanToString(model.flag)">
        <option>Select something...</option>
        <option value='true'>True</option>
        <option value='false'>False</option>
</select>
```

```
can.stache.registerConverter("numberToString",{
  get: function(source){
    return  source() ?  "true" : ( source() === false ? "false" : "");   
  },
  set: function(newVal, source){
    source(newVal === "" ? null : newVal === "true"); 
  }
});
```
