### ISSUE TITLE
this.constructor._bubble is null or is not an object in IE8

### ISSUE THREAD

**Issue by kostix** [canjs/canjs#1766]
CanJS 2.2.6 with jQuery 1.11.3.

While trying to implement a simple radio-group-like control in CanJS, I've encountered an error which triggers itself in IE8 in both of its "IE8 modes" ("true" and "compat" -- I have Russian locale here in Windows so can't tell their canonical names):

    Message: 'this.constructor._bubble' -  is null or is not an object
    Line: 2181
    Character: 17
    Code: 0

(That's my translation from Russian but I think it's quite precise).

This error is detected in can.jquery.js (which I obtained from the 2.2.6 release archive).

I've prepared a minimal [jsfiddle](https://jsfiddle.net/xmna7rkf/) with my code but while it works OK in recent FF and Chrome, IE8 fails on it quite before even attempting to render the jsfiddle's interface.
(Here, I'm using PHP's built-in web server to serve my app while I'm playing, hence if you so wish I can make a tarball out of it and make it available somehow.)

**Comment by kostix** [comment]
Tried including the latest `html5shiv` before loading `jquery.js` and `can.jquery.js` -- it made no difference.

**Comment by kostix** [comment]
OK, here's a [jsbin](http://output.jsbin.com/yirexowudu/) whick works in modern FF and Chrome, and fails in IE8 with the error I have reported (actually, it first fails on something coming from `jsbin` but it's easy to click that error away when in the developer mode).

**Comment by justinbmeyer** [comment]
closing ... if this is still an issue in can-map, I'll re-open there (or someone else can).
