### ISSUE TITLE
Stache block and inline nesting waltz

### ISSUE THREAD

**Issue by Macrofig** [canjs/canjs#1775]
In attempting to use input groups with Bootstrap, I ran into a bug with Stache when a block level element is inside an inline element.

If you want to do something like:

```html
<div class="input-group">
	<input class="form-control" id="test" type="text" can-value="myVal">
	<span class="input-group-btn">
		<button type="button" class="btn btn-default" can-click="validateField">Validate</button>
	</span>
</div>
```

Stache will render like: 
```html
<div class="input-group">
	<input class="form-control" id="test" type="text" can-value="myVal">
	<span class="input-group-btn"></span>
	<button type="button" class="btn btn-default" can-click="validateField">Validate</button>
</div>
```
Jsbin for visualness: http://jsbin.com/gurezu/1/edit?html,js,output

My thought is that Stache shouldn't really care about HTML spec and should just render elements even if it's not correct. Let the browser handle that part.  The other issue is that there are many different rules and exceptions to nesting and it's a lot of work to keep up with the rules... especially if they change.

I have a fix that works, it removes the closing of inline elements checker: https://github.com/Macrofig/canjs/blob/master/view/parser/parser.js#L97

Really interested to hear thoughts on this as I can see an opinionated Stache would be helpful to some.

**Comment by justinbmeyer** [comment]
So, I believe this is important for HTML like:

```
<li>First
<li>Second
```

This way, you don't have to close all your `<li>`s.

Seems like this code got pushed and might have found its way into 2.2.7.  Hopefully it won't cause weird problems for anyone.

**Comment by Macrofig** [comment]
Whew. Freaked out for a sec. Nope, it still works like you said: https://github.com/bitovi/canjs/blob/master/view/parser/parser.js#L97

To your point, though, if I were to hand write HTML like
```html
<li>First
<li>Second
```
the browser would attempt to self close them on it's own (sometimes?). But even if it doesn't, I kinda feel like Stache should just render what I give it, as broken as my template could be.

If the plan for Stache is to continue with auto-closing tags then it will need to process more than just inline vs block. There should be checks for all the [content categories](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Flow_content) and their exceptions. That just sounds like a lot of maintenance to me, though. I mean, it would be cool but a lot of work.

The other option is for Stache to render what I give it and let the browser handle the broken parts.

**Comment by justinbmeyer** [comment]
Weird. What the heck was I looking at?

**Comment by justinbmeyer** [comment]
HTML like:

```
<li>First
<li>Second
```

is valid html.  We should handle it appropriately.

**Comment by matthewp** [comment]
Why is this a 3.0.0 issue, would it be backwards incompatible?

**Comment by justinbmeyer** [comment]
it would.  Currently, inline elements like

```
<span>First
<span>Second
```

Gets turned into:

```
<span>First</span>
<span>Second</span>
```

This would probably change it to something more like:

```
<span>First
<span>Second</span></span>
```

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-view-parser/issues/3
