### ISSUE TITLE
Unbinding from non-bound compute throws error

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#1779]
No error:

```
var c = can.compute(32);
c.bind('change', can.noop);
c.unbind();
```

Error:

```
var c = can.compute(32);
c.unbind(); //-> "TypeError: Cannot read property 'undefined' of undefined
                 at can.unbindAndTeardown [as unbind] 
```

http://jsbin.com/nixatopuye/edit?js,console,output

**Comment by akagomez** [comment]
Correction: Calling `.unbind()` without any arguments does nothing. You need to at the very least pass a type (`.unbind([type])`). Still, doing so when no bindings are defined causes and error and the PR referenced here addresses that issue.

**Comment by justinbmeyer** [comment]
Reopening b/c I don't think this is a bug.  I think:

```js
var c = can.compute(32);
c.bind('change', can.noop);
c.unbind();
```

is actually more of a bug.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-compute/issues/8
