### ISSUE TITLE
Use of internal jQuery APIs that will be removed in jQuery 3.0

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#1786]
CanJS is using the semi-private `jQuery.buildFragment` method:
https://github.com/bitovi/canjs/blob/master/util/jquery/jquery.js#L46

In JQuery 3.0 it will be made *completely* private and no longer be reachable from the jQuery root object:
http://blog.jquery.com/2015/07/13/jquery-3-0-and-jquery-compat-3-0-alpha-versions-released/

 If you want to stick with a jQuery API, you could use [`jQuery.parseHTML`](http://api.jquery.com/jQuery.parseHTML/) but that returns an array of top-level DOM nodes and not a full document fragment.

For CanJS' purposes of walking the subtree and attaching live-binding handlers, an array of top-level nodes would work equally well. Actually, imho it might work a lot nicer if the `can.view` callback - instead of a raw document fragment - would return an element set wrapped via the DOM library on which CanJS is resting.

**Comment by justinbmeyer** [comment]
Thanks for letting us know this.

An array of top-level nodes can't be passed to appendChild so we should still return a fragment.

**Comment by justinbmeyer** [comment]
We can use jQuery.parseHTML.  The domManip being made private is more of a problem.

**Comment by justinbmeyer** [comment]
Closing for the changes in 3.0.
