### ISSUE TITLE
CanJS breaks Mootools More Drag and Drop code

### ISSUE THREAD

**Issue by tracer99** [canjs/canjs#1792]
Created a project to show the problem
https://github.com/tracer99/stealbreaksdrag
I originally thought it was upgrading steal, but it was a CanJS problem.
If you checkout the above and run stealcan.html then drag the example box, you can't release the box.

The offending code is in can/util/mootools/mootools.js

Specifically
var idOf = Slick.uidOf;
    Slick.uidOf = function (node) {
        if (node.nodeType === 1 || node === window || node.document === document) {
            return idOf(node);
        } else {
            return Math.random();
        }
    };
 
We have removed this code as our app doesn't support old versions of IE. I don't know what the correct solution would be though.

**Comment by justinbmeyer** [comment]
Why does it break mootools?  I'd happily accept a pull request.  But 3rd party mootools library support isn't priority for us right now.  If you are interested in solving, let me know and I'll reopen.

**Comment by tracer99** [comment]
Mootools more is not a 3rd party library. It's the UI portion of Mootools (like Jquery UI is to Jquery). It's just not included in the core because it's huge if you want it all. 

As for why it's happening, I spent a day on this and didn't get far in figuring out why it was happening. The symptom is that event binding was not being properly unbound.
