### ISSUE TITLE
CanJS doesn't intuitively load in NodeJS

### ISSUE THREAD

**Issue by Bajix** [canjs/canjs#1824]
In the latest release, 2.2.7, it's stated that CanJS was updated with the ability to load in NodeJS, however it's not obvious how to load it in NodeJS, nor are there any examples or documentation.

Simply installing can@2.2.7 and using require within Node REPL results in:
```
ReferenceError: steal is not defined
```

Assuming that CanJS can in fact be loaded into NodeJS, however indirectly via a loader, it would be really great to see a working example of how to do this, as well as updated documentation

**Comment by justinbmeyer** [comment]
It can load with steal in node, or browserify using require. 

It does not load in node with a normal require call without having a DOM present in node.

If you look in dist/cjs you'll find the commonjs-ified distributable.

**Comment by Bajix** [comment]
I've had issues loading it with StealJS as well as when loading the CommonJS distributable. For what it's worth, I'm also having tests fail on projects that use CanJS, such as can-ssr.

Just looking at how can-ssr loads, there's a lot of configuration going into loading with StealJS, so it would be good to have a tutorial for doing this regardless.

**Comment by justinbmeyer** [comment]
We will. You can check out donejs.com for right now. All of this is not released yet. I've also got a github.com/bitovi/bitballs app using this stuff.

**Comment by matthewp** [comment]
We can't really make loading canjs in Node intuitive unless we changed the folder structure.  Ideally it would be nice if you could do:

```js
require("can/util/vdom/vdom");
var can = require("can");
```

This won't work though because the CommonJS can/util/vdom is located at `dist/cjs/can/util/vdom/vdom` and Node doesn't provide a way to remap module locations.

**Comment by Bajix** [comment]
Is there any reason why the main entry point can't be a wrapper to load in CanJS into NodeJS?

**Comment by justinbmeyer** [comment]
CanJS is many things.  What part of CanJS?  Core, every module, those that work w/o a DOM?

What end goal are you trying to accomplish?

**Comment by Bajix** [comment]
Well, there are several use cases I envision here, mainly around doing server side plugins. For example, [broccoli-can-stache](https://www.npmjs.com/package/broccoli-can-stache) would benefit from being able to use can's built in template parsing. [can-ssr](https://github.com/canjs/can-ssr) would benefit from being able to load can without all of the ceremony.

The problem, as it stands now, is that a lot of aspects of CanJS, and more specifically DoneJS, are built around a one stop solution for everything, and encompass a seriously large number of tools that would otherwise be independently valuable in their own right, and more palatable to include in a standalone fashion. This limits the ability for outside developers to build their own tools for new purposes in mind, or to incrementally shift over.

For example, StealJS on Node is a very recent thing, and there are a lot of projects that aren't going to abandon their existing build system or otherwise don't feel comfortable making the transition for one reason or another, but would appreciate being able to use optimized templates, or alternatively to use optimized AMD bundling with RequireJS. Say for example you have a Grunt/Broccoli build pipeline, and are using SASS as a CSS pre-processor; you're probably not going to want to use StealJS because it only supports LESS.

**Comment by justinbmeyer** [comment]
So, our focus right now is on making everything work with DoneJS. DoneJS is designed to be a one stop solution because making things work with everything is super difficult. It's been painful enough making CanJS work in browserify/amd/systemjs. To make CanJS work in browserify, I had to submit a change to browserify. As node lacks some form of mapping or patching construct, something very different from the others will need to be done. CanJS needs a DOM. We can ensure one loads with stealjs. 

Once that's done, making all of these auxiliary projects work too will take time. 

I'm not opposed to it, but someone else is going to have to do the heavy lifting. 

If you want to meet to go over how this can be done, I'm happy to show you. Thanks!

**Comment by justinbmeyer** [comment]
Closing.  If someone wants to pair on this, let me know and I'll help make it happen.  But right now, it's not priority to make happen.
