### ISSUE TITLE
Warning in chrome with (event) attributes

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#1831]
Related to commit: https://github.com/bitovi/canjs/commit/289e97b8ad5a4b0eb1e7ff8632833c01f8a13ce1

chrome is giving a warning:

> Attr child nodes are deprecated and will be removed in M45, around August 2015. Please use 'Attr.value' instead.

Also, the try / catch should be removed whatever technique we use.

**Comment by justinbmeyer** [comment]
info: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/tW6Lr5nA1pY/BOedStgP2pEJ

**Comment by matthewp** [comment]
You get the warning because `cloneNode` is being removed from Attributes.  [Here's](https://github.com/canjs/dom-patch/blob/master/src/setattribute.js#L9) how I implemented in worker rendering without cloning and without using a try/catch.

**Comment by justinbmeyer** [comment]
Implemented in 2.3 this way.
