### ISSUE TITLE
can-value binding to a currently undefined value shows the first option being selected.

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#1834]
If I have a map like `map = new can.Map()`.

And a template like:

```
<select can-value="{map.value}">
  <option value="SOMETHING">SOMETHING</option>
</select>
```

No value should show up as being selected.

**Comment by dylanrtt** [comment]
This kinda makes me nervous... I don't think placing ```can-value``` on an element should cause it to update the view model upon insertion. Two-way binding already gets hate for the confusing side effects it can cause developers, and this would add an additional layer of complexity.

Some modules like ```bit-panel``` update the parent view model of a ```bit-tab``` when inserted but that is an example of two components specifically designed to work together, whereas ```can-value``` is generic so it's probably better to avoid this behavior.

The top-down approach still works so the only advantage this provides is that you don't have to define a default in the view model which I don't think is a good trade-off.

**Comment by justinbmeyer** [comment]
@dylanrtt Thanks for your input!

It's confusing in my opinion if we don't do this. It took me a few minutes to understand why my model attribute wasn't set when I did something like:

```
<select can-value="{game.round}">
  <select value="1">1</select>
  <select value="2">2</select>
  <select value="3">3</select>
  <select value="4">4</select>
</select>
```

Sometimes, because I wasn't selecting a value, `game.round` would be `undefined`.  But when I did select 2, 3, 4, suddenly my game had a round. 

If you looked at the form I was submitting, it certainly looked like the game should be round 1 to the user.

Two way binding does get hate for confusing side effects, however, I think the 2 way-ness of 2-way binding is something we should maintain.  If the value of the <select> is 1, so should `game.round`.  This way it's actually doing 2-way binding.

**Comment by justinbmeyer** [comment]
Btw, you can see my form here: https://bitballs.herokuapp.com/#!&tournamentId=1

I think that form, when submitted, should have round = 1 and court = 1.

**Comment by dylanrtt** [comment]
If the property is undefined, the ```<select>``` should probably not display the first option as being selected. As far as I can tell, that's how it worked before so you might have accidentally changed it recently when fixing live binding with dynamic select menus (#1762).

Here it is in 2.2.6 with no displayed selected value:
http://jsbin.com/mogocoteje/edit?html,js,output

If the blank option is not desirable then the developer should define a default and problem solved.

**Comment by justinbmeyer** [comment]
Ah. The first option should not be displayed. Thanks!

**Comment by justinbmeyer** [comment]
Updated the title and issue description to reflect what we should do (which is the 2.2.6 behavior).

**Comment by pYr0x** [comment]
do not get the problem...

so i created a jsbin
http://jsbin.com/xehapumixe/2/edit?html,js,console,output

@dylanrtt  can you explain the problem at the example?

btw:
there is a difference behaviour on firefox and chrome
* in chrome the select-element is blank at the first time
* in firefox the select-element shows the first option-element

**Comment by justinbmeyer** [comment]
@pYr0x thanks for pointing that out.  I will fix this.

**Comment by justinbmeyer** [comment]
I'm going to close this and move into #2027.  In short, I'll try to make `can-value` work the way it used to (not updating the scope). 

However, in 2.3, using `{(value)}="key"` will update key.  

@dylanrtt I know you dislike this, and for reasonable reasons.  Perhaps we can come up with another syntax that avoids this?  Created an issue for discussing it here: https://github.com/canjs/canjs/issues/2050
