### ISSUE TITLE
Supporting timeouts (and timeout cleanup) in can.Construct

### ISSUE THREAD

**Issue by moschel** [canjs/canjs#184]
We need a way to safely add timeout type methods to can.Construct, for things like debounce, throttle, and defer.  

## Problem

The problem with can/util/function/function.js methods like can.debounce is there is a single copy on the prototype shared across instances, so timeouts could interfere with each other.

Also, if a construct instance is destroyed while a timeout hasn't fired yet, when the timeout fires it'll run code on a cleaned up instance, which will often create errors.

## Solutions

One solution is to make a can.Construct plugin that lets you create timeouts, add them to a .timeouts property on the construct instance (an array of timeouts), and in destroy, can.Construct would go through that array and clearTimeout on each of them.

**Comment by justinbmeyer** [comment]
I don't think this is much of a problem now.  Live-binding tears itself down w/ the component, so it's rare that this would be a problem.  Closing.
