### ISSUE TITLE
Proposal: Setup event delegation with can.view.bindings

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#1852]
Maybe it's a stupid idea, but I'm curious if something like this could be valuable: 

```
var list = can.List([0, 1, 2]);

<ul can-click=".list-item {increment}">
  {{#each list}}
    <li class="list-item">{{.}}</li>
  {{/each}}
</ul>
```

Ideally the `increment` method would have the same call signature as if I had added the `can-click` binding directly to each `.list-item` element.

**Comment by justinbmeyer** [comment]
How would we be able to get the right context/scope value?

The only way I think you could do it would be to add it to each <li>. If you're doing that, you might as well be binding an event handler anyway.

**Comment by akagomez** [comment]
Okay, that part was unrealistic I'll admit. But the `click=".list-item {increment}"` bit is doable, yeah?

**Comment by justinbmeyer** [comment]
Yeah, but I wouldn't use that syntax.

**Comment by justinbmeyer** [comment]
Well, maybe ... it's a bit strange.

**Comment by justinbmeyer** [comment]
I'm closing unless there's a lot of other support.  I think `events` object is the right tool here if this kinda performance is needed.
