### ISSUE TITLE
can-import can-tag fails silently when tag does not exist

### ISSUE THREAD

**Issue by julia-allyce** [canjs/canjs#1859]
```
<can-import from="app/component/" can-tag="app-loading">
          <app-component></app-component>
</can-import>
````
If app-loading is not already imported, can-import will fail without throwing an error. It never renders app-component.

**Comment by matthewp** [comment]
I'm not sure if a warning would be possible, you don't have to use can-tag (you could use a `{{#isResolved}}` helper instead) so I don't think we could know when to warn.  But we definitely need to document this so that it's known that can-import is asynchronous.

**Comment by alexisabril** [comment]
Re-labeling this as a bug. Unconfirmed, however the callback inside of can-import should throw an error if "app-loading" is not loaded yet.

**Comment by justinbmeyer** [comment]
The DOM is supposed to "never" throw errors.

I think a warning is more appropriate.

**Comment by alexisabril** [comment]
Apologies for the confusion: https://github.com/bitovi/canjs/blob/minor/view/import/import.js#L33

"Should throw an error" is only in reference to "callback" on that line, which is expected to be undefined in this scenario.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-view-import/issues/2
