### ISSUE TITLE
can/view/href depends on can.route but does not import it

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#1861]
This is in minor

**Comment by matthewp** [comment]
Why was this closed?  It's not fixed: https://github.com/bitovi/canjs/blob/minor/view/href/href.js

**Comment by matthewp** [comment]
Oh, maybe because I said "this is in minor" you thought I meant it was fixed in minor, I meant that the problem is in minor.

**Comment by James0x57** [comment]
Oh! Sorry! It also it has the label "fixed in branch", which also might have been added by misread since I'm just noticing it wasn't added by you.

Is the fix just adding can/route to the steal list? I can take care of it real quick

**Comment by matthewp** [comment]
@James0x57 yep, that's all that's needed.

**Comment by julia-allyce** [comment]
The PR for this issue was never merged. Is this still relevant? cc: @James0x57

**Comment by justinbmeyer** [comment]
Closing as can-href is deprecated.  I'll include a fix if someone submits a fix w/ a test.
