### ISSUE TITLE
Add support for can.event.removeAllEvents

### ISSUE THREAD

**Issue by isadovskiy** [canjs/canjs#1870]
Looks like right now there is no ability to unsubscribe from all events, bound to an object.

So makes sense to add can.event.removeAllEvents() support or just allow can.event.removeEvent() without arguments to unsubscribe from all events, attached to an object.

**Comment by justinbmeyer** [comment]
If we were to add this, we would follow jQuery's convention and have calling `unbind()` with no arguments unbind every event handler.

**Comment by isadovskiy** [comment]
Per documentation, unbind() is just an alias of removeEvent() (http://canjs.com/docs/can.event.unbind.html). Totally makes sense to keep everything consistent and to not add new methods but use existed one.

**Comment by justinbmeyer** [comment]
@akagomez Did you add this functionality already?  I felt like we talked about it.

**Comment by akagomez** [comment]
No, this is new to me.

Chris

**Comment by justinbmeyer** [comment]
@akagomez you didn't work on making `.unbind()` unbind all event handlers?  I thought we looked at this and it was already working.

**Comment by akagomez** [comment]
I made `.unbind()` not error: https://github.com/bitovi/canjs/pull/1780#issuecomment-121241086

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-event/issues/4
