### ISSUE TITLE
can/all_tests.js includes individual can/util tests instead of the top level can/util test file (can/util/test/tests_test.js)

### ISSUE THREAD

**Issue by mjstahl** [canjs/canjs#1873]
`can/util/test/tests.js` does not include the updated `can/util` tests so adding your test to this file will not execute any tests except the new ones added.

`can/util/test/tests_test.js` includes all of the current `can/util` tests.  This file along with the `test.html` should be moved to `can/util` directory.  The individual `can/util/*/*_test.js` files should be removed from `can/all_tests.js`.

`can/util/test/tests.js` should also be removed, and `can/util/test/tests_test.js` should be renamed to `can/util/tests.js`

**Comment by justinbmeyer** [comment]
totally different now in 3.0.
