### ISSUE TITLE
can.events section to house can.batch, etc

### ISSUE THREAD

**Issue by alexisabril** [canjs/canjs#1911]
A potential new section, aside from can.util, to group event related documentation. Reference #778

**Comment by justinbmeyer** [comment]
Can you elaborate on what this means?

**Comment by alexisabril** [comment]
Just noting the reference issue #778 so we don't lose tracking of the comment below.

"It's under utils b/c that's where it's code is found. The same argument could be made for putting it under can.compute.  We should link to it from other pages, but it should stay in util.

Eventually, we should have an "can.events" that could house it."

**Comment by justinbmeyer** [comment]
https://github.com/canjs/can-event will now house it.
