### ISSUE TITLE
Asynchronous virtual properties cause extra recomputes

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#1915]
In the following example, I create an async virtual `foo` property, and a `bar` property that depends on it. If you bind to `bar`, it computes once when `foo` is `undefined`, and then recomputes twice after `foo` is set (3 total times). It should only recompute/log one time after `foo` is set (2 total times).

```js
var VM = can.Map.extend({
  define: {
    foo: {
      get(lastVal, setVal) {
        console.log('getting foo');
        setTimeout(() => {
          console.log('setting foo');
          setVal(5);
        }, 10);
      }
    },
    bar: {
      get() {
        var foo = this.attr('foo');
        if (foo) {
          console.log(`getting bar... foo = ${foo}`);
          return foo * 2;
        }
      }
    }
  }
});
```

Using stache binding:
http://jsbin.com/dagozulelu/edit?html,js,console,output

If it matters, in my use case, `bar` is also an asynchronous virtual property that makes a network request once `foo` is set.

As a workaround, I am setting `foo` in my component's `inserted` event for now.

**Comment by justinbmeyer** [comment]
Certainly a bug.

Seems like there are 2 problems.  First, when `setVal` is called, it's not dispatching in a batch.

But the more important problem is likely when `this.attr('foo')` is being called ... it's actually setting up a binding on two things:

1. the "foo" property, which is correct.
2. the internal compute of the "foo" property, which is incorrect.  This is happening here: https://github.com/bitovi/canjs/blob/minor/map/map.js#L259

The solution is probably to change:

https://github.com/bitovi/canjs/blob/minor/map/map.js#L259

To something like:

```js
can.__notObserve(function(){
  computedAttr.compute();
})
```

But, I would avoid re-creating the function each time and have a helper like:

```js
var readButDontObserveCompute = can.__notObserve(function(compute){
  return compute()
})
```

And then call:

```js
return readButDontObserveCompute(computedAttr.compute);
```

**Comment by whitecolor** [comment]
I experience I think a like problems with computes, I tried solution above, it doesn't seem to work.

**Comment by justinbmeyer** [comment]
If you can submit a test, I'll get this in 2.3.8 asap.
