### ISSUE TITLE
extended can.List helpers

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#192]
Create an array helpers plugin that adds underscore/lowdash methods to can.List.

**Comment by imjoshdean** [comment]
:+1:

**Comment by jawshooah** [comment]
Voting link appears to be broken, so I'll just toss my +1 in here. Specifically for `.some()` and `.every()`.

**Comment by justinbmeyer** [comment]
Moving to https://github.com/canjs/can-define/issues/13
