### ISSUE TITLE
can.List should implement a "reduce" method

### ISSUE THREAD

**Issue by mjstahl** [canjs/canjs#1939]

**Comment by daffl** [comment]
Instead of adding them all individually we should probably discuss adding Underscore/Lodash collection methods more.

**Comment by mjstahl** [comment]
Well I added a simple implementation and some tests.  If we decided to go a different route, that is completely fine. Just happen to need in a project so I made an implementation since we had to use lodash instead.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-define/issues/13
