### ISSUE TITLE
can-submit should always prevent default

### ISSUE THREAD

**Issue by daffl** [canjs/canjs#1941]
You never want the form to submit if CanJS is handling it.

**Comment by justinbmeyer** [comment]
I mostly agree ... but this would be a breaking API change.  It's something we could do for `($submit)` however.

**Comment by justinbmeyer** [comment]
btw, for the chat app, use `can-enter` on the input

**Comment by justinbmeyer** [comment]
It's too late for this. 

We could ... allow multiple expressions in call-expressions.  

```
<form ($submit)="%event.preventDefault(); yourMethod()">
```

But I think some special syntax might be ok too.

```
<form ($!submit)="yourMethod()">
```

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-stache-bindings/issues/10
