### ISSUE TITLE
IE 8 using can.control without extend fails yielding "Object doesn't support this action"

### ISSUE THREAD

**Issue by smoothlikejazz** [canjs/canjs#1957]
Hi, so in using IE8 and upgrading to new steal, using can.Control({}) is no longer working, and throws an error of "Object doesn't support this action", by utilising "extend" , can.Control.extend({}), this will alleviate the issue. 

I have ran the can.control tests for can version 2.2.5 and currently all 19 cases fail, placing the .extend, fixes most issues, yet 5 cases still fail with extend being added. 

I would like to know if new steal should be backwards compatible, or shall I update all Controls to use the "extend" method

Thanks

JMVC Forum reference: https://forum.javascriptmvc.com/#Topic/32525000001904013

**Comment by matthewp** [comment]
Thanks, I'm confused though, what about "can.Control({})" does ie8 have a problem with?

**Comment by smoothlikejazz00** [comment]
No problem, thanks for you reply Matt, 
So we have a lot of controllers created via var x= can.Control({...},{...});  and testing in IE8 when these lines are hit, IE is throwing an error stating "Object doesn't support this action",and browser halts; but then when updating with using can.Control.extend({...},{...});  is our current workaround that works works in IE8.

**Comment by matthewp** [comment]
Are you importing `can` in that module?

**Comment by smoothlikejazz00** [comment]
Not in this module directly.

**Comment by smoothlikejazz00** [comment]
setting debug point right before, can.Control statement.

type of can.Control returns "function"

**Comment by matthewp** [comment]
> Not in this module directly.

I'm not sure that this is it (because can does exist) but try importing `can` into this module.  You should really always import your dependencies and not depend on them having already loaded.  Maybe can is only partially loaded when this module is called.

**Comment by smoothlikejazz00** [comment]
Thanks for your help, ill try that, and also try upgrading our current version of can.

**Comment by justinbmeyer** [comment]
Is this the console.log getting hit in `can.Construct`?  

https://github.com/bitovi/canjs/blob/master/construct/construct.js#L496

What line does the error happen?

As of CanJS 2.0, you should always use can.Construct.extend.  CanJS 3.0 will likely enforce this.

**Comment by justinbmeyer** [comment]
http://canjs.com/docs/can.Control.html mentions that the `Constructor(proto)` signature is deprecated.  However, we should be using the @deprecated tag.

**Comment by smoothlikejazz00** [comment]
We have updated our source code to use the new syntax. yet in our situation, we have customers using the old syntax for UI customisation and just want to make sure that our customer wouldn't have any issues.

after digging into the issue more, the console.log.apply is causing the error, stemmed from https://github.com/bitovi/canjs/blob/master/construct/construct.js#L496

in the snippet below in IE8 console.log.apply is throwing error "Object doesn't support this action"
```
_logger: function (type, arr) {
			if (console.log.apply) {
				console[type].apply(console, arr);
			} else {
				console[type](arr);
			}
		}
```

**Comment by smoothlikejazz00** [comment]
I have replaced the above code in can/util/can.js with the below code snippet and it is working now
```
_logger: function (type, arr) {
			// test for console support
			if (typeof console == "object") {
				// test for console.log.apply support in IE8
				if (typeof console.log == "object") {
					console[type](arr);
				} else {
					if(console.log.apply){
						console[type].apply(console, arr);
					} else {
						console[type](arr);
					}
				}
			}
		}
```

**Comment by matthewp** [comment]
Great, mind sending a pull request then?

**Comment by rjgotten** [comment]
`console.log` and its siblings are host functions in IE9 and below, which means they don't inherit from `Function` and don't have `call` or `apply` members themselves. There's a little trick you can perform though:

```js
_logger: function (type, arr) {
	// test for support
	if (( typeof console == "object" ) && console[ type ]) {
		// applying the call method works around the fact that the console object
		// in IE9 and below is a host object whose methods are not of type Function.
		Function.prototype.call.apply([ console[type], console ].concat( arr ));
	}
}
```
This should work in any browser and shaves off some bytes.

**Comment by justinbmeyer** [comment]
IE8 isn't supported in 3.0.  I'm going to add a label "needs a hero".  We'll fix it if someone submits a pull request.
