### ISSUE TITLE
Improper Detection of deferred with can.List in can.View

### ISSUE THREAD

**Issue by kipwilliams** [canjs/canjs#1960]
When resolving a deferred can.List "findAll().then( **lst** ) { ... }" the resolved object **lst** will contain a property **"_deferred"** which holds a deferred object.  The function **getDeferreds** in **can.view** will loop through the can.List's props including "_deferred" and detect it as a deferred.  This results in  can.view return value being a deferred instead of a document fragment.

**Comment by justinbmeyer** [comment]
closing as `can.view` is deprecated.
