### ISSUE TITLE
Documentation error on guides page

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/canjs#1961]
In this [page ] (http://canjs.com/guides/Utilities.html) in the code example for can.capitalize is wrong the capitalize function is missing

**Comment by justinbmeyer** [comment]
@cherifGsoul that page doesn't seem to exist anymore.  Can you let us know how you navigated to it?  Thanks!

**Comment by marshallswain** [comment]
I'm not sure how to edit old documentation pages.  @daffl Can you shed some light on this for me?  The page used to exist at guides/utils.md, but was removed with 2ec8deec5bc4dd47998f82b4bd22a6895d36c5eb.

**Comment by cherifGsoul** [comment]
@justinbmeyer sorry Im late it seems it is removed in 2.3 version so you can check it in 2.2 version http://canjs.com/2.2/guides/Utilities.html 
![error](https://cloud.githubusercontent.com/assets/109013/10953292/9698c8ce-8347-11e5-911c-7d84a31467ca.png)

**Comment by justinbmeyer** [comment]
@marshallswain What I've done in the past is create a legacy branch of a tagged version like: https://github.com/canjs/canjs/tree/1.1-legacy

Then I make changes there and point documentjs to that.

**Comment by pYr0x** [comment]
created a new branch https://github.com/canjs/canjs/tree/2.2-legacy where david can linked the documentation

**Comment by justinbmeyer** [comment]
canjs.com's documentjs.json needs to point at that branch: https://github.com/bitovi/canjs.com/blob/gh-pages/documentjs.json#L39

**Comment by pYr0x** [comment]
https://github.com/bitovi/canjs.com/pull/261
@justinbmeyer please merge
