### ISSUE TITLE
After change of comparator @index in view stays the same for elements

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#1962]
After change of comparator on the list - @index value in view stays the same for sorted elements:

```
1. 700
2. 800
3. 300
````
after sort (using chage of `comparator` value I get:
```
3. 300
1. 700
2. 800
````

Is it a feature or a bug?

**Comment by justinbmeyer** [comment]
Bug

**Comment by justinbmeyer** [comment]
@akagomez Any thoughts on this?  Does a change of the comparator only issue "move" events?  If so, are they getting their `computeIndex` updated?

**Comment by justinbmeyer** [comment]
It doesn't look like `indexMap` is updated. An example of it being updated in `add`:

https://github.com/bitovi/canjs/blob/master/view/live/live.js#L285 

Remove does something similar.

This needs to happen in `move`.
