### ISSUE TITLE
Losing context in can.compute callbacks

### ISSUE THREAD

**Issue by lukewhyte** [canjs/canjs#1968]
Been working on a project with can, realized my version was old and bumped up to latest NPM release (v2.3.0-beta.1) and am now losing context in my compute callbacks. Eg:
````
can.Component.extend({
  viewModel: {
    someProp: can.compute(function () {
      return this.attr('someOtherProp'); // error: can't call attr on undefined prop
    })
  }
});
````
Works fine when I switch to v2.2.9

**Comment by justinbmeyer** [comment]
@lukewhyte I'm  not sure what's happening, but that form of compute-on-a-prototype should not be used anymore.  Instead use a define.getter.  I'll make sure a deprecation notice gets added.

**Comment by lukewhyte** [comment]
thanks @justinbmeyer

**Comment by justinbmeyer** [comment]
closing as this is deprecated.
