### ISSUE TITLE
Event simple setter

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#1984]
I'd like an easy way to set a property value from an event handler.

Currently this sorta thing works:

```
<input ($click)="attr('name', $element.val)"/>
```

But that kinda stinks.  Here's two other possibilities:

#### Option 1 

If you call a function that doesn't exist, but does match an attribute:

```
<input ($click)="name($element.val)"/>
```

Cons - this won't work well if `name` is a function.

#### Option 2 

Use hash expression:

```
<input ($click)="name=$element.val"/>
```

Cons - double equal

## Test for option 1

```js
	test('viewModel binding (event)="property(value)"', function(){
		can.Component.extend({
			tag: "viewmodel-binding",
			viewModel: {
				makeMyEvent: function(){
					this.dispatch("myevent");
				},
				bar: "BAR"
			}
		});
		var frag = can.stache("<viewmodel-binding (myevent)='foo(%viewModel.bar)'/>")(
			new can.Map({foo: null})
		);
		can.viewModel(frag.firstChild).makeMyEvent();
		equal( can.viewModel(frag.firstChild).attr("foo"), "BAR", "foo set to bar in view model");
		
		
	});
```

**Comment by whitecolor** [comment]
time for JSX

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-stache-bindings/issues/6
