### ISSUE TITLE
case statement in a switch does not re-evaluate

### ISSUE THREAD

**Issue by julia-allyce** [canjs/canjs#1988]
Using the latest canjs, switch seems to fail removing the case block that has an if/else block.

![routing-rendering2](https://cloud.githubusercontent.com/assets/1000574/10496061/efc0ccd8-728c-11e5-815b-fad965c652c3.gif)
## stache template
```
<ul class="nav">
	<li>
		<a can-href="{page='home'}" class="{{#eq page 'home'}}active{{/eq}}">Home</a>
	</li>
	<li>
		<a can-href="{page='users'}" class="{{#eq page 'users'}}active{{/eq}}">Users</a>
	</li>
</ul>
<div class="content">
{{#switch page}}
	{{#case 'home'}}
		<h1>Home</h1>
	{{/case}}
	{{#case 'users'}}
		{{#if slug}}
			<h1>User and Slug</h1>
		{{else}}
			<h1>User</h1>
		{{/if}}
	{{/case}}
{{/switch}}
</div>
```
## app.js
```
import can from 'can/';
import route from 'can/route/';
import $ from 'jquery';
import 'can/route/pushstate/';

import 'style.less!';
import appTemplate from 'index.stache!';

var AppState = can.Map.extend({});
var app = new AppState();

route(':page', { page: 'home' });
route(':page/:slug', { slug: null });
can.route.map(app);
can.route.ready();

$('body').append(appTemplate(app));
```

**Comment by matthewp** [comment]
Can you open a donejs issue that simply points to this one and assign it to me.

**Comment by matthewp** [comment]
@julia-allyce I tried to recreate the bug here https://github.com/bitovi/canjs/commit/bbb25cc76f3c0628f244968b6c90906137a1c9ce but am not seeing the same thing.

Are you sure you have the latest donejs?  If you just did an `npm install donejs -g` you actually have an older version.  Since we are on a prerelease you have to do `npm install donejs@0.5.0-pre.16 -g`.

**Comment by julia-allyce** [comment]
I was not using donejs at all actually. Just steal and canjs.

**Comment by justinbmeyer** [comment]
@julia-allyce Can you update to latest and try again?  I fixed a similar bug last week.  Hopefully that removes this.  

Btw: https://github.com/julia-allyce/routing-example doesn't seem to be public.  Maybe put it in a jsbin?

**Comment by julia-allyce** [comment]
It looks like I deleted the repo :/ I just removed a few several weeks ago, but I probably still have it on my machine...lemme see.

**Comment by julia-allyce** [comment]
Pushed repo up and lastest version of can seems to have resolved the issue @justinbmeyer
