### ISSUE TITLE
Component bindings do not always update in stache

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#1994]
This is a bit tricky to explain so you should just look at the jsbin.

http://jsbin.com/naroyawoya/edit?html,js,console,output

```html
{{#eq action 'view'}}
  page: {{page}}<br>
  <foo-bar page-name="{{page}}"></foo-bar>
{{/eq}}
```

When the above 'view' block is first rendered, the value of `page` is somehow cached so that all subsequent renders of the `<foo-bar>` component receive the original value, despite the fact that the displayed `{{page}}` in the same block is changing as you switch between 'view' and 'list'. The viewmodel logs whenever `pageName` is set so you can see it's clearly getting the wrong data.

This is a serious problem in my app so I am open to workarounds.

**Comment by justinbmeyer** [comment]
Thanks for submitting.  Anyway you can get it to break without components and can/route?  Just templates and maps.  Thanks!

**Comment by dylanrtt** [comment]
It's not using can.route. Just maps and components.

**Comment by justinbmeyer** [comment]
ah, read page and assumed.  Can you remove the component?

**Comment by justinbmeyer** [comment]
btw, a binding like:

```
<foo-bar page-name="{{page}}"></foo-bar>
```

Is going to give strange results.  Any reason you are using that instead of:

```
<foo-bar {page-name}="page"></foo-bar>
``

or the older:

```
<foo-bar page-name="{page}"></foo-bar>
```

**Comment by dylanrtt** [comment]
I haven't upgraded to the new pre versions yet because I've been really busy. It seems odd that doing `page-name="{{page}}"` is not supported. If so, I would have to go back and update older code.

The jsbin uses minor but this happens in much older versions as far as I can tell. I just did some testing and it happens in 2.2.6 but not 2.2.5.

**Comment by justinbmeyer** [comment]
@dylanrtt it is supported, but it sets up a binding on an attribute value ... not a direct binding to the scope.    It can only bind to `string` values ... and isn't synchronous as attribute events are fired next-turn.

**Comment by dylanrtt** [comment]
I recognize the value in using the new syntax for 1-way bindings (especially being able to pass non-strings), but I wouldn't expect those cons to cause this issue. I haven't had any other problems with this syntax before besides having to wait a frame for components to see the change. In this case, the change is never occurring.

**Comment by justinbmeyer** [comment]
> I recognize the value in using the new syntax for 1-way bindings (especially being able to pass non-strings), but I wouldn't expect those cons to cause this issue.

I don't really either, but things to eliminate.  We aren't going to be able to look at it until next week so I'm trying to share ideas on things to try to isolate the problem so it will be faster when we have time to look at it.

**Comment by dylanrtt** [comment]
Well the new syntax does work seemingly without this issue, so I'll just be converting to the new syntax anytime I encounter this problem.

**Comment by justinbmeyer** [comment]
Closing this.  If someone else spots it and can isolate the test a bit more, we'll fix it.
