### ISSUE TITLE
Warn on miss-matched quotes

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#1995]
I wrote `{(foo})` and it took me too long to figure out.  Lets let people know.

This can be done by changing the regular expression to account for these types of attributes:

https://github.com/bitovi/canjs/blob/minor/view/bindings/bindings.js#L549

And then change `attributeNameInfo` https://github.com/bitovi/canjs/blob/minor/view/bindings/bindings.js#L386 to check for miss-matches like:

- `{(foo})`
- `({foo})`
- `(foo}`
- `{foo)`

**Comment by pYr0x** [comment]
should this be documented?

**Comment by justinbmeyer** [comment]
That a warning is console.log-ed?  We don't document that we do that elsewhere.  Why do you think it should be documented?

**Comment by pYr0x** [comment]
you tagged https://github.com/canjs/canjs/pull/2078 as "Documentation"

**Comment by justinbmeyer** [comment]
Ah, I don't really know what to consider adding something like this.  I suppose it's a `feature`, but we tend to reserve that for things that would need a `minor` version change.
