### ISSUE TITLE
can.jquery.dev.js doesn't include dev parts of code

### ISSUE THREAD

**Issue by scaryzet** [canjs/canjs#2004]
can.jquery.dev.js doesn't actually include dev parts of code. I also tried to build canjs manually but got the same result.

I wanted the class naming (via eval) chunk of code in can.Construct.extend. Had to insert it by hand into my can.jquery.js. Why it is even stripped out in non-dev builds? I know eval is evil and stuff... But console.log is much less convenient without proper class names.

Well, I can live with this, but people will think "class naming feature doesn't work, a bug?.."

**Comment by justinbmeyer** [comment]
There are run times that don't support eval. We want to support those runtimes.

**Comment by justinbmeyer** [comment]
This is a bug.  Thanks for reporting.

**Comment by justinbmeyer** [comment]
For some reason, `steal-tools` must be removing:

```
//!steal-remove-start
```

This should be a configurable option in steal-tools with `removeDevelopmentCode`: http://stealjs.com/docs/steal-tools.transform.options.html

Perhaps the build config isn't setting it right: 

https://github.com/bitovi/canjs/blob/master/build/config_stealPluginify.js#L189

looks like it is.  Somewhere this is breaking down.

**Comment by matthewp** [comment]
I did a git log search in steal-tools and I don't see there ever being a `keepDevelopmentCode` option, transform has always had `removeDevelopmentCode`.  I would think changing it to `removeDevelopmentCode: false` would work.
