### ISSUE TITLE
stache does not update view with can.List and deep properties

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#2007]
on checking out how to listen to viewModel-changes in components event object (https://github.com/bitovi/canjs/issues/1740) i found a bug.

in this example http://jsbin.com/lakefonulo/edit?js,console,output the "mylist" item 0 is changed to "Hello" but the view is not updated.

**Comment by justinbmeyer** [comment]
This is almost certainly a problem with `can.view.live.list` not listening to `set` events.

Similar to how `can.view.live.list` listens to add events:

- handler - https://github.com/bitovi/canjs/blob/master/view/live/live.js#L236
- binding - https://github.com/bitovi/canjs/blob/master/view/live/live.js#L423

It needs to be doing a similar thing with set.  But when a set events happens can sneakily call `remove()` and `add` methods with the updated item similar to how diffing does it: https://github.com/bitovi/canjs/blob/master/view/live/live.js#L402
