### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by Daniel-Hug** [canjs/canjs#2018]
Dead links:
 - [ ] https://github.com/bitovi/canjs/blame/minor/guides/getting-started-tutorial/tutorial.md#L114
 - [ ] https://github.com/bitovi/canjs/blame/minor/guides/getting-started-tutorial/setup.md#L16
 - [x] https://github.com/bitovi/canjs/blame/minor/guides/getting-started-tutorial/setup.md#L99
 - [ ] https://github.com/bitovi/canjs/blame/minor/guides/getting-started-tutorial/stache-templates.md#L149

**Comment by justinbmeyer** [comment]
thanks!

**Comment by Alfredo-Delgado** [comment]
- https://github.com/bitovi/canjs/blame/minor/guides/getting-started-tutorial/tutorial.md#L114 & https://github.com/bitovi/canjs/blame/minor/guides/getting-started-tutorial/setup.md#L16 **looking into status of having zip file creation automated** [cf.](https://github.com/canjs/canjs/blob/master/guides/examples/PlaceMyOrder/create-zip-files)
- https://github.com/bitovi/canjs/blame/minor/guides/getting-started-tutorial/setup.md#L99 **unable to reproduce**
- https://github.com/bitovi/canjs/blame/minor/guides/getting-started-tutorial/stache-templates.md#L149 **should link to #context**
