### ISSUE TITLE
bug in tutorial app

### ISSUE THREAD

**Issue by Daniel-Hug** [canjs/canjs#2025]
On http://www.place-my-order.com/restaurants selecting a state and city works just fine.
but none of the chapter demos in [/guides/examples/PlaceMyOrder](https://github.com/bitovi/canjs/tree/master/guides/examples/PlaceMyOrder) work. After selecting a state "Choose a City" becomes the only option in the city `<select>`.

Following the tutorial instructions didn't work for me either.

**Comment by robert-sbin** [comment]
Yes, find same error. Found that in Chrome you get always "Choose a City" during in Firefox you get "Loading ...". 
I think Browsers don't wont to load Files with ajax-calls like "can.ajax". 
So I changed my fixtures.js to:
```
  can.fixture('GET /api/cities', function(request, response) {
  var citiesbystate = [
    {
      "name": "Green Bay",
      "state": "WI"
    },
    {
      "name": "Milwaukee",
      "state": "WI"
    },
    {
      "name": "Chicago",
      "state": "IL"
    },
    {
      "name": "Peoria",
      "state": "IL"
    },
    {
      "name": "Detroit",
      "state": "MI"
    },
    {
      "name": "Ann Arbor",
      "state": "MI"
    }  
  ];
  
  var cities = [];
  citiesbystate.forEach(function (city){
    if (city.state === request.data.state) {
      cities.push(city);
    }
  });
  response({"data": cities});
});
```

**Comment by pYr0x** [comment]
@Daniel-Hug @robert-sbin unfortunately i cant reproduce the problem.

clone the repo and open the chapter 9, all things are working as expected

```can.ajax``` make a asnyc call and ```response(data)``` is a asnyc setter

please reopen if needed

**Comment by robert-sbin** [comment]
Yes, it works if you open the index.html over a http-server. When you open the index.html over the file-open dialog of the browser, it doesn't.
