### ISSUE TITLE
3.0 Changes

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2026]
I'd like this issue to be a super issue to track all 3.0 major changes.
## 3.0 Goals

Primary goals:
- establishing the new best practices (stache, new bindings, can-connect)
- highly compatible with 2.3, with the exception of installing / setting up CanJS.
- moving each module into separate repos, allowing people to more easily upgrade a small part of their application.
- revamping documentation, focusing on best practices
### can-component
- [x] repository created
- [x] repository initialized
- [x] - standalone
- [x] - documented
- [x] - demos
- [ ] - reviewed
### can-compute
- [x] repository created
- [x] repository initialized
- [x] basics working
- [x] published
- [x] documented
- [x] - demos
- [ ] reviewed
### can-connect
- [ ] reviewed
- [x] - demos
### can-construct
- [x] repository created
- [x] repository initialized
- [x] basics working
- [x] published
- [x] documented
- [ ] reviewed
- [ ] - demos
### can-contruct-proxy
- [x] repository created
- [x] repository initialized
- [x] - standalone
- [ ] documented (outside core)
- [ ] reviewed
- [ ] - demos
### can-control
- [x] repository created
- [x] repository initialized
- [x] basics working
- [x] published
- [ ] documented
- [ ] reviewed
- [ ] - demos
### can-control-plugin
- [x] repository created
- [x] repository initialized
- [x] standalone
- [ ] documented (outside core)
- [ ] reviewed
- [ ] - demos
### can-define
- [ ] reviewed
- [x] - demos
### can-event
- [x] repository created
- [x] - `addEventListener`
- [x] repository initialized
- [x] basics working
- [x] published
- [ ] documented
- [ ] reviewed
- [ ] - demos
### can-fixture
- [x] documented
- [ ] reviewed
- [ ] - demos
### can-interrupt
- [ ] documented (legacy for now ... ecosystem once it works with DefineMap)
- [ ] reviewed
- [ ] - demos
### can-list
- [x] repository created
- [x] repository initialized
- [x] - standalone
- [ ] - documented
- [ ] reviewed
- [ ] - demos
### can-map
- [x] repository created
- [x] repository initialized
- [x] - standalone
- [ ] - documented
- [ ] reviewed
- [ ] - demos
### can-map-define?
- [x] repository created
- [x] readme.md in the `adding-docs` branch
- [x] repository initialized
- [x] - standalone
- [ ] - documented
- [ ] reviewed
- [ ] - demos
### can-map-attributes
- [x] repository created
- [x] repository initialized
- [x] - standalone
- [x] - documented (outside core)
- [ ] reviewed
- [ ] - demos
### can-map-backup
- [x] repository created
- [x] repository initialized
- [x] - standalone
- [x] - documented (outside core)
- [ ] reviewed
- [ ] - demos
### can-map-delegate
- [x] repository created
- [x] repository initialized
- [x] - standalone
- [x] - documented (outside core)
- [ ] - demos
### can-map-lazy
- [x] repository created
- [x] repository initialized
- [x] - standalone
- [ ] - documented (outside core)
### can-map-setter
- [x] repository created
- [x] repository initialized
- [x] - standalone
- [x] - documented (outside core)
### can-model
- [x] repository created
- [x] repository initialized
- [x] - standalone
- [ ] - documented (outside core)
### can-route
- [x] repository created
- [x] repository initialized
- [x] - standalone
- [ ] - documented 
- [x] - demos
#### can-stache
- [x] repository created
- [x] repository initialized
- [x] - standalone
- [ ] - demos
#### can-view-autorender
- [x] repository created
- [x] repository initialized
- [ ] - documented 
- [ ] - demos
#### can-stache-bindings
- [x] repository created
- [x] repository initialized
- [x] - documented 
- [ ] - demos
#### can-view-callbacks
- [x] repository created
- [x] repository initialized
- [ ] - documented
- [ ] - demos
#### can-view-import
- [x] repository created
- [x] repository initialized
- [x] - documented
- [ ] - demos
#### can-view-live
- [x] repository created
- [x] repository initialized
- [ ] - documented
- [ ] - demos
#### can-view-nodelist
- [x] repository created
- [x] repository initialized
- [ ] documented
- [ ] - demos
#### can-view-parser
- [x] repository created
- [x] repository initialized
- [ ] - documented 
- [ ] - demos
#### can-view-scope
- [x] repository created
- [x] repository initialized
- [ ] - documented 
- [ ] - demos
#### can-view-target
- [x] repository created
- [x] repository initialized
- [ ] - documented 
- [ ] - demos
### can-legacy-view-helpers
- [ ] - standalone
### can-ejs
- [x] repository created
- [x] repository initialized
- [ ] - using totally independent view helpers
- [ ] - standalone
- [ ] - documented 
### can-mustache
- [x] repository created
- [x] repository initialized
- [ ] - using totally independent view helpers
- [ ] - standalone
- [ ] - documented 
### can-view-href
- [x] repository created
- [x] repository initialized
- [ ] - standalone
- [ ] - documented (outside core)
### can-view-modifiers
- [x] repository created
- [x] repository initialized
- [x] - standalone
- [ ] - documented (outside core)
### [can-util](https://github.com/canjs/can-util)
- [x] - what's needed to needed to support CanJS, but without jQuery
### can-jquery
- [x] repository created
- [x] repository initialized

Provide nice integration for CanJS.
- `$().remove()` - we clean up memory
- `$().attr('')` - we fire an attributes event in old browsers
- `$().viewModel()`
## Other changes:
- no more sync `inserted` and `removed` events.  This will be dispatched with mutation observer.

**Comment by justinbmeyer** [comment]
- [ ] - https://github.com/canjs/canjs/issues/962

**Comment by justinbmeyer** [comment]
## Breaking Changes

- Controls use a raw element for `this.element` instead of a jQuery element. Fix is to wrap with `$(this.element)`
- No more `can.view` to load things (for at least the time being).  Register partials yourself or use a module loader.

**Comment by matthewp** [comment]
> Register partials yourself or use a module loader.

Will there be a new API for that?  Currently there's just `can.view.preload` (I think?) which is semi-private.

**Comment by justinbmeyer** [comment]
@matthewp you can pass partials to your helpers argument.

renderer(data,{partials: {name: otherRenderer}})

**Comment by justinbmeyer** [comment]
## Important Remaining 3.0 Changes

- [ ] - https://github.com/canjs/can-stache-bindings/issues/8 - make `.` live-bindable

**Comment by matthewp** [comment]
# Legacy stuff

* [ ] - can-jquery: https://github.com/canjs/can-jquery/issues/1
* [ ] - can-connect/can/model - put on namespace of can.Model not already there
  * can-model always puts itself on ns.
* [ ] - can/legacy includes can-map
* [ ] - can-connect data-url to handle jQuery promises.
