### ISSUE TITLE
Formalize two-way binding with selects.

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2027]
Using the new two-way binding syntax `{($value})="key"`, the parent scope value should be updated assuming the parent value is `undefined`.  

However, this makes it difficult to get the nice behavior of showing an empty select when the scope is `undefined`.  And once the value is selected, you can no longer select the empty option.

This is still possible, but tricky.  I'd like a way to make it easier.

**Comment by daffl** [comment]
I don't think this is fixable. A select field like

```html
  <select id="test">
    <option>One</option>
  </select>
```

When set like this:

```js
var element = document.getElementById('test');
element.value = '';
```

Will always show an empty select in Chrome/Safari etc. and the first item in Firefox.

**Comment by justinbmeyer** [comment]
Yarg ... that's dumb.  So for this to work in all browsers, we'd have to add an empty <option>?

**Comment by DesignByOnyx** [comment]
If you set the `selectedIndex` to -1 it will clear out the element, even in Firefox:

http://jsfiddle.net/3xyxpcqo/

**Comment by matthewp** [comment]
Normally when two way binding we set initial values based on which has a value. In this case the parent doesn't have a value but the child does, so we are making an exception for selects and saying that their value doesn't matter?

**Comment by matthewp** [comment]
More clearly, for selects we are ignoring their value and forcing parent->child initialization. Is this right?

**Comment by justinbmeyer** [comment]
This is a special case because FF forces it to be. 

Ideally, we wouldn't do special casing here. I wonder if it's possible to tell if the value was actually set, or just defaulted to the first item.

**Comment by matthewp** [comment]
I don't think it's possible to set a select's value as `undefined` so the parent compute is always going to be initialized as an empty string if we do this.

**Comment by matthewp** [comment]
Scratch that, if we initialize this special case before bindings are set up the parent compute's value won't be updated. This sucks though.

**Comment by matthewp** [comment]
This changes the behavior that was added for:

* https://github.com/bitovi/canjs/issues/1679
* https://github.com/bitovi/canjs/commit/c705aa6ca79571cf899fac95cb0b67f8d201d6a3

**Comment by Alfredo-Delgado** [comment]
Working on this, I'm not sure that the case where a key in a parent scope is undefined should be our concern. 

e.g. current behavior ([consistent across browsers](http://output.jsbin.com/mosikef))
```
var map = new can.Map({ });
equal(frag.firstChild.selectedIndex, 0, 'undefined <- {($first value)}: selectedIndex = 0');
```

What isn't consistent is what happens when the key's value doesn't match one of the select's options:
```
map.attr('key', 'does not match one of the options');
equal(frag.firstChild.selectedIndex, -1, 'selectedIndex = -1');
```
This passes in Chrome, but fails in Firefox (selectedIndex === 0).

This [branch](https://github.com/canjs/canjs/compare/selected-index-2027) addresses this much. I added the fix in `attr.set` because it seems like a universal problem. Like @matthewp mentioned above, this new behavior conflicts with the change done at https://github.com/bitovi/canjs/commit/c705aa6ca79571cf899fac95cb0b67f8d201d6a3

**Comment by justinbmeyer** [comment]
@Alfredo-Delgado I checked out your solution after I did mine (in bindings).  Yours seems better, but some tests of mine did not pass.  My pull request is here: #2076.  @daffl If it passes, lets get that in and we can investigate making this work directly in `attr` later.
