### ISSUE TITLE
Documentation Elements and Attributes

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#2028]
Tell me if I am wrong, but is the documentation of the Elements and Attributes completely wrong with the two-way binding and the reference? 
http://canjs.com/docs/can.elementAndAttributes.html
I can make a PR but I wanted to ask first if i misunderstand something.

**Comment by matthewp** [comment]
Yes, it is wrong.

**Comment by pYr0x** [comment]
sould i correct this? or would you like to change the content with hyperlinks to can.view.bindings

**Comment by justinbmeyer** [comment]
Please correct it!  Otherwise we will get to it.  Thanks!
