### ISSUE TITLE
Importing a template doesn't work with the new syntax

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#2042]
```
<can-import from='can/view/import/test/other.stache!' {^value}='*other' />{{> *other}}
```

Tries to import `*other.mustache`, not sure why yet.

**Comment by matthewp** [comment]
https://github.com/bitovi/canjs/commit/4b3402cc11702220796ace332506f9e8ba1b15ea contains tests.

**Comment by justinbmeyer** [comment]
@matthewp Can you make the changes we talked about on Friday tomorrow?  I'd like to get 2.3.2 done.  Thanks!

**Comment by justinbmeyer** [comment]
@matthewp made them.  This just needs to be merged: https://github.com/canjs/canjs/pull/2045
