### ISSUE TITLE
Make %scope available in the scope.

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#2043]
For the partial usage I want the ability to render the partial with the current scope. Ideally I could do:

```handlebars
<can-import from='test/other.stache!' {^@value}='*other' />

{{{*other(%scope)}}}
```

**Comment by justinbmeyer** [comment]
We can maybe "sneak" this into 2.3 undocumented and then make a 2.4?

**Comment by matthewp** [comment]
I don't think it's super important now that the `{{> *other}}` syntax is working which correctly applies the correct scope.

**Comment by justinbmeyer** [comment]
Closing then.  I'll reopen if someone asks for it in `can-view-scope`.
