### ISSUE TITLE
%index doesn't work with can.Map values in master

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#2067]
The {{(at)index}} stache helper/keyword will not render an index if the value at that index is a map. 

See: http://jsbin.com/qogafo/edit?html,js,output

**Comment by pYr0x** [comment]
should {{@index}} not be replaced by {{%index}} ?

**Comment by akagomez** [comment]
Maybe. Didn't work for me though.

**Comment by justinbmeyer** [comment]
It should be %index, but work both ways for now.
