### ISSUE TITLE
FF debugging functions conflicting with can.Map

### ISSUE THREAD

**Issue by julia-allyce** [canjs/canjs#2069]
This is from PR #1877 
"FF introduced a debugging function called watch. This meant that if you had a property labeled watch, it would throw an exception."
cc: @tracer99

**Comment by justinbmeyer** [comment]
@julia-allyce @tracer99 do we have a property named watch?  What's the actual problem?

**Comment by tracer99** [comment]
This was lost in the original ticket.
FF has an internal function called watch.
So if you want to have a map with a property watch, map.attr("watch") will fail.
I solved it by using hasOwnerProperty in the attr function in CanJS. However, @matthewp was concerned that this approach would not handle inhreted properties.

**Comment by justinbmeyer** [comment]
@tracer99 where in the attr function did you use this?  in `___get`?

**Comment by justinbmeyer** [comment]
> FF has an internal function called watch.

Is this on `Object.prototype`?

My concern would be more about performance.  We'd want to feature-detect this and only add this check for this property, specifically when the feature is detected.

**Comment by justinbmeyer** [comment]
@tracer99 let me know if you'd want to pair on it.  I'm available most times.  Just hit me up on gitter.

**Comment by justinbmeyer** [comment]
@prashantsharmain do you want to pair on it this week?

**Comment by prashantsharmain** [comment]
@justinbmeyer Sure, how about Thursday (12/17) ? We could set it up at the same time we have the contributor's meeting.

If I manage to find a fix before that, I'll share an update.

**Comment by julia-allyce** [comment]
Also just FYI, the original ticket/PR still exists along with all the code changes. It was only closed not deleted.
You can see the original pr here #1877
