### ISSUE TITLE
The %element call expression is not can.$ wrapped as the docs suggest

### ISSUE THREAD

**Issue by mickmcgrath13** [canjs/canjs#2073]
The docs here http://canjs.com/docs/can.view.bindings.event.html#section_DOMevents say that the `%element` call expression is "The can.$ wrapped element the event happened upon."

However, it is not a `can.$` wrapped element. For example, I tried this:
 ```
<input {($value)}="searchRoute" ($keyup)="triggerChange(%element)" />
```
```
const AppViewModel = AppMap.extend({
  define: {
    searchRoute: {
      value: ''
    }
  },
  triggerChange: function(el){
   el.trigger("change");
  }
});

can.route("foo/:searchRoute");
```
..and it didn't work.  Changing the `triggerChange` method to this, however, did work:
```
  triggerChange: function(el){
    can.$(el).trigger("change");
  }
```

**Comment by mickmcgrath13** [comment]
..using either `$element` or `@element` instead of `%element` does work.  So is this just a documentation change?

**Comment by matthewp** [comment]
Yeah I supposed this is intentional: https://github.com/canjs/canjs/blob/master/view/bindings/bindings.js#L238

**Comment by justinbmeyer** [comment]
Documentation is wrong.  $element is wrapped.  %element is raw element.
