### ISSUE TITLE
Inline view bindings used with component event bindings ignore bubble hierarchy

### ISSUE THREAD

**Issue by jcavanagh** [canjs/canjs#2075]
Ran into an interesting issue where inline can.view bindings and component event bindings seem to bubble independently.  A component event will always trigger after an inline view binding, regardless of element hierarchy.  

http://jsfiddle.net/jbacon617/a1j9jqcr/

As a workaround, one can use an inline binding at the point where the event should be trapped, instead of an event binding on the component.

**Comment by justinbmeyer** [comment]
My guess is that is because `($click)` is bound before `'.level-two click'`.  

It's like if you do:

```
$("#item").click(a);
$("#item").on("click",".something", b);
```

I believe `a` will be called no matter what `b` does.

I'd have to confirm.  But it this is the case, we might be able to make ($click) happen after `'.level-two click'`.

**Comment by justinbmeyer** [comment]
I confirmed: http://jsfiddle.net/a1j9jqcr/6/

There's no "reasonable" way of making this work.  So, I'm going to close.  If you have an idea, please let me know.
