### ISSUE TITLE
Binding to ViewModel functions and using them in a click handler

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#2079]
http://jsbin.com/zujoxahiqa/1/edit?js,console,output

I would expect this to work:

```handlebars
<foo-baz {^@save}="*save"></foo-baz>

<button ($click)="*save()">Save</button>
```

However save is not called.

**Comment by justinbmeyer** [comment]
There was another issue.  It needs to be `{^@save}="@*save"`

**Comment by justinbmeyer** [comment]
See: https://github.com/canjs/canjs/issues/2065
