### ISSUE TITLE
can.define is not documented

### ISSUE THREAD

**Issue by meconcomputer** [canjs/canjs#2085]
When using **can.Map.define** plugin, the **can.define** object is not documented (see https://github.com/canjs/canjs/blob/master/map/define/define.js#L6)

It should be properly documented (http://canjs.com/docs/can.Map.prototype.define.html), because:
+ it uses a *global attribute* on **can** object to store it's *types*
+ it helps users to understand that it can be used when they need to declare application wide **define.types**

**Comment by justinbmeyer** [comment]
It should probably not be used to create application wide types. This is mostly why it's not documented. There's a issue where I go into this. But I'll write up the explanation when I have a bit of time.

**Comment by Tarabyte** [comment]
> It should probably not be used to create application wide types.

Suppose I have lots of different models having different properties I need to convert using the same logic. For example `createdAt, modifiedAt, beginTime, endTime` etc that should be converted using say momentjs. What is wrong with defining an application wise `moment` type?

**Comment by justinbmeyer** [comment]
@Tarabyte it leads to dependency problems.  Better is to create a "define-types" module helper and do:

```
var types = require("define-types");

var MyMap = can.Map.extend({
  define: {
    createdAt: {
      type: types.moment
    }
  }
})
```

When people set define's globals, they tend to treat them like a global, not specifically requiring them for every module that depends on them.  Plus, these globals can conflict.  If you created a `define-types` module, you could share that with the world, and it would work if someone else created a similar `moment` type.

We could document `can.define`, but I'd put warnings against adding custom global types.

**Comment by meconcomputer** [comment]
Thank you guys for your comments.
   Nice coincidence @tarabyte https://github.com/canjs/canjs/issues/2085#issuecomment-156443443: the 'moment' type was the problem which made me rise this issue :smiley:
   On the other hand, @justinbmeyer you showed how simple and clear (at least for me) the issue of using common custom types on ``define`` can be solved. And this is the way I will do it.
   However, it will be of interest the other arguments that you have on why not to have it documented. Can is a framework implemented to work in the restrict-less javascript environment. I think Can gives you the choices. For me, the choice of not using ``can.define`` should be left on the programmer shoulders.
