### ISSUE TITLE
can.batch.trigger doesn't care about current listeners

### ISSUE THREAD

**Issue by roissard** [canjs/canjs#2088]
can.batch.trigger will push notifications into currentBatchEvents without taking into account the current value of item.__bindEvents.change[0].handler. Later when calling can.dispatch in can.batch.stop all the handlers will be called (even those that where not active when triggering the event).

The bug occurs in 2.3.1.

See following source for reproducing bug with expected vs. output values.

http://pastebin.com/sUR9i6Mi

**Comment by pYr0x** [comment]
@roissard can you write a test into ? https://github.com/canjs/canjs/blob/master/event/event_test.js

**Comment by justinbmeyer** [comment]
@pYr0x @roissard 2.3.3 has a very different batching mechanism.  It's possible that this is already fixed.

**Comment by roissard** [comment]
I have written the test in 2.3.1 and can see the bug occurs. In the master branch the same test passes, so I will close the bug.
