### ISSUE TITLE
Wrong context inside <content/>

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#2092]
Component's template:

````HTML
{{#each items}}
    <content></content>
{{/each}}
```

Inside `content` scope is not current `item` but component's viewModel.

**Comment by justinbmeyer** [comment]
Per web-components ... only one  `<content>` rendering makes sense.  I'm not sure this sorta thing should be officially supported.

**Comment by whitecolor** [comment]
Well it worked in 2.2. And multipe content tags (using select attribute) still needed feature.

**Comment by gsmeets** [comment]
This is extremely useful, it allows you to write components like drop-down menus that can be passed (required or optional) item templates.
