### ISSUE TITLE
Live binding on a derived attribute breaks when it's removed from then added back to the page.

### ISSUE THREAD

**Issue by marshallswain** [canjs/canjs#2095]
Here's a simplified jsbin that illustrates the problem: http://jsbin.com/defibe/3/edit?html,js,output

Here's another: http://jsbin.com/dabamo/15/edit?html,js,output

**Comment by justinbmeyer** [comment]
@marshallswain Anyway you can create a stache test and test w/ that branch?  Thanks,

**Comment by marshallswain** [comment]
Looks like you beat me to it.  Thanks.
