### ISSUE TITLE
2-way binding to current scope in a list acts like a 1-way binding

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2109]
If I have a list of scalar values, I should be able to 2-way bind to them in an `#each` like this:

```html
{{#each names}}
  <input {($value)}=".">
{{/each}}
```

It seems to only be a 1-way binding. Changing the input's value does not update the scope properly.
http://jsbin.com/varajayita/edit?html,js,console,output

It doesn't seem like this was ever supported but it would be handy for cases where the data structure is like this. For now, I'm doing `can-value="names.{{@index}}"` in 2.3.2.

**Comment by daffl** [comment]
I think #1692 is related to this as well.

**Comment by dylanrtt** [comment]
Closing as duplicate of #1692.
