### ISSUE TITLE
can.view.txt does not handle binding hookup on self-closing elements correctly

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#2113]
This issue surfaces when a hookup ends up inside a `colgroup` element. Via the `elements.tagMap` a `colgroup` element supports only a `col` child-element, however `col` is self-closing and may not hold content.

If you have a live-binding expression inside a `colgroup` (e.g. to render a variable amount of columns in a table), then the hookup in [view/render.js;207-222](https://github.com/canjs/canjs/blob/master/view/render.js#L207-L222) will emit HTML for a tag with content, e.g. `<col data-view-id="1234">@@!!@@</col>`.

HTML5 compliant browsers will coerce this to a self-closing col element and will push the `@@!!@@` marker outward: placing it before the containing `table` element, where it will no longer be replaced when hookups are resolved and will end up being exposed to the user.

The solution is to retain some special knowledge of self-closing tags and update the hookup to emit the correct self-closing HTML that way.

**Comment by pYr0x** [comment]
mustache or stache?

**Comment by rjgotten** [comment]
Reproduced in EJS, actually. (Yeah, this bug has been present since forever...)
Not sure if stache or mustache hit the same code paths in `can.view.txt`.

**Comment by pYr0x** [comment]
unfortunately ejs is deprecated and this is a "wont fix"
if you can reproduced this issue with can.stache let us know

**Comment by justinbmeyer** [comment]
@rjgotten can you share an example (or make a pull request with some breaking code).  Thanks!

**Comment by rjgotten** [comment]
@justinbmeyer 

http://jsfiddle.net/07zks0q1/1/

Fails in both EJS and Mustache

**Comment by pYr0x** [comment]
@rjgotten didnt fail on stache
http://jsbin.com/xunopoqexu/edit?html,js,output

**Comment by rjgotten** [comment]
@pYr0x 
> unfortunately ejs is deprecated and this is a "wont fix"

Your own documentation seems to disagree with that. http://canjs.com/docs/can.ejs.html clearly states that EJS "will still be maintained up to 3.0 and potentially after." That implies bugfixes will still be made.

Deprecation means you stop further development (of new features) and recommend people to switch over to a future-proof alternative, pending removal of the old system. It doesn't mean a free pass to ignore bugs that leave the old system in a broken state in lieu of the newest most shiny toy in the toybox.

**Comment by matthewp** [comment]
That's right, ejs is still supported, this isn't a "won't fix".

However bugs only get fixed if someone has time and energy to fix them. This is true of all features, new and old. Pull requests fixing this bug will of course be accepted.

It's also possible to sponsor a bug to ensure it gets fixed if you can't do it yourself, @justinbmeyer can speak more about how that can work in this case.

**Comment by rjgotten** [comment]
If you're willing to accept pull requests for bug fixes, I'll look into setting one up as I've I've managed to patch this issue locally already. (Wasn't that hard once I figured out where to look.)

Is it still a hassle to check out CanJS and all its dependencies via Git on Windows? I tried this once before in the v1.1 - v2.0 timeframe and it was really annoying having to deal with subrepositories back then.

**Comment by matthewp** [comment]
@rjgotten we don't use submodules any more, so it's much easier.  Just git clone and do an npm install.

**Comment by rjgotten** [comment]
@matthewp 
Done and done.

While the removal of subrepositories greatly simplfied things, you're indirectly using several native modules as dependencies. Those were an absolute pain in the rear to build (node-gyp and Windows is hell) but I eventually managed to skirt that minefield. Oh well. ^_^
