### ISSUE TITLE
Binding an undefined property to a component runs the setter

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2117]
In the following example, if the parent `bar` is undefined, the `foo` setter will run anyway. Maybe I'm wrong, but I don't think that's the right behavior. This is new in 2.3.3 and was not happening previously. It affects both 1-way and 2-way bindings using the new syntax (old binding syntax unaffected).

```html
<foo-bar {foo}="bar"></foo-bar>
```

http://jsbin.com/guweguqovi/edit?html,js,console

I just noticed that if the parent property is defined, the setter is run twice, which is strange for a 1-way binding, right? That is also new to 2.3.3.

**Comment by justinbmeyer** [comment]
I think setting the child to undefined is probably the right behavior.  If the child had a value, the one-way binding should probably overwrite it to `undefined`.

The double set is certainly a bug.  Will fix tomorrow.

**Comment by dylanrtt** [comment]
This popped up as an issue in places where an asynchronous virtual property's value is passed to a component where undefined is never expected, but perhaps it is the right behavior. I'll update my setters regardless of what you decide.

**Comment by pYr0x** [comment]
@dylanrtt my respect, nice work, you will find most of the bugs ;)
