### ISSUE TITLE
Possible 'infinite loop' bug when using can.Control.hookup and $.wrap

### ISSUE THREAD

**Issue by meconcomputer** [canjs/canjs#2120]
This issue appears when using `can/view/modifiers`, a Control that defines a `hookup` and a custom prototype `setup` (which uses `$.wrap` to modify `element`) e.g.
```javascript
  can.Control.extend('Test', {
    hookup: function(el) {
      return new this(el);
    }
  }, {
    setup: function(el, options){ 
        var newElem = $('<div/>');
      
        $(el).wrap(newElem);
        this._super.call(this, newElem, options);
    }
  });
```
The Control is called through an EJS template, e.g.
```javascript
<script id="templateEJS" type="text/ejs">
  <div><%= Test %></div>
</script>
```
   Basically, `$.wrap` called from a `Control.prototype.setup` is using the modified (through `can/view/modifiers`) `$.append`, which in turn calls `can.view.frag` (see `can/view/modifiers:54`).
   `frag` then uses `can.view.hookup` which generates an infinite loop.

   See http://jsfiddle.net/meconjs/kq9q6Lep/ as an example.

   Is this really a bug, or am I missing something?

**Comment by justinbmeyer** [comment]
@meconcomputer Thanks for reporting this.  The `modifiers` plugin isn't used much anymore so fixing this bug isn't priority.  I labeled it "needs a hero" which means that if you'd like to assist on a fix, we will work on it.  We can even setup a time to pair.  Thanks.

**Comment by meconcomputer** [comment]
@justinbmeyer Great to have a feedback.
  I always consider stability and flawless functionality in normal conditions (documentation based) as major attributes for a good framework. I chose CanJS because I sense it tends towards this.
  The way I see it there are two paths:
1. `modifiers` will still be considered an asset for the framework
2. in the near future, `modifiers` will be out of the framework
  If is still of interest, I am willing to fix it, but I need assistance, as I don't fully understand CanJS internals.

**Comment by justinbmeyer** [comment]
modifiers will be removed in 3.0.

if you want to work on it, we can setup a hangout (`justin@bitovi.com).  Just let me know when is a good time for you.
