### ISSUE TITLE
Cannot read property 'pop' of undefined 

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#2121]
2.3.3, 2.3.4
Uncaught TypeError: Cannot read property 'pop' of undefined .../node_modules/can/compute/get_value_and_bind.js 160 TypeError: Cannot read property 'pop' of undefined

I don't understand what is the case, but it allways worked, and it doesn't now.

```javascript
	ObservedInfo.batchEnd = function(batchNum){
		while( curDepth <= maxDepth ) {
			var cur = updateOrder[curDepth].pop(); //  here is the error
			if(cur) {
				cur.updateCompute(batchNum);
			} else {
				curDepth++;
			}
		}
		updateOrder = [];
		curDepth = Infinity;
		maxDepth = 0;
	};
```

if add check, there will be no error:
```javascript
var cur = updateOrder[curDepth] && updateOrder[curDepth].pop();
```

Last releases are full different of erros.

2.3.5 has already another errors...

**Comment by justinbmeyer** [comment]
Is this present in 2.3.5?

**Comment by justinbmeyer** [comment]
What code causes this? I need a breaking test case.

**Comment by whitecolor** [comment]
Well for now I'm not able to reproduce it on simple example, because it broke large app and have to figure out what part of it and what events cause this (it was always working fine in erlier versions).

In 2.3.5 I can not event test it because these issues:
https://github.com/canjs/canjs/issues/2122

**Comment by justinbmeyer** [comment]
Yes, the latest releases contain a big rewrite to fix compute and batching bugs. However, we will keep getting out releases quickly until everything is stabilized. Thanks for reporting.

**Comment by justinbmeyer** [comment]
I think I know how to reproduce.  Checking ...

**Comment by whitecolor** [comment]
Well  out a lot of events are intersecting that cause this: element custom trigged events and map's events within different components.
