### ISSUE TITLE
Uncaught TypeError: Illegal invocation and <content> issue

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#2122]
2.3.5 (latest master)

I'm not sure what causes it:

System reloader caught error: Uncaught TypeError: Illegal invocation /node_modules/jquery/dist/jquery.js 8458 TypeError: Illegal invocation
    at add (http://bb-reader-dev.127.0.0.1.til.io:2000/client/node_modules/jquery/dist/jquery.js:8458:41)

(probalbly these are different issues)
and another issue with this version
It seem that componets included in <content> do not get attributes passed from parent scope.

```javascript
tag: `comp1`
template: '<content/>'
modelView: {
 attr1: 1
}
```

```HTML
<comp1>
  <comp2 {attr2}="attr1"></comp2>
</comp1>
```

seem not to work attr2 is undefined in `comp2`

**Comment by justinbmeyer** [comment]
Can you write up an example. What you show works for me if I'm using stache

**Comment by justinbmeyer** [comment]
also, the example has `modelView` not `viewModel`

**Comment by justinbmeyer** [comment]
@whitecolor If you can get me an example soon .. I might be able to get a 2.3.6 out tomorrow with a fix for this an the other issue.  Thanks!

**Comment by justinbmeyer** [comment]
http://justinbmeyer.jsbin.com/wowome/edit?html,js,console,output shows that passing attrs works.

**Comment by whitecolor** [comment]
Well again I didn't reproduce it on small example it is just describing the case in big app, and there components inserted in <content/> do not get attributes passed.

**Comment by justinbmeyer** [comment]
I think #2139 will fix this.  I'm closing on that assumption.  Please re-open if you continue to find this problem.
