### ISSUE TITLE
Instantiation of controllers is slowing down the search widget

### ISSUE THREAD

**Issue by roger-ng-helloworld** [canjs/canjs#2125]
Hello,

I built this search widget: http://helloworld.com.au/l/cheap-domestic-flights

The loading time is alright on Desktop but it'll take 10 to 12 seconds to load on mobile. Basically, the widget comprise of 37 classes (some classes get instantiated more than 4 times). I found out the instantiation of classes are slowing down the loading time. Plus I'm using a lot can.Map and can.List.

One of the solutions I'm toying around is to merge some of the classes but that would be anti-pattern. I'm hoping I don't have to merge the classes. Is it expensive to use a lot of can.Map and can.List? My other solution is to consolidate some of the can.Map and can.List. 

Please help.

Rog

**Comment by justinbmeyer** [comment]
What version are you using? The latest CanJS is much faster than old versions.

**Comment by justinbmeyer** [comment]
Also, do you mean the creation of the classes themselves or do you mean instances of the classes?

**Comment by roger-ng-helloworld** [comment]
Hi Justin,

I'm using version 2.1.2 and I mean instances of classes. I seriously hope the instances of classes wouldn't cost that much because I'm not looking forward to merging some of the classes. Also, I'm using a lot of can.Map and can.List instances, would that be the reason why it's almost grinding to a halt on mobile?

Rog

**Comment by justinbmeyer** [comment]
2.3 is over-all much faster. Can you try upgrading?

Or, can you share the code that is running slow so I can experiment?

Are you listening to change events? Those are really slow.

**Comment by justinbmeyer** [comment]
Creating instances of Map and List is fast unless you are using them in certain situations. 

Another option, if you can't share the code, would be to hire us under contract to check it out.

**Comment by justinbmeyer** [comment]
@roger-ng-helloworld I'm going to close this until you get us a sample of the slow code.  Unfortunately, the site itself running in production minified is a bit difficult to figure out what's going on.
