### ISSUE TITLE
can.compute | NaN -> NaN dispatches a change event

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#2128]
https://github.com/canjs/canjs/blob/master/compute/proto_compute.js#L384

Currently `can.compute` fails to take into account the fact that `NaN !== NaN`, which causes computes to dispatch change events when their computed value remains `NaN`,

**Comment by justinbmeyer** [comment]
@rjgotten This should be a pretty easy fix.  Simply change the logic around:

https://github.com/canjs/canjs/blob/master/compute/proto_compute.js#L384

To check if `isNaN(newVal) ? ! isNaN(oldVal) : newValue !== oldValue`.

And add a test.
