### ISSUE TITLE
Export component scope to parent scope's map

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#2130]
This
```
<year-selector *year-selector />
```
Makes `{{*yearSelector}}` available in parent scope template, why not export `yearSelector` attribute to parent scope's map?

**Comment by matthewp** [comment]
I think this should do it:

<year-selector {^year-selector}="." />

**Comment by whitecolor** [comment]
No, why? `year-selector` here is a name of attribute of `year-selector` component.

**Comment by justinbmeyer** [comment]
Does {^.}="yearSelector" do it?

**Comment by whitecolor** [comment]
Yes it is! Thanks.

**Comment by pYr0x** [comment]
@whitecolor I tried my best to explain the binding, have a look http://canjs.com/docs/can.elementAndAttributes.html

**Comment by whitecolor** [comment]
@pYr0x that is ok, it was particular case I could guess that is should work this way.
question about `<can-import>`

`<can import from="helpers/stache-helpers"/>` says it imports helpers into the template, how this file should look like? Can I import something custom in to the scope?
let say `some/my/map.js`  module look like:

```javascript
export let someObject = {
 x: 1
}
```
How to get `someObject` in to the scope? I would think aboult something like that:
`HTML
<can import from="some/my/map" my-some="someObject"/>
`
so it imports and places `someObject` in to `mySome` attribute on the scope.

**Comment by matthewp** [comment]
@whitecolor here's an example of doing that: https://github.com/canjs/canjs/blob/master/view/import/import_test.js#L65

**Comment by whitecolor** [comment]
@matthewp 
Does `can-import` works as async `System.import` always? Can it be used like analogy of `import ...` statement?

**Comment by matthewp** [comment]
@whitecolor If the tag is self closing it is like `import ...`, if it contains children (light dom) then it acts like `System.import`.

### static

```
<can-import from="some/component"/>
```

### dynamic

```
<can-import from="some/component">
  {{#if isResolved}}
  <some-component/>
  {{/if}}
</can-import>
```

**Comment by whitecolor** [comment]
@matthewp is it possible to let know to upper scope that component was imported (loaded)? Maybe some event or attribute on `<can-import>`?

**Comment by whitecolor** [comment]
@matthewp `can-import` seem to fail to resolve the relative module, right?

and this:

```HTML
<can-import from="./some" {^value}="some"/>
```
seem to be not the same as:

```javascript
import some = './some'
can.Component({
  ...
  viewModel: {
    some: some
  }
}
```
because in second case `some` attribute has imported value while components init (and before template insertion), and in first case `some` attribute seem to be undefined while insertion. Am I correct?

**Comment by matthewp** [comment]
It should be able to resolve the relative module if you are loading the template with Steal, otherwise I think it will not.

That's right, the two examples are not exactly the same, bindings you add to a can-import will be applied asynchronously.
