### ISSUE TITLE
Incorrect view model context with <content/>

### ISSUE THREAD

**Issue by imjoshdean** [canjs/canjs#2137]
Between 2.2.9 and 2.3.0 and up, something changed with components that iterate over a list and render `<content/>` setting the context to be the outer template's context rather than the context within the current component.

An example of what is expected, and worked prior, can be found here: http://jsbin.com/fucokoqofu/1/edit?html,js,output

An example of what isn't expected happening as of 2.3.0 can be found here: http://jsbin.com/fucokoqofu/2/edit?html,js,output

An example of the issue still happening as of 2.3.6 can be found here: http://jsbin.com/yehupixoji/1/edit?html,js,output

A branch with a test in component_test.js is forthcoming.

**Comment by daffl** [comment]
Related #2092

**Comment by justinbmeyer** [comment]
We should close this one and move those fiddles into the other one.

I actually wrote a test and it didn't experience this problem. 

I'll checkout the bins.

**Comment by justinbmeyer** [comment]
Closing for the other issue.
