### ISSUE TITLE
Arithmetic not working with %index

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#2138]
Arithmetic such as `{{%index + 2}}` does not work in stache templates. `{{@index + 2}}` works as expected.

The right-most column in this example shows the unexpected behavior: http://jsbin.com/kahibegune/1/edit?js,output

**Comment by justinbmeyer** [comment]
There's a plus operator? I have no idea how the other one works?

**Comment by phillipskevin** [comment]
I don't know either. I updated that code to use a helper, but wanted to check in case this was intended to work.
