### ISSUE TITLE
Sub expression as named parameter

### ISSUE THREAD

**Issue by organic-scholar** [canjs/canjs#2140]
stache template with following experssion throws error Unable to understand expression.
```handlebars
{{ greet name=(uppercase username) }}
```
both greet and uppercase are helpers

**Comment by justinbmeyer** [comment]
This isn't valid syntax. Write it like:

> {{ greet name=uppercase(username) }}

**Comment by organic-scholar** [comment]
Thanks for quick response its working. but do you add support for follwing syntax.

```handlebars
{{ greet name=(uppercase username) }}
```
after all it is valid syntax.

**Comment by justinbmeyer** [comment]
@organic-scholar it's not valid stache syntax.  We decided we liked:

```
{{ greet name=uppercase(username) }}
```

more than the handlebars syntax.

**Comment by organic-scholar** [comment]
Please check this 
(http://jsbin.com/bopateq/1/edit?html,js,console,output)

i tried the above syntax its not working

**Comment by justinbmeyer** [comment]
@organic-scholar this works: http://justinbmeyer.jsbin.com/resipu/edit?html,js,console,output

**Comment by organic-scholar** [comment]
But right now we can't mix helper expression with call expression.

**Comment by justinbmeyer** [comment]
I'm pretty sure you can mix helper can call like: `{{#each foo(bar)}}`, but it seems that a helper hash doesn't work with a call expression like: `{{helper hash=call()}}`.  It's a bug we will fix for the next release.

**Comment by organic-scholar** [comment]
here is another example failing, this one with unnamed params.

http://jsbin.com/niseji/edit?html,js,console,output

**Comment by justinbmeyer** [comment]
Works: http://jsbin.com/xotunitoya/edit?html,js,console,output

So, their really isn't a problem. The confusion is that the results of call expressions are passed as computes to helper expressions.

Helper expressions get computes by default.

**Comment by organic-scholar** [comment]
but i think this behaviour is inconsistent beacuse we called the expression its is not  instead it is passed as compute.

**Comment by justinbmeyer** [comment]
Helpers are always passed a compute with any observable data. Even functions are converted to a compute. So it's consistent.
