### ISSUE TITLE
Move can/view/live into its own project

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#2154]
This could be a really nice library as a low-level way to bind Observables to DOM elements. Could even create an interface so that other types of observables than can.computes can be bound.

**Comment by justinbmeyer** [comment]
> Could even create an interface so that other types of observables than can.computes can be bound.

Probably not necessary b/c `can.compute` is an interface that allows other observables to become computes.

```
can.compute(initialValue, {
  on, off, get, set
})
```

**Comment by justinbmeyer** [comment]
What other use cases do you think people would want this?

**Comment by matthewp** [comment]
For projects that operate on raw DOM elements (like legacy jQuery projects) that still would want the benefits of live-binding. Also, other frameworks that use observables are doing essentially this.

**Comment by justinbmeyer** [comment]
done.
