### ISSUE TITLE
vdom innerHTML implementation should append a text node for script tags

### ISSUE THREAD

**Issue by DesignByOnyx** [canjs/canjs#2156]
The innards of the `innerHTML` implementation in vdom does this:

    ...
    var frag = parser.parse(""+html);
    this.appendChild(frag);

However, script tags contents are CDATA and should not be parsed as html.  Instead, a text node should just be appended with whatever content is given to it.

**Comment by DesignByOnyx** [comment]
The same should probably also be applied to STYLE tags. Please advise.

**Comment by justinbmeyer** [comment]
@DesignByOnyx would this also do the wrong thing if I did:

```js
var div = document.createElement('div');
div.innerHTML = "<script>var foo='bar';</script>";
```

Is `parser.parse(""+html)` aware of this rule?

**Comment by DesignByOnyx** [comment]
@justinbmeyer - I think the parser handles that properly already. I haven't tested it, but [this comment in the tokenizer](https://github.com/canjs/canjs/blob/master/view/parser/parser.js#L66) makes me think that it has been accounted for.

The reason this bug surfaced for me is because the react integration I am building uses a `<script>` tag, and internally react is using innerHTML to set the contents for the tag. This was not a problem until the contents contained some JSON data that contained a string like this: `"Foo<Bar"`. Adding spaces around the `<` fixed it, but unfortunately this is a trademarked name used by our client and the spaces cannot be there.
