### ISSUE TITLE
can.List.each iterates uninitialised values

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#2163]
From the `.forEach()` documentation: 

> ##### Description
> forEach() executes the provided callback once for each element present in the array in ascending order. *It is not invoked for index properties that have been deleted or are uninitialised (i.e. on sparse arrays).*

`can.List` DOES iterate uninitialised values: http://jsbin.com/jezabevira/edit?js,console

**Comment by mjstahl** [comment]
@akagomez This seems to actually be a bug in `can.each`.

https://github.com/canjs/canjs/blob/master/list/list.js#L769 (forEach on can.List)
http://jsbin.com/vuvusowosa/edit?html,js,console (updated with can.each use case)

**Comment by justinbmeyer** [comment]
closing for can-list issue.
