### ISSUE TITLE
can.viewModel mentioned in the navigation but not the root page contents

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#2165]
<img width="768" alt="screen shot 2016-01-04 at 4 54 59 pm" src="https://cloud.githubusercontent.com/assets/82166/12101764/6d075e0c-b304-11e5-95f5-03a97033ba24.png">

**Comment by justinbmeyer** [comment]
@akagomez please fix this tomorrow.  I can show you how if you need help.  Thanks!
