### ISSUE TITLE
{($value)} doesn't behave the same as can-value

### ISSUE THREAD

**Issue by marshallswain** [canjs/canjs#2167]
I'm don't think this is on purpose, but
{($value)} doesn't behave the same as can-value.
{($checked)} behaves the same.

Here's a JSBin demonstrating the behavior.
http://marshallswain.jsbin.com/vofiyi/edit?html,js,console,output

**Comment by pYr0x** [comment]
phillipskevin  and justinbmeyer talked about that in gitter 
https://gitter.im/canjs/canjs?at=56746e79b5777fb85ba4aa26

maybe it is the same problem as yours

**Comment by justinbmeyer** [comment]
value shouldn't behave the same as `can-value`.

**Comment by phillipskevin** [comment]
I think the confusion is just that the docs point you to use `{($value)}` in place of `can-value`: http://canjs.com/docs/can.view.bindings.can-value.html.

**Comment by justinbmeyer** [comment]
@phillipskevin Yep.  We should let people know that their choice of property/attribute matters with ({$value})

**Comment by phillipskevin** [comment]
Yep, and if there's a way to do radio buttons with the new binding syntax, we should add that too. When we discussed this before, @justinbmeyer, we decided the best way was to just use `can-value` for radio buttons.

**Comment by justinbmeyer** [comment]
If `type` was a property you wanted live-bound:

```
{$checked}="eq(%element.value, type)" ($change)="attr(type, %element.value)"
```

Something like that might work.  I'm not sure the first `%element.value` will work (but that can be fixed).

I've also thought about supporting:

```
{$checked}="eq(%element.value, type)" ($change)="type = %element.value"
```

or

```
{$checked}="eq(%element.value, type)" ($change)="type(%element.value)"
```

but both feel weird.

**Comment by marshallswain** [comment]
@justinbmeyer, why shouldn't $value behave the same as can-value?

**Comment by justinbmeyer** [comment]
@marshallswain Because `can-value`'s behavior was odd.  It didn't bind to `input.value` in checkboxes and radios. Instead it bound to the `checked` property.  `{($value})` is extremely consistent.

**Comment by justinbmeyer** [comment]
Closing for #2210
