### ISSUE TITLE
Parser is not allowing anchor tags as child of inline elements

### ISSUE THREAD

**Issue by DesignByOnyx** [canjs/canjs#2169]
I have content which looks like this:

    <p><span>Some text with an <a>anchor</a> in it</span></p>

but since the anchor is defined as a block element, it is getting converted to this:

    <p><span>Some text with an </span><a>anchor</a> in it</p>

The anchor element is an inline element, but per html5 spec it's the only inline element which allows block level children. The parser should take this into consideration. The "a" tag should be part of the "inline" set of elements ([not the "block" group](https://github.com/canjs/canjs/blob/master/view/parser/parser.js#L53)), and conditional logic should be used to prevent the "a" tag from being closed when a block element is encountered.

**Comment by justinbmeyer** [comment]
This is a reversal of another filed bug. I think the solution is to mark everything as block and require that people close all tags.
