### ISSUE TITLE
can.Map.keys is broken for complementary attributes added onto can.List lists

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#2173]
`can.Map.keys( map )` does not work properly on lists, even though getting/setting additional attributes works as expected and events properly dispatch to attached event listeners.

See: http://jsbin.com/hegozuwute/1/edit?html,js,console

It seems that, unlike `can.Map.prototype.___set`, `can.List.prototype.___set` does not update the backing private `_data` member of `can.Map` instances that the static `can.Map.keys` method builds upon.

(Infact, it seems like `can.List` instances do not have `_data` members *at all*, which is just weird...)

This can lead to unexpected problems with lists that carry additional members, e.g. for metadata purposes.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-list/issues/5
