### ISSUE TITLE
@index is double wrapped compute object in mustache/stache helper in latest version (V2.3.8)

### ISSUE THREAD

**Issue by lihan** [canjs/canjs#2179]
The ``@index`` is rendered as a number in mustache template, but is a double wrapped compute object in mustache helper, see this JSBin for illustration. http://jsbin.com/misawebeza/1/edit?html,js,output

I have traced this issue all the way back to V2.2.5, the first version that ``@index`` works correctly in mustache helper. Refer to this JSBin (http://jsbin.com/jovotareni/1/edit?html,js,output) If you change the canJS version to 2.2.6, you will see the broken result.

The same issue exists in both Mustache and Stache template.

Is there a suggested fix?

**Comment by justinbmeyer** [comment]
A breaking example in stache in 2.3.8: http://jsbin.com/patiho/edit?html,js,output

**Comment by justinbmeyer** [comment]
A workaround would be to make your helper check if it's still a compute and keep calling the compute.  We will look to have a fix soon.  Thanks for reporting.

**Comment by reno1979** [comment]
Ok same here, thank you for the milestone fix :)
