### ISSUE TITLE
canjs is not working with steal version 0.13

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#2180]
i want to update steal and steal-tools to 0.13. but the PR failed.
https://github.com/canjs/canjs/pull/2178

**Comment by matthewp** [comment]
Are you sure it's Steal and not jQuery? I know that there are currently issues with jQuery 2.2 that was released last week.

**Comment by pYr0x** [comment]
@matthewp the error is related to mocha.
https://travis-ci.org/canjs/canjs/jobs/101397873#L1603

what does this have to do with jquery 2.2?

@mjstahl do you have make some changes to the canjs core that fix the error on travis ci?

**Comment by mjstahl** [comment]
@pYr0x I am running through the tests right now. I have reason to believe that the error messages on Travis are misleading. We will soon see.

#2175 Updates jQuery to not depend on 1.12 or 2.2.0. Hopefully this fixes the problems we are seeing.  We will release that change (and some bugfixes with partials) for 2.3.9.  @justinbmeyer is working a compatibility change for jquery 2.2.0 and 1.12.0.

**Comment by mjstahl** [comment]
@pYr0x I think we can close this. #2175 is working just fine, and has all of the updates in it.

**Comment by pYr0x** [comment]
@mjstahl ok, maybe we can release this soon, to check if can-ssr will also pass the tests
