### ISSUE TITLE
can.Map throws when creating an instance that includes an array value.

### ISSUE THREAD

**Issue by m-mujica** [canjs/canjs#2182]
This is in can@2.3.9

```js
import Map from 'can/map/';
const bar = new Map({ foo: [1, 2, 3, 4] });
```

```
TypeError: List is not a function
    at Map.can.Map.can.Construct.extend.__type (http://localhost:3000/js/node_modules/can/map/map.js:323:14)
    at Map.can.Map.can.Construct.extend._set (http://localhost:3000/js/node_modules/can/map/map.js:302:28)
    at Map.can.Map.can.Construct.extend._setAttrs (http://localhost:3000/js/node_modules/can/map/map.js:489:12)
    at Map.can.Map.can.Construct.extend.attr (http://localhost:3000/js/node_modules/can/map/map.js:200:18)
```

my workaround was to import `can/list` along with `can/map`.

**Comment by matthewp** [comment]
Looking at the code it seems some effort was made not to make can/map depend on can/list, why is that @justinbmeyer ?

With that being the case I guess the solution is to check if can.List exists and not assume it does. Which would mean your arrays are not observable, probably not what you actually want.

**Comment by justinbmeyer** [comment]
Yeah, this isn't so much of an issue. I suppose we could leave arrays as arrays if List isn't imported.

**Comment by matthewp** [comment]
@justinbmeyer so why doesn't can/map depend on can/list?

I don't think silently making arrays non-observable is the way to go. We should at least provide a warning (I think an assertion is more appropriate).

**Comment by matthewp** [comment]
So it seems like maybe the reason it doesn't depend on can/list is to avoid a circular dependency. In that case I think an assertion is a good idea.

**Comment by m-mujica** [comment]
@matthewp assertion as in `steal.dev.assert`? throw an exception if `can.List` is not available?

If that's the case it feels odd to me, if the default behaviour we want is to make arrays properties observable we should just make sure `can.List` is available in `can.Map` and instead provide an option to prevent those arrays to be observables (which I think you can do using the define plugin already).

If we don't think it's an issue to change the default behaviour (before 2.3.9 you'd get observables from arrays by default) I guess warning is ok.

**Comment by justinbmeyer** [comment]
The reason why it's done this way is that it's good to build thing independently.  In 3.0, it will leave Arrays as plain Arrays unless can.List is imported.  

Closing for: https://github.com/canjs/can-map/issues/4
