### ISSUE TITLE
Server Side Rendering with can-ssr and the new binding syntax is not working

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#2185]
hallo,
i have tested can-ssr and made a simple example:

app.js
```js
import AppMap from 'can-ssr/app-map';
import route from 'can/route/';
import 'can/route/pushstate/';
import 'can/map/define/';

const AppViewModel = AppMap.extend({
  foo: "test"
});
route('/',{});

export default AppViewModel;
```

index.stache
```html
<can-import from="app" export-as="viewModel" />

{{*bar}}
<br/>
<input type="text" {($value)}="*bar"/>
```

package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "foobar",
  "main": "p.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "can": "git://github.com/canjs/canjs.git#master",
    "can-ssr": "^0.11.2",
    "done-autorender": "^0.6.0",
    "steal": "^0.13.0"
  },
  "system": {
    "main": "index.stache!done-autorender",
    "configDependencies": [
      "live-reload"
    ]
  },
  "devDependencies": {
    "steal-tools": "^0.13.2"
  }
}
```

the binding with the reference scope (see index.stache) is not working!
the can-server throw an warning ```WARN: can/view/stache/mustache_core.js: Unable to find key or helper "*bar".```

i can't also make this
```html
<input type="text" {$value}="foo"/>
```
no value is displayed.

**remember {{foo}} is "test" in the AppMap and {{foo}} is working outside the input**

**Comment by justinbmeyer** [comment]
Did you write your template correct? The input should be blank with {($value)}="*bar"

**Comment by justinbmeyer** [comment]
Instead of

{$value}="foo"

Do

value="{{foo}}"

**Comment by matthewp** [comment]
So you're expecting it to output something like `<input type="text" value="test">`?  I guess this is because can/view/bindings sets the value property and not the value attribute. But maybe it should when server-side rendered.  I think you probably want the placeholder attribute in this case though.

**Comment by pYr0x** [comment]
the expected behavior is not to have ```<input type="text" value="test">``` the ```{$value}="foo"``` was only a test that was also not working.

the expected behavior was to have an input field with a reference binding to ```bar```. that variable should be displayed before the input field. like the ```index.stache``` looks like.

@justinbmeyer what to you mean with
> The input should be blank with {($value)}="*bar"
```html
<input {($value)}="*bar"/>
```
??

@matthewp this example works fine: http://jsbin.com/cofoqamecu/edit?html,js,output

i want this behavior also with can-ssr

**Comment by justinbmeyer** [comment]
closing for the can-stache-bindings issue.
