### ISSUE TITLE
{{#if}} statement within partial gets displayed outside partial

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#2186]
If a template displays a partial under a certain condition (`showPartial` in my example), like: 

```js
  {{#if showPartial}}
    {{>mypartial}}
  {{/if}}
```

and then the partial also displays something based on another condition (`showHiddenSection`):

```js
<script id="mypartial" type="text/stache">
{{#if showHiddenSection}}
  <h4>Hidden Section of Partial</h4>
{{/if}}
</script>
```

It is possible to cause the hidden section to be displayed entirely outside of the partial.
Here is a GIF showing the hidden section repeatedly duplicated outside of the partial:

![partial-issue](https://cloud.githubusercontent.com/assets/5851984/12301895/1140d40a-b9e8-11e5-90ff-1d4101ef4815.gif)

And here is a JS Bin of the code: http://jsbin.com/zuvofuyuri/1/edit?html,js,output

**Comment by justinbmeyer** [comment]
Thanks @phillipskevin .  Anyway you can remove the use of the component and routing?  It will be probably ready for a quick insertion into a test at that point.  Thanks again.

**Comment by phillipskevin** [comment]
@justinbmeyer, here is a simplified example: http://jsbin.com/dizuxanide/edit?html,js,output.

If you point me to the right place, I can attempt to put in a test.

**Comment by justinbmeyer** [comment]
@phillipskevin It would be in `can/view/stache/stache_test.js`.  Ideally you shouldn't have to append it to the DOM like the vast majority of the other tests.

**Comment by justinbmeyer** [comment]
@phillipskevin I'd be interested if #2189 fixes it.  You might try to make that small change locally and see if your problem sticks around.

**Comment by phillipskevin** [comment]
@justinbmeyer the fix for https://github.com/canjs/canjs/pull/2189 doesn't resolve my issue. I should have time to submit a test for this tomorrow.

**Comment by phillipskevin** [comment]
@justinbmeyer the test is on this branch: https://github.com/canjs/canjs/tree/if-partial-if-2186.
