### ISSUE TITLE
Nested event batching dispatches in unexpected order

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#2187]
The problem looks something like this... 

```
// Start batch #1
// Trigger A
// Stop batch #1
// Handle A
  // Start batch #2
  // Trigger B
  // Stop batch #2
  // Trigger C
// Handle C <--- I would expect this to be "B" because it was triggered before "C"
// Handle B <--- I would expect this to be "C" because it was triggered after "B"
```

Here's a JSBin that demonstrates the issue: http://jsbin.com/fuwuvu/2/edit?js,console

It seems `event B` is being added to `batch #2` while `batch #1` is dispatching its events. When `batch #2` is stopped, `event C` is dispatched immediately because there is no `collectingBatch`. Or in other words, events aren't being queued because all batches (`batch #1` and `batch #2`) have been stopped. After `event A`'s handler is done, `batch #1` has no more events to dispatch and `batch #2` can begin dispatching its events, which includes `event B`.  

Judging by [this line in `batch.js`](https://github.com/canjs/canjs/blob/master/util/batch/batch.js#L119), this is the intended behavior... 

Okay, I just caught wind of `force=true` in the docs when fetching that link. That seems counter intuitive to me also. I'd expect that each batch is treated independently of one another. 

At this point I'm sure my expectations are broken. I'd love some help understanding the theory behind this API if you can spare the time @justinbmeyer.

**Comment by justinbmeyer** [comment]
Yes, this is a consequence of an `undefined` behavior when events are triggered outside of a batch within another batch being dispatched.

My guess is that if you changed your code to do:

```
// Start batch #1
// Trigger A
// Stop batch #1
// Handle A
  // Start batch #2
  // Trigger B
  // Stop batch #2
  // Start batch #3 
  // Trigger C
  // Stop batch #3
```

Everything would work fine.

One option might be to force any triggering of events to be part of a "solo" batch.   This would automatically dispatch C after B without having to wrap it with `start`/`stop`.

**Comment by justinbmeyer** [comment]
Closing for those can-event issues.
