### ISSUE TITLE
can.Map.keys dosent work with can.define

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/canjs#2193]
```can.Map.keys(map)``` return an empty array when attrs are defined with ```map-define``` plugin as demonstrated in this link http://jsbin.com/lediwa/edit?html,js,console,output

**Comment by dylanrtt** [comment]
I think a more precise description would be that virtual properties are not included in the output of `can.Map.keys(map)`. If the map has real properties, those will still be in the array.

What should the rules be for including virtual properties? This is where it could get tricky.

If you want to exclude keys with `undefined` value, unbound properties will have to be run when `keys(map)` is called. Furthermore, unbound async virtual properties may not resolve immediately, so if those are desired, maybe a promise should be returned?

One option would be to only include virtual properties that are already bound but I think that could be confusing, especially if you run `keys(map)` while an async property is still resolving and expect to be in the output array.

**Comment by justinbmeyer** [comment]
@cherifGsoul What problem is is this causing?  What's the use case for having a virtual property be returned by `keys`?  

I wonder there wouild be a high correlation with  `serialize: true` virtual properties and the properties you'd want to be present in `.keys()`

**Comment by cherifGsoul** [comment]
@justinbmeyer it was a question posted in gitter maybe users need it for some reason but the correlation between ```serialize``` and ```keys``` might be true

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-map-define/issues/5
