### ISSUE TITLE
Sort plugin breaks inheritance of .splice()

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#2196]
`Array.prototype.splice` is called:

https://github.com/canjs/canjs/blob/master/list/sort/sort.js#L379

It should use `oldSplice`: 

https://github.com/canjs/canjs/blob/master/list/sort/sort.js#L404

**Comment by rjgotten** [comment]
@akagomez 
Isn't it using the direct `Array.prototype.splice` in that location exactly because it's necessary to avoid the change events that `can.List.prototype.splice` triggers?

**Comment by akagomez** [comment]
I don't suspect so. Triggering "change" events is fine. Binding to them should be avoided. 

The sort plugin triggers "add" events in the same way `can.List.prototype.splice` does: 

https://github.com/canjs/canjs/blob/master/list/sort/sort.js#L382
https://github.com/canjs/canjs/blob/master/list/list.js#L334

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-list #35](https://github.com/canjs/can-list/issues/35) via [**ZenHub**](https://www.zenhub.com/)
