### ISSUE TITLE
With ($event)="expr()" syntax, provide default arguments for handlers

### ISSUE THREAD

**Issue by ramblinjan** [canjs/canjs#2197]
Currently there is no way to use the `($event)` syntax to call a handler with the default arguments (`element, event, scope, arguments...`).

Additionally, for custom event triggers, you lose the additional arguments with this syntax.

Proposal: 
- When you do `expr()`, the default arguments for handlers should be passed in.

**Comment by justinbmeyer** [comment]
> Currently there is no way to use the ($event) syntax to call a handler with the default arguments (element, event, scope, arguments...).

Yeah, you do:

```
($event)="method"
```

> When you do expr(), the default arguments for handlers should be passed in.

I don't think that should happen.  Sometimes methods check the number of arguments and you'll need a way to call an argument without any arguments.

I think we need an `%arguments` special key and a spread operator.

**Comment by justinbmeyer** [comment]
Closing for https://github.com/canjs/can-stache-bindings/issues/9
