### ISSUE TITLE
Current context can't be passed within a component that has leakScope: false

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2201]

**Comment by dylanrtt** [comment]
```html
<parent-comp>
  <child-comp {foo}="."></child-comp>
</parent-comp>
```

The context passed is the viewmodel of `<parent-comp>` even though it is `leakScope:false`. It should be the scope above `<parent-comp>`.

http://jsbin.com/sihogovema/edit?html,js,console

**Comment by justinbmeyer** [comment]
The following test passes:

```
		test("leakScope:false preserves context of parent", function(){
			can.Component.extend({
				tag: "outer-leak",
				viewModel: {
					tag: "outer-leak"
				}
			});
			can.Component.extend({
				tag: "inner-no-leak",
				template: can.stache("<content/>"),
				viewModel: {
					tag: "inner-no-leak"
				},
				leakScope: false
			});
			can.stache.registerHelper("getContext", function(c1, c2){
				equal(c1, c2, "same object passed");
				equal(c1.attr("tag"), "outer-leak");
			});
			var template = can.stache("<outer-leak><inner-no-leak>{{getContext . this}}</outer-leak><inner-no-leak>");
			template();
		});
```

**Comment by justinbmeyer** [comment]
@dylanrtt With a template, the scope is not leaked: http://justinbmeyer.jsbin.com/sihogovema/1/edit?html,js,console

Can you remind me again of why you would have a component without a template that you would not want to leak?

I'm not sure if this behavior is documented outside of the code: 

https://github.com/canjs/canjs/blob/master/component/component.js#L103

If it is documented (I'm on a very slow internet), then if this is a good change, it will have to wait until 3.0 to change it.  If it's not a documented behavior, we maybe be able to change it earlier.

**Comment by dylanrtt** [comment]
The pattern is a template-less logic component that wraps around a simple ui component. When the ui component's state changes, the logic component performs an action.

```html
<dropdown-listener {(selected)}="*selectedCommand">
  <dropdown-ui {items}="actionList" {(selected)}="*selectedCommand"></dropdown-ui>
</dropdown-listener>
```

This is the pattern that my coworker introduced for dropdowns and it has worked alright so far. There are certainly other ways to do this such as a custom attribute on the ui component that performs the logic, which I think I like better.

I suppose I could always add `template: can.stache('<content />')` as a workaround.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-component #94](https://github.com/canjs/can-component/issues/94) via [**ZenHub**](https://www.zenhub.com/)
