### ISSUE TITLE
createAttribute is deprecated

### ISSUE THREAD

**Issue by reno1979** [canjs/canjs#2205]
Firefox development version shows me : 

Use of document.createAttribute() is deprecated. Use element.setAttribute() instead.

(canjs version 2.3.11 ) 

```
setAttribute: function () {
                var doc = can.global.document;
                if (doc && document.createAttribute) {
                    try {
                        doc.createAttribute('{}');
                    } catch (e) {
                        var invalidNodes = {}, attributeDummy = document.createElement('div');
```

**Comment by justinbmeyer** [comment]
@reno1979 We do this because `setAttribute` doesn't support attribute names like `{foo}` in chrome.

**Comment by matthewp** [comment]
This is how I did it for web worker rendering: https://github.com/canjs/dom-patch/blob/master/src/setattribute.js#L22

**Comment by reno1979** [comment]
@justinbmeyer Ok I understand. Glad to see it added to the new milestone, thank you.

**Comment by daffl** [comment]
Bumping this to 2.3.13. We have been making at least weekly releases lately so this will still be fixed very soon.

**Comment by justinbmeyer** [comment]
I think this is fixed now ... we use innerHTML and then copy the attribute.
