### ISSUE TITLE
Route/Map triggering too many changes

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2206]
I'm not sure if this can be reproduced without the can.route. If I just use a map, this bug does not occur.

http://jsbin.com/pajewebezu/edit?html,js,console,output

```js
var appVM = new can.Map({});

can.route.map(appVM);
can.route.ready();

appVM.bind('action', function() {
  console.log('action change');
});

// triggers 'action' as expected
appVM.attr('action', 10);

setTimeout(function() {
  // unexpectedly triggers 'action' again
  appVM.attr('page', 'bar');
}, 100);
```

**Comment by justinbmeyer** [comment]
The reason for this is that the value is type coerced into strings: http://justinbmeyer.jsbin.com/megixa/edit?html,js,console,output

The only fix I can think of is that we overwrite `.__set` or maybe `.__type` on the route's map to automatically convert all values to strings.

**Comment by dylanrtt** [comment]
Ah, so if I set with `can.route.attr()` instead of directly on `appVM`, the problem is avoided. Good to know.

The 2nd bug is that if I use `can.route.attr()` with an object and no 2nd argument, it does not stringify the object's properties because it sees it as a read.

**Comment by dylanrtt** [comment]
I think the overriden `__type` function (and `can.route.attr()`) should ignore properties with `serialize:false` because there is no reason to stringify them, right?

**Comment by justinbmeyer** [comment]
@dylanrtt that's right.  I'm thinking about how this should work for 3.0.  My instinct is to simply have people default most properties to `type: "string"` like:

```js
var AppVM = DefineMap.extend({
  "*": "string",
  somethingNotInTheRoute: {
    type: "boolean",
   serialize: false
  }
})
```
