### ISSUE TITLE
jquery 2.2 in peer deps not supported

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#2207]
```
"jquery": ">=1.9.0 <1.12.0 || >=2.1.0 <2.2.0"
```

**Comment by daffl** [comment]
Fixed via #2208

**Comment by pYr0x** [comment]
@daffl @matthewp @justinbmeyer can we now update all canjs / stealjs and donejs repos to jquery 2.2?
for example can-ssr https://github.com/canjs/can-ssr/blob/master/package.json#L42

**Comment by justinbmeyer** [comment]
@pYr0x yes, it should be possible.
