### ISSUE TITLE
Document Form Examples for Stache

### ISSUE THREAD

**Issue by julia-allyce** [canjs/canjs#2210]
It would be nice to have a section in the stache documentation, dedicated just to forms with the new binding syntax.

For example:
- how to handle simple 2-way bound text inputs
- how to create an array of values from a group of checkboxes
- how to handle selects and multiselects etc, etc

Here are angular's docs for forms:
https://docs.angularjs.org/guide/forms

**Comment by pYr0x** [comment]
:+1:

**Comment by pYr0x** [comment]
we should document that behavior for checkboxes and radiobuttons... still confusing for users

**Comment by justinbmeyer** [comment]
We do for can-value. What is confusing specifically?

**Comment by pYr0x** [comment]
https://gitter.im/canjs/canjs?at=5705487bb12cb51618d29c3d

**Comment by justinbmeyer** [comment]
Closing for https://github.com/canjs/can-stache-bindings/issues/49
