### ISSUE TITLE
Set jQuery package version using Caret 

### ISSUE THREAD

**Issue by mihalycz** [canjs/canjs#2212]
When I try to set jQuery package version using caret  **("jquery": "^1.1.0")** then I receive warning message 
```javascript
WARN can@2.3.10 requires a peer of jquery@>=1.9.0 <1.12.0 || >=2.1.0 <2.2.0 but none was installed. 
```
And I see **1.12.0** version installed.

**Comment by matthewp** [comment]
Does jQuery even need to be a peerDependency any more? In DoneJS we installing with `donejs init`. In NPM3 peerDependencies aren't installed any more anyways, I'm thinking we can just move this to a dependency.
