### ISSUE TITLE
A "How to read our API docs" Doc ~3

### ISSUE THREAD

**Issue by julia-allyce** [canjs/canjs#2214]
I think having a dedicated page to explain how to read our API docs would really improve their usability or bring to light what we could do to improve them :)

It could explain the formatting and structure of our API docs, and how to read them.

We could explain things like:
What does this grey label mean?
What does the small text mean under the title?
What does it mean if there is a version tag next to it?
<img width="191" alt="screen shot 2016-01-25 at 1 10 26 pm" src="https://cloud.githubusercontent.com/assets/1000574/12559798/13c925a2-c365-11e5-8f4c-75e52f5ab60a.png">

What makes an item a top level menu item?
Whats the difference between prototype, static, and plugins?
<img width="309" alt="screen shot 2016-01-25 at 1 12 50 pm" src="https://cloud.githubusercontent.com/assets/1000574/12559875/9286c39a-c365-11e5-98c5-649293df69b8.png">

Whats this blue box at the top of every page?
How do I read the signature blocks?
<img width="750" alt="screen shot 2016-01-25 at 1 14 39 pm" src="https://cloud.githubusercontent.com/assets/1000574/12559881/a095c2c4-c365-11e5-9abb-c2b0ff9157dc.png">

What is this list at the top of the docs?
<img width="221" alt="screen shot 2016-01-25 at 1 16 08 pm" src="https://cloud.githubusercontent.com/assets/1000574/12559934/e9e25ae6-c365-11e5-82a7-3abc989c3167.png">

**Comment by chasenlehara** [comment]
https://canjs.com/doc/guides/api.html
