### ISSUE TITLE
Passing a compute to a component with ~ passes the value

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2216]
I should be able to pass a compute of a scope property to a component with `~`.

```js
var vm = new can.Map({ foo: 'bar' })
```

```html
<!-- should pass a compute of 'foo' instead of simply binding 'foo' -->
<foo-bar {compute}="~foo"></foo-bar>
```

http://jsbin.com/diginariwa/edit?html,js,console

I'm not really sure what a 2-way binding would look like or if it should even be possible.

**Comment by justinbmeyer** [comment]
closing for issue in can-stache-bindings
