### ISSUE TITLE
can.Map constructor is observable

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2220]
If I define a compute that returns a `new can.Map()`, changes to the map cause the compute to re-execute.

http://jsbin.com/suxayikepu/edit?js,console

```js
var c = can.compute(function() {
  return new can.Map();
});

c.bind('change', function(){});

var map = c();

// recomputes c
map.attr('foo', 'bar');
```

Shouldn't the compute in this example only ever be evaluated once? It appears to be binding to its own return value.

**Comment by justinbmeyer** [comment]
Yes. Seems like a bug.

**Comment by justinbmeyer** [comment]
my best is there is a call to call `can.Map.keys` somewhere during init that shouldn't be there.

**Comment by dylanrtt** [comment]
Yeah, this doesn't happen with just a compute, so it's a can.Map init issue.

I can do this as a workaround:

```js
var c = can.compute(function() {
  var map;
  can.__notObserve(function() {
    map = new can.Map();
  })();
  return map;
});
```

Tracing was pretty easy. During setup, it sets the data (an empty object in this case) and that eventually leads to `can.each` which calls `keys()`. I don't know enough about the internals of the framework to know whether adding __notObserve somewhere in the chain would be preferable or maybe something else.

**Comment by rjgotten** [comment]
> During setup, it sets the data (an empty object in this case) and that eventually leads to can.each which calls keys(). I don't know enough about the internals of the framework to know whether adding __notObserve somewhere in the chain would be the best solution as opposed to something else.

The problem is that `Map.prototype._setAttrs` uses `Map.prototype.each`, which is observed, instead of `Map.prototype._each`, which is not observed, when iterating over its current values.

I'd say this is a general bug with tripping an observer hook during the `map.attr({ ... })` method signature that just so happens to also surface as part of the constructor. Setters are never supposed to be observed, right? Just getters...

**Comment by justinbmeyer** [comment]
@rjgotten Yeah, setters shouldn't be observable.  Going to work on a fix now.  Thanks!
