### ISSUE TITLE
console.log.apply not supported on IE11?

### ISSUE THREAD

**Issue by meconcomputer** [canjs/canjs#2227]
Hi guys!
   When using I'm getting a wired 'Object doesn't support this action' error in [can/util/can.js, `_logger` function](https://github.com/canjs/canjs/blob/master/util/can.js#L264)
   For me, the fix was to replace the `if-else` with a `try-catch`.

**Comment by rjgotten** [comment]
@meconcomputer

In IE `console` is a host object and its methods are not true JS functions that descend from `Function`.
Therefore `console.log` has neither a `call` nor an `apply` method.

You can get a cross-browser compatible implementation via a little trick where you 'apply call', e.g. ,

```js
_logger : function( type, arr ) {
  if (( "console" in window ) && ( type in console )) {
    var call = Function.prototype.call;
    call.apply( call, [ console[ type ], console ].concat( arr ));
  }
}
```

**Comment by meconcomputer** [comment]
Agree. But doesn't this mean that `_logger` should be "officially" patched on `master` also?

**Comment by rjgotten** [comment]
It does.

**Comment by meconcomputer** [comment]
Integrated in 2.3.14
