### ISSUE TITLE
Warn: "trying to pass class as an attribute into a component"

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#2228]
```HTML
<bmi-slider class="{{result}}"/>
```
Got in the console:
```
WARN: can/component: looks like you're trying to pass class as an attribute into a component, but it is not a supported attribute
```

What is wrong with setting class name this way?

**Comment by matthewp** [comment]
Aside from the warning, is the class name not applied?

**Comment by whitecolor** [comment]
Applied ok of cource. Just strange warning.

**Comment by matthewp** [comment]
The warning is for when people want to set the `class` property on the child component's viewModel.

**Comment by whitecolor** [comment]
I understand, but it is not the case I belive?

**Comment by matthewp** [comment]
What is not the case?

**Comment by pYr0x** [comment]
i think with the new binding syntax this can be deprecated in the future?

**Comment by whitecolor** [comment]
I would understand this warning (single curle bracket):
```
<bmi-slider class="{result}"/>
```

**Comment by marshallswain** [comment]
I encountered this same thing last night.  I set a class with a dynamic value on a component, but I wasn't trying to pass it in, just use it.  It worked as expected, but the error message confused me and I back-tracked through all of the code I had written to figure out where I had done what it says.  I finally assumed it was from doing `class="{{result}}"` on a few components.

**Comment by justinbmeyer** [comment]
closing for can-stache-bindings issue.
