### ISSUE TITLE
Stache parser creating incorrect output

### ISSUE THREAD

**Issue by ccummings** [canjs/canjs#2229]
Fiddle: http://jsfiddle.net/qYdwR/2600/

I would expect that to render:

```html
<div>1.disabled=“disabled”</div>
<div disabled=“disabled”>2. test</div>
```
But it instead renders:

```html
<div>1.disabled=“disabled”</div>
```

**Comment by justinbmeyer** [comment]
https://github.com/canjs/canjs/blob/master/view/parser/parser.js#L300 is almost certainly where the error is.  It should probably be counting starting `#`, `^` and ending `/` sections.

**Comment by akagomez** [comment]
Simplified example: http://jsbin.com/lurunep/edit?html,js,output
