### ISSUE TITLE
Define getters run twice. setVal is missing on first run.

### ISSUE THREAD

**Issue by marshallswain** [canjs/canjs#2230]
With the latest version of Can, all of my define getters are getting run twice.  On the first run, `setVal` is absent.  On the second, it is present.

See this [JSBin](http://jsbin.com/ruvako/edit?html,js,console,output)

```
can.Component.extend({
  tag: "home-page",
  template: can.view('home-template'),
  viewModel: {
    define: {
      names: {
        get(val, setVal){

          console.log('ARGUMENT COUNT:' + arguments.length);

          // This check is now necessary
          if (setVal) {
            console.log('There you are, setVal!');
            return val;
          }
          
          console.log('no setVal');
          return [];
        }
      }
    }
  }
});

```

**Comment by daffl** [comment]
Is that bound to a select field?

**Comment by marshallswain** [comment]
Not in the JSBin: http://jsbin.com/ruvako/edit?html,js,console,output

It's simply
```
{{names}}
```

**Comment by dylanrtt** [comment]
Here is a simpler example:
http://jsbin.com/qayicihipa/edit?html,js,console,output

It doesn't seem to happen when you bind directly to the map before the stache binding.

**Comment by justinbmeyer** [comment]
This is due to the `return readButDontObserveCompute(computedAttr.compute);` added in #1915.

**Comment by justinbmeyer** [comment]
Instead of the solution for #1915, we should probably observe on the compute and not on the property itself.  Basically flip the behavior around.  Perhaps `__get` should check if it's a computed property and not call `can.__observe` around here: https://github.com/canjs/canjs/blob/minor/map/map.js#L246

**Comment by justinbmeyer** [comment]
A more simple test would probably have something like:

```
c = can.compute(function(){
  return m.attr("p");
})
```

Where `p` is a async defined property on map `m`.

**Comment by daffl** [comment]
Caused by #2224
