### ISSUE TITLE
Download links broken

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2231]
https://gitter.im/canjs/canjs?at=56b12800dc33b33c75497595

http://canjs.com/guides/Tutorial.html#observables

**Comment by justinbmeyer** [comment]
This is working now.  Something must be wrong with our build that it sometimes forgets to run this script.

**Comment by daffl** [comment]
This is fixed now. The reason why it was flaky was that the zip files were built when `canjs/canjs` master got updated but not after changing `bitovi/canjs.com` after a release. They now run every time.
