### ISSUE TITLE
can.Map.backup plugin should use serialize() instead of attr()

### ISSUE THREAD

**Issue by alexisabril** [canjs/canjs#2234]
Using serialize will allow the backup plugin to follow rules specified in a define declaration. Currently we use attr() which will return all properties, even if serialize: false exists in a define statement.

**Comment by gsmeets** [comment]
This could be a pretty big breaking change to be honest.
I use serialize overwrites to ensure certain stuff doesn't get back to the server, doesn't mean I don't want the backup plugin to handle it though.

Isn't this something you'd want to enable optionally?

**Comment by alexisabril** [comment]
@gsmeets Late response from me! This issue got buried a bit.

That's a valid point. The question becomes: Should `define` control what is backed up?

For custom serializers to become a problem in this regard, it would need to be a situation such as:

```
const item = Map.extend({
	define: {
		name: {
			serialize() {
				return 'foo';
			}
		}
	}
});
```

In this case, no matter what `name` is set to using `attr()`, `serialize()` will always return `foo` and `isDirty()` will be false. However, I'm having trouble thinking of other scenarios where this could cause an issue.

Just some background info, the backup plugin was always meant to use `serialize()`, this was originally a typo.

**Comment by alexisabril** [comment]
Thinking about this a bit more, there could be more scenarios where this causes issues. I'll bring this up at the next OS meeting.

For instance, the restore value would be the serialized value, which may not be what you're looking for. That may also touch on a missing, corresponding type converter.

**Comment by justinbmeyer** [comment]
closing for issue in can-map-backup
