### ISSUE TITLE
Possible improvements to named constructor functions

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#2237]
I noticed that `can.Construct` uses a little trick with `eval()` gated with a `//!steal-remove` build pragma to achieve its named constructors in dev builds:

```js
var constructorName = shortName ? shortName.replace(/;/g, '') : 'Constructor';
eval('Constructor = function ' + constructorName + '() { return init.apply(this, arguments); }');
```

That would be a nice feature to have for regular builds as well, but `eval()` has several performance problems so it's kind of unjustifiable. However, there's an alternative with the `Function` constructor that works very well and comes without the bulk of the performance impact:

```js
var namedCtor = (function(cache){
  return function(name, fn) {
    return ((name in cache) ? cache[name] : cache[name] = new Function(
      "__", "function "+name+"(){return __.apply(this,arguments)};return "+name
    ))( fn );
  }
}({}));

/* [ ... ] */

var constructorName = shortName ? shortName.replace(/;/g, '') : 'Constructor';
var Constructor = namedCtor( shortName, init );
```

Generating and using a parametrized non-closure-dependent function like this prevents poisoning the surrounding environment and allows most compiler optimizations to continue to go through. With minimal performance impact, this is a viable solution for named constrcutors in production or for application developers that don't care to install a special dev build.

(Note that this solution also uses a function declaration instead of a named function expression. You avoid issues with named function expressions in old IE versions that way. The generated function factories are cached because you may have subclasses re-using the same name, e.g. classes that inherit from `can.Map` but which don't set a new `shortName`.)

I can set-up a pull request if there is interest in improving the named constructors feature in this way.

**Comment by matthewp** [comment]
Is new Function really more performant that eval? I wonder why that is.

**Comment by justinbmeyer** [comment]
@matthewp it doesn't have a scope.

@rjgotten after a quick read, yes this seems like it would be nice.  I'd like to see the difference between this and how non-evaled code currently performs.  But even it was big, the real-world cost would probably be pretty low.

**Comment by rjgotten** [comment]
> @matthewp 
> Is new Function really more performant that eval? I wonder why that is.

Because it constructs an isolated function in the global scope. You don't have the possibility of outer functions' closure scopes influencing the function or vice-versa. Normally, to perform a lot of code optimizations safely, a JS compiler needs to be able to do static code analysis to figure out how to cope well with closures. Straight-up `eval` makes that impossible, but the isolation of `new Function` means it is *not necessary* to be able to still apply a great deal of optimizations.

> @justinbmeyer 
> I'd like to see the difference between this and how non-evaled code currently performs

While I don't have a testcase at hand, [testing by Modus Create](http://moduscreate.com/javascript-performance-tips-tricks/) at one point showed `new Function` can be 50x faster than `eval`. And iirc one of the Chrome dev people once held a presentation regarding the internals of V8 stating that it could make up to a 100x difference.

**Comment by justinbmeyer** [comment]
Sorry, I mean I'd like the code as it is right now when eval is removed compared to new Function. Right now eval only exists in dev so I don't care about its performance. I do care about performance of "production" CanJS. 

My assumption is that new Function is going to add another function call and be slightly slower overall.

**Comment by rjgotten** [comment]
Sure. I guess it'll be easy enough to build a perf-test for this: just take an array of a few thousand elements to convert to `can.Map` instances and compare the construction time with and without the named constructor added via `new Function`, right?

I'll try to set some time aside next Monday to concoct something and get you some numbers.

**Comment by rjgotten** [comment]
@justinbmeyer 
Ok. This is going to take some more time. I actually have a perf test case that I can run via jsPerf, but an asinine security service of Cloudflare sitting atop of jsPerf keeps flagging the test and keeps refusing it.

**Comment by rjgotten** [comment]
@justinbmeyer 

https://jsbin.com/decuzunowe/edit?html,js,console

The results may surprise: the *named* extend using the Function constructor is actually *faster* than the unnamed extend. o_O

**Comment by justinbmeyer** [comment]
@rjgotten this is great!  I'm moving the issue to `can-construct`.  I'd love to see a pull request land there if you have the time.  Thanks.
