### ISSUE TITLE
../ looks up wrong property on maps

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2244]
Seen in 2.3.14 (working in 2.3.13), if I use `../` or something similar to read an ancestor scope, the result is undefined.

http://jsbin.com/rayolokeho/edit?html,js,console,output

```html
{{#each people}}
  <foo-bar>
    <!-- logs undefined, should log the person -->
    {{log ../}}
  </foo-bar>
{{/each}}
```

**Comment by dylanrtt** [comment]
This was caused by #2219.

The can.compute 'map' reader ([compute/read.js#L155](https://github.com/canjs/canjs/blob/18e5e755f0a6147f2a88b6d8e877efdb716f1d20/compute/read.js#L155)) previously would return the context with `map.attr('')` but that now looks for a property keyed with an empty string.

I also think that this should return the map rather than the object (always thought that was a bug).

**Comment by justinbmeyer** [comment]
@dylanrtt 

> I also think that this should return the map rather than the object (always thought that was a bug).

What is `that`? I'm not sure what you mean.

**Comment by dylanrtt** [comment]
> What is that? I'm not sure what you mean.

I mean `../`, not `map.attr('')`.
