### ISSUE TITLE
Canjs dropdown does not pick the selected value

### ISSUE THREAD

**Issue by amitbikram** [canjs/canjs#2245]
http://jsfiddle.net/qYdwR/2609/

in this selected value is 'Payal' but is is not selected in view

**Comment by justinbmeyer** [comment]
@amitbikram Just a heads up, EJS is no longer actively supported.  We'll accept bug fixes, and even help you debug them (if you want to pair over skype or google hangout).  But we aren't devoting resources to EJS.  

Please let us know if you'd like to pair on fixing this, or need help in the right direction.  

Closing and marking as "needs a hero"

**Comment by amitbikram** [comment]
@justinbmeyer It looks like this issue is not limited to EJS. I found the same issue with Mustache also. Below is the link for that.
http://jsfiddle.net/S3kVm/15/

**Comment by justinbmeyer** [comment]
Mustache is also deprecated.  Please switch to stache.  If the bug happens there, we will fix it asap: https://canjs.com/docs/can.mustache.html

**Comment by amitbikram** [comment]
It works great with stache but I am working on a project which uses EJS and changing the the templating engine at this point of time does not look feasible. I have a fix ready for this and make a pull request.

**Comment by amitbikram** [comment]
@justinbmeyer I have have a pull request for this. When would would it be available if the fix looks good?

**Comment by justinbmeyer** [comment]
Probably in a week or 2.

**Comment by marshallswain** [comment]
Or right away if you install from github. ;)
