### ISSUE TITLE
Form reset won't work with two-way bindings on elements. w/ CanJS 2.3.15

### ISSUE THREAD

**Issue by marshallswain** [canjs/canjs#2249]
Form elements with two way value bindings (using either the old `can-value` or new `{($value)}` syntax) do not reset when a form's reset button is clicked.

Here's an example JSBin with the *old syntax*: http://jsbin.com/hobolo/6/edit?html,js,output
Here's an example with the *new syntax*: http://jsbin.com/hobolo/3/edit?html,js,output

In the new version of Can, do these exist as a single implementation in the code?  Meaning, does can-value use the same code as the new value bindings?

It looks like this has worked in the past.  Here's the same JSBin with can@2.3.4
http://jsbin.com/hobolo/5/edit?html,js,output

**Comment by marshallswain** [comment]
select boxes are working fine.  So far it's only an issue with text inputs.

**Comment by marshallswain** [comment]
Checkboxes work, too: http://jsbin.com/hobolo/6/edit?html,js,output

**Comment by jandjorgensen** [comment]
Fixed in branch in #2302 except in amd with dojo--will bug someone later for help with that
