### ISSUE TITLE
`Type` in a component’s VM doesn’t work correctly with lists

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2250]
If a `can.Component` has a `define` property that’s `Type` is a `can.List`, and that `can.List` has a `Map` type, and that `can.Map` has `define` properties, then those properties should be available on instances of the items within the list. For example:

```
var Item = can.Map.extend({
  define: {
    prop: {
      get: function() {
        return 'define prop';
      }
    }
  }
});

var Collection = can.List.extend({
  Map: Item
}, {});

var collectionInstance = new Collection([{}]);
collectionInstance[0].attr('prop');// Returns “define prop”

var homeTemplate = can.view.stache('<p>{{vmProp}}</p>');

can.Component.extend({
  tag: "home-page",
  template: homeTemplate,
  viewModel: {
    define: {
      collection: {
        Type: Collection
      },
      vmProp: {
        get: function() {
          var collection = this.attr('collection');
          return collection[0].attr('prop') || 'no prop';
        }
      }
    }
  }
});

var appTemplate = can.view.stache('<home-page collection="{collection}" />');

$("body").html(
  appTemplate({
    collection: [{objectProp:'object prop'}]
  })
);

// Body should have “define prop” but instead has “no prop”
```

Works in 2.2.9 (“define prop” is output): http://jsbin.com/cocarikefo/1/edit?html,js,output

Doesn’t work with latest (“no prop” is output): http://jsbin.com/rufavacera/1/edit?html,js,output

**Comment by justinbmeyer** [comment]
@chasenlehara is a component necessary?  Does it work if you simply `.attr("collection", [{objectProp:'object prop'}] )`

**Comment by chasenlehara** [comment]
Yeah, unfortunately the most simple case works, but it fails when a component is involved.
