### ISSUE TITLE
Batched change notifies child component before parent stache binding

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2252]
This bug was introduced in 2.3 (absent in 2.2.9), and is still present in 2.3.15.

``` html
{{#eq page 'view'}}
  <foo-view page="{page}"></foo-view>
{{/eq}}
```

If `<foo-view>` binds to `page`, and `page` is changed in a batch, it seems the component is notified of the change before the stache binding. The stache binding _should_ be called back first to remove the component and hopefully prevent the other batched event from running (however that works).

http://jsbin.com/xeqosawako/edit?html,js,console,output

**Comment by justinbmeyer** [comment]
There's an issue keeping this for 3.0.  Essentially, live-binding relied on a synchronous notification of `removed` events to teardown the bindings.  

In 3.0, for performance reasons, I was hoping to use MutationObservers to know when elements are added or removed.  MutationObservers dispatch at the next turn.

I'm going to try to come up with a way for this to work without having to resort to synchronous `"removed"` events.

**Comment by justinbmeyer** [comment]
actually, listening to nodeLists teardown should work.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-stache-bindings #278](https://github.com/canjs/can-stache-bindings/issues/278) via [**ZenHub**](https://www.zenhub.com/)
