### ISSUE TITLE
Publish changelog for 2.3.15

### ISSUE THREAD

**Issue by marshallswain** [canjs/canjs#2253]
https://canjs.com/guides/changelog.html

**Comment by daffl** [comment]
They're literally the same except for an NPM bugfix. You are right though, it should probably show up in the changelog.

**Comment by matthewp** [comment]
Do we really need to be publishing patch changelogs? If it's any amount of work to do I'm not sure it's worth it.

**Comment by marshallswain** [comment]
I feel like it really helps me to quickly catch up on what actually makes
it into each release. As an early adopter, I have a better idea of what to
expect when I keep upgrading to the latest version. As a bug reporter it
helps me feel like I have a better idea of what to watch for, or where to
look first when I encounter a new problem. So, I really appreciate the
detailed change log. I do try to read every issue that hits the repository,
but having this info all in one timeline is really nice.

**Comment by chasenlehara** [comment]
@matthewp I’d like to echo @marshallswain’s comment. If I’m experiencing a bug and I can narrow it down between two versions, looking through the changelog can give some indication of what might’ve caused the bug.
