### ISSUE TITLE
CanJS Live Binding with lazy load of Components Not working

### ISSUE THREAD

**Issue by pravin-d** [canjs/canjs#2254]
Please also see 
http://stackoverflow.com/questions/35339151/canjs-live-binding-with-lazy-load-of-components-not-working

Basically I have stache with #is or #if and #else, each containing a custom tag. I want to load the custom tag only when the tags become visible or are rendered. I'm using headJS to load the components.
eg.
{{#if tag1}}
<custom-tag1><custom-tag1>
{{/if}}
{{#if tag2}}
<custom-tag2><custom-tag2>
{{/if}}
Based on a click or condition tag1 or tag2 might change state. Using a listener I will fetch the can.Component for the appropriate tag (if not yet fetched)
This does not seem to be working.
Any Help?

**Comment by matthewp** [comment]
Yeah, the components must be registered when the template is parsed. You can work around this using a custom element and doing:

```js
{{#show}}
  <content/>
{{/show}}
```

```js
<only-show-if show="tag1">
  <custom-tag1></custom-tag1>
</only-show-if>
```

However... we already have [<can-import>](https://canjs.com/docs/can%7Cview%7Cstache%7Csystem.import.html) for exactly this purpose. It doesn't work with HeadJS though, are you married to using that library?  can-import works very nicely with [stealjs](http://stealjs.com/)

**Comment by justinbmeyer** [comment]
Templates don't have to be registered. At parse time.  The tags just need to have a hyphen.

**Comment by pravin-d** [comment]
@matthewp 
Had a quick read about stealjs and related docs. Would need some time to understand it properly.
 I'm a little confused about your example. Before setting show='tag1' I need to still check if the component is registered or not right ?

**Comment by matthewp** [comment]
@pravin-d sounds like i was wrong, try with putting a hyphen in.
