### ISSUE TITLE
can.view.preload docs could use improvement 

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#2269]
The docs for can.view.preload can only be found by hitting this URL directly: https://canjs.com/docs/can.view.preload.html

Also, a usage example would be very helpful.

**Comment by justinbmeyer** [comment]
@phillipskevin preload probably isn't needed in a modern / donejs application. What are you using it for?

**Comment by phillipskevin** [comment]
@justinbmeyer I've only seen it being used to load templates that are being used as partials. I'm not sure why it was done that way.

[This question on gitter](https://gitter.im/canjs/canjs?at=56c1e504fa79226456fa7bbe) led me to look up the docs again to see if can.view.preload would help. That's when I had trouble finding the docs. Also, once reading them I really wasn't sure if it was applicable in the situation.

**Comment by justinbmeyer** [comment]
gone in 3.0.
