### ISSUE TITLE
Infinite batching

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2272]
Introduced in 2.3.11. Still present in 2.3.16/latest.

```html
{{#if show}}
  <select multiple {($value)}="foo"></select>
  <select multiple {($value)}="bar"></select>
{{/show}}
```

If `show` is changes to truthy in a batch, some kind of infinite batch occurs when the selects are inserted.

2.3.11 mostly had changes to batching, so I'm not sure how the multiple selects play into it. The test requires both to be present and both to be 'multiple', so it needs some narrowing down.

It does not happen if I use `can-value` instead of `{($value)}`. Aren't they supposed to be the same for select elements? (I understand they are not the same for some form elements.)

http://jsbin.com/basowirasa/1/edit?html,js,output

**Comment by justinbmeyer** [comment]
In 3.0, we should make setting a compute not return the new value of the compute.  This will greatly simplify computes behavior and make situations like this less common.

**Comment by justinbmeyer** [comment]
Ok, I discovered the cause.  With the new batching system, any use of `can.batch.after` needs to be part of the batch that it is trying to hook into.

```
can.batch.start();

// MAKE CHANGES
can.batch.after(function(){
  // do stuff when current batch has completed
})
can.batch.stop();
```

Previously, this would hook into the "last batch" which wasn't necessarily the batch that we actually might have just created.
