### ISSUE TITLE
Add issue & pull request templates

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2273]
I think it would be useful to have [issue and pull request templates](https://github.com/blog/2111-issue-and-pull-request-templates) that define what details the team needs.

**Comment by matthewp** [comment]
Doesn't this feature assume every issue is a bug?

**Comment by chasenlehara** [comment]
I think it’s assuming that at least 50% of the issues created are the same type and would benefit from having a template available. Looking at the issues list, I think a majority of them would find a template that asks for a description, steps to reproduce, expected results, actual results, links, and version info useful. If you start filing a new issue that doesn’t make sense with the default template, it’s pretty easy to delete everything and start from scratch.

**Comment by chasenlehara** [comment]
Closing in favor of https://github.com/donejs/developer-relations/issues/15
