### ISSUE TITLE
Whitespace Control?

### ISSUE THREAD

**Issue by Schweinepriester** [canjs/canjs#2284]
If not yet supported, please support whitespace control like Handlebars: <http://handlebarsjs.com/expressions.html#whitespace-control>

My use case: `:empty` pseudo selector, which does not match

```
<div> </div>

<div>
  <!-- test -->
</div>

<div>
</div>
```

Background:
- <https://css-tricks.com/almanac/selectors/e/empty/>
- <http://thenewcode.com/692/Vanishing-Acts-The-CSS-empty-Selector>
- <http://codepen.io/katydecorah/post/a-case-for-empty>
- <https://stackoverflow.com/questions/15953293/handlebars-whitespace-control> ⇒ <https://github.com/wycats/handlebars.js/pull/336>

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-stache/issues/60
