### ISSUE TITLE
CanJS cannot be live reloaded

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#2285]
If you modify a file like `can/util/vdom/vdom` it will cause the parents to be reloaded and `can.view.Scope` becomes undefined. Need to investigate further.

**Comment by justinbmeyer** [comment]
Live reload works.  I assume you mean live-reload while keeping the state?

**Comment by matthewp** [comment]
This was the bug where you could not edit canjs code inside node_modules and have that code be reloaded. It's probably not an issue any more in 3.0, so closing this.
