### ISSUE TITLE
Properties with undefined value in can.route.attr(obj) are ignored instead of removed

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2287]
A feature of `can.Map` is that if you call `attr()` with an object as the first argument (and no 2nd arg), all properties of the object that are defined with `undefined` value will be removed from the map.

This does not currently work with `can.route.attr()` and the associated backing map due to the recent stringification changes.

The issues seems to be that [`can.extend()`](https://github.com/canjs/canjs/blob/4537ba7ca2901434d4e6f68960ffc923bfbe45aa/route/route.js#L68) removes properties with `undefined` value.

@nlundquist

**Comment by justinbmeyer** [comment]
> A feature of can.Map is that if you call attr() with an object as the first argument (and no 2nd arg), all properties of the object that are `undefined` will be removed from the map.

Only if you call a map like `map.attr(VALUES, true)` do `undefined` properties in `VALUES` get removed from `map`.

Unless you are talking about properties like `{prop: undefined}` where the property is actually defined, but it's value is undefined.

**Comment by dylanrtt** [comment]
Yes, I am talking about `{prop: undefined}` properties.

**Comment by justinbmeyer** [comment]
closing for P1 issue in `can-route`
