### ISSUE TITLE
routeUrl helper, merge option not working

### ISSUE THREAD

**Issue by gmahomarf** [canjs/canjs#2291]
I'm trying to use `{{routeUrl(page='home', true)}}` to change only the page attribute in my route, but it's not working. Debugging shows that when we call the helper [@here](https://github.com/canjs/canjs/blob/master/view/stache/mustache_helpers.js#L229), `params` is `true` and `merge` is the `options` object, as defined in the [stache helpers docs](https://canjs.com/docs/can.stache.helper.html). Shouldn't those arguments be inverted, so that they match the documentation (i.e. all arguments first, then options object with hash)?

**Comment by justinbmeyer** [comment]
When you use a call expression, their really shouldn't be an options object.  

Instead `page='home'` should pass an object like {page: "home"} as the first argument and `true` as the second.

**Comment by gmahomarf** [comment]
I'll try it, thanks. I was using a call expression as detailed in the [routeUrl helper docs](https://canjs.com/docs/can.stache.helpers.routeUrl.html). They should be updated.

**Comment by justinbmeyer** [comment]
@gmahomarf I'm a bit confused.   Does it not work the way I suggested in my comment?

If yes, then this is a bug, not a problem with the docs.

**Comment by gmahomarf** [comment]
@justinbmeyer just to be clear, you're saying I doo the following?:

```.html
<a href="{{routeUrl({page: 'home'}, true)}}"> Link</a>
```

**Comment by gmahomarf** [comment]
I ran several tests this morning. Each example has the stache template where routeUrl was used. Below that is are values of the arguments sent to the routeUrl helper ([see code](https://github.com/canjs/canjs/blob/master/view/stache/mustache_helpers.js#L229)) and the resulting value for the `href` attribute.

To avoid cluttering the issue comments, I created a gist with the results: https://gist.github.com/gmahomarf/92d97265694f0c1a77ec

**Comment by gmahomarf** [comment]
Any news on this?

**Comment by justinbmeyer** [comment]
Canjs is not a priority for me this week. I'm working on can-set issues currently. If you want to help fix it, I can pair with you this week and close it out. Otherwise it will probably have to wait until next week.

**Comment by gmahomarf** [comment]
@justinbmeyer For now, I've got my code working as I need it, so this is no longer urgent for me. Ping me whenever you have time to take a look at this, and I'd love to help fix it. Thanks!
