### ISSUE TITLE
can-EVENT removed in live bindings doesn't unbind with stache (possible regression)

### ISSUE THREAD

**Issue by BigAB** [canjs/canjs#2292]
Possibly a regression from #1112

in `view/bindings/bindings_test.js` there is a test for called **can-EVENT removed in live bindings doesn't unbind (#1112)**

When `can.view.mustache` is changed to `can.view.stache` this test now fails.

Adding a setTimeout delay before the assertion can make it pass in a browser, but not in Phantom

**Comment by BigAB** [comment]
I push the branch `regression-1112-in-stache` with this change to show the breaking test

**Comment by BigAB** [comment]
OH, forgot to mention, this passes in browser but fails in PhantomJS

**Comment by BigAB** [comment]
OK, edit number 2, it does fail in the browser too.

**Comment by justinbmeyer** [comment]
closing for issue in can-stache-bindings.  We can port it back to 2.3 if someone else needs it.
