### ISSUE TITLE
AMD build has confusing path flattening

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#2295]
CanJS AMD builds are currently generated with certain levels of the directory structure flattened in a way that leaves a jumbled mess of unassociated files.

Can we please have a build option that respects the orginal directory structure like the CJS and Steal builds do?

**Comment by matthewp** [comment]
I think this is the plan for 3.0, @justinbmeyer ?

**Comment by rjgotten** [comment]
Would be great if you can get that in **before** the 3.0 version.

Right now the 2.3.x builds are a bad enough mess that I'm seriously contemplating to AMD-ify my own package based on the CJS builds.

**Comment by matthewp** [comment]
We couldn't change the build structure in a non-breaking release.

**Comment by rjgotten** [comment]
Ofcourse. I'm asking for another build configuration next to the existing amd and amd-dev; amd-strict, for instance. Not for a replacement of what's already there.

**Comment by gsmeets** [comment]
I use a small grunt task that remaps the absolute canjs to the correct local absolute path, that's a workaround that works for me until 3.0. Drop me a line if you want it. ;)

**Comment by pYr0x** [comment]
@gsmeets can you share your code with us? Would be create... :)

**Comment by gsmeets** [comment]
Here are the relevant parts of my grunt config.
Basically this pulls in canjs from the npm location into my local directory Scripts/lib, and then the text replace tasks just changes every path from "can" to "lib/can". It's dirty, but it works. I would've preferred just relative paths to begin with. ;)


````
grunt.loadNpmTasks("grunt-contrib-copy");
grunt.loadNpmTasks("grunt-text-replace");

grunt.initConfig({
	copy: {
		can: {
				expand: true,
				cwd  : "node_modules/can/dist/amd/",
				dest : "Scripts/lib/",
				src  : [ "**" ]
			}
	},
	replace: {
		can: {
			src: "Scripts/lib/can/**/*.js",
			overwrite: true,
			replacements: [{
				from: "'can/",
				to: "'lib/can/"
			}]
		}
	}
});

grunt.registerTask( "copypackages", [ "copy:can", "replace:can" ]);
````

**Comment by rjgotten** [comment]
@gsmeets 

Thanks. That will help.

**Comment by justinbmeyer** [comment]
closing as this is how 3.0 will be and we aren't going to do it for 2.3.
