### ISSUE TITLE
.attr() doesn't trigger define's setter for object properties

### ISSUE THREAD

**Issue by alexisabril** [canjs/canjs#2304]
When using `.attr()` with an object to set multiple properties, sequential change events are not triggered for object properties. In the below example we should see three `set` calls, but only receive two.

Works as normal when using `.attr('prop', 'val')` syntax.

http://jsbin.com/redose/1/edit?html,js,output

**Comment by justinbmeyer** [comment]
This isn't a bug.  By default passing objects merges properties.  If you want to replace it, the second one should be:

```
item.attr({ foo: new can.Map({ id: 0 }) })
```

**Comment by alexisabril** [comment]
Do we consider this a conflicting API if `.attr('foo', {})` does not do a merge?

http://jsbin.com/redose/2/edit?html,js,output

**Comment by justinbmeyer** [comment]
`item.attr('foo', {})` will do a replace.  Not a conflict.

`.attr(VALUES)` -> merges

`.attr("prop", value)` -> replaces

**Comment by alexisabril** [comment]
Ah, that makes sense
