### ISSUE TITLE
childToParent bindings set can.Maps improperly

### ISSUE THREAD

**Issue by Bajix** [canjs/canjs#2314]
The [childToParent](https://github.com/canjs/canjs/blob/master/view/bindings/bindings.js#L642) bindings [unsafely merge can.Maps](https://github.com/canjs/canjs/blob/master/view/bindings/bindings.js#L668).

[When the properties are merged](https://github.com/canjs/canjs/blob/master/map/map.js#L454), this loops through and sets private properties, subsequently converting internal objects in unsafe ways that cause errors.

While [the merging of can.Maps](https://github.com/canjs/canjs/blob/master/view/bindings/bindings.js#L668) is what's calling attr in an unsupported fashion, I've seen a lot of developers trip up over this issue. I think this is a frequent enough issue to warrant throwing an error. The current behavior triggers an uncaught exception, however throwing an error would give Developers better feedback.

Additionally, there are a number of cases in which merging can.Map properties, as done with the childToParent binding, create unintended consequences. For example, if the parentCompute were a can.Model of a different ID, then merging properties would affect other instances unintentionally, possibly resulting inadvertently in data lose.

As such, I'd argue we should:
- Throw explicit errors whenever a can.Map is called w/ another can.Map instance while using the merge syntax
- Never recycle/merge can.Map instances when we intend to replace them.

**Comment by justinbmeyer** [comment]
I think the error when merging is a good idea. Regarding:


> Never recycle/merge can.Map instances when we intend to replace them.

I'm not sure we can identify those scenarios.  What case is this happening?  The only thing I can think of is with a `component` that is trying to export to a property on a plain JS object that happens to be a `can.Map` or a `can.List`.

```
<my-component {^export}="value"/>
```

that might be rendered with:

```js
{value: new can.Map()}
```

**Comment by justinbmeyer** [comment]
I should point out that this merge ability is there for `can-value` in situations like this one: https://github.com/canjs/canjs/blob/master/view/bindings/bindings_test.js#L669

`can-value` exports plain JS objects.

**Comment by Bajix** [comment]
> I'm not sure we can identify those scenarios. What case is this happening? The only thing I can think of is with a component that is trying to export to a property on a plain JS object that happens to be a can.Map or a can.List.

I think the [default behavior](https://github.com/canjs/canjs/blob/master/map/map.js#L483) of _setAttr to recycle can.Map's is what's problematic, as it has the potential to introduce side-effects. Setting nested objects results in merging nested maps rather than creating new ones, which quickly becomes problematic, as demonstrated [here](https://github.com/canjs/canjs/issues/1647). 

Right now I'm using can.Model.parseModel to simply avoid the only major use case in which I've had this occur: CRUD callbacks w/ deeply nested properties. If setting the value of a can.Map property were to always utilize define/Type rather than merging, we could combine that with better support for can.Model.model + define/Type/type, and that would make can.Model.store always work out of the box. That sort of simplification is what we need to make the library more accessible to new developers.

> I should point out that this merge ability is there for can-value in situations like this one: https://github.com/canjs/canjs/blob/master/view/bindings/bindings_test.js#L669

This is an excellent case for merging. I actually really do like merging whenever possible. It's only problematic when this behavior is unintentional and has the potential to inadvertently introduce side-effects.

The childToParent binding should probably just always be a vanilla compute. Merging props onto the existing map creates massive side-effecting, assuming we addressed serialization. For instance, imagine the ill-fated consequences of binding a model to the root viewModel: changing the value would affect other references of the previous model; something like a sub doc/ foreign doc would be inadvertently overridden.

**Comment by justinbmeyer** [comment]
> The childToParent binding should probably just always be a vanilla compute.

But that's not always the case as indicated in the above test.  

>  binding a model to the root viewModel:

What would this look like?

**Comment by Bajix** [comment]
> But that's not always the case as indicated in the above test.

In the case of multi-select, it would be safe to cross-bind the can.List itself, and then to replace members. The only way in which I see this going very wrong is if we didn't respect the can.List reference. I don't really see that occuring with multi-select, but conceivable elsewhere it would be problematic to have a childToParent binding replace the previous List's members rather than replace the list itself. It would also create an inconsistency in events: there wouldn't be a "{viewModel} myList" event, which suddenly means components would behave differently depending on how the value's are bound.

Think about that for a second. "{viewModel} myList" would trigger w/ 2-way bindings, parent-child bindings, but not child-parent bindings. That's breaking behavior IMO.

> What would this look like?

```
<find-one {^sidebar}="*sidebar" {_id}="{*router.sidebar}"></find-one>
<find-one {^widget}="*widget" {_id}="{*router.widget}"></find-one>
```

* Sidebar.widgets = [A, B]
* Update widget A & save sidebar
* Browse to widget B
* Sidebar.widgets = [B, B]
* Update widget B & save sidebar

Browsing to widget B inadvertently overrides A, which is referenced within in sidebar. Voila! Side effects with terrifying consequences that can easily be missed by the developer, QA as well as automated testing. Most likely, testing stops after successfully saving the sidebar.

There are a lot of ways this can go bad fast.

**Comment by justinbmeyer** [comment]
closing for can-stache-binding issue
