### ISSUE TITLE
can/view doesn't normalize template paths against SystemJS BaseURL

### ISSUE THREAD

**Issue by Bajix** [canjs/canjs#2315]
Currently, [can/view getRenderer](https://github.com/canjs/canjs/blob/master/view/view.js#L112) doesn't localize template URL's against the baseURL

The dirty fix would be to check for window.System and prepend System.baseURL, however I'd argue that we should just bite the bullet and make a wrapper for System/Almond/Steal/RequireJS in the same vein as what's been done with jQuery/MooTools/YUI/Zepto.

This could also address https://github.com/canjs/canjs/issues/2293

**Comment by justinbmeyer** [comment]
Thanks for submitting.  

`can/view` used for loading is really deprecated in favor of `<can-import>`.  `<can-import>` should normalize based off the moduleName of the current file.  Normalizing of the `baseURL` is less than ideal in a package (npm) workflow. 

We are removing the jQuery/Mootools/YUI/Zepto compatibility layer from CanJS 3.0.

In the same vein, I've been considering removing `<can-import>` from CanJS 3.0 and having them be 2nd or 3rd party modules.  `can.view` is very likely going to be removed as well.  

If it does stay in CanJS, this will have to be something the community creates.  I'll keep it open and label it "needs a hero".

**Comment by Bajix** [comment]
> can/view used for loading is really deprecated in favor of <can-import>. <can-import> should normalize based off the moduleName of the current file. Normalizing of the baseURL is less than ideal in a package (npm) workflow.

Almost, but not quite: not normalizing the URL affects the ID lookup, which is necessary for both sub templates and for loading cached templates. The can/view/stache/system plugin should ideally pre-load templates and include sub-templates as dependencies, possibly bundled.

> We are removing the jQuery/Mootools/YUI/Zepto compatibility layer from CanJS 3.0.

Standardize on jQuery?

> In the same vein, I've been considering removing <can-import> from CanJS 3.0 and having them be 2nd or 3rd party modules. can.view is very likely going to be removed as well.

can-import seems like a necessary evil, considering it's not viable to map component names to dependencies. That would also be difficult from a dependency tree perspective: the template translator would need account for can-import being externally required after the fact, which is unnecessarily painful.

> can.view is very likely going to be removed as well.

Makes sense. I was wondering when synchronous template loading was going to be deprecated. Pulling that bandaid out and forcing templates as a dependency simplifies a lot.

**Comment by rjgotten** [comment]
> `<can-import>` should normalize based off the moduleName of the current file. Normalizing of the baseURL is less than ideal in a package (npm) workflow. 

Yes please. 
Just as long as you also implement it for AMD/RequireJS, where you're not yet handling relative module lookups with `can.import` (which is what `<can-import>` uses under the hood, ofcourse).

Incidentally, incase you're still puzzling on how to get that to work: there's a little trick you can use whereby you define a dummy module that is meant to extract a *local* `require` reference for a sibling-module of the original parent. Then you use the dummy 'required `require`' to load the actual module you want.

In simplified code:

```js
can.import = function( moduleName, parentName ) {
  parentName += "?can-import";

  return can.Deferred( function( def ) {
    window.define( parentName, [ "require" ], function( require ) {
      return require;
    });
    window.require([ parentName ], function( require ) {
      require([ moduleName ], def.resolve );
    }, def.reject );
  }).promise();
}
```

(That won't solve the problem with optimized builds and grouping dependencies and inlined templates though. That bit requires a separate loader plugin...)

**Comment by Bajix** [comment]
> (That won't solve the problem with optimized builds and grouping dependencies and inlined templates though. That bit requires a separate loader plugin...)

I actually rolling w/ a custom can/view/stache/system plugin that does this. I'll try to get this integrated soon, but first need to sort out of all of areas in which SystemJS is semi-incompatible.

> <can-import> should normalize based off the moduleName of the current file. Normalizing of the baseURL is less than ideal in a package (npm) workflow.

I hadn't actually addressed the issue of normalization against a parentModule, which can't really be solved without abandoning can.view in favor of utilizing a module loader. We would need to use a normalized path that's relative to the baseURL for ID's, as well as use normalizeSync to expand the URL w/ path mapping. That gives us best of both worlds, as sub template lookup would grab from cache, and hit pre-loaded templates.

As a stop gap measure, we can include sub-templates as dependencies and pre-load them w/ ID's tokenized from the path mapped w/in System/Steal/RequireJS & relative to baseURL. At least that way we avoid needing can.view to do module loader things, which wouldn't be viable until 3.0

```
{{>my-component/views/index.stache}}
```

This should result in:
ID: my-component_views_index_stache
URL: http://www.example.com/assets/packages/my-project@0.0.1/dist/cjs/my-component/views/index.stache

**Comment by justinbmeyer** [comment]
Closing.  @rjgotten that's a great tip.  

http://canjs.github.io/canjs/doc/can-view-import.html is going to be in its own module in 3.0.  But for build other system specific integrations, we have the ecosystem category with things like [steal-stache]( http://canjs.github.io/canjs/doc/steal-stache.html).  My hope is that people can make browserify, amd, jspm, etc extensions and we can list them there.
