### ISSUE TITLE
autorendered template attributes are not added to template viewModel

### ISSUE THREAD

**Issue by nlundquist** [canjs/canjs#2317]
According to [the docs](https://canjs.com/docs/can%7Cview%7Cautorender.html) the following should work:

```
<script type="text/stache" can-autorender message="hello">
    {{message}}
</script>
```

However in the current (2.3.20) release the message attribute is not available to the template and the output is blank.

This is because an element (line 48) in can/view/autorender is jquery wrapped when it's not expected to be.

**Comment by phillipskevin** [comment]
This was fixed already by https://github.com/canjs/canjs/commit/8a8a9bce9265f825d35eedb6a32d0546c81f2d4d.
