### ISSUE TITLE
All tests depend on a global can

### ISSUE THREAD

**Issue by BigAB** [canjs/canjs#2325]
All the tests depend on a global `can` object being available.

This doesn't seem right, and, I feel, could lead to leaking stuff across tests because they are not fully isolated.

Importing 'can' into the tests causes **amd** and **global** tests to fail, which I guess makes sense, but I feel like there is a better way to do it where the tests are isolated and not depending on a global `can` object, but we can still test the **amd** and **global** builds without re-writing the test files.

**Comment by justinbmeyer** [comment]
There is a better way of doing this, but not without rewriting all the tests.

**Comment by justinbmeyer** [comment]
We should absolutely rewrite the tests.  But not until after an initial release.

**Comment by justinbmeyer** [comment]
done in 3.0
