### ISSUE TITLE
helpers in each loop [request]

### ISSUE THREAD

**Issue by reno1979** [canjs/canjs#2329]
ok wrong way for requesting an additional feature...

Is it possible to add two extra helpers aside the @index inside an #each loop? 

We where used to the @first and @last helpers used in handlebars.js, could the #each helper be extended with this functionality?

I would guess something like this, but offcourse I'm missing a lot of required details :) 

`return options.fn(options.scope.add({
                            '%index': index,
                            '@index': index,
                            '@first': (index === 0)
                        } ......
`

And what if the used keys are not numerical, would this still work?

**Comment by justinbmeyer** [comment]
@reno1979 sounds like a fine feature.  Closing for an issue in can-stache.
