### ISSUE TITLE
Filtering in fixtures findAll method is too limiting

### ISSUE THREAD

**Issue by xojins** [canjs/canjs#2331]
In can/util/fixture.js, around line 522:
The findAll method accepts parameters that will allow filtering of the fixtured data. However, the condition is that the parameter should not be undefined and must contain ID in the parameter name. This is too limiting in the real world. We can have composite primary keys in our data and need to have greater flexibility.

I suggest that the code be updated to the following:
`
if (request.data[param] !== undefined && (param in retArr[i])) {
`
This will allow the data to be filtered if the parameter is not undefined and if the parameter we want to filter is a key in the data object we want to filter on. 

This gives us the flexibility we need with using fixtures.

**Comment by justinbmeyer** [comment]
@xojins Thanks for the suggestion.  Anyway you can make it in https://github.com/canjs/can-fixture.  This is going to be where the next version of can-fixture is maintained.

Also, can you include a bit more in terms of code that isn't working.  I assume you are talking about `store.findAll`.  

The next version of `can-fixture` will be making use of set-algebra.

**Comment by justinbmeyer** [comment]
Closing b/c no changes to can.fixture will be made in this repo.
