### ISSUE TITLE
#each leaking memory in stache

### ISSUE THREAD

**Issue by imjoshdean** [canjs/canjs#2332]
Discovered that if you have a `{{#each}}` and iterate on a list that you are constantly moving around or adding and removing items from, it will leak memory. I looked it over with @ccummings and it looks like it might be something in `can.view.nodeList`.

Example written up here: http://jsbin.com/guzigig/1/edit?html,js,output

Demonstration of increasing memory and DOM nodes: 

![](https://i.imgur.com/1IS4g4n.png)

**Comment by justinbmeyer** [comment]
@imjoshdean please make a pull request with the JSBin's code as an HTML page in this folder:

https://github.com/canjs/canjs/tree/master/view/stache

https://github.com/canjs/canjs/blob/master/view/stache/visual_benchmark.html is an example of using steal to load CanJS.

This will save me some time getting setup to investigate.  Once that's created and I'm done with my morning meetings, I will look into it.

**Comment by ccummings** [comment]
Example is in #2333

**Comment by imjoshdean** [comment]
I feel like I should add that I saw this in a project that I am currently working on that desperately needs this fix, hence why I added the "Priority" label. I'm going to reapply it and assume it was removed because of the lack of understanding of that.

Also, thank you @ccummings.
