### ISSUE TITLE
failing to install with "ERR! cb() never called!"

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#2335]
Using:
* npm 3.7.3
* node 5.9.0

related https://github.com/npm/npm/issues/11976

**Comment by justinbmeyer** [comment]
Yeah, I was seeing this yesterday at a training. I had people switch to another version of npm and it worked.

**Comment by cherifGsoul** [comment]
@pYr0x is it fixed?

**Comment by pYr0x** [comment]
not for me...

**Comment by daffl** [comment]
I could reproduce this with those versions. I published a new 2.3.22 with it and the installation is now working.
