### ISSUE TITLE
can-import is not working as described in the documentation

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#2336]
simple app:

**main.js**
```
import appTemplate from "src/app.stache!";

$('body').append(appTemplate());
```

**app.stache**
_is not working_
```
<can-import from="testapp/components/welcome/"></can-import>
<welcome></welcome>
``` 

_is not working_
```
<can-import from="testapp/components/welcome/">
    <welcome></welcome>
</can-import>
``` 

_is working_
```
<can-import from="testapp/components/welcome/" />
<welcome></welcome>
```

the documentation shows all 3 typs https://canjs.com/docs/can%7Cview%7Cstache%7Csystem.import.html

you may want to download this testapp repo https://github.com/pYr0x/testapp

**Comment by cherifGsoul** [comment]
@pYr0x what about if you use hypen in you custom tag? like ```ui-welcome```

**Comment by pYr0x** [comment]
@cherifGsoul unfortunately... no

**Comment by cherifGsoul** [comment]
Why the importing paths are different? 
```import appTemplate from "src/app.stache!";```
```can-import from="testapp/components/welcome/```
I think paths should be changed

**Comment by justinbmeyer** [comment]
I'm not sure what you mean by "paths should be changed"?

**Comment by justinbmeyer** [comment]
Never mind, you mean that pRy0x should change his imports. Yes, that is almost certainly the problem.

**Comment by pYr0x** [comment]
@justinbmeyer what path should be changed?
@cherifGsoul I changed the import also to ```import appTemplate from "./app.stache!";``` and it doesn't t work too

**Comment by matthewp** [comment]
@pYr0x there are two types of can-imports, perhaps this should be explained in the docs:

## static
These are imports that are direct dependencies of the template. For example:

```js
import from 'foo';
```

Is equivalent to:

```handlebars
<can-import from="foo"/>
```

## dynamic

These are conditional imports, things you only want to import in certain situations. These are equivalent:

```js
System.import('foo').then(function(foo) { ... })
```

to

```handlebars
<can-import from="foo">
  {{#if isResolved}}
  <foo/>
  {{/if}}
</can-import>
```

**Comment by pYr0x** [comment]
ok got it.

thx to @matthewp for that rectification.
i will add this to the document

also be careful, the component need a hyphen for the dynamic loading see this issue here!
https://github.com/canjs/canjs/issues/1541

**Comment by cherifGsoul** [comment]
Nice to know thank you @matthewp
