### ISSUE TITLE
./ scope lookup should read current scope

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2339]
Introduced in 2.3.14. Similar to #2244.

``` js
var map = new can.Map();
var scope = new can.view.Scope(map);
scope.attr("./") == map; // false
```

http://jsbin.com/mafaroxire/1/edit?html,js,console

**Comment by justinbmeyer** [comment]
Technically, I think this is trying to read the `""` property from the `map`.  I know that:

```
var map = new can.Map();
var scope = new can.view.Scope(map);
scope.attr("./") == map; // false
```

should work.

Is there a reason to use `./`?

**Comment by dylanrtt** [comment]
I think someone might have reported this in Gitter. Some people prefer `./` over `.` for clarity or readability.

**Comment by justinbmeyer** [comment]
@dylanrtt what if someone wants to read the empty string property?  It's a very unlikely case, but `{"":123}` is valid.  Perhaps in 3.0, they could get it with `./[""]`.  I'm just debating if this makes sense semantically, if `./` should represent the same thing as `./[""]` or `.`.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-view-scope #54](https://github.com/canjs/can-view-scope/issues/54) via [**ZenHub**](https://www.zenhub.com/)
