### ISSUE TITLE
Performance Problems

### ISSUE THREAD

**Issue by RALifeCoach** [canjs/canjs#2342]
I have a component that produces 1 row in a table. From existing JS code, the component is added 156 times to build the full table. The stache template, map and component are found here:
http://jsbin.com/qawule/edit?html,js
And the code to link them together is:
```
            this.playerRowMap = new global.playerRow.PlayerRowMap(data);
            var template = can.stache('<player-row id="player-row-' + this.pid + '"></player-row>');
            this.container.append(template(this.playerRowMap));
```

**Comment by justinbmeyer** [comment]
@RALifeCoach Thanks for sharing.  I'm not sure I understand the example quite yet.

Your component is `<player-row>`.  But it doesn't seem like it is being inserted into an actual table is it? If it were, I would assume your example would look more like:

```js
this.playerRowMap = new global.playerRow.PlayerRowMap(data);
var template = can.stache('<tr><player-row id="player-row-' + this.pid + '"></player-row></tr>');
this.container.append(template(this.playerRowMap));
```

What is `this.container`?

Also, why is the code doing `append` itself?  In a modern, post-can.Component, application, one doesn't render and insert templates other than the initial template.  Instead, you'd have something like:

```
{{#each players}}
  <player-row {player}="."></player-row>
{{/each}}
```

Also, I noticed:

```js
this.highlightPicker = this.element.find(this.HIGHLIGHT_PICKER);
this.highlightPopup = this.element.find(this.HIGHLIGHT_POPUP);
this.expansionContainer = this.element.find(this.EXPANSION_CONTAINER);
this.articleButton = this.element.find(this.ARTICLES_BUTTON);
this.photoButton = this.element.find(this.PHOTOS_BUTTON);
this.videoButton = this.element.find(this.VIDEOS_BUTTON);
```

That's a lot of querying for each `<player-row>` which could be deferred until later.

Is there anyway you can make your JSBin work?  Give it mock data that will insert `player-row` 156 times into the page?  I could take a stab at it, but it would take me a while to figure out what the mock data looks like.

**Comment by RALifeCoach** [comment]
@justinbmeyer, Thanks for your comments.

You are right, the component is being inserted into a table of divs, not an HTML table. As for
```
this.highlightPicker = this.element.find(this.HIGHLIGHT_PICKER);
this.highlightPopup = this.element.find(this.HIGHLIGHT_POPUP);
etc.
```
I use those frequently in the events following. However, the performance issue is present whether the assigns are in the component init or not.

Getting the JSBin to work will take a fair bit of time. Let me see what I can do. It will probably only be for a few rows.

**Comment by justinbmeyer** [comment]
@RALifeCoach if you know the shape of your data, you can probably do something like:

```js
var players = [];
for(var i = 1; i <= 156; i++){
  players.push({
    id: i,
    name: "Player"+i,
    // dummy versions of all other data
  })
}

players.forEach(function(player){
  var template = can.stache('<player-row id="player-row-' + player.pid + '"></player-row>');
  container.append(template(player));
})
```

**Comment by RALifeCoach** [comment]
The JSBin is running and taking the about 3 seconds.

**Comment by RALifeCoach** [comment]
Here is the new JSBin. http://jsbin.com/wanima/1/edit?html,js,console,output

**Comment by RALifeCoach** [comment]
If I strip down the player object to just the fields that I need, then I get better timings. The load is still over 3 seconds, but the reload is .5 seconds. That still feels a touch long, but much improved. That opens the question, why does a large player object - where most of the properties are not used - take so much time? Having to write a mapper each time I want to use a template doesn't make much sense.

**Comment by RALifeCoach** [comment]
I know I am being impatient, but has there been any progress?

**Comment by justinbmeyer** [comment]
@RALifeCoach I might be able to work on this over the weekend.  But I didn't get a chance to look at this today.

If you have a lot of properties that you don't need, then you might consider using LazyMap and LazyList.  They only convert properties as they are read.

Also, if you are supporting IE>9, you might look at https://github.com/canjs/can-define.  This is about 3 to 4x faster than can.Map.

**Comment by justinbmeyer** [comment]
> That opens the question, why does a large player object - where most of the properties are not used - take so much time? 

This is because those properties are converted to being observable.  There's 135 properties and there's 156 items.  `21060` is a lot of data to convert.  

LazyMap and LazyList are able to avoid converting all of that and `can-define` is able to do it faster and you can specify what should be observable and what shouldn't.

> Having to write a mapper each time I want to use a template doesn't make much sense.

You only need these techniques when the set of observable data is as large as you are dealing with.

**Comment by RALifeCoach** [comment]
Thank-you @justinbmeyer for your suggestions. I have changed Map to LazyMap and I now get an exception thrown both in my code and in the JSBin. Please have a look and let me know what I have missed. (In the mean time I will see if what I have missed is to define all the properties I might be using.)

**Comment by RALifeCoach** [comment]
Any insights?

**Comment by RALifeCoach** [comment]
I have done further analysis. It is a third level property that causes the exception. The viewModel top level properties are options, player, etc. Player has a property player_bio. player_bio has properties country, first_name, etc. When I reference, in the stache file, ```player.player_bio.country```, I get a problem when updating the player ```map.attr('player', player);```. If I remap the player and flatten it to ```player.player_bio_country```, then the exception no longer happens.

**Comment by RALifeCoach** [comment]
@justinbmeyer I had a look at can-define. The readme references can.compute and therefore there is no can-define documentation. As well, this code is not available through the custom download builder. Question: why is this code can-define instead of can.define?

**Comment by jandjorgensen** [comment]
@RALifeCoach did this get resolved in https://github.com/canjs/can-map-lazy/issues/1?

**Comment by RALifeCoach** [comment]
@jandjorgensen Yes.

**Comment by justinbmeyer** [comment]
@RALifeCoach can-define because in 3.0 everything is going to be module based.

I'm closing this issue.  If you have performance problems in the future using can-define, please let us know.
