### ISSUE TITLE
Support a second, long-hand Stache binding syntax targeted at beginners

### ISSUE THREAD

**Issue by marshallswain** [canjs/canjs#2346]
I propose that we adopt a long-hand, alternative syntax for Stache bindings.

Here’s my proposed syntax:

```html
// Two-way binding
<my-component {(child-attr)}="value"> 
  is shorthand for  
<my-component bind:child-attr="value">

<my-component {($child-attr)}="value"/>
  is shorthand for  
<my-component bind:$child-attr="value">

// One-way binding, parent to child
<my-component {child-attr}="value">
  is shorthand for  
<my-component bind-in:child-attr="value">

<my-component {$child-attr}="value"/>
  is shorthand for
<my-component bind-in:$child-attr="value">

// One-way binding, child to parent
<my-component {^child-attr}="value">
  is shorthand for  
<my-component bind-out:child-attr="value">

<my-component {^$child-attr}="value"/>
  is shorthand for  
<my-component bind-out:$child-attr="value">

// Events
<my-component ($click)="doSomething()"> 
  is shorthand for 
<my-component on:$click="doSomething()">

<my-component (event)=“doSomething()"> 
  is shorthand for 
<my-component on:event="doSomething()">
```

Reasons I feel it’s important:
1. It’s self explanatory.  It doesn’t really *have* to be memorized.
2. When you’re still in the process of committing the shorthand syntax to memory, it can disrupt your workflow to have to look things up again.  This can trigger a negative emotional reaction that we don’t want, because emotions often stick around for the longterm, creating uncommitted users.
3. It’s memorizable in a matter of minutes.  It took me months to adjust to the new syntax, and I still get my `{}` and `()` reversed, sometimes.  At other times I might forget what syntax an event uses, or if a to-parent binding is supposed to be `{^to-parent}` or `{^(to-parent)}`
4. It lowers the likelihood of trip-ups for developers who bounce back and forth between projects that use the old and new syntax.
5. It allows those who like the shorthand to continue to use it.
6. Jorgensen’s Razor: If a syntax is hard to remember, developers will learn to use another way instead of learning the right way.

7. It feels appropriate (to me) to borrow back from Vue.js, since it seems like nearly all of Vue.js was modeled after CanJS, as the sincerest form of flattery.

**Comment by jandjorgensen** [comment]
:+1: on some of the anecdotes. It wasn't obvious when the syntax was first settled on, but after some "user testing" I think an alternative is worth considering.

**Comment by justinbmeyer** [comment]
While I like the syntax.  I think there are a lot of downsides to having multiple ways of doing things.  We had a long debate, everyone had their favorite binding syntax.  What we settled on wasn't mine (`child{="parent"`), but I'm wary of revisiting.  Also, I'd want to make sure we maintain some level of consensus.  

A starting place to experiment would be to expose `getBindingInfo` so it can be replaced.  That way you could easily write a plugin for your own rules by just providing an alternate regexp and rules for what it means like https://github.com/canjs/canjs/blob/master/view/bindings/bindings.js#L798

**Comment by BigAB** [comment]
Though I don't mind it.

I find it a bit overly verbose, making a template file look think and bloated with text.

I find it still suffers from a similar problem with confusion: "Was it `bind-in:` or `bind-out:`?", "Was it `on:event` or `on:(event)`?"

I think exposing an api to allow plugin modifications to the templating language would be super awesome though.

**Comment by jandjorgensen** [comment]
@BigAB verbose is arguably ok if it's memorable, and verbosity often begets readability. `{()}` syntax may be more concise, but there are two problems with that: it's arguably harder to parse visually with a glance and your brain is going through two steps when converting it to meaning. Symbols => Words, Words => What's Happening. It's kind of like using Spanish for an English-speaking audience for the sake of clarifying gender. It may add additional meaning with fewer words, but the incongruity it probably requires use of the reflective system of thinking instead of the automatic system.

Even if "Was it `bind-in` or `bind-out`?" is easily confused, you must retain less information to remember it. In=Down, Out=Up. For the current syntax, {}=Down, ()="Up" for events, {^}=Up.

**Comment by BigAB** [comment]
Fair enough.

I wouldn't use this syntax myself though. Maybe, if I had learned it first I would think differently.

**Comment by justinbmeyer** [comment]
I fully support this, but it's not something the OS team is going to undertake at this time.  If someone wants to take it up, I'm happy to pair with them. Closing and adding "needs a hero" label.

**Comment by marshallswain** [comment]
See https://github.com/canjs/can-stache-bindings/issues/229
