### ISSUE TITLE
Community page has no content

### ISSUE THREAD

**Issue by tomgreever** [canjs/canjs#2348]
The Community page on CanJS.com no longer has any content from Bithub. This is because the `bitovi.bithub.com` services were taken down by @mjstahl to save on our linode bill. As a result, the "Community" link in the menu goes to a useless page: https://canjs.com/community.html#!forums

My recommendation is (for now) is to remove the `href` in the "Community" menu item so the user cannot access this page. They can still use the dropdown menu items to access Community resources. 
![screen shot 2016-03-31 at 7 54 00 am](https://cloud.githubusercontent.com/assets/326843/14176325/039d6712-f716-11e5-821e-c101ebf7fbfb.png)

@justinbmeyer ?

**Comment by mjstahl** [comment]
Completely my mistake. I took it down because the server graphs for CPU, memory, and bandwidth were completely flatlined. So I assumed it wasn't being used anywhere anymore. Wrong assumption on my part.

If we decide to not go with Tom's suggestion, we can recreate the feeds on bithub.com.

**Comment by justinbmeyer** [comment]
fixed by removing the community page
