### ISSUE TITLE
3.0 Docs

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2356]
Objective:

- Create a best in class documentation solution for CanJS.  
- Allow a user to quickly take in CanJS at a high level and incrementally get deeper (Cheatsheet -> APIs + Example -> In Depth Docs).
- Make it easily editable by others and manageable by the OS team.
- Highlight CanJS's purpose, advantageous over similar utilities.

Prior art:
- https://github.com/joe-crick/DocumentJs_Proposal
- https://docs.google.com/document/d/171FKUihG1BoK1uLDiR-szVQyo4vGClUrCyM8tvljx2A/edit

**Comment by justinbmeyer** [comment]
[Tom's mockups](http://share.bitovi.com/UDF9Q4/#p=hubble)

**Comment by matthewp** [comment]
## Documentation difficulties

Here are some problems I've ran into when documenting 3.0 projects.

* Unsure if we should use the `can.` namespace in examples (or docs in general). I have been removing it so far.
* Linking to external projects. For example, in can-map there are links like `[can-compute]` which don't work in the readme but do work in the full-site.
