### ISSUE TITLE
Rendering stache templates as string not working (always returns DocumentFragment)

### ISSUE THREAD

**Issue by lastzero** [canjs/canjs#2358]
Calling `can.view.render()` or `can.view.renderAs('string', ... )` should return a string, according to the documentation:

https://canjs.com/docs/can.view.html#section_Renderingtostringsandsub_templates

However, a `DocumentFragment` object is always returned. Rendering as string used to work with EJS.

Example:
```
> console.log(can.view.renderAs(
    'string', 
    'view/errors/invalid.stache', 
    { caption: 'example' }
  ).toString());
  
  [object DocumentFragment]
```

**Comment by lastzero** [comment]
The bug seems to date back to 2014 (f761946449ab8e19ae1073649d51f408759b2d97):

```
// if the template has a fragRenderer already, just return that.
if(info.fragRenderer) {
	return info.fragRenderer(null, id);
} else {
	return makeRenderer(info.renderer(null, id));
}
```

Since fragRenderer doesn't offer a render() function for text rendering, a DocumentFragment is always returned:

```
renderTo: function (format, renderer, data, helpers, nodelist) {
    return result = (format === 'string' && renderer.render ? renderer.render : renderer)(data, helpers, nodelist);
},
```

As a workaround, it's possible to convert a DocumentFragment back to text like this:

```
if(text instanceof DocumentFragment) {
   text = new XMLSerializer().serializeToString(text);
}
```

**Comment by justinbmeyer** [comment]
@lastzero thanks for the workaround.  This method is being removed in 3.0 so closing.
