### ISSUE TITLE
Stache promise support doesn't work with ES6 promises

### ISSUE THREAD

**Issue by nlundquist** [canjs/canjs#2359]
https://canjs.com/docs/can.stache.html#section_WorkingwithPromises

The support described here for promises in stache templates appears to only apply to jQuery deferreds. ES6 promises are just treated as any other object in a template.

If this is intended the docs should be updated to reflect it. 

A test case to demonstrate: https://github.com/nlundquist/canjs-template-promise-test

Correction: this is resolved by #2247

**Comment by matthewp** [comment]
Looking at your example, I don't think native Promises have a `value` property, could this be why?

**Comment by justinbmeyer** [comment]
That's not why. We add one.

**Comment by nlundquist** [comment]
I think we need to add the same properties to native promises. Or at least document that this support is only for deferreds.

**Comment by justinbmeyer** [comment]
A+ promises must be working in some fashion, otherwise, all the promises produced by can-connect, which are not native, but A+ (which is close enough) do work.

**Comment by justinbmeyer** [comment]
Also, we don't need to add anything to native promises, we only have to make sure `can.isPromise` works for them.  My guess is that StealJS's polyfill is making `promise instanceof Promise` fail.

**Comment by justinbmeyer** [comment]
This shows native promises working if `can.isPromise` is fixed: http://jsbin.com/xitezi/1/edit?html,js,output

**Comment by nlundquist** [comment]
Good to know about A+. 

The steal polyfill issue would make sense. Yeah I wasn't suggesting to modify the native promises themselves, merely apply the support that enables those properties in templates. I'll look into this this evening if someone hasn't before then.

**Comment by nlundquist** [comment]
awesome thanks for looking into this
