### ISSUE TITLE
how can i change can.route.attr()

### ISSUE THREAD

**Issue by hntvip** [canjs/canjs#2360]
I have route.attr: `can.route.attr({type:"list",id:"list",val:""})`

location.hash -> `#!update/edit&val=113`

how can I change this to `#!list/list` and destroy val:"" in url

i use this : `can.route.attr({type:"list",id:"list",val:null})`

location.hash -> `#!update/edit&val=`  it didnt destroy val=

**Comment by pYr0x** [comment]
@hntvip what about `can.route.removeAttr('val')`

**Comment by hntvip** [comment]
thank you @pYr0x . i done with your suggestion

**Comment by hntvip** [comment]
when i on url : "#!update/add" , i want go to new url  "#!list", but when i call : can.route.attr({route:"list"}) . It changed page of url, but the url did not change ?. what can i do now?

**Comment by justinbmeyer** [comment]
@hntvip Thanks for asking questions.  We're always happy to help.  But if you don't mind, these types of questions are best on the forums: http://forums.donejs.com/c/canjs.  We like to keep github for bugs / features /etc.

I'm closing this issue, but you probably need to call `.attr` with `true` like:

```js
 can.route.attr({route:"list"}, true)
```

This tells it to remove any properties on `can.route` not in the object of property/values.

**Comment by hntvip** [comment]
@justinbmeyer  thank you so much, sorry when i ask some dumb question ! :((

**Comment by justinbmeyer** [comment]
There are no dumb questions. Keep asking!
