### ISSUE TITLE
IE8: Stache errors when using <style>

### ISSUE THREAD

**Issue by ccummings** [canjs/canjs#2362]
If you attempt to render a `<style>` tag using stache in IE8, it will throw an error ` Unexpected call to method or property access` at [can.view.targetL156](https://github.com/canjs/canjs/blob/master/view/target/target.js#L156)

jQuery worked around this issue a long time ago: https://bugs.jquery.com/ticket/9832

**Comment by justinbmeyer** [comment]
Only in IE8?

**Comment by justinbmeyer** [comment]
Closing b/c we don't support IE8 anymore.
