### ISSUE TITLE
Possible memory leak in stache CanJS@2.2.9

### ISSUE THREAD

**Issue by Tarabyte** [canjs/canjs#2365]
I am using stache template engine to inject some components inside jquery plugin (FuelUx Repeater to be precise).
The problem is that LiElements are captured within `__handlercomputeN...N` contexts and are never garbage collected.
[Plnkr demonstrating the issue](https://plnkr.co/edit/eC1MQAqc3pFfLjYBPfTc?p=preview)

* Parent UL is emptied on every test run.
* Inner component `removed` event is fired.
* 100 new HTMLLiElements are created on every test run.

I know 2.2.9 is a little outdated but is there any way to workaround this issue w/o upgrading to 2.3?

![Heap snapshot](https://lh3.googleusercontent.com/-1nCW075CIgs/VweB7XscZeI/AAAAAAAAE4Y/6byGbptxm6kc0joRfs-1lGiR7Ykm2GEPA/w1453-h805-no/StacheLeak.png)

**Comment by Tarabyte** [comment]
Ping

**Comment by justinbmeyer** [comment]
@Tarabyte sorry about the late response.  We've fixed a few memory leaks in 2.3, this is undoubtedly one of them.  

As tracking them all down, and making the individual changes will take a while, the easiest thing (and the best result) will be upgrading to 2.3.

**Comment by justinbmeyer** [comment]
2.3 is backwards compatible (unless you're relying on broken batching behavior).  Upgrading shouldn't be a problem.

If you do run into 2.3 upgrade problems, please report them and we will help you move past them.

**Comment by Tarabyte** [comment]
@justinbmeyer Thanks. I'll try to upgrade to the latest 2.3.x

**Comment by pYr0x** [comment]
@Tarabyte news about this issue?

**Comment by Tarabyte** [comment]
Fixed in 2.3.
