### ISSUE TITLE
Define getter/setters don't work with default property

### ISSUE THREAD

**Issue by nlundquist** [canjs/canjs#2367]
Trying to use the define plugin getters & setters on the 'wildcard' / 'default' property results in unexpected behaviour. 

eg.
```js
define: {
    '*': {
        set: function(value) {
            return JSON.stringify(value);
        },
        get: function (value) {
            return JSON.parse(value);
        }
    }
}
```
When any setter is defined an error is thrown, when a getter is defined it simply isn't called. 

The repo below shows how the getter isn't applied. To reproduce the setter issue, uncomment the setter.
https://github.com/nlundquist/canjs-default-setter 

If this is an expected incompatibility we might want to add a note in the docs.

**Comment by justinbmeyer** [comment]
Closing for https://github.com/canjs/can-map-define/issues/4
