### ISSUE TITLE
The value binding does not propagate updates on can.List for multiple select

### ISSUE THREAD

**Issue by ilyavf** [canjs/canjs#2368]
For select element with multiple type the $value binding only affects element on can.List set. The updates on can.List are ignored. [JS Bin](http://jsbin.com/juvoxe/1/edit?js,console,output)
```html
<select multiple {($value)}="myValues">
  <option value=1></option><option value=2></option>
</select>

var vm = { myValues: [1, 2] };

vm.pop();                  // does not update DOM

vm.attr('myValues', [1]);  // works correctly
```

The "change" event on the select element is not fired on can.List updates.

**Comment by justinbmeyer** [comment]
@ilyavf To be clear, you're saying that you expected `$value` to be cross bound to your values in the list.  

This won't actually work as `value` in the DOM is actually a string that just prints out the first selected `<option>`'s value.  So if `1` and `2` are selected, select.value is `"1"`.

This will be good to solve  in 3.0.  I'm not sure how to do it.  

jQuery's `.val` returns an array when used on `<select multiple>`.  It does it by looping through the options and getting the `.selected` ones around here: https://github.com/jquery/jquery/blob/e4fd41f8fa4190fbbb6cb98cf7ace64f6e00685d/src/attributes/val.js#L114

it seems `select.selectedOptions` is an array of the selected options.  But I doubt you can set it.

This might simply be a use case for either special handing of `$value` or a special helper like the old `can-value`.

We could make `can.attr` handle arrays.

Moving to: https://github.com/canjs/can-stache-bindings/issues/49
