### ISSUE TITLE
Stache expressions should support all methods

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2370]
I think these examples should work (they do nothing):

```html
<input ($change)="$element.trigger('foo')">
<input ($change)="%scope.attr('*foo', $element.val)">
<foo-bar ($inserted)="%viewModel.method()"></foo-bar>
```

http://jsbin.com/nujoniduje/edit?html,js,console,output

The issue seems to be that the scope read doesn't resolve as expected for these methods at 
[can/view/bindings.js#L264](https://github.com/canjs/canjs/blob/bbbb15f6a8def6f41af6b5788ab7dc80fc43fa95/view/bindings/bindings.js#L264).

**Comment by justinbmeyer** [comment]
this is very confusing.  Solve in 3.0 first, and then back-port to 2.3.  https://github.com/canjs/can-stache-bindings/issues/55

**Comment by justinbmeyer** [comment]
Those things should be available here: https://github.com/canjs/can-stache-bindings/blob/master/can-stache-bindings.js#L308
