### ISSUE TITLE
passing a plain data-object to can.stache won't work for can-value (radiobuttons)

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#2373]
since there is no good solutions for handling radio buttons with the new binding syntax i use `can-value` still for radio buttons.

in stache we can pass into the renderer function a plain javascript object. but this will not work with can-value.

this shows an easy example:
http://jsbin.com/qadewuyoye/1/edit?js,console,output

error caused by this line -> https://github.com/canjs/canjs/blob/0e270f65d321a34df6af781d356f67d12be2c65a/view/bindings/bindings.js#L373

here a working example by creating a can.Map before and pass this map into `can.stache? 
http://jsbin.com/wijoparole/2/edit?html,js,output

**Comment by justinbmeyer** [comment]
This should be solved by `can-stache-converters`.  We should still make sure POJOs work with `can-stache-bindings`.  Moving this issue there.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-stache-bindings #161](https://github.com/canjs/can-stache-bindings/issues/161) via [**ZenHub**](https://www.zenhub.com/)
