### ISSUE TITLE
can.view.bindings.event doesn't specify the arguments passed by default

### ISSUE THREAD

**Issue by ThanaShagrithaya** [canjs/canjs#2377]
https://canjs.com/docs/can.view.bindings.event.html

Documents: 

```
($click)="doSomething()"
```

But does not specify the arguments passed when called like:

```
($click)="doSomething"
```

**Comment by justinbmeyer** [comment]
This is mostly strategic.  Calling without `()` is deprecated.  It was the only thing possible with the old binding syntax: https://canjs.com/docs/can.view.bindings.can-EVENT.html

We supported the old, no `()` form so migrations would be easier.

Still worth explaining better.  Labeling as "documentation".

**Comment by justinbmeyer** [comment]
This is fixed in 3.0 as only call expressions should be used.
