### ISSUE TITLE
can.isArrayLike crashes on strings

### ISSUE THREAD

**Issue by imjoshdean** [canjs/canjs#2378]
http://jsbin.com/rotuqovomu/edit?html,js,console

Speaks for itself, like lodash, this should return `true` for strings. If we are in need of this for checking if things are array like objects, we should create `can.isArrayLikeObject` for that purpose.

**Comment by matthewp** [comment]
Interesting, does lodash just test for a `.length` that's a Number?

**Comment by imjoshdean** [comment]
lodash's `isArrayLike` will check if the value isn't null, whether or not the length property from the value is a proper length value, and isn't a function.

`isArrayLikeObject` checks if it is like an object and is like an array by it's `isArrayLike` standards as mentioned above.

**Comment by rjgotten** [comment]
That's actually not the only problem with `isArrayLikeObject`. It _also_ attempts to use an undefined variable `arr` instead of `obj` when checking for a function type.

**Comment by justinbmeyer** [comment]
fixing this in can-util.

**Comment by justinbmeyer** [comment]
fixed in 3.0. https://github.com/canjs/can-util/blob/master/js/is-array-like/is-array-like.js#L4
