### ISSUE TITLE
Old routes triggered in can.Control when using can-interrupt

### ISSUE THREAD

**Issue by taai** [canjs/canjs#2379]
Since there have not been any responses to the issue in canjs plugin [_can-interrupt_](https://github.com/canjs/can-interrupt) repository for almost two weeks, I'm posting here.

When I make a *Router* by using ```can.Control``` and creating ```can.route``` callbacks, two callbacks may be triggered – the one from previous route and the one from new route. I expect only the new route callback to be triggered (just like when the ```can-interrupt``` plugin is not being used).

Don't forget that the [_can-interrupt_](https://github.com/canjs/can-interrupt) (and _can.route.pushstate_) was used!

```html
<ul>
    <li><a href="/cars">All cars</a></li>
    <li><a href="/cars/1">Car 1</a></li>
    <li><a href="/cars/2">Car 2</a></li>
</ul>
```

```javascript
var Router = can.Control({
    'cars route': function(data) { console.log('All cars'); },
    'cars/:id route': function(data) { console.log('Car ' + data.id); }
});

var router = new Router(window);
can.route.ready();
```

I made an example here: https://jsfiddle.net/mumybx48/

So, after the ```/cars/1``` route was open, I don't want that callback to be triggered **again** when opening ```/cars``` route.

The original issue here: https://github.com/canjs/can-interrupt/issues/4
And there is a possible fix: https://github.com/tostercx/can-interrupt/commit/ff40d17c11cb1f20285a8569750d8503386e78b8

**Comment by matthewp** [comment]
I commented on the issue in can-interrupt.
