### ISSUE TITLE
Implement route change interruption in v3.0

### ISSUE THREAD

**Issue by taai** [canjs/canjs#2381]
I noticed that there is a version 3 coming... I would like the ```can-interrupt``` functionality already implemented in the routing, so it would be possible to interrupt route change. Currently ```can-interrupt``` plugin is bad.

**Comment by matthewp** [comment]
What is bad about it?

**Comment by taai** [comment]
I'm glad to have your attention. Read the issue #2379 !

**Comment by matthewp** [comment]
Ok, will read it.

**Comment by matthewp** [comment]
I responded to the original issue. Feel free to open an issue in https://github.com/canjs/can-route  if you think interrupting should be a core part of the router. Maybe it should be.

**Comment by justinbmeyer** [comment]
@taai I'd advise you against using control based routing.  It's being removed in 3.0.  We use AppViewModel based routing now.

**Comment by taai** [comment]
@justinbmeyer Do you mean that I should create my own setup without ```can.Control``` and/or ```can.Component```? I don't understand why it would be better than using the ```can.Control``` for that, of course, as long as it's the only object that is dealing with URLs directly...

Anyway, the point is that I would like to prevent route/URL from changing. It is needed to prevent user from closing a form without saving the data. This is how I see it:

* If route change is being called from the code (or by a click on a link), it should be stoppable without actual change of the URL.
* If user presses "back" button on the browser, the app should be able to change back the URL of the current route.
* If user moves away from the page, the window's event "beforeunload" should be used to tell that all data will be lost, if he will move away from the page.

I did read the routing code of canJS (the 2.3.x version) and I realized that it's super hard to make this happen. I could override the ```setState``` method to catch the URL change. But it is super hard to wrap my head around the ```can.route.attr``` to prevent the route from changing by calling ```can.route.attr``` from my code. It is because there is no [built-in] way to prevent ```can.Map``` from changing, and the ```change``` event will be triggered for every value in the map – and that's why there is this ```batch number``` used... It's too complicated for me to figure this out on my own.

At least there should be a separate ```can.route.transitionTo('car/:id', { id: 123 })``` method so it would be possible not to deal with complicated ```can.Map``` directly.

I like the way how [Ember](https://guides.emberjs.com/v2.5.0/routing/) is dealing with routing. They are using the "router.js" package (https://github.com/tildeio/router.js). It depends on 2 other packages so the whole thing is a bit bulky. And it doesn't touch the actual URL by itself, you have to change URL by yourself, for example, by using [History.js](https://github.com/browserstate/history.js/).
All this just for better routing in CanJS app – that's a lot of kilobytes! :grin: 

It would be nice to see routing syntax like ["router.js"](https://github.com/tildeio/router.js) built in CanJS. All that ```transitionTo().then()``` and ```transition.abort()``` are powerful things! Also the route ```enter``` and ```exit``` events should not be forgotten.
