### ISSUE TITLE
Why does can/util/attr/ set defaultValue?

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#2383]
https://github.com/canjs/canjs/blob/master/util/attr/attr.js#L160

Not sure why this is happening. If you do:

```js
var ta = document.createElement('div');
ta.value = 'foo';

ta.defaultValue === '';
```

I would expect the same behavior.

**Comment by matthewp** [comment]
Still curious about this.

**Comment by justinbmeyer** [comment]
probably some crazy browser quirk.  Might not be needed in 3.0.  In 3.0, we can probably remove it and then make sure we test supported browsers.  cc @phillipskevin
