### ISSUE TITLE
Instantiate can.Component on standard HTML element

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#2386]
This feature request follows from #648, #1680 and #1799 all of which consider various aspects and solution strategies to instantiating a `can.Component` without the burden of a custom element.

I have devised a working solution to instantiate components on standard elements in a personal fork of 2.3.x and I wanted to guage whether it would be suitable to fullfill the use-cases of the above 3 issues and possibly be accepted for merging into the official builds.

My solution is very similar to the old proposed spec for web components being instantiated on pre-existing, standard elements. It allows one to author a component on a standard element as follows:

``` html
<div can-tag="my-component"></div>
```

Bindings and nested content templates all work, as under the hood the `can-tag` attribute is wired up to call the original custom tag handler and everything that goes with it. You can still do something like the following, where my-component adds more complex logic than a simple list iteration to the templated items:

``` html
<div can-tag="my-component" {items}="items">
  <div>{{name}}</div>
</div>
```

Please let me know if you'd consider a pull request for this feature.
#### Implementation sketch

The implementation involves minimal changes to the stache parser, all isolated to `view/stache/stache.js`:

In the `end` method that finishes parsing the opening tag, I've expanded the `viewCallbacks.tag` check to not only consider the `tagName` but to also consider the presence and value of a `can-tag` attribute set in `state.node.attrs`. (The tag name itself takes precedence though, so you cannot use `can-tag` on an element that is already deemed custom.)

In the `close` method that parses the closing tag, normally the `viewCallbacks.tag` check is performed again, but at that point there is no access to the attribute collection. To resolve this problem and also do away with the duplicated check based on `tagName`, I expanded the data that is stored in `sectionElementStack` to a tuple object with a `type` member that holds the old string value and a `custom` member that holds the custom tag, i.e. , component name.

The `close` method now inspects the last element on that stack rather than re-running the `viewCallbacks.tag` check. If the last tuple on the stack has `{ type : "custom" }` it now grabs the component tag name that it should be using directly from the tuple.

**Comment by justinbmeyer** [comment]
@rjgotten that seems great!  A few questions:

- Do you mean `can-tag` not `can-as`?
- Could you make the pull request against: https://github.com/canjs/can-stache ?  We aren't adding new features to 2.3 and 3.0 is the next release.

**Comment by rjgotten** [comment]
Uhm yeah; It's `can-tag` and not `can-as`. Sorry about that. Part of my notes was typed up against an older version of my code. I switched to `can-tag` after I saw it mentioned in one of the other three issues I cited. (I corrected my notes for future readers.)

I can set up a pull request with the can-stache repository for 3.0. I'll have some time to work on that next monday. 

---

Regarding the 2.3 releases: I am still expecting to use this feature for a project running on 2.3, so if I'm looking at the possibility of merging the feature into my own private 2.3 fork, what would the odds be that patch releases for the 2.3 line will still contain large changes to `view/stache/stache.js` ?

**Comment by matthewp** [comment]
can/view/import has a `can-tag` feature that lets you to define a Component (or can.view.tag) that controls the inner scope.  Maybe this new feature could replace the need for that.

**Comment by justinbmeyer** [comment]
@rjgotten the patch releases for 2.3 will not contain changes to `stache.js`, only minor bug fixes.  

We're planning on making 3.0 highly compatible with 2.3 and have a "compatibility" mode for the jquery-specific changes.  Here's the current breaking changes: https://github.com/canjs/canjs/issues/2026#issuecomment-214504889 let me know if any of those seem troublesome to you.

**Comment by rjgotten** [comment]
@justinbmeyer 
Hmm.. nothing problematic there, I think. It'd be somewhat annoying to have to insert the jQuery-wrapped collections everywhere, but that's not something totally breaking.

Thanks.

@matthewp 
With some work, maybe. Not sure how compatible that particular feature is with what I wrote to instantiate components off of a tag. I think can-import actually does a bit more delegation under the covers with a promise and async loading, right?

(Btw. I've been wondering: what was the reason behind implementing can-import as a tag rather than a helper? Seems like the wrapping tag is not actually needed for anything.)

**Comment by justinbmeyer** [comment]
The wrapping tag is used to indicate progressive loading.

**Comment by rjgotten** [comment]
FYI; I'm running a bit behind on the pull request I'd promised because of some higher priority work that required my time. Not sure when I'll have time again.

**Comment by ilyavf** [comment]
+1

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-component #95](https://github.com/canjs/can-component/issues/95) via [**ZenHub**](https://www.zenhub.com/)
