### ISSUE TITLE
replace List property of map via define plugin

### ISSUE THREAD

**Issue by pilou** [canjs/canjs#2388]
I have a Map.
It has a property witch is a List, name it `items`.
It has another property, name it `itemCount`.
When i save the model the server reponds with the generated `items `array based on the given `itemCount`.
But the `items `is always merged I couldnt find a way to make it replace, like I've seen at https://canjs.com/docs/can.Map.prototype.define.set.html#section_Merging

Here is a jsbin example http://jsbin.com/dahiqevuka/edit?html,output

You can get 1 than 2, but not the opposite, because the merging.

Also the `Map.define.PROP.set` with the newVal param dont fit me, because I dont want to replace the '`items`' List, just its elements. And `Map.define.items.set` doesnt seems to be called after save

Is there any way to do this via Map or List configuration?

Workarounds I used:
Extending the List, and overiding inner functions :(
Legacy:
```
            _attrs: function (items, remove) {
                // Force remove as true, to delete extra unnecessary elements
                this._super(items, true);
            }
```
Current:
```
            _setAttrs: function (items, remove) {
                this._super(items, true);
            }
```

But now I wanna do it the right way

**Comment by justinbmeyer** [comment]
Yes, a custom type or setter with the define plugin can probably do it. If you can't figure it out, write back tomorrow and I can probably sketch up an example.

**Comment by pilou** [comment]
Thank You for your time!

Slightly modified the code, added some logging...
http://jsbin.com/gicevubisa/1/edit?html,output

As you can see the `set `is only called on `Map ` init, so I cant change the `merging `to `replace `.

My only workaround was to overwrite inner function of the `List`, but as its not a public API it can be changed over time which has happened before.

**Comment by pilou** [comment]
So, can you think about this plz?

**Comment by justinbmeyer** [comment]
Notes on JSBin:

- _get one from server_ -> returns one item in `.items`.
- _get two from server_ -> returns two items in `.items`.

Going back and forth always shows just 1 item because everything is always merged.

**Comment by justinbmeyer** [comment]
I think the best way to do this would be to overwrite `updated` like this:

http://jsbin.com/kididu/edit?html,output
