### ISSUE TITLE
can.stache performs lowercase conversion on property names for bindings

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#2391]
### Expected behavior
When writing a binding against a component viewmodel, bindings written against camelcase property names are bound to their equivalent camelcase properties in the viewmodel.

### Actual behavior
Camelcase bindings written in the template are converted to lower case by the templating engine and are bound to not-previously-existing lowercase properties in the viewmodel, leaving the original camelcase property at its initial value.

### Minimal reproducing case

http://jsbin.com/mesokabimi/1/edit?html,js,output

### Proposed resolution

I'd expect the templating engine to convert camelcase bindings to their equivalent spinalcase automatically.

**Comment by justinbmeyer** [comment]
HTML doesn't respect case sensitivity of attribute names. It's the DOM converting everything to lowercase. This is why all bindings (data and events) use dashes. 

We can probably give a warning if we see a capital letter. 

Change the fiddle to camel-case and it should work.

**Comment by rjgotten** [comment]
@justinbmeyer 
I know.

I'm asking if there's a way for binding attributes to be converted from `{camelCase}` to `{spinal-case}` automatically, during the parsing phase of the template as a convenience factor.

**Comment by justinbmeyer** [comment]
@rjgotten Yes, very likely.  We could probably see that happening here:

https://github.com/canjs/canjs/blob/master/view/stache/stache.js#L211

The difficulty is that `stache` doesn't know about `view bindings`.  We could have stache call some hook that `view bindings` would implement.  That way `view bindings` could could correct these sorts of things.

Alternatively, that hook could be part of can-view-parser. 

I think fixing this / making this easier would be great.  Adding the feature tag.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-view-parser/issues/13
