### ISSUE TITLE
CanJS subdomain SSL Certificate(s) expired

### ISSUE THREAD

**Issue by Bajix** [canjs/canjs#2393]
The SSL certificates on various CanJS subdomains are expired.

See https://connect.canjs.com

**Comment by justinbmeyer** [comment]
Thanks.  @daffl is taking a look at it.  Should be fixed shortly.

**Comment by justinbmeyer** [comment]
works for me in incognito now.

**Comment by Bajix** [comment]
That was fast. 👍

**Comment by daffl** [comment]
Good timing, I was just looking at it. Thanks for reporting!
