### ISSUE TITLE
Sort plugin is activated via .sort()

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#2398]
See this bin: http://jsbin.com/zabibun/2/edit?html,console,output

Essentially, after the changes made in https://github.com/canjs/canjs/pull/2257 there's no way for somebody to sort a list without the sort plugin setting up bindings.

The solution is to separate the two features via the api (comparator to bind, `sort()` for on-demand sorting) and provide an alternative solution for this issue: https://github.com/canjs/canjs/issues/2159

**Comment by justinbmeyer** [comment]
Why is there no way to sort a list without setting up bindings?  What specifically enforces that?

**Comment by akagomez** [comment]
https://github.com/canjs/canjs/blob/master/list/sort/sort.js#L236

I suppose that's not entirely true. You can sort a list without setting up bindings if you don't provide a comparator.

**Comment by justinbmeyer** [comment]
Why couldn't it do:

```
this.attr('comparator', comparator);
this._sort();
```

?

**Comment by akagomez** [comment]
Closed via #2399.
