### ISSUE TITLE
Observe.List add/remove pre/post processors

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#240]
I think it would be good to add ability to make pre and post processors for add/remove actions with Observe.List.

It will allow for example to implement for example such cases as:
1) before actually add items to list, they are saved to server (if for example it can't be done nothing will happen, and if it is items will have server generated ids)
2) conversion of items to some class besides Observe/Model.
3) ID and other stuff generation

**Comment by justinbmeyer** [comment]
moving to can-define.
