### ISSUE TITLE
Properties with set/get methods don't trigger change events

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#2402]
I noticed that a route property I was changing would update the DOM, but not the URL. The property had BOTH a `set` AND `get` method. When I commented the two define methods out the URL and the DOM both updated. 

I was able to recreate the example in this JSBin without `can.route`: http://jsbin.com/gakexi/edit?html,js,console

I'm not sure if this is a "bug" or not, but I thought I'd report it anyway.

**Comment by justinbmeyer** [comment]
It's not a bug. Getters are not serialized by default. Only serialized properties end up in the url.

**Comment by akagomez** [comment]
In my case `serialize` was set to `true`.

**Comment by justinbmeyer** [comment]
If that's the case, can you create a jsbin showing that happening and file it on: https://github.com/canjs/can-route

**Comment by justinbmeyer** [comment]
actually, this is probably fixed in 3.0 already.  It's broken now because `getter` properties don't fire "change" events.  But in 3.0, instead of binding on "change", a compute is used to wrap `.serialize()`.
