### ISSUE TITLE
Calling Helpers with call expressions.

### ISSUE THREAD

**Issue by isadovskiy** [canjs/canjs#2403]
> We're looking for a way to make call expressions only search helpers for faster lookup.  Proposals towards the bottom.

It looks like at the moment it's not possible to mix arguments and hashes for helpers in sub-expressions. Here is the fiddle: https://jsfiddle.net/e5gb322t/3/

As you can see, argument+hash combination works just for helper, which does not have sub-expression (using helper syntax).

With call syntax, mixing of arguments and hashes does not work at all.

**Comment by justinbmeyer** [comment]
You need to use commas in between arguments.

**Comment by justinbmeyer** [comment]
Also, stache sub expressions are called more like functions.  To call `foo`, you write `foo( arg1, arg2, propA=valueA propB=valueB)`: https://canjs.com/docs/can.stache.expressions.html#section_Callexpression

Here's a similar example to the one you made:

http://justinbmeyer.jsbin.com/vorote/2/edit?html,js,output

**Comment by isadovskiy** [comment]
> Also, stache sub expressions are called more like functions

Yeah. But in this case they will be looked up in context/viewmodel first (per call expressions documentation). So using helper syntax allows to lookup them in helpers first, which is a micro performance optimization from my point of view. So if I would like to execute helper, I would like to invoke it as a helper to lookup it in helpers instantly.

**Comment by justinbmeyer** [comment]
Ah, ok.  I'll check it out again.

**Comment by isadovskiy** [comment]
I was able to get my example works for call syntax by adding commas. 

I also figured out, for call syntax I need to lookup hash values in options.hashKey, rather than options.hash.hashKey (like in helpers syntax). But I think it introduces another issue. Now my helper's code depends on the way I'm invoking it. So basically helper should be invoked using just "call" or just "helper" syntax all through the code. Else it just won't work since hash key will be looked up in the wrong place. It's an issue for big projects and library projects...

**Comment by justinbmeyer** [comment]
@isadovskiy yes, this was a deliberate decision.  Call expressions are mostly intended to work well with arbitrary functions that might exist on view models or any other API. It's very common to want to do call arbitrary functions like:

```
someMethod(1234,{foo: "bar", zed: "ted"})
```

Call Expressions are designed to make this possible:

```
{{ someMethod(1234, foo="bar" zed="ted") }}
```

They allow multiple object arguments too:

```
someMethod(1234,{foo: "bar"}, {zed: "ted"})
{{ someMethod(1234, foo="bar", zed="ted") }}
```

And in a controlled order:

```
routeCurrent({page: 'recipe'}, true)
{{ routeCurrent(page='recipe', true) }}
```

As this was an entirely new syntax, we decided flexibility was more important than interop with existing helpers.  

If this is an issue, you might want to checkout how we manage this in `routeCurrent`: https://github.com/canjs/can-stache/blob/master/helpers/route.js#L24

You can sniff out the type of expression and make a helper work both ways.  It's ugly, but you can probably make a wrapper function out of it:

```
registerHelper("something", makeWorkAsCallAndHelperExpression(function(){
   // logic that works with CallExpressions
}) );
```

I'd even support adding something like this as a utility in 3.0 if people would like it.

**Comment by isadovskiy** [comment]
yes, totally makes sense. So looks like we will follow https://github.com/canjs/can-stache/blob/master/helpers/route.js#L24 approach.

**Comment by isadovskiy** [comment]
But still wondering if it makes sense to have sub-expressions and hashes with old helpers syntax? Or helper lookup order could be worked around in some other way?

**Comment by justinbmeyer** [comment]
Yeah, I've not thought about providing a way to make a helper faster to lookup.  I optimized call expressions away from looking in helpers because they tend to be calling things on the VM.  This is why they look at helpers last.  

I'm going to have think about this some.  Do you have any idea?

**Comment by isadovskiy** [comment]
I think you can introduce some special symbol prefix before function in call expression, which will tell engine to lookup function among helpers first. This aligns with another similar concepts in the canjs.

**Comment by justinbmeyer** [comment]
@isadovskiy maybe we could do something like:

```
{{%helpers.theHelper(items)}}
```

?

**Comment by isadovskiy** [comment]
@justinbmeyer yes, looks like good solution for me.

**Comment by justinbmeyer** [comment]
@isadovskiy I would write that like:

```
{{ %helpers.foo( %helpers.bar( %helpers.buz(0, buz=1), bar=2), foo=3) }}
```

Yeah, but assuming you don't have a `foo`, `bar` or `buz` in your scope (or your scope isn't massively deep), this shouldn't really be a problem.

**Comment by isadovskiy** [comment]
yes, missed commas. But in general yes, should work. It lines up wi the similar syntax in https://canjs.com/docs/can.view.bindings.event.html#sig__VIEW_MODEL_EVENT___CALL_EXPRESSION_

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-stache #182](https://github.com/canjs/can-stache/issues/182) via [**ZenHub**](https://www.zenhub.com/)
