### ISSUE TITLE
Unnecessary code in stache helpers

### ISSUE THREAD

**Issue by taai** [canjs/canjs#2404]
I found unnecessary code in stache helpers. Here:
https://github.com/canjs/canjs/blob/master/view/stache/mustache_helpers.js#L4

```JavaScript
var resolve = function (value) {
	if (utils.isObserveLike(value) && utils.isArrayLike(value) && value.attr('length')) {
		return value;
	} else if (can.isFunction(value)) {
		return value();
	} else {
		return value;
	}
};
```

The value is being returned "as is" only when it's not a function, so I think this is more efficient:

```JavaScript
var resolve = function (value) {
	return can.isFunction(value) ? value() : value;
};
```

And what's with the declaring functions as variables?! Let's do it right!

```JavaScript
function resolve(value) {
	return can.isFunction(value) ? value() : value;
}
```

**Comment by justinbmeyer** [comment]
@taai thanks for the fix.  IMO, there's nothing more right about declarations instead of expressions.  https://javascriptweblog.wordpress.com/2010/07/06/function-declarations-vs-function-expressions/  except for those cases when a debugging tool can't give an appropriate name to the function.
