### ISSUE TITLE
React PropTypes for can.Components

### ISSUE THREAD

**Issue by imjoshdean** [canjs/canjs#2406]
Been working with ReactJS a lot lately, and while I don't normally like the idea of copycatting other libraries, this one feels really helpful for developers.

https://facebook.github.io/react/docs/reusable-components.html

PropTypes have been described to me as "runnable documentation for your team," a way to make sure components are utilized correctly and that if there are particular properties that need to be passed into components, the developer finds out ~about it while looking at the browser on localhost~ with a warning in the developer tools. 

It would be nice to have an implementation of this within can.Component. I know we could technically do this with view models and the define plugin, but that doesn't feel like an appropriate place for it and wouldn't baked in by default, which is what I think something like this should be.

**Comment by justinbmeyer** [comment]
What does "while looking at the browser on localhost" mean?  Do you mean runtime errors get thrown?

Why wouldn't the define plugin be the appropriate place?  It would effectively be a validation on what the view model needs to be `init`ed with?

`can-component` could reach into the view model pretty easily and do this.

**Comment by imjoshdean** [comment]
The core implementation is relatively simple and would mimic ReactJS pretty much 1 to 1

```js
import { default as Component, PropTypes } from 'can/component';

Component.extend({
  tag: 'custom-button',
  props: {
    onClick: PropTypes.function.isRequired,
    name: PropTypes.string
  }
});
```

**Comment by imjoshdean** [comment]
@justinbmeyer Updated my comment. A `console.warn` should be called in development mode.

I disagree with the define plugin being the appropriate place for a few reasons.

1.) It is a plugin, this is something that I feel should be baked in by default. The counter-argument has been made to me that define will become core soon but...
2.) define's focal point is maps, which aren't necessarily the focal point of components. Properties we pass into a component _are_ a focal point of components though.
3.) The type of validation done on maps and define is not developer-centric. The purpose of PropTypes is very specifically developer-centric validation of component use.

**Comment by imjoshdean** [comment]
I also feel like I should emphasize that I do not think this should be some component plugin, and should be built within Component core.

**Comment by justinbmeyer** [comment]
@imjoshdean 

> define's focal point is maps, which aren't necessarily the focal point of components. 

A big part of CanJS is that components aren't the focal point of an application, the easily unit testable view model is.  Components only exist to combine a view model, template and tag.

The proposal would make components the focal point, which goes against good engineering practices.  Furthermore it creates a lot of redundancy.  Consider having to define all your properties in your view model:

```js
DefineMap.extend({
  onClick: 'function',
  name: 'string'
})
```

And then to repeat that in a component:

```
Component.extend({
  tag: 'custom-button',
  props: {
    onClick: PropTypes.function.isRequired,
    name: PropTypes.string
  }
});
```

Also, how is this testable?

Now we could relatively easy add better validation primitives to the define plugin:

```
MyVM = DefineMap.extend({
  onClick: {
    type: 'function',
    validate: PropTypes.function.isRequired
  },
  name: {
    validate: 'string'
  }
})
```


And then still unit test it:

```
new MyVM({name: 123}) //-> throws warnings, errors, or has a .valid() method
```

In general, good validations systems are able to be as close to the source as possible, but scale upwards.

It makes the most sense from a technical standpoint, and from a best-practices standpoint to make strong validation a feature of Maps.  

> The type of validation done on maps and define is not developer-centric.

I don't think a validation on a map versus a component would matter that much, especially if everything else happens on the map.

**Comment by matthewp** [comment]
I think it would be a good start to add a `required` property in the define definition. `type` already covers type validations. I wouldn't want to attempt to do anything more validation related, and leave that to a plugin like can-validate if someone needs more.

**Comment by justinbmeyer** [comment]
Moving to https://github.com/canjs/can-define/issues/62.  @imjoshdean let me know if this works.  I think `required` is a good idea.  It just belongs in the view model.
