### ISSUE TITLE
Add a “Migrating to 2.3” guide

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2409]
It would be really helpful if [this page](https://canjs.com/guides/migrating.html) in the 2.3 docs had info about things to look out for when upgrading to CanJS 2.3.

**Comment by justinbmeyer** [comment]
There technically shouldn't be anything to look out for as 2.3 is backwards compliment. There should only be new feature.  We can link to the 2.3 release article. 

If there are things to look out for, please let us know.

**Comment by chasenlehara** [comment]
There were some things that we had to change in our code to upgrade to 2.3, but I think most/all of them were bugs in our code that just happened to work in 2.2 (like calling `this.prop()` instead of `this.attr('prop')`. I’ll write those things up as soon as I get a chance.
