### ISSUE TITLE
can.Map.List.filter event spam

### ISSUE THREAD

**Issue by gsmeets** [canjs/canjs#2410]
I used a filter within a getter. When the source list got replaced for a new list, it spammed a length change event on my getter for each item in the list.

I managed to work around this by attr the source list length in my getter and just use can.map on the source list. 

Still seems like this is a bug though. Don't have a simple repro case atm, let me know if this is something you wish to investigate.

**Comment by justinbmeyer** [comment]
Yes. Please send us a test case.

**Comment by justinbmeyer** [comment]
@gsmeets any updates? Thanks!

**Comment by gsmeets** [comment]
Totally missed this one. Will have a look what this was about.

**Comment by justinbmeyer** [comment]
@gsmeets please let us know if you have a test case.  Otherwise, I'm going to close.  Thanks!
