### ISSUE TITLE
2.3.24 stache observables are not reflected in the object change event loop 

### ISSUE THREAD

**Issue by chikkalingaiah** [canjs/canjs#2414]
2.3.24 stache observables are not reflected in the object change event loop.
Please see the JSBin example of the issue, 2.3.7 works fine 
http://jsbin.com/funebi/edit?html,js,console,output
This may not be a bug but new implementation in 2.3.24, just wanted to make sure different behavior b/w 2.3.24 compared to 2.3.7 is expected change.

**Comment by justinbmeyer** [comment]
Anyway you can make that example more simple?  Are components needed?  

On first glance I don't know what to look for.  I'm sure I could figure it out, but the easier it is for me to understand, the faster I tend to look at issues.

**Comment by justinbmeyer** [comment]
Without looking at the example much, my guess is that you're setting something and expecting a compute's value to be updated immediately. That doesn't happen anymore.  I think there's a related issue explaining why, but this is as close as I found: https://github.com/canjs/canjs/issues/2323


In short,  batches are "breadth first" instead of "depth first".  A change happens, all computes are updated, but any listeners aren't fired until after the entire batch completes.

**Comment by chikkalingaiah** [comment]
I need 3 components hierarchy to simulate the behavior, I have simplified the example a bit.
Question I have is on this piece of code:
'{viewModel} someObject': function() {
        this.viewModel.attr('section', "showGrandChild");
      }
In above code I am listening to change in "someObject" and updating "section" with new value "showGrandChild" which injects grand-child component on DOM.
{{#is section "showGrandChild"}}
      <grand-child {length}="length"></grand-child>
    {{/is}}
In "inserted" event of "grand-child" I am updating "inputBoxes" array attribute and trying to see whether it reflects on DOM immediately in next line, but it does not reflect on DOM.

But if I do same thing in next event loop of "someObject" change by using 0milli-second setTimeout, grand-child DOM is updated immediately:
'{viewModel} someObject': function() {
        setTimeout(()=>{this.viewModel.attr('section', "showGrandChild")},0);
      }

**Comment by justinbmeyer** [comment]
Can you tell me what I'm looking for?  I click a button and then a whole bunch of input boxes show up.  What should or shouldn't I see?  Why are 5 input boxes needed?

**Comment by chikkalingaiah** [comment]
$('.input-boxes').length is 0 in "inserted" event  of grand-child, when 
'{viewModel} someObject': function() {
this.viewModel.attr('section', "showGrandChild");
}

 But if I insert grand-child in next event-loop using setTimeout $('.input-boxes').length is 6. 
'{viewModel} someObject': function() {
setTimeout(()=>{this.viewModel.attr('section', "showGrandChild")},0);
}

**Comment by justinbmeyer** [comment]
Ah yeah.  This is what I thought was going on.   

When this runs:

```
this.viewModel.attr('section', "showGrandChild");
```

a batch is created, say batch `6`.  All of it's listeners will fire, including a listener that inserts `grand-child` an triggers `inserted` on it.

However, in `inserted`, which is still running in batch `6`, some actions take place that will fire other events:

```
this.viewModel.attr('inputBoxes').push(true);
```

Those events are queued for the next batch (`7`), and not dispatched immediately, so the DOM never updates.  

You can use `can.batch.afterPreviousEvents` to be called after any previous actions have completed:

http://justinbmeyer.jsbin.com/citacohapo/edit?html,js,console,output

**Comment by chikkalingaiah** [comment]
Thanks for the reply, but why do I see event being queued up only in this scenario, if I trigger showGrandChild from child directly the observable changes are reflected immediately . Basically my question is when to expect events to be queued up vs when not.
Please see example: http://jsbin.com/jececi/edit?html,js,console,output
Here "Show Grand Child 3 level hierarchy" button trigger does not reflect the observable changes immediately but "Show Grand Child 2 level hierarchy" does immediately.
