### ISSUE TITLE
Add alias for child viewModel

### ISSUE THREAD

**Issue by gsmeets** [canjs/canjs#2416]
There's no way to alias the child event viewmodel. If I want to refer to it I have to alias the viewmodel with a reference binding:

```
<my-foo>
    <my-bar *bar
        (some-event)="doSomething(*bar)"
    />
/>
```

I'd like to reference to that *bar implicitly, just like I can reference the current scope with `this` or `.`.

**Comment by justinbmeyer** [comment]
You can use `%viewModel`

**Comment by gsmeets** [comment]
Did I miss that in the docs? Or is it undocumented?

**Comment by justinbmeyer** [comment]
Referenced here: https://canjs.com/docs/can.stache.key.html
