### ISSUE TITLE
jQuery modifier bug with (el) -> el.someFunction()

### ISSUE THREAD

**Issue by foxdonut** [canjs/canjs#2417]
Context: we are working with long-time CanJS code, around version 1.0.7 or so. Back then, it was idiomatic, or, at least, it was a practice that was not on its way out as it seems to be today, to use

```
<div {{(el) -> el.someFunction()}}>
```

Now, when `someFunction()` calls `el.html(htmlString)`, and `htmlString` does not have a single root node, such as:

```html
var htmlString = '<li>One</li><li>Two</li><li>Three</li><li>Four</li>';
```

Then, when using `can.view.modifiers.js`, the `html` function is "decorated" by CanJS and the result is incorrect.

Here is a code example illustrating the issue:

http://codepen.io/foxdonut/pen/PzNXOW?editors=1010

A workaround is to move the code out of `{{(el) -> el.someFunction()}}` and into the JavaScript code, such as into the `init` function.

This is a somewhat obscure issue. I also understand that the `(el) ->` syntax is on its way out, as are CanJS modifiers themselves. Nevertheless, this caused a bug in our production code. We'll be using the workaround mentioned above, but I still wanted to document this issue in case anyone else encounters similar problems. When some code calls `element.html(...)` and the result is not what you expect, it can be difficult to figure out why this is happening.

**Comment by matthewp** [comment]
Thanks, if you'd like to fix the bug you can do so in [can-ejs](https://github.com/canjs/can-ejs).
