### ISSUE TITLE
Feature request: Negated bindings

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#2419]
I just ran across the situation where I have a `selected` property on a Map, which parts of my UI need to bind against the `disabled` DOM property of buttons, fields, and fieldsets.
However, while some parts need to bind it in such a way that the UI is disabled when the selected property is `true`, other parts need to bind it so that the UI is disabled when the selected property is `false`.

I really don't like the idea of creating a complement negated `unselected` property on the Map in question, so what I'm looking for is some way to provide a boolean negated binding.

And then I got to thinking; wouldn't it be nice if we could just do `{$disabled}="^selected"` and have that work...

**Comment by gsmeets** [comment]
Except that ^ already has semantics. ;) I think there's already an issue floating about where this was brought up...

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-stache/issues/17

You could create a `not` helper like:

```
can.stache.registerConverter("not",{
  get: function(source){
    return !source();   
  },
  set: function(newVal, source){
    source(!newVal); 
  }
});
```

```
{$disabled}="not(selected)"
```
