### ISSUE TITLE
Add indeterminate state to checkbox value binding.

### ISSUE THREAD

**Issue by ilyavf** [canjs/canjs#2423]
According to [caniuse](http://caniuse.com/#search=indeterminate) its well supported.

Mozilla docs [here](https://developer.mozilla.org/en-US/docs/Web/CSS/%3Aindeterminate)

```
checkbox.indeterminate = true
```
![image](https://cloud.githubusercontent.com/assets/1895948/16277185/d66072c0-387f-11e6-83d8-e9aa2e9ff81b.png)

**Comment by ilyavf** [comment]
hm... maybe its as simple as this:
```
<input type="checkbox" ($checked)="isChecked" ($indeterminate)="isPartlyChecked" />
```

**Comment by justinbmeyer** [comment]
is it?  does that work?  Closing b/c it should.  I'll reopen if not.
