### ISSUE TITLE
can.List is an unspecified dep of can.Map

### ISSUE THREAD

**Issue by alexisabril** [canjs/canjs#2424]
https://github.com/canjs/canjs/blob/master/map/map.js#L331

We should have a `can/list/` in the `steal()` statement at the top.

**Comment by matthewp** [comment]
This is gone in can-map: https://github.com/canjs/can-map/blob/master/can-map.js#L104

**Comment by justinbmeyer** [comment]
`can/list` itself depends on `can/map`.  So we can't fix it that way w/o creating a cycle.  Closing as this is resolved in 3.0.

**Comment by alexisabril** [comment]
@matthewp I believe we do have 2.3.x releases for critical bugs down the road(I realize this is non-critical).

@justinbmeyer Any reason not to just leave this open for any future 2.3.x release, should it occur? It's an easy fix we can ship with a critical release.

**Comment by justinbmeyer** [comment]
I labeled it "needs a hero".  You'll see other closed features/bugs with this label that the core team isn't indenting to fix.  We'll accept a patch if someone provides it.
