### ISSUE TITLE
Regressions in the `this` / context value of `can.compute([settings])`

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#2426]
Before the prototype-based `can.Compute` was introduced, it was possible to configure the context of a compute created via `can.compute([settings])` via a `context` setting. This setting is no longer available.

Also, when not configured otherwise the context used to point to the settings object itself. Now it points to the instance of `can.Compute`.

**Comment by matthewp** [comment]
Are you talking about [this signature](https://canjs.com/docs/can.compute.html#sig_can_compute_initialValue__settings__)?  How were you able to pass the context?

**Comment by rjgotten** [comment]
@matthewp 
Yes. That's the one.
In older CanJS versions you could (accidentally) pass a context as a `context` member on the settings object. And if you did not pass a context member, the context would be set to the settings object itself.

**Comment by matthewp** [comment]
Can you give a code example of what that looked like?

**Comment by rjgotten** [comment]
@matthewp 

A heavily, *heavily(!!)* trivialized example would be:

```js
var
  obj = { prop : "foo" },
  computed = can.compute( undefined, {
  get : function() { return this.prop; }
  set : function(value) { this.prop=value; }
  context : obj
  }
});
```

As for real-world applicability: I developed a two-way binding framework for use with EJS, far before CanJS offered native two-way binding in (mu)stache, which offered custom binders acting as a kind of micro-controller to handle, e.g. two-way binding to range sliders, date-pickers, or `<select>` elements with dynamic `<option>` and `<optgroup>` members.

Under the hood, these micro-controllers were really just assembled into computes with added instance members and methods, e.g.

```js
function makeFormBinder( element, options, type ) {
  var
    mixin,
    nodeName;

  element = can.$( element );

  if ( type == null ) {
    nodeName = ( element.prop( "nodeName" ) || "" ).toLowerCase();
    switch ( nodeName ) {
      case "select" : type = "select"; break;
      case "input"  : type = element.attr( "type" ); break;
      default       : type = ""; break;
    }
  }

  mixin = {
    element : element,
    on      : function( update ) {
      can.bind.call( options.element, options.event, update )
    },
    off     : function( update ) {
      can.unbind.call( options.element, options.event, update )
    }
  };

  options = can.extend(
    {},
    formBinders[ "default" ],
    formBinders[ type ],
    options,
    mixin
  );

  if ( options.init ) {
    options.init();
  }

  return can.compute( options.get.call( options ), options );
};
```

**Comment by matthewp** [comment]
Ah, ok thanks, so it was a property on [computeSettings](https://canjs.com/docs/computeSettings.html). It's not documented but I think that's a fair thing to add.

**Comment by matthewp** [comment]
Moved this to a [can-compute issue](https://github.com/canjs/can-compute/issues/13), thanks!
