### ISSUE TITLE
Add possibility to specify an explicit scope for <content> tags

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#2429]
Currently, a component that iterates over a list has to use `leakScope:true` when it uses a `<content>` subtemplate to delegate rendering of the list items back to the component's consuming view. Otherwise the consuming view will not be able to access the iteration item.

However, setting `leakScope:true` has several other undesirable effects, such as exposing the entire inner view model state of the component to the outer world.

Therefore I propose that it becomes possible for `<content>` tags to have an explicit scope set. 
When `leakScope:false` this scope (and *only* this scope; not its stack of ancestors) should be combined with the consuming view's scope stack to form the scope stack used to evaluate the `<content>` subtemplate.

E.g.

_component.stache:_
```html
<ul>
  {{#items}}
    <li><content can-scope="." /></li>
  {{/items}}
</ul>
```

_consumer.stache:_
```html
<my-component {items}="items">
  <!-- will take the name from the content item scope -->
  <span>{{name}}</span> 
  <!-- Will take the name from the consumer view's scope. -->
  <span>{{../name}}</span>
</my-component>
```

Something very similar is already being used to implement `leakScope:true`, so I assume this should be very feasible.

---

[EDIT]
Yup. Very feasible. Took me maybe 10 minutes to add into the CanJS build that I'm currently using on my projects. It's a ridiculously simple change. Simple matter of using `scope.add` and `scope.get` to construct the scope and you're done:

```js
if (renderingLightContent) {
    if (lexicalContent) {
        var scope = el.getAttribute( "can-scope" );
        if (scope) {
            lightTemplateData = {
                scope: componentTagData.scope.add( contentTagData.scope.get( scope )),
                options: componentTagData.options
            }
        } else {
            lightTemplateData = componentTagData;
        }
// ( ... )
```

---

[EDIT 2]
I found that it would also be beneficial to be able to pass along non-context members, such as the special `%index` or `%key` properties. Since then I've expanded my implementation and adopted an expression parsing hack from `can-href` to be able to parse expressions with an optional hash of non-context members to propagate into the subtemplate, like so:

```html
<ul>
  {{#each items}}
    <li><content can-scope="{. %index=%index}" /></li>
  {{/each}}
</ul>
```

Code's a bit more involved now. Let me know if there's interest to merge this and I'll try to set up a pull request. (I have atleast one other issue for which I should also still do so. So hopefully I'll be able to arrange for some time to get that done, this time over.)

**Comment by matthewp** [comment]
Thanks @rjgotten, couple of comments:

1) Light DOM should already have the template's scope when using `leakScope: false`. If not it's a bug.

2) Using `<content>` inside of each is not supported, it doesn't work in web components and only works by mistake in CanJS.  `<content>` is not a template, it's a way to insert light DOM in a place inside of the local DOM (aka the shadow DOM).  `<content>` is actually be deprecated from web components and being replaced by something called slots, which I think we want to [implement in can-component](https://github.com/canjs/can-component/issues/4), so I don't think further changes to `<content>` are a good idea.

**Comment by justinbmeyer** [comment]
There is a slot proposal we can do this in.

**Comment by rjgotten** [comment]
> @matthewp
> 1) Light DOM should already have the template's scope when using `leakScope: false`. If not it's a bug.

Yes, it does have the *template* scope stack.

This issue advocates adding a way for a component to explicitly push another scope onto this stack, so you can opt to publish only *part* of an internal scope stack for use by the light DOM, instead of having to rely on `leakScope:true` which leaks all the internal state.

> @justinbmeyer 
> There is a slot proposal we can do this in.

Refresh my memory; is that the one for which I offered my `<can-region />` implementation as a candidate? If so; I still have to build this particular work I've done for `<content/>` into my region implementation anyway. I could kill two birds with one stone in that case.

**Comment by gsmeets** [comment]
@justinbmeyer is referring to #2278.

**Comment by justinbmeyer** [comment]
Moving into: https://github.com/canjs/can-component/issues/4
