### ISSUE TITLE
Multiline comments?

### ISSUE THREAD

**Issue by Schweinepriester** [canjs/canjs#2432]
<https://canjs.com/docs/can.stache.tags.comment.html>

How do you write multiline comments (or: comment out code), including tags from can.stache?

If there are docs for that, i'm happy with just a link!

Thanks! :)

**Comment by justinbmeyer** [comment]
There currently isn't a way to do this.  We might be able to make something like `{{! {{foo}} {{bar}} }}` work.

**Comment by justinbmeyer** [comment]
closing for issue in can-view-parser
