### ISSUE TITLE
Live/Two-way binding with nested components

### ISSUE THREAD

**Issue by Macrofig** [canjs/canjs#2433]
I posted a question in [Gitter](https://gitter.im/canjs/canjs?at=5783edcc1ca34a944ef2891a) regarding live-binding between multiple nested components.  It seems that binding a boolean value travels all the way down but does not update back up.

## Setup

So, this is my main template:

```mustache
<button type="button" can-click="triggerReload">Reload</button>
<main-component reload="{reload}"></main-component>
```

The `main-component`'s template looks like...

```mustache
<sub-component reload="{reload}"></sub-component>
```

By clicking on the `Reload` button, we update the `reload` property to `true`. This should travel all the way down to `sub-component` which fetches its own data. When the data is retrieved, `sub-component` should set `reload` back to `false` so we can re-fetch data again in the future.

> I have a workaround that I can use for the time being. But I should mention that I don't recommend component's fetching their own data. Unfortunately, we're kinda stuck with this for now.

## Problem

Using the latest CanJS, changing the property from above will update down. But when the sub-component updates the value, the change does not propagate back up to the top.

Thanks to @web-mech for explaining that it could be that live-binding to primitives doesn't really work. Although, my understanding is that CanJS would wrap these values in a compute so it *should* work. But I could be wrong.

~~Furthermore, in using the workaround, I found out that my sub-component cannot be the one to define an object; it must be defined by the top most component. This makes sense-ish. Except for this: https://canjs.com/docs/can.view.bindings.twoWay.html#section_Initialization Maybe I misunderstood what should happen when the parent is undefined but the child is defined?~~ This was related to old syntax. New two-way binding syntax works fine.

## JSBin Links

- Latest [broken]: http://jsbin.com/joyofu/edit?html,js,output
- Latest, Workaround [works]: http://jsbin.com/bamapo/1/edit?html,js,output
- Latest, workaround, sub-component define [broken]: http://jsbin.com/cuzavu/edit?html,js,output
- Latest, new binding syntax [broken]: http://jsbin.com/qamada/1/edit?html,js,output
- 2.2.9 [REALLY broken]:  http://jsbin.com/ninibot/2/edit?js,output

**Comment by justinbmeyer** [comment]
Using a timeout works: http://justinbmeyer.jsbin.com/jedice/1/edit?html,js,output

**Comment by justinbmeyer** [comment]
So does `can.batch.after`: http://justinbmeyer.jsbin.com/jedice/2/edit?html,js,output

It's because the value is changing twice w/i the same batch so the 2nd event is ignored.  You need to make sure it happens after the batch completes.

**Comment by Macrofig** [comment]
@justinbmeyer Is it not possible for Can to fire off any events after batch is completed? Is it a problem of knowing which setter to call? 

I guess I'm not exactly sure why I need to add code that checks for the batch. Passing properties around like this should be consistent regardless of the nesting, no?

**Comment by justinbmeyer** [comment]
I'm not sure what you mean. Yes, can can fire off events. I don't know what you mean by setter to call. What properties are being passed? 

It's certainly a bug, but it's because the same object is changing within a batch back to its original value.

**Comment by Macrofig** [comment]
> Passing properties around like this

I was referring to the my jsbin example... of passing properties up/down a deeply nested set of components.

> It's certainly a bug

Ok, that's what I was trying to figure out. I wasn't sure if you were saying this is correct behavior or not. Thanks!

**Comment by Macrofig** [comment]
Regarding my secondary issue...

> Furthermore, in using the workaround, I found out that my sub-component cannot be the one to define an object; it must be defined by the top most component. 

I did a bit more poking around on this and it seems to be unrelated so I'll create a separate issue.

**Comment by justinbmeyer** [comment]
I think this can be closed?  I'm not sure what the issue is. Seems like new binding syntaxes work with after.

Please re-open if I'm missing something.

**Comment by Macrofig** [comment]
Yea, using `after` works but I have two concerns.

First, the mental model for how this works is deceiving. I understand that there are multiple updates going on, even though the trigger for these updates is a single action. I feel like this is a confusing API.  (That said, I need to do test this out with latest 3.0 stuff to see if it is still an issue)

Second, is this behavior documented somewhere and maybe I just missed it? 

> When a change triggers just one compute to update, we won't need to use `after`. But because we have nested computes, we need to use `after`.
