### ISSUE TITLE
Live/Two-way binding with nested components

### ISSUE THREAD

**Issue by Macrofig** [canjs/canjs#2434]
I posted a question in [Gitter](https://gitter.im/canjs/canjs?at=5783edcc1ca34a944ef2891a) regarding live-binding between multiple nested components.  It seems that binding a boolean value travels all the way down but does not update back up.

## Setup

So, this is my main template:

```mustache
<button type="button" can-click="triggerReload">Reload</button>
<main-component reload="{reload}"></main-component>
```

The `main-component`'s template looks like...

```mustache
<sub-component reload="{reload}"></sub-component>
```

By clicking on the `Reload` button, we update the `reload` property to `true`. This should travel all the way down to `sub-component` which fetches its own data. When the data is retrieved, `sub-component` should set `reload` back to `false` so we can re-fetch data again in the future.

> I have a workaround that I can use for the time being. But I should mention that I don't recommend component's fetching their own data. Unfortunately, we're kinda stuck with this for now.

## Problem

Using the latest CanJS, changing the property from above will update down. But when the sub-component updates the value, the change does not propagate back up to the top.

Thanks to @web-mech for explaining that it could be that live-binding to primitives doesn't really work. Although, my understanding is that CanJS would wrap these values in a compute so it *should* work. But I could be wrong.

Furthermore, in using the workaround, I found out that my sub-component cannot be the one to define an object; it must be defined by the top most component. This makes sense-ish. Except for this: https://canjs.com/docs/can.view.bindings.twoWay.html#section_Initialization Maybe I misunderstood what should happen when the parent is undefined but the child is defined?

## JSBin Links

- Latest [broken]: http://jsbin.com/joyofu/edit?html,js,output
- Latest, Workaround [works]: http://jsbin.com/bamapo/1/edit?html,js,output
- Latest, workaround, sub-component define [broken]: http://jsbin.com/cuzavu/edit?html,js,output
- Latest, new binding syntax [broken]: http://jsbin.com/qamada/1/edit?html,js,output
- 2.2.9 [REALLY broken]:  http://jsbin.com/ninibot/2/edit?js,output

**Comment by matthewp** [comment]
@justinbmeyer did you close this without comment on purpose? Going to assume not.

**Comment by Macrofig** [comment]
Probably because it is a duplicate of #2433 Github was acting up when I created the first one.
