### ISSUE TITLE
variables in script tags don't get processed

### ISSUE THREAD

**Issue by justthismorning** [canjs/canjs#2437]
variables in script tags within .stache templates do not get processed. 

```
<script type="text/javascript">
console.log({{param}});
</script>
```

**Comment by rjgotten** [comment]
Should script tags in general even be processed when inserted as nodes?
(Afaik jQuery contains some kind of workaround for this, but it's not a given.)

**Comment by gsmeets** [comment]
I don 't thinking that's supported. And that's a good thing. You shouldn't include scripts through the view, and you shouldn't write dynamically generated scripts.

**Comment by pYr0x** [comment]
closed by forum thread.
http://forums.donejs.com/t/pass-variables-to-script-content-in-stache-files/356
