### ISSUE TITLE
Conditional attribute values do not get updated

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#2439]
`value` will not be updated when `count` changes in this scenario:

```
  <input type="text" {{#if count}}value="{{count}}"{{/if}} />
```

See this example: http://jsbin.com/lokati/3/edit?html,js,output

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-stache #183](https://github.com/canjs/can-stache/issues/183) via [**ZenHub**](https://www.zenhub.com/)
