### ISSUE TITLE
viewModel dispatch only accepts array as second parameter

### ISSUE THREAD

**Issue by gsmeets** [canjs/canjs#2440]
Couldn't dispatch on viewModels handle single objects as well? This has confused me a few times already. i.e. handle:

```
this.dispatch( "foo", fooData );
```

as if it was:

```
this.dispatch( "foo", [ fooData ]);
```

**Comment by justinbmeyer** [comment]
It's not worth adding a branch in dispatch (which is canjs's most performance sensitive code). Perhaps a different version can be added to maps.

**Comment by justinbmeyer** [comment]
please open in can-define if you'd like to see this in 3.0.  Thanks!
