### ISSUE TITLE
Provide can.Map interface (similar to .attr) that includes derived properties

### ISSUE THREAD

**Issue by kylegifford** [canjs/canjs#2441]
Currently, `can.Map.attr()` only exports non-derived properties when it creates a raw object. We have a need to pass both derived and non-derived properties to a third-party library, but there is currently no interface for this.

**Comment by justinbmeyer** [comment]
Use serialize:true. And use the serialize method. This is a duplicate issue.

**Comment by matthewp** [comment]
This is a valid new issue.  What is being talked about here is a sort of "meta" API that ignored enumerability. You might not want your derived properties to be serializable but need to access them anyways in special cases. I would suggest something like `Map.getRawObject(map)` (not a great name)  that ignores enumerability similar to how Object.getOwnPropertyNames ignores enumerability.

**Comment by justinbmeyer** [comment]
closing for issue in can-define.
