### ISSUE TITLE
Scoping issue when instantiating multiple can.Components

### ISSUE THREAD

**Issue by foundling** [canjs/canjs#2443]
I posted an issue I was having recently on the donejs forums [(here)](http://forums.donejs.com/t/trouble-instantiating-multiple-components-of-the-same-type-with-separate-scope/372) where I was trying to render multiple instances of the same component in a stache `{{#each}}` loop.  @justinbmeyer advised me to use the `define` plugin in my component's `viewModel` and that worked out well.

But I want to bring this up because it seems unintuitive to me that I would need to bring in a separate plugin in order to ensure that multiple instances of a component have separate scopes.  Am I missing something about how components work? I could see the use case for sharing data among multiple component instances, but it doesn't seem natural to be the default. If this is intended behavior, I'd love to understand why, and maybe see the `can.Component` documentation touch on this.

**Comment by justinbmeyer** [comment]
The define plugin is pretty much the most useful thing ever and is standard for every/any modern CanJS app.   So don't worry about brining it in.

Regarding why this is ... it's related to how JS works.

Lets start with:

```js
can.Component.extend({
  viewModel: {
    stars: new can.List([
      {selected: false},
      {selected: false},
      {selected: false},
      {selected: false},
      {selected: false},
    ])
  }
}
```

This is just sugar for:

```js
ViewModel =  can.Map.extend({
    stars: new can.List([
      {selected: false},
      {selected: false},
      {selected: false},
      {selected: false},
      {selected: false},
    ])
});

can.Component.extend({
  viewModel: ViewModel
});
```

`can.Map.extend` is simply setting up the `prototype` of the `ViewModel` constructor.  It's almost something like this:

```js
ViewModel = function(){}
ViewModel.prototype.stars = new can.List([
      {selected: false},
      {selected: false},
      {selected: false},
      {selected: false},
      {selected: false},
    ])
```

With this last bit, hopefully you can see how the same `stars` `can.List` will be shared by every instance of `ViewModel`.  If this doesn't make sense, give this a watch:  http://blog.bitovi.com/training-series-prototypes/

This is just how prototypes work in JS.

I suppose we could document this here: https://canjs.com/docs/can.Map.prototype.DEFAULT-ATTR.html

In 3.0, with DefineMap, this syntax is no longer available.  You have to use a `value` definition.  And it does warn of this http://canjs.github.io/canjs/doc/can-define.types.value.html:

> If the default value should be an object of some type, it should be specified as the return value of a function (the above call signature) so that all instances of this map don't point to the same object. For example, if the property value above had not returned an empty array but instead just specified an array using the next call signature below, all instances of that map would point to the same array (because JavaScript passes objects by reference).

**Comment by foundling** [comment]
Thanks, that clarifies things. 🍦
