### ISSUE TITLE
In util/object/object.js on line 84 compare should be before a and b ~2

### ISSUE THREAD

**Issue by ArGGu** [canjs/canjs#2451]
In file util/object/object.js on line 84 has parameters in wrong order, when calling same.

compare should be before a and b.

**Comment by pYr0x** [comment]
you mean it should be
```
if (!same(a[i], b[i], compare, a, b)) {
```

**Comment by ArGGu** [comment]
@pYr0x yes.

**Comment by justinbmeyer** [comment]
this is fixed in `can-set`.
