### ISSUE TITLE
Can Pushstate ignores properties and key modifiers

### ISSUE THREAD

**Issue by Macrofig** [canjs/canjs#2452]
I thought created an issue for [this forum post](http://forums.donejs.com/t/pushstate-ignores-target-attribute-key-modifiers/158) and recently ran into the same bug again. As I tried to find the status of the issue, I realized I never filed it! 😞 

The issue is not easily reproducible in JSBin so I created [this page to help](http://www.juanorozco.com/demos/can-pushstate/). Essentially, can.pushstate ignores properties like `_blank` and also blocks browser behaviors like `⌘ (or CTRL) + click`. Code right around this [line in can.pushstate](https://github.com/canjs/canjs/blob/master/route/pushstate/pushstate.js#L173) seems to be the issue.

In some cases, we want to be able to open a link, that is within the same domain, in a new tab. Currently, pushstate prevents this but we have a can.view.attr as a workaround.

**Comment by matthewp** [comment]
Are there cases other than `_blank` that you can think of? Otherwise maybe we can special case it.

**Comment by Macrofig** [comment]
I think that's probably the most common one. Looking at the MDN page for it, there's the frame specific values and there's also the `download` property that might be an issue as more people use it. https://developer.mozilla.org/en/docs/Web/HTML/Element/a

**Comment by matthewp** [comment]
We have a special case for `javascript://` [here](https://github.com/canjs/can-route-pushstate/blob/master/can-route-pushstate.js#L171), this is where I'd add special logic to prevent intercepting clicks for anchors with target values.

**Comment by justinbmeyer** [comment]
closing for issue in can-route
