### ISSUE TITLE
Build customizer mentions undocumented library

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#2455]
What is a `can.Model.Queue`?

<img width="371" alt="screen shot 2016-08-22 at 9 54 00 am" src="https://cloud.githubusercontent.com/assets/82166/17859404/151fc1ec-684f-11e6-85a8-55c1affabd1a.png">

**Comment by matthewp** [comment]
I haven't used it but I assume it's this: https://github.com/canjs/canjs/blob/master/model/queue/queue.js

**Comment by justinbmeyer** [comment]
yes.  Closing as it's gone in 3.0 and the new site will be up.
