### ISSUE TITLE
Include can.view.attr in can/legacy

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2457]
It’d be really useful to still have `can.view.attr` when you require `can/legacy` in CanJS 3.

**Comment by matthewp** [comment]
This should be available in can/can as well, since it's brought in by can-component anyways.

**Comment by justinbmeyer** [comment]
but it shouldn't be `can.view.attr` in `can/can`.  It should be `can.viewCallbacks.attr`

**Comment by matthewp** [comment]
viewCallbacks is a weird internal name though, it doesn't mean anything to users.  I wonder if the project should be named can-view :)

**Comment by matthewp** [comment]
This was done in 8d900a5cdedbcbcad14c9bfb9074f1451dc855c8
