### ISSUE TITLE
Add a note to migration guide about `value` -> `type` rename for embedded define definitions

### ISSUE THREAD

**Issue by akagomez** [canjs/canjs#2461]
Used to be able to define inline definitions on the `value` property. In 3.0 the `type` property is used.

**Comment by matthewp** [comment]
This is specific to can-define/map/map.  I wonder if there should be a separate can-map-define -> can-define/map/map migration guide.

**Comment by Rlin415** [comment]
@matthewp I'm a little confused about this. To me it seems like can-define/map/map still offers the same functionality for `value` as can-map/define did. Maybe I'm looking at the wrong places? These are the 2 resources that I've looked at:
- http://canjs.com/doc/can-define.types.propDefinition.html
- https://v2.canjs.com/docs/can.Map.prototype.define.value.html

**Comment by justinbmeyer** [comment]
I think this means that you used to be able to do:

```
Map.extend({
  define: {
    name: "Justin"
  }
})
```

w/ DefineMap, the following would think that `Justin` is a type:

```
DefineMap.extend({
  name: "Justin"
})
```

**Comment by Rlin415** [comment]
I tried doing this in a JSbin using canJS 2 and it doesn't work.
```js
Map.extend({
  define: {
    name: "Justin"
  }
})
```

I get this error: 

```js
TypeError: Cannot use 'in' operator to search for 'value' in Justin
    at Object.mapHelpers.define (http://canjs.com/release/latest/can.jquery.js:8609:29)
    at Function.setup (http://canjs.com/release/latest/can.jquery.js:2997:32)
    at Function.extend (http://canjs.com/release/latest/can.jquery.js:2719:95)
    at venaje.js:1:957
```

**Comment by justinbmeyer** [comment]
He is probably talking about this:  

Map.extend( { name: "Justin" })
