### ISSUE TITLE
Document how everything is documented across the different modules

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2463]
As a developer, I’d like an overview of how the docs are written in the individual repos and are generated into their READMEs & the [CanJS 3 docs](http://canjs.github.io/canjs/) so that I can more easily contribute documentation changes. In addition to just making changes, it’d be helpful to generate the docs and preview the changes locally.

Furthermore, if I’m creating a new project that would be a good fit for the [CanJS ecosystem page](http://canjs.github.io/canjs/doc/can-ecosystem.html), I’d like to know how I should document my project and propose that my project be included on that page.

**Comment by matthewp** [comment]
Probably this sort of thing goes in the Contributing guide @justinbmeyer

**Comment by chasenlehara** [comment]
Looks like @justinbmeyer wrote this: https://v3.canjs.com/doc/guides/contributing/documentation.html

I’ll review that page and close this issue as soon as I can.
