### ISSUE TITLE
routeURL is not documented in canjs 3.0

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#2464]
the `routeURL` helper (here the old site: https://canjs.com/docs/can.stache.helpers.routeUrl.html) is not documented on the new canjs 3.0 documentation.

it is also important, that you have to manually import `can-stache/helpers/route` to getting the `routeURL` helper
```
import 'can-stache/helpers/route'
```

**Comment by justinbmeyer** [comment]
It is documented

https://canjs.github.io/canjs/doc/can-stache.helpers.routeUrl.html

As its in a separate module, it's implied it needs to be imported

**Comment by pYr0x** [comment]
oh ok.. didn't see this page.
