### ISSUE TITLE
can-route needs a route property

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#2465]
using routing with the new DefineMap (mention: that  `seal` is by default `true`) you have to add a property called `route` to your AppViewModel because can-route will add the property to the ViewModel if it not exists.

```
const AppViewModel = DefineMap.extend("AppViewModel",{
  route: "string",
  page: {
    type: "string"
  }
});
```

otherwise you can set `seal` to `false`.

pls update the docs for the new canjs 3.0 for can route

**Comment by matthewp** [comment]
This should be mentioned in can-route.map: http://canjs.github.io/canjs/doc/can-route.map.html

**Comment by justinbmeyer** [comment]
closing for https://github.com/canjs/can-route/issues/21
