### ISSUE TITLE
canjs 3.0 converters docs

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#2466]
`string-to-any` converter example might by wrong?
http://canjs.github.io/canjs/doc/can-stache-bindings.converters.string-to-any.htm

```
var str = document.getElementById('select-template').innerHTML;
var template = stache(str);

var map = new DefineMap({
    val: "foo"
});

document.body.appendChild(template(map));

map.item = NaN; // select.value becomes "NaN"

// Click the select box and choose Boolean
map.item === true; // -> true
```

`val` on the DefineMap should be `someValue`
`map.item` should be `map.someValue`

**Comment by matthewp** [comment]
Yeah, you're right, will fix it in can-stache-bindings.

**Comment by matthewp** [comment]
Will be fixed in the next canjs publish.
