### ISSUE TITLE
can-import self closing tag on css/less

### ISSUE THREAD

**Issue by MarcGodard** [canjs/canjs#2469]
A self-closing tag should be accepted for css/less

```
<can-import from="somfile.less!"></can-import>
```
to
```
<can-import from="somfile.less!"/>
```

There will never be content.

Currently if you do this:
```
{{#if xyz}}
<can-import from="somfile.less!"/>
{{/if}}
```

The css/less file is loaded even when ```xyz``` is false, unless you don't use a self closing tag.

**Comment by matthewp** [comment]
Self-closing is equivalent to the ES6 static imports like:

```js
import 'foo.js';
```

If you put that in a conditional it would still be loaded:

```js
if(foo) {
  import 'foo.js';
}
```

**Comment by MarcGodard** [comment]
I know that. What I am saying is that you should treat self closing css/less can-imports like they are not self-closing.

**Comment by matthewp** [comment]
Why? There are definitely situations where you want to progressively load css, to prevent loading more than you need for a particular view.

**Comment by marshallswain** [comment]
In the example:
```erb
{{#if xyz}}
<can-import from="somfile.less!"/>
{{/if}}
```
If xyz is true and those styles load, would remove that style-sheet remove the styles from the DOM?  Is it even possible to remove styles?  I've never played with it, at least consciously.  :)

**Comment by pYr0x** [comment]
@marshallswain no the stylesheet will not removed.
@MarcGodard dont see any benefits of your issue.

**Comment by marshallswain** [comment]
Thanks, @pYr0x.  This would be super beneficial if the stylesheet did get removed after xyz is set back to false, again.  But I think it will just be confusing if it's not possible to strip a stylesheet from the browser.  This would be better handled by loading all css and using classes to apply styles.

**Comment by pYr0x** [comment]
it is also a little bit tricky if more then one module rely on the same stylesheet. removing the stylesheet will causing a unstyled content

**Comment by justinbmeyer** [comment]
@pYr0x I think the styles are removed.  Anyone got the energy to create an example?

**Comment by MarcGodard** [comment]
https://github.com/MarcGodard/donejs-appframework

This is where it would be needed. Switching between iOS and Android in development.

I am trying to incorporate Framework7 with doneJS... so far very unsuccessfully.

**Comment by MarcGodard** [comment]
@matthewp That is what I want, to progressively load CSS but using a self-closing tag.

**Comment by MarcGodard** [comment]
@justinbmeyer It wouldn't be hard to make it an example in my repo. https://github.com/MarcGodard/donejs-appframework

I need to call it a night, will look into it more tomorrow. Also, if anyone wants to help with this project, I could use the help. I really like doneJS and it would be so sweet to take the Framework7 stuff and incorporated it (too bad it's javascript isn't great like its css--I was looking into changing that)

**Comment by pYr0x** [comment]
here a demo app.
https://github.com/pYr0x/css-import

setting the variable to false will not remove the css import!

**Comment by MarcGodard** [comment]
It would be cool if it did remove it.

**Comment by MarcGodard** [comment]
There is still the problem of when the tag is self closing, it loads regardless of the {{#if}}

**Comment by matthewp** [comment]
This is not a fixable issue. The same way this is not conditional in JavaScript:

```js
if(someCondition) {
  import "foo";
}
```

stache templates are statically analyzed to determine what should be imported up front and what should be imported based on runtime conditions.  This is how JavaScript ES modules works too.  

An `{{#if}}` is just a helper and there is no special logic to handle it. You could have a custom helper in your template that did:

```handlebars
{{#myHelper}}
  <can-import from="something.css"/>
{{/myHelper}}
```

Which we can't statically determine if this is a conditional type of helper or not.  So we need some rule *based on syntax* to determine if something is intended to be static vs. dynamic. That syntax rule is *currently* self-closing vs. not self closing.  

We *could* in the future switch to some different syntax rule.  Maybe an attribute like `dynamic`.  Suggestions welcome here.

**Comment by pYr0x** [comment]
> There is still the problem of when the tag is self closing, it loads regardless of the {{#if}}

you read matthew's comment?
https://github.com/canjs/canjs/issues/2469#issuecomment-244509497
and pls read this too
https://canjs.com/docs/can%7Cview%7Cstache%7Csystem.import.html#section_static_dynamicimport

**Comment by matthewp** [comment]
Let's keep this issue open a little longer, I don't want @MarcGodard to feel like his opinion is being ignored.  Hopefully we can explain why static analysis is needed to distinguish between static/dynamic imports.  I can't certainly understand the desire for conditionals in ifs.

We really just choose self-closing/non-self-closing because it was the best we could come up with at the time. Maybe there's a better way!

**Comment by justinbmeyer** [comment]
I really think there is a way to remove the rules

**Comment by MarcGodard** [comment]
You say this doesn't work:
```
{{#if xyz}}
<can-import from="somfile.less!"/>
{{/if}}
```
but then why does this work:
```
{{#if xyz}}
<can-import from="somfile.less!"></can-import>
{{/if}}
```

All I am saying is that for css and less files you shouldn't need the extra tag to close the import for it to work. That is all.

**Comment by justinbmeyer** [comment]
@MarcGodard I think @matthewp explained this.  `<can-import/>` vs `<can-import></can-import>` is the same difference between `import "jquery"` and `System.import("jquery")`.

**Comment by MarcGodard** [comment]
@justinbmeyer I understand that, but it wouldn't be too hard to change it for css/less files to always work like `System.import()` This would save new people a lot of potential hassle and would be better in other ways as well. I am just going to close this, because otherwise you guys don't understand what I am saying or I am completely wrong.

**Comment by justinbmeyer** [comment]
You wouldn't want it to always work like System.import. Css and less should be part of the static dependencies. But it also should be possible to progressively load.

**Comment by matthewp** [comment]
I see this as bit of an existential crisis for Steal. It's sort of like https://github.com/stealjs/steal-css/issues/16.

Let me explain.  This issue has identified 2 problems with using can-import with CSS. Those are:

* CSS is imported regardless of whether the `<can-import>` is inserted into the page or not. This goes against the expectation of HTML (which stache is not) that side-effects only happen once inserted into the DOM.
* CSS is not removed when the `<can-import>` is removed from the page. It's understandable how you might want this behavior.

There's an existing API that gives you both of those things. It is:

```handlebars
{{#if condition}}
  <link rel="stylesheet" href="path/to/styles.css">
{{/if}}
```

If you use a `<link>` then you get exactly what is wanted. The CSS is not fetched until inserted into the page. Styles are removed when removed from the page.

There's just one **big** problem with using a `<link>` in a DoneJS application. Steal doesn't know about it. So it can't dedupe it and steal-tools can't create bundles for it. Steal only knows about a JavaScript main and its dependencies (or something that compiles to JavaScript). To work around this we make *everything* into a JavaScript module.  But by doing this we give up all of the features that `<link>` has, and that makes me sad. I don't want to reimplement all of link.

This is a problem I've been thinking a lot about recently. I see Steal as evolving towards revolving around **pages** and their dependencies, which includes JavaScript modules, CSS, images, and anything else that can be described in an HTML tag, including some day, custom elements.  A page's dependency graph looks like:

<img width="681" alt="screen shot 2016-09-06 at 4 49 27 pm" src="https://cloud.githubusercontent.com/assets/361671/18290885/3a2010e0-7453-11e6-9911-3495bbb8e3be.png">

For CSS, for example, you could have a custom element like:

```html
<steal-css href="path/to/styles.css"></steal-css>
```

That solves all of the problems we encounter:

1. It would only fetch styles when inserted into the page.
2. It would remove its stylesheets when it is removed from the page.
3. It could deduplicate `import()`s.
4. It would produce bundles during the build.

**Comment by pYr0x** [comment]
thanks @matthewp  for you detailed answer. maybe a talk for the upcomming doneJS meetup.

**Comment by justinbmeyer** [comment]
@matthewp I'm confused why we can't make dynamic `<can-import></can-import>` of styles able to remove the stylesheet?


`<can-import>`'s behavior, imo, should be relatively divorced from steal's behavior.  It's a layer that uses steal, but it's steal itself.  It can have it's own behaviors and abilities.

**Comment by matthewp** [comment]
@justinbmeyer 

> @matthewp I'm confused why we can't make dynamic <can-import></can-import> of styles able to remove the stylesheet when the element is removed?

We might be able to, but I was answering the larger point about this issue which removing the stylesheet doesn't solve, and the problems that have prompted https://github.com/stealjs/steal-css/issues/16, and https://github.com/stealjs/steal-bundler and https://github.com/donejs/done-component, etc.

To your point though, I'm not sure how to do this without special casing CSS. 

Roughly speaking, any dynamic can-import translates into:

```js
var from = el.getAttribute('from');
System.import(from);
```

I'm not sure what removal is supposed to trigger? Let's say it did this:

```js
System.delete(from);
```

And somehow steal-css was able to know about this through a hook (that doesn't exist at the moment), you wouldn't want this anyways in the case of JavaScript imports which also happen within conditionals.

So, I don't think the use-case fits well into any existing Steal lifecycle hooks.

> `<can-import>`'s behavior, imo, should be relatively divorced from steal's behavior. It's a layer that uses steal, but it's steal itself. It can have it's own behaviors and abilities.

I'm not sure what this is referencing, did something I said make you think that I want Steal to be aware of can-import?  If so that wasn't my intent.

What I was saying is that can-import is not a great fit for CSS because of the reasons I outlined above, and how normal `<link>` solves both problems outlined here but isn't useable in this context because steal-tools can't trace page dependencies.
