### ISSUE TITLE
precompile stache templates in nodejs

### ISSUE THREAD

**Issue by blackmamba** [canjs/canjs#2471]
Hello @justinbmeyer,

I am trying to pre-compile canjs' stache templates during the build. For which I need to have canjs in my webpack build system, on nodejs. 

When I try to require can as following:

`var can = require('can/dist/cjs/can');`

I get 

```

ReferenceError: document is not defined
    at /User/projectname/node_modules/can/dist/cjs/util/fragment.js:60:56
    at Object.<anonymous> (/User/projectname/node_modules/can/dist/cjs/util/fragment.js:71:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/User/projectname/node_modules/can/dist/cjs/util/jquery/jquery.js:14:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/User/node_modules/can/dist/cjs/util/util.js:10:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

Is it possible to possible to pre-compile '.stache' files like '.hbs' ? 

I'm using canjs 2.3.24
Would appreciate any help.
thanks!

**Comment by blackmamba** [comment]
If I go the **Steal route**:

```
var steal = require('steal');
var can = require('can/dist/steal/can/can');

```
then I get:
```

TypeError: Cannot read property 'then' of undefined
    at steal (/User/project/node_modules/steal/main.js:224:25)

```

**Comment by blackmamba** [comment]
**can-simple-dom route**

`
var simpleDOM = require('can-simple-dom');
var document = new simpleDOM.Document();
var can = require('can/dist/cjs/can');
`

`
ReferenceError: document is not defined
    at /User/projectname/node_modules/can/dist/cjs/util/fragment.js:60:56
`

no luck so far!

**Comment by pYr0x** [comment]
@blackmamba if you are using canjs 3.0 here is a little code snippet

NodeJS File:
```
var stealconfig  = {
	configMain: 'package.json!npm',
	main: '@empty',
	stealPath: __dirname+'/node_modules/steal/steal.js'
};

var steal = require('steal');

steal.startup(stealconfig).then(function () {
	steal.import('can-stache/src/intermediate_and_imports').then(function (module) {
		var stache = module('<p ($click)="foobar()">Hello</p><p><u>World</u></p>');

		console.log(stache.intermediate);
	});
});
```

as you see, you need steal for loading all the canjs stuff. you need also`"can-stache": "^3.0.0-pre.15"` in your `dependencies` in your `package.json`

you will get an output of `stache.intermediate`
you can put this output in the normal `stache()` method and get a `renderer` back

see the example: https://jsbin.com/kazidezoya/edit?html,js,output

now you can create precompiled stache files, load them as json and put them into the `stache()`

**Comment by blackmamba** [comment]
Thanks @pYr0x for your response.

Let me start with sharing what I have done since last night, with a hope that it may help others.

While troubleshooting the above, I stumbled upon Donejs - and tried the above mentioned 'Steal route'. I also stumbled upon the modular implementations of the packages in CanJS 3.0.0. I must add that, looking at the modular implementations got me really excited. And I decided to try to accomplish the above using the 'can-stache 3.0.0-pre.18' module. Hoping that it should be as easy as the following lines of code:

```
var stache = require('can-stache');
var template = require('./path/to/template');
var renderer = stache(template); 

```

But, unfortunately I couldn't even get pass the require('can-stache') line. It fails with an error of some modules not found. Basically, say for example sake, inside can-stache.js, it requires a module in the following way:

`var assign = require('can-util/js/assign');`

Typically that means that inside 'assign' directory, there will be an index file, but here it contains an assign.js. And the require cannot interpret that, and its failing. I fixed many modules by pre-pending it with the module name after the directory name, hoping that its just one or two modules, but seems like there are a lot. I thought may be this is because I'm on Node 5.x, so I upgraded to Node 6.x incase this new feature is introduced, but no luck so far. 
eg: of the error I'm running into

```
fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
module.js:457
    throw err;
    ^

Error: Cannot find module 'can-event/lifecycle/'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user/project/node_modules/can-compute/proto-compute.js:37:22)

```

Now coming to using Steal, as per your example. I am already using require to load dependencies i n my node build. And I am skeptical adding, one more dependency management just to pre-compile. Hopefully there is a workaround. The jsbin example is good, but the browser environment was never a problem. Its the node where I'm facing this. May be I'm missing something, as to how can-stache is supposed to be built. Will appreciate if someone can point out. If not then may be as the last resort I may have to consider Steal.

Thanks!

**Comment by pYr0x** [comment]
@blackmamba i updated the jsbin. it pointed to the wrong url
https://jsbin.com/ceqesenope/edit?html,js,output

**Comment by pYr0x** [comment]
@blackmamba i think there is actual no workaround for that. i think you have to use steal.

but it is a good question to ask @matthewp or @justinbmeyer why canjs 3.0 is not usable with nodeJS. canjs 3.0 is written in commonJS and it is all modular. so why do we have to use steal for loading canjs in node. forget at this point the `DOM ` problem. we can workaround with `can-simple-dom`

**Comment by gsmeets** [comment]
I have it running with requirejs (can 2.X). Last time I tested precompilation though it was actually slower than parsing the string templates at runtime.

**Comment by justinbmeyer** [comment]
There's probably just some places that import module names like foo/bar/ when they should be foo/bar/bar.  We just need to fix them.

**Comment by pYr0x** [comment]
@justinbmeyer it seems something wrong in many places.

1. in package.json in `can-view-live` the main points to `"main": "dist/cjs/can-view-live",` but the  `dist` folder does not exists because `https://github.com/canjs/can-view-live/blob/master/.npmignore`
2. there are many places where the module pointed to a `steal-readable` path 
```
var isEmptyObject = require("../../../js/is-empty-object/");
var each = require("../../../js/each/");
var makeArray = require("../../../js/make-array/make-array");

var events = require("../events");
var domData = require("../../data/");
var getMutationObserver = require("../../mutation-observer/");
var domDispatch = require("../../dispatch/");
var mutationDocument = require("../../mutation-observer/document/");
var getDocument = require("../../document/");
```

**Comment by blackmamba** [comment]
@pYr0x Exactly.

Just running a require('can-stache') should help uncover a lot of this. I fixed a few on my end, but it's spread across many repositories. I'll try to open a PR.

Thankfully I haven't seen any of the 'window' or 'document' undefined messages in can 3.0 yet, so most probably I may not need a Virtual DOM to be included explicitly.

Any ETA on this ?

Thanks!

**Comment by justinbmeyer** [comment]
@blackmamba this isn't priority right now, but it will land before 3.0.  If you can submit pull requests, that will be very helpful.

A virtual dom will need to be included explicitly for stache to work (possibly not for it to be loaded).  For example, can-view-target imports some can-util/dom utilities: https://github.com/canjs/can-view-target/blob/master/can-view-target.js#L8

**Comment by blackmamba** [comment]
Totally understand. I'll try my best to contribute at my earliest leisure. 

Gotcha. I'll add it when required, once I'm past the above errors.

Cheers!

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-stache #184](https://github.com/canjs/can-stache/issues/184) via [**ZenHub**](https://www.zenhub.com/)
