### ISSUE TITLE
ViewModel function is undefined when using "attr" to get it.

### ISSUE THREAD

**Issue by edba** [canjs/canjs#2472]
Using the viewModels "attr" function to get a function that is assign as a property in the viewModel will return undefined. 

Example: http://jsbin.com/kayomi/15/edit?html,js,console

I was expecting the function to be returned when using "attr" as it works for any other property on the viewModel.

**Comment by pYr0x** [comment]
@edba whats wrong with using ?
```
init(){
    this.viewModel.action()
  }
```

**Comment by justinbmeyer** [comment]
Properties are different from methods. You call methods like viewModel.method().

**Comment by edba** [comment]
Calling methods like viewModel.method() works fine until you start passing methods from parent to child or the other way around.

Since viewModel.method() will always execute the currents components method without taking into account what has been bound to it.

So the only reliable way to execute either the bound method or the components method is like:
```
if(typeof this.viewModel.attr('method') === 'function'){
  this.viewModel.attr('method')();
} else {
  this.viewModel.method();
}
```
Here is a working example: http://jsbin.com/kayomi/19/edit?html,js,console

This becomes a bit cumbersome and it's not immediate obvious since functions are treated differently than any other property on the viewModel.

I guess one way around this could be to use the define plugin to return a function as the initial value.

What are your thoughts on this?

**Comment by justinbmeyer** [comment]
@edba This should be fixed with `can-reflect` like:

```
canReflect.apply( item, canReflect.getKeyValue( item , "method"), [] );
```

You could also use `can-observation/reader` right now like:

```
reader.read(this.viewModel, reader.reads("method"), {})
```
