### ISSUE TITLE
Stache helper is called with wrong options properties

### ISSUE THREAD

**Issue by SergeRNR** [canjs/canjs#2474]
Hi,

the [documentation](https://canjs.com/docs/can.stache.helperOptions.html) says only section helpers have "options.fn" and "options.inverse" methods. But I noticed that inline {{helper}} also has "options.fn". This method returns undefined if called.
I see it as expected behavior in [tests](https://github.com/canjs/canjs/commit/8238af274256daf408517fa735152884b6ca0cc4).

We use custom helpers as inline and section helpers and we need to distinguish if helper was called as section or not. How can we do it ?

**Comment by justinbmeyer** [comment]
I'm not sure there's a way currently.  Good catch!

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-stache #185](https://github.com/canjs/can-stache/issues/185) via [**ZenHub**](https://www.zenhub.com/)
