### ISSUE TITLE
Two-way binding to inputs does not take feedback from setter values

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#2475]
See the following JSBin:
http://jsbin.com/qikidavinu/1/edit?html,js,output

Enter any numeric value greater than 10 while not at 10 and both input and displayed value will clamp.
Enter any numeric value less than 0 while not at 0 and both input and displayed value will clamp.

Do either while already at the respective limit and the input will _not_ clamp.

It seems the current implementation of two-way binding does not correctly implement feedback from the setter of the binding's opposite end.

**Comment by justinbmeyer** [comment]
Weird.  I thought we fixed this in 3.0 by making values sticky here: https://github.com/canjs/can-stache-bindings/issues/122 ... Moving to `can-stache-bindings`.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-stache-bindings #162](https://github.com/canjs/can-stache-bindings/issues/162) via [**ZenHub**](https://www.zenhub.com/)
