### ISSUE TITLE
#if stache helper double runs computes even with @

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2480]
Using the `#if` stache helper will run a function argument even if prefixed with `@`.

```
{{#if @foo}} true {{/if}}
```

http://jsbin.com/yifagodeco/edit?js,console,output

The cause seems to be that `can.compute.truthy()` will run the compute's result if it is a function.

https://github.com/canjs/canjs/blob/b26e84eb141c5cfa9914d8c8f6a578b053ce6207/compute/compute.js#L69

```
can.compute.truthy = function (compute) {
    return can.compute(function () {
        var res = compute();
        if (typeof res === 'function') {
            res = res();
        }
        return !!res;
    });
};
```

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-stache #186](https://github.com/canjs/can-stache/issues/186) via [**ZenHub**](https://www.zenhub.com/)
