### ISSUE TITLE
get_value_and_bind.js implicitly requires can.batch

### ISSUE THREAD

**Issue by aweidner-ct** [canjs/canjs#2488]
CanJS file `get_value_and_bind.js` requires `can.batch` to be initialized because it sets a property on `can.batch` (the property name is `_onDispatchedEvents`), but does not explicitly require `can/util/batch.js` in the module definition.  This can lead to a `TypeError` if `get_value_and_bind` is loaded before `can/util/batch`.

**Comment by matthewp** [comment]
Looks like this will be fixed in 3.0: https://github.com/canjs/can-observation/blob/master/can-observation.js#L17
