### ISSUE TITLE
TodoMVC Guide Tasks

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2490]
- [x] - Fix notes 
- [x] - Make sure it works and is consistent  
- [x] - Add focused.
- [x] - add ending JSBin
- [x] - Get it reviewed
- [x] - Get templating and pick up package.json's data.
- [ ] - Make videos showing what people will be able to do.
- [x] - get diffs styled (hoverable, lines inserted are darker)
- [x] - plan meetup

**Comment by mickmcgrath13** [comment]
Under [Create Todos](http://localhost:8080/doc/guides/todomvc.html#Createtodos) -> "Update the html tab to:",
It says
> Updates the todo’s name with the <input>’s value using {^to-parent}
but the [code](https://github.com/canjs/canjs/blob/master/docs/can-guides/experiment/todomvc/5-create/html.html#L14) is using `{($value)}`.

Should we:
1) change the code to use `{^to-parent}`
OR
2) change the description to say `{(two-way)}`?

**Comment by mickmcgrath13** [comment]
The field doesn't clear properly unless we use two-way.

**Comment by mickmcgrath13** [comment]
Closing - We won't do videos until after the release
