### ISSUE TITLE
Chat Guide

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2493]
- [x] - Fix notes 
- [x] - Make sure it works and is consistent  
- [x] - add ending JSBin
- [x] - Get templating and pick up package.json's data.
- [ ] - Make videos showing what people will be able to do.
- [x] - plan meetup

**Comment by justinbmeyer** [comment]
- [ ] - can we remove `contentType: 'application/x-www-form-urlencoded'`

**Comment by mickmcgrath13** [comment]
In response to:
can we remove contentType: 'application/x-www-form-urlencoded'

In the JSBin, it works whether it's there or not.
Further, with the contentType set to `application/x-www-form-urlencoded`, the Content-Type response header is `application/json`, but there doesn't seem to be a request header set.

Request with `contentType: 'application/x-www-for-urlencode'`
![image](https://cloud.githubusercontent.com/assets/1030325/20067330/52b3a9c0-a4da-11e6-8e1b-b01541157c65.png)


Request without `contentType`
![image](https://cloud.githubusercontent.com/assets/1030325/20067356/6cb4c6d8-a4da-11e6-8597-50a92763019f.png)

**Comment by mickmcgrath13** [comment]
Without `contentType: 'application/x-www-for-urlencode'`, the creation of messages results in an error:

OPTIONS - http://chat.donejs.com/api/messages
**Response Headers:**
```
HTTP/1.1 200 OK
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: X-Requested-With
Access-Control-Allow-Methods: DELETE, GET, HEAD, POST, PUT, OPTIONS, TRACE
Allow: GET,POST,PATCH,PUT,DELETE,HEAD
Content-Type: text/html; charset=utf-8
Content-Length: 30
Etag: W/"1e-CVFZ0nFHwOziYlbMcCG31A"
Vary: Accept-Encoding
Date: Mon, 07 Nov 2016 17:49:58 GMT
Via: 1.1 vegur
```

**Request Headers:**
```
OPTIONS /api/messages HTTP/1.1
Host: chat.donejs.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Access-Control-Request-Method: POST
Origin: http://null.jsbin.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
Access-Control-Request-Headers: content-type
Accept: */*
Referer: http://null.jsbin.com/runner
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,pt-BR;q=0.6,pt;q=0.4
```

curl
```
curl 'http://chat.donejs.com/api/messages' -X OPTIONS -H 'Pragma: no-cache' -H 'Access-Control-Request-Method: POST' -H 'Origin: http://null.jsbin.com' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8,pt-BR;q=0.6,pt;q=0.4' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Referer: http://null.jsbin.com/runner' -H 'Connection: keep-alive' -H 'Access-Control-Request-Headers: content-type' --compressed
```


Response (200 OK - empty but caused error):
```
XMLHttpRequest cannot load http://chat.donejs.com/api/messages. Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.
```
![image](https://cloud.githubusercontent.com/assets/1030325/20069022/7daf6906-a4e0-11e6-8ed7-dc39d8c070cb.png)

**Comment by mickmcgrath13** [comment]
Closing - We won't do videos until after the release
