### ISSUE TITLE
can.view.bindings API page is broken

### ISSUE THREAD

**Issue by prashantsharmain** [canjs/canjs#2500]
Multiple issues seen on [can.view.bindings](https://canjs.com/docs/can.view.bindings.event.html) API page:
1. ($DOM_EVENT)='CALL_EXPRESSION' anchor link is broken
2. (VIEW_MODEL_EVENT)='CALL_EXPRESSION' anchor link is broken
3. Parameters section of (VIEW_MODEL_EVENT)='CALL_EXPRESSION' incorrectly lists **DOM_EVENT** as the first parameter: _DOM_EVENT {String} A DOM event name like "click". jQuery custom events can also be given_. Description should be updated to state it's a **VIEW_MODEL_EVENT** and not a **DOM_EVENT**

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-stache-bindings #163](https://github.com/canjs/can-stache-bindings/issues/163) via [**ZenHub**](https://www.zenhub.com/)
