### ISSUE TITLE
Add missing tests to test suite

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#2527]
These tests need to be added or fixed [here](https://github.com/canjs/canjs/blob/major/test/test.js):
- [x] add can-stache-bindings
- [x] other missing core packages
- [x] other missing infrastructure packages
- [x] other missing legacy packages
- [x] https://github.com/canjs/can-stache-bindings/issues/69
- [x] can-component tests are failing https://travis-ci.org/canjs/can-component/builds/163549036
- [x] https://github.com/canjs/can-jquery/issues/25
- [x] https://github.com/canjs/can-util/issues/115
- [x] https://github.com/canjs/can-util/pull/113, https://github.com/canjs/can-jquery/pull/24
- [x] https://github.com/canjs/can-util/issues/118
- [x] https://github.com/canjs/can-util/issues/119
- [ ] fix remaining test failures

|| Status | Reported By | OS | Browser | Repo | Test |
|---|---|---|---|---|---|---|
|1| [fixed](https://github.com/canjs/can-stache-bindings/pull/77) | [Sauce Labs](https://saucelabs.com/jobs/ff32b4ceb2e44b109a9fe35b6f072df0) | Windows 10 | Chrome | can-view-autorender | [the basics are able to work for steal](https://github.com/canjs/can-view-autorender/blob/master/can-view-autorender_test.js#L52-L54) |
|2| [fixed](https://github.com/canjs/can-stache-bindings/pull/77) | [Sauce Labs](https://saucelabs.com/jobs/ff32b4ceb2e44b109a9fe35b6f072df0) | Windows 10 | Chrome | can-view-autorender | [works with a can-define/map/map](https://github.com/canjs/can-view-autorender/blob/master/can-view-autorender_test.js#L60-L62) |
|3| can't reproduce | [Sauce Labs](https://saucelabs.com/jobs/318c724753c64dd5a9211b31da65b6d9) | Windows 8 | IE 10 | can-stache-bindings | [dom: dynamic attribute bindings](https://github.com/canjs/can-stache-bindings/blob/master/test/bindings-test.js#L1734-L1763) |
|4| can't reproduce | Kevin | Windows 7 | IE 10 | can-component | [map - dom basic tabs](https://github.com/canjs/can-component/blob/master/test/component-map-test.js#L132-L288) |
|5| [caused by this](https://github.com/canjs/can-simple-dom/issues/46) | Kevin | Windows 10 | MS Edge | can-component | [map - DOM trees not releasing when referencing CanMap inside CanMap in template (#1593)](https://github.com/canjs/can-component/blob/master/test/component-map-test.js#L1578-L1625) |
|6| David investigating | Kevin | Windows 7 | IE 10 | can-util | [can-util/dom/ajax abort](https://github.com/canjs/can-util/blob/master/dom/ajax/ajax-test.js#L18-L34) |

**Comment by phillipskevin** [comment]
| Fixed | Reported By | OS | Browser | Repo | Test |
|---|---|---|---|---|---|
| No | [Sauce Labs](https://saucelabs.com/jobs/ff32b4ceb2e44b109a9fe35b6f072df0) | Windows 10 | Chrome | can-view-autorender | [the basics are able to work for steal](https://github.com/canjs/can-view-autorender/blob/master/can-view-autorender_test.js#L52-L54) |
| No | [Sauce Labs](https://saucelabs.com/jobs/ff32b4ceb2e44b109a9fe35b6f072df0) | Windows 10 | Chrome | can-view-autorender | [works with a can-define/map/map](https://github.com/canjs/can-view-autorender/blob/master/can-view-autorender_test.js#L60-L62) |
| No | [Sauce Labs](https://saucelabs.com/jobs/318c724753c64dd5a9211b31da65b6d9) | Windows 8 | IE 10 | can-stache-bindings | [dom: dynamic attribute bindings](https://github.com/canjs/can-stache-bindings/blob/master/test/bindings-test.js#L1734-L1763) |

**Comment by daffl** [comment]
For the can-view-autorender tests: https://github.com/canjs/can-view-autorender/pull/21
