### ISSUE TITLE
Remove implicit arguments to helpers

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#2533]
In the code below, `isActive` will be passed the `context` and `scope` by default from here: https://github.com/canjs/can-stache/blob/master/src/mustache_core.js#L98. Also, `makeActive` will be passed the `context`, `element`, and `event` from here: https://github.com/canjs/can-stache-bindings/blob/master/can-stache-bindings.js#L269-L277.

```
        var TabsViewModel = CanMap.extend({
            ...
            isActive: function (panel) {
                return this.attr('active') === panel;
            }
        });

        // new Tabs() ..
        Component.extend({
            tag: "tabs",
            ViewModel: TabsViewModel,
            template: stache("<ul>" +
                "{{#panels}}" +
                "<li {{#isActive}}class='active'{{/isActive}} can-click='makeActive'>{{title}}</li>" +
                "{{/panels}}" +
                "</ul>" +
                "<content></content>")
        });
```

With Call Expressions, there is no more need for these implicit arguments since people can pass these things themselves if they want.

Also, in 3.0 the context is changing to a compute, so people will already need to update their code if they are doing things like this since `panel` will be a compute now inside of `isActive`.

Now might be a good time to remove some of this implicit behavior.

**Comment by matthewp** [comment]
Is it possible to only add the arguments when using Helper Expression or is that not known by the code that adds it?  I do agree that for Call Expressions you should be explicit.

**Comment by phillipskevin** [comment]
In the `isActive` case, we know it is a helper and mustache-core only adds those arguments for Helpers. For the `makeActive` case we **don't** know whether it is a Helper expression, but we know it's not a Call expression.

**Comment by justinbmeyer** [comment]
This is mostly a question of how badly to we want to make people's migrations for a bit of code cleanup on our end.

The only way we should remove this is to make sure we give people very strong warnings in the next release of 2.3.  That way they can see where they are doing this, and take the correct steps to change it before upgrading to 3.0.

**Comment by justinbmeyer** [comment]
We didn't do this.  We would have to make this happen in can-stache-bindings 4.0

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-stache-bindings #164](https://github.com/canjs/can-stache-bindings/issues/164) via [**ZenHub**](https://www.zenhub.com/)
