### ISSUE TITLE
Uncaught SyntaxError: Unexpected token switch

### ISSUE THREAD

**Issue by lewismoten** [canjs/canjs#2553]
I'm upgrading a pretty large project. I've been getting a lot of errors when using can.Control.extend("long.path.name.reservedJavaScriptKeyword").  - when the reserved word in JavaScript is "import" or "switch". I'm still going through a few others, but as I said, it's a large project.

The problem appears to be deep in can where it is trying to create a constructor with a function named after that last part of the extended path. See `can/construct/construct.js` extend around line 483

```
eval('Constructor = function ' + constructorName + '() { return init.apply(this, arguments); }');
```

**Comment by matthewp** [comment]
Which version are you upgrading to? 3.0 doesn't support setting a global namespace object any more.

**Comment by justinbmeyer** [comment]
He's upgrading to 2.3. 

A temporary work around would be to create the constructor like:

```js
long.path.name["switch"] = Type.extend({ ... },{ ... })
```

**Comment by lewismoten** [comment]
Correct @matthewp - I am upgrading to can 2.3. I'm uncertain what I am upgrading from. The package.json and changelog.md says its version 1.1.7, the can.js file says 2.1.1

@justinbmeyer  The temporary workaround - is "Type" supposed to be "can" or "can.Control" in this case? I don't think "path" and "name" exist just yet in this namespace either. I could be wrong.

**Comment by lewismoten** [comment]
@justinbmeyer - it looks like the work-around fixed the issue. Thanks!

**Comment by lewismoten** [comment]
I spoke a bit too soon. I had other resources failing first with the load order. I'm getting "Type is undefined."

**Comment by lewismoten** [comment]
Maybe this?
```javascirpt
something.here = something.here || {};
something.here["import"] = can.Control.extend({
```

**Comment by justinbmeyer** [comment]
Yeah, that should work.
