### ISSUE TITLE
Rendering a template with a custom scope throws on reference scope bindings

### ISSUE THREAD

**Issue by dylanrtt** [canjs/canjs#2558]
Reference scope bindings throw when a template is rendered with a custom `can.view.Scope()` that does not have a reference scope in its chain.

``` js
var scope = new can.view.Scope({});
var template = can.stache('<foo-bar {^.}="*bar" />{{*bar.foo}}');
template(scope); // throws "Cannot read property '_context' of undefined"
```

http://jsbin.com/fulemupihe/1/edit?js,console,output

Using a `can.Map` or plain object as the scope works. Adding a references scope to the scope chain manually also works:

``` js
scope = scope.add( new can.view.Scope.Refs() );
```

One solution may be to add a references scope to the chain if the provided scope does not have one.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-view-scope #55](https://github.com/canjs/can-view-scope/issues/55) via [**ZenHub**](https://www.zenhub.com/)
