### ISSUE TITLE
Type and two-way bindings don’t behave correctly when a property is removed

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2560]
Demo (using latest CanJS, 2.3.27 right now): http://jsbin.com/zehediriyo/edit?html,js,output

When a parent and child component both have a property defined with `Type`, then the child calls `removeAttr` to set the property to `undefined`, the parent component then updates the property with a new instance of what’s specified by `Type`.

**Comment by justinbmeyer** [comment]
Looks like this works in 3.0: http://justinbmeyer.jsbin.com/lenomid/2/edit?html,js,output
