### ISSUE TITLE
v3.0.0 submodule releases

### ISSUE THREAD

**Issue by daffl** [canjs/canjs#2563]
- [x] can-component
- [x] can-compute
- [x] can-connect
- [x] can-construct
- [x] can-construct-super
- [x] can-control
- [x] can-define
- [x] can-event
- [x] can-fixture
- [x] can-jquery
- [x] can-list
- [x] can-map
- [x] can-map-backup
- [x] can-map-define
- [x] can-observation
- [x] can-route
- [x] can-route-pushstate
- [x] can-set
- [x] can-simple-dom
- [x] can-simple-map
- [x] can-stache
- [x] can-stache-bindings
- [x] can-util
- [x] can-view-autorender
- [x] can-view-callbacks
- [x] can-view-href
- [x] can-view-import
- [x] can-view-live
- [x] can-view-model
- [x] can-view-nodelist
- [x] can-view-parser
- [x] can-view-scope
- [x] can-view-target
- [x] can-stache-converters
- [x] can-ejs
- [x] can-vdom

**Comment by daffl** [comment]
All done now.

**Comment by justinbmeyer** [comment]
- [ ] can-stache-converters
- [ ] can-ejs
- [ ] can-vdom

**Comment by justinbmeyer** [comment]
And then there's `can` itself.  But lets wait on that.
