### ISSUE TITLE
Broken images paths in guides

### ISSUE THREAD

**Issue by garrettreed** [canjs/canjs#2607]
Most relative image paths in the guides are incorrect. Introduction and the ATM guide seem to be okay because they've been worked on recently.

Here's an example in the PMO guide and it's associated path:

![screen shot 2016-10-21 at 10 05 40 am](https://cloud.githubusercontent.com/assets/4079858/19601191/3c32dfb6-9776-11e6-9bcf-deffb1095f4c.png)

```
![Empty pmo-restaurant-details element](../can/guides/images/event-handling/EmptyRestaurantDetails.png)
```

It would also be a good idea to move the contents of `docs/can-guides/images/` into `docs/images/`

**Comment by justinbmeyer** [comment]
The PMO guide should probably be removed for now.

**Comment by justinbmeyer** [comment]
I hid pmo
