### ISSUE TITLE
Broken can-connect demos

### ISSUE THREAD

**Issue by moschel** [canjs/canjs#2629]
Go to http://canjs.github.io/canjs/doc/can-connect/constructor/store/store.html. Demo is showing 404.

![2016-10-27_0049](https://cloud.githubusercontent.com/assets/22180/19756007/5c530baa-9bdf-11e6-93ec-cfc49209d0ce.png)

**Comment by moschel** [comment]
Same thing with this page: http://canjs.github.io/canjs/doc/can-connect/real-time/real-time.html

**Comment by moschel** [comment]
Same with this: http://canjs.github.io/canjs/doc/can-connect/fall-through-cache/fall-through-cache.html

I think we can safely assume all can-connect demos are not working.

**Comment by garrettreed** [comment]
@justinbmeyer do you have an idea of what's going on here? Should this be filed under can-connect?

**Comment by justinbmeyer** [comment]
It should.  It's probably just the path having too many `../`

**Comment by garrettreed** [comment]
Issue moved to [canjs/can-connect #169](https://github.com/canjs/can-connect/issues/169) via [**ZenHub**](https://www.zenhub.com/)
