### ISSUE TITLE
DefineMap needs a Use section

### ISSUE THREAD

**Issue by moschel** [canjs/canjs#2630]
http://canjs.github.io/canjs/doc/can-define/map/map.html

The rest of the Core API top-level pages have a Use section. DefineMap is important enough it should have one too.

**Comment by justinbmeyer** [comment]
I think this already a can-define issue. Please try to create bugs in the right repo.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-define/issues/82
