### ISSUE TITLE
Docs show can.Map and can.List

### ISSUE THREAD

**Issue by moschel** [canjs/canjs#2631]
Isn't there no more can.Map or can.List?

http://canjs.github.io/canjs/doc/can-connect/can/map/map.html

^ That behavior links to 2.3 can.Map docs and shows can.Map in its examples.

![123](https://cloud.githubusercontent.com/assets/22180/19757469/a36706be-9be8-11e6-8300-aa2627c6650c.png)

^ super-map shows can.Map and can.List in its examples also

**Comment by justinbmeyer** [comment]
closing for issue in can-connect
