### ISSUE TITLE
Technical Highlights: Observables - Why they’re powerful section - 5 images needed

### ISSUE THREAD

**Issue by BigAB** [canjs/canjs#2636]
> There are images needed for the [Technical Highlights](http://canjs.github.io/canjs/doc/guides/why-canjs/technical.html) and [Comparison to Other Frameworks](http://canjs.github.io/canjs/doc/guides/why-canjs/comparison.html) pages.

> Until merged, we are currently working in this branch:  `2496-technical-highlights-and-framework-comparison`

> So if that branch still exists any PR's with these images should set their base to the `2496-technical-highlights-and-framework-comparison` branch

**Technical Highlights - 5 images needed:**
Technical Highlights: Observables - Why they’re powerful section

If you pull down the branch and go to `/doc/guides/why-canjs/technical.html` there is a section labeled **Why they’re powerful section** that has **placeholders for 5 images** (please ignore the placeholder images, they are not indicative of a design suggestion.

If the description text is not sufficient to describe what is needed please as Adam ( @BigAB ) or Brian ( @brianmoschel ) for more information.

---

Here is the section text and placeholder text and images:

>Why they’re powerful

> Observables as a concept enable an important architectural advantage in large applications.

> Say you have an application with three discrete components.

IMAGE: app with 3 things

> Without observables, you might have component A tell component B to update itself when something happens, like user input.

IMAGE: arrows showing this happening

> With observables, you would separate the state of your application into a separate layer, and each component would be able to change parts of the state it cares about and listen to parts of the state it needs. When the same user input occurs, component A would update the observable state object. Component B would be notified that a property of the observable state has changed, and update itself accordingly.

IMAGE: show this happening

> Why is this better? Because this allows each component to be untied from the rest. They each get passed the state they need, but are unaware of the rest of the components and their needs. The architecture diagram changes from this:

IMAGE: arrows pointing at everything
![image](https://cloud.githubusercontent.com/assets/76821/19786492/6fa6db24-9c5b-11e6-984e-eb73ae680271.png)

> To this:

IMAGE: state is in the middle
![image](https://cloud.githubusercontent.com/assets/76821/19786515/9663cc7c-9c5b-11e6-81d4-40ebc026b8e0.png)

> Not only is this simpler to understand, these components are more easily testable and shareable, and changes are more contained are less risky to have unwanted side effects. All of these advantages are possible because of observables.

**Comment by moschel** [comment]
@BigAB Thanks, but I'm not ready yet for these images. This section is a WiP so it's premature to make the images. I think i'll make rough versions of them first myself before a designer works on these.

**Comment by moschel** [comment]
Please don't work on this yet

**Comment by tomgreever** [comment]
@moschel - just noting that @karlshaver is available now when you get to this. Just tag/assign him
