### ISSUE TITLE
Technical Highlights: Modularity - Adopt new framework features without any upgrade effort or library bloat section - 1 image

### ISSUE THREAD

**Issue by BigAB** [canjs/canjs#2637]
> There are images needed for the [Technical Highlights](http://canjs.github.io/canjs/doc/guides/why-canjs/technical.html) and [Comparison to Other Frameworks](http://canjs.github.io/canjs/doc/guides/why-canjs/comparison.html) pages.

> Until merged, we are currently working in this branch:  `2496-technical-highlights-and-framework-comparison`

> So if that branch still exists any PR's with these images should set their base to the `2496-technical-highlights-and-framework-comparison` branch

**Technical Highlights - 1 images needed:**
Technical Highlights: Modularity - Adopt new framework features without any upgrade effort or library bloat section

If you pull down the branch and go to `/doc/guides/why-canjs/technical.html` there is a section labeled **Adopt new framework features without any upgrade effort or library bloat section** that has a **placeholder for 1 image**

If the description text is not sufficient to describe what is needed please as Adam ( @BigAB ) or Brian ( @brianmoschel ) for more information.

---

Here is the section text for context there are no placeholder images:

>Adopt new framework features without any upgrade effort or library bloat

> For users that have an existing application, this modularity means they can leave their application and all it’s dependencies alone, forever, while using new features and parts of the library in other areas of the application.

> For example, say an entire application is built with CanJS 3.0. The following year, the developer is tasked with adding a new feature. At that point, can-component 4.0 is out with a new set of features. The developer can simply leave the remainder of the application using CanJS 3.0 (including can-component 3.0), and import can-component 4.0 in the new area of the application. It will likely still share the same lower level dependencies, since those are less likely to change very often, so this adds an insignificant amount of code weight.

IMAGE: show application component blocks using 3.0, with new area using can-component 4.0, but sharing same low level dependencies

> Angular 1.x to 2.0 is a good counterexample to this approach. The recommended upgrade strategy was to either rewrite your application with 2.0 (a lot of extra work) or load your page with 1.X and 2.0, two full versions of the framework (a lot of code weight). Neither is preferable.

> With the modularity described in CanJS, applications can import multiple versions of the high level APIs while avoiding the work of rewriting with future syntaxes and the extra code weight of importing two full frameworks.

**Comment by moschel** [comment]
Please don't work on this yet.

**Comment by tomgreever** [comment]
Same here. @moschel not sure why this was closed. @BigAB included it in a long list of issues that needed a designer, so let me and @karlshaver know if you still need help.
