### ISSUE TITLE
Technical Highlights: Observables - Data bound templates - 1 image needed

### ISSUE THREAD

**Issue by BigAB** [canjs/canjs#2638]
> There are images needed for the [Technical Highlights](http://canjs.github.io/canjs/doc/guides/why-canjs/technical.html) and [Comparison to Other Frameworks](http://canjs.github.io/canjs/doc/guides/why-canjs/comparison.html) pages.

> Until merged, we are currently working in this branch:  `2496-technical-highlights-and-framework-comparison`

> So if that branch still exists any PR's with these images should set their base to the `2496-technical-highlights-and-framework-comparison` branch

**Technical Highlights - 1 image needed:**
Technical Highlights: Observables - Data bound templates

If you pull down the branch and go to `/doc/guides/why-canjs/technical.html` there is a section labeled **Data bound templates** that has a **placeholder for 1 image**

If the description text is not sufficient to describe what is needed please as Adam ( @BigAB ) or Brian ( @brianmoschel ) for more information.

---

Here is the section text for context, there are no placeholder images:

> Data bound templates

> Although not directly a feature of observables, data bound templates are a feature of CanJS Views that are tied closely with the observable layer.

> Templates in CanJS bind to property changes and update the DOM as needed.

> For example, there may be a template that looks like this:

> ```
> <div>{{fullName}}</div>
> ```

>If first is changed:

>```
> person.first = 'Jane';
> fullName recomputes, then the DOM automatically changes to reflect the new value.
> ```

> Observables express complex relationships between data, without regard to its display. Views express properties from the observables, without regard to how the properties are computed. The app then comes alive with rich functionality.

DIAGRAM - circular arrows pointing back to each layer

**Comment by tomgreever** [comment]
Curious why this one was closed? @karlshaver is available to work on it, if needed.
