### ISSUE TITLE
Technical Highlights: MVVM - Composed, hierarchical state - 1 image needed

### ISSUE THREAD

**Issue by BigAB** [canjs/canjs#2639]
> There are images needed for the [Technical Highlights](http://canjs.github.io/canjs/doc/guides/why-canjs/technical.html) and [Comparison to Other Frameworks](http://canjs.github.io/canjs/doc/guides/why-canjs/comparison.html) pages.

> Until merged, we are currently working in this branch:  `2496-technical-highlights-and-framework-comparison`

> So if that branch still exists any PR's with these images should set their base to the `2496-technical-highlights-and-framework-comparison` branch

**Technical Highlights - 1 image needed:**
Technical Highlights: MVVM - Composed, hierarchical state

If you pull down the branch and go to `/doc/guides/why-canjs/technical.html` there is a section labeled **Composed, hierarchical state** that has a **placeholder for 1 image**

If the description text is not sufficient to describe what is needed please as Adam ( @BigAB ) or Brian ( @brianmoschel ) for more information.

---

Here is the section text for context, there are no placeholder images:

> Composed, hierarchical state

> CanJS applications are composed from hierarchical components, each containing their own independent state (it’s own ViewModel). This architecture is at the core of CanJS’ approach to building large applications.

> The secret to building large apps is never build large apps. Break your applications into small pieces. Then, assemble those testable, bite-sized pieces into your big application.

IMAGE: show a diagram of several components and their ViewModel properties

> Hierarchical State Machines (HSMs) is one way to describe this concept. UML diagrams allow for modeling of hierarchically nested states, such as those in CanJS applications. Check out the ATM guide for an example of a hierarchical state machine implemented using hierarchical ViewModels.

> React, and other competing frameworks, have a big global state object that contains the application’s state. The problem with this approach, at least in any application with even moderate complexity, is that this monolithic layer becomes a dependency of every component in the application. This creates additional downstream problems:

**Comment by tomgreever** [comment]
Same here. @moschel not sure why this was closed. @BigAB included it in a long list of issues that needed a designer, so let me and @karlshaver know if you still need help.
