### ISSUE TITLE
Image needed: CanJS Mission page

### ISSUE THREAD

**Issue by moschel** [canjs/canjs#2660]
I need help creating an image for the following section.

_______________

The constantly changing JavaScript ecosystem has made it hard for developers and their apps to keep up.

You shouldn't have to rewrite your application to keep pace with technology.

The CanJS mission is to help developers transcend the changing technology landscape.

CanJS’ intended audience is experienced developers building complex
applications, which they intend to live for a long time.

We aim to provide a stable platform so those developers can block out noise and stay focused on their app, not the tools.

IMAGE: Smooth ride, looking out the window, while hurricane of JavaScript logos and terminology passes by outside the window. Vehicle has an arrow pointing forward towards progress.

_______________

I didn't create a sample of what I mean because it would not turn out useful. I'm visualizing:

 * someone looking out a car window, or maybe even like a train window like this:
![looking-out-window-on-train](https://cloud.githubusercontent.com/assets/22180/19880163/c034c73e-9fc8-11e6-94a9-e965fb6380d6.jpg)
 * Out the window they might see a volcanic hellfire like this:
![hellscape](https://cloud.githubusercontent.com/assets/22180/19880177/ec5584ca-9fc8-11e6-8df5-f2ca36dc5c64.jpg)
 * In that hellscape there is a tornado with a bunch of JS framework logos (or maybe it's part of a fire or volcano).
 * The train or car has a green arrow pointing forward toward progress (maybe, or maybe this is too corny/literal)

I realize this is a ridiculous description. It's intended to be funny and cartoonish, so feel free to have fun with it.

**Comment by tomgreever** [comment]
@brianmoschel when you get to this again, let me know because I think we might want to have Eric (who drew the turtle) to do a custom illustration for this too.

**Comment by moschel** [comment]
Justin took over this page and I don't think he wants this image in there anymore, so i'll close it.

**Comment by moschel** [comment]
@justinbmeyer reopen if you still want this.
