### ISSUE TITLE
Proposal: Publish Builds

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/canjs#2666]
http://www.jsdelivr.com/projects/canjs

look at this we should update that because it even allows chaining of the used libs its so nice to click a cdn url from them together with needed components without build.

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

Example https://cdn.jsdelivr.net/npm/jquery@3.1.1
Example directory listing https://cdn.jsdelivr.net/npm/jquery@3.1.1/
