### ISSUE TITLE
Docs: CDN links to canjs.com/release are gone

### ISSUE THREAD

**Issue by ccummings** [canjs/canjs#2684]
The old `//canjs.com/release/x.x.x/` files have disappeared (likely in prep for the 3.0 site) which means the majority of the jsbin/jsfiddle's that we and others have published are now broken.

We might want to set something up to handle these. https://unpkg.com is a good replacement, but we have to figure out what to do with links to the old files.

**Comment by daffl** [comment]
Sorry those should still be there. I updated the release folder with latest. We probably want to keep them but for 1.x and 2.x release could refer to rawgithub.com (from https://github.com/bitovi/canjs.com).
