### ISSUE TITLE
Run tests in IE 11

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#2686]
Remaining issues:
- [x] https://github.com/canjs/can-stache/issues/95
- [x] https://github.com/canjs/can-stache-bindings/issues/85

**Comment by justinbmeyer** [comment]
@phillipskevin is this closed?

**Comment by phillipskevin** [comment]
Yes, this is closed.

**Comment by matthewp** [comment]
@phillipskevin how do we get the saucelabs message updated.

**Comment by phillipskevin** [comment]
Looks like this was reverted, which is why IE 11 isn't showing up in the sauce labs badge.

**Comment by phillipskevin** [comment]
Re-added by https://github.com/canjs/canjs/commit/8ab0b8e35ccf305188d510a98f8dffe86ea09ee1. Badge should be updated shortly.
