### ISSUE TITLE
Review ATM Guide

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2692]
- [x] - [Card Tests](http://v3.canjs.com/doc/guides/atm.html#Cardtests) -> “Update the JS tab to:” -> restoring it to `2md` after every test runs
  - should say `2s`
- [x] - [Transaction, Deposit, and Withdrawal models](http://v3.canjs.com/doc/guides/atm.html#Transaction_Deposit_andWithdrawalmodels) -> no description or code highlighting for account model creation
  - The Account model implementation needs to be part of the new code block
  - The “Update the JavaScript tab to:” section needs to include a description for the implementation of the Account Model
- [x] - [Choosing Transaction page and test](http://v3.canjs.com/doc/guides/atm.html#ChoosingTransactionpageandtest) -> "Update the TESTS section of the JavaScript tab to:" - call `.chooseDeposit()` - new test code not highlighted
  - Should highlight the [new test code](https://github.com/canjs/canjs/blob/master/docs/can-guides/experiment/atm/8-choosing-transaction/js.js#L379)
- [x] - [Withdrawal Info Page](http://v3.canjs.com/doc/guides/atm.html#WithdrawalInfopage) -> no tests added
  - In the "In this section, we will" part, it says "Add tests to ATM Basics test, but no tests are added
  - Need to ~add tests~ remove the description about adding tests.  Adding tests here would require a cascading refactor of the rest of the tests because we'd need to create a whole other flow ("ATM Basics - Deposit" vs "ATM Basics - Withdrawal").  Will create another issue to address this.
- [x] - Loader images not visible (1x1 pixel)
  - They're all pointing to `<img src="http://www.bristolallheart.com/media/mod_mailchimpsignup/images/ajax-loader.gif"/>`
  - Find appropriately styled loader and host it

**Comment by mickmcgrath13** [comment]
Issue to handle the Withdrawal tests: canjs/canjs/issues/2712
