### ISSUE TITLE
ATM Guide - Explanations for no Withdrawal tests

### ISSUE THREAD

**Issue by mickmcgrath13** [canjs/canjs#2712]
- [x] - There is a section for adding a [Deposit Test](http://localhost:8080/doc/guides/atm.html#Deposittest), but there isn't one for Withdrawal Test
  - Need to explain why there is no section for Withdrawal Test
- [x] - [Withdrawal Info Page](http://v3.canjs.com/doc/guides/atm.html#WithdrawalInfopage) -> no tests added
  - In the "In this section, we will" part, it says "Add tests to ATM Basics test, but no tests are added
  - Need to explain why no tests are being added

**Comment by justinbmeyer** [comment]
I don't think we need one for Withdrawal.  it would be the same test. It's a guide.  

Same with the withdrawal info page ... no tests needed.

The guide gets across the point w/o needing these.

**Comment by justinbmeyer** [comment]
Well, I was thinking we might explain why they aren't there.  I could see people being confused.

**Comment by mickmcgrath13** [comment]
I've updated the description and first comment accordingly.  I'll knock that out tomorrow
