### ISSUE TITLE
CanJS 3.4.0

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2718]

**Comment by matthewp** [comment]
3.4 is out.

**Comment by phillipskevin** [comment]
There are still a bunch of issues in this epic that are not complete, so I'm going to re-open this and rename it 3.5.0. I don't know if this is the best way to do it, but it's what we've been doing. If someone has a better approach for handling the "next minor release" epic let me know.

**Comment by phillipskevin** [comment]
I see there's already an Epic for 3.5, so I'm going to re-close this. We'll just need to move these over:

![image](https://cloud.githubusercontent.com/assets/5851984/22336986/80699ad8-e3a9-11e6-813a-9c7ebe932783.png)
