### ISSUE TITLE
Bitovi menu is incorrect

### ISSUE THREAD

**Issue by tomgreever** [canjs/canjs#2739]
The Bitovi menu in 3.0 has "Consulting" which leads to `bitovi.com/consulting` resulting in a 404. Should be "Design" and "Development"

While we're at it, the two dots logo is way too big compared to the nav and the CanJS logo. I recommend making it smaller. 

![screen shot 2016-11-11 at 7 37 53 am](https://cloud.githubusercontent.com/assets/326843/20216754/f700549c-a7e1-11e6-97ce-29f664ae3503.png)

**Comment by leoj3n** [comment]
So, add two new menu items? Like:

- Bitovi.com
- Blog
- Design
- Development
- Training
- Open Source

Looks like http://donejs.com/ links to the 404 as well.

Haven't looked into whether or not that would be a separate change or not, but I think it will as I assume this is coming from the respective bit-docs website themes.

**Comment by leoj3n** [comment]
Looks like it comes from here:

https://github.com/canjs/bit-docs-html-canjs/blob/master/templates/header-right.mustache#L8

Perhaps we can make it a reusable component to standardize the menu items and logo size across websites.

**Comment by chasenlehara** [comment]
A reusable component would be nice, but not a priority for now. @leoj3n, would you mind submitting a PR to fix the CanJS, DocumentCSS, and DoneJS sites please? [I think all the other ones are ok.]

**Comment by matthewp** [comment]
The websites are not single page CanJS apps so that couldn't be a can-component.
