### ISSUE TITLE
Demos aren't working

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2740]
On http://v3.canjs.com/doc/can-component.html and everywhere else, the demo pages aren't working:

![canjs_-_can-component](https://cloud.githubusercontent.com/assets/78602/20220452/2e68e5aa-a7f3-11e6-853c-bd997c9a361d.png)

This is because steal.js is a 404.  

![canjs_-_can-component](https://cloud.githubusercontent.com/assets/78602/20220481/54429686-a7f3-11e6-916f-b65dbc528ab8.png)

However, it is in gh-pages:

https://github.com/canjs/canjs/blob/gh-pages/node_modules/steal/steal.js

The `Makefile` is certainly adding it:

https://github.com/canjs/canjs/blob/master/Makefile#L10

**Comment by phillipskevin** [comment]
Looks like demos are broken again (or still?).
