### ISSUE TITLE
Improve stability of CanJS by moving out stateful modules and providing warnings

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2747]
Currently, if a person loads multiple versions of `can-util` or `can-observation` their app will not work.

We should make this less likely and warn if this is going to happen.

Currently, there are some stateful modules in `can-util` like:

- can-util/namespace
- can-util/types
- can-util/js/cid

That must never be loaded twice.  If loaded twice, the app will break.

My suggestion is to:

1.  Create a `can-namespace`.  This should export just an empty object `{}`, be marked as `1.0` and NEVER change.  I might even consider having it add `can` to the global ... simply to make sure no other `can` has ever been created.

2.  All other stateful modules should be moved out into their own repo.  They should import `can-namespace` and check if someone else added their name to `can-namespace`.  If someone has, throw a warning.  If not, add themselves.  For example:

```js
if( namespace.Observation ) {
  throw "You can't have two versions of can-observation, check your dependencies";
} else {
  module.exports = namespace.Observation = Observation;
}
```

Combined, this should decrease the likely hood of incompatible versions (`cid`, `can-obsevation`
shouldn't change very often) and it will give people a warning when something went wrong.

**Comment by phillipskevin** [comment]
`can-view-callbacks` adds the list of custom tags as `can.view.callbacks._tags`. I am planning to move this to a new `can-tags` repo and throw whenever `namespace.tags` is already set when `can-tags` is loaded.

Also, should `can-observation` throw whenever `namespace.Observation` is defined twice? Or should I create another repo for it's global state `can-observation-stack`? Is it possible that anything other than `can-observation` would want to add to the `observationStack`?

@justinbmeyer what do you think?

**Comment by justinbmeyer** [comment]
@phillipskevin For now, I would prioritize preventing errors/bugs over "fuzzy use cases".  This means, I wouldn't worry about making a `can-observation-stack` and handle this in `can-observation`.

For `can-tags` .... I have to think about that.  I'm wary of getting too deep into defining the behavior of a tag because for all intents and purposes, tags are really just `stache` mixins.

I think `can-tags` needs to be part of a large discussion on how we could support:

 - multiple template engines
 - multiple binding syntaxes
 - multiple "types" of components (can.Component, can.Element)

**Comment by phillipskevin** [comment]
For now I will just have `can-view-callbacks` handle the case where it is loaded twice. We can make a decision about separating out the `tags` state into its own repo once that larger discussion happens.
