### ISSUE TITLE
Clean up "who's using" page

### ISSUE THREAD

**Issue by moschel** [canjs/canjs#2753]
Use better screenshots for this page: http://v3.canjs.com/doc/guides/who-uses-canjs.html

**Comment by tomgreever** [comment]
@brianmoschel what do you think about something like this? This adds a border and dropshadow, which makes them look nicer. And for the ones that include a url, we can fake a browser address bar. This won't change the markdown other than wrapping the section in a parent div. Other than that it's just CSS, so it should still be simple to update.

![screen shot 2016-11-16 at 12 33 48 pm](https://cloud.githubusercontent.com/assets/326843/20360351/f9fdb17e-abf8-11e6-9c62-a2545ed4bbec.png)

**Comment by tomgreever** [comment]
oh and it scales nicely. 
![screen shot 2016-11-16 at 12 36 46 pm](https://cloud.githubusercontent.com/assets/326843/20360439/6222f55c-abf9-11e6-9774-6cfdad304086.png)

**Comment by moschel** [comment]
looks good to me

**Comment by tomgreever** [comment]
This should be closed by #2757 - I'm not seeing the changes on GH pages yet, but closing anyway and trusting it's gtg since the PR was merged
