### ISSUE TITLE
Images cleanup for Mission page

### ISSUE THREAD

**Issue by moschel** [canjs/canjs#2754]
Change the style and improve the quality of images on this page.

http://v3.canjs.com/doc/guides/mission.html

"SproutCore -> Knockout -> Backbone -> Angular -> React -> ?" I think should be turned into an image also. @justinbmeyer did you intend for that to be an image? I know that used to be the Zoolander graphic.

**Comment by tomgreever** [comment]
@brianmoschel @justinbmeyer here is the first one. If this is good to go, I'll finish the rest!

![timeline-bomb1](https://cloud.githubusercontent.com/assets/326843/20406751/1e586d4e-acd4-11e6-86d8-20f57d5940a1.png)

**Comment by tomgreever** [comment]
![timeline-bomb2](https://cloud.githubusercontent.com/assets/326843/20407251/27a18438-acd6-11e6-82be-22f0944a82f9.png)

**Comment by tomgreever** [comment]
![timeline-mission](https://cloud.githubusercontent.com/assets/326843/20408092/a3fdcac0-acd9-11e6-8068-4eacbfdc62c3.png)

**Comment by tomgreever** [comment]
![timeline-canjs](https://cloud.githubusercontent.com/assets/326843/20409309/c6194238-acde-11e6-81b4-d6540f4a5f81.png)

**Comment by moschel** [comment]
looks good to me

**Comment by justinbmeyer** [comment]
Maybe it's me, but I find that font still pretty hard to read.

**Comment by tomgreever** [comment]
@justinbmeyer @chasenlehara Here are a few other options that still appeal to the informal/handwritten style. 

Please let me know what you think today. If the font is the only thing left, I'll probably pick one and submit a PR today if I don't hear back. We can always update it afterwards, but I want to get this in before the weekend.

## Original
![screen shot 2016-11-18 at 8 45 13 am](https://cloud.githubusercontent.com/assets/326843/20433955/69f2921a-ad6b-11e6-8c24-9e788b878104.png)

## Different Options
![screen shot 2016-11-18 at 8 45 02 am](https://cloud.githubusercontent.com/assets/326843/20433970/748c706a-ad6b-11e6-958d-13b490283f7a.png)
![screen shot 2016-11-18 at 8 45 07 am](https://cloud.githubusercontent.com/assets/326843/20433972/785e8458-ad6b-11e6-8331-4b62712f5bbb.png)

**Comment by tomgreever** [comment]
My recommendation is the first one. 

![betting-bomb](https://cloud.githubusercontent.com/assets/326843/20434274/ac527886-ad6c-11e6-90d5-6519cf4b3bc0.png)
