### ISSUE TITLE
Automate release notes

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#2763]
Some possible solutions:

- https://github.com/skywinder/github-changelog-generator
- https://github.com/conventional-changelog/conventional-changelog-cli
- https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by phillipskevin** [comment]
https://github.com/zeit/release is another option

**Comment by bgando** [comment]
When canjs has a release, pull the latest release notes from the updated can-* packages and aggregate them into the latest canjs release notes.
