### ISSUE TITLE
Better images for CanJS upgrade path

### ISSUE THREAD

**Issue by tomgreever** [canjs/canjs#2765]
These look like they were made by a sleep-deprived developer in PowerPoint

On the mission page: http://v3.canjs.com/doc/guides/mission.html

<img width="802" alt="mission-stability-upgrade-new" src="https://cloud.githubusercontent.com/assets/326843/20409452/4458e4a0-acdf-11e6-9b87-92953dcd8b1b.png">
<img width="537" alt="mission-stability-upgrade-breakdown" src="https://cloud.githubusercontent.com/assets/326843/20409451/44577a48-acdf-11e6-9c05-097a410a9db5.png">
<img width="537" alt="mission-stability-3-upgrade" src="https://cloud.githubusercontent.com/assets/326843/20409453/445bbd7e-acdf-11e6-9362-d2993e349fdb.png">

**Comment by tomgreever** [comment]
I've asked Eric Merced to draw some stuff for this to make it better.

**Comment by tomgreever** [comment]
@justinbmeyer would you mind providing feedback on these? I can submit a PR real-quick like if you think they are gtg

![turtle-1-final](https://cloud.githubusercontent.com/assets/326843/20676395/3dd3bb5e-b555-11e6-9d1a-8b89f949fb01.jpg)

![turtle-2-final](https://cloud.githubusercontent.com/assets/326843/20676394/3dd29058-b555-11e6-8f3f-49b308674f0f.jpg)

![turtle-3-final](https://cloud.githubusercontent.com/assets/326843/20678142/45493f52-b55b-11e6-8b0e-099434c2a3d5.jpg)

**Comment by justinbmeyer** [comment]
they look great!
