### ISSUE TITLE
Production tests are failing

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#2778]
Running `npm run test-production` is currently not working.

This request is failing (copied from Firefox's network panel):
```
curl 'http://localhost:3996/socket.io/?EIO=3&transport=polling&t=LY7dlWy' -H 'Host: localhost:3996' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Content-Type: text/plain;charset=UTF-8' -H 'Referer: http://localhost:3996/test/production.html?__token=70fnr5' -H 'Content-Length: 3' -H 'Cookie: io=PRPsKPt8YVMu-q83AAAX' -H 'Connection: keep-alive'
```

with this response:
```
{"code":2,"message":"Bad handshake method"}
```

**Comment by phillipskevin** [comment]
This is needed to create new releases.

**Comment by phillipskevin** [comment]
This is caused by `can-fixture`'s xhr.js overwriting `XMLHttpRequest`. I attempted to fix this by using getters/setters to make sure the properties of our mock XHR match that of the real XHR (code can be found [here](https://github.com/canjs/can-fixture/tree/getter-setters)), but this did not solve the problem.

There must still be something that our XHR is not doing correctly, but I don't have an idea what it is.

I've also determined that this only happens in the production tests because in dev mode socket.io loads before we overwrite `XMLHttpRequest`. If I delay xhr.js from loading then the issue goes away in production mode also.

A workaround for this issue is to try to make xhr.js load after socket.io, even in the built version of the tests. To do this, perhaps `can-fixture` can be separated into its own bundle or `socket.io` can be set as a dependency of `can-fixture/xhr`.

**Comment by matthewp** [comment]
Overwriting globals has proven to be more of a headache than its worth in my opinion.

**Comment by phillipskevin** [comment]
Keeping open until released.

**Comment by phillipskevin** [comment]
Closed by https://github.com/canjs/canjs/pull/2805.
