### ISSUE TITLE
Require format problems blocks possibility to use webpack

### ISSUE THREAD

**Issue by perehnbom** [canjs/canjs#2780]
When using webpack as module loader, many CanJS modules load fine, but there are a couple of cases where require is on a format that doesnt work, e.g. require("can-event/batch/") instead of require("can-event/batch/batch"). There's also cases where the property "main" in package.json is wrong.

To try out CanJS with webpack, I have set up the following template project: 
https://github.com/perehnbom/canjs3-webpack-template

The following changes are necessary in order to get webpack to work.

can-compute:
require('can-event/batch/') -> require('can-event/batch/batch')
require('can-util/js/cid/') -> require('can-util/js/cid/cid')

can-compute: proto-compute.js
require('can-util/js/cid/') -> require('can-util/js/cid/cid')
require('can-util/js/assign/') -> require('can-util/js/assign/assign')
require('can-util/js/types/') -> require('can-util/js/types/types')
require('can-util/js/is-empty-object/') -> require('can-util/js/is-empty-object/is-empty-object')

can-util : dom/events/make-mutation-event
require("../../../js/each/") -> require("../../../js/each/each")
require("../../data/") -> require("../../data/data")
require("../../dispatch/") -> require("../../dispatch/dispatch")
require("../../mutation-observer/document/") -> require("../../mutation-observer/document/document")
require("../../document/") -> require("../../document/document")
require("../../is-of-global-document/") -> require("../../is-of-global-document/is-of-global-document")

can-view-model: package.json
"main" : "dist/cjs/can-view-model" -> "main" : "can-view-model"

can-view-live: package.json:
"main" : "dist/cjs/can-view-live" -> "main" : "can-view-live"

can-simple-map: package.json
"main": "dist/cjs/can-simple-map" -> "main": "can-simple-map"

can-stache:
require('../helpers/core') -> require('./helpers/core')
require('../helpers/converter') -> require('./helpers/converter')

**Comment by matthewp** [comment]
Can you submit PRs to those repos? Looks like you already did the work to identify the problems.

**Comment by perehnbom** [comment]
Hi, yes I've identified the problems. Im happy to submit pull requests to
the repos. It's the first time I do that for CanJS but I guess it shouldnt
be too hard.

/Per

**Comment by justinbmeyer** [comment]
Thanks! We will accept them if you make them.

**Comment by justinbmeyer** [comment]
Thanks for making these!  I've started publishing them.  So far only:
- can-util 3.0.13
- can-compute 3.0.4

I will get to the rest you've already made pull requests for today.

**Comment by perehnbom** [comment]
I should be thanking you, CanJS is in my opinion the best framework out there if you're looking to build an advanced SPA. And I've been working with quite a few frameworks.

**Comment by justinbmeyer** [comment]
Thanks!  Please let others know ( http://v3.canjs.com/doc/guides/contributing/evangelism.html ) and let us know if there's anything we can do to help you be successful on your project.

**Comment by perehnbom** [comment]
These changes should be sufficient for all canjs modules to work with webpack

**Comment by justinbmeyer** [comment]
I published those first 6 packages.  Please let me know if I need to publish any others immediately so you can get work done.  Otherwise, they will be published next week along with CanJS 3.2.

**Comment by perehnbom** [comment]
I encountered another problem when using can-fixture. Both webpack 1 and 2 gives an error when requiring can-fixture, and the problem is because of the code snippet `require.resolve` in fixture.js:

```
if(typeof window !== "undefined" && !require.resolve) {
	window.fixture = fixture;
}
```

I’m not quite sure why this is a problem in webpack but I’ll post a PR all the same that eliminates the problem. I'll let you decide whether to accept it or not.

**Comment by perehnbom** [comment]
Another problem encountered in webpack 2 but that works in webpack 1 is the following in can-connect/data/url/url.js:

`var getIdProps = require("../../helpers/get-id-props");`

That is strange since similar requires in e.g. can-util works fine:

```
var assign = require("../../js/assign/assign");
var namespace = require("../../namespace");
var parseURI = require('../../js/parse-uri/parse-uri');
```

And the require of get-id-props works fine when using

`var getIdProps = require(”can-connect/helpers/get-id-props");`

It looks like it has something to do with the name starting with `get-` but I would consider that being a bug in webpack 2, not CanJS, and maybe that should be filed as a webpack bug.

**Comment by perehnbom** [comment]
After looking more closely into the problems described about can-connect I found the following: 

In can-connect/package.json there's a property "browser" which sets up module paths. The paths are defined so modules point to the dist folder e.g `"./helpers/get-index-by-id": "./dist/cjs/helpers/get-index-by-id"`. I dont see similar use of "browser" in other canjs modules.

Webpack 2 seems to use the "browser" property in order to resolve module paths, and since the path is to the dist folder and not the source, the build fails. 

I'm not quite sure why this configuration in can-connect is there in the first place, but by either removing the "browser" property, or set the paths point to the source instead of the dist, the problem is solved.

**Comment by matthewp** [comment]
Since can-connect uses a regular CommonJS structure now I don't think it needs the "browser" config any more. True @justinbmeyer @phillipskevin ?

**Comment by justinbmeyer** [comment]
Yes, it can be removed

**Comment by matthewp** [comment]
@perehnbom https://github.com/canjs/can-connect/issues/200

**Comment by perehnbom** [comment]
Thanks, I can setup a PR for can-connect if you want me to.

**Comment by matthewp** [comment]
That would be great, thanks!

**Comment by matthewp** [comment]
@perehnbom I did can-connect.

**Comment by matthewp** [comment]
Oops, no I haven't I guess. Still fixing.

**Comment by matthewp** [comment]
Ok, can-connect **is** fixed. I'm going to go through other projects and see if they have the same issue.

**Comment by matthewp** [comment]
Everything should be working now @perehnbom   I'll close for now but if you have any other issues let me know.

**Comment by perehnbom** [comment]
thanks @matthewp , I hadnt had the time to go over it yet. I've upgraded to canjs 3.2.0 + can-connect 1.0.14. Everything I've covered in my test application now works with both webpack 1 and 2.

**Comment by perehnbom** [comment]
canjs 3.2.0 uses can-connect 1.0.12 so that would need an upgrade in the next release.
