### ISSUE TITLE
Create an agenda for the user experience testing

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2788]
The agenda should outline everything that should be covered during CanJS user experience testing.

**Comment by chasenlehara** [comment]
@justinbmeyer, here’s a rough agenda for what I’ll go through with each person tomorrow:

1. Ask some questions to establish their familiarity with JavaScript and CanJS (5 minutes)
2. Direct them to the CanJS homepage, have them go through it and get their feedback (5–10 minutes)
3. Let them browse around the site a bit based on what they’re interested in (15–20 minutes)
4. If they haven’t already, direct them to pages like Mission and Technical Highlights to get their feedback (15–20 minutes)
5. Break! (5–10 minutes)
6. Help them pick an experiment guide (e.g. the Chat or TodoMVC guides), have them go through it and collect their feedback (30–90 minutes)
7. Closing thoughts: collect general feedback about the site, framework, etc. (10–15 minutes)

Please let me know if I’ve left out something you’d like me to cover.

**Comment by justinbmeyer** [comment]
Sounds good. Thanks!
