### ISSUE TITLE
2.3: Stache inserts element twice using switch inside two or more <content/> tags

### ISSUE THREAD

**Issue by ccummings** [canjs/canjs#2790]
Using a `#switch` statement inside of two or more nested `<content />` tag causes the content within the `switch` to be inserted twice.

For example this template where `<echo-comp>` has `<content />` as its template will cause `<my-comp>` to be inserted twice.

```html
<echo-comp>
  <echo-comp>
    {{#switch page}}
      {{#case 'home'}}
        <my-comp></my-comp>
      {{/case}}
    {{/switch}}
  </echo-comp>
</echo-comp>
```

[Example in JSBin](http://jsbin.com/hunuti/edit?html,js,output)

Adding more `<echo-comp>` elements does not cause any extra inserts. No matter how deeply nested, only 2 inserts are performed.

I have confirmed that this is not an issue in 3.0.

**Comment by justinbmeyer** [comment]
If someone wants to help see this through, we'll get a release out.
