### ISSUE TITLE
Having issues using Browserify with CanJS 3

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2794]
When I tried to use a module like `can-define/map/map`, I get this error when I build with Browserify:
```
Error: Cannot find module 'cssify' from '~/canjs-browserify-npm/node_modules/can-observation'
    at ~/.nvm/versions/node/v6.9.1/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (~/.nvm/versions/node/v6.9.1/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (~/.nvm/versions/node/v6.9.1/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (~/.nvm/versions/node/v6.9.1/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (~/.nvm/versions/node/v6.9.1/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at ~/.nvm/versions/node/v6.9.1/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

I’ve created a repo to demo this issue. Here’s the code in my `can-define-map` branch that demonstrates the issue: https://github.com/chasenlehara/canjs-browserify-npm/blob/can-define-map/main.js

Requiring a module like `can-util` works correctly (`master` branch): https://github.com/chasenlehara/canjs-browserify-npm/blob/master/main.js

Please let me know if this is a CanJS bug or if I need to do more setup to make it work with Browserify.

**Comment by matthewp** [comment]
The problem seems to be that a bunch of packages have a `cssify` transform listed even though they don't have anything to do with CSS. Going to post subissues as I find them:

https://github.com/canjs/can-construct/issues/19

**Comment by matthewp** [comment]
Those are the only issues.

**Comment by matthewp** [comment]
Fixed those two issues and it looks to be working fine now. Reopen if you see otherwise.

**Comment by chasenlehara** [comment]
Reopening because `can-stache` has the same issue: https://github.com/canjs/can-stache/blob/master/package.json#L31

**Comment by matthewp** [comment]
A convenient link: https://github.com/search?p=1&q=org%3Acanjs+cssify&type=Code

**Comment by matthewp** [comment]
@chasenlehara this should be fixed now.

**Comment by chasenlehara** [comment]
Thanks @matthewp, I will test the new releases either today or tomorrow. Closing for now.
