### ISSUE TITLE
There is something wrong with the @ page key@prop link

### ISSUE THREAD

**Issue by BigAB** [canjs/canjs#2827]
![the-at-page](https://cloud.githubusercontent.com/assets/76821/20764303/3fd7d5da-b6f3-11e6-809a-c5c83f0bc49b.gif)

Clicking on the menu, the link at `2.` changes in to ...some big mess. Refreshing makes it go back to normal.

**Comment by chasenlehara** [comment]
Closing in favor of https://github.com/canjs/bit-docs-html-canjs/issues/211
