### ISSUE TITLE
Add docs for adding to the CanJS ecosystem

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2844]
Please add instructions for how to get a package included in the CanJS website in the ecosystem sections.

Related to https://github.com/canjs/canjs/issues/2463

**Comment by justinbmeyer** [comment]
- `@package ./package.json`
- `@parent can-ecosystem`
- `require("your-package")` in _ecosystem.js_
- in _canjs.md_
  - add highlight like:

  ```
  - **[can-fixture]** <small><%can-fixture.package.version%></small> Simulate AJAX requests
    - `npm install can-fixture --save`
    - <a class="github-button" href="https://github.com/canjs/can-fixture" data-count-href="/canjs/can-fixture/stargazers" data-count-api="/repos/canjs/can-fixture#stargazers_count">Star</a>
  ```
  - `"can-fixture-socket": "<%can-fixture-socket.package.version%>", `

**Comment by Macrofig** [comment]
@justinbmeyer's comment explains what needs to happen in the CanJS repo.

I think it would be helpful to describe the process of using bit-docs in the source repository as well.

I'm assuming the docs should be added [here](http://canjs.com/doc/guides/contributing/documentation.html)?

**Comment by phillipskevin** [comment]
The first two bullets in @justinbmeyer's comment are about the source repo. I think those are the only real requirements. Are there other things you're finding?

**Comment by justinbmeyer** [comment]
There's no "hard requirement" to use bit-docs in he source repo.

**Comment by Macrofig** [comment]
There were a few tiny things to make notes of, but other than that, the above steps were fine.
 Here's a rough draft of what I noted down:

https://gist.github.com/Macrofig/32b4070858b4dd1bee97a40b86f212bc
