### ISSUE TITLE
Stache removes elements in undesired order

### ISSUE THREAD

**Issue by Macrofig** [canjs/canjs#2850]
I have a component with a template that inserts a few other components in a nested order.  The main component's template has a conditional, when falsey, the nested components are removed.

When the components are inserted, they are inserted in a specific order (top to bottom) but when they are removed, they are removed in an odd order:

- child
- grand-parent
- parent

I would expect (bottom to top)

- child
- parent
- grand-parent

Demo of undesired behavior: http://jsbin.com/mufucag/6/edit?console,output

**Comment by justinbmeyer** [comment]
This is probably a bug with `can-view-live.list`.  In general, the computes passed to `can-view-live` have a primaryDepth.  But I think this is ignored by `can-view-live.list`.  

I think that can-view-live.list should opt into the same "update schedule" that computes have.  This is something @phillipskevin and I talked about with a recent can-view-live.list change.

**Comment by justinbmeyer** [comment]
Closing for https://github.com/canjs/canjs/issues/2447
