### ISSUE TITLE
Make the in-page navigation more visible

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2861]
Two of three UX testers explicitly mentioned that they wish they could easily navigate between the sections in a page. They looked through the navigation on the left; we offer that navigation in the top black bar, which they seemed to not notice (they never interacted with it).
<img width="1000" alt="screen shot 2016-12-08 at 2 45 15 pm" src="https://cloud.githubusercontent.com/assets/10070176/21027183/51aed9bc-bd55-11e6-82c3-45e5d7a58342.png">

**Comment by chasenlehara** [comment]
@justinbmeyer and I talked about following a similar pattern to what’s used by the [DoneJS](https://donejs.com/Features.html) and [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) sites: a table of contents that sticks to the right as the user scrolls.

I think this would be more visible to users and would also help with the content not being so wide on widescreen displays.

**Comment by justinbmeyer** [comment]
Can you open all issues like this in bit-docs-html-canjs?  It's easier to consolidate functionality issues that way.

**Comment by chasenlehara** [comment]
Issue moved to [canjs/bit-docs-html-canjs #202](https://github.com/canjs/bit-docs-html-canjs/issues/202) via [**ZenHub**](https://www.zenhub.com/)

**Comment by chasenlehara** [comment]
👍 Sorry about that.

Looks like ZenHub has a “Move Issue” feature in the right sidebar that makes this pretty easy.
