### ISSUE TITLE
Move the API Guide page

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2863]
The [API Guide](http://canjs.com/doc/guides/api.html) currently has this outline:

1. Documentation Structure
2. Package and Module Pages
3. Functions, Properties, and Typedef pages
4. How to find what you’re looking for…

When UX testers went to this page, they expected to see an overview of the entire CanJS API, not info about how to use the site.

Arguably, we shouldn’t need to have a page that tells the users about the site’s information architecture; it should be obvious how to move through the site without reading a how-to guide. However, if we do keep this page, we should either rename it or move it so new users aren’t confused by its presence.

**Comment by imaustink** [comment]
@chasenlehara with all the structure changes coming to the site I feel like it would be safe to remove this page entirely. Do you concur?

**Comment by chasenlehara** [comment]
No, we’re going to keep it.

**Comment by imaustink** [comment]
Okay, what do you think about renaming it to "API Introduction"? I am not sure where we would move it that is more relevant than the "guides" sections. Any thoughts?

**Comment by chasenlehara** [comment]
I’m starting to think that we should move the migration/upgrade guide back under “commitment” and rename the API Guide page to something like “How to read the docs” so it’s more clear what to expect from that page.

**Comment by chasenlehara** [comment]
The [information architecture screenshot](https://cloud.githubusercontent.com/assets/5323173/25757411/8cfc2276-3187-11e7-81b1-c9166017b0ad.jpg) in [this comment](https://github.com/canjs/canjs/issues/2752#issuecomment-299529110) renames the group and this page’s title… but I’m really conflicted about it. I think the most useful place for this information would be in the API Docs hierarchy, but there’s no good place to put it unless we just put it on the API Docs page.

**Comment by imaustink** [comment]
I opened a [PR](https://github.com/canjs/canjs/pull/3315) that matches the mockup. Maybe we should have a quick discussion about other options first though?
