### ISSUE TITLE
De-emphasize the contribution guides

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2864]
When UX testers went through the [Guides](http://canjs.com/doc/guides.html) and got down to the “contribute” part, they were either confused by what it meant or didn’t find it relevant, which makes sense: a new user is generally not going to be interested in how to contribute to a project when they’re first learning about it.

I’m not sure how we should fix this, but one idea is to make “contribute” a main section and put it below Legacy.

**Comment by justinbmeyer** [comment]
Yes, new users won't find this relevant.  I don't think this is a good enough reason to move it.  The guides page contains all sorts of guides.
