### ISSUE TITLE
Remove the GitHub stars from the packages in the Collections list

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2872]
The GitHub stars next to each package are inspiring if there are a lot of watchers, but they remove credibility from the projects when the counts are low (like most of the individual modules).

This is less of a problem if we [move the Collections section off the home page](https://github.com/canjs/canjs/issues/2868) because then they won’t be as visible.

**Comment by gKreator** [comment]
I thought a similar thing with the low count, but how will you get the count higher if you don't display the buttons prominently?

**Comment by chasenlehara** [comment]
Two thoughts on that:
1. We could remove the count but leave the button (that was actually my original intent when I filed this issue).
2. If we [move that section off the homepage](https://github.com/canjs/canjs/issues/2868), I think the star count is not as big of a deal.

**Comment by gKreator** [comment]
Sounds good :)
