### ISSUE TITLE
in DefineMap, models are not removed from lists on destroy

### ISSUE THREAD

**Issue by perehnbom** [canjs/canjs#2878]
I’ve working on migrating an app from CanJS 2 to Canjs3. I would like to use DefineMap instead of can.Model, there’s a lot of good features in the new DefineMap, but have come across a couple of problems in the work:

I have a model which in turn has a list of other models as a property, e.g. a project contains a list of todo items.

```
var Project = can.DefineMap.extend({
  items : {
    Type : Item.List
  }
})
```

When calling destroy on one of the todo items, it is not removed from the list. Automatic removal on destroy works fine if I instantiate a Item.List directly through can-connect, but not if it’s part of the project model. The same problem applies when I instantiate an Item.List without using can-connect, but by using a constructor with json, e.g. new Item.List(json)

In can.Model, the removal of items relied on the change event bubbling up to the list, but there’s another mechanism used in DefineMap. I do miss the change event bubbling up, it was handy to use when e.g. implementing live bound sorting or other types of live updates on lists.

I have setup a jsbin which highlights the problem. 3 different lists are defined, and after a second, the first item in each list is destroyed. Only in one of the lists the item is removed from the list: http://jsbin.com/gagepa/edit?html,js,output

For a more comprehensive example, see https://github.com/perehnbom/tryout-canjs3

I wonder if there’s a simple way of achieving this. For now, this is a blocker for me in order to move to DefineMap from Model. The application I'm upgrading is https://www.agiloo.com, an app that relies heavily on live updates in models and model lists and fetches data both by ordinary ajax and by pushing out updates through socket.io.

**Comment by justinbmeyer** [comment]
This works for me in bitballs. You might have to set the ._listSet property on the list. I'll check it out Monday.

**Comment by perehnbom** [comment]
Thanks @justinbmeyer

**Comment by justinbmeyer** [comment]
[This JSBin](http://jsbin.com/salikiyulo/1/edit?html,js,output) shows the items in a list example working.  It does it by making sure that `.__listSet` is set on the list:

```
items : {
      set: function(items){
        if(items) {
          items.set("__listSet",{projectId: this.id})
        }
        return items;
      },
      Type : Item.List
    }
```

**Comment by justinbmeyer** [comment]
The JSBin I shared isn't perfect.  The set `{projectId: this.id}` won't accurately represent your set because items don't have a `projectId`.  The following will explain ....

In 3.0, adding and removing items is done with the [real-time](http://canjs.com/doc/can-connect/real-time/real-time.html) behavior.  

The real-time behavior adds and removes instances to/from lists using the the params used to retrieve a list.  For example, if you load items like:

```
Items.getList({projectId: 5});
```

By default, it's expected the server will respond back with item data like:

```js
{
  data: [{id: 55, name: "something", projectId: 5}]
}
```

This is so the following will pass:

```
algebra.has({projectId: 5}, {id: 55, name: "something", projectId: 5}) //-> true
```

Read more about this here: http://canjs.com/doc/can-set.html#SolvingCommonIssues

Let me know if that's enough to get you started.

**Comment by perehnbom** [comment]
Thanks, this solved the issue for me. In my real case scenario, each item does actually have a projectId. However, the json format is 

```
items : [{
   id : 1,
   projectId: 1
}]
```

and not 

```
items : {
   data : [{
      id : 1,
      projectId : 1
   }]
}
```

Changing to the 2nd format solved the problem without using
```
items.set("__listSet",{projectId: this.id})
```

**Comment by perehnbom** [comment]
I consider this solved, closing the issue.

**Comment by chasenlehara** [comment]
@justinbmeyer, are there docs for `__listSet` (or this general issue) anywhere?

**Comment by justinbmeyer** [comment]
In the base connection docs.

**Comment by Bajix** [comment]
Any reason not to use items.__listSet = projectId: this.id};

**Comment by justinbmeyer** [comment]
it's optional if it's not being observed.  In most cases, it's optional.

**Comment by matthewp** [comment]
We should make it be a function like `items.defineListSet(set)` or `items.listSet(set)` or something like that. Setting a double underscore property is an uncommon API.

**Comment by Bajix** [comment]
This really should have it's own API.

**Comment by Bajix** [comment]
This should really have it's own API. It would be really powerful to be able to take the serialized state of a component's viewModel, and update the list set accordingly within a getter or a stream, such that the end behavior allows you to have a UI that's decorated with search filters / sorting that can handle more complex real-time filters. Here's an example of the behavior above using 2.3.x:

**Comment by justinbmeyer** [comment]
@matthewp 

> We should make it be a function like items.defineListSet(set) or items.listSet(set) or something like that.

Making it a function wouldn't necessarily help.  It's double underscore because that's the default property name.  It can be whatever anyone wants.  


@Bajix Please elaborate on what you mean in a new issue with much less code to parse through.

**Comment by Bajix** [comment]
Sure

**Comment by matthewp** [comment]
Here's the docs: http://canjs.com/doc/can-connect/base/base.listSetProp.html
