### ISSUE TITLE
ES2015 used in the can-define/list/list docs

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/canjs#2897]
First of all i could not find the position here in the docs :) we should realy think about a extra docs repo that is so clean that any one could make changes :)

at: https://canjs.com/doc/can-define/list/list.html
```
Non-numeric properties can also be defined on custom DefineList type. The following defines a completed property that returns the completed todos:

var TodoList = DefineList.extend({
    "#": Todo,
    get completed(){
        return this.filter({complete: true})
    }
});

var todos = new TodoList([{complete: true}, {complete:false}]);
todos.completed.length //-> 1
```
there is a fail in the TodoList var it should be:

```
var TodoList = DefineList.extend({
    "#": Todo,
    get: function completed() {
        return this.filter({complete: true})
    }
});
```

I think or did you realy do this none javascript syntax?

**Comment by chasenlehara** [comment]
Hi @frank-dspeed, a few comments:
1. Each page has a “source” link that takes you to where you can see & edit the docs. I have an issue open for changing the link’s text to something more identifiable: https://github.com/canjs/bit-docs-html-canjs/issues/201
2. It looks like those links aren’t working correctly for `can-define/list/list`, so I’ve filed an issue for that: https://github.com/canjs/canjs/issues/2898
3. That example uses the new ES2015 syntax, so it’s not wrong, but I’ve opened an issue for only using ES5 in our docs to avoid confusion: https://github.com/canjs/canjs/issues/2884

**Comment by justinbmeyer** [comment]
@chasenlehara , it doesn't use 2015 syntax as far as I can tell.  It uses ES5 getters.  Closing, will re-open if I'm mistaken.

**Comment by chasenlehara** [comment]
Today I learned that those getters were included in ES5.1: http://www.ecma-international.org/ecma-262/5.1/#sec-11.1.5

**Comment by matthewp** [comment]
I don't think it's the responsibility of our docs to teach JavaScript features. We should be free to use any features that are supported. Maybe link to an MDN page when using a feature that users are unfamiliar with.
