### ISSUE TITLE
The “source” link on the can-define/list/list doc pages doesn’t work

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2898]
Steps to reproduce:
1. Go to the `can-define/list/list` docs: https://canjs.com/doc/can-define/list/list.html
2. Click the “source” link

Expected results: land on a page like this: https://github.com/canjs/can-define/blob/master/list/docs/define-list.md

Actual results: landed on this page: https://github.com/canjs/canjs/tree/v3.2.2/node_modules/can-define/list/docs/define-list.md

**Comment by justinbmeyer** [comment]
please move this to bit-docs-html-canjs

**Comment by chasenlehara** [comment]
Issue moved to [canjs/bit-docs-html-canjs #204](https://github.com/canjs/bit-docs-html-canjs/issues/204) via [**ZenHub**](https://www.zenhub.com/)
