### ISSUE TITLE
Improve the state diagram in the ATM Guide

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2901]
[This](https://github.com/canjs/canjs/blob/master/docs/can-guides/experiment/atm/1-pages-template/state-diagram.png) image in the [ATM Guide](http://canjs.com/doc/guides/atm.html#Mockoutswitchingbetweenpages) needs to be replaced with something that:

- [ ] Doesn’t have the red wiggly lines
- [ ] Is high-DPI

**Comment by justinbmeyer** [comment]
Those extra arrows are meaningful in state diagrams.

**Comment by chasenlehara** [comment]
Ok, I’ve removed that from the description.

I understand what the first “entry point” one means, but what do the ones near unverified, Picking Account, and Withdraw Info mean?

**Comment by justinbmeyer** [comment]
Those are the entry points for substates.  This is a special hierarchical form of state diagram.  

The one on `unverified` means that substate starts at `unverified`.  

For the other ones, it's trying to show that a "transaction" starts at `invalid` ... though the "ATM" starts at `picking account`.  The hierarchy is flipped upside down a bit there.  





The one at "invalid" means that a

**Comment by blazepollard** [comment]
Here is the newly updated graphic:
![flow](https://cloud.githubusercontent.com/assets/3195728/25756032/777ed916-3182-11e7-9b19-4514f027a00c.png)

**Comment by chasenlehara** [comment]
Thanks @blazepollard! If you want to, you can submit a PR that updates the image in this folder: https://github.com/canjs/canjs/tree/master/docs/can-guides/experiment/atm/1-pages-template

If someone needs to make changes in the future, where can they find the original file you worked on?

**Comment by blazepollard** [comment]
I've added the new image to this PR: 
https://github.com/canjs/canjs/pull/3203

I did the diagram in Axure, I've attached the PDF file here:
[flowchart_for_canjs.pdf](https://github.com/canjs/canjs/files/980164/flowchart_for_canjs.pdf)

Where would be a good location for this Axure file?

**Comment by chasenlehara** [comment]
Thanks @blazepollard!

@jamiemccue, could you please add Blaze’s Axure file to wherever you’re organizing the rest of the design resources?
