### ISSUE TITLE
Typo in the can-cid module description

### ISSUE THREAD

**Issue by marshallswain** [canjs/canjs#2917]
@marshallswain commented on [Mon Dec 19 2016](https://github.com/canjs/bit-docs-html-canjs/issues/207)

<img width="1366" alt="img_0704" src="https://cloud.githubusercontent.com/assets/128857/21337442/7e31e910-c62a-11e6-9935-5bc239054e02.PNG">

---

@justinbmeyer commented on [Mon Dec 19 2016](https://github.com/canjs/bit-docs-html-canjs/issues/207#issuecomment-268146958)

This is an issue for canjs/canjs.  This repo is for the theme/functionality of the canjs site.  Can you open an issue there and close this one?

**Comment by phillipskevin** [comment]
👍
