### ISSUE TITLE
bind multiple functions on ($click)

### ISSUE THREAD

**Issue by arti1793** [canjs/canjs#2918]

**Comment by marshallswain** [comment]
@arti1793 any suggestions on what would this look like in practice?

**Comment by matthewp** [comment]
FWIW you can't do this in JavaScript either: `anchor.onclick = fn;`.

**Comment by phillipskevin** [comment]
I think this is the discussion that prompted this issue: https://gitter.im/canjs/canjs?at=5858f4e80730ce6937e981e0

**Comment by phillipskevin** [comment]
I think something like `($click)="fn1(), fn2()"` is what @arti1793 is looking for.

**Comment by arti1793** [comment]
@phillipskevin you're absolutely right

**Comment by matthewp** [comment]
or `fn1(); fn2();` if the right hand side of an event binding is a Function body.

**Comment by justinbmeyer** [comment]
@arti1793 can you open this up here: https://github.com/canjs/can-stache-bindings

**Comment by arti1793** [comment]
Opened issue there https://github.com/canjs/can-stache-bindings/issues/115
