### ISSUE TITLE
Improve the Migration Guide’s structure

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2920]
Here are the current sections in the [Migration Guide](http://canjs.com/doc/migrate-3.html):

1. Minimal migration path
	- Use can/legacy
	- Set leakScope on Components
	- Asynchronous inserted/removed events
	- can.view is no more
	- Promises are needed
	- Passing the this value to a helper
	- No more global scope names
	- Using stache templates with Steal
2. Modernized migration path
	- Use can-* packages
	- Wrap elements in jQuery objects
	- Remove use of change events
3. Future-proof migration path
	- can-define replaces can-map
	- Use can-connect directly
	- Use the new binding syntax

Following the last step isn’t really “future-proofing” your application, some of the sections are a little out of place, and I want to [add a section about what you can do _before_ upgrading](https://github.com/canjs/canjs/issues/2460), so here’s a proposal for how the guide should be organized:

1. Pre-migration preparation
	- Use the module folders
	- Replace uses of `can.$`
	- Set `leakScope` on components
2. Minimal migration path
	- Use `can/legacy`
	- Use `can-jquery/legacy`
	- Asynchronous `inserted` and `removed` events
	- Replace uses of `can.view`
	- Use real Promises
	- Passing the `this` value to a helper
	- No more global scope names
	- Use `steal-stache` for templates
2. Modernized migration path
	- Use the new can-* packages
	- Move from `can-map` to `can-define`
		- Remove use of change events
	- Use `can-connect` directly
3. Avoid future deprecations and removals
	- Wrap elements in jQuery objects
	- Use the new binding syntax

Thoughts/ideas/feedback?

**Comment by justinbmeyer** [comment]
I still think we need to keep `use the new can-* packages` and `can-map -> can-define` in separate tasks. Perhaps:

- Pre-migration preparation
- Minimal migration path
- Modernized migration path
- Latest & greatest migration path 
- Avoid future deprecations and removals
