### ISSUE TITLE
can-operate proposal (in progress)

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2931]
## Summary

Provide common operators and hooks for those operators so different types like `DefineMap` can partake in those operations.

We will provide symbols that different objects within CanJS can opt into.

This should be able to replace `can-observation/reader`.

Related:

 - Formalize DefineMap - https://github.com/canjs/can-define/issues/63
 - can-observation/reader - https://github.com/canjs/can-observation/blob/master/reader/reader.js

## Operators 

- `get(obj, prop)`
- `peak(obj, prop)`
- `set(obj, prop)`
- `call( func, arg1, arg2 )`
- `apply( func, [args...] )`  
- `in(obj, Type)`
- `getPropertyNames( obj )`
- `getOwnPropertyNames( obj )`
- `hasOwnProperty( obj, prop )`
- `forEach( obj )`
- `getPrototypeOf`
- `getOwnPropertySymbols`

## Symbols

- `get`
- `peak`
- `set`
- `call`
- `apply`
- `ownPropertyKeys` - `in`, `getPropertyNames`, `getOwnPropertyNames`,  `hasOwnProperty`
- `iterator` - `forEach`
- `proto` - `getPrototypeOf`

## Mechanism

The symbols should change as little as possible.  We might want to put everything in its own module.  But at minimum, there might be a:

__can-symbol__

With all of the symbols above and a method used to assign them.

```js
var canSymbol = require("can-symbol");

var obj = {};

canSymbol.setSymbol( obj, canSymbol.get, function(obj, prop){ .... })
```

__can-operators__

Supplies the operators above:

```js
var operators = require("can-operators");
operators.get( obj, "prop" );
```

**Comment by matthewp** [comment]
Can you describe the problem a bit more? I know we have talked about this several times but an overview of the problem area makes it easier to evaluate the proposal.

**Comment by justinbmeyer** [comment]
@matthewp the problem is that something like `can-observation/reader` needs to know about every possible type (Map, DefineMap, compute, etc), so it knows to call `.attr`, `.get`, or `()`.  A similar problem exists in `can-route` and a few other places in CanJS.

This proposal would allow each type to define how basic operations should be performed on it.  This should result in more maintainable and flexible code.  Different types, like an observable `Set` can be added without changing anything else.  We'll also have some useful methods like `forEach` to offer people who want to similar flexibility.

**Comment by matthewp** [comment]
Would this be used by anything outside of can-view-scope?

**Comment by justinbmeyer** [comment]
@matthewp  `can-observation/reader` and `can-route` would benefit directly.  But in general, anything that has to interact with a `Type` would benefit.    A lot of code has been shifted to use `can-observation/reader` already.  But `can-observation/reader` is a terrible piece of code because it has to have implicit knowledge of every other type.  

Also, `can-observation/reader` is really designed for `can-stache` as it automatically "calls" functions (`foo`) if given something like `foo.bar`.  This would make a layer of functionality ignorant of an end goal like `can-stache`.

**Comment by justinbmeyer** [comment]
Another consideration ... What about types like `Promise` where we might want to read a `.value`, `.isRejected`, or `.reason` type virtual property uniformly across anything using `get(obj, prop)`

**Comment by justinbmeyer** [comment]
Related: https://github.com/canjs/can-util/issues/103

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-operate/issues/1
