### ISSUE TITLE
make-model-year example broken on old canjs site

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2939]
https://v2.canjs.com/docs/can.Map.prototype.define.html

has this demo:

https://v2.canjs.com/can/map/define/doc/examples/make-model-year.html

**Comment by nmasilva** [comment]
Hi Justin, 
Is the make-model-year migrated to the canjs 3 ?

Thanks,
Nuno Silva

**Comment by justinbmeyer** [comment]
It's at the bottom of http://canjs.com/doc/can-map-define.html

However, we need a DefineMap version.

**Comment by nmasilva** [comment]
Can't find the complete example source with the stache files and etc

I've added a post on the forum:
http://forums.donejs.com/t/canjs-3-change-select-box-data-source/604

**Comment by justinbmeyer** [comment]
Source for the demo is here: https://github.com/canjs/canjs/blob/master/demos/can-map-define/make-model-year.html
