### ISSUE TITLE
All V2 examples on the website are broken

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/canjs#2941]
Component examples:
https://v2.canjs.com/docs/can.Component.html

can.Control tab example:
https://v2.canjs.com/docs/can.Control.html

https://v2.canjs.com/docs/can.List.html
has:
https://v2.canjs.com/docs/can.List.plugins.promise.html

Related https://github.com/canjs/canjs/issues/2939

**Comment by pYr0x** [comment]
it's very simple. change the jsfiddle to `https://`

**Comment by cherifGsoul** [comment]
thank you @pYr0x :)

**Comment by chasenlehara** [comment]
The URLs just need to be changed to be [protocol relative](https://github.com/canjs/canjs/pull/2848/files); this would be an easy contribution if someone wants to take it.

**Comment by cherifGsoul** [comment]
@chasenlehara ok I take it

**Comment by phillipskevin** [comment]
JSFiddles are working again

![image](https://cloud.githubusercontent.com/assets/5851984/21860203/3849f73a-d7f5-11e6-8bc3-13e0393d82a1.png)
