### ISSUE TITLE
Docs dropdown points to older version of CanJS 2.3 ~1

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#2960]
The dropdown should point to the latest version (2.3.28), but it is showing 2.3.27:

![image](https://cloud.githubusercontent.com/assets/5851984/21856770/cc86c250-d7e8-11e6-9fd8-241a50049f4c.png)

**Comment by justinbmeyer** [comment]
This is fixed here: https://github.com/canjs/canjs/blob/master/package.json#L153
