### ISSUE TITLE
Demo on v2.canjs.com is broken

### ISSUE THREAD

**Issue by abalmus** [canjs/canjs#2965]
Most of the demos are broken. Example https://v2.canjs.com/docs/can.Map.prototype.define.html

**Comment by phillipskevin** [comment]
These are broken because some npm dependencies are missing:

![image](https://cloud.githubusercontent.com/assets/5851984/21897026/fe73c428-d8ad-11e6-8e61-4c1a6d2fdb88.png)

I think these need to be added back to https://github.com/canjs/canjs/blob/2.3-legacy/package.json#L25-L56.

**Comment by phillipskevin** [comment]
This should be fixed now. Please let us know if you still see any issues. Thanks for pointing out the issue @abalmus.
