### ISSUE TITLE
can.List cannot handle big arrays

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#2967]
```js
new can.List( new Array( 10000 ))
``` 
results in `Uncaught RangeError: Maximum call stack size exceeded`

The problem is that array -> List conversion internally ends up using `Function.prototype.apply` to forward the operation to `Array.prototype.push`.  Just like `call`, the `apply` method can only handle so many arguments and going over the limit results in the call stack size being exceeded because of all the arguments being pushed onto the call stack.

This could be resolved by internally splitting the operation into smaller, more managable chunks.
All the List methods that borrow from `Array.prototype` have this problem, actually.

**Comment by matthewp** [comment]
Going to move this to canjs/can-list.

**Comment by matthewp** [comment]
Issue moved to [canjs/can-list #26](https://github.com/canjs/can-list/issues/26) via [**ZenHub**](https://www.zenhub.com/)
