### ISSUE TITLE
can-semijs

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2971]
The following is a very rough idea of a template engine:

```
import helpers from "my-helpers";
import studentView from "student-view.semijs";

export default (viewModel) => {
<ul>
   for(let classRoom of viewModel.classRooms) {
     <li class=classRoom.type;>
       let teacher = classRoom.teacher;
       <p> Name: classRoom.name; </p>
       <p> Teacher: teacher.name; </p>
       <p> if( !teacher.hasKeys( classRoom ) ) { No keys } else { Keys } </p>
       <p> helpers.prettyDate( classRoom.startTime ); </p>
     </li>
   }
</ul>
};
```

Notes:

 - this uses `;` to signal the end of a `JS` expression.
 - it also uses `identifier( ... ) { ... }` to signal a `JS` expression.

Pros:

 - Even more like JS.
 - Uses only one ending identifier to signal an insert expression `;`.  I like this A LOT more than  `{ }` because JavaScript already uses `{}` so I've never thought `{}` was a good language switch "identifier".

Cons:

 - Much harder to make work without creating a lot more code. 
 - Might be impossible to parse.  We'd have to parse backwards from `;`.  How do you know if `let teacher = classRoom.teacher;` is `{#let teacher be classRoom.teacher}` or `let teacher be {classRoom.teacher}`.

**Comment by justinbmeyer** [comment]
The following is an example of a [bitballs template](https://github.com/donejs/bitballs/blob/master/public/components/game/details/details.stache) I updated: https://gist.github.com/justinbmeyer/cf19ed9789417f3c1f068707b45cc006

My concern with this is that `;` might not be enough of a visual indicator that something is going on.

**Comment by marshallswain** [comment]
Making functionality change based on the presence of `;` required will not feel JS-like, but I like the idea of it being something simple like that.

Why not use `${ expression }` from es6 strings?

**Comment by rjgotten** [comment]
If you want to use a simple one-token-only template language, why not look at how something like Microsoft's Razor syntax does it?

It's forward-parsable by heading code nuggets off with an `@` and then using the semantics of the language (C# or VB.NET in Microsoft's case) to determine where the expression closes and when the parser should return to HTML mode.

(It has some other features to it that you'd probably like as well, such as the possibility to declare re-usable snippits inline as `@helper` and placeholder-filling using `@section`. Seriously worth looking at for inspiration.)

**Comment by matthewp** [comment]
I think it's a bad idea to make a language look like another language but have different semantic meaning. This is the same reason I think our `<select multiple>` implementation is the wrong way to go. If something looks like something else but behaves differently you can't use existing knowledge to understand what you're looking at; anything could have been changed.

In this example there's a for loop that looks a little bit like a JavaScript for loop except here there is something like an implicit yield happening. In JavaScript for loops are for side effects and don't return as expression.

Also, it seems like this idea would require the language to constantly change as JavaScript itself changes, and that would be a difficult thing to keep up with.

**Comment by phillipskevin** [comment]
Why not a syntax that is JS instead of mostly JS? Something like elm-lang/html or cyclejs/dom where you call functions directly, passing an object with attributes for the element and an array of child elements.

```
import { ul, li, p, text } from "can-html";
import helpers from "my-helpers";
import studentView from "student-view";

export default (viewModel) => 
    ul({}, viewModel.classRooms.map((classroom) => 
        li({
            class: classRoom.type
        }, [
            p({}, [ text(`Name: ${classRoom.name}`) ]),
            p({}, [ text(`Teacher: ${classRoom.teach.name}`) ])
            p({}, [ text(!teacher.hasKeys( classRoom ) ? 'No keys' : 'Keys') ])
        ])
    ));
```

I understand this is less "designer-friendly", but making a syntax that is more like JS probably isn't targeting that audience.

**Comment by justinbmeyer** [comment]
@matthewp JS looks like Java.  Java looks like C.  If we couldn't re-use existing syntax, we'd run out of ways for expressing things very quickly.  `a.b` is a great way of accessing things.  `a()` is a great way of "running" something.  `{ CODE }` is a great way of indicating there's some block of code ( some languages do it with indention ).

> In JavaScript for loops are for side effects and don't return as expression.

There are many use cases for for loops that don't involve side effects ... unless you are counting the `iterator` variable as a side effect.  

> Also, it seems like this idea would require the language to constantly change as JavaScript itself changes, and that would be a difficult thing to keep up with.

This is what React had to do prior to babel.  They've shifted this to them.

**Comment by justinbmeyer** [comment]
> Why not a syntax that is JS instead of mostly JS?

This layer can still exist (as it does with react).  But it will be gross.

**Comment by phillipskevin** [comment]
> But it will be gross.

Can you explain what you mean?

**Comment by justinbmeyer** [comment]
@phillipskevin Creating bindings will involve making and passing computes around.  A two-way binding will need a special call.

**Comment by phillipskevin** [comment]
Yeah, there's not really a pretty solution to two-way binding that isn't extremely verbose.

How would two-way binding work in the semijs proposal?

**Comment by justinbmeyer** [comment]
@phillipskevin it could still look like `can-stache-bindings`, but probably had different rules around expressions.  For example `{prop}="method"` would need to be `{prop}="method()"`.

**Comment by justinbmeyer** [comment]
@phillipskevin ideally, data-bindings can operate somewhat independently from view-bindings.

**Comment by phillipskevin** [comment]
Ok, so using another component inside of a view function like this would look a lot like it does now:

```
export default (viewModel) => {
<ul>
   for(let classRoom of viewModel.classRooms) {
     <class-room
       {type}="classRoom.type"
       {(name)}="classRoom.name"
       {teacher}="teacher.name">
    </class-room>
   }
</ul>
};
```

I was thinking you were expecting to be able to call the `studentView` function directly, which would have the same sorts of problems with two-way binding that an "all-JS" solution would have I would think.

**Comment by rjgotten** [comment]
> @phillipskevin 
> Why not a syntax that is JS instead of mostly JS?

I'm going to turn that right back on you:
If you're going to eventually generate HTML, why not have syntax that is close to HTML instead of something that abuses nested callback functions, object literals and template strings?

Don't throw out the baby with the bathwater, please.
The reason intermixed JS-like constructs with HTML markup are such a desired feature is because they give you the best of both worlds: you get a good picture of what your output is going to look like, while you retain the privilege of having virtually all the fine-grained control you want ***when you need it***.

**Comment by phillipskevin** [comment]
> something that abuses nested callback functions, object literals and template strings

@rjgotten I'm not really sure what you mean. My "all-JS" proposal is really just calling functions that take an object and an array.

I understand the benefit of having something that looks like HTML but has _some_ features of JS, but I think there is also value in something that has _all_ of the features of JS but might not look as much like HTML.

**Comment by matthewp** [comment]
@rjgotten 

> The reason intermixed JS-like constructs with HTML markup are such a desired feature is because they give you the best of both worlds: you get a good picture of what your output is going to look like, while you retain the privilege of having virtually all the fine-grained control you want, when you need it. And you can forego that complexity when you don't.

I think you're mistaken here, this proposal *isn't JavaScript*, it's something that looks a bit like JavaScript but behaves in different ways in some cases (see my comment on for loops above) and supports some subset of features of JavaScript that have all been defined yet.

I agree with you about the advantages of something like JSX that is strictly a superset of JavaScript, but that's not what this proposal is.

**Comment by rjgotten** [comment]
> @phillipskevin
> I'm not really sure what you mean

Your proposal uses JS syntax to express HTML semantics, or to put it in other terms: you are using JS as a DSL for HTML generation.

> @matthewp 
> I think you're mistaken here, this proposal isn't JavaScript, it's something that looks a bit like JavaScript

Which is why I wrote JS-**like** constructs that give you **virtually** all the fine-grained control you'd want. JSX just pushes that idea to its logical extreme by intermixing *actual* JS with HTML markup.

**Comment by matthewp** [comment]
I think we'll have to wait and see what this proposal introduces before we judge how much control is given. So far we have some imports, an export and a for loop (but not like a JavaScript for loop).

**Comment by justinbmeyer** [comment]
To be clear about this proposal, it was only intended to spark a discussion.  Specifically, about what a react-like library with fewer magic tag delimiters might look like and how we might take the cutting edge a bit further.

@matthewp you are right about the `for` loop, though this still could be JavaScript if the context of where the loop is (within a tag expression) is taken into account. 

I really have no great ideas on what the future of `JS <=> DOM` interplay should look like.  Perhaps there shouldn't even be `JS <=> DOM` interplay.  


I'm going to close this issue as hopefully its spirit will live on.  __Lets get crazy__ and start brainstorming wild ideas.  If you are reading someone else's idea, adopt is spirit and try to figure out how to make it better.

**Comment by matthewp** [comment]
Good point, we should try to adopt the spirit of the proposal and improve upon it.  I think stuff like this is going to be difficult:

```js
if( !teacher.hasKeys( classRoom ) ) { No keys } else { Keys }
```

to differentiate between that as code and that as a string in the template. What if I wanted to write that as a string. Maybe use something like backticks?

```html
`if( !teacher.hasKeys( classRoom ) ) { No keys } else { Keys }`
```

**Comment by matthewp** [comment]
^^ Essentially this means that code gets precedence over html or text which I think is probably the right choice, you want to make writing code easier and make the exceptions (like writing text that looks like code) the exception that needs special syntax.

**Comment by justinbmeyer** [comment]
@matthewp as there are no semicolons, it "knows" `No Keys` and `Keys` have to be text.

**Comment by matthewp** [comment]
@justinbmeyer I'm talking about if I want to write the entire expression as text in the template. I literally want to show the user the code. I think you would need some special syntax because by default it wants to evaluate the `if()...` as code.

**Comment by justinbmeyer** [comment]
@matthewp you would `\{` your curlies.

**Comment by justinbmeyer** [comment]
I'm making the assumption that `{}` isn't super common in straight html.  Stache / dash / etc already make this assumption and expect you to escape it.

**Comment by rjgotten** [comment]
I'm going to suggest that for inspiration on inference of what is code vs what is text, you have, again, a look at what Microsoft did with their [Razor templating syntax](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor), because they solved that pretty well.

E.g. here's what Razor adapted to JS would look like when applied to the template @justinbmeyer had in this thread's opening post:

```html
<ul>
  @for( let classRoom of viewModel.classRooms ) {
    let teacher = classRoom.teacher;

    <li class="@classRoom.type">
      <p>Name: @classRoom.name</p>
      <p>Teacher: @teacher.name</p>
      <p>@if( teacher.hasKeys( classRoom )) { <text>No keys</text> } else { <text>Keys</text> }</p>
      <p>@helpers.prettyDate( classRoom.startTime )</p>
    </li>
  }
</ul>
```
Razor starts in markup context, at which point any leading `@` sign flips over to code context.
Inside a code context, any opening tag for an element flips back to markup context. Language semantics are used to determine when a tag-like string is actually a tag and when not. Roughly speaking that rule is "anywhere a statement can be started". 
To place output text directly inside a code block without a wrapping element, you have two options:

1. you can use a leading `@:` mark, which switches the line to markup context and switches back to code context on the next line; or
2. you wrap the text in a special `<text></text>` element, which outputs only its content and which switches back to code context after the element's closing tag.
_(This is what the example listed above uses.)_

**Comment by justinbmeyer** [comment]
@rjgotten I like it. Thanks for sharing.

**Comment by matthewp** [comment]
I like it to, that's a good way to visually see where a code section starts.
