### ISSUE TITLE
can v2.3 : regarding the examples in delegate page

### ISSUE THREAD

**Issue by aNoobFrevr** [canjs/canjs#2977]
In the page explaining delegates.
https://v2.canjs.com/docs/can.Map.delegate.html

The following topics 
 Listening on multiple properties and values
 Listening when properties are a particular value

have examples which do not use the keyword delegate. Is that the intended purpose?

I am new to canJs, so a bit confused.

**Comment by justinbmeyer** [comment]
`.bind` will call `.delegate` if passed three options.  

If you are starting to use CanJS, I'd encourage you to use 3.0.  It's faster, easier to use, better documented and more.

Also the delegate plugin was dropped in 3.0 because it's unnecessary in a fully MVVM programming model.
