### ISSUE TITLE
Component paginate demo is borken

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#2980]
http://canjs.com/doc/can-component.html  The paginate demo doesn't show the total number of pages momentarily.

**Comment by justinbmeyer** [comment]
easy fix is to not use `superMap` and instead use `baseMap`.  The right fix is to solve: https://github.com/canjs/can-connect/issues/129

**Comment by chasenlehara** [comment]
Two things I see that are broken:

- [ ] Demo tab doesn’t show the total number of pages
- [ ] HTML tab just shows `<div id="out"></div>`

<img width="360" alt="screen shot 2017-01-23 at 1 31 25 pm" src="https://cloud.githubusercontent.com/assets/10070176/22223548/4b12b634-e170-11e6-87dd-7612ee6e365d.png">

<img width="362" alt="screen shot 2017-01-23 at 1 31 31 pm" src="https://cloud.githubusercontent.com/assets/10070176/22223547/4b0cbf04-e170-11e6-9ed6-b04ab3f8f35d.png">

**Comment by imaustink** [comment]
@justinbmeyer Switching to `baseMap` doesn't fix the demo: https://github.com/canjs/canjs/compare/2980-fix-peginate-demo?expand=1

@chasenlehara looks like other demos on that page are showing that same HTML. What would you expect to be there? Seems like that's the only markup that isn't made in stache land.

**Comment by chasenlehara** [comment]
I _think_ the stache markup should be shown. According to the [@demo docs](https://documentjs.com/docs/documentjs.tags.demo.html), you can add `id="demo-html"` to the `script` element to show it.
