### ISSUE TITLE
RFP: Templating

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#2995]
This is a request for proposals related to improving templating within CanJS.

@justinbmeyer started the discussion a few weeks ago when he opened two issues: [can-semijs](https://github.com/canjs/canjs/issues/2971) and [can-stache 4.0](https://github.com/canjs/can-stache/issues/151). This was discussed in a [contributors meeting](http://forums.donejs.com/t/donejs-contributors-meeting-2017-01-20/537/8) (discussion starts at [~5:41](https://www.youtube.com/watch?v=Lv4B_uMt4nk&feature=youtu.be&t=5m41s)) a couple weeks ago.

To say that the core team’s goal is to “improve” templating is a little nebulous, but I think it’s safe to say that `can-stache` (in its current incarnation) is not the pinnacle of maintainable, performant, and usable templating. We can do better and we want your help.

The core team encourages you to brainstorm ideas for improvements to `can-stache` or a complete replacement. Like Justin has already done in the issues he opened, it is best to create a new issue in this repo or [can-stache](https://github.com/canjs/can-stache) to outline your proposal with:

- Its goals & use cases
- Details on how it might work
- Pros and cons compared to `can-stache` and other alternatives
- Unanswered questions that will warrant discussion

The core team will start discussing proposals as early as Friday, March 17, so to guarantee that your ideas will be considered, please submit them by ~~__Friday, March 10th__~~ ([update](#issuecomment-284449277)). We ~~may~~ will start discussion later than that, so “late” proposals ~~might~~ will still be considered, ~~but March 10th is the deadline we’re setting for now~~.

To submit a proposal, please leave a comment here with a link to the issue. We welcome proposals from anyone in the community, and we see this process as a way to brainstorm ideas, so please don’t be shy in sharing! These proposals are a starting point for our discussion, so we don’t expect one proposal to “win” and be selected without some changes. If you submit a proposal, we may invite you to join the contributors meetings to join the discussion.

As with other major changes to DoneJS, the core team will vote on a final decision. All members in good standing will have a vote. If you are not already a part of the core team, [consider joining us](https://donejs.com/About.html#section=section_Coreteam).

**Comment by chasenlehara** [comment]
The core team is quickly closing in on the [DoneJS 1.0 release](https://github.com/donejs/donejs/issues/703). Since that’s still our current focus this month, I’ve updated the RFP’s description to note that we are not requiring submissions by March 10. We will most likely set another date as we get closer to when we’ll start discussing this topic.

**Comment by leoj3n** [comment]
Here is some research I found pertinent, and my opinions included:

https://github.com/canjs/canjs/issues/3089

**Comment by christopherjbaker** [comment]
Bit of an extra feature, but could apply to any proposal. It might be worth trying to modularize the actual dom rendering component, in order that it can be swapped out for other renderers (native ios, native android, threejs/webgl, etc). I would think they could all use the same (or nearly the same) diffing (perhaps it might have some options set by the renderer?), and some sort of common API that they hook into (method calls, event system, etc).

**Comment by imaustink** [comment]
I've added a proposal here: #3197

**Comment by christopherjbaker** [comment]
added a (meta) proposal at #3248

**Comment by christopherjbaker** [comment]
added JSX proposal at #3252

**Comment by leoj3n** [comment]
Semi-related
https://github.com/jstransformers/jstransformer
https://www.npmjs.com/browse/keyword/jstransformer

**Comment by matthewp** [comment]
Can this be closed? I think we settled on incrementally improving stache and eventually doing JSX.
