### ISSUE TITLE
Release folder does not exist after v2.3.27

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#3009]
We should manually create a build for the `v2.3.28` tag and add it to the release folder on the gh-pages branch so that files like http://canjs.com/release/2.3.28/can.jquery.js will exist.

The Makefile is just copying over the release folder from the gh-pages branch before overwriting the gh-pages branch since we are no longer updating the releases folder, but people using 2.3.x will expect this to exist.

**Comment by chasenlehara** [comment]
Update the release folder is part of the docs for publishing a 2.3 release, so I’m going to close this issue.
