### ISSUE TITLE
Add info about using a Promise polyfill to Setting Up CanJS

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3019]
The [Setting Up CanJS](http://canjs.com/doc/guides/setup.html) guide doesn’t include anything about adding a Promise polyfill for older browsers (i.e. IE9).

Forum post where this came up as a question: http://forums.donejs.com/t/promise-undefined-canjs-ie/557

**Comment by rjgotten** [comment]
Did you also ever resolve the problem where said polyfill *must* write to the global scope by creating `window.Promise` vs. having a clean module import without polluting global scope?

Something like
```js
define( "can/promise", [], function() { return window.Promise; })
```

could implement the existing behavior and still be overruled by users that cannot risk polluting global scope. (Such as vendors of third party widget embeds.)

**Comment by matthewp** [comment]
Not yet. That would be a reasonable add to https://github.com/canjs/can-util/tree/master/js. Could then provide a nice error message if there isn't a window.Promise.
