### ISSUE TITLE
build is broken with can-connect-feathers

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#3020]
seems like steal is unable to load some of feather's modules.  The following is seen in `canjs/canjs`'s test/index.html page in latest chrome.

**Comment by kylegifford** [comment]
<img width="1182" alt="screenshot 2017-02-22 11 38 46" src="https://cloud.githubusercontent.com/assets/4341379/23224336/95689e98-f8f3-11e6-9855-e2cc26031ade.png">

**Comment by marshallswain** [comment]
I wiped out node_modules, pulled, `npm install`ed and got a different result. The tests stop at the point shown in this screenshot:

![screen shot 2017-02-22 at 11 10 40 am](https://cloud.githubusercontent.com/assets/128857/23225601/a78ee2b6-f8ef-11e6-8987-8d1c0d24a2fa.jpg)

**Comment by marshallswain** [comment]
Ah.  If I rerun the last test, then I get the same errors as @kylegifford:

![screen shot 2017-02-22 at 11 19 59 am](https://cloud.githubusercontent.com/assets/128857/23225916/e92335e6-f8f0-11e6-8c78-a90e6c2fdd8d.jpg)

**Comment by marshallswain** [comment]
I think this might be an npm bug.  After npm installs dependencies, here's the `npm ls debug` output:

```
can@3.4.1 /Users/marshall/Sites/canjs
├─┬ feathers@2.0.3  // Odd to me, considering the version it references compared to others.
│ ├── debug@2.6.1
│ └─┬ express@4.14.1
│   ├── debug@2.2.0
│   ├─┬ finalhandler@0.5.1
│   │ └── debug@2.2.0
│   └─┬ send@0.14.2
│     └── debug@2.2.0
├─┬ feathers-socketio@1.4.2
│ └─┬ socket.io@1.7.3
│   ├── debug@2.3.3
│   ├─┬ engine.io@1.8.3
│   │ └── debug@2.3.3
│   └─┬ socket.io-adapter@0.5.0
│     └── debug@2.3.3
├─┬ socket.io-client@1.7.3
│ ├── debug@2.3.3
│ ├─┬ engine.io-client@1.8.3
│ │ └── debug@2.3.3
│ └─┬ socket.io-parser@2.3.1
│   └── debug@2.2.0
├─┬ steal-tools@0.16.8
│ └─┬ chokidar@1.6.1
│   └─┬ fsevents@1.1.1
│     └─┬ node-pre-gyp@0.6.33
│       └─┬ tar-pack@3.3.0
│         └── debug@2.2.0
└─┬ testee@0.3.1
  ├─┬ miner@0.2.1
  │ └─┬ localtunnel@1.8.2
  │   └── debug@2.2.0
  └─┬ mocha@3.2.0
    └── debug@2.2.0
```

These are the packages from the error messages that Steal complains about.  I've listed the debug module version number referenced in each package.json.

```
feathers | debug@^2.1.1  // Lower than the others, but npm installed 2.6.1
feathers-authentication-client | debug@^2.2.0
feathers-authentication-popups | debug@^2.2.0
feathers-errors | debug@^2.2.0
feathers-hooks-common | debug@^2.2.0
feathers-rest | debug@^2.2.0
feathers-socket-commons | debug@^2.2.0
feathers-socketio | debug@^2.2.0
socket.io-client | debug@^2.3.3
```

After Yarn installs dependencies, the problem goes away.  Here's the `npm ls debug` output:

```
can@3.4.1 /Users/marshall/Sites/canjs
├─┬ can-connect-feathers@3.5.1
│ ├─┬ feathers-authentication-popups@0.1.2
│ │ └── debug@2.6.1
│ └─┬ feathers-errors@2.5.0
│   └── debug@2.6.1
├─┬ feathers@2.0.3
│ ├── debug@2.6.1
│ └─┬ express@4.14.1
│   ├── debug@2.2.0
│   ├─┬ finalhandler@0.5.1
│   │ └── debug@2.2.0
│   └─┬ send@0.14.2
│     └── debug@2.2.0
├─┬ feathers-authentication-client@0.1.8
│ └── debug@2.6.1
├─┬ feathers-hooks@1.7.1
│ └─┬ feathers-hooks-common@2.0.3
│   └── debug@2.6.1
├─┬ feathers-rest@1.6.0
│ └── debug@2.6.1
├─┬ feathers-socketio@1.4.2
│ ├── debug@2.6.1
│ └─┬ feathers-socket-commons@2.4.0
│   └── debug@2.6.1
├─┬ socket.io-client@1.7.3
│ ├── debug@2.3.3
│ └─┬ socket.io-parser@2.3.1
│   └── debug@2.2.0
├─┬ steal-tools@0.16.8
│ ├─┬ chokidar@1.6.1
│ │ └─┬ fsevents@1.1.1
│ │   └─┬ node-pre-gyp@0.6.33
│ │     └─┬ tar-pack@3.3.0
│ │       └── debug@2.2.0
│ └─┬ transpile@0.9.7
│   └─┬ babel-core@5.8.14
│     └── debug@2.6.1
└─┬ testee@0.3.1
  ├─┬ body-parser@1.16.1
  │ └── debug@2.6.1
  ├─┬ connect-injector@0.4.4
  │ └── debug@2.6.1
  ├── debug@2.6.1
  ├─┬ launchpad@0.5.4
  │ ├─┬ browserstack@1.5.0
  │ │ └─┬ https-proxy-agent@1.0.0
  │ │   └── debug@2.6.1
  │ ├── debug@2.6.1
  │ └─┬ restify@4.3.0
  │   └─┬ spdy@3.4.4
  │     ├── debug@2.6.1
  │     └─┬ spdy-transport@2.0.18
  │       └── debug@2.6.1
  ├─┬ miner@0.2.1
  │ └─┬ localtunnel@1.8.2
  │   └── debug@2.2.0
  ├─┬ mocha@3.2.0
  │ └── debug@2.2.0
  └─┬ testee-client@0.4.0
    └─┬ superagent@3.4.4
      └── debug@2.6.1
```

**Comment by marshallswain** [comment]
Steal can't find the `debug@2.6.1` module.  It's not in `loader.defined`
![screen shot 2017-02-22 at 12 21 12 pm](https://cloud.githubusercontent.com/assets/128857/23237249/c0a367d4-f919-11e6-89f9-1e8395dc9cf0.jpg)

Here are the debug modules in `loader.defined`:
![screen shot 2017-02-22 at 4 14 21 pm](https://cloud.githubusercontent.com/assets/128857/23237320/0d67563e-f91a-11e6-9b7b-15f464c2a3c4.jpg)

**Comment by marshallswain** [comment]
All tests pass when I install with yarn.

**Comment by justinbmeyer** [comment]
@marshallswain regardless of how `npm` installs things ... steal should be able to handle it. 

@marshallswain where are things "really" installed?

cc @matthewp

**Comment by marshallswain** [comment]
Hmm... `debug@2.6.1` is installed in the node_modules root.  Steal should probably know it's there.

**Comment by matthewp** [comment]
Based on this info it sounds like there are 3 versions of `debug` and we are loading one of them incorrectly. Very likely a steal bug.

What I would do as a next step is construct a test project when emulates what is happening here. Don't install the same modules, but instead create a fake directory structure like:

```
node_modules/
  debug@2.6.1
  package-a/
    debug@2.2.0
  package-b/
    debug@2.3.3
```

Or whatever the directory structure actual is. Then make it so that package-a requires debug and package-b requires debug... again whatever is happening in this example, do the same thing.

If you set it up the same way it is happening here, it *should* break. In which case there is a steal bug worth looking at.

**Comment by marshallswain** [comment]
I've created a demo project that mimics the problem, but Steal handles it fine.  I was able to get the tests to all pass by removing `"npmAlgorithm": "flat"` from the canjs package.json.  I installed all packages with `npm@3.10.3`, so I'm not sure why that worked.

**Comment by matthewp** [comment]
I can probably look at it on Monday if not resolved before then.

**Comment by marshallswain** [comment]
This problem went away this morning.  Several `npm installs` and it worked fine.  Now it's back.  I've created the `steal-bug` branch.  Just open `/test/index.html` to see the error, and no tests run.

**Comment by matthewp** [comment]
I'll try out the branch.

**Comment by marshallswain** [comment]
@matthewp found & fixed this in Steal and will create a test for the fix.

**Comment by matthewp** [comment]
I didn't fix it, just spot-checked it inside my node_modules. I will write a test + fix though.  Bug is here: https://github.com/stealjs/steal/issues/1075

**Comment by matthewp** [comment]
This is fixed in steal 1.2.8

**Comment by frank-dspeed** [comment]
@matthewp i think this can be closed so right?

**Comment by matthewp** [comment]
Yep, thanks.
