### ISSUE TITLE
can-hyperscript

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#3042]
This is a proposal for the [Templating RFP](https://github.com/canjs/canjs/issues/2995) to use [can-hyperscript](https://www.npmjs.com/package/can-hyperscript) for CanJS templating.

### Goals

The goal of can-hyperscript is to write templates entirely in JavaScript.

### How does it work

Take a look at the [README](https://www.npmjs.com/package/can-hyperscript), [source](https://github.com/phillipskevin/can-hyperscript), and give it a try.

### Benefits compared to can-stache

- no new syntax to learn
- composable - views can be broken into smaller functions that can be easily reused across components
- testable - small functions can be [tested easily](https://github.com/phillipskevin/can-hyperscript/blob/master/test/can-hyperscript_test.js#L94-L112)
- templates are easy to load (no `stache.from()`, `steal-stache`, `raw-loader` for webpack, etc)
- we don't have to write, evolve, and maintain a language

### Downsides compared to can-stache

- harder to turn static html into templates
- people are used to can-stache (although this might be a benefit over other alternatives)
- some people just won't like it because it's different from what they're used to

### Unanswered questions

- [binding between components](https://github.com/phillipskevin/can-hyperscript/issues/6)
- `.component` files
- [list performance](https://github.com/phillipskevin/can-hyperscript/issues/7)

**Comment by pYr0x** [comment]
hello kevin,

i find this syntax very strange.
you didnt got any code completion or syntax highlighting in your IDE.

this syntax is maybe good for short and simple HTML. but if you write complex HTML you really want code completion.

one good reason to use this syntax is: it is testable !

good job.. keep it up :)

**Comment by justinbmeyer** [comment]
Have you thought about how lists will work (diffing)?

**Comment by justinbmeyer** [comment]
It would also be nice to see how event and two way bindings would look. 

I wonder if Proxy could make it look nicer. It could save at least two characters:

h.li("content")

Btw, couldn't this be the compile target for other templates?

**Comment by justinbmeyer** [comment]
Would this be able to use can-view-target? can-view-target helps a lot with performance.

**Comment by justinbmeyer** [comment]
Because there is no "definition" of the template apart from the "execution" of the template, it might be harder to optimize. 

I wonder if the 'h' could be contextualized. That way, if you ran the same template twice, parts of it could be memoized similar to what can-view-target is doing.

**Comment by phillipskevin** [comment]
@pYr0x you get the same code completion and syntax highlighting you get with any other JavaScript. I don't really use code completion with html, so maybe I'm totally wrong, but isn't it mainly helpful for adding closing tags?

There is https://github.com/ohanhi/hyperscript-helpers that gives you helper functions like `div(...`, `span(...`, etc that you might like better. It should work out of the box with can-hyperscript.

**Comment by matthewp** [comment]
Also, Babel can compile JSX to any hyperscript-compatible implementation. This is how all of the non-React vdom libraries use JSX.

**Comment by phillipskevin** [comment]
I've taken a stab at handling lists by overwriting `.map` on any properties used in a hyperscript function. That way `can-view-live.list` will be used if you do something like this:


```
h('div', { },
  data.planets.map(planet =>
    h('p', {}, [ () => `Hello, ${planet}!` ])
  )
)
```

There are other ways that people could use lists that we would want to handle, but this might be the most common way and shows how it could be done.

**Comment by phillipskevin** [comment]
Closing in favor of https://github.com/canjs/canjs/issues/3569.
