### ISSUE TITLE
Broken source link in docs

### ISSUE THREAD

**Issue by ilyavf** [canjs/canjs#3060]
Here http://canjs.com/doc/can-define/list/list.html

broken `source` link: 404
https://github.com/canjs/canjs/tree/v3.4.1/node_modules/can-define/list/docs/define-list.md

**Comment by ilyavf** [comment]
Reference: https://github.com/canjs/canjs/issues/2892

**Comment by chasenlehara** [comment]
@ilyavf, I’m not sure what that issue you referenced has anything to do with this one. This issue is related to editing the docs for a module and that other one is for seeing the actual source code for the module. Could you clarify please?

**Comment by Rlin415** [comment]
This is the same as canjs/bit-docs-html-canjs#204
