### ISSUE TITLE
Suggestion: put Recipes under “experiment” on CanJS.com

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3101]
I think it’d make more sense if the Recipes link was next to the other guides. Additionally, I think it’d make more sense to put _Setting Up CanJS_ before all the other guides.

Current:
<img width="275" alt="screen shot 2017-03-15 at 7 21 54 pm" src="https://cloud.githubusercontent.com/assets/10070176/23979111/cb29dfca-09b4-11e7-892f-12626edfd141.png">

Suggested:
<img width="278" alt="screen shot 2017-03-15 at 7 22 43 pm" src="https://cloud.githubusercontent.com/assets/10070176/23979115/d0c8eade-09b4-11e7-8509-d6e262482a80.png">

**Comment by justinbmeyer** [comment]
I don't think setting up is what a person coming to canjs should do before the guides. The guides all use JSBin to avoid people having to setup anything. 

Setting up canjs correctly, with its many packages, shouldn't be a prerequisite for exploring it.

**Comment by chasenlehara** [comment]
Recipes is now a direct descendant of Guides:
<img width="308" alt="screen shot 2017-06-06 at 3 17 40 pm" src="https://user-images.githubusercontent.com/10070176/26854527-5e584b90-4acb-11e7-8685-6eded32689b8.png">
