### ISSUE TITLE
Migration Guide: Document that can-map no longer creates a custom can-list

### ISSUE THREAD

**Issue by ccummings** [canjs/canjs#3104]
In 2.3, creating a custom can.Map would also create a custom can.List whose static `Map` property was the custom Map. For example:

```js
const MyMap = can.Map.extend({
  myHelper() {
  }
});

//MyMap.List can now be used elsewhere
```

In 3.0 this was [removed](https://github.com/canjs/can-map/commit/30f4a5c492b8457f4591c94bc1114baa0fa7e2bd#diff-3c6b7cc7a9646438b0db634c5ffc7abdR112).

If the removal is permanent, it should be added to the migration guide.

**Comment by justinbmeyer** [comment]
This is arguably a bug. Can you create an issue in can-map?

**Comment by chasenlehara** [comment]
Issue moved to [canjs/can-map #34](https://github.com/canjs/can-map/issues/34) via [**ZenHub**](https://www.zenhub.com/)
