### ISSUE TITLE
Add: Repolinks to the docs 

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/canjs#3111]
https://canjs.com/doc/can-connect/can/super-map/super-map.html 

for example that link should have at top or in footer a link to the repo.

**Comment by chasenlehara** [comment]
Hey @frank-dspeed, thanks for the feedback. I don’t disagree that this would be helpful, I’m just curious why you would find this useful. 🙂

**Comment by frank-dspeed** [comment]
@chasenlehara because i often want to point to code parts when people have questions and i can find the repos more fast when i browse the docs and then show the related parts in the repos original code

**Comment by frank-dspeed** [comment]
@chasenlehara closing this as this is done feel free to reopen
