### ISSUE TITLE
Migration guide: calling new List with an object

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#3116]
In 2.3:
```
var l = new can.List({ foo: 'bar' });
console.log(l.serialize()); // [{ foo: "bar" }]
```

in 3.0:
```
var l = new can.List({ foo: 'bar' });
console.log(l.serialize()); // []
```

**Comment by justinbmeyer** [comment]
Is that a bug?  I'm not sure why 3.0 should differ from 2.3.

**Comment by phillipskevin** [comment]
I'm not sure. This doesn't seem like a documented API. `can.List` and `can-list` only show `new List([array])` and `new List(deferred)`. I'll look into the 2.3 code to see how this was working.

**Comment by phillipskevin** [comment]
Moved this to `can-util/js/make-array/make-array`.
