### ISSUE TITLE
Docs: Inconsistent parameter naming for domData.set

### ISSUE THREAD

**Issue by leoj3n** [canjs/canjs#3123]
On this canjs doc page:

https://canjs.com/doc/can-util/dom/data/data.set.html

Should it be:

`domData.set.call(el, key, value)` with `1. key {String}: the key to store the value under`

Or should it be:

`domData.set.call(el, name, value)` with `1. name {String}: the key to store the value under`

Notice the difference: **key** vs. **name**

**Comment by chasenlehara** [comment]
I would make it `name`: https://github.com/canjs/can-util/blob/3bd0e682e3e2d8edd340bb084a838a320ee67257/dom/data/data.js#L5
