### ISSUE TITLE
Migration Guide: beforeremove syntax is wrong

### ISSUE THREAD

**Issue by ccummings** [canjs/canjs#3126]
The migration guide has the syntax `beforeremove: function(){...}` which does not work. According to the [docs](http://canjs.com/doc/can-component/beforeremove.html) it should be `{element} beforeremove: function(){...}`

**Comment by morrme** [comment]
@chasenlehara Can I help with this?

**Comment by chasenlehara** [comment]
Hi @morrme! Yes, please feel free to submit a PR for it. I think all that needs to changed is the `beforeremove ` example in this file: https://github.com/canjs/canjs/blob/24c957194c034b778fdc45eaee042196b4b523dc/docs/can-guides/commitment/migrating_to_3.0.md

**Comment by morrme** [comment]
@chasenlehara Thanks! Should the quotes around "beforeremove" remain?

**Comment by chasenlehara** [comment]
Yup, I think it should change from `"beforeremove"` to `"{element} beforeremove"`
