### ISSUE TITLE
Make can.view not make an AJAX request when an id lookup fails

### ISSUE THREAD

**Issue by ccummings** [canjs/canjs#314]
There should be a way to tell can.view to stop if it doesn't find an element with the given id. 

Right now can.view will try first to lookup a template by id and fallback to making an AJAX request. https://github.com/bitovi/canjs/blob/master/view/view.js#L471

I have two ideas for solving this:

can.view takes an Object with an id or url key (it can also take a String which will do an id lookup then Ajax)

```js
can.view({id: 'tmpl'}) //-> id lookup, no Ajax request
can.view({url: 'mytmpl/tmpl.mustache'}) //-> Ajax request, no id lookup
can.view('tmpl') //-> id lookup then Ajax request
```

Another way to know is to assume a `#` at the beginning of the URL means id lookup only. We already assume as much in the [code](https://github.com/bitovi/canjs/blob/master/view/view.js#L486), but still fallback to an Ajax request. 

```js
can.view('#tmpl', {}) //-> id lookup only
can.view('tmpl', {}) //-> id lookup then Ajax request
```

**Comment by justinbmeyer** [comment]
I think this is sorta dead because of the ubiquity of using a loader for templates.  Closing unless there's a hero to do it.

**Comment by pYr0x** [comment]
@justinbmeyer does ccummings PR #918 not solve this issue?
