### ISSUE TITLE
Use bitovi/test-saucelabs

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#3159]
We should replace [this script](https://github.com/canjs/canjs/blob/master/test/test-sauce-labs.js) with https://github.com/bitovi/test-saucelabs.

**Comment by morrme** [comment]
@phillipskevin I am new to your codebase. What would need to be done to resolve this? Would references to the prior script need to be changed to a script in the repo you linked?

**Comment by matthewp** [comment]
[This repo](https://github.com/stealjs/steal/blob/09888580c9da088446527c4c44782f53656fcd8b/test/saucelabs.js) uses test-saucelabs, maybe use that as a guide.

**Comment by chasenlehara** [comment]
Another example of how to do it: https://github.com/canjs/can-util/pull/267/files

**Comment by morrme** [comment]
@chasenlehara thanks!

**Comment by phillipskevin** [comment]
@morrme I was planning to work on this today. Were you planning to work on it?

**Comment by morrme** [comment]
@phillipskevin  Yes, I'd been working on it offline and was stuck on something until @chasenlehara shared that other example. Sorry for the delay! I see you've taken care of it.

**Comment by phillipskevin** [comment]
Sorry @morrme, the canjs builds are blocked because of the saucelabs configuration we're using for Appium is no longer available, so this became higher priority. I look forward to your future contributions.

**Comment by morrme** [comment]
@phillipskevin totally understand. i definitely hope to be able to contribute again soon! i'm newish to github and it's really cool to support a local company here!
