### ISSUE TITLE
Model in a Model Exception

### ISSUE THREAD

**Issue by Nithanaroy** [canjs/canjs#3180]
I have a baseMap, `Report` which has another baseMap, `Event` as a property. `validate()` in `Report` model calls the `validate()` on `Event` model instance as well. 

When calling `reportInstance.validate()` in a component, an exception that the event model instance does not have a validate method is raised.

Complete example and how to reproduce the exception are shown at https://jsbin.com/dizacon/edit?js,output

**Comment by justinbmeyer** [comment]
@Nithanaroy thanks for reporting.  Anyway you can simplify this example?  Thanks!

**Comment by justinbmeyer** [comment]
Also, is this the error you are talking about:

<img width="792" alt="cursor_and_js_bin_-_collaborative_javascript_debugging" src="https://cloud.githubusercontent.com/assets/78602/26693088/929baf34-46c8-11e7-9f69-ab7cb525747a.png">


This seems different than what you are reporting.

**Comment by justinbmeyer** [comment]
Also, if I look at the JSBin, no other error is thrown.  Event as I click on the __Validate Report__ button:


<img width="524" alt="js_bin_-_collaborative_javascript_debugging" src="https://cloud.githubusercontent.com/assets/78602/26693152/c7002818-46c8-11e7-815d-831ebceb65d0.png">

Is it possible this error was fixed?

**Comment by justinbmeyer** [comment]
Btw:

```
Event.List = can.DefineList.extend({
  "Map": Event
});
```

should be:

```
Event.List = can.DefineList.extend({
  "#": Event
});
```

**Comment by justinbmeyer** [comment]
Also, using inserted in this way to get data for the view-model is an anti-pattern.  Use an async getter.

```
inserted: function () {
      const self = this;
      console.log("getting");
      Report.get({id: "1"}).then(function (report) {
        // console.log("Fetched report", report);
        self.viewModel.report = report;
      }).catch(function (err) {
        console.error("Error fetching report", err)
      });
    }
```

**Comment by justinbmeyer** [comment]
The request bug can be seen in a simplified form here: https://jsbin.com/zuwayakode/edit?html,js,output

I think this might be due to a problem with zones and fixture  cc @matthewp

**Comment by justinbmeyer** [comment]
It's not a problem with fixtures.  The problem is that fixtures and can-connect have slightly different expectations about urls. We should make:

```js
can.connect.baseMap({
  "Map": Report,
  "List": Report.List,
  "url": "/api/v1/report/{id}",
  "name": "Report"
});
```

work in can-connect.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-connect #298](https://github.com/canjs/can-connect/issues/298) via [**ZenHub**](https://www.zenhub.com/)
