### ISSUE TITLE
`DefineList[Model].map()` confusing behavior

### ISSUE THREAD

**Issue by Nithanaroy** [canjs/canjs#3181]
I have a `Report` model which has a list of `Event` models. Each of `Event` model instances has a `validate()` method which returns `true` or `false`.

When I execute `this.report.events.map(e => e.validate())` in a component's view model, shouldn't the result be an array of `true` or `false` values?

Am I missing anything on how `map()` behaves or is my Report model definition incorrect or something else?

Complete example here: https://jsbin.com/duyile/edit?html,js,console,output

**Comment by chasenlehara** [comment]
I think this is the same as https://github.com/canjs/can-define/issues/153. I think this is fixed in the latest version of `can-define` and the fix will be included in the next version of CanJS.

**Comment by justinbmeyer** [comment]
yes, this is a duplicate, closing.
