### ISSUE TITLE
list.map() doesn't properly handle context arg

### ISSUE THREAD

**Issue by dtomack** [canjs/canjs#3182]
In list.js, the `map()` method attempts to use a short-circuit evaluation of an OR to handle choosing between the context argument versus `this` to use in the call to the client callback function.  It erroneously uses a bit-wise OR instead of a logical OR to do this resulting a number being passed as the context.

See https://github.com/canjs/canjs/blob/2.3-legacy/list/list.js#L873
```javascript
	var mapped = callback.call( thisArg | self, item, index, self);
```

This problem appears to also be present in the[ `filter` method of List](https://github.com/canjs/canjs/blob/2.3-legacy/list/list.js#L862).

I don't see this addressed in the 3.5.x codebase either:

- `map`: https://github.com/canjs/can-list/blob/master/can-list.js#L941
- `filter`: https://github.com/canjs/can-list/blob/master/can-list.js#L930

**Comment by chasenlehara** [comment]
Thanks for filing this issue @dtomack! This seems like a pretty straightforward bug. Would you be able to submit a PR for it? Otherwise the team will probably take a look sometime next week.

**Comment by dtomack** [comment]
@chasenlehara Thanks for the feedback.  I've created a PR for the main branch of code.  What do I need to do to address this for 2.3? We currently are using the 2.3 code.  Thanks.

**Comment by chasenlehara** [comment]
Thanks @dtomack! You can branch off `2.3-legacy` and submit a PR; we’re happy to make a release once it’s merged in.

**Comment by dtomack** [comment]
@chasenlehara Thanks!  I've gone ahead and created a PR for 2.3-legacy.  What else do I need to do to shepherd this along? (Other than, obviously, correcting anything I get feedback about).

Thank you.

**Comment by chasenlehara** [comment]
Nothing else; I don’t want to take the risk of publishing a bad release at the end of the day, so I’m going to publish 2.3.31 in the morning. Thanks for your contributions!

**Comment by chasenlehara** [comment]
@dtomack CanJS 2.3.31 has been [released](https://github.com/canjs/canjs/releases/tag/v2.3.31) with this fix. We’ll get out a new release of `can-list` with this fix soon too. Thanks for your help!
