### ISSUE TITLE
can-route demo and documentation

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#3208]
the demos on 
- https://canjs.com/doc/can-stache.helpers.routeCurrent.html
- https://canjs.com/doc/can-stache.helpers.routeUrl.html
are not working.

i also suggest to improve a little bit the docs of can-route.
- on the demo on stache helpers we are using `:page` instead of `{page}` (also on https://donejs.com/Apis.html#pushstate-change , https://donejs.com/Apis.html#can-route)
- on the main site (https://canjs.com/doc/can-route.html)  there should be a small example (on the `data` section) how you can create an `AppState` and set it on the stache tempalte like 
```
const AppState = DefineMap.extend({
page: "string"
});
let appState = new AppState();
route.data = appState;
...
...
let renderer = stache("....")(appState);
route.ready();
```
... the same as https://donejs.com/Apis.html#can-route
- on https://donejs.com/place-my-order.html#create-routes `To learn more about routing visit the CanJS guide on Application State and Routing.` is pointing to canjs version 2

**Comment by imaustink** [comment]
[Fixed demos](https://github.com/canjs/canjs/pull/3249)
[Added AppState example](https://github.com/canjs/can-route/pull/74)
[Updated route slug syntax in docs](https://github.com/donejs/donejs/issues/942)
