### ISSUE TITLE
Can compile for versions > 2.3.27

### ISSUE THREAD

**Issue by ypanyukov** [canjs/canjs#3209]
http://v2.canjs.com/release/latest/can.jquery.js - contains 2.3.27
Current latest version in 2.3-legacy - 2.3.31

http://v2.canjs.com/release/2.3.27/can.jquery.js - exists as expected (200ok)

Don't exist (404 not found):
http://v2.canjs.com/release/2.3.28/can.jquery.js
http://v2.canjs.com/release/2.3.29/can.jquery.js
http://v2.canjs.com/release/2.3.30/can.jquery.js
http://v2.canjs.com/release/2.3.31/can.jquery.js

Problem. There is no way to use can compile for versions > 2.3.27 (2.3.28, 2.3.29, 2.3.30, 2.3.31)

**Comment by chasenlehara** [comment]
@ypanyukov Sorry about that, all of those release folders are there now.

**Comment by ypanyukov** [comment]
http://v2.canjs.com/release/2.3.30/can.jquery.js
http://v2.canjs.com/release/2.3.31/can.jquery.js

For last 2 url does not match library.

http://v2.canjs.com/release/2.3.30/can.jquery.js - 2.3.29
http://v2.canjs.com/release/2.3.31/can.jquery.js - 2.3.30

Please double check!

**Comment by chasenlehara** [comment]
Yeah, I saw that and manually checked to see if the code is correct for the version. It looks like just the numbers are wrong in the comments. I would have “fixed” it but then it would’ve been different from the actual release, so I left the files alone.

**Comment by ypanyukov** [comment]
+
