### ISSUE TITLE
Create package can-dom-events

### ISSUE THREAD

**Issue by andrejewski** [canjs/canjs#3210]
This issue is for splitting `can-util/dom/events` into its own package and custom events into their own packages. There is a [discussed proposal](https://gist.github.com/andrejewski/fe553535217b2f3894a19b18d62ef9be) for going about designing the package and its event ecosystem.

Feedback can be placed/tracked here.

# `can-dom-events`

This is the DOM events API.

The package modules are:

- `can-dom-events` which replaces `can-util/dom/events`
- `can-dom-events/event/make-custom` for standardizing custom events
- `can-dom-events/event/make-native` for standardizing native events
- `can-dom-events/event/make-compat` for compatibility with `can-util/dom/events`
- `can-dom-events/make-registry` for creating event registries

Topics:
1. Standalone events
	1. Package custom events
	2. Unified native events
2. Registered events
	1. Generic registries
	2. Global registry
3. Documentation story

## Standalone events
Allows events without the need for a registry. Example:

```js
import myCustomEvent from 'can-event-my'

const el // HTML element
const removeListener = myCustomEvent.addListener(el, () => {
	// called when the custom event triggers
})

removeListener() // removes the handler from the custom event
```

### Packaged events
Custom events that can be their own packages.
The prefix is `can-event-` such as in `can-event-radiochange`.
The `make-custom` module makes custom events:

```js
// my-event.js
const makeCustom = require('can-dom-events/event/make-custom')
module.exports = makeCustom('my-event', function addListener () {
	/* EventTarget as this */
	/* EventTarget.addEventListener() arguments as arguments */

	// add listener ...
	return function removeListener () {
		// remove listener ...
	}
})
```

To support `can-util/dom/events` overriding behavior, pass the result of
`make-custom` to `make-compat` which returns a compatibility layer which accepts
an `can-util/dom/events/events` object to override:

```js
// my-event-compat.js
const myEvent = require('./my-event')
const makeCompat = require('can-dom-events/event/make-compat')
module.exports = makeCompat(myEvent)
```

```js
// my-old-can-util-app.js
const domEvents = require('can-util/dom/events/events')
const myEvent = require('./my-event-compat')
const removeEvent = myEvent.override(domEvents)

removeEvent() // un-does the overriding
```

### Unified events
For consistency, native events can adapt to the subscription-disposal pattern.
This utility lives in the `can-dom-events/event/make-native` module.

```js
// can-dom-events/event/make-native.js
const makeCustom = require('./make-native')
module.exports = function makeNativeEvent (eventName) {
	return makeCustom(eventName, function addListener () {
		this.addEventListener.apply(this, arguments)
		return () => {
			this.removeListener.apply(this, arguments)
		}
	})
}
```

```js
const makeNative = require('can-dom-events/event/make-native')
const clickEvent = makeNative('click')
const cleanupClick = clickEvent.addListener(el, () => {
	// called when the click event triggers
})

cleanupClick() // removes the handler from the click event
```

The main `can-dom-events` module calls `make-native` for unknown events when
called with `addListener`, returning a disposal function as custom events do.

## Registered events
Registries group custom events.

### Generic registries
The `can-dom-events/make-registry` module creates registries.

```js
// my-registry.js
const makeRegistry = require('can-dom-events/make-registry')

/*
	NOTE: implementors decide where to store registry data
	Some possible implementations: inside of a DefineMap prop, DOM data, or global map
*/
const sharedStorage = {}
const storageSolution = {
	get (eventName) {
		return sharedStorage[eventName]
	},
	set (eventName, event) {
		sharedStorage[eventName] = event
	},
	remove (eventName) {
		delete sharedStorage[eventName]
	}
}

module.exports = makeRegistry(storageSolution)
```

```js
// can-dom-events/make-registry.js
module.exports = function makeRegistry (storage) {
	return {
		addEvent (eventName, customEvent) {
			const self = this
			eventName = eventName || customEvent.defaultEventName
			const existingEvent = storage.get(eventName)
			if (existingEvent) {
				// throw error; no duplicate events allowed
			}
			storage.set(eventName, customEvent)
			return function removeEvent () {
				storage.remove(eventName)
			}
		},
		addEventListener (eventName) {
			const customEvent = storage.get(eventName)
			if (customEvent) {
				return customEvent.addListener.apply(this, arguments)
			}
		}
	}
}
```

Adding events to a registry:
```js
import myCustomEvent from 'can-event-my'
import myRegistry from './my-event-registry'

const removeEvent = myRegistry.addEvent('my-event', myCustomEvent)

const removeListener = myRegistry.addEventListener.call(el, 'my-event', () => {
	// called when the my-event triggers
})

removeListener() // remove listener from event
removeEvent() // remove custom event from registry
```

### Global registry
The custom event `.addGlobally()` method will add an event to the global registry.

```js
const removeGlobally = require('can-event-my').addGlobally()
// ^ add custom event to global registry

removeGlobally() // remove custom event from global registry
```

The global registry used by the core `can-dom-events` module is not exposed.

## Documentation story
End users of `can-dom-events` use `can-dom-events` directly along with the
custom events they choose to use.
All other packages are for implementors.
The `make-registry` module is for `can-component` and other packages which want
to support scoped events.
The `event/make-{custom|native|compat}` modules are for custom event package
authors to extend. This will give us much greater flexibility in the future to
make sweeping interface changes to all event types at once as they all extend
from a common base.

The `can-util/dom/events` split into packages, get marked as deprecated in util,
and get removed in can-util's 4.0. The breaking up of packages can happen in
pieces thanks to the `can-dom-events/event/make-compat` layer.

**Comment by justinbmeyer** [comment]
A few thoughts:

### Do we need the events folder?

### Can you explicitly document the typedef/apis?

For example, what exactly does `makeCustom` export?

__Exports:__

- _function(eventName, addListener)_

  _params_

  - __eventName__
  - __addListener(this:target, ...arguments)->removeListener()__

    - _this_ - the target the event should be registered upon.
    - _arguments_ - the arguments forwarded
    - _returns_ `removeListener()` which cleans up 
 
 _returns_ An object with the following methods / properties:

    - _addListener(target, handler)->removeListener()_
  
### What does `makeCompat` return?

An object with a `addEventListener`, `removeEventListener`?

Currently, `can-util/dom/events` is mutated in place.  

### Does `myEvent.override` mutate its argument?

If it does, are there concerns with calling `removeEvent` out of order? (I don't think so, but don't want to think hard right now).

### Are there better names for `override`? `mixin`, `addTo`, etc.

### Should `makeNative` be memoized?

### Should we use a constructor for `makeRegistry`?

### Why different storage solutions?  

I bet we don't need this, so we can simply make `makeRegistry` not take a solution and expand to another argument if needed.  

### Should we distinguish between DOM events and `can-event`?

`can-dom-event-radiochange`?

**Comment by andrejewski** [comment]
**Do we need the events folder?**

No, this is a bike shed.

**Can you explicitly document the typedef/apis?**

- **`makeCustom()`**
  - parameters
    - `defaultEventName: string` default name of the event
    - `addEventListener: function`
      - `this: EventTarget` the target to register the event on
      - `eventName: string` the name of the event to register on
      - `handler: function` the handler to call when the event is triggered
      - `bubble: boolean` *optional* whether the event should bubble
      - `useCapture: boolean` *optional* whether the event should capture
  - returns an object containing:
      - `addGlobally(): disposalFn`
        - returns the `removeGlobally()` disposal function
      - `addListener(el: HTMLElement, handler: function[, bubble: boolean][, useCapture: boolean]): disposalFn`
        - parameters
          - `el: EventTarget` the target to register the event on
          - `handler: function` the handler to call when the event is triggered
          - `bubble: boolean` *optional* whether the event should bubble
          - `useCapture: boolean` *optional* whether the event should capture
        - returns the `removeListener()` disposal function

- **`makeNative()`**
  - parameters
    - `eventName: string` default name of the event
  - returns an object containing:
      - `addGlobally(): disposalFn`
        - returns the `removeGlobally()` disposal function
      - `addListener(el: HTMLElement, handler: function[, bubble: boolean][, useCapture: boolean]): disposalFn`
        - parameters
          - `el: EventTarget` the target to register the event on
          - `handler: function` the handler to call when the event is triggered
          - `bubble: boolean` *optional* whether the event should bubble
          - `useCapture: boolean` *optional* whether the event should capture
        - returns the `removeListener()` disposal function

- **`makeCompat()`**
  - parameters
    - `domEvent CustomEvent|NativeEvent` the event created via `makeCustom` or `makeNative` to use in the returned `override` method
  - returns an object containing:
    - `override(domEvents: object): disposalFn`
      - returns the `removeOverride()` disposal function

- **`makeRegistry()`**
  - parameters
    - none, below we agreed to not allow custom storage solutions for now
  - returns an object containing:
    - `addEvent([eventName: string,] event: CustomEvent)`
      - parameters
        - `eventName: string` *optional* custom name for custom event, otherwise `makeCustom`'s `defaultEventName` is registered
        - `event: CustomEvent` event created via `makeCustom()`
      - returns the `removeEvent()` disposal function
    - `addEventListener: function`
      - parameters
        - `this: EventTarget` the target to register the event on
        - `eventName: string` the name of the event to register on
        - `handler: function` the handler to call when the event is triggered
        - `bubble: boolean` *optional* whether the event should bubble
        - `useCapture: boolean` *optional* whether the event should capture
      - returns the `removeEventListener()` disposal function

**What does makeCompat return?**

See previous snippets.

**Does myEvent.override mutate its argument?**

Yes, `override` was chosen to reflect how the implementation works. Removal out of order is accounted for, see [can-event-radiochange](https://github.com/canjs/can-event-radiochange/blob/1597e4b189a157da13803c3214ea4fec99806209/src/override.js#L39) for how it will be handled. There could also be a development mode warning for mis-ordered removals.

**Are there better names for override? mixin, addTo, etc.**

The word `override` sounds bad, which is what I want to convey about using the old API. Also the implementation matches the name.

**Should makeNative be memoized?**

There is no reason why it could not be.

**Should we use a constructor for makeRegistry?**

No, I don't want to encourage mucking around with it. Under the hood sure, but not as a part of the interface. Heck, let's freeze these puppies.

**Why different storage solutions?**

> expand to another argument if needed.

As in add the `storage` argument in the future? If so, yes that's fine.

**Should we distinguish between DOM events and can-event?**

Absolutely. The `can-event-radiochange` package can be renamed.

**Does these custom events need to be identify-able?**

I don't know what this means. If you mean to say should be create a `can-symbol` symbol to identify and differentiate event types in something like `can-import` statements, we can. The interfaces are minimally defined so we can make these changes in the future as well.

**Comment by matthewp** [comment]
I think distinguishing between can-event events and DOM events is a bit overkill. There have been no custom can-event events created yet.

**Comment by andrejewski** [comment]
**Appended: Consistent APIs across projects**

- Conform registry types with `can-view-callbacks`
- Conforming interfaces with `can-event`

There could be some overlap amongst event, attribute, and tag registry systems. `can-dom-events` may also should align with `can-event`. Below are my thoughts on these.

**Conform registry types with `can-view-callbacks`**

Looking at [`can-view-callbacks`](https://canjs.com/doc/can-view-callbacks.html) there definitely some things we can do to make things more consistent, especially when aligning design goals. There are a few things to align:

- use the subscribe-disposal pattern for add/remove
- rename `tag()` and `attr()` to `addTagEffect()` and `addAttributeEffect()`

There is not much else to align, multiple registries don't make sense in the current implementation of `can-view-callbacks`. The only way multiple registries makes sense to be is a component-level registry which child nodes fire up to in the render tree. To accomplish that, we'd need

- `TagEffectRegistry/.add()` and `AttributeEffectRegistry/.add()`
- or, `EffectRegistry/(.addTag/.addAttribute)`, making `can-view-callbacks` the global effect registry
- and a `dispatch(el)` method for all callback registries

The wildcard style regex filter used in `callbacks.attr()` is not something that can be brought to `can-dom-events` because we cannot listen on *all* events ahead of time because of the way DOM events work.

Aside: In the `tag` and `attr` calls, the string equality and regex filter are doing the same thing: filtering DOM nodes. So in `can-view-callbacks` we can "lift" those to accept a predicate function and specialize when a string or regex is passed instead.

**Conforming interfaces with `can-event`**

This depends on how congruent we'd like to get. Maximally, the `addEventListener()` and `dispatch()` (rename to `dispatchEvent`) are the only two methods needed. Using the subscribe-disposal pattern the `remove` methods are eliminated. There are also a number of aliases for doing that same thing that can be removed. I don't know how `un/delegate` are used so I'd drop those. The `listenTo/stopListening` methods don't make sense in the age of `bind` and with arrow functions even less, so drop. 

That leaves the shorthand `one`, which is much easier to de-sugar with the disposal function, so much easier that I'd remove it. Here's an before/after for `one`:

```js
canEvents.one.call(obj, 'foo', function () {
  // do something once
})
```

```js
var removeListener = canEvents.addEventListener.call(obj, 'foo', function () {
  removeListener()
  // do something once
})
```

Also, currently `can-event` maps calls to `can-util/domEvents` if the object is an EventTarget, which I don't think is a good decision because if miscalled, DOM events could propagate unexpected events which don't have to be proper Event objects into the DOM event system. Better to isolate the two use cases so one is not coupled to the other.

The result of these changes is that `can-dom-events` and the `can-events` mixin both use the disposal-pattern and expose only two methods `addEventListener()` and `dispatchEvent()`.

---

Note: nothing here changes the `can-dom-events` API, but clarifies how we can better rework the ecosystem to align with its usage.

**Comment by andrejewski** [comment]
[`can-dom-events`](https://github.com/canjs/can-dom-events) went 1.0.0 yesterday, closing.
