### ISSUE TITLE
Guides: YouTube Playlist Guide need a stopPropogation for the thumbnail

### ISSUE THREAD

**Issue by Sinjhin** [canjs/canjs#3244]
Dragging the thumbnail image rather than the `<li>` causes the video to drag without the data methods attached to dragging the li.

![playlist-error](https://cloud.githubusercontent.com/assets/1085104/25978439/b18c7dca-3687-11e7-840a-4f9e9fa561a1.gif)

**Comment by justinbmeyer** [comment]
I think it needs preventDefault()

**Comment by justinbmeyer** [comment]
I'll do this once we can have `videoDrag` use a helper.

**Comment by Sinjhin** [comment]
This is fixed with #3439
