### ISSUE TITLE
Make the About page more compelling

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3253]
The [About page](https://canjs.com/doc/about.html) is one of the first pages people might visit after the home page, but it’s not very engaging.

Maybe we should add the same hare/tortoise image to that page? Or have big buttons for the sub-pages, similar to what we’re adding under [Getting started on the home page](https://github.com/canjs/canjs/issues/2752#issuecomment-299529110)?

**Comment by jamiemccue** [comment]
- update favicon
- H1 color darker
- add images to about page
- change logo to blue
- discuss canjs style guide

**Comment by chasenlehara** [comment]
https://github.com/canjs/canjs/pull/3254
