### ISSUE TITLE
Control + Components

### ISSUE THREAD

**Issue by paul321** [canjs/canjs#3255]
Hi,

Is there any way to pass values from a component into a controller that instantiated that component? Lets say i have a can Control on an element and inside is a component that represents a dropdown and i want to pass it's values from the scope to the parent control in order to update the UI.

Is that possible?

Thanks

**Comment by justinbmeyer** [comment]
Yes. How is your control creating the component? Via a template? If so, you can either use to-parent bindings {^} or get the view model of the component with can-view-bindings

**Comment by paul321** [comment]
Yes my control is creating the component via template, so we have a control like this one 

define([
    'can',
], function(can) {
    return can.Control.extend({
        defaults: new can.Map({
        })
    }, {
        init: function() {
        },

        'button click':function(el, ev) {
            //need to access the component scope here
        }
    });
});

and we need to access the component values in the button click function. Maybe you can give us some hints?

Thanks

**Comment by mickmcgrath13** [comment]
Here's an example using `can.viewModel`: http://jsbin.com/heruzil/1/edit?html,js,output

Here's an example using stache's binding syntax: http://jsbin.com/mosatad/1/edit?html,js,output

An important thing to note is that the `defaults` property of a can.Control's static props must be a plain object.  If it is a `can.Map` instance, it will be converted into a plain object anyway.  In the second example I gave, the map instance was moved to a property on `defaults` called `componentScope` following the pattern described [here](https://canjs.com/doc/can-control.defaults.html#SharedProperties).

**Comment by paul321** [comment]
In the first example, we might have more components with the same tag in the same file which might be the problem, we are using mustache files to load the templates we do not use templates defined within a script tag

**Comment by mickmcgrath13** [comment]
Are you referring to this line?
```js
    var componentVm = can.viewModel(this.element.getElementsByTagName("demo-component")[0]),
```

If so, can.viewModel just takes an element, so you can get your component in whatever way is appropriate for your project.  For example, you can use jQuery and a classname:
```js
var someSpecificComponentElement = $(this.element).find(".some-specific-component-classname")[0],
      componentVm = can.viewModel(someSpecificComponentElement);
```

Please let me know if this isn't what you mean.

I will say, though, that it might be a better approach to use the second example as it is more state-based and requires less manual interaction with the DOM.

**Comment by paul321** [comment]
I don't really understand the following lines

`    var componentRenderer = can.stache.from("demo-control-template");
    
    //give the renderer a scope for stache to bind to
    this.element.appendChild(
      componentRenderer(this.options.componentScope)
    );
`

Can we use the component like this?

```
  <div id="control-el">
    <demo-component {^component-prop}="controlProp" />

    <button>Click Me</button>
  </div>
```

**Comment by paul321** [comment]
Ok i've got it working in our app, thank you we use the second example because it's better.

Another question if i have an attribute in this.options called dropdown can i have a method in the controller so we can observe if a property is changed or updated by a component?

```
'{dropdown} change': function() {
}
```

**Comment by mickmcgrath13** [comment]
Sure!
Assuming you've got a can.Map defined in your control's options like:
```js
var DemoControl = can.Control.extend({
  defaults: {
    componentScope: new can.Map({
      dropdown: "some-value-for-the-dropdown"
    });
  }
}, {
/* ... */
}
```
..and your Stache template is child-to-parent (or two-way) binding that property like:
```
<your-component {^dropdown-property}="dropdown" />
```

..then you can listen to the dropdown property change in your control like this:
```js
  "{componentScope} dropdown": function(componentScope, event, newVal, oldVal){
    console.log("componentScope's dropdown property changed", arguments);
  }
```
_(you can think of `"{componentScope} dropdown"` in this case as similar to `this.options.componentScop.attr("dropdown").bind("change", function(){})`_


If you're wanting to 'listen' for when an item is added to or removed from a list, you can do that like this:
```js
  "{componentScope.controlAr} add": function(vm, newVal, oldVal){
    console.log("something added to the controlAr property", arguments);
  }
```

Here is an example: http://jsbin.com/natowod/1/edit?html,js,output

**Comment by paul321** [comment]
Thanks a lot Mick for the help 👍

**Comment by mickmcgrath13** [comment]
NP!

**Comment by mickmcgrath13** [comment]
Is this issue resolved, then?

**Comment by paul321** [comment]
if i have this case:
`
var DemoControl = can.Control.extend({
  defaults: {
    componentValue: 1;
  }
}, {
/* ... */
}`

Can i listen to changes on componentValue in my control?

**Comment by mickmcgrath13** [comment]
The property you want to listen to would need to either be [a compute](https://canjs.com/doc/can-compute.html#Use) or nested within a can.Map [like this](https://github.com/canjs/canjs/issues/3255#issuecomment-301880954).

**Comment by paul321** [comment]
Yes, but i don't want to create another can.Map in the options, i'll use this.options.on(....
I'm closing this one
