### ISSUE TITLE
Links not working in the Simple File Navigator Guide on SSL

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3259]
Steps to reproduce:

1. Go to https://canjs.com/doc/guides/recipes/file-navigator-simple.html#Rendertherootfolderanditscontents
2. Click on the [can-stache.from](http://canjs.com/doc/can-stache.from.html) link on the page

Expected results: you’re taken to that page

Actual results: error in the console because it’s a `http` url: `Failed to execute 'pushState' on 'History'`

**Comment by mickmcgrath13** [comment]
those urls are hard-coded as `http` in the .md file: https://github.com/canjs/canjs/blob/master/docs/can-guides/commitment/recipes/file-navigator-simple.md#what-you-need-to-know

All links that point to canjs.com:

...should be changed from this format:
```
[can-stache](http://canjs.com/doc/can-stache.html)
```

to this format:
```
[can-stache]
```

**Comment by mickmcgrath13** [comment]
it's not clear to me how to convert this
```
[CanJS documentation](http://canjs.com/)
```

into a non protocol-specified version.

**Comment by mickmcgrath13** [comment]
Also not sure about this one:
```
[Array shorthand](http://canjs.com/doc/can-define.types.propDefinition.html#Array)
```

(the #Array part)

**Comment by chasenlehara** [comment]
I’m not sure what the syntax should be for linking to the root of the site. I would just change that link to be `https`.

I don’t think we need to immediately deploy a new version of the site to fix this issue (because they work on `http` and we’re not forwarding to `https` right now), so I think it’s ok to wait until `bit-docs-html-canjs` is fixed.

**Comment by mickmcgrath13** [comment]
Here's a branch: https://github.com/canjs/canjs/tree/3259-hardcoded-http-links

still need to change our outgoing links to https, too
* funcunit.com
* stealjs.com
* bitovi.com
* etc

**Comment by justinbmeyer** [comment]
> [CanJS documentation](http://canjs.com/)

Should probably be:

`[CanJS CanJS documentation]`.

**Comment by justinbmeyer** [comment]
> [Array shorthand](http://canjs.com/doc/can-define.types.propDefinition.html#Array)

You could always use relative paths or `//`.  Better yet, would be to make:

```
[can-define.types.propDefinition#Array Array shorthand]
```

work.  This could be done here: https://github.com/bit-docs/bit-docs-generate-html/blob/master/build/make_default_helpers.js#L268 ... just make sure the regexps allow it, pull off the hash and add it back later.

**Comment by mickmcgrath13** [comment]
Hash syntax support for bit-docs links
* [Issue](https://github.com/bit-docs/bit-docs-generate-html/issues/27)
* [PR](https://github.com/bit-docs/bit-docs-generate-html/pull/34)

Only pushState to same protocol
* [Issue](https://github.com/canjs/bit-docs-html-canjs/issues/240)
* [PR](https://github.com/canjs/bit-docs-html-canjs/pull/241)

This issue (https links not working)
* [Issue](https://github.com/canjs/canjs/issues/3259)
* [PR](https://github.com/canjs/canjs/pull/3260)
