### ISSUE TITLE
Organize design resources

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3270]
Right now under the [Guides](https://canjs.com/doc/guides.html) page of CanJS.com, there’s a “contribute” section with docs for contributing to the project, such as [Code](https://canjs.com/doc/guides/contributing/code.html). This issue is for creating a new Design page that will have all the info a designer needs to start working on design issues for the website: links to prototypes, tools, etc. The goal is to have everything on there that would make it easy for a Bitovi designer unfamiliar with the project to start contributing.

**Comment by tomgreever** [comment]
Hey @chasenlehara I'm not aware of any resources we could provide that would solve for this. You mentioned prototypes. We don't have a master prototype for CanJS. (Maybe we should? But what would it include?) Usually, we prototype one thing per issue and then those get closed with the ticket. What tools did you have in mind? And is this for a Bitovi designer? Or any designer, including someone outside Bitovi who wants to contribute?

Usually, the best thing to help someone get up-to-speed on a project like this is a style guide showing all the UI elements, the CSS and HTML needed. You know, the whole DocCSS thing.

Outside of that, I can't think of anything else a designer would need to start contributing . But maybe I'm not understanding the need.

**Comment by chasenlehara** [comment]
Hey @tomgreever! To be clear, I’m not advocating for any change in the process[1], I just want to make it easier for:

- designers to get up to speed with the project
- developers to reference the design mockups/prototypes

I’m afraid stuff gets lost in GitHub issues and it’s sometimes hard to answer questions like “is this a bug or how the design is supposed to look?”

Hopefully that makes it a little more clear why I think it’s worth us organizing what we have and what we make going forward.

[1] _Yet…_ I hope we get to the point of having live style guides for our sites.

**Comment by jamiemccue** [comment]
I vote we close this issue with the acknowledgment that going forward we create a centralized folder/repo (style guide) for the team to grab design resources from. The URL to access would be in the Github readme for the projects. This would make it easy for a Bitovi designer unfamiliar with the project to start contributing. (Like myself recently)

**Comment by jamiemccue** [comment]
https://github.com/canjs/canjs/tree/master/docs/can-guides/contribute
- organize all project resources
- 'here is where the design resources are located'
- create google drive with assets

**Comment by jamiemccue** [comment]
- logos - move to design drive folder
