### ISSUE TITLE
can-define-validate-validatejs demo is not working

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#3274]
the demo is not working. http://canjs.com/doc/can-define-validate-validatejs.html

```"Error loading "validate.js@0.11.1#validate" at http://canjs.com/node_modules/validate.js/validate.js
Error loading "validate.js@0.11.1#validate" from "undefined" at <unknown>
Not Found: http://canjs.com/node_modules/validate.js/validate/index.js" undefined```

**Comment by phillipskevin** [comment]
Issue moved to [canjs/can-define-validate-validatejs #16](https://github.com/canjs/can-define-validate-validatejs/issues/16) via [**ZenHub**](https://www.zenhub.com/)
