### ISSUE TITLE
Binding to a list index using bracket notation does not bind or errors

### ISSUE THREAD

**Issue by kylegifford** [canjs/canjs#3289]
if `test` is defined as `test: [''']`, then the following binding issues occur:

works:
```
<input {($value)}="test.0" />
{{test.0}}
```

works:
```
<input {($value)}="test['0']" />
{{test.0}}
```

errors in can-observation/reader:287:
```
<input {($value)}="test[0]" />
{{test.0}}
```

![screenshot 2017-05-30 15 28 50](https://cloud.githubusercontent.com/assets/4341379/26605857/e186e398-454c-11e7-8227-4d1aaf812de5.png)
![screenshot 2017-05-30 15 29 05](https://cloud.githubusercontent.com/assets/4341379/26605856/e1841e9c-454c-11e7-9cff-25a7492e2336.png)

if `test` is defined as `test: { foo: ['''] }`, then the following binding issues occur:

works:
```
<input {($value)}="test.foo.0" />
{{test.foo.0}}
```

doesn’t work (no error, just doesn't set the value):
```
<input {($value)}="test['foo']['0']" />
{{test.foo.0}}
```

errors in can-view-scope:109:
```
<input {($value)}="test['foo'][0]" />
{{test.foo.0}}
```

![screenshot 2017-05-30 15 32 25](https://cloud.githubusercontent.com/assets/4341379/26605947/353eade0-454d-11e7-9d91-013f7acddc80.png)

**Comment by phillipskevin** [comment]
Issue moved to [canjs/can-stache #207](https://github.com/canjs/can-stache/issues/207) via [**ZenHub**](https://www.zenhub.com/)
