### ISSUE TITLE
can.Map.bind() does not work on "deep" properties that are defined as type "compute"

### ISSUE THREAD

**Issue by UselessPickles** [canjs/canjs#3291]
Problem was discovered in v2.3.27.

Given the following structure of a can.Map (a view model with nested data model):

```
    var DataModel = can.Map.extend({
        define: {
            value: {
                // This "compute" type causes the problem
                type: "compute"
            }
        }
    });
    
    var viewModel = new can.Map({
    	data: new DataModel({
        	value: 42
        })
    });

```

Listening for changes to the nested `value` attribute like this does not work:
```
    viewModel.bind("data.value", function() {
        console.log("data.value changed");
    });

```

That handler is never called when changing the `value` attribute's value.

But if I more directly bind my handler like this, then it works:
```
    viewModel.attr("data").bind("value", function() {
    	console.log("attr(\'data\').value changed");
    });

```

If I bind BOTH change handlers using both approaches, then both handlers are called. The second bind "fixes" the first.

Also, this seems to be related to the `value` attribute being defined as type `"compute"`. If I remove the `type: "compute"` definition, then everything works as expected.

Here is a jsfiddle demonstrating this issue: http://jsfiddle.net/xffnzoqy/4/

**Comment by justinbmeyer** [comment]
can you use a compute here?  This bug has been around for a while and we aren't going to fix it.  Bubbling (which can.Map does) was very error prone.  Generally speaking, a compute can be created for what you need:

```js
prop: {
  get: function(){
    this.attr("data.value");
    return {}
  }
}
```

`prop` will fire everytime `data` or `value` changes.

**Comment by UselessPickles** [comment]
In my case, this approach works just fine for me:
```
    viewModel.attr("data").bind("value", function() {
    	console.log("attr(\'data\').value changed");
    });
```

Does this problem exist also in v3?

**Comment by UselessPickles** [comment]
I confirmed that this bug also exists in can v3
