### ISSUE TITLE
can.Map.attr() returns stale value for a "compute" type attr immediately after updating under certain conditions

### ISSUE THREAD

**Issue by UselessPickles** [canjs/canjs#3292]
Discovered in v2.3.27

If I have a can.Map with two "compute" properties:
```
    var DataModel = can.Map.extend({
        define: {
            triggersChangeToValue: {
                type: "compute"
            },
            value: {
                type: "compute"
            }
        }
    });

    var dataModel = new DataModel({
        triggersChangeToValue: false,
        value: 42
    });
```

AND  I have created a compute from one of the fields in the map:
`    var valueComputePassedToAnotherControlFor2WayBinding = dataModel.compute("value");
`

AND I have bound a change listener to that compute:
`    valueComputePassedToAnotherControlFor2WayBinding.bind("change", function() {});
`

AND  I change the value of that field in response to the other field changing, then immediately read the value of the changed attribute, I get the old (stale) value:
```
    dataModel.bind("triggersChangeToValue", function() {
        this.attr("value", 9000);
        console.log(this.attr("value")); // logs 42, but expected 9000!!!
    });

    // Trigger the change that should convert 'value' from 42 to 9000
    dataModel.attr("triggersChangeToValue", true);
```

This unexpected behavior seems to be triggered by a very particular combination of factors. For example, if I change EITHER property definition to not be "compute", then it works properly. Or, if I simply don't bind a change listener to my `valueComputePassedToAnotherControlFor2WayBinding`, then it also works as expected.

This is a complicated situation that is best demonstrated, rather than attempting to explain fully in words. Here is a jsfiddle demonstrating the problem, with several comments pointing out aspects of the situation that seem to trigger the unexpected behavior: 

http://jsfiddle.net/n491v2xq/4/

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-map #45](https://github.com/canjs/can-map/issues/45) via [**ZenHub**](https://www.zenhub.com/)
