### ISSUE TITLE
Number alignment

### ISSUE THREAD

**Issue by moschel** [canjs/canjs#3316]
Is this intentional? or a bug?

<img width="1049" alt="2017-06-17_2054" src="https://user-images.githubusercontent.com/22180/27257524-64d51246-539f-11e7-8fe6-16c441b7d0a5.png">

**Comment by justinbmeyer** [comment]
Bug.  @imaustink did you make any progress on this?

**Comment by imaustink** [comment]
Yes sir, I have a PR in https://github.com/canjs/bit-docs-html-canjs/pull/325. I will add you as a reviewer.
