### ISSUE TITLE
Design Credit Card Form

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#3318]
Please create a CC form that looks like:

![image](https://user-images.githubusercontent.com/78602/27299050-99127e2a-54f0-11e7-903c-838879282ae0.png)

Use the following JSBin as a template:

http://justinbmeyer.jsbin.com/kukare/edit?html,css,js,output

Change its CSS in the CSS tab.

Please design the Pay button with `disabled` and active state in mind.  Thanks!

**Comment by justinbmeyer** [comment]
I've removed the `email` part of this form.

**Comment by adrifolio** [comment]
@justinbmeyer I cloned the bin here: http://jsbin.com/bahinof/edit?html,css,output

![credit-card](https://user-images.githubusercontent.com/950214/27342056-a97bf9c6-55a4-11e7-9465-f8fe79cc89e2.gif)

Note that I moved the error message to the top. Let me know your thoughts!

**Comment by adrifolio** [comment]
Added error styles:

<img width="365" alt="screen shot 2017-06-20 at 2 59 15 pm" src="https://user-images.githubusercontent.com/950214/27353283-1ffa40de-55c9-11e7-8524-dd4768ca3b7e.png">

**Comment by justinbmeyer** [comment]
@adrifolio could you make the button when disabled look more disabled?  Thanks!

**Comment by adrifolio** [comment]
@justinbmeyer check this out:

<img width="368" alt="screen shot 2017-06-21 at 8 21 52 am" src="https://user-images.githubusercontent.com/950214/27386213-b632574e-565a-11e7-86a3-9d265f91b10c.png">

**Comment by justinbmeyer** [comment]
![cursor_and_canjs_-_credit_card_guide__simple_](https://user-images.githubusercontent.com/78602/27451508-d86e9bd8-5754-11e7-954b-a812e1ed63b1.png)

**Comment by justinbmeyer** [comment]
![cursor_and_js_bin_-_collaborative_javascript_debugging](https://user-images.githubusercontent.com/78602/27451781-ea3ed3d6-5755-11e7-8dd8-c4e83bc8aa90.png)
