### ISSUE TITLE
Allow to have default variables in can.Model ajax call

### ISSUE THREAD

**Issue by schovi** [canjs/canjs#336]
It can have similar syntax as can.Control defaults

```javascript
can.Model('User', {
  options: {
    host: "http://testapi.apiary.io"
  },
  findOne: "GET {host}/user/{id}.json"
}, {})
```

only instead of `defaults` i choose `options` because defaults can lead to misunderstanding and i can imagine it can be used as default model values in future.

----
I made my own implementation, but it is ugly and buggy -> findOne({id:1}) will call /user/1.json?id=1 :-1: 
I will try to fix it and share

**Comment by justinbmeyer** [comment]
Does `resource` solve this?  I think for most situations, it probably would.

**Comment by justinbmeyer** [comment]
closing unless this gets more interest.
