### ISSUE TITLE
Change 'id' attribute to be function for composed ids in complex scenarios

### ISSUE THREAD

**Issue by amcdnl** [canjs/canjs#337]
The model store doesn't account for lack of ids or ids that are not unique.  

For instance, in the following demonstration the 'user' is unique to each 'department' but not unique to the model its in.  

    [  {  user: 1, department: 1 }, { user: 1, department: 2 } ]

A composed id attribute would accept a function and created a id like:

    id: function(){
        return this.department + '/' + this.user;
    }
    
Additionally, we should throw a warning if there is no id and/or use the `.__cid` property.

**Comment by justinbmeyer** [comment]
Moving to can-connect.
