### ISSUE TITLE
“diffObject” in canJS does not work if the value of the property is an array

### ISSUE THREAD

**Issue by pavankmv** [canjs/canjs#3405]
let obj1={id:1,values:[1,2,3,4,5]}, obj2={id:1,values:[1,2,3,4,5]};
diffObject(obj1, obj2)?
**Output**
Actual:
[{"property":"values","type":"set","value":[1,2,3,4,5]}]
Expected:
[] i.e. Empty Array 
As both the objects are same

**Comment by justinbmeyer** [comment]
It's not a deep diff. If you need a deep merge/diff look at https://canjs.com/doc/can-connect/helpers/map-deep-merge.html
