### ISSUE TITLE
Algebra where clause issue with compound ids

### ISSUE THREAD

**Issue by gregorgodoy** [canjs/canjs#3409]
In the can-set the getClauseProperties function, breakup incorrectly the id and where clause when the algebra has multiple ids.

A full explanation and example in this forum post:

http://forums.donejs.com/t/algebra-clause-issue-possible-bug/682

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-set #62](https://github.com/canjs/can-set/issues/62) via [**ZenHub**](https://www.zenhub.com/)
