### ISSUE TITLE
Missing license files in projects

### ISSUE THREAD

**Issue by andrejewski** [canjs/canjs#3440]
The affected projects without license files are:

- can-cid
- can-component
- can-compute
- can-connect
- can-construct
- can-construct-super
- can-ejs
- can-event
- can-jquery
- can-list
- can-list-sort
- can-map
- can-map-backup
- can-map-define
- can-model
- can-route
- can-stache
- can-stache-bindings
- can-types
- can-validate-legacy
- can-view-autorender
- can-view-callbacks
- can-view-model

These are according to issue https://github.com/canjs/can-stache/issues/248 and there are potentially more.

---

*We are working on an automation tool to fix these, no one waste their time making individual PRs.*

**Comment by chasenlehara** [comment]
Thank you @andrejewski and @dpeixoto; we are working to resolve this today.

Closing this in favor of https://github.com/canjs/canjs/issues/3440
