### ISSUE TITLE
Proposal: Create a documentation badge for linking documentation

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/canjs#3443]
Create a documentation badge for linking documentation #3419 https://github.com/donejs/developer-relations/issues/12
- use http://svgshare.com/i/2Bm.svg
add documentation in grey on the right side and adjust size

this needs to be discussed here:
@andrejewski sayed:
> The badge, like donejs/developer-relations#12, needs to be discussed before anyone spends too much time on it.

**Comment by chasenlehara** [comment]
I’m closing this because we’re not going to move forward with this idea right now. We discussed it in the [2017-07-28 contributors meeting](http://forums.donejs.com/t/donejs-contributors-meeting-2017-07-28/691/9).
