### ISSUE TITLE
Proposal: create a FAQ Page on canjs.com

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/canjs#3444]
I think a faq page that gets linked in error messages with the right section would help a lot so users understand errors and solutions better

example:
Hi, when I write something like:
```<h3 class="userCard-userName">{{currentPerson.firstname}} {{currentPerson.lastname}}</h3>```
I have a warning in console:
```WARN: can-stache/src/expression.js: Unable to find key or helper "currentPerson.imageUrl".```
It doesn't break anything, but annoys a bit. Besides currentPerson is in ```viewModel```, what exactly wrong with ```{{currentPerson}}``` notation, because I think I have the same warning in other places when show some info on the page.

The Warning could stay as is but we add https://canjs.com/faq#expression-warnings

The content would be something like:
This warning happens sometimes when you do not try to read it (imgUrl) in a stache Template but its set on a property of defineMap as property

or if your using async values that are undefined at first like a promis always return the promis directly and use isResolved alternate method when your function uses resolve wrapp it with if

```
{{#if entitiesList}}
  {{#each entitiesList}}
  {{/each}}
{{/if}}
```

we could also add some wrong examples for canDefine and canConnect there this are the places where most trouble happens in canjs

**Comment by frank-dspeed** [comment]
also good issue to add: canjs/can-route#98

**Comment by chasenlehara** [comment]
Thanks for the feedback @frank-dspeed, I’m going to close this in favor of https://github.com/canjs/can-connect/issues/347, https://github.com/canjs/can-stache/issues/282, and https://github.com/canjs/canjs/issues/3416.
