### ISSUE TITLE
Proposal: Better Error Handling

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/canjs#3459]
does any one know if we could copy that fast?
https://facebook.github.io/react/blog/2017/07/26/error-handling-in-react-16.html
i think its nice if we would also have errors by component some how
i think we could maybe do errors by viewModel ?
as the code normal always gets executed inside a viewModel right?

i am not sure if we and where we should implament this i think the most best could be can-component or done-component or even the viewModel?

Some one with a higher view about the overall concepts needs to look into this i think

**Comment by justinbmeyer** [comment]
Yeah, I read about this.  The parallel to this would be doing it in stache.  Or even in observation.  The error would somehow need to be communicated to the component or maybe just a `%error` in a template.

Moving this issue to can-stache.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-stache #254](https://github.com/canjs/can-stache/issues/254) via [**ZenHub**](https://www.zenhub.com/)
