### ISSUE TITLE
IE9 Tests False Positives

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#3482]
The tests in IE9 are not running, but they show `(0 / 0) successful` so the CI job still completes successfully.

Last build where tests ran: https://travis-ci.org/canjs/canjs/builds/240128705
First PR where tests did NOT run: https://github.com/canjs/canjs/pull/3381/files

Related to https://github.com/bitovi/test-saucelabs/issues/5

**Comment by Sinjhin** [comment]
Main tests that were added:
- [ ] `require('can-connect-ndjson/test/can-connect-ndjson-test');`
- [ ] `require('can-ndjson-stream/can-ndjson-stream-test');`
- [ ] `require('can-connect-ndjson/test/can-connect-ndjson-test');`
- [ ] `require('can-ndjson-stream/can-ndjson-stream-test');`
- [ ] `require('can-reflect/can-reflect-test');`
- [ ] `require('can-symbol/can-symbol-test');`

**Comment by Sinjhin** [comment]
Updates since `3.9.1`
- [ ] ``
- [ ] ``
- [ ] ``
- [ ] ``
- [ ] ``
- [ ] ``
- [ ] ``
- [ ] ``
- [ ] ``
- [ ] ``
- [ ] ``

**Comment by phillipskevin** [comment]
this is fixed in `minor`.
