### ISSUE TITLE
Unavoidable error message: Dispatching a synthetic event on a disabled element

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#3496]
Code like:

```
<button disabled:from="disablePaymentButton.value">Pay $1000</button>
```

Gives the following warning:

![localhost_8080_canjs_demos_can-kefir_credit-card_html_number_1234-1234-1234-1234_expiry_12-12_cvc_123](https://user-images.githubusercontent.com/78602/29442334-6842a0de-8396-11e7-96f9-f874686d0162.png)

We are changing disabled and firing an attribute event that no one is listening for.  

Related to https://github.com/canjs/can-util/issues/294

We should avoid firing this warning, ideally by not dispatching an attributes event because nothing should be listening to an attributes event.

**Comment by justinbmeyer** [comment]
Ideally ... we wouldn't need to dispatch an attributes event anymore.  Instead we'd have a MutationObserver polyfill that avoids DOM dispatching.  

cc @andrejewski 

This would be a 4.0 change likely.

**Comment by matthewp** [comment]
I can't tell what this issue is about. Is it a bug report, a feature request? Could you update the issue with a little more description of what is wrong / what should be happening. Thanks.

**Comment by justinbmeyer** [comment]
@matthewp updated a little.  Let me know if it's not clear.

**Comment by justinbmeyer** [comment]
The short-term fix is to make can-stache and can-stache-bindings smart about knowing what might have dynamic attributes, and avoid setting up `attributes` event binding if the element in question isn't listening to attributes changes.

**Comment by phillipskevin** [comment]
Here is an example JSBin reproducing the issue: http://jsbin.com/joteciriqo/edit?html,js,output.

In this case, the warning is produced because of the `removed` event that gets dispatched when the `{{#if}}` is toggled.

I don't think we can avoid dispatching these events because we use them to teardown the bindings for the live attributes.

**Comment by andrejewski** [comment]
The warning not longer exists in @phillipskevin's JSBin updated to use can@4.0.0-pre.10: http://jsbin.com/jowixuxeye/edit?html,js,output

Inspecting the last Can `_traceData` the only modules using `domDispatch` and `can-util/domEvents` which expose the warning code path are test files. So CanJs internally will not produce this warning anymore in 4.0.

**Comment by matthewp** [comment]
lgtm 👍
