### ISSUE TITLE
Remove all pre-release dependencies

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3500]
A bunch of our packages are still pointing to prerelease versions of their dependencies:

- https://github.com/canjs/can-view-model/blob/403b8718994d2ab41d96cdc2e881bd8d54fc61be/package.json#L33-L34
- https://github.com/canjs/can-construct/blob/f449c72eef4e437abf512c8452a4fa082be9550e/package.json#L38-L39
- https://github.com/canjs/can-view-live/blob/f5cb90820e1c2de4a5376b14fc973ccc493fa3cc/package.json#L55-L60
- https://github.com/canjs/can-list/blob/4fe2e5a6232b0634043f9c8890e9d369ab28f5bc/package.json#L39-L47
- https://github.com/canjs/can-compute/blob/c4d14077a72282fde2c1c56dc13220666ccdfd9b/package.json#L37-L39
- https://github.com/canjs/can-simple-map/blob/47a0b0d5d9c1496252925bfbbe00ede7712b3a3d/package.json#L45-L51
- https://github.com/canjs/can-map/blob/17b72c2951a002804fe3398cd85a5c7b9b55ad56/package.json#L38-L45
- https://github.com/canjs/can-route/blob/103203675e465e32a274725df98d19acde2095e5/package.json#L48-L56
- https://github.com/canjs/can-util/blob/f1adba9ca03b040872abadcd170210fa1ac40fda/package.json#L84-L85

This is not an exhaustive list, so whoever takes this issue should find them all.

**Comment by phillipskevin** [comment]
This codemod can be used to make the changes: https://gist.githubusercontent.com/phillipskevin/75a3626b00dd32709b13132706cb7f30/raw/36b0a4f55cc611e79670549ed9a24b9bc8670a42/remove-pre-release-deps.js.

**Comment by bmomberger-bitovi** [comment]
I think I've found them all.

**Comment by chasenlehara** [comment]
@bmomberger-bitovi It looks like this one still needs to be updated: https://github.com/canjs/can-simple-map/blob/master/package.json#L45-L51

I would close this once you’ve merged & released all the PRs you created.

**Comment by bmomberger-bitovi** [comment]
Yep, I had pushed it but not created a PR.  Will close this once patch releases are done for every lib.

**Comment by phillipskevin** [comment]
I closed this since all the PRs have been merged.
