### ISSUE TITLE
Extract out can-simple-observable

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#3546]
We need a way of making simple primitive values reflective without using computes.

This code here is the basis and can be replaced once this exists: https://github.com/canjs/can-stache-bindings/blob/master/can-stache-bindings.js#L71-L101.

This code should also be changed to use `canReflect.assignSymbols`.

**Comment by justinbmeyer** [comment]
- bike shed on name

**Comment by phillipskevin** [comment]
Let's go with `can-simple-observable`.

**Comment by phillipskevin** [comment]
This has been published: https://www.npmjs.com/package/can-simple-observable.
