### ISSUE TITLE
Error: Cannot find module 'can-make-rest'

### ISSUE THREAD

**Issue by lgh5018** [canjs/canjs#3576]
vim a.js:
`
var makeRest = require('can-make-rest');
`
node a.js

=>

module.js:471
    throw err;
    ^

Error: Cannot find module 'can-make-rest'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/vagrant/ttt/cc/aaa.js:2:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by pYr0x** [comment]
Have you installed can-make-rest via npm?

**Comment by lgh5018** [comment]
yes!
===================================
ubuntu@ubuntu-xenial:/vagrant/ttt/cc$ ll
total 15
drwxrwxrwx 1 ubuntu ubuntu 4096 Sep 24 00:34 ./
drwxrwxrwx 1 ubuntu ubuntu 4096 Sep 23 16:11 ../
-rwxrwxrwx 1 ubuntu ubuntu   42 Sep 23 16:27 a.js*
-rwxrwxrwx 1 ubuntu ubuntu    0 Sep 23 16:15 bundle.js*
-rwxrwxrwx 1 ubuntu ubuntu  236 Sep 23 09:34 index.html*
-rwxrwxrwx 1 ubuntu ubuntu   39 Sep 23 16:51 main.js*
-rwxrwxrwx 1 ubuntu ubuntu   31 Sep 23 14:22 main.stache*
drwxrwxrwx 1 ubuntu ubuntu 4096 Sep 23 16:33 node_modules/
-rwxrwxrwx 1 ubuntu ubuntu   58 Sep 23 16:33 package.json*
ubuntu@ubuntu-xenial:/vagrant/ttt/cc$ cat package.json
{
  "dependencies": {
    "can-make-rest": "^0.1.1"
  }
}
ubuntu@ubuntu-xenial:/vagrant/ttt/cc$ cat a.js
var makeRest = require('can-make-rest');
ubuntu@ubuntu-xenial:/vagrant/ttt/cc$

**Comment by justinbmeyer** [comment]
Thanks, the `dist` isn't getting included for some reason.  @phillipskevin it might be good to have a code-mod go find any `main` thats that point to dist and just remove them.  I'll fix this in can-make-rest.

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-make-rest #12](https://github.com/canjs/can-make-rest/issues/12) via [**ZenHub**](https://www.zenhub.com/)
