### ISSUE TITLE
can.Control route plugin destroy during route change

### ISSUE THREAD

**Issue by amcdnl** [canjs/canjs#359]
If I have a Control that is listening for route changes and then I destroy the Control during change, the event is still called on the control.

	var Files = can.Control({
		'/:view route':function(){
			this.element.html('WOO!')
		}
	});

	var Contacts = can.Control({
		'/:view route':function(){
			this.element.html('WOO!')
		}
	});

	var views = {
		contacts: Contacts,
		files: Files
	};

	var ParentControl = can.Control({
		'/:view route':function(route){
			$(document.body).control().destroy();
			new views[route.view](document.body);
		}
	});

	<a href="#!/contacts">Contacts</a>
	<a href="#!/files">Files</a>

Would probably be a good idea to add a `controller.element` check here: https://github.com/bitovi/canjs/blob/master/control/route/route.js#L11

Thoughts?

**Comment by justinbmeyer** [comment]
Closing as using controls for routing has been deprecated for over a year.
