### ISSUE TITLE
Determine API docs grouping

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3594]
Below is a series of comments with some thoughts on how we could organize things. These are just some ideas to get the conversation started. 👍’s are welcome on individual comments to show support for the ideas in that comment.

**Comment by chasenlehara** [comment]
[Justin’s proposal description](https://github.com/canjs/canjs/issues/3404#issue-241132072) grouped most but not all of the packages into these groups:

- Observables
- Views
- Data Modeling
- DOM Utilities
- Routing
- Typed Data
- Polyfills
- JS Utilities

I’ve put the rest of our packages (as of [minor](https://github.com/canjs/canjs/tree/minor) a few days ago) into these groups. You can also see the list below [in a spreadsheet](https://docs.google.com/spreadsheets/d/1gJfTsgABVmbViLIzjcZw-PCSxM6hU2nSSNPXa139i7Q/edit?usp=sharing).

<details>
 <summary>All Packages Grouped by Purpose</summary>
 
1. Observables
	- Core
		- can-define
		- can-define/list/list
		- can-define/map/map
	- Infrastructure
		- can-compute
		- can-event
		- can-event/async/async
		- can-event/batch/batch
		- can-event/lifecycle/lifecycle
		- can-observation
		- can-simple-map
		- can-simple-observable
		- can-stream
		- can-stream-kefir
	- Ecosystem
		- can-define-stream
		- can-define-stream-kefir
		- can-kefir
		- can-observe
	- Legacy
		- can-list
		- can-map
		- can-map-backup
		- can-map-define
2. Data Modeling
	- Core
		- can-connect
		- can-set
	- Ecosystem
		- can-connect-cloneable
		- can-connect-feathers
		- can-connect-ndjson
		- can-connect-signalr
		- can-fixture
		- can-fixture-socket
		- can-ndjson-stream
3. Views
	- Core
		- can-component
		- can-stache
		- can-stache-bindings
	- Infrastructure
		- can-stache-converters
		- can-view-callbacks
		- can-view-live
		- can-view-model
		- can-view-nodelist
		- can-view-parser
		- can-view-scope
		- can-view-target
	- Ecosystem
		- can-element
		- can-react-component
		- can-view-autorender
		- can-view-import
		- react-view-model
		- react-view-model/component
		- steal-stache
	- Legacy
		- can-ejs
		- can-view-href
4. Routing
	- Core
		- can-route
		- can-route-pushstate
		- can-stache/helpers/route
	- Infrastructure
		- can-deparam
		- can-param
5. JS Utilities
	- Infrastructure
		- can-ajax
		- can-assign
		- can-globals
		- can-make-map
		- can-parse-uri
		- can-test-helpers
		- can-util
	- Ecosystem
		- can-zone
		- can-zone-storage
6. DOM Utilities
	- Infrastructure
		- can-attribute-encoder
		- can-control
		- can-dom-events
		- can-event-dom-enter
		- can-event-dom-radiochange
	- Ecosystem
		- can-jquery
7. Data Validation
	- Infrastructure
		- can-validate-interface
	- Ecosystem
		- can-define-validate-validatejs
		- can-validate
		- can-validate-validatejs
	- Legacy
		- can-validate-legacy
8. Typed Data
	- Infrastructure
		- can-cid
		- can-construct
		- can-namespace
		- can-reflect
		- can-reflect-promise
		- can-types
	- Ecosystem
		- can-construct-super
9. Polyfills
	- Infrastructure
		- can-symbol
	- Ecosystem
		- can-vdom
</details>

**Comment by chasenlehara** [comment]
Out of curiosity, I got the number of page views for each package shown in the sidebar to determine what is most frequently viewed on the site. The numbers include all of the pages under each package, but is adjusted so nothing is double-counted (i.e. `can-stache` does not include `can-stache-bindings` in its total).

<details>
 <summary>Here are the packages that received at least 1000 page views this year</summary>
 
1. can-connect: 15,980
2. can-stache: 11,924
3. can-component: 7,148
4. can-define/map/map: 4,263
5. can-define/list/list: 3,737
4. can-stache-bindings: 3,620
5. can-util: 3,575
6. can-define: 3,541
7. can-set: 3,029
8. can-event: 2,671
9. can-route: 2,157
10. can-compute: 1,980
11. can-fixture: 1,406
12. can-control: 1,388
13. can-stache-converters: 1,277
</details>
<br />

Most of the packages in this list are in Core, with some notable exceptions:

- can-control
- can-event
- can-fixture
- can-stache-converters
- can-util

In the new sidebar, I think it’s important to make these visible by default so they’re more easily accessible.

**Comment by chasenlehara** [comment]
Keeping the above in mind, here’s what we could show by default if we include the Core packages and the exceptions I noted above.

<details>
 <summary>Core packages + exceptions noted above</summary>
 
1. Observables
	- can-define
	- can-define/list/list
	- can-define/map/map
	- can-event
2. Data Modeling
	- can-connect
	- can-fixture
	- can-set
3. Views
	- can-component
	- can-stache
	- can-stache-bindings
	- can-stache-converters
4. Routing
	- can-route
	- can-route-pushstate
	- can-stache/helpers/route
5. JS Utilities
	- can-util
6. DOM Utilities
	- can-control
</details>
<br />

I think this is decent. All of Observables, Data Modeling, and Views would be above the fold for the majority of our users (based on looking at screen resolutions in Google Analytics).

**Comment by chasenlehara** [comment]
Note that in the above list, there isn’t anything shown from Data Validation, Typed Data, or Polyfills, and there are only a couple utilities shown.

I think what we would actually want to do is show most of the packages in those categories; I think it matters less to hide them since they’re further down in the navigation.

In some ways, I think this could even strengthen CanJS’s brand as a collection of useful libraries, because a lot of utilities would be shown and they would be on the same hierarchical level as everything else.

<details>
 <summary>Here’s what the nav could look like by default if we included more of the utility packages</summary>
 
1. Observables
	- can-define
	- can-define/list/list
	- can-define/map/map
	- can-event
2. Data Modeling
	- can-connect
	- can-fixture
	- can-set
3. Views
	- can-component
	- can-stache
	- can-stache-bindings
	- can-stache-converters
4. Routing
	- can-route
	- can-route-pushstate
	- can-stache/helpers/route
5. JS Utilities
	- can-ajax
	- can-assign
	- can-globals
	- can-make-map
	- can-parse-uri
	- can-test-helpers
	- can-util
	- can-zone
	- can-zone-storage
6. DOM Utilities
	- can-attribute-encoder
	- can-control
	- can-dom-events
	- can-event-dom-enter
	- can-event-dom-radiochange
	- can-jquery
7. Data Validation
	- can-define-validate-validatejs
	- can-validate
	- can-validate-interface
	- can-validate-validatejs
8. Typed Data
	- can-cid
	- can-construct
	- can-construct-super
	- can-namespace
	- can-reflect
	- can-reflect-promise
	- can-types
9. Polyfills
	- can-symbol
	- can-vdom
</details>

**Comment by chasenlehara** [comment]
What about all the other packages?

- __Observables__ still has Infrastructure, Ecosystem, and Legacy packages
- __Data Modeling__ has more Ecosystem packages
- __Views__ has more Infrastructure, Ecosystem, and Legacy packages
- __Routing__ has more Infrastructure packages
- __Data Validation__ has one Legacy package

<details>
 <summary>Here’s all the packages with the Infrastructure/Ecosystem/Legacy ones included too</summary>
 
1. Observables
	- can-define
	- can-define/list/list
	- can-define/map/map
	- can-event
	- Infrastructure
		- can-compute
		- can-event/async/async
		- can-event/batch/batch
		- can-event/lifecycle/lifecycle
		- can-observation
		- can-simple-map
		- can-simple-observable
		- can-stream
		- can-stream-kefir
	- Ecosystem
		- can-define-stream
		- can-define-stream-kefir
		- can-kefir
		- can-observe
	- Legacy
		- can-list
		- can-map
		- can-map-backup
		- can-map-define
2. Data Modeling
	- can-connect
	- can-fixture
	- can-set
	- Ecosystem
		- can-connect-cloneable
		- can-connect-feathers
		- can-connect-ndjson
		- can-connect-signalr
		- can-fixture-socket
		- can-ndjson-stream
3. Views
	- can-component
	- can-stache
	- can-stache-bindings
	- can-stache-converters
	- Infrastructure
		- can-view-callbacks
		- can-view-live
		- can-view-model
		- can-view-nodelist
		- can-view-parser
		- can-view-scope
		- can-view-target
	- Ecosystem
		- can-element
		- can-react-component
		- can-view-autorender
		- can-view-import
		- react-view-model
		- react-view-model/component
		- steal-stache
	- Legacy
		- can-ejs
		- can-view-href
4. Routing
	- can-route
	- can-route-pushstate
	- can-stache/helpers/route
	- Infrastructure
		- can-deparam
		- can-param
5. JS Utilities
	- can-ajax
	- can-assign
	- can-globals
	- can-make-map
	- can-parse-uri
	- can-test-helpers
	- can-util
	- can-zone
	- can-zone-storage
6. DOM Utilities
	- can-attribute-encoder
	- can-control
	- can-dom-events
	- can-event-dom-enter
	- can-event-dom-radiochange
	- can-jquery
7. Data Validation
	- can-define-validate-validatejs
	- can-validate
	- can-validate-interface
	- can-validate-validatejs
	- Legacy
		- can-validate-legacy
8. Typed Data
	- can-cid
	- can-construct
	- can-construct-super
	- can-namespace
	- can-reflect
	- can-reflect-promise
	- can-types
9. Polyfills
	- can-symbol
	- can-vdom
</details>
<br />

I think we have a few different options…

**Comment by chasenlehara** [comment]
As proposed by Justin, we could have buttons that show/hide entire collections across all the groupings, similar to this screenshot (from [here](https://github.com/canjs/canjs/issues/3404#issue-241132072)):

<img width="187" alt="Buttons for the entire collection" src="https://user-images.githubusercontent.com/78602/30555699-dfe14470-9c6d-11e7-8bc6-fd3ff2bb5045.png">

He noted that “[h]aving the collection toggle at the top might be annoying because you wont be able to see what's there,” which I agree with; there’s less of a connection between what the user clicks and what will be updated in the nav. Those buttons would be hidden when scrolling through the list as well, unless we created some sort of sticky header for them.

**Comment by chasenlehara** [comment]
We could add the collection names under each grouping so they only appear if there’s more to see (from [here](https://github.com/canjs/canjs/issues/3404#issuecomment-330301695)):

<img width="230" alt="Collections under each grouping" src="https://user-images.githubusercontent.com/78602/30556772-a1e0f5cc-9c71-11e7-9fb8-87b3c9198996.png">

**Comment by chasenlehara** [comment]
Here’s another take on the above idea, with show/hide buttons for non-Core collections under each group:

__Collapsed:__
<img width="248" alt="show" src="https://user-images.githubusercontent.com/10070176/31255070-ee527a7c-a9df-11e7-83cc-eb9d6b9b4711.png">

__Expanded:__
<img width="260" alt="hide" src="https://user-images.githubusercontent.com/10070176/31255096-f42d6024-a9df-11e7-9c6b-854d46ad0d14.png">

Do we even need to give a title to the Core group? It takes valuable vertical space away, so I think it’d be ok not to include it.

**Comment by chasenlehara** [comment]
Another idea: move the Infrastructure items out from under the main groupings and into their own top-level sections.

This would leave us with Ecosystem and Legacy under each section. We could show and hide them via More/Less buttons.

<details>
 <summary>Structure if we moved Infrastructure packages into their own sections and grouped Ecosystem &amp; Legacy under a “More” button</summary>
 
1. Observables
	- can-define
	- can-define/list/list
	- can-define/map/map
	- can-event
	- More…
		- can-define-stream
		- can-define-stream-kefir
		- can-kefir
		- can-observe
		- Legacy
			- can-list
			- can-map
			- can-map-backup
			- can-map-define
2. Data Modeling
	- can-connect
	- can-fixture
	- can-set
	- More…
		- can-connect-cloneable
		- can-connect-feathers
		- can-connect-ndjson
		- can-connect-signalr
		- can-fixture-socket
		- can-ndjson-stream
3. Views
	- can-component
	- can-stache
	- can-stache-bindings
	- can-stache-converters
	- More…
		- can-element
		- can-react-component
		- can-view-autorender
		- can-view-import
		- react-view-model
		- react-view-model/component
		- steal-stache
		- Legacy
			- can-ejs
			- can-view-href
4. Routing
	- can-route
	- can-route-pushstate
	- can-stache/helpers/route
	- More…
		- can-deparam
		- can-param
5. JS Utilities
	- can-ajax
	- can-assign
	- can-globals
	- can-make-map
	- can-parse-uri
	- can-test-helpers
	- can-util
	- can-zone
	- can-zone-storage
6. DOM Utilities
	- can-attribute-encoder
	- can-control
	- can-dom-events
	- can-event-dom-enter
	- can-event-dom-radiochange
	- can-jquery
7. Data Validation
	- can-define-validate-validatejs
	- can-validate
	- can-validate-interface
	- can-validate-validatejs
	- More…
		- Legacy
			- can-validate-legacy
8. Observables Infrastructure (or some other name)
	- can-compute
	- can-event/async/async
	- can-event/batch/batch
	- can-event/lifecycle/lifecycle
	- can-observation
	- can-simple-map
	- can-simple-observable
	- can-stream
	- can-stream-kefir
9. Views Infrastructure
	- can-view-callbacks
	- can-view-live
	- can-view-model
	- can-view-nodelist
	- can-view-parser
	- can-view-scope
	- can-view-target
10. Typed Data
	- can-cid
	- can-construct
	- can-construct-super
	- can-namespace
	- can-reflect
	- can-reflect-promise
	- can-types
9. Polyfills
	- can-symbol
	- can-vdom
</details>

**Comment by chasenlehara** [comment]
I think we could even integrate the Legacy packages with the others and just make sure each one has a deprecation warning on their main pages. If we did that, we wouldn’t have to indent the additional packages differently; we could just have Show More and Show Less buttons to control what’s displayed:

__Collapsed:__
<img width="200" alt="show more" src="https://user-images.githubusercontent.com/10070176/31255130-26840d0c-a9e0-11e7-98e0-433ed4b50456.png">

__Expanded:__
<img width="200" alt="show less" src="https://user-images.githubusercontent.com/10070176/31255134-2c26ebee-a9e0-11e7-9661-45a66be79fdb.png">

Alternatively, we could add ☑ Show Legacy checkbox at the top or bottom of the API Docs section to show/hide those packages. [Ember does this in their docs.](https://www.emberjs.com/api)

<details>
 <summary>Hierarchy with Ecosystem and Legacy collections on the same level</summary>
 
1. Observables
	- can-define
	- can-define/list/list
	- can-define/map/map
	- can-event
	- More…
		- can-define-stream
		- can-define-stream-kefir
		- can-kefir
		- can-list
		- can-map
		- can-map-backup
		- can-map-define
		- can-observe
2. Data Modeling
	- can-connect
	- can-fixture
	- can-set
	- More…
		- can-connect-cloneable
		- can-connect-feathers
		- can-connect-ndjson
		- can-connect-signalr
		- can-fixture-socket
		- can-ndjson-stream
3. Views
	- can-component
	- can-stache
	- can-stache-bindings
	- can-stache-converters
	- More…
		- can-ejs
		- can-element
		- can-react-component
		- can-view-autorender
		- can-view-href
		- can-view-import
		- react-view-model
		- react-view-model/component
		- steal-stache
4. Routing
	- can-route
	- can-route-pushstate
	- can-stache/helpers/route
	- More…
		- can-deparam
		- can-param
5. JS Utilities
	- can-ajax
	- can-assign
	- can-globals
	- can-make-map
	- can-parse-uri
	- can-test-helpers
	- can-util
	- can-zone
	- can-zone-storage
6. DOM Utilities
	- can-attribute-encoder
	- can-control
	- can-dom-events
	- can-event-dom-enter
	- can-event-dom-radiochange
	- can-jquery
7. Data Validation
	- can-define-validate-validatejs
	- can-validate
	- can-validate-interface
	- can-validate-validatejs
	- More…
		- can-validate-legacy
8. Observables Infrastructure (or some other name)
	- can-compute
	- can-event/async/async
	- can-event/batch/batch
	- can-event/lifecycle/lifecycle
	- can-observation
	- can-simple-map
	- can-simple-observable
	- can-stream
	- can-stream-kefir
9. Views Infrastructure
	- can-view-callbacks
	- can-view-live
	- can-view-model
	- can-view-nodelist
	- can-view-parser
	- can-view-scope
	- can-view-target
10. Typed Data
	- can-cid
	- can-construct
	- can-construct-super
	- can-namespace
	- can-reflect
	- can-reflect-promise
	- can-types
9. Polyfills
	- can-symbol
	- can-vdom
</details>

**Comment by chasenlehara** [comment]
Again, these are just some ideas to get the conversation started.

I personally most like the [third to last idea](https://github.com/canjs/canjs/issues/3594#issuecomment-334607280) (because it’s clear about what you’re showing/hiding) and the [last idea](https://github.com/canjs/canjs/issues/3594#issuecomment-334607581) (because it has the most simple hierarchy).

**Comment by phillipskevin** [comment]
I like the [option](https://github.com/canjs/canjs/issues/3594#issuecomment-334607333) with the simple `More...` button for CanJS Users.

However, I think this makes it more difficult for CanJS Authors to find API docs, since they're most often looking at infrastructure docs I think. Maybe that doesn't matter?

**Comment by chasenlehara** [comment]
Yeah, I think breaking the Infrastructure packages into their own groupings might be more confusing, because you’d look for them when expanding the section, not be able to find them, then need to scroll down to find their own grouping.

**Comment by chasenlehara** [comment]
After talking with Justin, I’m going to more forward with the design in [this comment](https://github.com/canjs/canjs/issues/3594#issuecomment-334607581) (show more/less buttons).

Some other notes:

- _Not_ going to [make any non-Core packages visible by default](https://github.com/canjs/canjs/issues/3594#issuecomment-334606645).
- _Not_ going to [move the Infrastructure items out from under the main groupings](https://github.com/canjs/canjs/issues/3594#issuecomment-334607333).
- I’ll work with a designer on some ideas for showing the collections in the sidebar, but for now I’ll proceed with not showing those. We’ll at least want to [mark all the Legacy packages as deprecated](https://github.com/canjs/canjs/issues/3621).
- All the packages will have new parents, e.g. `@parent can-observables` for can-define, and a new `@collection` tag will be added; these changes can be made as late as possible as to not disrupt any releases
