### ISSUE TITLE
Design new API docs sidebar

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3595]
Below is what I’ve come up with so far. Some considerations:

- Important concept is that we will show Core packages under the groupings by default, then allow the user to optionally show the others
- We will hide all the packages under some groups by default
- We may or may not want to show some sort of indicator for each package’s collection

__Collapsed:__
<img width="200" alt="show more" src="https://user-images.githubusercontent.com/10070176/31255130-26840d0c-a9e0-11e7-98e0-433ed4b50456.png">

__Expanded:__
<img width="200" alt="show less" src="https://user-images.githubusercontent.com/10070176/31255134-2c26ebee-a9e0-11e7-9661-45a66be79fdb.png">

**Comment by tomgreever** [comment]
I attempted to combine this idea with @adrifolio's from https://github.com/canjs/canjs/issues/3404#issuecomment-330320397 but I wasn't happy with  the results. It makes the interface too heavy / cluttered / busy imo... and I didn't even add the shapes and colors to each element:
<img width="584" alt="screen shot 2017-10-11 at 3 41 52 pm" src="https://user-images.githubusercontent.com/326843/31465810-ba0b789e-ae9a-11e7-9f4b-3c627776238f.png">

I think the best solution is probably the simplest, given this new organization with a collapsed / expanded state. My recommendation is to add a single "show all" / "show less" text link next to the API parent.

- Clicking "show all" expands all of the groups and shows all of the libraries
- When expanded, it changes to "show less"
- The browser is cookied to remember their last choice

<img width="276" alt="screen shot 2017-10-11 at 3 45 25 pm" src="https://user-images.githubusercontent.com/326843/31465979-3924330a-ae9b-11e7-9325-5f24807960b9.png">

An additional possibility is that clicking on each group, like "Observables", not only loads that page but also expands that group only. Clicking on another group, like Routing, would collapse Observables and expand Routing. In that way, the titles of each group act to expand just that one group, where only one group can be expanded at a time.

If this looks/sounds good, I'd be happy to mock up a demo of what the animation would look like to get a better idea - didn't want to spend time on that tho, unless this is a good direction.

**Comment by tomgreever** [comment]
In the context of the rest of the page: 
<img width="961" alt="screen shot 2017-10-11 at 3 53 19 pm" src="https://user-images.githubusercontent.com/326843/31466308-5a5900e0-ae9c-11e7-8c78-0704d10ecc1a.png">

**Comment by chasenlehara** [comment]
I agree with the what you said about the interface being too cluttered if we also incorporate the collections.

I think it’ll be important for users to “customize” their sidebar by expanding just the sections they care about. I worry that if the only two options are to show/hide everything, then users who just really care about, say, the additional _Views_ packages will also be bogged down by everything else showing.

With regard to possible collapsing other groups when you expand one: I think one of the strengths of the current sidebar is that you can quickly switch between, say, `can-component` and `can-define` because they’re both under Core. If we start hiding groups automatically, I think it’ll be less usable.

Thank you for working on this Tom! 🙏 If you have the time, I would like to see your ideas for how we would include show/hide indicators for each group, and the animations to expand/collapse them.

**Comment by justinbmeyer** [comment]
I think we should show as many expanded groups as users pick.

**Comment by chasenlehara** [comment]
Here’s what my prototype looks like so far with the individual buttons for showing/hiding:
![sidebar prototype](https://user-images.githubusercontent.com/10070176/31527175-58f9ea4a-af80-11e7-88e6-5315eb8cfec6.gif)

**Comment by justinbmeyer** [comment]
That does seem a bit overwhelming. Maybe +/- instead of show more/show less. Or maybe go with tom’s single button.

**Comment by chasenlehara** [comment]
@adrifolio explored a bunch of ideas in these prototypes:

- http://share.bitovi.com/HC0GTL/#g=1&p=collapsible_panels_-_alpha_order&c=1 (click on More under Data Modeling)
- http://share.bitovi.com/HC0GTL/#g=1&p=collapsible_panels_-_no_alpha_order&c=1
- http://share.bitovi.com/HC0GTL/#g=1&p=collapsible_panels_-_collapsible_panels&c=1 (click on the indicator next to JS Utilities)
- http://share.bitovi.com/HC0GTL/#g=1&p=collapsible_panels_-_no_alpha_order&c=1 (collections under Routing)

This is what we settled on as the “final” design:
<img width="240" alt="screen shot 2017-10-27 at 4 20 51 pm" src="https://user-images.githubusercontent.com/10070176/32128527-406bbf44-bb33-11e7-83e1-34ee90250706.png">

🙏 Thank you to Adri and Tom for working with me on this. 🙏
