### ISSUE TITLE
Finish implementation of new sidebar

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3598]
- [x] Remove HTML from the link titles/descriptions
- [x] Display the correct “short title”
- [x] Fix support for `@hide`
- [x] Automatically expand sections when something under them is selected
- [x] Persist collapsed/expanded state
- [x] Increase the button size so it’s an easier target
- [x] Look into accessibility (do we need `aria-pressed`?)
- [x] After navigating to a page, its link should display in the sidebar’s viewport (related: https://github.com/canjs/bit-docs-html-canjs/issues/339)
- [x] Fix selecting search results when on any page other than the home page
- [x] Animate showing/hiding modules
- [x] Change the focus indicator to only show on keyboard nav
- [x] Add more spacing between Routing and CORE
- [x] Make the +/- button a consistent width (and maybe - the same width as +)
- [x] Fix an animation hiccup when closing the sections that don’t start off with Core children
- [x] Convert the purpose pages to groups
- [x] Make the collection names links
- [x] Fix the search results styling
- [x] Don’t show groups in the search results
- [x] Fix console warnings by using https://github.com/canjs/can-stache/releases/tag/v3.13.0
- [x] Show the collections as selected when they’re clicked in the sidebar
- [x] Some of the widest items in the menu are cut off on mobile
- [x] Fix the jump when expanding sections with longer titles

**Comment by chasenlehara** [comment]
@justinbmeyer @phillipskevin I still have more work to do (see the list above), but you can play around with the new sidebar here: https://bit-docs.github.io/canjs/

**Comment by phillipskevin** [comment]
Looks great. The only thing that I think would help is to make it more obvious somehow which items were added when the `+` was clicked.

I'm not sure of a good solution to this, but it is sort of jarring when new items are added above the existing ones.

**Comment by imaustink** [comment]
More issues found:
- X button in search bar not visible on mobile
- Some of the widest items in the menu are cutoff in mobile

**Comment by chasenlehara** [comment]
Implementation is finished and deployed for testing here: https://bit-docs.github.io/canjs/
