### ISSUE TITLE
Create a `can-bind` package

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#3738]
Both `can-route` and `can-stache-bindings` tie the values of two observables together.

There are a lot of pitfalls around this that would be good to explore in a single centralized package.  Example include:

- sticky values
- warning, preventing, and supporting cycles
- the queue the mutation should happen
- parent "domination"

Example:

Consider the following bindings that will create an infinite loop:

```js
var o1 = new SetObservable(0, function(newVal){
  return newVal + 1;
});
var o2 = new SetObservable(0, function(newVal){
  return newVal + 1;
});

o1.on((val) => { o2.set(val) });
o2.on((val) => { o1.set(val) });
```

I'd like to mimic `can-stache-binding`'s current behavior like:

```
var binding = canBind({
  parent: o1,
  child: o2,
  cycles: 0,
  sticky: "toChild",
  queue: "mutate",
  priority: 100
});

binding.on();
binding.off();
```

If `o1` was set to `1`, the following would happen:

1. o1 is 2, fires events
2. o2's setter called with `2` in mutate
3. o2's value is set to 3, it's events are queued
4. o2's value is checked and its setter is called with `2` again because `sticky: "toChild"`
5. o2's events are dispatched
6. o1 ignores o2s changes because `cycle: 0`

For `can-route`, I'd like some additional values to control the "setting":

```js
var binding = canBind({
  parent: hashChangeObservable,
  child: route.serialized,
  cycles: 0,
  sticky: "toChild",
  queue: "mutate",
  priority: 100,
  parentToChild: function(hash){
    canReflect.update( can.route.data, route.deparam(hash) )
  },
  childToParent: function(serialized){
    hashChangeObservable( route.param(serialized) )
  }
});
```

**Comment by chasenlehara** [comment]
@justinbmeyer How should can-bind determine whether it should one-way bind the child/parent or two-way bind? Should can-bind look for symbols on the child/parent observables, or should there be something like `shouldUpdateChild`/`shouldUpdateParent` options passed in when you initialize the binding?
