### ISSUE TITLE
Remaining 4.0 prerelease packages

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3750]
Core:

- [ ] can-route
- [ ] can-route-pushstate

Infrastructure:

- [x] can-assign
- [x] can-attribute-encoder
- [x] can-cid
- [x] can-compute
- [x] can-dom-events
- [x] can-event-dom-enter
- [x] can-event-dom-radiochange
- [ ] ~~can-make-map~~
- [x] can-parse-uri
- [x] can-types
- [x] can-util
- [x] can-validate-interface

**Comment by chasenlehara** [comment]
FYI tests are currently failing in [major](https://github.com/canjs/canjs/commits/major) because of a change in [can-stache-key 1.0.0-pre.13](https://github.com/canjs/can-stache-key/releases/tag/v1.0.0-pre.13) that’s breaking [can-stache-bindings major](https://github.com/canjs/can-stache-bindings/commits/major); @phillipskevin is going to investigate.

**Comment by justinbmeyer** [comment]
Can-event isn’t part of 4.0

**Comment by chasenlehara** [comment]
Everything checked off is now in `major`; `can-route` and `can-route-pushstate` are in the `package.json` but their tests aren’t being run because of https://github.com/canjs/canjs/issues/3760
