### ISSUE TITLE
CanJS 4.0 migration guide

### ISSUE THREAD

**Issue by James0x57** [canjs/canjs#3781]
### Changes to watch for

**Stache:**
* `%event` and other special symbols are now on `scope`
  - for example, `%event` is now `scope.event`
* can-view-scope doesn't do implicit scope walking, so change to use `../` and whatnot. Or use `{{scope.find('foo')}}`

**Routes:**
* `can.route(":page", { page: "home" });` is now `can.route("{page}", { page: "home" });`
* `can.route.ready();` is now `can.route.start();`
* `can.route()` is now `can.route.register()`

**Packages**
* `can-stache/helpers/route` is now `can-stache-route-helpers`

**Code/ViewModels**
* `can.batch.start()` is now `can.queues.batch.start()`
* `can.batch.stop()` is now `can.queues.batch.stop()`

**Comment by matthewp** [comment]
`can-stache/helpers/route` is now `can-stache-route-helpers`.

**Comment by matthewp** [comment]
can-view-scope doesn't do implicit scope walking, so change to use `../` and whatnot.

**Comment by phillipskevin** [comment]
The `.each` method has been removed from `can-define/map/map`, `can-define/list/list`, `can-map`, and `can-list`.

You should use `.forEach` or `canReflect.each` instead.

**Comment by chasenlehara** [comment]
`can-define` uses `can.keys` as the event name for when keys are dispatched instead of `__keys`

**Comment by phillipskevin** [comment]
stache's `log` helper is now `console.log` (the other `console` methods are available also).

**Comment by phillipskevin** [comment]
These will no longer automatically call `bar` as a function:
```
{{bar}}
```

```
{{#bar}}
  ...
{{else}}
  ...
{{/bar}}
```

You need to now call them manually (passing `scope.helperOptions` if you're using `options.fn` or `options.inverse`):
```
{{bar()}}
```

```
{{#bar(options.fn)}}
  ...
{{else}}
  ...
{{/bar}}
```

**Comment by chasenlehara** [comment]
can-route-pushstate should now allow the browser to open a new tab/window when the user is holding down a modifier key (e.g. control, command, etc.)

**Comment by phillipskevin** [comment]
`inserted` and `removed` events on components should be moved to `connectedCallback` and `disconnectedCallback`s on the component's ViewModel.

Or you should run this to make `inserted` and `removed` work:
```
import domEvents from "can-dom-events";
import domMutateDomEvents from "can-dom-mutate/dom-events";

domEvents.addEvent(domMutateDomEvents.inserted);
domEvents.addEvent(domMutateDomEvents.removed);
```

**Comment by matthewp** [comment]
Should we create `can-dom-mutate-events-legacy` or something that does the above?

**Comment by andrejewski** [comment]
@matthewp I would prefer a `can-3-4-compat` package that does more than add two events if there is anything else we could restore.

**Comment by matthewp** [comment]
The downside to that is it would be harder to remove the compat package if you depend on several of its internal behaviors.

**Comment by andrejewski** [comment]
We could have `can-3-4-compat/dom-mutation-events` be a module that is imported by `can-3-4-compat/index` and what not, allowing people more granularity without scattering legacy behavior across entire packages.

**Comment by matthewp** [comment]
I would favor not allowing importing `can-3-4-compat` and forcing people to import the individual things they need.

**Comment by phillipskevin** [comment]
The `default` helper can no longer be called as function.

**Comment by justinbmeyer** [comment]
@phillipskevin is it possible to make `{{default()}}` still work?

**Comment by justinbmeyer** [comment]
DefineMap's `value` behavior should now be called `default`.

**Comment by matthewp** [comment]
`can.route.deparam(routeString)` no longer includes a `.route` property when there is a matching route.

**Comment by matthewp** [comment]
can-view-model no longer uses domData to get an element's viewModel. Instead it uses the `can.viewModel` symbol.

**Comment by matthewp** [comment]
Are there any uses cases for keeping can-event in a project @justinbmeyer @phillipskevin? I think everything it did is covered by can-queues.batch and can-event-queue, right?

**Comment by matthewp** [comment]
@chasenlehara @phillipskevin @m-mujica @justinbmeyer Here is the first version of the migration guide: https://canjs.github.io/next/doc/migrate-4.html . You can leave feedback here and I'll update in a PR.

**Comment by phillipskevin** [comment]
Some comments from reviewing the guide:

1. We might want to mention that not all ecosystem packages have been updated to 4.0. Especially if using the `can` package, it might not be super easy to tell if everything you're using has a 4.0 version. Maybe we have people check the site for the packages they're using. Or we could give a list of what has not been updated.

2. In the inserted/removed event section, this sentence reads a little strange:

> Most if what was done in the inserted event can be replaced in places like value.

3. The `connectedCallback` is only on the ViewModel (pretty sure).

```
Component.extend({
    connectedCallback: function(){
```

should be

```
Component.extend({
    ViewModel: {
        connectedCallback: function(){
        }
    }
```

4. I think this is a typo:

>In can-define 1.0, you would default a default value for a property

**Comment by justinbmeyer** [comment]
I have been thinking if we should call connected callback on both the component and the VM.  Sometimes I feel like it makes more sense on the component.

**Comment by justinbmeyer** [comment]
> Unlike previous versions of CanJS, in CanJS 4 there are a mixture of different package versions. This is because CanJS is now developed as separate independent packages.

Was this not true for 3.0? `can-define` was 1.0 for can@3.0.

> Use can-queues instead of can-event

`can-queues` replaces most closely `can-event/batch/batch`.

If you were using `can-event`, then you likely want to use `can-event-queue/map/map`.  

I actually think `can-event-queue/map/map` is the best thing to use at first.  It includes `.start()` and `.stop()` and other old `can-event/batch/batch` methods: 

https://github.com/canjs/can-event-queue/blob/master/map/map.js#L821

These warn, but fix those later ...

> Implicit scope walking  

I think this section should tell people that upgrading to the latest 3.0 will warn them of where they are using implicit scope walking.

**Comment by matthewp** [comment]
@justinbmeyer 

> Was this not true for 3.0? can-define was 1.0 for can@3.0.

No, can-define was not part of CanJS 2.3, so it wasn't part of the migration guide.

**Comment by phillipskevin** [comment]
@matthewp there are a few things missing from the migration guide:

* `.each` is removed from our Map and List types and you need to use `.forEach` (https://github.com/canjs/canjs/issues/3781#issuecomment-351097925)
* functions are not automatically called by stache without `()` (https://github.com/canjs/canjs/issues/3781#issuecomment-351837669)

Do you want me to add these? Or do you want to take care of it?

**Comment by matthewp** [comment]
I'll get it, thanks for the notes!

**Comment by matthewp** [comment]
@phillipskevin what was the reason for `.each` being dropped? Was it that it conflicted with something else?

**Comment by phillipskevin** [comment]
stache lookups will now check the context before checking helpers, so `{{#each(list)}}` would have called `list.each` instead of the `each` helper.

**Comment by phillipskevin** [comment]
About https://github.com/canjs/canjs/issues/3781#issuecomment-357727911 - I'm going to try to get `{{#default()}}` working today so we don't have to explain/codemod this.

**Comment by matthewp** [comment]
These are all added to https://canjs.github.io/next/doc/migrate-4.html
