### ISSUE TITLE
Update jsbins/code in recipes and guides to 4.0

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#3782]
cc @James0x57 

* [x] - ATM Guide @James0x57 
* [x] - Chat Guide @James0x57 
* [x] - Credit Card Guide (Simp) @James0x57 
* [X] - CTA Bus Route @matthewp
* [X] - File Navigator @matthewp
* [X] - Playlist Editor @matthewp
* [X] - Signup and Login @matthewp
* [X] - TodoMVC with Steal @matthewp
* [x] - Weather Report Guide @James0x57

-----------

If they rely on **streams**, they will be hidden for now. This issue will track those:
https://github.com/canjs/canjs/issues/3789

**Comment by James0x57** [comment]
Closing because all are done and pushed now.
Remaining ones are hidden and listed in #3789 because they rely on Streams.
