### ISSUE TITLE
Check the demos for 4.0

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3793]
- Update any in 3.0 that are using old/deprecated syntax
- Remove any that are no longer used
- Make sure demos are working in 4.0 site

**Comment by matthewp** [comment]
Which demos? @James0x57 and I did the recipes and TodoMVC and that sort of thing.

**Comment by chasenlehara** [comment]
There are also demos in all the individual packages that need to be checked.

**Comment by justinbmeyer** [comment]
I don't know if many packages have demos that are actually shown in the docs.  The `demos` folder is the most important one here.

**Comment by chasenlehara** [comment]
This was completed with these PRs:

- https://github.com/canjs/canjs/pull/3799
- https://github.com/canjs/canjs/pull/3800
- https://github.com/canjs/canjs/pull/3803
- https://github.com/canjs/canjs/pull/3804
- https://github.com/canjs/canjs/pull/3805
- https://github.com/canjs/canjs/pull/3806
- https://github.com/canjs/canjs/pull/3807
- https://github.com/canjs/canjs/pull/3811
- https://github.com/canjs/canjs/pull/3812
