### ISSUE TITLE
Make documentation able to document "mixins" and inheritance.  

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#3797]
Many parts of CanJS "mixin" behaviors from other places.  It would be useful if there was a way to document this behavior.

```js
@module {function} can-define/map/map
@mixin can-event-queue/map/legacy/legacy 
``` 

I'm not sure how this should show up in the UI.

**Comment by chasenlehara** [comment]
This is a dupe of https://github.com/canjs/canjs/issues/3008
