### ISSUE TITLE
Improve the Setting Up CanJS page

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3841]
- [x] Create GitHub repos for each of the main ways to set up CanJS (steal, webpack, etc.)
- [x] Add links to those GitHub repos to the Setting Up CanJS page
- [x] Include a simple example of using can-component? Maybe this should just be in the repos?

**Comment by christopherjbaker** [comment]
1 and 2 are done.

there are PRs for 3, but they depend on canjs/can-component#219
* canjs/browserify-example#2
* canjs/webpack-example#2
* canjs/stealjs-example#2
