### ISSUE TITLE
Use const/let in sample code

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3846]
It’d be nice for all of the code in our guides and core APIs to show const/let; extra points for having _all_ of our example code show const/let instead of var.

Note that this is not talking about the source code, where we intend to continue using what’s supported by the browsers we support.

**Comment by christopherjbaker** [comment]
The following PRs have been opened:
* https://github.com/canjs/can-define-list/pull/2
* https://github.com/canjs/can-connect/pull/408
* https://github.com/canjs/can-set/pull/85
* https://github.com/canjs/can-vdom/pull/44
* https://github.com/canjs/can-validate/pull/71
* https://github.com/canjs/can-observe/pull/46
* https://github.com/canjs/can-fixture/pull/146
* https://github.com/canjs/can-zone/pull/163
* https://github.com/canjs/can-define/pull/317
* https://github.com/canjs/can-view-href/pull/47
* https://github.com/canjs/can-util/pull/415
* https://github.com/canjs/can-compute/pull/128
* https://github.com/canjs/can-component/pull/222
* https://github.com/canjs/can-construct/pull/54
* https://github.com/canjs/can-route/pull/155
* https://github.com/canjs/can-event/pull/76
* https://github.com/canjs/can-stache-bindings/pull/430
* https://github.com/canjs/can-view-callbacks/pull/82
* https://github.com/canjs/can-view-import/pull/100
* https://github.com/canjs/can-view-nodelist/pull/44
* https://github.com/canjs/can-view-parser/pull/89
* https://github.com/canjs/can-view-scope/pull/150
* https://github.com/canjs/can-view-target/pull/61
* https://github.com/canjs/can-observation/pull/126
* https://github.com/canjs/can-stache/pull/465
* https://github.com/canjs/can-view-model/pull/63
* https://github.com/canjs/can-route-pushstate/pull/87
* https://github.com/canjs/can-connect-feathers/pull/105
* https://github.com/canjs/can-simple-map/pull/60
* https://github.com/canjs/can-stream-kefir/pull/64
* https://github.com/canjs/can-stache-converters/pull/80
* https://github.com/canjs/can-define-stream/pull/60
* https://github.com/canjs/can-fixture-socket/pull/61
* https://github.com/canjs/can-define-backup/pull/7
* https://github.com/canjs/can-validate-validatejs/pull/21
* https://github.com/canjs/can-connect-signalr/pull/37
* https://github.com/canjs/can-zone-storage/pull/14
* https://github.com/canjs/can-define-stream-kefir/pull/28
* https://github.com/canjs/can-define-validate-validatejs/pull/48
* https://github.com/canjs/can-parse/pull/7
* https://github.com/canjs/can-element/pull/49
* https://github.com/canjs/can-connect-cloneable/pull/19
* https://github.com/canjs/can-ndjson-stream/pull/30
* https://github.com/canjs/can-connect-ndjson/pull/14
* https://github.com/canjs/can-symbol/pull/25
* https://github.com/canjs/can-reflect/pull/101
* https://github.com/canjs/can-migrate/pull/69
* https://github.com/canjs/can-param/pull/9
* https://github.com/canjs/can-stream/pull/13
* https://github.com/canjs/can-global/pull/2
* https://github.com/canjs/can-is-browser-window/pull/1
* https://github.com/canjs/can-globals/pull/40
* https://github.com/canjs/can-stache-animate/pull/47
* https://github.com/canjs/can-validate-interface/pull/12
* https://github.com/canjs/can-make-rest/pull/17
* https://github.com/canjs/can-dom-mutate/pull/29
* https://github.com/canjs/can-stache-key/pull/27
* https://github.com/canjs/can-debug/pull/39
* https://github.com/canjs/can-attribute-encoder/pull/16
* https://github.com/canjs/can-kefir/pull/15
* https://github.com/canjs/can-test-helpers/pull/11
* https://github.com/canjs/can-queues/pull/14
* https://github.com/canjs/can-jsx/pull/7
* https://github.com/canjs/can-compute-memoize/pull/10
* https://github.com/canjs/can-key-tree/pull/10
* https://github.com/canjs/can-simple-observable/pull/19
* https://github.com/canjs/can-define-lazy-value/pull/4
* https://github.com/canjs/can-event-queue/pull/16
* https://github.com/canjs/can-observation-recorder/pull/6
* https://github.com/canjs/can-stache-route-helpers/pull/4
* https://github.com/canjs/can-reflect-dependencies/pull/14
* https://github.com/canjs/can-reflect-tests/pull/7
* https://github.com/canjs/can-stache-helpers/pull/3
* https://github.com/canjs/can-define-map/pull/1

**Comment by chasenlehara** [comment]
This has not been finished.
