### ISSUE TITLE
Consider making the can package the recommended way of using CanJS

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#3849]
This was mentioned in a [forum post by Justin](https://forums.donejs.com/t/lets-embrace-chaos-and-make-division-easy/786) and came up during our usability study; users are sometimes confused and intimidated by the number of packages needed to get started with CanJS. Additionally, our guides typically use the `can` package because they use JS Bin, but we explicitly tell people that’s not how they should build apps, which creates a disparity between how we show CanJS vs. how we want people to use it.

This issue is for more thoroughly considering the above problems and enumerating potential solutions. Note that this is _not a proposal_ for anything in particular, but a starting point for our conversation.

**Comment by frank-dspeed** [comment]
I think the current module way is great we could simply write tutorials about how to compile a custom canjs can version or how to use can global namespace stuff to get a can object. 

That means we change near nothing but make clear how the can.* gets build. Then we Also introduce can.all as the general way to use canjs and in donejs we introduce the modules.  and reference there how they could get a global can.* from the modules

then stealjs tree shaking can strip down the main canjs build to only the used functions in production builds.

**Comment by frank-dspeed** [comment]
i think a new can.all plus can.Component alone in tutorials is a nice reduction from using stache and defineMap for basic examples

**Comment by chasenlehara** [comment]
We’ve done this as of CanJS 5.
