### ISSUE TITLE
CodeMods for CanJS 4.0 Migration Guide

### ISSUE THREAD

**Issue by Sinjhin** [canjs/canjs#3857]
**Stache:**

- [x] %event and other special symbols are now on scope
for example, %event is now scope.event
- [ ] can-view-scope doesn't do implicit scope walking, so change to use ../ and whatnot. Or use {{scope.find('foo')}} 
- [x] functions are now called with () in stache like `{{myFunc()}}`. We need to at least get a codemod for the built-in helpers. (This still works with no parens for built-in and registered helpers, we are just going to document the why and how on the migration guide and not make a codemod)
- [x] `{{log}}` to `{{console.log(this)}}` seems easy.
- [x] Properties like `prop="value"` no longer set an attribute on the viewModel and need to be changed to `prop:from="value"` if they are not built-in things like `style` or `id`

**Routes:**
- [x] `can.route(":page", { page: "home" });` is now `can.route("{page}", { page: "home" });`
- [x] `can.route.ready();` is now `can.route.start();`
- [x] `can.route()` is now `can.route.register()`

**Packages**
- [x] `can-stache/helpers/route` is now `can-stache-route-helpers`

**Code/ViewModels**
- [x] `can.batch.start()` is now `can.queues.batch.start()`
- [x] `can.batch.stop()` is now `can.queues.batch.stop()`
- [x] `.each()` was removed from Maps and Lists and replaced by `.forEach()` **(In progress: John)**

**Components**
- [X] `inserted` and `removed` have been removed from a components events object (Not easy or maybe even possible with a codemod)

Will continue to add more from https://github.com/canjs/canjs/issues/3781 as I get through these.

- [x] - Release new version 1.0.0 of can-migrate.
- [X] - Release new version 2.0.0 of can-migrate.

**Comment by matthewp** [comment]
Couple of other nice-to-haves:

* [ ] `{{log}}` to `{{console.log(this)}}` seems easy.
* [ ] - `DefineMap.extend({ prop: { value: 'foo' } })` to `DefineMap.extend({ prop: { default: 'foo' } })`. Seems a little hard, can't just assume that we can replace any instead of `value:`, would want to check when explicitly extending a definemap.

**Comment by chasenlehara** [comment]
I don’t think we have any codemods for the recent stache syntax deprecations, e.g. `prop="{prop}"` => `prop:bind="prop"`

**Comment by Sinjhin** [comment]
These are all closed with versions 2.0.0 - 2.0.4 of `can-migrate`

A new issue has been created for lack of implicit scope walking https://github.com/canjs/can-migrate/issues/72
