### ISSUE TITLE
CanJS Release Article

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#3907]
Process:

- I have just been editing raw html.  I edit the source code in my atom editor (not the hubspot text area).
- I paste that into <img width="764" alt="edit_blog_post___canjs_4_0" src="https://user-images.githubusercontent.com/78602/35569733-8b68107a-0592-11e8-98ef-aa5e153df7e7.png">

Things that need to be done:

- [x] - Link outline to sections.  I've already set this up for `Community Driven Development`.  <img width="692" alt="canjs_4_0" src="https://user-images.githubusercontent.com/78602/35569820-dcefd52c-0592-11e8-9abd-c51fc6df670f.png"> The outline titles should link to the sections in the main body of the article.  Unfortunately, hash-linking to the `<h2>` or `<h3>` sections won't work as the titles will be covered. Instead, I put an `id` on the paragraph (`<p>`) before the title.
- [ ] - Make sure links point to `canjs.com` (not `canjs.github.io/next`) urls.  There are MANY missing links in this article.  I didn't put in links because we didn't have the final URLS anyway.  In some places I underlined (`<u>`) text to remind myself I wanted a link there.  Someone needs to go through after the 4.0 canjs.com site is published and make sure everything is linked nicely.
- [x] - Picture of community survey
- [x] - Debugging JSBIN
- [x] - Queues `DEMO`: https://github.com/canjs/can-queues/blob/master/demos/domUI-performance.html
- [x] - Stuff like `NOTE: This demo` should be `<blockquote>`
- [ ] - Image of code mod -> terminal running code-mod

**Comment by Sinjhin** [comment]
Here is a gif to use for showing `can-migrate`:

![can-migrate-to-4](https://user-images.githubusercontent.com/1085104/35642233-20c5a83a-0688-11e8-8274-7cf191d89031.gif)

**Comment by justinbmeyer** [comment]
Might be useful to link to these proposals:

<img width="498" alt="canjs_4_0" src="https://user-images.githubusercontent.com/78602/35687197-b25a243c-0733-11e8-8d0c-8d9629d27e4c.png">

**Comment by matthewp** [comment]
@Sinjhin couple of notes on the gif:

1. Do you think you could do it again without the install? I don't think that's necessary since we go over that in the guide and it makes the video longer. I think just typing the command and then running it and then doing a quick  `git diff` would be a good length of time.
2. I notice there's some parser errors shown. Do you know what those are about? Any chance you could make those go away?

**Comment by justinbmeyer** [comment]
=====

> This has shifted our focus to things that matter to users.

To:

This has shifted our focus to what matters most to users.

=====

> Division was nearly impossible with roman numerals, but it's easy with decimal numbers that we use today

Should link to: https://www.washingtoncitypaper.com/columns/straight-dope/article/20854121/how-did-anyone-do-math-in-roman-numerals

**Comment by matthewp** [comment]
This was released.
