### ISSUE TITLE
Issue with can-slot and if/else blocks in 4.0

### ISSUE THREAD

**Issue by roemhildtg** [canjs/canjs#3929]
https://jsbin.com/xexeboviko/1/edit?html,js,output

I''m not sure what the exact issue is here, but when you click the button, a queue batch gets run from the data.assign and the node doesn't get removed in the `{{else}}node{{/if}}` block throwing an error that breaks stache. 

It happens in `can-slot` when there is an if/else block that gets rendered, then removed.

**Comment by roemhildtg** [comment]
This also happens with `{{#with()}}`. Probably all branching logic:

https://jsbin.com/sitepaxazu/edit?html,js,output

**Comment by justinbmeyer** [comment]
I’ll try to take a look over the weekend

**Comment by justinbmeyer** [comment]
As a temporary work around, you can put a `<div>` or some other element directly within your `<can-template>` tag like:

```
<can-template name="stuff">
<div> .... </div>
</can-template>
```

**Comment by justinbmeyer** [comment]
Here's a jsbin that shows the issue a bit nicer: https://jsbin.com/nixiwib/1/edit?html,js,output

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-component #220](https://github.com/canjs/can-component/issues/220) via [**ZenHub**](https://www.zenhub.com/)
