### ISSUE TITLE
Model store doesn't update instances

### ISSUE THREAD

**Issue by ccummings** [canjs/canjs#40]
A model instance in the model store will not be updated if a modified version is retrieved using findOne or findAll.

Model instance in model store:

``` js
{
  id: 1,
  name: 'CanJS',
  version: '1.0b2'
}
```

Model instance on server:

``` js
{
  id: 1,
  name: 'CanJS',
  version: '1.0'
}
```

findOne for {id: 1} will return:

``` js
{
  id: 1,
  name: 'CanJS',
  version: '1.0b2'
}
```

The model store does not get updated with the new attributes so findOne resolves the deferred with the stale version from the store.

Need to update the instance in the store with the new attributes in [model.js](https://github.com/jupiterjs/canjs/blob/master/model/model.js#L738)

**Comment by neildcruz19** [comment]
Was this ever fixed for array attributes? I seem to be facing the same issue even in the latest version.

**Comment by justinbmeyer** [comment]
Use the define plugin to handle merging.  You can create a setter that does merging however you would like.
