### ISSUE TITLE
Bug: 404 url in Setting up CanJS documentation

### ISSUE THREAD

**Issue by haestflod** [canjs/canjs#4006]
The first link for the heading `Building for production`
https://canjs.com/doc/guides/setup.html#Buildingforproduction

The link `Moving to Production` is linking to an url returning 404.
https://stealjs.com/docs/StealJS.moving-to-prod.html

**Comment by justinbmeyer** [comment]
Thanks!

**Comment by chasenlehara** [comment]
This was fixed in https://github.com/stealjs/stealjs/commit/bb861ac27321041f5dff3e461955f3b22d9e24bd by @matthewp, thanks!
