### ISSUE TITLE
Formatting for can-define 'value' documentation is incorrect -- making it difficult to read

### ISSUE THREAD

**Issue by mjstahl** [canjs/canjs#4036]
Reference URL:
https://canjs.com/doc/can-define.types.value.html

Screenshot:
<img width="1012" alt="screen shot 2018-03-12 at 09 13 43" src="https://user-images.githubusercontent.com/212726/37285705-3acb36f6-25d6-11e8-8a5e-311190947ce9.png">

**Comment by justinbmeyer** [comment]
This has been fixed, just not published.
