### ISSUE TITLE
Migrated to canjs4, now on:enter stopped working?

### ISSUE THREAD

**Issue by MarcGodard** [canjs/canjs#4064]
Hello, I migrated my app to use all the latest from canjs and my events for on:enter no longer seem to be firing on enter.

Not sure how much more info I can give.

**Comment by justinbmeyer** [comment]
You have to include the enter event manually:

https://canjs.com/doc/can-event-dom-enter.html

You can actually just import this module:

https://github.com/canjs/can-event-dom-enter/blob/master/add-global/add-global.js

And it will add the event to the global registry. 

I think the compat package does this.

I’ll update the migration guide to show how to do this.

**Comment by justinbmeyer** [comment]
Keeping open until its part of the migration guide and the `add-global` module is documented.

**Comment by matthewp** [comment]
This is in the migration guide now, add-global docs are here: https://canjs.com/doc/can-event-dom-enter/add-global/add-global.html
