### ISSUE TITLE
Unable to model destroy with parameter

### ISSUE THREAD

**Issue by r0m4n** [canjs/canjs#4082]
Hey,

I'm running into an issue on a relatively basic canjs model destroy.

```
(function() {
  console.log(can);
  var myModel = can.Model.extend({
    destroy: function(id) {
      console.log(id, '... destroy');
    }
  });
  
  var test = can.Control.extend({
    init: function() {
      console.log('init');
      this.element.append('test');
      myModel.destroy(1);
    }
  });
  new test('#someComp')
}());
```
https://jsfiddle.net/r0m4n/zym4hves/

This results in the following error: Uncaught TypeError: instance.serialize is not a function

I'm working through upgrading a project from Can v1 to v3 and have read all the migration documentation. Nothing I could locate about changes to can-model up to v4...

**Comment by chasenlehara** [comment]
Hi @r0m4n, I know that you’re using the [can-connect/can/model/](https://v3.canjs.com/doc/can-connect/can/model/model.html) module in the JSFiddle; in your actual project, are you using that or [can-model](https://www.npmjs.com/package/can-model)?

I wouldn’t expect the `can-model` package to have this issue, but it does look like one of the differences between it and `can-connect/can/model/` is that the latter requires an instance be passed to it.

**Comment by r0m4n** [comment]
A similar bundle to that of the one in the jsfiddle so it must be the can-connect/can/model/ module. From what I read in the docs, the whole point of that module is to be backwards compatible so I included it in our bundle... 

We were using the destroy as a custom function that performed a few api calls so we may just be better off moving away from the can-model "destroy" and just call it something else to avoid the serialize. We may have been using the model destroy in a non standard way...

**Comment by r0m4n** [comment]
ah you are right @chasenlehara, including can-model and not can-connect fixed the issue. Didn't realize they are being maintained separately (and work differently)

**Comment by phillipskevin** [comment]
Going to close this. Please re-open if there is anything that we could do to make this more obvious.

**Comment by r0m4n** [comment]
I think the issue is that can-connect/can/model breaks backwards compatibility and the first sentence in the documentation says "can-connect/can/model is for backwards compatibility with can.Model"

https://v3.canjs.com/doc/can-connect/can/model/model.html

**Comment by justinbmeyer** [comment]
Calling destroy like is happening here is not documented in old canjs, and therefore not supported in new releases. So can-connect/can/model is not breaking comparability of documented features.

**Comment by justinbmeyer** [comment]
Also, the goal of can-connect/can/model is to provide a high level of compatibility, but not perfect compatibility. It’s unlikely can-model will be supported forever. can-connect/can/model is an “easy” way to support old Model code.

**Comment by r0m4n** [comment]
Isn't it the same as this?

https://v2.canjs.com/1.1/docs/can.Model.destroy.html

Implement destroy with a function like:
```
Recipe = can.Model.extend({
  destroy : function(id){
    return $.post("/recipe/destroy/"+id,{});
  }
},{})
```

Ok that's ok. I think I will be able to get our project running with the module mentioned above without too much work. At some point it will have to be rewritten. Just thought I would mention it for anyone else that runs into a similar issue. Thanks for the help above

**Comment by justinbmeyer** [comment]
@r0m4n To be clear, I'm talking about __calling__ destroy directly on the model like:

```js
myModel.destroy(1)
```

That is not supported.  Afaik, being able to call this like this is not documented. 

__Defining/implementing__ a destroy method like:

```js
Recipe = can.Model.extend({
  destroy : function(id){
    return $.post("/recipe/destroy/"+id,{});
  }
},{})
```

Is supported (or at least should be) by `can-connect/can/model`.  Are you having problems with defining the `destroy` method like as shown in the v2 docs?

**Comment by justinbmeyer** [comment]
btw, the following might work as a fallback:

```js
myModel.destroy(new myModel({id: 1}));
```

Good luck with the upgrade.  Keep posting questions and we will do our best to assist.
