### ISSUE TITLE
Make can/can an ES module

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#4090]
This is for canjs 5.0.  Move what is `can/es` in can 4.2 to `can/can`, which is the main. This makes can an ES module by default.

**Comment by matthewp** [comment]
# ES module options

The goal here is to make it possible to import parts of can from a single import statement, like so:

```js
import { Component } from 'can';
```

The question this issue is trying to resolve is:

* What should `can` consist of? Everything or just core?

## Option A: Retain separate can and can/all (and can/ecosystem) modules

If we make `can` only contain core, then it's everything that people are most likely loading in their apps today anyways.

__Advantages__

* Prevents loading a bunch of stuff you are likely not using.

__Disadvantages__

* Important, but not core packages like `can-connect` would not be included, so you would need to do `import { connect } from 'can/all';` to get it.

## Option B: Bundle all of can together

If we were to create an ES module bundle that contains all of there's less concern about load times.

__Advantages__

* Only 1 file to load for can prevents waterfalls.

__Disadvantages__

* Added complexity when developing `can`, should you be building all of the time?
* `can/all` is quite large so the bundle itself could be quite large.
* stealjs/transpile doesn't currently support transpiling to ES modules, so this would have to be added first.

**Comment by justinbmeyer** [comment]
Another summary of this choice.  There are two dimensions:

- _bundle_ vs _import/export_
  - import/export - `can`'s `main` module will import sub packages and export them.
  - bundle - `can`'s `main` module contains code from other packages.
- _core_ vs _core+ecosystem_
  - `can`'s `main` module exports only the core and infrastructure packages
  - `can`'s `main` module exports core and the ecosystem pacakges

## Bundle Core

## Bundle Core+Ecosystem 

## Import/Export Core 

## Import/Export Core+Ecosystem

**Comment by matthewp** [comment]
Update, we are attempting to go the import/export core+ecosystem route. For bundlers with tree shaking this doesn't present much of an issue. It does present an issue for steal. So to start I'm going to spend a little time trying to implement https://github.com/stealjs/steal/issues/1381

**Comment by matthewp** [comment]
This is in major now.
