### ISSUE TITLE
Please ! A bug in the API !!!!!(url:https://canjs.com/doc/can-compute.html)

### ISSUE THREAD

**Issue by xu-oliver** [canjs/canjs#4092]
Oh my GOD! The 'Translator computes' third Demo , wallLengthInMeters function to compute is error !

**Comment by phillipskevin** [comment]
You just mean that the calculation is reversed? It should be

```
const wallLengthInMeters = compute( function( lengthInM ) {
    if ( arguments.length ) {
        wall.length = lengthInM * 3.28084;
    } else {
        return wall.length / 3.28084;
    }
} );
```

You can click the "Edit on GitHub" button at the top of the page to update the example if you'd like to update it:
![image](https://user-images.githubusercontent.com/5851984/38311098-f3034208-37e3-11e8-92ae-ce3395da5d3f.png)

**Comment by xu-oliver** [comment]
thanks~
