### ISSUE TITLE
CanJS 4 doesn't work properly in `IE11` due to unsupported JS functionality.

### ISSUE THREAD

**Issue by Lighttree** [canjs/canjs#4100]
This is reproducible in `IE11` (assume IE 9 - 11 as well)

Without polyfills:
`CanJS` code throwing issues due to missed `Object` functionality.
`Object.assign is not a function`

With [Core JS](https://github.com/zloirock/core-js) (tried different versions) polyfills you need to add `Object`, `Weak Set`, `Map` polyfills to avoid some issues, but finally fall into:
`Incompatible receiver, map required!`
I wasn't able to fix this using any other polyfill.

With [Babel-polyfill](https://babeljs.io/docs/usage/polyfill/) I fall into
`Incompatible receiver, map required!` - instantly
Because `Babel-polyfill` uses `Core JS` internally and enables all required polyfills at once.

Reproducible in newly created `Done JS 2` app.

If I run `babel-loader` (I'm using `Webpack`) over `CanJS` source code it throws another issue:
`Invalid calling object` here:
https://github.com/canjs/can-dom-mutate/blob/master/can-dom-mutate.js#L65

Some logs:
https://hastebin.com/raw/oricomajak
https://hastebin.com/raw/qesivazazo

**Comment by justinbmeyer** [comment]
So these errors happen while CanJS is loading?  Can you give more details about how you set this up?  Do you have a repo we can clone?  Thanks!

**Comment by Lighttree** [comment]
@justinbmeyer 

Sure, just run this project for development and open in `IE11`:
https://github.com/Lighttree/ie11-canjs-demo

**Comment by rjgotten** [comment]
@Lighttree 
There's apparantly a bug in CoreJS 2.5.3 with IE 11 which always results in `Incompatible receiver, map required!` when using `Set` or `Map`. Have you tried pinning the version to 2.5.2 ?

See also: https://github.com/zloirock/core-js/issues/368

**Comment by chasenlehara** [comment]
I think this can be closed now. 😊 https://canjs.com/doc/guides/setup.html#IE11Support
