### ISSUE TITLE
Swipe Carousel Recipe

### ISSUE THREAD

**Issue by MrSocom** [canjs/canjs#4108]
## Goal 

- Create a Tinder-like Swipe Carousel recipe for the [May 23rd DoneJS meetup](https://www.meetup.com/DoneJS-Chicago/events/249715742/)

![image](https://user-images.githubusercontent.com/22969581/38703841-004a302a-3e6a-11e8-8e64-c01fef838cd3.png)

- People like canjs (not confusing)

### Week 1

- Finalize design
- [Playlist Editor](https://canjs.com/doc/guides/recipes/playlist-editor.html)
- JSBin, __JSFiddle__, CodePen, which is best for mobile demos.
  - Can you remove the `version` and it look good on mobile? Ex: https://output.jsbin.com/qeguhac Does it automatically update if someone edits?

- __JSFiddle__ lets users collaborate and see live preview on mobile devices, but the UI experience isn't the best 
- __CodePen__ does not have collaboration, does have live preview,  has a better UI experience 

### Week 2

- figure out how to add event handlers that take arguments.
- Make swipe work
  - build our own swipe
  - port jQuery++'s swipe to CanJS: https://github.com/bitovi/jquerypp/blob/master/event/swipe/swipe.js ?

### Week 3

- OBJECTIVE: Rough draft of example

### Week 4

- OBJECTIVE: Get example styled
- OBJECTIVE: Build the final code example

### Week 5

- OBJECTIVE: Write up the tutorial

### Week 6

- OBJECTIVE: Deliver tutorial

**Comment by justinbmeyer** [comment]
![dalek](https://user-images.githubusercontent.com/78602/40454672-566b4984-5eaf-11e8-808d-cb5afd445e89.jpg)

![darth](https://user-images.githubusercontent.com/78602/40454681-59cffdb8-5eaf-11e8-94ac-4849ab08d90c.jpg)
![hannibal](https://user-images.githubusercontent.com/78602/40454689-6343b6f0-5eaf-11e8-8dc6-a7fd0d8bfab3.jpg)

![gru](https://user-images.githubusercontent.com/78602/40454685-5cab196e-5eaf-11e8-87ac-4af6792994ed.jpg)

![hannibal](https://user-images.githubusercontent.com/78602/40454705-6bf4d3d8-5eaf-11e8-9562-2bd178485527.jpg)


![norman](https://user-images.githubusercontent.com/78602/40454709-6fecc536-5eaf-11e8-9eb5-3da39730adc4.jpg)

![venom](https://user-images.githubusercontent.com/78602/40454716-76bef438-5eaf-11e8-9d29-5002260e96e1.jpg)

![stapuft](https://user-images.githubusercontent.com/78602/40454711-72b19d78-5eaf-11e8-9732-80155ff8bb52.jpg)

![wickedwitch](https://user-images.githubusercontent.com/78602/40454720-7c3d984c-5eaf-11e8-9fa7-f68ddd33e3f0.jpg)

![zod](https://user-images.githubusercontent.com/78602/40454722-802ef694-5eaf-11e8-8964-ca648368720d.jpg)

**Comment by phillipskevin** [comment]
This is done. Nice work. What a cool guide!
