### ISSUE TITLE
would you tell me which version is compatible with IE8

### ISSUE THREAD

**Issue by zhanghengxin** [canjs/canjs#4120]
would you tell me which version is compatible with IE8
please~

**Comment by zhanghengxin** [comment]
which version support the IE8 or lower

**Comment by zhanghengxin** [comment]
@tdreyno @leemhenson @arijo @schovi @obaid ,i'm so sorry , but i not find it

**Comment by chasenlehara** [comment]
Hi @zhanghengxin, CanJS 2 supports IE8+ and CanJS 3 supports IE9+ (with a Promise polyfill).

You can find the CanJS 2 docs here: https://v2.canjs.com/
