### ISSUE TITLE
Syntax highlighting for can-reflect is broken

### ISSUE THREAD

**Issue by imaustink** [canjs/canjs#4165]
Most of `can-reflect`'s pages in the docs don't have syntax highlighting for the examples.

https://canjs.com/doc/can-reflect/observe.offKeyValue.html

**Comment by justinbmeyer** [comment]
Issue moved to [canjs/can-reflect #111](https://github.com/canjs/can-reflect/issues/111) via [**ZenHub**](https://www.zenhub.com/)
