### ISSUE TITLE
canjs.com's state-management link isn't helpful

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#4171]
it should link to tech overview

**Comment by phillipskevin** [comment]
@justinbmeyer is this closed now?

This link:

![image](https://user-images.githubusercontent.com/5851984/49036333-07457a80-f17d-11e8-8f17-267fa1461f04.png)

...now links to https://canjs.com/doc/guides/technology-overview.html#Key_ValueObservables.
