### ISSUE TITLE
CanJS 5.0 Migration Guide

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#4184]
- [x] use `updateInstanceWithAssignDeep: true`
- [x] use `can-query-logic` instead of `can-set`
- [x] add `{identity: true}`
- [x] create a List type
- [ ] Document set.props.ignore

**Comment by matthewp** [comment]
* [ ] - Use `{ filter: query }` with `getList()`.

**Comment by matthewp** [comment]
This is done: https://canjs.github.io/next/doc/migrate-5.html
