### ISSUE TITLE
can.Model.Queue disables 'defaults' functionality of can.Observe.attributes

### ISSUE THREAD

**Issue by taai** [canjs/canjs#420]
I'm using automatically packed version from canjs.com -> customize... This problem occurs in version 1.1.6.

It's nice that plugin ```can.Observe.attributes``` gives me an option to define ```defaults``` which are automatically set on my Models.

Sadly the plugin ```can.Model.Queue``` disables it.

I made two examples.
**without** can.Model.Queue (good): http://jsbin.com/olitit/2/edit
**with** can.Model.Queue (bad): http://jsbin.com/ijojep/2/edit

The code that I need to work:
```javascript
var Car = can.Model({ defaults: { wheels: 4, color: 'red' } }, {});
var mycar = new Car();
console.log(mycar.attr());
// -->  {"wheels":4,"color":"red"}
```

Please fix that!

**Comment by justinbmeyer** [comment]
I'm closing this as queue isn't heavily used and it's not in can-connect.
