### ISSUE TITLE
Add ways to enable side-effectual packages

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#4202]
We have several side-effectual packages that would get removed in tree-shaking.

* can-stache-converters
* can-stache-route-helpers
* can-route-pushstate
* can-stache-bindings

We need a way for the user to import these packages and use them, so that they are not tree-shaken.  Could be something like:

```js
import { stache, stacheBindings } from "can";

stache.addBindings(stacheBindings);
```

We need to figure out a way for all of our side-effectual packages.

For helpers we can change `stache.addHelper` to accept an object of multiple helpers.

```js
import { stacheRouteHelpers } from "can";

stache.addHelper(stacheRouteHelpers);
```

**Comment by matthewp** [comment]
can-debug is another: https://github.com/canjs/can-debug/issues/46

**Comment by matthewp** [comment]
To register side-effectual helpers you would do:

```js
import { stacheRouteHelpers, stache } from "can-stache";

stache.addHelper(stacheRouteHelpers);
```

However, we have several examples that import these into the templates like so:

```handlebars
<can-import from="can-stache-route-helpers" />
```

So the question is:

1. Should can-stache-route-helpers be self-registering itself?
2. If not where would the registration happen?

**Comment by justinbmeyer** [comment]
@matthewp (cc @phillipskevin ) I feel like we are now forced to implement the "special" imports.  I think there's issues around this, but they would look like this:

```
<can-import from="can-stache-route-helpers" value:to="scope.helpers"/>
```


```
<can-import from="can-dom-events-enter" value:to="scope.events"/>
```

**Comment by matthewp** [comment]
I don't think this would work, 

```handlebars
<can-import from="can-stache-route-helpers" value:to="scope.helpers"/>
```

Would replace `scope.helpers` with export of can-stache-route-helpers. What if you import multiple helpers.

**Comment by phillipskevin** [comment]
We could either make the setter handle this, but that would probably end up being confusing. Maybe we need to make this work:

```html
<can-import from="can-stache-route-helpers" value:assignTo="scope.helpers"/>
```

as discussed in https://github.com/canjs/can-stache-bindings/issues/104#issuecomment-337778746 (and I think other issues).

**Comment by matthewp** [comment]
That's pretty user unfriendly imo.

**Comment by phillipskevin** [comment]
Does this work already?

```html
<can-import from="can-stache-route-helpers" value.routeUrl="scope.helpers.routeUrl"/>
```

**Comment by matthewp** [comment]
To make `addBindings` work I'm going to add a `Symbol.for("can.stacheBindings")` that can-stache will use. This is because can-stache-bindings already exports stuff. So the user can either do:

```js
import { stache, stacheBindings } from "can";

// Yuck!
stache.addBindings(stacheBindings.bindings);
```

So to make 

```js
import { stache, stacheBindings } from "can";

// Yuck!
stache.addBindings(stacheBindings);
```

Work I'm going to have can-stache check for a symbol.
