### ISSUE TITLE
Repository cleanup - removing unsupported plugins

### ISSUE THREAD

**Issue by daffl** [canjs/canjs#423]
Currently the repository contains many unofficial plugins that are not fully tested and/or documented or even working.

These plugins should be moved to the [Incubator](https://github.com/bitovi/incubator) project and go through a review process before being added to the main repository.

**Comment by BigAB** [comment]
So, `can/control/modifier/key` was included in the npm release of 2.2.4 but not the bower release.

Bug? Or should we also remove it from npm release.

**Comment by daffl** [comment]
This has been solved via #2337
