### ISSUE TITLE
Pushstate is the current `core.mjs` binding

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#4240]
In this demo: https://codepen.io/justinbmeyer/pen/ZRPrPd?&editors=1011

The default binding is pushstate.  This should be hashchange unless I activate it.

I think we will need to make a breaking change here: https://github.com/canjs/can-route-pushstate/issues/101

**Comment by justinbmeyer** [comment]
You can see that `currentBinding` is pushstate if you set a breakpoint in the line that breaks and walk up to `start()`:

![image](https://user-images.githubusercontent.com/78602/42194406-7185ba48-7e39-11e8-8816-2a2d1ce68b90.png)

**Comment by justinbmeyer** [comment]
This is even easier to see if you import from `"can"` in the route-counter demo:

http://localhost:8080/canjs/demos/technology-overview/route-counter.html

**Comment by chasenlehara** [comment]
Can the initialization that currently happens when can-route-pushstate is included wait to be done until `start()` is called? https://github.com/canjs/can-route-pushstate/blob/c5e7a47bcf400ecaf90f372ac2ff6751c1a58094/can-route-pushstate.js#L309

**Comment by matthewp** [comment]
This is fixed with can-route-pushstate@5
