### ISSUE TITLE
can.route plugin for valid variable values

### ISSUE THREAD

**Issue by neektza** [canjs/canjs#426]
Hi everyone.

I have an idea for a can.route plugin. It would allow one to sepcify valid values for each can.route variable.

Example:

```js
can.route(':project/:category', { defaults: { ... }, valid: { project: ['canjs', 'jquerypp'], category: ['bug', 'article'] }}
can.route(':page/:category', { defaults: { ... }, valid: { page: ['greatest', 'latest'], category: [ ... ] }}

/*
"/greatest/bugs" => would match 2nd route
"/canjs/bugs" => would match 1st route
*/
```

That way, it would be possible to match certain cases of currently non-determinable routes.

Thoughs?

**Comment by justinbmeyer** [comment]
I think this is a reasonable suggestion, although a breaking change.  Currently, you'd have to do something like:

```
['canjs', 'jquerypp'].forEach(function(project){
  route(project+"/:category", {project: project});
});
['greatest', 'latest'].forEach(function(page){
  route(page+"/:category", {page: page});
});
```

Closing and moving to: https://github.com/canjs/can-route/issues/3
