### ISSUE TITLE
Proposal: Add a "logic" guide

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#4266]
I'd like a guide to provide suggestions on how to write DefineMaps (and eventually can-observe) in an organized, testable, and maintainable way.

### From imperative OO to FRP:

```js
// Imperative
DefineMap.extend({
  name: "string",
  nameChangeCount: {default: 0},
  updateName(name){
    this.name = name;
    this.nameChangeCount++;
  }
});
```

```js
// Imperative setter
DefineMap.extend({
  name: {
    set(name) {
      this.nameChangeCount++;
      return name;
    }
  },
  nameChangeCount: {default: 0}
});
```

```js
// Declarative light-weight streams
DefineMap.extend({
    name: "string",
    nameChangeCount: {
        value({listenTo, resolve}) {
            let count = resolve(0);
            listenTo("name", () => {
                resolve(++count);
            });
        }
    }
})
```

```js
// Declarative Kefir streaming properties
DefineMap.extend({
    name: "string",
    nameChangeCount: {
        stream(){
            return this.stream(".name").scan((prev) => {
                return prev+1;
            },0)
        }
    }
})
```

```js
// Solo Kefir streams
const name = Kefir.emitterProperty();

const nameChangeCount = name.scan(function(prev){
    return prev+1;
},0);
```

- when to use what

### dispatch, listenTo, connectedCallback, etc

What these things are, how/when to use them, etc.

### Organization

I usually organize my view model code as follows:

```js
import {Component} from "can";

Component.extend({
    tag: "some-component",
    view: `...`,
    ViewModel: {
        // EXTERNAL STATEFUL PROPERTIES
        // These are properties passed from another component.
        todoId: "number",

        // INTERNAL STATEFUL PROPERTIES
        // These are properties that are owned by this component.
        isEditing: {type: "boolean", default: false}

        // DERIVED PROPERTIES
        get something(){ ... }


        // METHODS
        updateTodo(){
            this.dispatch("updateTodo")
        }

        connectedCallback(element){
            // SIDE EFFECTS
            // if `connectedCallback()` isn't called ... then no side effects,
            // you can test yourself
            this.listenTo("updateTodo", function(){
                new Todo().save();
            })
        }    
    }

})
```

### Testing 

How to supply your own alternative side-effects without too much dependency-injection ugliness:

```js
updateTodo() {
  this.todo.save() // <- we normally use fixtures here, but maybe that won't work, what do you do?
}
```

**Comment by rjgotten** [comment]
> ```js
> // INTERNAL STATEFUL PROPERTIES
> // These are properties that are owned by this component.
> ```

I'd actually love if there were a way to make these _truly_ internal.

Marking private properties via a convention such as a leading underscore, or via a `modifier: "private"` or `private: true` property and making it impossible for the world outside a component to bind to those would be very nice as a way to enforce encapsulation.

**Comment by matthewp** [comment]
@rjgotten I don't think that's possible in JavaScript if you expect to internally be able to do `this.foo`. You could however do this yourself like so:

```js

const PrivateStuff = DefineMap.extend({
  priv: "string"
});

const privates = new WeakMap();

const PublicStuff = DefineMap.extend({
  init: function(){
    privates.set(this, new PrivateStuff());
  }

  prop: {
    get: function() {
      let privateStuff = privates.get(this);
      return privateStuff.priv;
    }
  }
});

module.exports = PublicStuff;
```

**Comment by justinbmeyer** [comment]
Along with this, I think we should have the component generators produce this.  For example:

```js
Component.extend({
    tag: "component-name",
    view,
    ViewModel: {
      // EXTERNAL STATEFUL PROPERTIES
      // These properties are passed from another component. Example:
      // value: {type: "number"}

      // INTERNAL STATEFUL PROPERTIES
      // These properties are owned by this component.
      message: {default: "This is the component-name component"},

      // DERIVED PROPERTIES
      // These properties combine other property values. Example:
      // get valueAndMessage(){ return this.value + this.message; }

      // METHODS
      // Functions that can be called by the view. Example:
      // incrementValue() { this.value++; }

      // SIDE EFFECTS
      // The following is a good place to perform changes to the DOM
      // Or do things that don't fit in to one of the areas above.
      connectedCallback(element){

      }
    }
});
```

**Comment by justinbmeyer** [comment]
`new Bind()`

**Comment by rjgotten** [comment]
> @matthewp 
> I don't think that's possible in JavaScript

I know it's not possible to do 'true' private properties.
That's also not what I'm suggesting; read closer.

What I was suggesting is that there is some kind of marker on view model definition to mark certain properties as not being able to bind them from outside the component that would use them.

For instance, Vue.js does this by separating `props` and `data`. Both still end up as public members on the component instances, but getting outside accesss to `data` requires that you go outside the normal usage path. The only people doing that are people that _know_ what they're doing and getting themselves into.

So it's kind of like putting a safety on a foot-gun.

**Comment by matthewp** [comment]
@rjgotten If you're not looking for actual private properties then the normal JavaScript conventions such as underscore property name should suffice, no?
