### ISSUE TITLE
Post 5.0 issues

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#4288]
- [x] Release with can-super-model and can-define fixed
- [x] Get webpack working again
- [x] Finish tech overview (Justin)
- [x] Get build to be stabilized ( npm build is showing breaks https://www.npmjs.com/package/can )
- [x] Get webpack-stache working
- [x] Migration guide includes pushstate
- [x] Release blog article

**Comment by phillipskevin** [comment]
We might want to do #4295 also.

**Comment by justinbmeyer** [comment]
It seems that with our existing guide, in production webpack, `//steal-remove-x` is still left:

![image](https://user-images.githubusercontent.com/78602/42853462-3689ebfc-89fc-11e8-844e-4f6d077b4871.png)

**Comment by roemhildtg** [comment]
You need to add something like this to your production webpack config:

```
    optimization: {
        minimizer: [
            new UglifyJSPlugin({
                uglifyOptions: {
                    output: {
                        comments: false,
                    },
                },
            })],
    },
```

It seems silly that this comments aren't removed by default, and the option to do so is nested 6 objects deep but that's what I've found frustrating in webpack.

**Comment by rjgotten** [comment]
> It seems silly that this comments aren't removed by default,

No it's not silly that the default is to keep those type of comments.
`//!` and `/*!` is a common convention for marking comments that should _not_ be removed by minification. E.g. because they contain lincensing information.

The silly here is on the side of CanJS, using `//!` as build pragmas when that form of comment already had a widely adopted previously established meaning.

**Comment by phillipskevin** [comment]
@justinbmeyer 

> debugger guide shows importing can-debug with require. How can we do this with import?

Is this asking about the webpack setup? 

You can do 
```
import { debug } from "can";

if (process.env.NODE_ENV !== "production") {
  debug();
}
```

...and the import will be removed by tree-shaking in production.

**Comment by justinbmeyer** [comment]
@rjgotten Steal's support of `//!` likely goes back 8 years.  I'm not sure it was well established by then.
