### ISSUE TITLE
Add build changes to the migration guide

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#4295]
The 5.0 migration guide should explain the build changes. Especially for people using the global build, we should explain that they need to update the URLs they're using:

`https://unpkg.com/can@4/dist/global/can.js` -> `https://unpkg.com/can@5/dist/global/core.js`
`https://unpkg.com/can@4/dist/global/can.all.js` -> `https://unpkg.com/can@5/dist/global/ecosystem.js`

This confusion was pointed out on Gitter: https://gitter.im/canjs/canjs?at=5b43674af16644066125c984.

**Comment by justinbmeyer** [comment]
I think we should just copy the `core.js` and `ecosystem.js` to `can.js` and `can.all.js`, maybe insert a `console.warn()` at the top.

**Comment by matthewp** [comment]
Why should we do that? If people are already changing the URL why can't they change it to core.js / ecosystem.js as well?

**Comment by phillipskevin** [comment]
For people that aren't changing the URL (like `https://unpkg.com/can/dist/global/can.js`).

**Comment by justinbmeyer** [comment]
Yeah, a little bit of work can make sure a bunch of demos keep working without surprises.

**Comment by justinbmeyer** [comment]
People should change their URLs, but they likely haven't.  CanJS 3.0, 4.0, 5.0 all can have basic examples that work for every version.
