### ISSUE TITLE
Add string-to-any to forms guide for <select>

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#4312]
I really like being able to do something like:

```html
<select value:to="string-to-any(value)">
  <option value="null">Nothing Selected</option>
  <option value="1">One</option>
  ...
```

https://canjs.com/doc/guides/forms.html#Select

**Comment by phillipskevin** [comment]
Here are the docs for the string-to-any converter: https://canjs.com/doc/can-stache-converters.string-to-any.html
