### ISSUE TITLE
The accordion demo is broke because of dev bundle

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#4329]
This demo in latest:

http://localhost:8080/canjs/demos/can-component/accordion.html

Works if `dev-bundle` is removed from `<script src="../../node_modules/steal/steal.js" dev-bundle main="@empty">`.  However, if the `dev-bundle` is used, the app fails (and shows warnings).

**Comment by matthewp** [comment]
Want me to look into this?
