### ISSUE TITLE
can-dom-mutate

### ISSUE THREAD

**Issue by pYr0x** [canjs/canjs#4334]
in https://github.com/canjs/canjs/blob/master/es/can-dom-mutate.js we export `can-dom-mutate` by default.
but sometimes we need `can-dom-mutate/dom-events` as well.
e.g. for `inserted` and `removed` events [see here](https://github.com/canjs/can-3-4-compat/blob/master/dom-mutation-events.js)

**Comment by matthewp** [comment]
Good catch. We just need to do something like we do in https://github.com/canjs/canjs/blob/master/es/can-define.js to export from subdirectories.

**Comment by matthewp** [comment]
That module isn't documented. I'm not sure if that's intentional or not. cc @phillipskevin @justinbmeyer
