### ISSUE TITLE
Broken links to Firefox install guides on "Developing Locally" docs page

### ISSUE THREAD

**Issue by mikedane** [canjs/canjs#4337]
https://canjs.com/doc/guides/contributing/developing-locally.html#InstallFirefox

I noticed 3 broken links on the firefox install section of the Developing Locally docs page linked above. The broken links are supposed to link to guides for installing firefox on Mac, Windows & Linux

> Mozilla has guides for installing it on [Linux](https://support.mozilla.org/t5/Install-and-Update/Install-Firefox-on-Linux/ta-p/2516), [Mac](https://support.mozilla.org/t5/Install-and-Update/How-to-download-and-install-Firefox-on-Mac/ta-p/3453), and [Windows](https://support.mozilla.org/t5/Install-and-Update/How-to-download-and-install-Firefox-on-Windows/ta-p/2210).

Here's some updated links I found to replace the broken ones:

Linux - https://support.mozilla.org/en-US/kb/install-firefox-linux
Windows - https://support.mozilla.org/en-US/kb/how-download-and-install-firefox-windows
Mac - https://support.mozilla.org/en-US/kb/how-download-and-install-firefox-mac

**Comment by knrt10** [comment]
I would like to fix this.

**Comment by justinbmeyer** [comment]
@knrt10 , that would be great.  You just have to create a PR with the changes to [this file](https://github.com/canjs/canjs/edit/master/docs/can-guides/contribute/developing-locally.md).
