### ISSUE TITLE
General content improvements for "Technology Overview" docs page

### ISSUE THREAD

**Issue by mikedane** [canjs/canjs#4344]
Below is a list of suggested changes/improvements that can be made to the existing documentation on the [Technology Overview](https://canjs.com/doc/guides/technology-overview.html) page in response to #4116

Since this documentation is split up into multiple sections, paragraphs and code blocks I've used the following notation to make it easy to locate (and fix) the specified issues within the documentation. 

Issues will first be identified by the high level section of the documentation they are in (ex. Overview, Key-Value Observables, etc), then by either the paragraph number (pX) or code block number. A paragraph here is defined as any block of text which is separated from surrounding text/code examples by a blank new line (a bulleted list is it's own paragraph), and a code block is any section of the docs that contains code and is again separated from other text/code block by a blank new line. I also may refer to images in the same manner. If anyone can think of a better notation, I can change this up to make it easier to follow.

## Overview
- [ ] p1 - We should link the word _Observables_ here to a definition of what exactly observables are just in case the user is unsure.
- [x] p3, 2nd bullet - _The browser URL to support the forward and back ~button~ buttons through 
Routing._
## Key Value Observables
- [x] p3, 2nd sentence - _myCounter.count is ~what we call~ part of the state of the myCounter instance._
- [x] p5, 1st sentence - The link to **_DefineList_** goes to the [can-define](https://canjs.com/doc/can-define.html) page, it would be better to link it to the actual [DefineList](https://canjs.com/doc/can-define/list/list.html) page.
- [x] code block 3 - uses the es5 `get` syntax which may be confusing to newer js users who haven't used it before. It might be useful to put a comment here indicating that it's a getter. 
- [x] code block 3 - When creating the new instance of `Counters` 
    ```js
    let myCounters = new Counters([
        new Counter(),
        new Counter({count: 3}),
        // Plain objects will be converted to Counter instances.
        {count: 4}
    ]);
    ```
    This example is passing an object `{count: 3}` into the `new Counter()` constructor. While it can be assumed that this initializes `count` with a custom value, it might be helpful to explicitly state what this is doing, maybe in a comment. 
- [ ] Mention that while Observables are the core of the technology behind the framework, a the lower end boilerplate is handled by the Component, restModel and routing abstractions. the majority of this behavior is abstracted away for ease of use. Mention how stache(linked) will provide a lot of binding between observables and the DOM events below V

## Observables and HTML elements
- [x] p1, 1st sentence - _CanJS applications use ~[Component](https://canjs.com/doc/can-component.html)~ [Components](https://canjs.com/doc/can-component.html) to connect_
- [x] code block 1 - This uses the outdated `var` keyword and should be updated to use `const` and `let` instead.
- [x] code blocks 2 & 3 - These two code blocks are doing exactly the same thing, except the first one defines the `Counter` observable outside of the `Component` declaration. I think these two code example should be merged into one single example, or we should just have _code block 3_ and get rid of _code block 2_
- [x] briefly mention magic tags from stache as doing the event binding.
- [x] briefly mention that you defining the ViewModel as an inline object is a way the Component abstraction simplifies the observable behavior.

## Observables and the browser's location
- [ ] start by mentioning that the router is a simple key value store for the window location -minus function values
- [x] p2, 2nd & 3rd sentences (replace period w/ comma) - _Click +1 a few times, then click the forward (⇦) and back (⇨) buttons to see the count change:_
- [x] code block 1 - This uses the outdated `var` keyword and should be updated to use `const` and `let` instead. I also think that there should be more explanation about the `#!&` symbols in the url, this could be confusing/intimidating for new users. Finally this code example is importing the `<mock-url>` element, but that is never explained to the user. A comment similar to the ones in _code blocks 2 & 3_ would work.
- [ ] mention the route.register as a way of registering a key as THE ROUTE

## Observables and the service layer
In this section of the Technology Overview there are two particularly massive code examples each ~65 lines of code. Given the complexity of the service layer, it makes sense that these examples are so involved, but from a new user's perspective this might be intimidating and could potentially turn them off of the framework. I think we should consider trying to trim these examples down to a more manageable amount of code (~30-40 lines) or simply remove the code and introduce the service layer in a more abstract way. 

- [x] code block 1 - small type in code, change it to:
    ```js
    {
        data: [
            { "id": 1, "name": "cook food",
              "complete": false, "dueDate": "Wed Jul 11 2018 13:42:31 GMT-0500" },
            { "id": 2, "name": "do taxes",
              "complete": true, "dueDate": "Sun Jul 29 2018 20:58:25 GMT-0500" },
            ...
        ]
    }
    ```
- [x] p3 - These list items use words like _Defines, Connects & Uses_, they should use _Defining, Connecting & Using_, it will sound better when reading along with the previous paragraph.
- [x] code block 2 - In line 7, `identity` field is not explained. It would also be nice to have a list of the most common types like `number` and `boolean`, so the user has a better idea of what types are available, and their corresponding names. 

## Next Steps
- [x] p1 - There are no next steps here, it just cuts off without saying anything. We should include some next steps or simply remove the section. My suggestion would be :
    
    > Now that you've got a rough idea idea on the major pieces of CanJS, we suggest: the [HTML](https://canjs.com/doc/guides/html.html), [Routing](https://canjs.com/doc/guides/routing.html), and [Service Layer](https://canjs.com/doc/guides/data.html) in depth guides.

## General Notes
While the above are changes that can be implemented immediately, these are also some more general suggestions/thoughts that could potentially aid the docs long term, and lead to some good discussion.

One note was about the extent to which this technology overview should cover the topics of HTML, Routing & The Service Layer. Given that this is simply meant as an overview of the technology in CanJS, is it really necessary to go as in-depth as this page is going. 

One of the consequences of this is that there is a decent amount of repeated information when the user does eventually move from the technology overview to one of the pages dedicated to HTML, Routing or the Service Layer. The user is exposed to the same or similar code examples a second time. Also by going into such depth in the technology overview the user might feel pressure to fully understand every code example and everything thats going on before they even get past the overview. This has the potential to turn them off of the framework. 

I wonder if it might be better if the Technology Overview introduced these topics in a more abstract way, or even through some sort of video or diagrams.

Another note is about observables. Obviously observables are a centerpiece of how CanJS functions, but when and where is the best time to bring observables up. After all it's possible for the user to learn about Components & Routing without being explicitly exposed to observables. I worry that newer and even intermediate JS devs might not have a solid understanding of what observables are. This technology overview essentially assumes that the user understands observables and that has the potential to intimidate less experienced devs

One final note is about the code examples. As of right now this section (aswell as other sections of the docs) use a variety of different code examples/demos. Like the counter, the todo list, the progress slider, the page login. With so many examples floating around it might get overwhelming for the user. Instead of so many different types of examples, what if we simply had one example app that got built throughout the docs. It would be one app that the user would really understand and by the time they reached the end of the introductory docs they would have it finished.

**Comment by thomaswilburn** [comment]
One thing not mentioned above, in the restModel section we assign the TodoList constructor as the `Todo.List` property, then we only operate on the list through `Todo.getList()`. Elsewhere, I've seen us define the list separately as its own variable, and pass it into the restModel config object directly as `List` to be augmented and used. I think that may be clearer for many new users, instead of expecting them to understand that "List" is a special property on DefineMaps when used with the restModel mixin.
