### ISSUE TITLE
Update demos to use es6 let/const syntax

### ISSUE THREAD

**Issue by mikedane** [canjs/canjs#4358]
Most of the code demos in the `/demos` folder use the outdated `var` keyword, which is weird because they are using the es6 `import` statement. Since they are already utilizing some es6 syntax they should all be updated to use `let` and `const` instead of `var`. 

All of the packages in the can eco-system pull their code demos from this folder in the canjs repo. By updating the demos it will not only improve the canjs docs but the docs for all of the packages in the eco-system.

**Comment by NandoTheessen** [comment]
Is this still needed? 
If yes, I'd be happy to contribute!

**Comment by mikedane** [comment]
Yup! It's still needed, It'd be awesome if you could take a look!

**Comment by NandoTheessen** [comment]
Awesome, just opened PR #4456 !
