### ISSUE TITLE
Make `@codepen` button work for demos.

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#4361]
I'd like to make `@codepen` work for demos and under the following considerations:

1.  We show `import {X} from "can"`
2.  We can import packages like https://github.com/bitovi-components/bit-hello-world/blob/master/bit-hello-world.mjs, https://github.com/canjs/todos-fixture, etc that import `import {Component} from "//unpkg.com/can@5/core.mjs";`.

## Example

I'd like to create a basic routing and data example that looks either like:

```html
<mock-url>
<script id="demo-source" src="../../node_modules/steal/steal.js" dev-bundle>
import {X,Y,Z} from "can";
import "//unpkg.com/mock-url@5"
import "//unpkg.com/todos-fixture@5"

// OTHER CODE HERE

</script>
```

Or eventually:

```html
<mock-url>
<script id="demo-source" src="../../node_modules/steal/steal.js" dev-bundle>
import {X,Y,Z} from "can";
import "mock-url"
import "todos-fixture"

// OTHER CODE HERE

</script>
```

On `canjs.com`, the demos will be presented like they are above.  However, for steal to load this, we need it able to support module specifiers starting with `//`: https://github.com/stealjs/steal/issues/1450

This is because [those packages](https://github.com/bitovi-components/bit-hello-world/blob/master/bit-hello-world.mjs) import `core.mjs` like: 

```js
import {Component} from "//unpkg.com/can@5/core.mjs";

export default Component.extend({
    tag: "hello-world",
    view: `<h1>{{greeting}} world!</h1>`,
    ViewModel: {
        greeting: {default: "Hello"}
    }
});
```

I need to be able to map "//unpkg.com/can@5/core.mjs" to `"can"`.  That way, we can publish little modules like this that work both in `steal` and using native module loaders.

**Comment by mikedane** [comment]
Here's some of the demos that suffer from this problem:

- [ ] demos/technology-overview/route-counter.html
- [ ] demos/technology-overview/route-counter-registered.html
- [ ] demos/technology-overview/route-mini-app.html
- [ ] demos/technology-overview/route-mini-app-start.html
- [ ] demos/technology-overview/task-editor.html

**Comment by chasenlehara** [comment]
I just tested a demo in the routing guide and it looks like this works now.
