### ISSUE TITLE
everything.mjs is built in production env?

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#4482]
With `core.mjs`, there's `DefineMap.prototype.log`:

https://codepen.io/justinbmeyer/pen/XPQoZd?editors=1011

With `everything.mjs`, there's no `DefineMap.prototype.log`:

https://codepen.io/justinbmeyer/pen/zJXyWK?editors=1011

**Comment by phillipskevin** [comment]
Yeah, looks like it's missing the `removeDevelopmentCode: false` that `core` and `ecosystem` have:

https://github.com/canjs/canjs/blob/c242be8502b4a6bdbb620c74c914fef22660af2e/build.js#L105

**Comment by phillipskevin** [comment]
This was fixed in https://github.com/canjs/canjs/commit/74ad7875a4a278bbc22a68d36a5f81cd4c06dfd2.
