### ISSUE TITLE
Chrome Dev Tools doesn't show the whole stack.  

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#4499]
In this example: https://codepen.io/justinbmeyer/pen/xybZYy?editors=0010

Chrome shows:

![image](https://user-images.githubusercontent.com/78602/46239990-51b99f00-c366-11e8-8f3a-ac5c48d45429.png)

Log stack shows:

![image](https://user-images.githubusercontent.com/78602/46239992-5e3df780-c366-11e8-9f15-197e4d4c17e3.png)

**Comment by phillipskevin** [comment]
Issue moved to [canjs/devtools #29](https://github.com/canjs/devtools/issues/29) via [**ZenHub**](https://www.zenhub.com/)
