### ISSUE TITLE
Proposal: Make can-component work inside of NodeJS

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/canjs#4527]
I think for testing and all kind of stuff it could be slick to import a component in node and then do component.element also to do ssr and other stuff.

I know this works in the browser but for node we need some redesign of the code that only works in the browser.

at present for example i try to get can-stache working inside node
```js
(node:30787) ExperimentalWarning: The ESM module loader is experimental.
TypeError: decodeHTML is not a function
    at HTMLSection.add (/home/frank/example-es6-loader/interface/node_modules/can-stache/src/html_section.js:125:11)
    at HTMLSectionBuilder.add (/home/frank/example-es6-loader/interface/node_modules/can-stache/src/utils.js:44:16)
    at Object.chars (/home/frank/example-es6-loader/interface/node_modules/can-stache/can-stache.js:378:39)
    at callChars (/home/frank/example-es6-loader/interface/node_modules/can-view-parser/can-view-parser.js:203:13)
    at HTMLParser (/home/frank/example-es6-loader/interface/node_modules/can-view-parser/can-view-parser.js:267:6)
    at stache (/home/frank/example-es6-loader/interface/node_modules/can-stache/can-stache.js:200:2)
    at Function.setup (/home/frank/example-es6-loader/interface/node_modules/can-component/can-component.js:329:22)
    at Function.extend (/home/frank/example-es6-loader/interface/node_modules/can-construct/can-construct.js:700:29)
    at file:///home/frank/example-es6-loader/interface/src/canapp/index.mjs:8:26
    at ModuleJob.run (internal/modules/esm/module_job.js:96:12)
```

**Comment by justinbmeyer** [comment]
It should be possible to do this as DoneJS does this already.   You likely need to first setup can-simple-dom and then make sure `can-globals` gets all of `can-simple-dom`'s outputs.

Something like:

```
var makeDocument = require('can-vdom/make-document/make-document');
var globals = require('can-globals');
var doc = makeDocument();

globals.setKeyValue("document",doc);
globals.setKeyValue('MutationObserver', null);


var Component = require("can-component");

... DO STUFF ...
```

**Comment by frank-dspeed** [comment]
@justinbmeyer i applyed your changes but the problem is still the code inside can-stache 
```
assign(HTMLSection.prototype,{
	inverse: function(){
		this.inverseData = [];
		this.data = "inverseData";
	},
	// Adds a DOM node.
	push: function(data){
		this.add(data);
		this.targetStack.push(data);
	},
	pop: function(){
		return this.targetStack.pop();
	},
	add: function(data){
		if(typeof data === "string"){
			data = decodeHTML(data);
		}
		if(this.targetStack.length) {
			last(this.targetStack).children.push(data);
		} else {
			this[this.data].push(data);
		}
	},
```
decodeHTML don't exists and is not a browser method or anything

**Comment by frank-dspeed** [comment]
@justinbmeyer i found out that the problem was not can-stache its can-globals and the coding style of it that don't works out well when used async
```js
import me from 'can-globals'
import other from 'other'
```
dont gets executed in order they run parallel and because of the prototype additions all over some functions are missing in some state.

issu #4533 - is related to this as this is the base for it 

https://github.com/canjs/can-globals - has some open PR's that need discussion or merge so that all works more smoth

**Comment by frank-dspeed** [comment]
the owner of #4524 should look into this to have a example complet application using only CanJs with nativ ESM Methods.

**Comment by Lighttree** [comment]
Isn't "program instantiation" helpful in this case ? I didn't use `CanJS@5` but I was hoping that this feature will allow "create" component in `NodeJS` and test this. Its actually cool feature, because it will be great if we will be able to do what `Enzyme` provides for `React`: https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md

Basically to allow simulate component interaction in `Node` and write all tests in `Jest` for example.

**Comment by frank-dspeed** [comment]
@Lighttree yes exact that is working but it needed a bit more research and tweaks for setting up the globals right
