### ISSUE TITLE
can.view duplicates conversion to document fragment & breaks live binding hookups

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#453]
It's possible to trigger a situation where `can.view` converts the output of the internally called `can.view.render` to a document fragment twice, and tries to perform hookup of live binding twice.

This happens when you pass it a Deferred as the data *and* supply it a callback function. The code path taken will first resolve the deferred, which will pipe the view string through `can.view.frag` for hookup. Afterwards it will check if a callback was passed in and if so, will then also call it with the view string, which *again* will be piped through `can.view.frag` for hookup.

Ofcourse, this second time the `can.view.hookups` collection prepared by the view renderer will already have been consumed by the first fragment conversion and hookup. As a result, no hookup will take place the second time and the view will keep its mangled placeholders.

I've mentioned this multiple times on multiple issues before, but I'll reiterate it again for this one: I strongly feel these kind of bugs could be completely avoided by sanitizing and unifying the `can.view` API to work exclusively through a Deferred and to **always** resolve results asynchronously.

**Comment by justinbmeyer** [comment]
@kiennguyen1101 is the template calling `formatSize`?  Sorry this is so late.

**Comment by justinbmeyer** [comment]
@rjgotten I'm not sure what you meant by 

> will then also call it with the view string, which again will be piped through can.view.frag for hookup.

**Comment by kiennguyen1101** [comment]
Yes, the template was calling formatSize

**Comment by rjgotten** [comment]
@justinbmeyer 
It's related to the old way the view template and Deferreds were being fetched; there used to be a private-by-closure `pipe` function present to chain resulting Deferreds together. The template's string -> fragment conversion (and thus the binding hookup) was (indirectly) called from that function.

The current trunk version of the view API was restructured and no longer contains this particular construct. I think the bug also no longer surfaces, but I'd have to check.

**Comment by justinbmeyer** [comment]
Closing b/c it might not be a problem anymore and `can.view` won't be part of core in 3.0.
