### ISSUE TITLE
Proposal: Rename Steal Only Related can- modules to steal-

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/canjs#4571]
and then running donejs build.

<can-import> has hooks that notify the build time algorithm to create a bundle for this template fragment and its dependencies. This feature spans StealJS, steal-build, CanJS, and done-cli.

- can-import => steal-import

**Comment by frank-dspeed** [comment]
maybe call it steal-stache-import ?

**Comment by chasenlehara** [comment]
can-view-import works with webpack as well, so it’s not specific to steal. I don’t think it needs to be renamed.
