### ISSUE TITLE
Not all tests are running in IE11

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#4612]
In the last master build (https://travis-ci.org/canjs/canjs/builds/457609160) only 2143 assertions ran in IE11, vs ~8500 in other browsers.

After fixing can-query-logic's tests (https://github.com/canjs/can-query-logic/releases/tag/v1.1.6), 6373 assertions passed and 2 failed (https://travis-ci.org/canjs/canjs/jobs/458164628).

We need to fix the 2 broken assertions and figure out what other tests are not running.

The only tests that should not be running are:

* `can-component viewModels with observe` (https://github.com/canjs/can-component/blob/master/test/component-viewmodel-observe-test.js)
* `can-connect/can/map/map with can-observe`(https://github.com/canjs/can-connect/blob/master/can/map/observe-test.js)
* `can-route observe` (https://github.com/canjs/can-route/blob/master/test/route-observe-test.js)

**Comment by phillipskevin** [comment]
Here are the two tests that are failing:

![image](https://user-images.githubusercontent.com/5851984/48874967-be2baa00-edbb-11e8-99b8-579335492ec0.png)

**Comment by cherifGsoul** [comment]
The `can-fixture-socket` error is in not in `canjs` is in [feathers-hooks](https://github.com/feathersjs-ecosystem/feathers-hooks) in this line

**Comment by phillipskevin** [comment]
Here is what is failing in the latest run:

![image](https://user-images.githubusercontent.com/5851984/49108585-2c55ee00-f24e-11e8-87d2-02514f8d23a9.png)

**Comment by phillipskevin** [comment]
closed by https://github.com/canjs/canjs/pull/4615.
