### ISSUE TITLE
Routing guide codepen is not working

### ISSUE THREAD

**Issue by mikemitchel** [canjs/canjs#4614]
When trying to change the hash to `#!&page=products` as suggested on the routing guide sample codepen here:
https://canjs.com/doc/guides/routing.html

Nothing happens and this error is logged in the console
`Uncaught ReferenceError: viewModel is not defined
    at pen.js:74`

**Comment by justinbmeyer** [comment]
which codepen?  Can you provide a screenshot?

**Comment by justinbmeyer** [comment]
figured it  out, fixed
