### ISSUE TITLE
Update the “Credit Card Guide (Simple)” guide for CanJS 5

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4623]
This should include:

- Importing modules from `unpkg.com/can@5/core.mjs`
- Switching from JS Bin to CodePen (use the [Bitovi](https://codepen.io/bitovi/) account)
- Showing newer syntax (if applicable): `this.`, `for(of)`, can-component instead of `can.stache.from`, etc.

**Comment by manaswinidas** [comment]
I'm interested to solve this issue

**Comment by chasenlehara** [comment]
Thanks @manaswinidas!

We’ve already upgraded some of the other recipes, so you can use those for reference:

- https://canjs.com/doc/guides/recipes/modals.html
- https://canjs.com/doc/guides/recipes/search-list-details.html
- https://canjs.com/doc/guides/recipes/signup-simple.html
- https://canjs.com/doc/guides/recipes/text-editor.html
- https://canjs.com/doc/guides/recipes/tinder-carousel.html
- https://canjs.com/doc/guides/recipes/video-player.html

Some of my PRs for upgrading the other recipes can be used for reference:

- https://github.com/canjs/canjs/pull/4293
- https://github.com/canjs/canjs/pull/4605
- https://github.com/canjs/canjs/pull/4392

This is a big task, so don’t be afraid to ask questions here or message us on Gitter: https://gitter.im/canjs/canjs 😊
