### ISSUE TITLE
Update the “CTA Bus Map (Medium)” guide for CanJS 5

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4624]
This should include:

- Importing modules from `unpkg.com/can@5/core.mjs`
- Switching from JS Bin to CodePen (use the [Bitovi](https://codepen.io/bitovi/) account)
- Showing newer syntax (if applicable): `this.`, `for(of)`, can-component instead of `can.stache.from`, etc.

**Comment by justinbmeyer** [comment]
## CodePen Review Notes

CodePen: https://codepen.io/cherifGsoul/pen/VRyxPx?editors=0010

- [ ] The styles seem broken.  Here's what it looks like in the JSBin: ![image](https://user-images.githubusercontent.com/78602/54781213-ab01dd00-4be9-11e9-951e-69a5fb59e418.png) and in the codepen: 
![image](https://user-images.githubusercontent.com/78602/54781251-c2d96100-4be9-11e9-8bbf-3f9444871bd6.png)



- [ ] I wonder if we should tell users to layout the codepen like this and to put the map on top like the following: ![image](https://user-images.githubusercontent.com/78602/54781080-5a8a7f80-4be9-11e9-95d0-d458dc80c2f2.png)
- [ ] Get rid of the double scroll bar

**Comment by cherifGsoul** [comment]
in the JSBIN the `body` is the parent element, in the CodePen  `bus-tracker` element is the parent,
now the style should be fixed by:
```css
bus-traker {
  display: flex;
  flex-direction: column;
}
```

**Comment by cherifGsoul** [comment]
The styling issues were fixed yesterday!

**Comment by justinbmeyer** [comment]
- [ ]  Add a line between the `import { Component } from "//unpkg.com/can@5/core.mjs";` and any code that comes after it.
- [ ] `this.to` vs `this:to` ... how was this working?  I don't think `mapElement` is actually used.  I see `element.firstElement` instead.   I think `mapElement` can be removed.
- [ ] Instead of listening to vehicles ... could we do the following:
   ```
   get markers(){
     return (this.vehicles || []).map( (vehicle) => new google.maps.Marker( ... ) )
   },
   connectedCallback( element ) {
     this.listenTo("markers", (ev, newMarkers, oldMarkers){
        oldMarkers.forEach( marker => marker.setMap(null) );
     })
   }
   ```

**Comment by cherifGsoul** [comment]
@justinbmeyer the above issues are fixed in the CodePen https://codepen.io/cherifGsoul/pen/EMdbJw

**Comment by chasenlehara** [comment]
I moved the `window.googleAPI` setup to the HTML tab. Everything else looks good to me: https://codepen.io/bitovi/pen/MRKbWK?editors=1010

@cherifGsoul Is the next step to update https://github.com/canjs/canjs/pull/4779?

**Comment by cherifGsoul** [comment]
@chasenlehara Yes I'll update the steps in the guide.

**Comment by cherifGsoul** [comment]
@chasenlehara I updated the guide.
