### ISSUE TITLE
Update the “File Navigator Guide (Advanced)” guide for CanJS 5

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4625]
This should include:

- Importing modules from `unpkg.com/can@5/core.mjs`
- Switching from JS Bin to CodePen (use the [Bitovi](https://codepen.io/bitovi/) account)
- Showing newer syntax (if applicable): `this.`, `for(of)`, can-component instead of `can.stache.from`, etc.

**Comment by justinbmeyer** [comment]
- [ ]  I think `Entity.List = DefineList.extend({` can be removed now.
- [ ] `realtimeRestModel` is this needed?  I think `restModel` is enough in this app.
- [ ] spacing should look like `{{ folder.name }}`
