### ISSUE TITLE
Update the “File Navigator Guide (Simple)” guide for CanJS 5

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4626]
This should include:

- Importing modules from `unpkg.com/can@5/core.mjs`
- Switching from JS Bin to CodePen (use the [Bitovi](https://codepen.io/bitovi/) account)
- Showing newer syntax (if applicable): `this.`, `for(of)`, can-component instead of `can.stache.from`, etc.

**Comment by manaswinidas** [comment]
I'd like to help with the documentation

**Comment by chasenlehara** [comment]
I left a comment on another issue about getting started on this: https://github.com/canjs/canjs/issues/4623#issuecomment-450207645

**Comment by justinbmeyer** [comment]
@manaswinidas if you'd like to pair on any of this, please reach out to us: `core@donejs.com`.  We can help get you started.  Thanks for offering to help!  Also, couldn't hurt to email us because we will send you some t-shirts and such :-)

**Comment by manaswinidas** [comment]
@justinbmeyer Thanks! That's awesome
