### ISSUE TITLE
Update the “Playlist Editor (Advanced)” guide for CanJS 5

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4627]
This should include:

- Importing modules from `unpkg.com/can@5/core.mjs`
- Switching from JS Bin to CodePen (use the [Bitovi](https://codepen.io/bitovi/) account)
- Showing newer syntax (if applicable): `this.`, `for(of)`, can-component instead of `can.stache.from`, etc.

**Comment by cherifGsoul** [comment]
@justinbmeyer this is the finished CodePen to review https://codepen.io/cherifGsoul/pen/ywpxyy?editors=0010
