### ISSUE TITLE
Update the “TodoMVC with StealJS” guide for CanJS 5

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4628]
This should include:

- Importing modules from `unpkg.com/can@5/core.mjs`
- Switching from JS Bin to CodePen (use the [Bitovi](https://codepen.io/bitovi/) account)
- Showing newer syntax (if applicable): `this.`, `for(of)`, can-component instead of `can.stache.from`, etc.

**Comment by justinbmeyer** [comment]
codepen and unpkg doesn't apply to this guide

**Comment by cherifGsoul** [comment]
The `TodoMVC` is already updated!
