### ISSUE TITLE
Update the “Weather Report Guide (Simple)” guide for CanJS 5

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4630]
This should include:

- Importing modules from `unpkg.com/can@5/core.mjs`
- Switching from JS Bin to CodePen (use the [Bitovi](https://codepen.io/bitovi/) account)
- Showing newer syntax (if applicable): `this.`, `for(of)`, can-component instead of `can.stache.from`, etc.

**Comment by cherifGsoul** [comment]
<img width="1440" alt="screen shot 2019-01-04 at 9 50 53 pm" src="https://user-images.githubusercontent.com/109013/50710304-e3723000-106a-11e9-98c7-959d3a884506.png">

https://developer.yahoo.com/weather/

**Comment by frank-dspeed** [comment]
here a starting point from me you can change it to use can@5 
https://codepen.io/frank-dspeed/pen/xyvpKO

**Comment by chasenlehara** [comment]
That notice says:

> Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired. 
>
> To continue using our free Yahoo Weather APIs, use https://weather-ydn-yql.media.yahoo.com/forecastrss. Contact yahoo-weather-ydn-api@oath.com for credentials to onboard to this free Yahoo Weather API service.

I emailed them to see if we can get free credentials.

**Comment by cherifGsoul** [comment]
@chasenlehara do we have credentials?

**Comment by chasenlehara** [comment]
I never received a response from them.

**Comment by CleverOscar** [comment]
I sent out an email and would love to work on this guide, hopefully, I can get some credentials
