### ISSUE TITLE
Add info to the 3.x migration guide that /:page is deprecated

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4674]
The old route register colon syntax is deprecated in favor of `/{page}`. We should mention this in the migration guide.

**Comment by matthewp** [comment]
The colon syntax was deprecated by not removed, right?

**Comment by matthewp** [comment]
Yeah, colon was still supported: https://github.com/canjs/can-route/blob/v3.0.0/can-route.js#L160

**Comment by matthewp** [comment]
In major via https://github.com/canjs/canjs/pull/5321
