### ISSUE TITLE
stealjs setup doesn't link to github repo

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#4679]
https://canjs.com/doc/guides/setup.html#StealJS

**Comment by cherifGsoul** [comment]
What link should be changed? stealjs.com by stealjs repo?
<img width="577" alt="screen shot 2018-12-26 at 9 21 19 pm" src="https://user-images.githubusercontent.com/109013/50456376-415c9480-0954-11e9-8916-4769f3985326.png">

**Comment by cherifGsoul** [comment]
I guess this repo https://github.com/canjs/steal-can-example should be mentioned
