### ISSUE TITLE
Proposal: Reduce Repo Size 

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/canjs#4683]
This inital Repo is to big:

```
Klone nach 'canjs' ...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 103928 (delta 19), reused 20 (delta 7), pack-reused 103882
Empfange Objekte: 100% (103928/103928), 119.08 MiB | 577.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (67212/67212), Fertig.
```

We Should Reduce its size by Splitting out the Guides and move the history to canjs-history branch or even own repo

**Comment by justinbmeyer** [comment]
I believe there is already an issue for doing this for all canjs packages

**Comment by frank-dspeed** [comment]
@justinbmeyer is something blocking? is some one assigned to that already?

**Comment by justinbmeyer** [comment]
Nothing blocking. No one assigned. The big thing is changing how canjs/canjs works. I’ll write up more later.

**Comment by chasenlehara** [comment]
Closing this in favor of https://github.com/canjs/canjs/issues/4238
