### ISSUE TITLE
PR: Extend Setup Guide Rollup ES2030

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/canjs#4684]
I will add my Effort to Produce ES+ Compatible builds to the setup guide but maybe that needs a extra guide later linked form the Setup Guide as ES+ is diffrent from the current CJS Style and Introduces a lot of new Concepts.

## Related ISSUES
- #4533 - Proposal Create can-rollup
- #4502 - debuggerHelper not in build with rollup
- #4652

**Comment by matthewp** [comment]
What do you mean when you say it doesn't work with tree shaking? What does work exactly?

**Comment by frank-dspeed** [comment]
@matthewp i am talking about nativ builds via the current node ESM Fork https://github.com/nodejs/ecmascript-modules + rollup it includes always much extra functions that never get used or called. i am maintaining a ```canes ``` Fork of CanJS that is trying to get ESM Compatible as far as possible but there are a lot of blocking issues.
