### ISSUE TITLE
Update canjs.com with new CRUD copy

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4738]
To start, I’ll update the home page with copy from [the mockup/prototype](https://canjs-home-page-redesign.webflow.io/) (with some tweaks). Instead of using [this simple to-do app CodePen](https://codepen.io/bitovi/pen/omqyMw?editors=0010), I’ll embed the custom element into the page. The CTAs will link to the [current TodoMVC guide](https://canjs.com/doc/guides/todomvc.html).

@ryangwilson, the design of that example app could use some love.

**Comment by ryangwilson** [comment]
To Do List styling updated here: https://codepen.io/ryangwilson/pen/yZrogP
<img width="895" alt="screen shot 2019-02-20 at 1 21 14 pm" src="https://user-images.githubusercontent.com/4571457/53114759-8810da00-3512-11e9-81cf-0455414ac81d.png">

**Comment by ryangwilson** [comment]
Added To Do list strikethrough, add, and remove animation examples here: https://codepen.io/ryangwilson/pen/qgGmVd
![todo-anim-demo](https://user-images.githubusercontent.com/4571457/53177831-b64bf380-35be-11e9-9a6d-ab7ba4f5621d.gif)
