### ISSUE TITLE
Move the main sidebar nav to the header

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4742]
We should move the About, Guides, etc. links from the sidebar to the header. This will mean the homepage is full-width, then going to any other page will add the sidebar.

@ryangwilson, at some point we’ll need to nail down what the header should look like.

**Comment by ryangwilson** [comment]
Step 2 - Option 1
![Step 03](https://user-images.githubusercontent.com/4571457/54524252-e7161300-4947-11e9-8588-c69b4b8518d2.jpg)


Step 2 - Option 2 (Stars, By Bitovi)
![Step 03 -OPT2](https://user-images.githubusercontent.com/4571457/54524279-f4330200-4947-11e9-8c6c-49ff314e4593.jpg)

**Comment by chasenlehara** [comment]
Let’s have something like the By Bitovi logo that SDD has on the right-hand side (instead of the bits).

**Comment by ryangwilson** [comment]
By Bitovi - created as an SVG
`<svg viewBox="0 0 539 190" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <path id="a" d="M0 0h539v162H0z"/>
  </defs>
  <g fill="none" fill-rule="evenodd">
    <g transform="translate(0 28)">
      <mask id="b" fill="#fff">
        <use xlink:href="#a"/>
      </mask>
      <path d="M129.923936 0c-11.668616 0-21.171633 9.543471-21.171633 21.201047 0 11.656576 9.503017 21.157045 21.171633 21.157045 11.660611 0 21.167631-9.50047 21.167631-21.157045C151.091567 9.543471 141.584547 0 129.923936 0zm387.860398 0c-11.668616 0-21.171633 9.547471-21.171633 21.201047 0 11.652575 9.511023 21.157045 21.171633 21.157045C529.445945 42.358092 539 32.861622 539 21.201047 539 9.539471 529.453951 0 517.784334 0zM129.923936 5.528273c8.690417 0 15.683581 6.988345 15.683581 15.672774 0 8.683429-6.993164 15.672774-15.683581 15.672774-8.693419 0-15.687583-6.989345-15.687583-15.672774 0-8.684429 6.994164-15.672774 15.687583-15.672774zM0 47.971369v111.610512h61.91672c7.021184 0 13.212756-.715036 18.533685-2.203109 5.425006-1.594079 9.948346-3.797188 13.568019-6.562324 3.61567-2.766137 6.313662-5.993296 8.122998-9.71548 1.806333-3.828189 2.721009-7.969394 2.721009-12.434614v-.344017c0-7.656378-2.138579-13.55867-6.394722-17.703874-4.257143-4.144205-10.004387-7.28536-17.23973-9.410465 6.06648-2.129105 10.90205-5.199257 14.51872-9.242457 3.61567-4.145204 5.441018-9.578473 5.441018-16.273803v-.305015c0-3.82819-.621458-7.187355-1.899402-10.058497-1.274941-2.871142-2.947176-5.321263-4.968669-7.340362-3.299436-3.297163-7.509545-5.770285-12.614314-7.46937-5.000693-1.703083-11.3764-2.547125-19.143136-2.547125H0zm111.258154 111.610512h37.328563V47.971369h-37.328563v111.610512zM155.67395 47.971369v31.560558h32.879279v80.049954h37.375598V79.531927h32.832243V47.97137H155.67395zm211.233976 0l45.32647 112.431552h35.729382l45.322467-112.431552h-41.132373l-21.731046 62.647094-21.691017-62.647094h-41.823883zm132.210625 111.610512h37.332567V47.971369h-37.332567v111.610512zM36.381864 76.207763h16.15693c7.978893 0 11.96984 2.539126 11.96984 7.640378v.304015c0 5.102252-3.96793 7.68438-11.840744 7.68438v-.039003H36.381864v-15.58977zM317.828687 45.55325c-8.620365 0-16.622274 1.535076-24.068772 4.617229-7.446499 2.977147-13.955305 7.164353-19.48739 12.477616-5.426007 5.211257-9.725181 11.35956-12.915537 18.480912-3.08828 7.016347-4.624415 14.58672-4.624415 22.66912v.301015c0 8.078399 1.536135 15.676774 4.624415 22.798126 3.084278 7.015346 7.318404 13.140648 12.74341 18.347906 5.532085 5.211257 11.973841 9.285458 19.315262 12.262605C300.863159 160.484925 308.904096 162 317.523461 162c8.619364 0 16.661303-1.515075 24.111804-4.492222 7.446499-3.082152 13.885253-7.223357 19.31126-12.434614 5.531084-5.316262 9.835262-11.461566 12.919539-18.480913 3.189355-7.121351 4.792539-14.715726 4.792539-22.794125v-.348017c0-8.0784-1.536134-15.605771-4.620412-22.621117-3.084277-7.125352-7.431487-13.313658-12.962571-18.524915-5.426007-5.207257-11.821729-9.285459-19.268228-12.262606-7.341421-2.976147-15.363344-4.488222-23.978706-4.488222zm-.305225 33.029632c3.61567 0 6.849057.691034 9.722179 2.074102 2.873121 1.378068 5.323931 3.22616 7.345424 5.566275 2.020491 2.340115 3.556626 5.07825 4.624414 8.160403 1.168863 2.976147 1.770307 6.117302 1.770307 9.414465v.301015c0 3.297163-.535395 6.437318-1.59818 9.414465-1.067788 2.976147-2.603922 5.644278-4.624414 7.984394-2.021493 2.23511-4.472303 4.016198-7.345424 5.399267-2.873122 1.382068-6.035457 2.070102-9.550052 2.070102-3.61567 0-6.888086-.688034-9.761208-2.070102-2.873121-1.383069-5.323931-3.23116-7.345424-5.571276-2.020492-2.340115-3.584647-5.011247-4.75351-7.988394-1.062784-3.082152-1.599181-6.246309-1.599181-9.539471v-.348017c0-3.293163.536397-6.433318 1.599181-9.410465 1.063786-2.976147 2.59992-5.582276 4.624415-7.816386 2.021493-2.340116 4.472302-4.188207 7.345424-5.566275 2.869118-1.383068 6.035457-2.074102 9.546049-2.074102zM36.381865 114.763667h18.834907c4.045988 0 7.09524.758038 9.119734 2.246111 2.021493 1.488074 3.022232 3.469172 3.022232 5.914292v.301015c0 2.445121-1.067789 4.429219-3.198362 5.914292-2.020492 1.492074-5.026711 2.246111-9.072699 2.246111H36.381864v-16.621821z" fill="#C93136" mask="url(#b)"/>
    </g>
    <path d="M3.09 53V2.845h15.995c3.080015 0 5.734155.30333 7.9625.91s4.059993 1.469994 5.495 2.59c1.435007 1.120006 2.496663 2.490825 3.185 4.1125.688337 1.621675 1.0325 3.44749 1.0325 5.4775 0 1.236673-.192498 2.42666-.5775 3.57-.385002 1.143339-.96833 2.204995-1.75 3.185-.78167.980005-1.76166 1.854996-2.94 2.625-1.17834.770004-2.560825 1.399997-4.1475 1.89 3.663352.723337 6.428324 2.041657 8.295 3.955 1.866676 1.913343 2.8 4.433318 2.8 7.56 0 2.123344-.39083 4.059991-1.1725 5.81-.78167 1.750009-1.924992 3.254994-3.43 4.515-1.505007 1.260006-3.348322 2.234163-5.53 2.9225C26.125822 52.655837 23.635014 53 20.835 53H3.09zm6.79-22.855V47.61h10.85c1.936676 0 3.59916-.221664 4.9875-.665 1.38834-.443336 2.531662-1.067496 3.43-1.8725.898338-.805004 1.557498-1.761661 1.9775-2.87.420002-1.108339.63-2.327493.63-3.6575 0-2.590013-.915824-4.637493-2.7475-6.1425-1.831676-1.505008-4.602481-2.2575-8.3125-2.2575H9.88zm0-4.83h8.96c1.913343 0 3.569993-.209998 4.97-.63 1.400007-.420002 2.560829-1.00333 3.4825-1.75.921671-.74667 1.604164-1.650828 2.0475-2.7125.443336-1.061672.665-2.222494.665-3.4825 0-2.940015-.886658-5.098326-2.66-6.475-1.773342-1.376674-4.526648-2.065-8.26-2.065H9.88v17.115zM67.7 33.05V53h-6.755V33.05L42.57 2.845h5.95c.60667 0 1.084998.151665 1.435.455.350002.303335.653332.676664.91 1.12l11.48 19.495c.466669.81667.857498 1.586663 1.1725 2.31.315002.723337.600832 1.434996.8575 2.135.256668-.723337.536665-1.446663.84-2.17.303335-.723337.688331-1.481663 1.155-2.275L77.815 4.42c.210001-.373335.495832-.729165.8575-1.0675.361669-.338335.834164-.5075 1.4175-.5075h6.02L67.7 33.05z" fill="#7C7C7C" fill-rule="nonzero"/>
  </g>
</svg>
`
