### ISSUE TITLE
Move search to the header

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4743]
The search field (that’s currently in the black bar) should be moved to the header. 

@ryangwilson, we will need to figure out how the results should display as the user types, as well as what this will look like on mobile.

**Comment by ryangwilson** [comment]
Step 1 - Option 1
![Step 02](https://user-images.githubusercontent.com/4571457/54524167-9ef6f080-4947-11e9-83a5-5b9e93ee0053.jpg)

Step 1 - Option 2 (Search layout different)
![Step 02 -OPT2](https://user-images.githubusercontent.com/4571457/54524174-a1594a80-4947-11e9-80c8-9e5c8ac2718d.jpg)
