### ISSUE TITLE
Move the in-page nav into the main content

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4744]
This will allow us to get rid of the black bar and instead have any in-page nav in the content.

@ryangwilson, we’ll need to figure out a new design for this. Maybe as another column, maybe just a box in the page, maybe something else?

**Comment by ryangwilson** [comment]
![Step 05](https://user-images.githubusercontent.com/4571457/54524351-23497380-4948-11e9-84f2-b628f1a30889.jpg)

**Comment by chasenlehara** [comment]
Nesting example: https://canjs.com/doc/guides/forms.html

**Comment by ryangwilson** [comment]
**Nesting concepts**
Notes: truncating at one line will most likely cut off important information, two lines seems like a better idea. Another idea might be to add a data line to the headers where we could summarize the title and pull that in to the sidebar link

Existing Bullet Size (Academy)
![Existing Bullet Size](https://user-images.githubusercontent.com/4571457/56380107-44b7ac80-61df-11e9-8080-dc6c49ac6f27.jpg)

Smaller Bullet Size
![Smaller Bullet Size](https://user-images.githubusercontent.com/4571457/56380106-44b7ac80-61df-11e9-9fab-eba9d5af5d76.jpg)

Truncate at 2 lines
![Truncate at 2 lines](https://user-images.githubusercontent.com/4571457/56380108-44b7ac80-61df-11e9-8a2c-372f81f21b12.jpg)

Truncate at one line
![Truncate at one line](https://user-images.githubusercontent.com/4571457/56380109-44b7ac80-61df-11e9-9c63-2dc0f0efe235.jpg)

Two levels of nesting
![two levels of nesting](https://user-images.githubusercontent.com/4571457/56380110-44b7ac80-61df-11e9-82b7-86e17f488200.jpg)

**Comment by chasenlehara** [comment]
On tablet/desktop, we should:

- Add the GitHub and Twitter buttons that were hidden in the header
- Include a link to the forums

Maybe instead of just links, we can also have logos (e.g. Discourse & Slack logos)?
