### ISSUE TITLE
Should we export can-kefir as { kefir } or { Kefir } ?

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4770]
Kefir’s docs show uppercase `Kefir`: https://kefirjs.github.io/kefir/

can-kefir’s docs follow suit and show uppercase `Kefir`: https://canjs.com/doc/can-kefir.html

…but as far as I can tell, Kefir isn’t a constructor function. I don’t see any reason why it should be uppercase, other than to be consistent with the original Kefir docs.

Right now, we export lowercase `kefir`: https://github.com/canjs/canjs/blob/7b6aed59b9040d4f6b28ca43cf46755df5c60744/ecosystem.js#L6

Should we keep this and update our docs to show lowercase `kefir`? Or should we export `Kefir` instead?

This blocks [updating the advanced credit card guide](https://github.com/canjs/canjs/issues/4622).

**Comment by phillipskevin** [comment]
I think we should keep it consistent with Kefir's docs and Kefir's code and export `Kefir`.
