### ISSUE TITLE
"quick" homepage review

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#4773]
![image](https://user-images.githubusercontent.com/78602/54549575-53a90600-4978-11e9-9310-16e7386d695c.png)

## Navigation

- [x] `P0`"Build CRUD apps in fewer lines of code" in header 
- [x] `P0` Back button shows a huge section: 
![image](https://user-images.githubusercontent.com/78602/54551177-8bfe1380-497b-11e9-890f-94ab8dc42e46.png)

## Hero

- [x] "Learn how to build a CRUD app" button doesn't look like a button. `P1`
- [x] Learn how to build a CRUD app ... should it be ... learn how to build this ➡️ CRUD app? `P1`
- [ ] Would be nice to have CanJSy things in the todos. `P4`

## Triple Threat

- [x] Hover effect on "model layer / promises / etc" is weighty/unnecessary. I see this is to make them buttons.  I'm not sure what a better solution might be.  Maybe "learn more" link? `P1`
- [x] Blue and dotted lines feel a bit out of place 
![image](https://user-images.githubusercontent.com/78602/54549822-df229700-4978-11e9-8e16-73d490f6eae2.png)

### Model Layer

- [x] Your/you use ... should we write "Components shouldn't be concerned with how your data is fetched, cached, or ... "?
- [x] How your data is fetched, updated, or cached. I re-arranged to group fetched & cached. It would be nice to have some other examples.  
- [x] Model Layer animation - Why double arrows?  Why animated? Should components have arrows with models?
- [x] Remove animation `P1`

### Promises in templates

- [ ] Should we also mention it can do this with observables like kefir?
- [x] Why this animation instead of the code?
- [ ] Maybe that state diagram works better ... 
- [ ] I wonder if ndjson stuff / streaming responses would be nice here.
- [x] Link to promises?
- [x] No extra code ... should be "There's no extra code to ...."

### Real-time list updating

- [ ] Should this be real-time list management?

## Community has your back

- [x] Link to Bitovi 
- [x] I think we could be more aggressive on stating how much we want to help

## Get started with just a few lines of code

- [x] Below is an entire CanJS app `that` shows off some of the best features of CanJS:
- [ ] to-do vs todo?
- [x] Have it start with only 2 or 3 todos so it isn't cut off by the page
- [ ] The bullet points about the best features should reference the explanations later somehow ...

### Model layer

- [x] Might want to code "API" a bit better.  Meaning always use "backend API" or "service API".  It's confusing what you mean by just _API_.
- [x] We might want the code example to include:
  ```
  Todo.getList({sort: "name"}); 
  ```
- [x] > you only have to change the model code and not every component that uses that API.

   you only have to configure the model and not change every component that uses that API.
- [x] > Additionally, CanJS starts off by assuming your API is RESTful, which is a lot of code for each model that you don’t have to write.

   By default, CanJS assumes a RESTful backend API. If the backend API ...
   
### Promises in templates

- [x] `P2` Space this how stache recommends.  `{{# if( this.todosPromise.isPending ) }}`

### Real-time list updating

- [ ] Should this show `.save()`?

## Trusted by Enterprise companies 

- [x] Remove enterprise I think

**Comment by chasenlehara** [comment]
More changes:

- [ ] Hovering over CRUD should show a longer explanation of what CRUD is.
- [ ] Change the “Our community has your back” copy to something like “We have your back” and emphasize that we answer every question.
- [ ] Make a list of all the forum posts we never responded to.
- [ ] Add more spacing between the community block and the Model layer explanation header.
- [ ] The code example needs to be vertically centered at wider screen widths:
<img width="1537" alt="Screen Shot 2019-04-03 at 2 39 22 PM" src="https://user-images.githubusercontent.com/10070176/55515009-52d1ce80-561e-11e9-8809-77bb70b8f68e.png">
