### ISSUE TITLE
Set up Travis deploy with new API key

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#4782]
I generated a new API key for the `bitovi-core-os` user because the old key was revoked, so we'll need to run the setup process for travis deployments again. The steps to do this are:

1. remove the `deploy` section from the `.travis.yml` file
2. run `travis setup npm`
3. commit the new `.travis.yml` file

I ran this on `can-dom-events` and verified the new key is working:

![image](https://user-images.githubusercontent.com/5851984/54947922-7a7fb300-4f09-11e9-9df3-622433c32c18.png)

I think these repos need to be done (there might be more, I'm not sure:

- grunt-testee
- can-dom-event-radiochange
- can-event-dom-enter
- can-dom-mutate

**Comment by chasenlehara** [comment]
I think these are all the repos that need to be updated:

- [ ] https://github.com/bitovi/grunt-testee
- [ ] https://github.com/bitovi/testee
- [ ] https://github.com/bitovi/testee-client
- [x] https://github.com/canjs/can-dom-events
- [ ] https://github.com/canjs/can-dom-mutate
- [ ] https://github.com/canjs/can-event-dom-enter
- [ ] https://github.com/canjs/can-event-dom-radiochange
- [ ] https://github.com/canjs/can-model
- [ ] https://github.com/canjs/can-reflect

**Comment by phillipskevin** [comment]
I generated new keys for all of these repos.
