### ISSUE TITLE
Stache element mixin

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#4801]
For 6.0 we'd like to start making parts of CanJS available as mixins for custom element creation. The primary API would be decorators but it should work seamlessly as class mixins as well. For example:

```js
import { withStache } from "can";

const template = `
  <span>Hello {{name}}</span>
`;

@withStache(template)
class MyElement extends HTMLElement {

}

customElements.define('my-element', MyElement);
```

**Comment by phillipskevin** [comment]
We've moved away from using decorators, but the mixin is available here: https://github.com/canjs/can-stache-element/blob/403c24d71961024baf754bb2b1741a2a814dd35d/src/mixin-stache-view.js.
