### ISSUE TITLE
Upgrade to QUnit 2

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4823]
This upgrade should help us avoid issues like what was found with https://github.com/canjs/canjs/issues/4789

Cherif ran [a codemod](https://gist.github.com/cherifGsoul/e82fd3546da2c3bdabe4b4b9c918d361) that opened a bunch of PRs titled [Landscaper: QUnit2 upgrade](https://github.com/search?o=desc&q=org%3Acanjs+is%3Apr+is%3Aopen+%22Landscaper%3A+QUnit2+upgrade%22&s=created&type=Issues).

Greenkeeper also opened PRs to upgrade to steal-qunit@2 (and thus QUnit 2): [Update steal-qunit to the latest version 🚀](https://github.com/search?o=desc&q=org%3Acanjs+%22Update+steal-qunit+to+the+latest+version%22+is%3Aopen+is%3Apr&s=created&type=Issues)

Some of these are already passing, but most of them will require a little bit of work.

QUnit has an [upgrade guide](https://qunitjs.com/upgrade-guide-2.x/) that outlines all the changes required.

Here’s what still needs to be done for each of the repos below:

1. Find the latest Landscaper or Greenkeeper PR.
2. Clone the repo locally.
3. Check out the branch locally (it’s probably named `landscaper/qunit2` or `greenkeeper/steal-qunit-2.0.0`).
4. Run `npm install --no-shrinkwrap && npm test`
5. If there are JSHint errors, fix those first.
6. With an HTTP server running, open the test HTML page. It’s usually `test.html` or `test/test.html`, but you can check the repo’s `package.json` file for the `testee` script and see which HTML file it opens.
7. When all the tests are passing (run `npm test` to confirm)…
8. Make a commit `git commit -m "Fix tests for QUnit 2"`
9. Push to GitHub: `git push`
10. Check that the build passes on GitHub
11. Add a link to the PR and check off the box in the list. Make sure you refresh the page first so you have the latest edits.

## When all the repos are ready

When _all_ of the branches are ready, the main [canjs/canjs](https://github.com/canjs/canjs) repo can be updated.

1. Merge & release all of the packages in the list (patch release is fine, but be sure to check that nothing else has been merged & not released that would make it a minor or major version bump).
2. When everything’s released, create a new branch off `master` in the main CanJS repo and run `npm run outdated`. Update all the necessary packages to their new patch versions.
3. Also run the codemod on this repo / update steal-qunit.
4. Fix any remaining issues with the build.
5. Merge & release a new version of CanJS (Kevin or Matthew can also help with this).

If everything’s been updated, I would expect the tests to pass. If any packages were missed, then there might be issues with having multiple versions of QUnit/steal-qunit.

---

_[Old info that’s not relevant anymore:]_

[Codemod tool](https://github.com/apsdehal/qunit-migrate)

Here’s how the codemod tool can be used.

**Install:** `npm i -g qunit-migrate` [only run this once]

**Run:** `qunit-migrate "*-test.js" -w --no-jscs`

You might need to run `qunit-migrate "test/*.js" -w --no-jscs` in some repos because the files are in a `test` folder.

**Fix:** `find . -type f -name '*-test.js' -exec sed -i '' 's/QUnit.deepEqual/assert.deepEqual/; s/QUnit.equal/assert.equal/; s/QUnit.notDeepEqual/assert.notDeepEqual/; s/QUnit.notEqual/assert.notEqual/; s/QUnit.notPropEqual/assert.notPropEqual/; s/QUnit.notStrictEqual/assert.notStrictEqual/; s/QUnit.ok/assert.ok/; s/QUnit.propEqual/assert.propEqual/; s/QUnit.strictEqual/assert.strictEqual/; s/QUnit.throws/assert.throws/; s/stop()/var done = assert.async()/; s/QUnit.start()/done()/' {} +`

The codemod tool doesn’t replace `QUnit.deepEqual` with `assert.deepEqual`, and other calls that need to be changed, so the command above replaces (I think everything?) that needs to be changed.

Additionally, the codemod says it can migrate async tests, but it doesn’t seem to in all cases. The command above will replace `stop()` with `var done = assert.async()` and `QUnit.start()` with `done()` to fix most cases.

After this, JSHint and the tests should pass, but if they don’t, some manual fixing might be required. If you make more more robust commands to automate the migration, leave a comment on this issue.

**Comment by cherifGsoul** [comment]
- [ ] can-attribute-encoder [PR opened](https://github.com/canjs/can-attribute-encoder/pull/31/files)
- [ ] can-debug
- [ ] can-stache-key
- [ ] can-dom-mutate
- [ ] can-event-dom-enter
- [ ] can-reflect-promise
- [ ] can-event-dom-radiochange
- [ ] can-make-rest
- [ ] can-dom-events
- [ ] can-globals
- [ ] can-make-map
- [ ] can-parse-uri
- [ ] can-assign
- [ ] can-deparam
- [ ] can-param
- [ ] can-ajax
- [ ] can-reflect
- [ ] can-symbol
- [ ] can-connect-ndjson
- [ ] can-define-validate-validatejs
- [ ] can-define-stream-kefir
- [ ] can-types
- [ ] can-connect-singlr
- [ ] can-validate-legacy
- [ ] can-validate-validatejs
- [ ] can-compute-memoize
- [ ] can-fixture-socket
- [ ] can-define-stream
- [ ] can-contruct-super
- [ ] can-stache-converters
- [ ] can-stream-kefir
- [ ] bit-docs-html--canjs
- [ ] can-simple-map
- [ ] steal-stache
- [ ] can-route-pushstate
- [ ] can-view-model
- [ ] can-stache
- [ ] can-observation
- [ ] can-jquery
- [ ] can-view-target
- [ ] can-view-scope
- [ ] can-view-parser
- [ ] can-view-nodelist
- [ ] can-view-live
- [ ] can-view-import
- [ ] can-view-callbacks
- [ ] can-stache-bindings
- [ ] can-view-autorender
- [ ] can-map-define
- [ ] can-map
- [ ] can-list
- [ ] can-event
- [ ] can-route
- [ ] can-control
- [ ] can-construct
- [ ] can-component
- [ ] can-compute
- [ ] can-util
- [ ] can-view-href
- [ ] can-map-backup
- [ ] can-test-helpers [PR opened](https://github.com/canjs/can-test-helpers/pull/16)
- [ ] can-mustache
- [ ] can-ejs
- [ ] can-define
- [ ] can-fixture
- [ ] can-observe
- [ ] node-route
- [ ] dom-patch
- [ ] can-validate
- [ ] can-set
- [ ] can-connect
- [ ] canjs
- [ ] can-feathers
- [ ] can-define-singleton
- [ ] can-map-compat
- [ ] can-route-hash
- [ ] can-route-mock
- [ ] can-join-uris
- [ ] can-child-nodes
- [ ] can-fragment
- [ ] can-data-types
- [ ] can-import-module
- [ ] can-local-store
- [ ] can-super-model
- [ ] can-rest-model
- [ ] can-realtime-rest-model
- [ ] can-devtools-components
- [ ] can-string-to-any
- [ ] can-bind
- [ ] can-set-legacy
- [ ] can-diff
- [ ] can-value
- [ ] can-memory-store
- [ ] can-dom-data
- [ ] can-key
- [ ] can-string
- [ ] can-stache-ast
- [ ] can-attribute-observable
- [ ] can-define-list
- [ ] can-define-map
- [ ] can-stache-helpers
- [ ] can-event-radiochange
- [ ] can-reflect-dependencies
- [ ] can-stache-route-helpers
- [ ] can-observation-recorder
- [ ] can-event-queue
- [ ] can-lazy-value
- [ ] can-query-logic
- [ ] can-log
- [ ] can-dom-data-state
- [ ] can-simple-observable
- [ ] can-key-tree
- [ ] can-legacy-view-helpers
- [ ] can-reflect-tests
- [ ] can-define-lodash
- [ ] can-list-sort
- [ ] can-map-attributes
- [ ] can-model
- [ ] worker-render

**Comment by chasenlehara** [comment]
# Released

Check the ones that have been merged & released.

- [ ] can-ajax [PR](https://github.com/canjs/can-ajax/pull/62)
- [ ] can-assign [PR](https://github.com/canjs/can-assign/pull/18)
- [ ] can-attribute-encoder [PR](https://github.com/canjs/can-attribute-encoder/pull/37)
- [ ] can-attribute-observable [PR](https://github.com/canjs/can-attribute-observable/pull/35)
- [ ] can-bind [PR](https://github.com/canjs/can-bind/pull/20)
- [ ] can-child-nodes [PR](https://github.com/canjs/can-child-nodes/pull/11)
- [ ] can-cid [PR](https://github.com/canjs/can-cid/pull/43/)
- [ ] can-component [PR](https://github.com/canjs/can-component/pull/352)
- [ ] can-compute [PR](https://github.com/canjs/can-compute/pull/146)
- [ ] can-connect [PR](https://github.com/canjs/can-connect/pull/469)
- [ ] can-connect-feathers [PR](https://github.com/canjs/can-connect-feathers/pull/147) (Sauce labs error)
- [ ] can-connect-ndjson [PR](https://github.com/canjs/can-connect-ndjson/pull/19)
- [ ] can-connect-tag [PR](https://github.com/canjs/can-connect-tag/pull/3)
- [ ] can-construct [PR](https://github.com/canjs/can-construct/pull/74)
- [ ] can-construct-super [PR](https://github.com/canjs/can-construct-super/pull/53)
- [ ] can-control [PR](https://github.com/canjs/can-control/pull/135)
- [ ] can-data-types [PR](https://github.com/canjs/can-data-types/pull/11)
- [ ] can-debug [PR](https://github.com/canjs/can-debug/pull/72)
- [ ] can-define [PR](https://github.com/canjs/can-define/pull/452)
- [ ] can-define-backup [PR](https://github.com/canjs/can-define-backup/pull/22)
- [ ] can-define-lazy-value [PR](https://github.com/canjs/can-define-lazy-value/pull/9)
- [ ] can-define-stream [PR](https://github.com/canjs/can-define-stream/pull/72)
- [ ] can-define-stream-kefir [PR](https://github.com/canjs/can-define-stream-kefir/pull/37)
- [ ] can-define-validate-validatejs [PR](https://github.com/canjs/can-define-validate-validatejs/pull/60)
- [ ] can-deparam [PR](https://github.com/canjs/can-deparam/pull/15)
- [ ] can-diff [PR](https://github.com/canjs/can-diff/pull/18)
- [ ] can-dom-data [PR](https://github.com/canjs/can-dom-data/pull/10)
- [ ] can-dom-data-state [PR](https://github.com/canjs/can-dom-data-state/pull/37)
- [ ] can-dom-events [PR](https://github.com/canjs/can-dom-events/pulls)
- [ ] can-dom-mutate [PR](https://github.com/canjs/can-dom-mutate/pull/56)
- [ ] can-event-dom-enter [PR](https://github.com/canjs/can-event-dom-enter/pull/26)
- [ ] can-event-dom-radiochange[PR](https://github.com/canjs/can-event-dom-radiochange/pull/24)
- [ ] can-event-queue[PR](https://github.com/canjs/can-event-queue/pull/31)
- [ ] can-fixture [PR](https://github.com/canjs/can-fixture/pull/169)
- [ ] can-fixture-socket [PR](https://github.com/canjs/can-fixture-socket/pull/76)
- [ ] can-fragment [PR](https://github.com/canjs/can-fragment/pull/11)
- [ ] can-globals [PR](https://github.com/canjs/can-globals/pull/54)
- [ ] can-kefir [PR](https://github.com/canjs/can-kefir/pull/24)
- [ ] can-key [PR](https://github.com/canjs/can-key/pull/10)
- [ ] can-key-tree [PR](https://github.com/canjs/can-key-tree/pull/19)
- [ ] can-list [PR](https://github.com/canjs/can-list/pull/92)
- [ ] can-local-store [PR](https://github.com/canjs/can-local-store/pull/7)
- [ ] can-log [PR](https://github.com/canjs/can-log/pull/17)
- [ ] can-make-map [PR](https://github.com/canjs/can-make-map/pull/13)
- [ ] can-map [PR](https://github.com/canjs/can-map/pull/135)
- [ ] can-map-compat [PR](https://github.com/canjs/can-map-compat/pull/9)
- [ ] can-map-define [PR](https://github.com/canjs/can-map-define/pull/104)
- [ ] can-memory-store [PR](https://github.com/canjs/can-memory-store/pull/9)
- [ ] can-namespace (without tests)
- [ ] can-ndjson-stream [PR](https://github.com/canjs/can-ndjson-stream/pull/49)
- [ ] can-observation [PR](https://github.com/canjs/can-observation/pull/146)
- [ ] can-observation-recorder [PR](https://github.com/canjs/can-observation-recorder/pull/17)
- [ ] can-observe [PR](https://github.com/canjs/can-observe/pull/82)
- [ ] can-param [PR](https://github.com/canjs/can-param/pull/16)
- [ ] can-parse-uri [PR](https://github.com/canjs/can-parse-uri/pull/11)
- [ ] can-query-logic [PR](https://github.com/canjs/can-query-logic/pull/44)
- [ ] can-queues [PR](https://github.com/canjs/can-queues/pull/28)
- [ ] can-realtime-rest-model [PR](https://github.com/canjs/can-realtime-rest-model/pull/9)
- [ ] can-reflect [PR](https://github.com/canjs/can-reflect/pull/160)
- [ ] can-reflect-dependencies [PR](https://github.com/canjs/can-reflect-dependencies/pull/27)
- [ ] can-reflect-promise [PR](https://github.com/canjs/can-reflect-promise/pull/31)
- [ ] can-rest-model [PR](https://github.com/canjs/can-rest-model/pull/9)
- [ ] can-route [PR](https://github.com/canjs/can-route/pull/239)
- [ ] can-route-hash [PR](https://github.com/canjs/can-route-hash/pull/10)
- [ ] can-route-mock [PR](https://github.com/canjs/can-route-mock/pull/7)
- [ ] can-route-pushstate [PR](https://github.com/canjs/can-route-pushstate/pull/150)
- [ ] can-set-legacy [PR](https://github.com/canjs/can-set-legacy/pull/5)
- [ ] can-simple-dom [PR](https://github.com/canjs/can-simple-dom/pull/92)
- [ ] can-simple-map [PR](https://github.com/canjs/can-simple-map/pull/72)
- [ ] can-simple-observable [PR](https://github.com/canjs/can-simple-observable/pull/41)
- [ ] can-stache [PR](https://github.com/canjs/can-stache/pull/690)
- [ ] can-stache-bindings [PR](https://github.com/canjs/can-stache-bindings/pull/534)
- [ ] can-stache-converters [PR](https://github.com/canjs/can-stache-converters/pull/102)
- [ ] can-stache-key [PR](https://github.com/canjs/can-stache-key/pull/46)
- [ ] can-stache-route-helpers[PR](https://github.com/canjs/can-stache-route-helpers/pull/22)
- [ ] can-stream [PR](https://github.com/canjs/can-stream/pull/16)
- [ ] can-stream-kefir [PR](https://github.com/canjs/can-stream-kefir/pull/79)
- [ ] can-string [PR](https://github.com/canjs/can-string/pull/7)
- [ ] can-string-to-any [PR](https://github.com/canjs/can-string-to-any/pull/7)
- [ ] can-super-model [PR](https://github.com/canjs/can-super-model/pull/7)
- [ ] can-symbol [PR](https://github.com/canjs/can-symbol/pull/36)
- [ ] can-validate [PR](https://github.com/canjs/can-validate/pull/80)
- [ ] can-validate-interface [PR](https://github.com/canjs/can-validate-interface/pull/14)
- [ ] can-validate-legacy [PR](https://github.com/canjs/can-validate-legacy/pull/59)
- [ ] can-validate-validatejs [PR](https://github.com/canjs/can-validate-validatejs/pull/30)
- [ ] can-value [PR](https://github.com/canjs/can-value/pull/29)
- [ ] can-vdom (mocha)
- [ ] can-view-autorender [PR](https://github.com/canjs/can-view-autorender/pull/99)
- [ ] can-view-callbacks [PR](https://github.com/canjs/can-view-callbacks/pull/115)
- [ ] can-view-live [PR](https://github.com/canjs/can-view-live/pull/139)
- [ ] can-view-model [PR](https://github.com/canjs/can-view-model/pull/76)
- [ ] can-view-nodelist [PR](can-view-nodelist)
- [ ] can-view-parser [PR](https://github.com/canjs/can-view-parser/pull/103)
- [ ] can-view-scope [PR](https://github.com/canjs/can-view-scope/pull/202)
- [ ] can-view-target [PR](https://github.com/canjs/can-view-target/pull/76)
- [ ] steal-stache [PR](https://github.com/canjs/steal-stache/pull/78)
