### ISSUE TITLE
Refine the homepage

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4833]
- [x] Use the right blue everywhere on the homepage (see the [brand guide](https://github.com/bitovi/brain/blob/master/logos/canjs/canjs_brand_guide.pdf))
- [x] Add the GitHub and Twitter buttons to the “We have your back” section
- [x] Add more spacing between the community block and the Model layer explanation header.
- [x] Instead of having the diagrams go to the right of the text at wider screen widths, let’s remove this code and force a max-width that keeps the page looking good. <img width="1537" alt="Screen Shot 2019-04-03 at 2 39 22 PM" src="https://user-images.githubusercontent.com/10070176/55515009-52d1ce80-561e-11e9-8809-77bb70b8f68e.png">
- [x] Consistently line everything up; examples of the left edges not being lined up in this gif:
![alignment](https://user-images.githubusercontent.com/10070176/56700859-3838c580-66b1-11e9-9b0f-3551a8726c88.gif)
- [x] When the page first loads, there’s a white space above the gray area that appears and then disappears when the page is fully loaded. Maybe because the styles are inline in the page, and maybe it’ll be fixed by the scroll fixes.
![jump](https://user-images.githubusercontent.com/10070176/57644618-5cc9e400-7571-11e9-9a9f-882c366c197a.gif)

**Comment by jamiemccue** [comment]
- I made the requested adjustments to the homepage including tweaking margins and spacing for the various breakpoints. Also updated the blue hex values, added social media logos, and fixed the alignment of images on smaller breakpoints. 

- The one request that I feel we should leave (at least for desktop) is the `Consistently line everything up` - while I can see where the request is coming from I feel from an overall design perspective not having all the text align on desktop helps the visual hierarchy. It breaks the page up more. However, I did align the elements on smaller breakpoints which looks better. 

- I changed the button color to a dark grey which gives it more emphasis and breaks the page colors up. There is a lot of blue and grey. Here is an example: 

![button-colors](https://user-images.githubusercontent.com/381138/58574582-25a43580-81f5-11e9-8825-8668f1e77123.png)

- For the font headings I increased the font weight slightly from 300 to 400. By increasing the weight it gives them more prominence and legibility to the heading. Here is an example: 

![font-weights](https://user-images.githubusercontent.com/381138/58574421-cc3c0680-81f4-11e9-9e2f-16f2cadd3d7e.png)

Overall screenshot:

![screencapture-127-0-0-1-8080-2019-05-29-08_57_00](https://user-images.githubusercontent.com/381138/58574698-69973a80-81f5-11e9-9300-eb32513fb052.png)

**Comment by chasenlehara** [comment]
> The one request that I feel we should leave (at least for desktop) is the Consistently line everything up - while I can see where the request is coming from I feel from an overall design perspective not having all the text align on desktop helps the visual hierarchy. It breaks the page up more. However, I did align the elements on smaller breakpoints which looks better.

I think it looks sloppy as-is. The page is already broken up by the use of the white and gray blocks.

> I changed the button color to a dark grey which gives it more emphasis and breaks the page colors up. There is a lot of blue and grey.

The blue buttons look more like buttons to me than the dark gray ones. I like that the blue buttons are consistent with the other thing we want people to click, links.

Regarding the GitHub and Twitter buttons: I’d like to see what that section looks like with:

1) The same GitHub and Twitter buttons at the top of every [v4](https://v4.canjs.com/) page.
2) More consistent icons (GitHub logo & name and Twitter & name), like the Slack and Discourse logos.

Please create a PR with what you have so we can talk through the specifics over a live page. 😃

**Comment by jamiemccue** [comment]
@chasenlehara 
- I updated the margins as requested
- Reverted the button back to blue
- The logos you requested are not their official logos so they do not provide them. Unlike Slack and Discourse which include the icon with the name. How do you want to proceed?
