### ISSUE TITLE
codesandbox.io - Simple example doesn't work

### ISSUE THREAD

**Issue by BigAB** [canjs/canjs#4863]
The best of all online code editors [codesandbox.io](https://codesandbox.io) can't seem to run a simple CanJS example.
https://codesandbox.io/s/61ypnzyqjr

I don't expect to know what to do about this, as this exact example seems to work locally (with parcel setup with exactly the same code), so I think it has something to do with CodeSandbox itself, but it does make me think we may need to rethink our assumptions about how we handle our stateful modules.

I don't have any solutions or suggestions so feel free to close this issue, but I was saddened to see I couldn't use my favourite online editor for CanJS examples.

**Comment by chasenlehara** [comment]
I see “My CanJS Demo” in Chrome, Firefox, & Safari after updating the example to use the latest version of CanJS (5.24.0): https://codesandbox.io/s/zly8m10qql

**Comment by matthewp** [comment]
I think there might have been a period where some packages were using an old version of can-dom-data-state which caused multiple versions to exist. I'll take the blame for this, I should have done a better job coordinating to make sure that didn't happen.

**Comment by BigAB** [comment]
Yay!  Okay, cool.  Closing
