### ISSUE TITLE
AMD template plugin support

### ISSUE THREAD

**Issue by isadovskiy** [canjs/canjs#491]
This issue is for creating plugins that can build templates for AMD similar to the "system" plugins for SystemJS: https://github.com/bitovi/canjs/blob/e82f1ea44e0857f29302cf9cfcdfd1e9fda4bf6e/view/stache/system.js.

@isadovskiy has already has it working for EJS here: https://github.com/isadovskiy/canjs-require-ejs

@isadovskiy 's original comment:

> I finalized the EJS templates plugin for CanJS with templates pre-compilation support. Sources are example are available here: https://github.com/isadovskiy/canjs-require-ejs

> There are few configuration tricks, which should be done in config.js and build.js in order to make everything works. I will explain them later in readme. CanJS library sources are also tweaked a little bit to eliminate direct dependencies from window and document in the source files, which are required for EJS templates compilation.

> CanJS team, if you are interesting in integration this solution into your framework, I can provide all necessary information and support.

**Comment by justinbmeyer** [comment]
@isadovskiy I would like to get this into CanJS.  Can I rename / cleanup the issue to make it clear that we would support plugins for building stache / mustache / ejs templates?  Thanks.

**Comment by isadovskiy** [comment]
Sure! No any objections from my side.

**Comment by justinbmeyer** [comment]
@isadovskiy are you interested in making this work similar to https://github.com/canjs/steal-stache for 3.0?  Our goal is to have these things in separate repos for 3.0, but list all of these 3rd party integrations on the homepage.  

I'm going to close, but let me know and I'll create a `require-stache` repo.  Thanks!

**Comment by isadovskiy** [comment]
@justinbmeyer at the moment we are completely switched to StealJS. So we ar not so interested in AMD support. 

I also see https://github.com/canjs/steal-stache already supports AMD/RequireJS. Or am I missing anything?

**Comment by rjgotten** [comment]
> Or am I missing anything?

It doesn't seem to have an actual AMD loader plugin anywhere in the source, so there's no way to, e.g., do:
```js
define([
  "can/component",
  "stache!./my-template.stache"
], function( Component, template ) {
  return Component.extend({
    tag      : "my-component",
    template : template
  })
});
```

and to have that transparently work with both development builds and optimized production builds.

Maybe it's generated as part of the `dist` build, but I have no way to verify that, as installing the required dev dependencies with NPM to make  abuild, leads to a 100% reproducible `EBUSY rename` error on Windows.

There are also other issues related to loading stache templates via AMD, such as the fact that `<can-import>` doesn't support AMD-based module lookups. Doing that properly, i.e. , including all the AMD idioms such as relative module ID lookups; proper honoring of `package`, `map` and `path` directives and support for plugin loaders is non-trivial.

**Comment by matthewp** [comment]
There is no AMD plugin in this repo, that is correct. There is a plugin a community member created but I'm having trouble finding it right now.

can-import should definitely work with Requirejs, we detect if running inside an AMD loader and call the dynamic loader: https://github.com/canjs/canjs/blob/master/util/can.js#L198-L200  This logic is tested with requirejs.

**Comment by gsmeets** [comment]
That community member would be me. ;)
I have that stache amd plugin loader working in my private repo. The public repo is a bit outdated (https://github.com/Empirion/can-stache-amd) 

I've been murderously busy at work past 6 months, so I haven't even had the time to get that updated and documented. (So maybe you should reconsider my offer @rjgotten :P) If there's definite interest from someone then drop me a line. If not, updating that repository is still on my todo list somewhere in the next few weeks.

**Comment by rjgotten** [comment]
> @matthewp
> can-import should definitely work with Requirejs, we detect if running inside an AMD loader and call the dynamic loader: https://github.com/canjs/canjs/blob/master/util/can.js#L198-L200 This logic is tested with requirejs.

Simply using the global `require` entrypoint on the window is not sufficient. Like I wrote:
> Doing that properly, i.e. , including all the AMD idioms such as **relative module ID lookups** (...) is non-trivial.

You need some intermediate logic to create a `require` that is local and relative to the generated module ID of the stache template that was loaded through the loader plugin.

You have to go through a two-step require-chain to get that working; first use a loader plugin engineered to retrieve a `require` that is rebased to the module ID passed to the loader plugin, then use that rebased `require` to resolve the import. I.e.

```js
if (window.define && window.define.amd) {
  if ( parentName ) {
    window.require(["can/util/amd/rebase!" + parentName], function(require) {
      require([moduleName], function (value) {
        deferred.resolve(value);
      });
    });
  } else {
    window.require([moduleName], function (value) {
      deferred.resolve(value);
    });
  }
}
```
where the `rebase` plugin is implemented as:
```js
define([], function() {
  var
    rootRequire = require,
    hasUndef    = "undef" in rootRequire;

  return {
    load : function(name, require, load, config) {
      // Temporary collision-free name at the same relative
      // directory level as the reference name.
      name += "#require";

      define(name, ["require"], function(require) {
        return require;
      });

      require([name], function(require) {
        hasUndef && rootRequire.undef(name);
        load(require);
      }, function(err) { load.error(err); });
    }
  }
});
```



> @gsmeets
> That community member would be me. ;)

It keeps surprising me that when either of us sits down to engineer something, we always tend to arrive at a similar solution. (One thing tho': you might want to refactor your builder to hook up the intermediate AST that the build process generated, instead of having the client reparse the template. Seems wasteful. ;-) )

**Comment by matthewp** [comment]
> You need some intermediate logic to create a require that is local and relative to the generated module ID of the stache template that was loaded through the loader plugin.

That's true, relative is currently not working with AMD modules. The Steal plugin includes the current module id (that is the id of the stache module once compiled to js), so the AMD plugin could do the same. We'd need some way to pass your own require instead of using `window.require` though. Very opening to collaborating with requirejs users to make sure our APIs support such a plugin.

**Comment by gsmeets** [comment]
@rjgotten 

> It keeps surprising me that when either of us sits down to engineer something, we always tend to arrive at a similar solution. 

In this particular case I based it off of your old ejs amd version, combined with some other implementation I found floating around the interwebs. ;)

> One thing tho': you might want to refactor your builder to hook up the intermediate AST that the build process generated, instead of having the client reparse the template. Seems wasteful. ;-) 

I would if it actually performed better, but it doesn't. Parsing the text performed a lot better, can't remember the exact numbers, but it was > 20% perf. Discussed it with @justinbmeyer back then on gitter, and he seemed as surprised as I was. I spent a good amount of time trying to find out why, but I couldn't. The AST was just slower than the text. I still have the benchmark code somewhere shelved away...

**Comment by rjgotten** [comment]
> The AST was just slower than the text.

That's slightly crazy and somewhat interesting. There's no reason that should happen from a code complexity point of view. So it has to have something to do with compiler optimizations.

I wonder if it has to do with https://github.com/canjs/canjs/blob/master/view/parser/parser.js#L21 and the fact that `Function.prototype.apply` is called with the array of args stored in the intermediate representation. Using `apply` is substantially slower than `call` with a fixed number of arguments, which internally desugars to the exact same operation as a regular function call and thus can be far more optimized.

I wonder what would happen when a set of intermediate functions that explicitly expands the item's `args` array to direct calls with the correct number of arguments for each token type is used instead.

i.e. 
```js
var arities = [
  function(handler, item, args) { return handler[item.tokenType]() },
  function(handler, item, args) { return handler[item.tokenType](args[0]) },
  function(handler, item, args) { return handler[item.tokenType](args[0],args[1]) },
  function(handler, item, args) { return handler[item.tokenType](args[0],args[1],args[2]) }
  // ...
];
function handleIntermediate(intermediate, handler){
  for(var i = 0, len = intermediate.length; i < len; i++) {
    var item = intermediate[i];
    arities[item.args.length](handler, item, item.args);
  }
  return intermediate;
}
```


I might just have to try that out some time. :)

**Comment by matthewp** [comment]
Cool idea!
