### ISSUE TITLE
Make more homepage refinements

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#4999]
- [x] Fix the jump in the hero section when the homepage first loads
- [x] Remove the GitHub and Twitter logos from the “We have your back” section
- [x] [Make the code example a little taller so no scrollbar appears in the result pane in Firefox](https://user-images.githubusercontent.com/10070176/58900058-410ab700-86b3-11e9-9ec7-7c4aa5000c78.png)
- [x] [Align the diagrams in the three columns on the homepage](https://github.com/canjs/canjs/pull/5010#issuecomment-500083430)
- [x] Apply a max-width to the entire page

**Comment by jamiemccue** [comment]
@chasenlehara The problem with the diagram alignment is the SVG's have different amounts of whitespace on the top so they will not align equally. 

<img width="1351" alt="Screen Shot 2019-06-10 at 8 39 36 AM" src="https://user-images.githubusercontent.com/381138/59207917-e236b900-8b5c-11e9-9bf3-392f31c98411.png">
