### ISSUE TITLE
Implement content select attribute

### ISSUE THREAD

**Issue by imjoshdean** [canjs/canjs#500]
[VOTE HERE](http://bithub.com/event/25882)

http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom/#toc-projection

Currently in can.Component, it seems that you can only use one <content/> tag in the component template, it seems like where components is going is to not only allow more than one content tag, but to specify what the content element projects. This is done via a select property on the content node.

Currently:
===

DOM: 
```
<hello>Bob</hello>
```

"hello" Template: 
```
<h1><content/></h1>
```

Rendered:
```
<hello><h1>Bob</h1></hello>
```
Proposal:
===

DOM: 
```
<hello>
  <div class="name">Bob</div>
  <div class="email">bob@bitovi.com</div>
</hello>
```

"hello" Template:

```
<h1>My name is <content select=".name"/></h1>
<h2>Email me at <content select=".email"/></h2>
```

Rendered:

```
<hello>
  <h1>My name is Bob</h1>
  <h2>Email me at bob@bitlvi.com</h2>
</hello>
```

VOTE FOR THIS HERE: http://bithub.com/event/25882

**Comment by whitecolor** [comment]
Is it going to be in 2.3 or anytime soon?

**Comment by matthewp** [comment]
No, not in 2.3 at least.

**Comment by justinbmeyer** [comment]
Closing for #2278 which will be far easier to implement.
