### ISSUE TITLE
Fix the homepage hero image in Edge

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#5002]
It currently looks like this:
<img width="507" alt="Screen Shot 2019-06-04 at 1 05 07 PM" src="https://user-images.githubusercontent.com/10070176/58913927-26940600-86d2-11e9-8fce-dcbcbf6463ad.png">

**Comment by jamiemccue** [comment]
https://github.com/canjs/canjs/pull/5045

**Comment by chasenlehara** [comment]
Fixed by https://github.com/canjs/canjs/pull/5045
