### ISSUE TITLE
Add Template Inheritance to can.Mustache

### ISSUE THREAD

**Issue by ccummings** [canjs/canjs#507]
See this discussion in the spec: https://github.com/mustache/spec/issues/38

This is implemented by 3 other mustache engines, namely:
[GRMustache](https://github.com/groue/GRMustache/blob/master/Guides/partials.md#overriding-portions-of-partials)
[mustache.java](https://github.com/spullara/mustache.java)
[hogan.js](https://github.com/twitter/hogan.js)

**Comment by groue** [comment]
The correct link to the GRMustache documentation of template inheritance is https://github.com/groue/GRMustache/blob/master/Guides/template_inheritance.md

**Comment by justinbmeyer** [comment]
I'm closing this unless someone really needs it.

In the mean time, I'll be focusing on landing slots: https://github.com/canjs/canjs/issues/2278 and inline partials: https://github.com/canjs/can-stache/issues/3 which should cover much of what's needed here.
