### ISSUE TITLE
Create a style guide page

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#5088]
As Justin mentioned in https://github.com/canjs/bit-docs-html-canjs/issues/552#issuecomment-506070239, it’d be helpful if we had a style guide.

I see this being broken into these steps:

- [x] Choose a tool (DocumentCSS or something else?)
- [x] Get a basic working prototype that documents a couple of styles
- [ ] Figure out how we’re going to document more complex things, like the header, sidebar, demos, etc.
- [x] After we’ve verified the tool works for us… add a style guide page to the [Contributing docs](https://canjs.com/doc/guides/contribute.html)
- [ ] Document the rest of the styles

**Comment by justinbmeyer** [comment]
I don't think we need to do all this much, I mostly think we can create something like we did for Bitovi Academy: https://www.bitovi.com/academy/training/style-guide.html

I bet we get 90% of the benefit from a page that simply shows the content like this.

**Comment by chasenlehara** [comment]
Ah great, I hadn’t seen that before. I agree, something like the Academy style guide would work ok for CanJS too.
