### ISSUE TITLE
Session guide issues

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#5092]
- [x] Highlighting broken: 
![image](https://user-images.githubusercontent.com/78602/60379029-234e1a80-99f1-11e9-897f-b49c372b2782.png)

   This seems to be a problem with most of the examples.

- [x] `Depending On Session In View` -> `Depending on Session in the View`

- [x] The subsections to __Initializing The App__ don't necessarily have to be part of initialization.  It's more like "Using the state of the session" 

- [ ] There are some trailing commas:

   ```
       static define = {
      todos: {
        async(resolve) {
          Todo.getList({}).then(resolve);
          return [];
        }
      },
    };
   ```

- [x] The bix __Example__ should have just the session stuff highlighted.

- [x] We might want to show an image or gif of what the example does.

**Comment by chasenlehara** [comment]
@nlundquist Are these still issues that need to be resolved?

**Comment by nlundquist** [comment]
As for trailing commas, are these really an issue? Should we be removing trailing commas from this?
```
    static props = {
      email: String,
      password: String,
      logInError: type.Any,
    };
```
imo there's nothing inherently bad about trailing commas.

**Comment by chasenlehara** [comment]
After watching people at meetups, I think that it’s best to leave trailing commas in any lists that people will add things to. I’ve seen lots of people miss a comma and then wasting time debugging that. Additionally, it’s awkward when we have to highlight a line that we’re only adding a comma to.
