### ISSUE TITLE
Update guides which use globals to use modules

### ISSUE THREAD

**Issue by Mattchewone** [canjs/canjs#5104]
Currently we have the following guides which all reference `can` globally, this doesn't work with the class constructors, we should update those guides to use modules.

- [ ] atm guides
- [ ] chat
- [ ] todomvc

```html
<html>
<body>
    <my-app></my-app>

    <script src="//unpkg.com/can@5/dist/global/core.js"></script>
    <script>
    can.Component.extend({
        tag: "my-app",
        view: `CanJS {{feels}} modules`,
        ViewModel: {
            feels: { default: "😍" }
        }
    });
    </script>
</body>
</html>
```

Should become:
```html
<html>
<body>
    <my-app></my-app>

    <script type="module">
      import { StacheDefineElement } from "//unpkg.com/can@5/everything.mjs";
      
      class MyApp extends StacheDefineElement {
        static get view() {
          return `CanJS {{feels}} modules`;
        }

        static get define() {
          return {
            feels: { default: "😍" }
          };
        }
      };
      customElements.define('my-app', MyApp);
    </script>
</body>
</html>
```

**Comment by chasenlehara** [comment]
We decided to [hide the ATM guide](https://github.com/canjs/canjs/issues/4616) but I didn’t write why in that issue and I don’t remember. 😢 For now I would leave it alone and remove/hide it on the [Guides page](https://canjs.com/doc/guides.html).

It looks like [todomvc.html](https://github.com/canjs/canjs/blob/master/docs/can-guides/experiment/todomvc/todomvc.html) is used to [test the global build](https://github.com/canjs/canjs/blob/67322c82e84a2f8ff5c469da2dd24d236b456b63/test/global-build.js#L1), so I don’t think it should be updated.

I think it’s safe to delete these files (I think they were only used to test the result, which is now a lot easier to do with CodePen / plain HTML):

- https://github.com/canjs/canjs/blob/master/docs/can-guides/experiment/chat/chat-steal.html
- https://github.com/canjs/canjs/blob/master/docs/can-guides/experiment/chat/chat.html

I think this is the only page that needs to be updated to not show `can.Component.extend`: https://github.com/canjs/canjs/blob/master/docs/can-canjs/can-api.md#custom-element-bindings

**Comment by matthewp** [comment]
This should be done in the `major` branch.

**Comment by justinbmeyer** [comment]
ATM needs a big rewrite. Much better state management and testing approaches now
