### ISSUE TITLE
The owner of this Pen needs to verify their email address to enable Full Page View.

### ISSUE THREAD

**Issue by leoj3n** [canjs/canjs#5106]
https://canjs.com/doc/guides/crud-beginner.html

https://codepen.io/bitovi/full/omqyMw

![image](https://user-images.githubusercontent.com/990216/60762863-228b3900-a02e-11e9-9a36-2ec489b3d6fc.png)

**Comment by chasenlehara** [comment]
How can I replicate this issue / what is the full page view?

**Comment by leoj3n** [comment]
https://codepen.io/bitovi/full/omqyMw

**Comment by chasenlehara** [comment]
I mean to ask, from CanJS.com, how do you get to the full page view? Is there a button in the embedded CodePen, or do some of the CodePens launch to this view, or…?

**Comment by leoj3n** [comment]
It's when you click the button:

<img width="1268" alt="ss" src="https://user-images.githubusercontent.com/990216/60922719-f86e8c80-a262-11e9-941f-d9c96c31e3b2.png">

**Comment by leoj3n** [comment]
Not an issue for me anymore as I worked around the limitation by exporting the built code (CSS) that I was trying to get at:

<img width="701" alt="ss2" src="https://user-images.githubusercontent.com/990216/60922861-44213600-a263-11e9-9087-6b12bd8df831.png">

Looks like "view frame source" is another way to get at the built code:

<img width="397" alt="ss3" src="https://user-images.githubusercontent.com/990216/60923046-ada14480-a263-11e9-8e2c-7d328a726236.png">

As would forking the pen (not something I wanted to do).

Seeing as this has multiple workarounds and it's not an issue for me anymore, feel free to not verify your account.
