### ISSUE TITLE
CanJS 6 migration guide

### ISSUE THREAD

**Issue by Mattchewone** [canjs/canjs#5108]
Doc - https://docs.google.com/document/d/1Lx_kujFQ0j9cG9HFO_Ca91ZXLSE-BTGOa-9gxwRLNVQ/edit

**Comment by matthewp** [comment]
I started on this in the `migration` branch: https://github.com/canjs/canjs/tree/migration

**Comment by chasenlehara** [comment]
Not sure whether I should add stuff to the doc or write comments here…

`<content />` isn’t supported. Instead, you can do something like:

```js

class InView extends StacheElement {
    static view = `{{content(context)}}`;
}
customElements.define("in-view", InView);

class MyDemo extends StacheElement {
    static view = `
        {{<viewContent}}
        {{/viewContent}}
        <in-view content:from="viewContent" context:from="this" />
    `;
}
customElements.define("my-demo", MyDemo);
```

**Comment by matthewp** [comment]
This is done. Will open new issues for improvements.
