### ISSUE TITLE
Fix the counter example in the HTML guide

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#5115]
The first time the [HTML guide](https://canjs.com/doc/guides/html.html#Overview) loads, the counter element doesn’t render. It does appear if you refresh the page.

![html page](https://user-images.githubusercontent.com/10070176/60911119-55ece400-a237-11e9-88cf-29313f7f3c5f.gif)

**Comment by cherifGsoul** [comment]
The example is loaded for me in Chrome, Firefox and Safari, tested in private browsing mode also.

**Comment by chasenlehara** [comment]
To be clear, it loads correctly when you 1) open a new tab, 2) go to canjs.com > Guides, and 3) click on the HTML page? Could you please attach a gif like mine that shows this?
