### ISSUE TITLE
Run the codemods against the docs

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#5118]
Check for issues with the codemods by running them against our current docs:

- [x] https://canjs.com/doc/guides/crud-beginner.html
- [x] https://canjs.com/doc/guides/technical.html
- [x] https://canjs.com/doc/guides/setup.html
- [x] https://canjs.com/doc/guides/technology-overview.html
- [x] https://canjs.com/doc/guides/html.html
- [x] https://canjs.com/doc/guides/routing.html
- [x] https://canjs.com/doc/guides/data-introduction.html
- [x] https://canjs.com/doc/guides/data-configuring-requests.html
- [x] https://canjs.com/doc/guides/data-managing-sessions.html
- [x] https://canjs.com/doc/guides/data-customizing-connections.html
- [x] https://canjs.com/doc/guides/debugging.html
- [x] https://canjs.com/doc/guides/forms.html
- [x] https://canjs.com/doc/guides/testing.html
- [x] https://canjs.com/doc/guides/logic.html
- [x] https://canjs.com/doc/guides/chat.html
- [x] https://canjs.com/doc/guides/todomvc.html
- [x] https://canjs.com/doc/guides/recipes/todomvc-with-steal.html
- [x] https://canjs.com/doc/guides/recipes/canvas-clock.html
- [x] https://canjs.com/doc/guides/recipes/credit-card-simple.html
- [x] https://canjs.com/doc/guides/recipes/file-navigator-simple.html
- [x] https://canjs.com/doc/guides/recipes/signup-simple.html
- [x] https://canjs.com/doc/guides/recipes/video-player.html
- [x] https://canjs.com/doc/guides/recipes/cta-bus-map.html
- [x] https://canjs.com/doc/guides/recipes/modals.html
- [x] https://canjs.com/doc/guides/recipes/text-editor.html
- [x] https://canjs.com/doc/guides/recipes/tinder-carousel.html
- [x] https://canjs.com/doc/guides/recipes/credit-card-advanced.html
- [x] https://canjs.com/doc/guides/recipes/file-navigator-advanced.html
- [x] https://canjs.com/doc/guides/recipes/playlist-editor.html
- [x] https://canjs.com/doc/guides/recipes/search-list-details.html
- [x] https://canjs.com/doc/guides/api.html
- [x] https://canjs.com/doc/api.html

**Comment by Mattchewone** [comment]
Note regarding the `tinder-carousel` guide, the original version has a profiles property with an array as a default which defaults to being converted to a `DefineList` this doesn't happen with DefineObject. 

We will need to update to `return new DefineArray(...[{...}])` and also update the getters to use `this.profiles[0]` rather than the previous `DefineList` lookup methods: `this.profiles.get(0)`

Demo - https://codepen.io/mattchewone-the-looper/pen/JQwpjx?editors=1000

**Comment by Mattchewone** [comment]
For `https://canjs.com/doc/guides/technical.html` under the heading `### Separation of concerns` the codeblock is invalid, it's missing a comma after the first property:

```js
const Todo = DefineMap.extend({
	id: {identity: true, type: "number"}
	complete: "boolean",
	name: "string"
});
```

Should be
```js
const Todo = DefineMap.extend({
	id: {identity: true, type: "number"},
	complete: "boolean",
	name: "string"
});
```

**Comment by Mattchewone** [comment]
In `https://canjs.com/doc/guides/technology-overview.html`

In the later part of the guide we are showing this:
```js
route.data = document.querySelector("my-counter").viewModel;
route.start();
```

With the CanJS 6 we need to remove the `.viewModel` as the element is the observable. 

Making a note of this here as the docs here - `https://canjs.com/doc/can-route.data.html#HTMLElement` say that this is deprecated so this should be done for CanJS 6 and not a hotfix.

**Comment by Mattchewone** [comment]
Guides that need to be updated to remove references to using DefineMaps as the ViewModel of the Component, as this is not possible in CanJS 6.

This is no longer possible:
```js
const Counter = DefineMap.extend({
  count: { type: 'number', default: 0 },
  increment () { this.count++ }
})
Component.extend({
  view: `Count {{count}}`,
  ViewModel: Counter
})
```

1. https://canjs.com/doc/guides/html.html

**Comment by Mattchewone** [comment]
Routing guide:

We need to update the dynamic imports.

Existing:
```js
return import("can/demos/technology-overview/page-login")
  .then((module) => {
    return new module.default({
      viewModel: {
        isLoggedIn: value.bind(this, "isLoggedIn")
      }
    });
  });
```

To:
```js
return import("can/demos/technology-overview/page-login")
  .then((module) => {
    return new module.default().bindings({
      isLoggedIn: value.bind(this, "isLoggedIn")
    });
  });
```

**Comment by Mattchewone** [comment]
`https://canjs.com/doc/guides/data-introduction.html`

There are instances of `connectedCallback` and `ViewModel` that are not wrapped in a `DefineMap` or `Component` so these are not being transformer, these will need to be manually updated

**Comment by Mattchewone** [comment]
Date Guide:

As there is already `StacheDefineElement` in use in the docs, we may want to manually update how it shows the use of `define` for example to be consistent with how `can-migrate` will transform it.

In docs now:
```js
static define = {
  email: String,
  password: String,
  logInError: type.Any,
};
```

How we show it from `can-migrate`:
```js
static get define () {
  return {
    email: type.maybeConvert(String),
    password: type: maybeConvert(String),
    loginError: type.Any
  }
}
```

Also may be worth updating how we show these:
```js
  Todo.connection = restModel({
    Map: Todo,
    url: {
      resource: '/api/todo',
      beforeSend: () => {
        return Session.currentPromise;
      }
    }
  });
```
Not sure if we are continuing to show adding properties like `connection` to the `DefineObject` in this way.

**Comment by Mattchewone** [comment]
Guides that rely on the `demos` which are referenced via the `/demos` folder

- [ ] forms

**Comment by Mattchewone** [comment]
Possible issue with `https://canjs.com/doc/guides/recipes/file-navigator-simple.html`

In how it defines a children type:
```js
class Person extends DefineObject {
  static get define() {
    return {
      name: type.maybeConvert(String),
      age: type.maybeConvert(Number),
      addresses: [{
        type: function(rawData) {
          return new Address(rawData);
        }
      }]
    };
  }
}
```

This is currently not working in a demo - https://codepen.io/mattchewone-the-looper/pen/OeKNxB?editors=0010

**Comment by Mattchewone** [comment]
`https://canjs.com/doc/guides/recipes/modals.html`

When converted using codemods, will need to update the following:
```js
            occupationQuestions: {
                get default() {
                    return new OccupationQuestions({
                        viewModel: {
                            isDiva: value.bind(this, "isDiva"),
                            isProgrammer: value.bind(this, "isProgrammer"),
                            next: this.next.bind(this)
                        }
                    });
                }
            },
```

To initialize a new component you need to do the following:
```js
            occupationQuestions: {
                get default() {
                    return new OccupationQuestions().initialize( {
                            isDiva: value.bind(this, "isDiva"),
                            isProgrammer: value.bind(this, "isProgrammer"),
                            next: this.next.bind(this)
                        });
                }
            },
```

**Comment by Mattchewone** [comment]
`https://canjs.com/doc/guides/recipes/file-navigator-advanced.html` in order to get the demo working I had to modify how the initialised data was created via the component.

Demo here - https://codepen.io/mattchewone-the-looper/pen/wLVXEN?editors=0010

Assigned the initial values:
```js
Object.assign(root, {
  isOpen: true,
  folder: new Entity({
    id: "0",
    name: "ROOT/",
    hasChildren: true,
    type: "folder"
  })
});
```

**Comment by chasenlehara** [comment]
@Mattchewone I think it’s going to be easier to track everything if individual issues are opened for each of your comments above. After they’re opened, I would close this issue.

**Comment by matthewp** [comment]
We're not using this doc for tracking any more, so closing.
