### ISSUE TITLE
Reuse code snippets

### ISSUE THREAD

**Issue by Mattchewone** [canjs/canjs#5129]
We should look to move code examples into external code files so that we can reference it in multiple places to prevent duplicating the same code or parts of the same code.

For example in the `data-guide` we could have these snippets of code, reference from a more fuller example to prevent duplication. 

![Screenshot 2019-07-11 at 18 49 43](https://user-images.githubusercontent.com/4574152/61074862-99e71100-a410-11e9-97df-a95fcd2e40a5.png)

This would also mean that the code-mods would run on the full example and the update would be done for all references.

I will create a list here :)

- [ ] https://canjs.com/doc/guides/data-introduction.html#Updatelistswhenrecordsaremutated
- [ ] https://canjs.com/doc/guides/testing.html#Propertiesderivedfromasynchronousbehavior
- [ ] https://canjs.com/doc/guides/testing.html#Routedata
- [ ] https://canjs.com/doc/guides/logic.html#Sideeffectswhenderivedpropertieschange
- [ ] https://canjs.com/doc/guides/recipes/todomvc-with-steal.html#DefineTodotype_DefineMapbasics_
- [ ] https://canjs.com/doc/guides/recipes/video-player.html#Makeplay_pausebuttonchangeasvideoisplayedandpaused
- [ ] http://localhost:8080/doc/guides/recipes/search-list-details.html#Configurerouting

**Comment by matthewp** [comment]
How can we do this? Is this something bit-docs already can do?

**Comment by Mattchewone** [comment]
I think the plan was to create external files with the code and then use that code in multiple places making use of the highlight plugin to only show specific sections where needed.

**Comment by matthewp** [comment]
Oh I see, so just using `@sourceref` to pull them in.

**Comment by matthewp** [comment]
I don't think we're doing much of this for 6.0, but perhaps in the future.
