### ISSUE TITLE
Update docs for access `viewModel` on the element

### ISSUE THREAD

**Issue by Mattchewone** [canjs/canjs#5138]
We currently show accessing `viewModel` property on the element, with the new `StacheDefineElement` the element is the observable so there is no need to use the `viewModel` property.

```js
const appVM = window.appVM = document.querySelector("todo-mvc").viewModel;
```

Would be:
```js
const appVM = window.appVM = document.querySelector("todo-mvc");
```

We use these in the following guides:

- https://canjs.com/doc/guides/recipes/cta-bus-map.html#Changetheapptitle
- https://canjs.com/doc/guides/recipes/tinder-carousel.html#Showthecurrentandnextprofileimages
- https://canjs.com/doc/guides/todomvc.html#Defineandusethemaincomponent
- https://canjs.com/doc/guides/routing.html#Overview

**Comment by phillipskevin** [comment]
@m-mujica Related to https://github.com/canjs/canjs/pull/5203#issuecomment-521256833, yeah, we should update things like this also:

```js
events: {
  click() {
      this.viewModel.visible = !this.viewModel.visible;
   }
}
```

**Comment by justinbmeyer** [comment]
That specific example can be done in stache: `on:click="this.visible = not(this.visible)"`

**Comment by matthewp** [comment]
@m-mujica I believe this is no longer shown, right?

**Comment by m-mujica** [comment]
Yes, I think this can be closed. (shame autoclose only works on master)
