### ISSUE TITLE
Update modals guide for CanJS 6

### ISSUE THREAD

**Issue by Mattchewone** [canjs/canjs#5152]
We will need to re-write how the Modals guide is written. Currently we are using a getter to create an array of components to display as modals, in 6.0 this causes a `connectedBindingsTeardown` which means that the component is torndown and the bindings removed. 

As the component was initialized within a `default` and this only runs once the bindings do not get re-created.

You can see the issue here - https://codepen.io/mattchewone-the-looper/pen/Zdgadx?editors=1000

If you select `isDiva` you see the new modal appear behind the current one, but when you deselect `isDiva` the modal does not get removed and the displayed properties on the page no longer update when you toggle.

**Comment by matthewp** [comment]
This no longer throws errors.
