### ISSUE TITLE
File navigator advanced guide

### ISSUE THREAD

**Issue by Mattchewone** [canjs/canjs#5154]
We should update how we initialise the component within this guide. 

Previously we would set the initial values by getting the `viewModel` and assigning them, we should move to creating the component and giving it initial values and appending it to the body. 

```js
var el = new MyElement().initialize({
  isOpen: true,
  folder: ...
})
document.body.append(el)
```

to replace:
```js
root.viewModel.assign({
  folder: new Entity({
    id: "0",
    name: "ROOT/",
    hasChildren: true,
    type: "folder"
  })
});
```

**Comment by matthewp** [comment]
We've stayed with the `assign` way, primarily because we wanted to show the element as being in the page.
