### ISSUE TITLE
Playlist editor advanced 6.0

### ISSUE THREAD

**Issue by Mattchewone** [canjs/canjs#5155]
This guide shows the shorthand Type definition:

```js
playlistVideos: {
    Type: ["any"],
    Default: DefineList
}
```

Which isn't currently handled in 6.0. We would need to create a `DefineArray` and use this as the type for the prop.

https://canjs.com/doc/guides/recipes/playlist-editor.html#Dropvideos

**Comment by Mattchewone** [comment]
Related to - https://github.com/canjs/can-define-array/issues/35

**Comment by matthewp** [comment]
This uses an ObservableArray now: https://github.com/canjs/canjs/blob/a410c52963a02db9111e75e9ec523385a93f3b92/docs/can-guides/commitment/recipes/playlist-editor/8-create-playlist.js#L160
