### ISSUE TITLE
Update document script to move can-define docs to core

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#5170]
When CanJS 6.0 is release, we will update the `can-define` documentation to move `can-define` to the `can-legacy` package. We will then need to update the `canjs#5.x-legacy` branch (not created yet), so that the `can-define` docs are still shown in `can-core` on [v5.canjs.com](v5.canjs.com).

As part of the `npm run document` script, we should replace `can-legacy` with `can-core` in any markdown files inside `node_modules/can-define`.

**Comment by phillipskevin** [comment]
We will update these file in the source code:
https://github.com/canjs/can-define/blob/master/docs/define.md
https://github.com/canjs/can-define/blob/master/map/docs/define-map.md
https://github.com/canjs/can-define/blob/master/list/docs/define-list.md

To replace `@collection can-core` with `@collection can-legacy`.

However, we don't want these to show up under legacy on the v5 site.

So when generating the docs on the v5 branch, we want to change these back. This could either be a `bit-docs` plugin or just a nodejs script that edits these files before running `bit-docs`.

**Comment by Mattchewone** [comment]
I am not sure if this is possible but if there is a way to create a plugin which can manipulate the output before it gets generated then I think that would work. If we could have something like this as a config that could be placed within `canjs`'s `bit-docs` config within `package.json`
```js
{
  "legacy": [{
    "pattern": "@collection can-core",
    "search": [
        "node_modules/can-define/**/*"
      ]
  }]
}
```

We define the pattern we wish to translate into `@collection can-legacy` and the files in which this applies to, this presumes the plugin has knowledge about the file.

**Comment by chasenlehara** [comment]
Since this is a one-off right now, I would just change the v5 Makefile to do this transformation instead of making a whole plugin for it.

**Comment by Mattchewone** [comment]
Yeah after some initial investigation into `bit-docs` it seems like a simple regex / find & replace will be easiest. 

The `Makefile` runs when publishing `canjs` so when testing locally it would be different but I think for this it is probably ok.

**Comment by Mattchewone** [comment]
Ok my proposal is to add these to the `Makefile` before the `bit-docs` command is run

```bash
sed -i -e 's/@collection can-legacy/@collection can-core/g' "./node_modules/can-define/docs/define.md"
	sed -i -e 's/@collection can-legacy/@collection can-core/g' "./node_modules/can-define/map/docs/define-map.md"
	sed -i -e 's/@collection can-legacy/@collection can-core/g' "./node_modules/can-define/list/docs/define-list.md"
```

**Comment by chasenlehara** [comment]
I just noticed that these two lines: https://github.com/canjs/canjs/blob/d29fba995499b73765a7542290be4f5a64db9234/Makefile#L4-L5

…are the same as [npm run document:force](https://github.com/canjs/canjs/blob/d29fba995499b73765a7542290be4f5a64db9234/package.json#L29)

Maybe we can update the `document` and `document:force` scripts to do the renaming? Add an npm script with those commands and add it to both of those?
