### ISSUE TITLE
Remove references to nodeLists from the 6.0 docs

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#5188]
Things like http://next.canjs.com/doc/can-stache.view.html still show the `nodeList` parameter:

> view(data, [helpers], [nodeList])

We should go through and remove these before the 6.0 release.

**Comment by m-mujica** [comment]
(canjs/canjs) > ag -Q [nodeList] node_modules/ 

- [ ] [node_modules/can-view-live/lib/text.js](https://github.com/canjs/can-view-live/pull/147)
- [ ] [node_modules/can-stache/docs/view.md](https://github.com/canjs/can-stache/pull/714)

**Comment by m-mujica** [comment]
It seems it only happens on those two packages. I also tried searching for `nodelist)` but got only references in actual code.

**Comment by m-mujica** [comment]
I didn't find any references other than internal APIs.
