### ISSUE TITLE
Make sure devtools work in 6.0

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#5189]
Things to check:

- [x] StacheElements show up in the component tree and can be edited
- [x] Mutation Breakpoints work with StacheElement
- [x] attribute -> property bindings show up in bindings graph
- [x] changes to ObservableObject / ObservableArray are displayed in the Queues Stack

**Comment by Mattchewone** [comment]
`StacheElement` shows in the component tree:
![Screenshot 2019-08-15 at 20 19 15](https://user-images.githubusercontent.com/4574152/63120314-fa321b00-bf99-11e9-8f0e-d8cfff89d53f.png)
`StacheElement` property being edited:
![Screenshot 2019-08-15 at 20 16 29](https://user-images.githubusercontent.com/4574152/63120347-0cac5480-bf9a-11e9-85f1-795adf3527e7.png)


attribute -> property binding showing up in graph:
![Screenshot 2019-08-15 at 20 15 09](https://user-images.githubusercontent.com/4574152/63120380-1df56100-bf9a-11e9-95c1-007d3d161a9f.png)

**Comment by Mattchewone** [comment]
Mutation Breakpoints work with StacheElement - https://github.com/canjs/devtools/pull/77

**Comment by phillipskevin** [comment]
Nice job @Mattchewone.
