### ISSUE TITLE
Show ES5/IE11-friendly versions of the docs

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#5219]
Since most of our code examples are now using code that only works in Chrome (for the time being until Firefox ships class fields), we may want to make it possible for users to choose to display the docs in ES5.

@matthewp mentioned that [Stripe](https://stripe.com/docs/stripe-js/reference#stripe-elements) shows an option to display code snippets in "ESNext":

![stripe-esnext](https://user-images.githubusercontent.com/5851984/63181726-52a6fe00-c016-11e9-871d-b5972d32587b.gif)

**Comment by matthewp** [comment]
Doesn't appear likely this will happen for 6.0. Given that it's unlikely IE11 support will continue on much longer, is this issue really necessary?

**Comment by phillipskevin** [comment]
This was a proposal for the last survey and got 0 votes, so no, it's not needed.
