### ISSUE TITLE
Replace uses of can-define-array & can-define-object

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#5225]
Can all of these uses be updated?

- https://github.com/search?q=org%3Acanjs+"can-define-array"&type=Code
- https://github.com/search?q=org%3Acanjs+"can-define-object"&type=Code

**Comment by phillipskevin** [comment]
Yes.

**Comment by phillipskevin** [comment]
We should change `can-stache-define-element` to `can-stache-element` in `can-migrate` also.

**Comment by chasenlehara** [comment]
Re-opening this because there are still more uses that need to be updated: https://github.com/search?q=org%3Acanjs+%22can-define-object%22&type=Code

**Comment by phillipskevin** [comment]
@cherifGsoul can this be closed now?

**Comment by cherifGsoul** [comment]
Yes it's done.
