### ISSUE TITLE
can@5.32.0 package uses incompatible versioned dependencies

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#5229]
Just an FYI but the current 5.x branch's umbrella `can` package has a few transient dependencies that are hard-locked into incompatible versions.

This is causing multiple versions of the same `can-*` constituent packages to be installed.
Not sure how this will affect bundlers.

Offending packages are:
- `can-event-queue` versions: 1.1.6 and 1.1.7
- `can-observation` versions: 4.1.3 and 4.2.0
- `can-queues` versions: 1.2.2 and 1.3.1
- `can-simple-observable` versions: 2.4.2 and 2.4.3

The root offender here seems to be `can-simple-observable` with version 2.4.3 being directly required by the `can` package, but with version 2.4.2 still being transiently depended on, via other dependencies.

`can@5.31` is fine, but is unusable with Webpack and IE 11 due to [can-observable-mixin #125](https://github.com/canjs/can-observable-mixin/issues/125) not being patched in the version of `can-observable-mixin` that it uses.

@phillipskevin 
Am I correct in assuming that packages were bumped to include that change with the umbrella `can` package and that these could be what triggered the version mismatch?

**Comment by rjgotten** [comment]
OK. This is weird: Seems this problem _only_ occurs when using `npm update can` to update an existing installation. When doing `npm uninstall can` followed by `npm install can` you _do_ end up with a consistent version.

So... chalk it up to NPM not doing version reconcilliation correctly, I guess?

**Comment by phillipskevin** [comment]
This behavior is very frustrating, but I don't think it's anything we can control. Sorry for the headache.

**Comment by justinbmeyer** [comment]
We could change the "duplicate package" warnings to suggest re-installing.

**Comment by phillipskevin** [comment]
> We could change the "duplicate package" warnings to suggest re-installing.

Are you talking about the `You cannot have two version of...` errors? The issue here is with a package that can have multiple versions. There is just a bug in an earlier version so @rjgotten wanted the latest.

**Comment by rjgotten** [comment]
If you're still interested in showing users a warning; there's one thing I can think of that might work:
a post-install NPM script that uses `npm ls` to enumerate what's installed and check for duplications.

Very heavy handed though, because there's no good way to filter the dependency tree with wildcard partial matches. 😞
