### ISSUE TITLE
Improve type errors

### ISSUE THREAD

**Issue by phillipskevin** [canjs/canjs#5310]
During user testing, users had a lot of trouble understanding the errors thrown by `can-type`.

Here is a codepen with the existing error: https://codepen.io/kphillips86/pen/mdbvmwg?editors=0010.

If you have a prop like `num: { type: Number }`, and set the value to `"3"`, you get this error:

> Uncaught Error: 3 is not of type Number.

There are a few things we should do to improve this:

## 1. Include the type of the value

The warning should include that `num` is being set to a String, like:

> Uncaught Error: "3" is not of type Number.

or

> Uncaught Error: 3 (String) is not of type Number.

## 2. Include the name of the property that is being set

`ObservableObject` / `StacheElement` should catch the type errors thrown by `can-type`/`can-reflect` and include the name of the property.

> Uncaught Error: 3 is not of type Number. Property `num` is using `type: Number`.

## 3. Errors should include suggestions for what type to use

> Uncaught Error: 3 is not of type Number. Property `num` is using `type: Number`. Use `num: type.ToNumber` to automatically convert values to Numbers when setting the `num` property

## 4. Explain that `<input>` elements always set properties to Strings

This may be difficult to do, but it would be helpful if the error message could explain when this issue is caused by an `<input>` setting a property as a string.

For example, with the codepen above, you get this error when using a template like:
```js
<input value:bind="this.num">
```

The same thing happens if you use `type="number"`, which can be especially confusing.

## 5. Fix weirdness with arrays

One user tried to do this:

```js
  static props = {
    list: []
  };
```

and then `this.list = [ "one", "two" ];`, which gives this error:

> TypeError: Right-hand side of 'instanceof' is not callable

This is very confusing.

**Comment by cherifGsoul** [comment]
This had been released!
