### ISSUE TITLE
6.0 Releases

### ISSUE THREAD

**Issue by matthewp** [canjs/canjs#5324]
This issue is to track releasing the various major revisions.

Projects:

* [ ]    "can-attribute-observable": "2.0.0-pre.1"
  * [x] Merge to master ([PR](https://github.com/canjs/can-attribute-observable/pull/40))
  * [x] Release
  * [ ] Notes
* [ ]    "can-component": "5.0.0-pre.5",
  * [x] Merge to master ([PR](https://github.com/canjs/can-component/pull/361))
  * [x] Release
  * [x] Notes
* [ ]    "can-connect": "4.0.0-pre.3",
  * [x] Merge to master ([PR](https://github.com/canjs/can-connect/pull/503))
  * [x] Release
  * [x] Notes
* [ ]    "can-connect-tag": "2.0.0-pre.4",
  * [x] Merge to master ([PR](https://github.com/canjs/can-connect-tag/pull/5))
  * [x] Release
  * [ ] Notes
* [ ]    "can-control": "5.0.0-pre.2",
  * [x] Merge to master ([PR](https://github.com/canjs/can-control/pull/141))
  * [x] Release
  * [x] Notes
* [ ]    "can-deep-observable": "1.0.0-pre.1",
  * [x] Merge to master
  * [x] Release
  * [ ] Notes
* [ ]    "can-observable-array": "1.0.0-pre.9",
  * [x] Merge to master ([PR](https://github.com/canjs/can-observable-array/pull/64))
  * [x] Release
  * [x] Notes
* [ ]    "can-observable-mixin": "1.0.0-pre.11",
  * [x] Merge to master ([PR](https://github.com/canjs/can-observable-mixin/pull/138))
  * [x] Release
  * [ ] Notes
* [ ]    "can-observable-object": "1.0.0-pre.3",
  * [x] Merge to master ([PR](https://github.com/canjs/can-observable-object/pull/26))
  * [x] Release
  * [x] Notes
* [ ]    "can-realtime-rest-model": "2.0.0-pre.0",
  * [x] Merge to master
  * [x] Release
  * [ ] Notes
* [ ]    "can-rest-model": "2.0.0-pre.0",
  * [x] Merge to master
  * [x] Release
  * [ ] Notes
* [ ]    "can-route": "5.0.0-pre.4",
  * [x] Merge to master ([PR](https://github.com/canjs/can-route/pull/252))
  * [x] Release
  * [ ] Notes
* [ ]    "can-route-pushstate": "6.0.0-pre.0",
  * [x] Merge to master ([PR](https://github.com/canjs/can-route-pushstate/pull/163))
  * [x] Release
  * [ ] Notes
* [ ]    "can-stache": "5.0.0-pre.6",
  * [x] Merge to master ([PR](https://github.com/canjs/can-stache/pull/721))
  * [x] Release
  * [ ] Notes
* [ ]    "can-stache-bindings": "5.0.0-pre.6",
  * [x] Merge to master ([PR](https://github.com/canjs/can-stache-bindings/pull/544))
  * [x] Release
  * [ ] Notes
* [ ]    "can-stache-converters": "5.0.0-pre.1",
  * [x] Merge to master ([PR](https://github.com/canjs/can-stache-converters/pull/104))
  * [x] Release
  * [ ] Notes
* [ ]    "can-stache-element": "1.0.0-pre.13",
  * [x] Merge to master ([PR](https://github.com/canjs/can-stache-element/pull/87))
  * [x] Get `<template>` support in
  * [x] Release
  * [x] Notes
* [ ]    "can-stache-route-helpers": "2.0.0-pre.3",
  * [x] Merge to master ([PR](https://github.com/canjs/can-stache-route-helpers/pull/27))
  * [x] Release
  * [x] Notes
* [ ]    "can-type": "1.0.0-pre.9",
  * [x] Merge to master ([PR](https://github.com/canjs/can-type/pull/37))
  * [x] Release
  * [x] Notes
* [ ]    "can-view-autorender": "6.0.0-pre.0",
  * [x] Merge to master ([PR](https://github.com/canjs/can-view-autorender/pull/101))
  * [x] Release
  * [x] Notes
* [ ]    "can-view-callbacks": "5.0.0-pre.2",
  * [x] Merge to master ([PR](https://github.com/canjs/can-view-callbacks/pull/121))
  * [x] Release
  * [x] Notes
* [ ]    "can-view-live": "5.0.0-pre.2",
  * [x] Merge to master ([PR](https://github.com/canjs/can-view-live/pull/148))
  * [x] Release
  * [x] Notes
* [ ]    "can-view-target": "5.0.0-pre.0",
  * [x] Merge to master ([PR](https://github.com/canjs/can-view-target/pull/82))
  * [x] Release
  * [x] Notes
* [ ]    "steal-stache": "5.0.0-pre.2"
  * [x] Merge to master ([PR](https://github.com/canjs/steal-stache/pull/86))
  * [x] Release
  * [x] Notes
* [ ]    can-migrate
  * [x] Merge to master
  * [x] Release
  * [ ] Notes
* [ ]    "can-view-import": "5.0.0-pre.2",
  * [x] Merge to master ([PR](https://github.com/canjs/can-view-import/pull/129))
  * [x] Release
  * [ ] Notes

**Comment by phillipskevin** [comment]
We'll need to publish a final version of `can-migrate`.
