### ISSUE TITLE
Test the production webpack code

### ISSUE THREAD

**Issue by chasenlehara** [canjs/canjs#5358]
It looks like we test building webpack in production mode, but maybe we don’t test that the code actually works?

Unfortunately I didn’t have time to dig into this, but I came across an issue where the webpack build passed for an example app but the code didn’t work because some code was compiled out of the production build, causing a runtime error. Here’s what I fixed: https://github.com/canjs/can-connect/pull/506/files

**Comment by matthewp** [comment]
We have a smoke test or two. It's probably that the tests simply aren't using can-connect, and that's the reason this wasn't caught.

**Comment by chasenlehara** [comment]
This was the example app that I was working with: 
https://github.com/canjs/webpack-example

It doesn’t explicitly load can-connect in the app, but it ran into this issue. 🤷‍♂️

**Comment by chasenlehara** [comment]
webpack uses `core.mjs` because of this:

https://github.com/canjs/canjs/blob/436a7bb63641a36b3ee113091ef2e69a281c5af1/package.json#L5

The webpack test uses `core.js`, so switching it to use `core.mjs` does catch this bug:

https://github.com/canjs/canjs/blob/436a7bb63641a36b3ee113091ef2e69a281c5af1/test/builders/webpack/index.js#L1

However, using `core.mjs` instead of `core.js` causes these assertions to fail:

https://github.com/canjs/canjs/blob/436a7bb63641a36b3ee113091ef2e69a281c5af1/test/builders/webpack/treeshake.html#L12-L13

I’m not sure if this is:

1) Expected from the mjs build, so those tests should be removed
2) An issue with webpack / how we configure it for this build
2) An issue we need to fix with the mjs build

**Comment by matthewp** [comment]
I believe those assertions are testing tree shaking.

**Comment by rjgotten** [comment]
For what it's worth: Webpack won't apply tree-shaking unless code is minified using the Terser minifier. 
It more or less completely relies on Terser's ability to perform dead code removal.

Minification using Terser is only applied by default when `mode : "production"` is set in webpack's configuration. Is your test build maybe not set to production? Or did it disable minification?
