### ISSUE TITLE
Weather report recipe for canjs6

### ISSUE THREAD

**Issue by cherifGsoul** [canjs/canjs#5397]
I wrote the widget in a [CodePen](https://codepen.io/cherifGsoul/pen/ZEEejxP?editors=0010) it would be great if someone could take a look at the code before I start writing the guide.

**Comment by matthewp** [comment]
I think this looks pretty good! The only issue would be is if we can reuse that API key in the guide? That won't present a problem?

**Comment by cherifGsoul** [comment]
The only problem can be the rate limit for request calls.

I suggest to advice the use to create an account an have a free key so other people can benefit from the example in the CodePen.
