### ISSUE TITLE
debugging guide breakpoint issue

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#5438]
with a page like:

```
<body>
    <my-counter></my-counter>

    <script type="module">
        import {StacheElement} from "//unpkg.com/can@6/core.mjs";

        class MyCounter extends StacheElement {
            static view = `
              Count: <span>{{ this.count }}</span>
              <button on:click="this.increment()">+1</button>
            `
            constructor(){
                super();
                this.count = 0;
            }
            increment(){
                this.count++;
            }
        }

        customElements.define("my-counter", MyCounter);

    </script>
</body>
```

I setup a __SINGLE__ debugger on `MyCounter.count`

![image](https://user-images.githubusercontent.com/78602/69921868-5b540080-145c-11ea-8671-d9b5b8995899.png)

However, everytime I click the `+1` button, an additional (maybe 2) breakpoint is added. 

This makes it break multiple times.

**Comment by justinbmeyer** [comment]
Also, the first time I tried this, the queues stack had information.  Now it shows nothing:

![image](https://user-images.githubusercontent.com/78602/69921927-edf49f80-145c-11ea-8a7a-d1865f3fb128.png)

**Comment by justinbmeyer** [comment]
it seems like the white page is caused if any edits happen before the mutation breakpoint is set

**Comment by phillipskevin** [comment]
This is a duplicated of https://github.com/canjs/devtools/issues/90.
