### ISSUE TITLE
can-component is not legacy

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/canjs#5456]
I regonized that can-component is essential for ssr i studied api's of diffrent frameworks and my conclusion is. canjs has the most clever solution to ssr

a object with a render function is the key for ssr can-component should maybe get redesigned

i am working at present on ssr for webcomponents and that studies lead me to the fact that we should need to wrap a webcomponent always with a can-component like layer that allows us to render strings via the render function and dom nodes via connectedCallback.

i have created a new framework based on lit-html and webcomponents that uses similar layer to archive cross Platform rendering with the same component.

i don't use any template bindings and do all bindings in the custom element so they only get executed in the browser. and every element is able to produce its string representation via the constructor.

## What needs to get done
- can-component should get more light weight 
- should supply basic constructor patterns to create a render function and maybe component registry for NodeJS and webworkers in the browser simply use the customElements registry.
- stache needs to be able to produce string only results without bindings and dom 

## Example
Little example not for production only to illustrate the need of a component wrapper for ssr.

```js
/*
   A Custom Element gets registered with a tag 
   in the string representation a element also needs a tag
   so a isomorphic way to register or render the component
   to a tag is essential only the main app view don't needs a tag 
   as it produces the <html> or its tag could even be html
*/
import { Component } from 'can-component'
Component.define('tagName',Class)

```

**Comment by justinbmeyer** [comment]
CanJS will continue to support can-component, however, we will encourage people to use can-element.

**Comment by frank-dspeed** [comment]
@justinbmeyer and how do you handle ssr? To switch to Can Element with the current design drops donejs and ssr support

**Comment by justinbmeyer** [comment]
We will get a DOM for velocirender that supports custom elements.
