### ISSUE TITLE
can/util/fixture needs a steal.then

### ISSUE THREAD

**Issue by thecountofzero** [canjs/canjs#59]
According to the comment at the top of can/util/fixture/fixture.js, it needs a steal.then cause it does not steal its dependencies so it can work with dist.

When not wrapped in a then, things do not work correctly. What I noticed is that fixtures for findAll work fine, but ones for findOne do not.  In my bit of debugging when I was seeing this weirdness, I tracked it down to the following failing regular expression that was resulting in null during findOne calls.

```
res = new RegExp(fixtureUrlAdjusted.replace(replacer, function (whole, part) {
    order.push(part)
    return "([^\/]+)"
}) + "$").exec(url)
```

Eventually daffl pointed out the comment at the top fo fixture.js

Wrapping in a then() resolves the issue...

**Comment by rahulswamicse** [comment]
I am not able to use .then() function while stealing in canjs.
My Code:
steal('can',
		'./views/runreportInit.mustache',
		'onlineclaims/common/resources.js',
		'onlineclaims/common/properties.js',
		'onlineclaims/models/service/runreport_service.js',
		"/templates/components/libraries/1.2/datatables/media/js/jquery.dataTables.js",
		"/templates/components/libraries/1.2/datatables/media/css/jquery.dataTables.css").then(
		"/templates/components/libraries/1.2/datatables/extras/ColVis/media/js/ColVis.js",
		"/templates/components/libraries/1.2/datatables/extras/ColVis/media/css/ColVis.css",
		"/templates/components/libraries/1.2/datatables/extras/TableTools/media/js/TableTools.js",
		"/templates/components/libraries/1.2/datatables/extras/TableTools/media/css/TableTools.css",
		'/templates/components/libraries/1.2/plugins/1.0/overlay/jquery.overlay.js',
		
		function(can, initView, ResourceManager, Properties, runreportService, overlay){
	/**

Its is giving me below error.
Error:
TypeError: can is undefined
 	return can.Control(

**Comment by justinbmeyer** [comment]
`.then` is very old.  It was deprecated in JMVC 3.3.  It is gone from the new Steal.  You have to configure those files:

{
  meta: {"jquery.dataTables.js": { deps: ["jquery"] }
}
