### ISSUE TITLE
The future of synchronous XHR use in can.view?

### ISSUE THREAD

**Issue by rjgotten** [canjs/canjs#64]
Please see ticket 11013 on the jQuery bugtracker; http://bugs.jquery.com/ticket/11013
Synchronous jQuery.ajax requests are to be deprecated starting jQuery 1.8 and one can assume they will be removed altogether in some future version.

As far as I can tell, the only real use case for synchronous XHR in `can.view` is in facilitating 'partial views' that can synchronously output their rendered HTML into the master view template. This seems like a hack though. Wouldn't it be better to make the EJS view engine recognize the `can.Deferred` interface and postpone the final array join operation on the component results until all encountered deferreds have resolved?

Interestingly enough, this would also enable you to have arbitrarily nested levels of deferred properties in your model, instead of the current hack (and yes; it definitely is a dirty, dirty hack) which reshapes properties of the `data` parameter to `can.view.render` that are `can.Deferred` into their resolved parameter, but only does so one level deep.

**Comment by justinbmeyer** [comment]
@rjgotten Added for 3.0.

**Comment by justinbmeyer** [comment]
I'm closing this as `can.view` won't be supported in 3.0 (except for legacy support).

Going forward, template loading will be left to people to do themselves (or using a module loader plugin which we will help create).

For async loading of templates, you can do something like:

```
var templatePromise = $.get("path/to/template.stache").then(function(text){
  return stache(text)
});

templatePromise.then(function(template){
  return template(data);
});
```
