### ISSUE TITLE
Mixin component as attributes

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#648]
[VOTE HERE](http://bithub.com/event/25859)

<h3>Injecting (attaching) components via attributes</h3>

```HTML
<div my-comp="myCompOptions" another-comp another-comp-prop="anotherProp">
  <some-content/>
</div> 
```
components my-comp and another-comp should be attached to the div element (in specified order), so it would be quite the same as template markup:

```HTML
<div>   
  <my-comp prop1="myCompOptions.prop1" prop2="myCompOptions.prop2">
      <another-comp prop="anotherProp">
          <some-content/>
      </another-comp>
  </my-comp>
</div>
```

<b>but resulting DOM won't include wrapping tags: "my-comp" and "another comp" and all the events will be bound to "div" element.</b>

A component can also be attached to custom tags:

```javascript
<some-comp my-comp="myCompOptions"></some-comp>
```

To allow this for components to be injected via attributes they could be declared as:

```javascript
can.Component({
   tag: 'my-component',
   attribute: 'my-component'
   ...
})
```

<h3>Passing attributes</h3>
```HTML
<div my-comp="myCompOptions"></div>
```
Would take myCompoOptions from parent scope and mix (extend) them into my-comp initial scope (with two-way binding)

Or attributes could be passed individually
```HTML
<div my-comp my-comp-prop1="myCompProp1" my-comp-prop2="myCompProp2"></div>
```

<h3>Accessing scopes on the element</h3>
Well can.scope API could be extended to allow this

```javascript
can.scope(element, tagName, attr)
```

if "tagName" fits to one of the "attached" components it will work with corresponding scope if no it will treat "tagName" as "attr" argument and work with default scope.

<h3>Extending component with other components</h3>
As upper suggestions assume actually ability to have several components on the element and some kind of multiple inheritance we could also extend component while definition:

```javascript
can.Component({
    tag: 'some-comp',
    
    attach: [
        {'my-comp': 'myCompOptions'},
        {'another-comp': {
           'prop': 'anotherCompProp'
       }}
    ]

})
```
"attach" property here is an array because the order of injecting of components is significant

so putting

```javascript
<some-comp></some-comp>
```
would be the same as

```javascript
<some-comp my-comp="myCompOptions" another-comp another-comp-prop="anotherCompProp"></some-comp>
```

**Comment by justinbmeyer** [comment]
@whitecolor Do you still support this issue?  Hopefully, `can.view.tag` gives you enough power to be able to mix in behaviors.

The problem with something like:

```
<div my-comp="myCompOptions" another-comp another-comp-prop="anotherProp">
```

Is "who owns" the template?

I think a better solution would be enabling Components that don't have a "template" or "tag" property to be added via `can.view.attr` like:

```
var MyComp = can.Component.extend({
  scope: { ... },
  events: { ... }
});

can.view.attr("my-comp", MyComp);
```

Thoughts?

**Comment by justinbmeyer** [comment]
Related: https://github.com/bitovi/canjs/issues/1376

**Comment by matthewp** [comment]
What is the goal here, why do you want to have components as attributes rather than tags?

**Comment by whitecolor** [comment]
first reaso was to have "headless" components (without wrapping tag), another reason multiple components on one element. I'm not sure if it really appropriate.

**Comment by matthewp** [comment]
Headless components makes sense, I'm not understanding the reason behind multiple though... can.view.attr is great for mixins and #1376 has a way to make a higher-level plugin for those.

**Comment by whitecolor** [comment]
yes multiple components ont a big issue `can.view.attr` can be used, though component propose more robust API (scope, events) for creating comprehansive behaviour model. 

Headless components would be intresting to have though.

**Comment by matthewp** [comment]
I like suggestion here, essentially a component with no tag and no template, allow that to be passed into `can.view.attr`.  What do you think?

**Comment by whitecolor** [comment]
I think this would be fine.

**Comment by justinbmeyer** [comment]
Adding the label can-component.  I'm going to try to run through all component related issues and move them as a group to the can-component repo.  My hope is that I can consolidate some of them.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-stache/issues/15
