### ISSUE TITLE
pushstate default and hashchange as plugin for v3.0?

### ISSUE THREAD

**Issue by stevenvachon** [canjs/canjs#661]
`pushState` is the future.

Also, would be cool if the hashchange plugin could be set to "fallback mode" where it's only used for browsers that do not have `history.pushState`. Along with that, have its hashes converted to states on browsers that do (for incoming links from email, etc).

**Comment by justinbmeyer** [comment]
I think we can do this for 3.0.

**Comment by justinbmeyer** [comment]
So hashchange is still going to be "core" in 3.0 mostly because it's tricky to setup routing without server support like DoneJS has.  I think this will have to continue indefinitely or pending some unforeseen browser technology.  

Closing.
