### ISSUE TITLE
can.route.bind "error" and "ignore" events

### ISSUE THREAD

**Issue by stevenvachon** [canjs/canjs#663]
We need a way of handling URLs that `can.route` is unable to route. These can originate from mis-typed links (in user emails,etc) and outdated links (in marketing material,etc).

# Listening to errors in can.route
Listen for unrelated URLs from links, `history.pushState` and `location.hashchange` with:
```javascript
can.route.bind("error", function(event, url) {
	var loc = window.location;
	if (url.host != loc.host || url.port != loc.port || url.protocol != loc.protocol) {
		console.log("different protocol/host/port");
	}
	else if (can.route.defaultBinding=="pushstate" && url.pathname.indexOf(can.route.bindings.pushstate.root) != 0) {
		console.log("outside app root");
	}
	else if (can.route.defaultBinding=="hashchange" && url.pathname != loc.pathname) {
		console.log("outside app root");
	} else {
		console.log("unrouted");
	}
	//return false;
});
```
**@param** {Event} event
**@param** {URLUtils} data Contains URL information.

Returning `false` in this event will prevent the default behaviour from occurring on links and push states. It will not affect hash changes, however.

# Listening to ignored routes in can.route
Listen for `attr` changes to routes that you've specifically ignored with [`can.route.ignore`](https://github.com/bitovi/canjs/issues/655) with:
```javascript
can.route.bind("ignore", function(event, data) {
	
});
```
**@param** {Event} event
**@param** {Object} data Contains route information.

**I'm thinking that this may be needless, as its purpose can be achieved through use of the `"change"` event.**

**Comment by justinbmeyer** [comment]
Moving to can-route-pushstate
