### ISSUE TITLE
Dev warning when can.Model is extended without static properties.

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/canjs#716]
When `can.Model` is extended without static properties like:

``` js
Todo = can.Model.extend({
  findAll: "GET /todos"
});
```

This is almost always a mistake.  We should warn users with something like:

> can/model/model.js: can.Model extended without static properties.

VOTE FOR THIS FEATURE HERE:  http://bithub.com/event/25835

**Comment by NoICE** [comment]
This helped me discover something unusual. If you do this in canjs 2.2.5:

```js
steal('can/model', 'can/map/attributes', function() {
can.Model.extend('HiThere',
// @Static
{
  attributes: {},
  findAll: function() {
    // doesn't matter
  }
},
// @Prototype
{}
)
})
```

It will throw this error and the model is empty, without definitions. Incomplete. Dead.
But I'm giving it the name, static props and prototype props.

The cause of this is the stealing of can/map/attributes, which breaks it completely and causes it to break. It is deprecated, but it's removed from docs but not from canjs package, so I didn't even knew it was deprecated :-DThis helped me discover something unusual. If you do this in canjs 2.2.5:

```js
steal('can/model', 'can/map/attributes', function() {
can.Model.extend('HiThere',
// @Static
{
  attributes: {},
  findAll: function() {
    // doesn't matter
  }
},
// @Prototype
{}
)
})
```

It will throw this error and the model is empty, without definitions. Incomplete. Dead.
But I'm giving it the name, static props and prototype props.

The cause of this is the stealing of can/map/attributes, which breaks it completely and causes it to break. It is deprecated, but it's removed from docs but not from canjs package, so I didn't even knew it was deprecated :-D
