### ISSUE TITLE
Make new can.Model({id}) check the model-store.

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#721]
Currently, to get something from the store, someone has to use `Model.model()`.  This would make the constructor function look up if there is already an instance.

@whitecolor's original comment:

> I've met a strange bug in my app with current minor branch.

> Some times one of my models disappears from Model.store and that causes new arrived data for the same model (with the same id) to be created again (with another _cid).

> I found out that that this happens due this removal from store:
https://github.com/bitovi/canjs/blob/minor/model/model.js#L1494

> This bug is hard to reproduce, and even in my app I not always get it when I do the same actions. Sometimes after certain operations model from store disappears and some times it is not.

> I don't know what causes this code (_bindteardown) to be executed in my app, but I wonder why something touches Model.store anyway?

**Comment by justinbmeyer** [comment]
Closing for an issue in can-connect.
