### ISSUE TITLE
Feature request: expose __reading on the API

### ISSUE THREAD

**Issue by thomblake** [canjs/canjs#727]
It's nice sometimes to use __reading to manually set up binding on something that is not a can.Map or can.List, but it's obviously the sort of thing that's private and shouldn't be relied upon.  It would be nice if there were a public version of this.

VOTE FOR THIS FEATURE HERE: http://bithub.com/event/25828

**Comment by justinbmeyer** [comment]
This is going to happen in 3.0 here: https://github.com/canjs/can-observe-info
