### ISSUE TITLE
Expose keyboard mappings to allow matching key events besides can-enter.

### ISSUE THREAD

**Issue by thomblake** [canjs/canjs#728]
[VOTE HERE](http://bithub.com/event/25827)

When handling keyboard events, you can check event.which to see what key was pressed, by code.  But the mappings are nicely in canjs / control / modifier / key / key.js but not exposed outside the module.  It would be nice if those were exposed somewhere as constants, like can.keys.ENTER or suchlike, so that app authors don't need to recreate it.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/can-stache-bindings/issues/5
