### ISSUE TITLE
Dev mode should warn when excessive events are being fired

### ISSUE THREAD

**Issue by thomblake** [canjs/canjs#737]
When using can.js dev mode, the developer should get a warning if excessive events are being fired - for example, if a list with 10,000 elements fires 10,000 events and each one updates the mustache view.  Perhaps if events/second is over some threshold.

Raised at the Silicon Valley meetup

**Comment by justinbmeyer** [comment]
@thomblake Interested in taking this on?  I can show you how to add this.

**Comment by justinbmeyer** [comment]
Closing.  Please re-open here if someone is interested in taking this on: https://github.com/canjs/can-event
