### ISSUE TITLE
Move EJS and MUSTACHE into their own project.

### ISSUE THREAD

**Issue by alexisabril** [canjs/canjs#747]
We are going to move mustache and EJS into their own projects for 3.0.

@alexisabril 's original comment:

> Mustache has replaced EJS in CanJS core and will be continuously receiving new features. We do plan on supporting EJS as it stands today for some time(potentially 2+ major versions), however no plans are currently in place for new features.

> This issue is meant as a discussion thread for what the community would like for the future of EJS. Thoughts have bounced around such as an official deprecation, becoming obsolete after CanJS v4.0(2 versions ahead), estimated. Another thought would be to separate EJS from CanJS into it's original form, just an independent view engine, similar to how other popular view engines operate today in isolation.

**Comment by justinbmeyer** [comment]
EJS and Mustache will be put in another project in 3.0.  They will be worked on there.

**Comment by justinbmeyer** [comment]
EJS and Mustache are in https://github.com/canjs/can-ejs https://github.com/canjs/can-mustache
