### ISSUE TITLE
Documentation for the new branch infrastructure

### ISSUE THREAD

**Issue by andykant** [canjs/canjs#781]
Recently, the management for branches [was changed](http://bitovi.com/blog/2014/02/canjs-infrastructure-improvements.html).

In summary:
- **master** is used for patch releases -- intended for bug fixes (like 2.0.6)
- **minor** is used for minor releases -- intended for new features (like 2.1.0)
- **major** is used for major releases -- intended for huge new features and API revamps (like 3.0.0)

The contribution guide should be updated to describe this new structure along with how to use it. Additionally we should document the process for merging branches for releases.

**Comment by justinbmeyer** [comment]
Closing for: https://github.com/canjs/canjs/issues/2392
