### ISSUE TITLE
can.Object.subset is wrong: can.Object.subset({id: 1}, {id: 1, name: 'foo'}) => false

### ISSUE THREAD

**Issue by puppetdoll** [canjs/canjs#796]
```
can.Object.subset = function(subset, set, compares){
	// go through set {type: 'folder'} and make sure every property
	// is in subset {type: 'folder', parentId :5}
	// then make sure that set has fewer properties
	// make sure we are only checking 'important' properties
	// in subset (ones that have to have a value)
	
	var setPropCount =0,
		compares = compares || {};
			
	for(var prop in set){

		if(! same(subset[prop], set[prop], compares[prop], subset, set )  ){
			return false;
		} 
	}
	return true;
}
```

The for loop should iterate over properties of subset, not set.

**Comment by RuslanGetmansky** [comment]
Also has bumped into this bug here:
https://github.com/canjs/canjs/blob/master/util/object/object.js#L160
should be:
```php
for (var prop in subset)
```
I doubt anyone is using it because it doesn't work if a subset contains less properties than a set.

**Comment by justinbmeyer** [comment]
This is heavily used by can/fixture.  A `subset representation` DOES contain less properties than a set.  Btw, this is the future of can.Object: http://github.com/canjs/can-set and explains why much better.

This means that if I compare the `{}` in  `Todo.findAll({})` to `{due: "today"}` in `Todo.findAll({due: "today"})`, `{}` is a superset of `{due: "today"}`, but has less properties.

The object compared here represent a set, they are not the set themselves.

**Comment by RuslanGetmansky** [comment]
@justinbmeyer Probably the concept of can.Object.subset is correct. I don't mind. Then the actual bug is how it's used in [can.Object.subsets](http://canjs.com/docs/can.Object.subsets.html). Because it doesn't work as explained in the doc. For example:
```javascript
can.Object.subsets({id: 1}, [
    {id: 1, name: 'name1'},
    {id: 2, name: 'name2'}
])
```
gives nothing because ```can.Object.subset({id: 1}, {id: 1, name: 'name1'}) === false``` in current implementation.

**Comment by justinbmeyer** [comment]
can.Object is deprecated in favor of [can-set](/canjs/can-set).  Closing.
