### ISSUE TITLE
Add serialize additional option parameter

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#941]
I have cases, where it is necessary to have differently serialized data of the same object for different purposes, for example depending on where data had to be set.

For example scenario where two different sets of data (of the same object) had to be sent on server and in local db. The other example if one wants to send on server only changed properties and in other case full object.

What do you think?

```javascript

...
define: {
    'onlyLocalProperty.serialize': function(val, option) {
         if (option && option == 'local'){
            return val
         }
    }

}
....

map.serialize('local')


```

**Comment by juanmaia** [comment]
+1

**Comment by justinbmeyer** [comment]
I'm adding "needs a hero" label.  I'm happy to help make this happen, but I need a champion to do the heavy lifting.  

Both `can-map` and `can-define/map` use a serialize helper to loop through each property and recursively call `serialize` or some other method on the value if appropriate: 

https://github.com/canjs/can-define/blob/master/map/map.js#L177

The solution to this might be to make a `can-util/js/serializer` which essentially would be a helper that would do something similar, but exposed and documented so everyone could use it.

**Comment by gsmeets** [comment]
You could just make the serialize function depend on another property on the same map. I don't see how this has to be something that canjs has to support natively.

**Comment by justinbmeyer** [comment]
Closing, I'll re-open if someone is going to help.
