### ISSUE TITLE
Restrict scope attributes taken from parent scope

### ISSUE THREAD

**Issue by whitecolor** [canjs/canjs#983]
Not sure how to put it right. Didn't you think about restricting attributes that are taken from parent scope, as it is actually done with '@' attributes?

Now it is possible to pass to scope anything via attributes on the element and it will try to lookup in upper scopes if it can find it.

One of the problems I see with this approach: if I have some special attributes (for example to handle by ```can.view.attr```) setup will try to pass this attributes to scope. (probably not big deal, but its not very efficient)

```HTML
<my-component some-mixin="xxx" .. >
```

So I don't want ```some-mixin``` to be passed to scope (event if it find ```xxx``` attribute somewhere in upper scopes)

Besides passing only attributes that has been predefined in scope will make component's API cleaner (from code perspective).

Api could look like something like this.

```javascript
scope: {
   someParentAtrr: '^',
   someStringAttr: '@'
}
```
And I don't really can figure out were it can be really useful not to have such attributes predefined in scope.

**Comment by justinbmeyer** [comment]
I'm going to close this one and mark it as "needs a hero".  If you'd still like to see this happen, please open an issue in /canjs/can-component .  As the new view bindings are a bit more explicit, I'm hopeful this isn't really much of a problem.
