### ISSUE TITLE
Can.compute doesn't cache when not bound too

### ISSUE THREAD

**Issue by Bajix** [canjs/canjs#995]
A lot of times it's common to build out can.Map's before tying them into much. Unfortunately, when doing this, computes are not bound to anything, and thus fail to return cached values. This gets particularly problematic when returning objects, particularly deferreds.

There is no documentation that expresses when can.Compute will/will not cache values, and it's not obvious that you need to bind a change handler to them for them to work in that manner.

Computes should always cache values, or otherwise the documentation needs to be updated to make this crystal clear.

**Comment by justinbmeyer** [comment]
@rjgotten you could absolutely do that. Closing for an issue in can-compute
